### ISSUE TITLE
软件一致性问题

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#1]
migarate from：https://github.com/winlinvip/simple-rtmp-server/issues/288

**Comment by winlinvip** [comment]
#288 和这个重复。

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/issues/786#issuecomment-283590878
保持简单构造函数，支持empty object行为。以及使用不可重用对象简化逻辑。

**Comment by winlinvip** [comment]
这个#1很容易被引用，还是用#288那个。

**Comment by hothothot90** [comment]
Api

**Comment by hothothot90** [comment]
Bitcoin
