### ISSUE TITLE
srs的time jitter算法的疑问

### ISSUE THREAD

**Issue by jamken** [ossrs/srs#1001]
winlinvip，你好，我们是杭州一家做课堂直录播服务公司，目前正在使用srs2.0作为我们的接入级流服。
我们在review 代码中目前的time jitter算法，感觉此算法会导致严重的时间戳混乱，因此希望请教一下作者的设计意图。目前SrsRtmpJitter对象是每个comsumer拥有自己唯一一个，该SrsRtmpJitter负责同时纠正音频流和视频流两条流内的数据包，该对象有两个成员变量last_pkt_time，last_pkt_correct_time是算法的关键，问题是这两个成员变量并没区分当前记录的是音频流的timestamp，还是视频流的timestamp。因此在某种情况下就会出现混乱情况，大部分的编码器可以保证音频单增，视频单增，假设编码器推送有如下序列的音视频帧：(假设音视频帧率都为25fps）
发送帧序列： V1（ts: 500ms），A1（50）， V2(540),  A2(90), V3( 580), A3(130)

而jitter算法调整的序列改变为： V1(500), A1(510), V2(520), A2(530), V3(540), A4(550)。

不知道我们是否对算法有理解错误。

建议：jitter算法只修复单个音频或者视频轨道中的跳变，保证单个轨道的时间戳单增。而依赖mix_correct（具体我们还未分析，判读应该类似于ffmpeg的利用缓冲队列进行重新排序输出的原理）来保证流单增。

期望回复

**Comment by jamken** [comment]
Adding a point, the above sequence example does not consider the zeroing function of the jitter algorithm. It is only to emphasize that a time variable cannot be shared between the audio and video tracks.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
You can disable time jitter by handling timestamps at the source or encoder, refer to the wiki.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The time jitter algorithms are designed to handle several types of timestamp issues, but they cannot address all problems.

`TRANS_BY_GPT3`
