### ISSUE TITLE
使用http-flv协议，前台请求需要跨域获取flv流，我看过wiki，还没有找到答案，求帮助，谢谢

### ISSUE THREAD

**Issue by hyfsgit** [ossrs/srs#1002]
我在wiki中只看到了http-api中可以跨域，请教一下使用http-flv也可以跨域吗

**Comment by alon21034** [comment]
I face the same problem, too. My workaround is adding 
```
w->header()->set("Access-Control-Allow-Origin", "*");
```
in https://github.com/ossrs/srs/blob/master/trunk/src/app/srs_app_http_stream.cpp#L485 .
Hope it will have an option in the conf file in the future.

**Comment by hyfsgit** [comment]
I resolved the problem with the same way yesterday, thanks for your help

**Comment by canglongxiang** [comment]
@hyfsgit Did you solve this problem by modifying the source code as mentioned above? I am currently facing the same issue.

`TRANS_BY_GPT3`

**Comment by hyfsgit** [comment]
It is the same method as the one used by the person upstairs. Modify the http-conn file and add an additional attribute in the response header.

`TRANS_BY_GPT3`

**Comment by hyfsgit** [comment]
All the same, we are modifying the source code, but we are modifying different files.

`TRANS_BY_GPT3`

**Comment by hyfsgit** [comment]
His method is a little safer, so you should still follow his method to make changes.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
There are several solutions:
1. Add an HTTP proxy: https://github.com/ossrs/go-oryx/tree/develop/httpx-static
2. SRS3 supports CORS, but it is a bit complicated to merge it, so you can directly modify the code to support it, as shown above.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #717 #798 #1002 #1025
