### ISSUE TITLE
Which tools prefer for  programming this project

### ISSUE THREAD

**Issue by thisroot** [ossrs/srs#1013]
Hi i need to extend functionality of this project. Can you advice programming tools (IDE)?
I was try Visual Studio, CLion but this IDEs can't correct work with it. I need autocomplete that get access to data structures.

**Comment by hibate** [comment]
I use clion to edit the code, compile in the shell and run the srs binary, click "run" -> "attach to the local process" and select the srs process, set some breakpoints to debugging

**Comment by winlinvip** [comment]
Use any editor you like. For debuging, use GDB for linux, LLDB for macOS.

**Comment by winlinvip** [comment]
For IDE, use Clion.
