### ISSUE TITLE
Stream Cast服务，无法转发RTSP流问题

### ISSUE THREAD

**Issue by phoenixZZZ** [ossrs/srs#1016]
现在我想利用SRS的Stream Cast功能实现
将设备推送过来的RTSP流，通过Stream Cast，转换为RTMP，客户端拉流进行观看
Stream Cast的conf配置文件：

> listen              1935;
> max_connections     1000;
> daemon              off;
> srs_log_tank        console;
> stream_caster {
>     enabled         on;
>     caster          rtsp;
>     output          rtmp://192.168.1.1/[app]/[stream];
>     listen          554;
>     rtp_port_min    57200;
>     rtp_port_max    57300;
> }
> vhost __defaultVhost__ {
> }

RTSP推流端的推流脚本：

> #!/bin/bash
> for((;;)); do \
>    /usr/local/bin/ffmpeg -re -i /171020085123.mp4 \
>    -vcodec copy -acodec copy \
>    -f rtsp -y rtsp://192.168.1.1/live/livestream.sdp; \
>    sleep 1; \
> done

但是执行后, 无视频画面，服务端的log如下：

> [2017-11-15 03:32:42.097][warn][48845][0][0] check feature compile nginx: off
> [2017-11-15 03:32:42.097][warn][48845][0][0] check feature compile ffmpeg: off
> [2017-11-15 03:32:42.097][trace][48845][0] stream caster: on
> [2017-11-15 03:32:42.097][trace][48845][0] MR(merged-read): on, @see https://github.com/ossrs/srs/issues/241
> [2017-11-15 03:32:42.097][trace][48845][0] MR(merged-read) default 0 sleep 350
> [2017-11-15 03:32:42.097][trace][48845][0] MW(merged-write) default sleep 350
> [2017-11-15 03:32:42.097][trace][48845][0] read chunk stream cache cid [0, 16)
> [2017-11-15 03:32:42.097][trace][48845][0] default gop cache 1, play queue 30s
> [2017-11-15 03:32:42.097][trace][48845][0] complex send algorithm enabled.
> [2017-11-15 03:32:42.097][warn][48845][0][0] TCP_NODELAY enabled, may hurts performance.
> [2017-11-15 03:32:42.097][trace][48845][0] auto guess socket send buffer by merged write
> [2017-11-15 03:32:42.097][trace][48845][0] system default latency in ms: mw(0-350) + mr(0-350) + play-queue(0-30000)
> [2017-11-15 03:32:42.097][trace][48845][0] http: root mount to ./objs/nginx/html
> [2017-11-15 03:32:42.097][trace][48845][0] st_set_eventsys to epoll
> [2017-11-15 03:32:42.097][trace][48845][0] st_init success, use epoll
> [2017-11-15 03:32:42.097][trace][48845][100] server main cid=100, pid=48845, ppid=48844, asprocess=0
> [2017-11-15 03:32:42.097][trace][48845][100] write pid=48845 to ./objs/srs.pid success!
> [2017-11-15 03:32:42.107][trace][48845][100] RTMP listen at tcp://0.0.0.0:1935, fd=7
> [2017-11-15 03:32:42.118][trace][48845][100] RTSP listen at tcp://0.0.0.0:554, fd=8
> [2017-11-15 03:32:42.118][trace][48845][100] signal installed
> [2017-11-15 03:32:42.128][trace][48845][100] http: api mount /console to ./objs/nginx/html/console
> [2017-11-15 03:32:42.138][trace][48845][100] ingest thread cid=104, current_cid=100
> [2017-11-15 03:32:46.003][trace][48845][105] rtsp: serve 60.29.171.162
> [2017-11-15 03:32:46.003][trace][48845][105] rtsp: ignore header User-Agent=Lavf57.56.100
> [2017-11-15 03:32:46.059][trace][48845][105] rtsp: ignore header User-Agent=Lavf57.56.100
> [2017-11-15 03:32:46.159][trace][48845][105] rtsp: video(#0, H264, RTP/AVP/96), audio(#1, , RTP/AVP/8, 0HZ 0channels), rtsp://40.125.170.233:554/live/livestream
> [2017-11-15 03:32:46.225][trace][48845][105] rtsp: ignore header User-Agent=Lavf57.56.100
> [2017-11-15 03:32:46.236][trace][48845][105] rtsp: #0 Video over RTP/AVP/UDP unicast client-port=5202-5203, server-port=57200-57201
> [2017-11-15 03:32:46.304][trace][48845][105] rtsp: ignore header User-Agent=Lavf57.56.100
> [2017-11-15 03:32:46.314][trace][48845][105] rtsp: #1 Audio over RTP/AVP/UDP unicast client-port=5204-5205, server-port=57202-57203
> [2017-11-15 03:32:46.365][trace][48845][105] rtsp: ignore header Range=npt=0.000-
> [2017-11-15 03:32:46.365][trace][48845][105] rtsp: ignore header User-Agent=Lavf57.56.100
> [2017-11-15 03:32:46.907][trace][48845][106] srand initialized the random.
> [2017-11-15 03:32:46.918][trace][48845][109] RTMP client ip=127.0.0.1
> [2017-11-15 03:32:46.921][trace][48845][106] complex handshake success.
> [2017-11-15 03:32:46.921][trace][48845][109] complex handshake success
> [2017-11-15 03:32:46.961][trace][48845][109] connect app, tcUrl=rtmp://127.0.0.1/live, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=1935, app=live, args=(obj)
> [2017-11-15 03:32:46.961][trace][48845][109] edge-srs ip=10.0.0.4, version=2.0.243, pid=48845, id=106
> [2017-11-15 03:32:47.001][trace][48845][106] connected, version=2.0.243, ip=127.0.0.1, pid=48845, id=109, dsu=1
> [2017-11-15 03:32:47.001][trace][48845][106] protocol in.buffer=0, in.ack=2500000, out.ack=2500000, in.chunk=60000, out.chunk=60000
> **#[2017-11-15 03:32:47.001][error][48845][106][11] stream param size must be positive. ret=3038(Resource temporarily unavailable)
> [2017-11-15 03:32:47.001][error][48845][106][11] rtsp: process rtp packet failed. ret=3038(Resource temporarily unavailable)**
> [2017-11-15 03:32:47.001][warn][48845][106][11] handle udp packet failed. ret=3038
> [2017-11-15 03:32:47.001][warn][48845][106][11] thread udp cycle failed, ignored and retry, ret=3038
> [2017-11-15 03:32:47.041][trace][48845][109] client identified, type=flash-publish, stream_name=livestream, duration=-1.00
> [2017-11-15 03:32:47.061][trace][48845][109] source url=/live/livestream, ip=127.0.0.1, cache=1, is_edge=0, source_id=-1[-1]
> [2017-11-15 03:32:47.072][trace][48845][109] start publish mr=0/350, p1stpt=20000, pnt=5000, tcp_nodelay=0, rtcid=112
> [2017-11-15 03:32:47.072][trace][48845][112] protocol in.buffer=0, in.ack=2500000, out.ack=2500000, in.chunk=60000, out.chunk=60000
> [2017-11-15 03:32:47.072][trace][48845][109] 29B video sh,  codec(7, profile=Baseline, level=3.1, 1280x720, 0kbps, 0fps, 0s)
> [2017-11-15 03:32:56.174][trace][48845][106] <- SCS rtsp: rtp #0 598B, age=10000, vt=2/96, sts=652/2042675141/0x66654fe7, paylod=586B, chunked=0

RTSP推流使用的是ffmpeg 3.3版本
SRS使用的2.0版本，编译时选择了“./configure --with-stream-caster” 
附件中是我们的测试程序，请各位大神帮忙看一下，多谢多谢
[171024131425.mp4.zip](https://github.com/ossrs/srs/files/1473362/171024131425.mp4.zip)

**Comment by atlantis414** [comment]
我有相同的问题

**Comment by jiyeyuran** [comment]
我也有相同的问题

**Comment by joke-lee** [comment]
same problem

**Comment by winlinvip** [comment]
Need to replay this bug.

**Comment by hipitt** [comment]
@winlinvip 求解..

**Comment by winlinvip** [comment]
Dup to #1500
