### ISSUE TITLE
Record mp4 or a method to trigger transcode after recording

### ISSUE THREAD

**Issue by danionescu2007** [ossrs/srs#1023]
Is there a way to directly record mp4 to file or at least to trigger a command line in order to convert it to mp4?
Is this a feature you would consider to implement if missing?

Thank you and thank you for your great work on srs.
Regards, 
Dan

**Comment by wnpllrzodiac** [comment]
use dvr callback hook?
you can call ffmpeg to do convert job in server.py

**Comment by winlinvip** [comment]
For SRS2, you can use FFMPEG to transcode the DVR file and you can setup a callback so that you could know the file is ready.

For SRS3, it supported DVR to mp4. BUT SRS3 is not released yet.

**Comment by winlinvip** [comment]
Fixed.
