### ISSUE TITLE
Origin [...] is not allowed by Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by danionescu2007** [ossrs/srs#1025]
I am trying to use a html5 player (videojs) for hls playback from a srs 2.0.243. Althought this in one machine install (same host) for both the Apache web server and SRS, in browser console it complains about:
```
Failed to load resource: Origin http://172.16.1.238 is not allowed by Access-Control-Allow-Origin.
http://172.16.1.238:8080/live/5a0f8610e8ee6/index.m3u8
```

I enabled CORS in Apache, but I cannot find a way to enable it also in SRS.
Can anyone shed some lite, please.
Thank you,
Dan

**Comment by winlinvip** [comment]
Well, you can use a HTTP proxy which enable js CORS: https://github.com/ossrs/go-oryx/tree/develop/httpx-static

**Comment by danionescu2007** [comment]
Thank you for your suggestion.

Regards,
Dan

**Comment by winlinvip** [comment]
Dup to #717 #798 #1002 #1025
