### ISSUE TITLE
srs_player.html 不能播放视频流

### ISSUE THREAD

**Issue by keith2008** [ossrs/srs#1026]
请问我安装了srs后，访问
http://XXX.XXX.XXX.XXX:8080/players/srs_player.html
设置流的路径后，不能播放流，控制台输出：stream is null, ignore timer event.

而使用
http://www.ossrs.net/players/srs_player.html
设置流的路径后，却可以播放流。

**Comment by 799677446** [comment]
请问这个问题是如何处理的，我现在也碰到同样的问题

**Comment by winlinvip** [comment]
Player issue.

**Comment by kedi-z** [comment]
不是最新版本？
