### ISSUE TITLE
srs请教

### ISSUE THREAD

**Issue by zhengbin1015** [ossrs/srs#1035]
当有客户端请求play时，srs是如果发送'F','L','V'这个头的，我没有打到源码，希望得到帮助，因为想把这个头改成别的，‘F','L','V'这个头跨网（联通，移动）会被限制

**Comment by wnpllrzodiac** [comment]
这个是flv文件头标志啊，改了，播放器就不认了

**Comment by zhengbin1015** [comment]
播放器没事，这边可以自己改

**Comment by winlinvip** [comment]
找找代码可以改的哦。
