### ISSUE TITLE
低延迟模式 画面fps很不稳定

### ISSUE THREAD

**Issue by disword** [ossrs/srs#1036]
我用了几个srs red5 测试了下  srs red5低延迟很不错  但是用ffplay -fflags nobuffer 播放  ,red5 画面很稳定 但是本身不支持edge server, srs画面帧数抖动很严重 , 试了几个参数没变化 请问应该从哪些参数优化？

**Comment by winlinvip** [comment]
SRS会尽快发包降低延迟，所以解码时FPS可能不稳定，这个问题只能改播放器，如果播放器不能改只能增加缓冲时间增加延迟，比如500ms延迟一般比200ms延迟稳定。
