### ISSUE TITLE
srs-librtmp开发播放器的问题

### ISSUE THREAD

**Issue by qingkouwei** [ossrs/srs#1046]
基于srs-librtmp与mediacodec开发的android rtmp播放器srs-librtmp
编译完有500k左右,是否还有可以删减的模块?
https://github.com/qingkouwei/oarplayer

**Comment by wnpllrzodiac** [comment]
ffmpeg only keeps demux. Even after simplification, it's still around 300-500k.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍

**Comment by qingkouwei** [comment]
> 👍

Brother, I'm ready to maintain this repository. Can I post it in https://github.com/ossrs/srs/wiki/v3_CN_ClientSDK?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It's easy to start, but difficult to persist. I see that oarplayer is no longer being maintained.

Clients, everyone should obediently use FFmpeg and bow down to the master.

`TRANS_BY_GPT3`

**Comment by qingkouwei** [comment]
> It's easy to start, but difficult to persist. I see that oarplayer is no longer being maintained.
> 
> Clients, everyone should obediently use FFmpeg and bow down to the master.

> Indeed, the application scenarios are too few~

`TRANS_BY_GPT3`
