### ISSUE TITLE
publish will cause memory leak

### ISSUE THREAD

**Issue by jasamu** [ossrs/srs#1047]
版本：SRS v2.0.243
參照 trunk/research/librtmp/srs_h264_raw_publish.c 開發publisher 程式
但在執行時發現 vm.drop_caches 後free memory 會愈來愈少
最後找到是因為當host 收到message 後，on_recv_message 會回 acknowledgement message
但因為publish 中並未receive message，所以buffer usage 會一直增加

解決方法：
在publish 中開一個thread 去一直呼叫 srs_rtmp_read_packet 即可解決

**Comment by juntaoliu** [comment]
在Publish结束之后，这个是不是就释放了？？还是说publish结束，这个内存泄漏也一直存在？

**Comment by jasamu** [comment]
結束後會釋放

**Comment by juntaoliu** [comment]
如果结束后会释放，那这个问题看上去也不是特别大的问题；除非是碰到那种一推几十天不结束的流。
