### ISSUE TITLE
unsupported vhost directive  stream_caster

### ISSUE THREAD

**Issue by nick950222** [ossrs/srs#1053]
version : 2.0.205
description:
i wrote  something like ：
stream_caster {
    enabled         on;
    caster          mpegts_over_udp;
    output          rtmp://127.0.0.1/live/livestream;
    listen          1935;
}
in the conf ，but when i start srs , it doesn't work , and the log file says  "unsupported vhost directive  stream_caster". What's wrong?

**Comment by winlinvip** [comment]
Use SRS3.
