### ISSUE TITLE
3.0版本srs_h264_raw_publish存在问题

### ISSUE THREAD

**Issue by luofuchong** [ossrs/srs#1054]
SRS 3.0版本的srs_h264_raw_publish，连接srs时提示“simple handshake failed.”错误，切换回SRS 2.0版本的srs和srs_h264_raw_publish就没问题。另外，如果用ffmpeg搭配3.0版本的srs也没问题，怀疑是3.0版本的srs_h264_raw_publish本身的问题。

**Comment by Liu-Tommy** [comment]
hello,luofuchong.Where can I download SRS3？

**Comment by winlinvip** [comment]
Fixed.
