### ISSUE TITLE
V2.0.43 推送后http-flv 请求30左右才能看到画面

### ISSUE THREAD

**Issue by jfward001** [ossrs/srs#1056]
V2.0.43 推送后http-flv 请求30左右才能看到画面（每次推流都是一样的），不知道是哪儿的配置问题

**Comment by wnpllrzodiac** [comment]
On the configuration file and streaming parameters, also, are you a pure audio stream?

`TRANS_BY_GPT3`

**Comment by atlantis414** [comment]
https://github.com/ossrs/srs/wiki/v2_CN_LowLatency  This can be referred to for GOP-Cache.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@atlantis414 👍
