### ISSUE TITLE
能更新一下fdk-aac的版本么

### ISSUE THREAD

**Issue by PMExtra** [ossrs/srs#1060]
我正在做 srs 的 docker-ci (#1061)，目前遇到一个问题，`--with-ffmpeg` 在 debian 下构建时，fdk-aac 会编译失败，构建日志详见 [https://hub.docker.com/r/pm9551/srs/builds/b6cxmrrijksbbkrhzfahyng/](https://hub.docker.com/r/pm9551/srs/builds/b6cxmrrijksbbkrhzfahyng/) 。

这个问题在 debian 官方的 bug 跟踪系统里也有记录：[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836933](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836933)

说是新版本的 fdk-aac 修复了这个问题。因此希望能更新 2.0release 和 3.0release 的 fdk-aac 依赖。

**Comment by PMExtra** [comment]
#1061

**Comment by winlinvip** [comment]
Please submit a PR to update FDK-AAC, but only update for SRS3. Please submit it to the 3.0release branch.

`TRANS_BY_GPT3`
