### ISSUE TITLE
docker ci 支持

### ISSUE THREAD

**Issue by PMExtra** [ossrs/srs#1061]
我正在尝试做 SRS 的 docker ci

希望得到官方的承认，如果可以，希望能把此项目转让给官方。

github: [https://github.com/PMExtra/docker-srs](https://github.com/PMExtra/docker-srs)

dockerhub: [https://hub.docker.com/r/pm9551/srs](https://hub.docker.com/r/pm9551/srs)

**Comment by PMExtra** [comment]
Discovered that the official team once made a Docker image in SRS 1.0 version, but I wonder why they later abandoned it?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Mainly because there is no time to maintain multiple projects. Feel free to submit a PR at https://github.com/ossrs/srs-docker.

`TRANS_BY_GPT3`

**Comment by wony-zheng** [comment]
I use Docker to run SRS, but every time I call DVR, the container crashes. SRS is not inherently compatible with Docker, and its restart mode conflicts with Docker.

`TRANS_BY_GPT3`

**Comment by PMExtra** [comment]
@wony-zheng Turn off the srs daemon, and then add --restart always to the docker run command

`TRANS_BY_GPT3`

**Comment by PMExtra** [comment]
@winlinvip If you plan to do CI, I suggest adding Docker support directly within this project. This way, triggering builds based on branches and tags is the simplest approach. If you use a separate build script to complete the build, you will need to set up a webhook and ensure that the CI platform supports setting environment variables through webhooks, which complicates matters.

`TRANS_BY_GPT3`

**Comment by objnf-dev** [comment]
I submitted a PR, feel free to refer to it.

`TRANS_BY_GPT3`

**Comment by PMExtra** [comment]
@zhouweitong3 Thank you for your contribution, but I feel like you have submitted too many things that are unrelated to the core functionality of SRS, even including your own certificate. This seems more like your personal exclusive image rather than an official image for the community users.

Currently, my building method is based on the official Docker images of several large open-source projects, including nginx/redis, and it also supports managing multiple image versions. However, it requires manual maintenance.

![image](https://user-images.githubusercontent.com/11289158/38204369-501a414e-3668-11e8-83f7-a8484506f52a.png)

![image](https://user-images.githubusercontent.com/11289158/38204287-f21e34ce-3667-11e8-9a9c-142165570121.png)

`TRANS_BY_GPT3`

**Comment by objnf-dev** [comment]
Thank you for the feedback~
Actually, that certificate is a sample certificate issued by localhost to localhost, valid until 2099.
The purpose is to test the use of HTTPS.

I still feel that yours is more professional~
I have already starred it~

`TRANS_BY_GPT3`

**Comment by PMExtra** [comment]
@zhouweitong3 Generally speaking, Docker images should not include sample certificates. You can refer to the way nginx configures certificates.

`TRANS_BY_GPT3`

**Comment by wony-zheng** [comment]
@PMExtra restart is useless, I tested and found that the previous streaming has already been disconnected and the recording files are also lost. Even if it restarts, it's not what I want for SRS. I have already given up on the docker mode and now using the service mode.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@PMExtra @zhouweitong3 Can SRS docker submit PR to https://github.com/ossrs/srs-docker? Is this PR https://github.com/ossrs/srs-docker/pull/6 submitted by you?

`TRANS_BY_GPT3`

**Comment by PMExtra** [comment]
@winlinvip I haven't submitted a PR yet, and I haven't maintained the version for a while. I'll find some time to work on it soon.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍

**Comment by PMExtra** [comment]
After trying, submitting a pull request is not an appropriate solution because my repository is not a fork of ossrs/srs-docker and has very little similarity to it. Furthermore, my project relies on WebHook to achieve automatic building, and a significant part of its value lies in the Docker Cloud configuration I have made, not just the content in the git project. Therefore, I cannot merge my project into ossrs/srs-docker.

I believe the best approach is to directly add my build script to the ossrs/srs project itself and configure a webhook. This way, we can rely on the release tag of this project to trigger automatic builds, avoiding the need for separate maintenance.

The alternative solution is to transfer the PMExtra/docker-srs project directly to ossrs. However, this would require someone to manually push tags to maintain versions.

The final solution is:
If you insist on using the current build method and are unwilling to use my automated build, then you can copy the source code from my project and modify it yourself. I am willing to give up all rights.

`TRANS_BY_GPT3`

**Comment by PMExtra** [comment]
<img width="1280" alt="qq20180805-220025 2x" src="https://user-images.githubusercontent.com/11289158/43686584-f9ccc816-98fa-11e8-9b2b-8e228f69d010.png">

Promote a wave, just maintained the recent version, currently in the queue for building.
Other users who are interested in this PR can go to https://hub.docker.com/r/pm9551/srs/ to use it.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I will simply shut down srs-docker and then connect it to your project.

`TRANS_BY_GPT3`

**Comment by PMExtra** [comment]
Then I will transfer ownership to you, and you can give me a contributor role so that I can continue to participate in maintenance. This would be better.
Also, the current Docker Hub account for publishing images is under my personal name, but I noticed there is an ossrs Docker account. I hope we can use the official account for publishing.
Could you please add me on QQ for convenient and instant communication? My QQ number is 1304445713.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Sure, I will add you as an owner. You can directly submit it to srs-docker. Please add me on WeChat: winterserver. If you need any other information, you can contact me.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I have added you as the Owner of https://github.com/ossrs/srs-docker. You can define how to maintain this project on your own.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #1595
