### ISSUE TITLE
第三方依赖项的管理方式

### ISSUE THREAD

**Issue by PMExtra** [ossrs/srs#1062]
我正在尝试做 SRS 的 docker ci (#1061)
过程中发现一个问题，srs的源码包非常庞大。
我不太明白为什么要把所有第三方依赖包以 zip 形式存放于 srs 的 repo 中。
感觉更合理的方式应该是在编译过程中，从各个第三方的仓库下载代码，或者将第三方的 repo 作为 submodule 引入。

**Comment by winlinvip** [comment]
As much as possible, the source code should not rely on network downloads.

`TRANS_BY_GPT3`
