### ISSUE TITLE
chrome浏览器上，用flv.js不能播放

### ISSUE THREAD

**Issue by 995518790** [ossrs/srs#1064]
ffmpeg推流，srs启动http.flv.live.conf，解决跨域问题，在windows的chrome浏览器上，用flv.js最简单的demo，不能播放，network的请求时间条越来越长，貌似在下载整个视频文件。求大神帮忙，急！

**Comment by man201601** [comment]
我觉得，可以用2.0解决跨域的方法+nginx 跨域，这样会好的多！

2018-02-05 15:25 GMT+08:00 995518790 <notifications@github.com>:

**Comment by winlinvip** [comment]
Need more information, please read:
https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion#file-issue
or
https://github.com/ossrs/srs/wiki/v1_EN_HowToAskQuestion#file-issue

**Comment by winlinvip** [comment]
Fixed
