### ISSUE TITLE
Disable -Werror for http parser.

### ISSUE THREAD

**Issue by ocktech** [ossrs/srs#1065]
I am getting this error when installing on ubuntu 17.10.

build http-parser-2.1
patching file Makefile
cc -I. -DHTTP_PARSER_STRICT=1  -Wall -Wextra -Werror -O0 -g  -c http_parser.c
http_parser.c: In function ‘http_parser_parse_url’:
http_parser.c:2093:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
         found_at = 1;
         ~~~~~~~~~^~~
http_parser.c:2096:7: note: here
       case s_req_server:
       ^~~~
cc1: all warnings being treated as errors
Makefile:40: recipe for target 'http_parser.o' failed
make: *** [http_parser.o] Error 1
build http-parser-2.1 failed, ret=2

**Comment by Daniate** [comment]
You should change the source code:

the file `http_parser.c` in 3rdparty/http-parser-2.1.zip

change
```
case s_req_server_with_at:
        found_at = 1;

      /* FALLTHROUGH */
```
to
```
case s_req_server_with_at:
        found_at = 1;

      /* fall through */
```

**Comment by Daniate** [comment]
The better solution is change gcc g++ version to 4.8

```
sudo apt install gcc-4.8 g++-4.8
```
In the `/usr/bin` dir，change the symbolic links:

```
lrwxrwxrwx 1 root root    7 3月  29 12:33 gcc -> gcc-4.8
-rwxr-xr-x 1 root root 755K 9月  14  2017 gcc-4.8
lrwxrwxrwx 1 root root   22 2月   3 09:20 gcc-7 -> x86_64-linux-gnu-gcc-7
lrwxrwxrwx 1 root root   10 3月  29 12:34 gcc-ar -> gcc-ar-4.8
-rwxr-xr-x 1 root root  27K 9月  14  2017 gcc-ar-4.8
lrwxrwxrwx 1 root root   25 2月   3 09:20 gcc-ar-7 -> x86_64-linux-gnu-gcc-ar-7
lrwxrwxrwx 1 root root   10 3月  29 12:34 gcc-nm -> gcc-nm-4.8
-rwxr-xr-x 1 root root  27K 9月  14  2017 gcc-nm-4.8
lrwxrwxrwx 1 root root   25 2月   3 09:20 gcc-nm-7 -> x86_64-linux-gnu-gcc-nm-7
lrwxrwxrwx 1 root root   14 3月  29 12:34 gcc-ranlib -> gcc-ranlib-4.8
-rwxr-xr-x 1 root root  27K 9月  14  2017 gcc-ranlib-4.8
lrwxrwxrwx 1 root root   29 2月   3 09:20 gcc-ranlib-7 -> x86_64-linux-gnu-gcc-ranlib-7
```

```
lrwxrwxrwx 1 root root    7 3月  29 12:35 g++ -> g++-4.8
-rwxr-xr-x 1 root root 759K 9月  14  2017 g++-4.8
lrwxrwxrwx 1 root root   22 2月   3 09:20 g++-7 -> x86_64-linux-gnu-g++-7
```

**Comment by winlinvip** [comment]
Dup for #1159.

**Comment by jgbaldwin3** [comment]
I had the configure failed when compile on Ubuntu Studio 18.04, with line # 2095 of "http-parser-2.1/http_parser.c" where the comment was FALLTROUGH and not FALLTHROUGH, note the first "H" is missing.

For the user that may know how to update the source in the zip file, the following commands show how I did it and verified it working:

cd ~ && git clone https://github.com/ossrs/srs && cd srs/trunk
./configure && make

===> configure FAILS -- update http-parser source zip file

mkdir temp
cd temp
unzip ../http-parser-2.1.zip 
grep -n "FALLT" ./http-parser-2.1/http_parser.c
sed -e s/FALLTROUGH/FALLTHROUGH/ -i ./http-parser-2.1/http_parser.c
grep -n "FALLT" ./http-parser-2.1/http_parser.c
mv ../http-parser-2.1.zip ../http-parser-2.1-orig.zip
zip ../http-parser-2.1.zip http-parser-2.1/*

===> back to srs/trunk folder to configure and make

cd ../..
./configure && make

===> test

./objs/srs -c conf/srs.conf
tail -f ./objs/srs.log
ps -aF

**Comment by huanghe2015** [comment]
With the help of the original poster, I will also share my setup situation (Ubuntu 18.04):
<pre><font color="#8AE234"><b>deploy@ubuntu</b></font>:<font color="#729FCF"><b>~/SRS/srs-2.0-r4/trunk</b></font>$ ./configure --full &amp;&amp; make
regenerate config: --prefix=/usr/local/srs --with-hls --with-hds --with-dvr --with-nginx --with-ssl --with-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --with-stream-caster --with-http-api --with-librtmp --with-research --with-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace
check gcc/g++/gdb/make
depends tools are ok
Ubuntu detected, install tools if needed
install libtool
Reading package lists... Done
Analyzing dependency tree for packages
Reading status information... Done
libtool is already the newest version (2.4.6-2).
0 upgraded, 0 newly installed, 0 to remove, and 0 not upgraded.
W: --force-yes is deprecated, use options starting with --allow instead.
install libtool success
Ubuntu install tools success
SED is sed_utility
st-1.9t is ok.
build http-parser-2.1
patching file Makefile
cc -I. -DHTTP_PARSER_STRICT=1  -Wall -Wextra -Werror -O0 -g  -c http_parser.c
**http_parser.c:** In function '**http_parser_parse_url**':
<b>http_parser.c:2093:18:</b> <font color="#EF2929"><b>error: </b></font>this statement may fall through [<font color="#EF2929"><b>-Werror=implicit-fallthrough=</b></font>]
         <font color="#EF2929"><b>found_at = 1</b></font>;
         <font color="#EF2929"><b>~~~~~~~~~^~~</b></font>
<b>http_parser.c:2096:7:</b> <font color="#34E2E2"><b>note: </b></font>here
       <font color="#34E2E2"><b>case</b></font> s_req_server:
       <font color="#34E2E2"><b>^~~~</b></font>
cc1: all warnings being treated as errors
Makefile:40: recipe for target &apos;http_parser.o&apos; failed
make: *** [http_parser.o] Error 1
build http-parser-2.1 failed, ret=2
<font color="#8AE234"><b>deploy@ubuntu</b></font>:<font color="#729FCF"><b>~/SRS/srs-2.0-r4/trunk</b></font>$ 
</pre>

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
We don't need the `-Werror` to compile the http parser.

**Comment by winlinvip** [comment]
SRS3 has no problem. We don't plan to solve the compilation issue in SRS2, so everyone needs to handle it themselves.

`TRANS_BY_GPT3`

**Comment by huanghe2015** [comment]
Then remember to release the new version as soon as possible! @winlinvip

`TRANS_BY_GPT3`

**Comment by fannigurt** [comment]
**SRS3没有问题。SRS2不打算解决编译问题了，需要大家自己处理下。**

**Translation:**

There is no problem with SRS3. SRS2 does not intend to solve the compilation problem, you need to handle it yourself.
So don't forget to 
`git checkout 3.0release` after the cloning repo

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/a554dd85e110ca4ce9ec35423c9886edaff90371 in 2.0.263

**Comment by huanghe2015** [comment]
Looks like many similiar errors:
There are too many similarities:
<pre><b>src/core/ngx_murmurhash.c:</b> In function '<b>ngx_murmur_hash2</b>':
<b>src/core/ngx_murmurhash.c:37:11:</b> <font color="#EF2929"><b>error: </b></font>this statement may fall through [<font color="#EF2929"><b>-Werror=implicit-fallthrough=</b></font>]
         <font color="#EF2929"><b>h ^= data[2] &lt;&lt; 16</b></font>;
         <font color="#EF2929"><b>~~^~~~~~~~~~~~~~~~</b></font>
<b>src/core/ngx_murmurhash.c:38:5:</b> <font color="#34E2E2"><b>note: </b></font>here
     <font color="#34E2E2"><b>case</b></font> 2:
     <font color="#34E2E2"><b>^~~~</b></font>
<b>src/core/ngx_murmurhash.c:39:11:</b> <font color="#EF2929"><b>error: </b></font>this statement may fall through [<font color="#EF2929"><b>-Werror=implicit-fallthrough=</b></font>]
         <font color="#EF2929"><b>h ^= data[1] &lt;&lt; 8</b></font>;
         <font color="#EF2929"><b>~~^~~~~~~~~~~~~~~</b></font>
<b>src/core/ngx_murmurhash.c:40:5:</b> <font color="#34E2E2"><b>note: </b></font>here
     <font color="#34E2E2"><b>case</b></font> 1:
     <font color="#34E2E2"><b>^~~~</b></font>
cc1: all warnings being treated as errors
objs/Makefile:429: recipe for target &apos;objs/src/core/ngx_murmurhash.o&apos; failed
</pre>

`TRANS_BY_GPT3`

**Comment by xuie0000** [comment]
> SRS3 has no problem. We don't plan to solve the compilation issue for SRS2, so everyone needs to handle it themselves.

> I switched to compiling 3.0 release, but I still encounter an nginx error (this error is caused by the -Werror flag added to the nginx configuration on Ubuntu 18.04) ... I used `./configure --with-nginx && make`.

`TRANS_BY_GPT3`

**Comment by xuie0000** [comment]
For each configuration compilation of ngnix, `-Werror` will be automatically added. Modify this part to disable the decompression, and it should work normally after the change!
```
diff --git a/trunk/auto/depends.sh b/trunk/auto/depends.sh
index 63e9f707..245c99d9 100755
--- a/trunk/auto/depends.sh
+++ b/trunk/auto/depends.sh
@@ -515,9 +515,12 @@ if [ $__SRS_BUILD_NGINX = YES ]; then
     else
         echo "Building nginx-1.5.7";
         (
-            rm -rf ${SRS_OBJS}/nginx-1.5.7 && cd ${SRS_OBJS} && 
-            unzip -q ../3rdparty/nginx-1.5.7.zip && cd nginx-1.5.7 && 
-            ./configure --prefix=`pwd`/_release && make ${SRS_JOBS} && make install &&
+            #rm -rf ${SRS_OBJS}/nginx-1.5.7 && 
+	    cd ${SRS_OBJS} && 
+            #unzip -q ../3rdparty/nginx-1.5.7.zip && 
+	    cd nginx-1.5.7 && 
+            #./configure --prefix=`pwd`/_release && 
+	    make ${SRS_JOBS} && make install &&
             cd .. && rm -rf nginx && ln -sf nginx-1.5.7/_release nginx
         )
     fi
```

`TRANS_BY_GPT3`

**Comment by weldevan** [comment]
I did all the process on a virtual machine, opened test ports and the ports are open, but when I connect to the server, it gives me this error.
---------------------------
Failed to connect
---------------------------
Failed to connect to Server

The connection timed out. Make sure you have set up a valid broadcast service and no firewall is blocking the connection.
---------------------------
OK
https://prnt.sc/p2t03q
https://prnt.sc/p2t2as
firewall ports are open

`TRANS_BY_GPT3`

**Comment by weldevan** [comment]
How do I install it on a VPS?

`TRANS_BY_GPT3`

**Comment by hanxinle** [comment]
build srs1.0relese met this problem. I solved it by the follow method:
Change Makefile in 3rdparty/http-parser-2.1.zip，delete -Werror in CFLAGS.

**Comment by hanxinle** [comment]
build srs1.0relese met this error. I solved it by :
Change Makefile in 3rdparty/http-parser-2.1.zip by delete -Werror in the line start with "CFLAGS".

then, 
both ./configure and make  OK.
