### ISSUE TITLE
ubuntu 16.04server开机启动无效？

### ISSUE THREAD

**Issue by xugaoxiang** [ossrs/srs#1069]
你好，在ubuntu 16.04server上编译srs release 2.0r0， 创建了软连接文件/etc/init.d/srs，手动测试sudo /etc/init.d/srs start/stop/restart都没有问题，但是系统重启后不起作用？

**Comment by RocFang** [comment]
你这个问题跟srs没关系..
开机启动和服务脚本两码事，google一下linux开机启动
