### ISSUE TITLE
build failed on ubuntu 16

### ISSUE THREAD

**Issue by quickstreamingmedia** [ossrs/srs#1073]
make[2]: Entering directory '/root/srs/trunk'
g++ -c -ansi -Wall -g -O0 -fPIC  -Isrc/app -Isrc/core  -Isrc/kernel  -Isrc/protocol  -Iobjs/st -Iobjs/hp -Iobjs/openssl/include -Iobjs \
          -o objs/src/app/srs_app_http_conn.o src/app/srs_app_http_conn.cpp
src/app/srs_app_http_conn.cpp: In constructor ‘SrsHttpServer::SrsHttpServer(SrsServer*)’:
src/app/srs_app_http_conn.cpp:1346:46: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     http_stream = new SrsHttpStreamServer(svr);
                                              ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1347:46: error: invalid use of incomplete type ‘class SrsHttpStaticServer’
     http_static = new SrsHttpStaticServer(svr);
                                              ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: note: forward declaration of ‘class SrsHttpStaticServer’
 class SrsHttpStaticServer;
       ^
In file included from src/app/srs_app_http_conn.hpp:31:0,
                 from src/app/srs_app_http_conn.cpp:24:
src/app/srs_app_http_conn.cpp: In destructor ‘virtual SrsHttpServer::~SrsHttpServer()’:
src/app/srs_app_http_conn.cpp:1352:15: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     srs_freep(http_stream);
               ^
src/core/srs_core.hpp:105:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp:1352:15: warning: invalid use of incomplete type ‘class SrsHttpStreamServer’
     srs_freep(http_stream);
               ^
src/core/srs_core.hpp:105:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
In file included from src/app/srs_app_http_conn.hpp:31:0,
                 from src/app/srs_app_http_conn.cpp:24:
src/app/srs_app_http_conn.cpp:1352:15: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     srs_freep(http_stream);
               ^
src/core/srs_core.hpp:105:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp:1353:15: warning: possible problem detected in invocation of delete operator: [-Wdelete-incomplete]
     srs_freep(http_static);
               ^
src/core/srs_core.hpp:105:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp:1353:15: warning: invalid use of incomplete type ‘class SrsHttpStaticServer’
     srs_freep(http_static);
               ^
src/core/srs_core.hpp:105:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: note: forward declaration of ‘class SrsHttpStaticServer’
 class SrsHttpStaticServer;
       ^
In file included from src/app/srs_app_http_conn.hpp:31:0,
                 from src/app/srs_app_http_conn.cpp:24:
src/app/srs_app_http_conn.cpp:1353:15: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     srs_freep(http_static);
               ^
src/core/srs_core.hpp:105:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::initialize()’:
src/app/srs_app_http_conn.cpp:1367:27: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     if ((ret = http_stream->initialize()) != ERROR_SUCCESS) {
                           ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1371:27: error: invalid use of incomplete type ‘class SrsHttpStaticServer’
     if ((ret = http_static->initialize()) != ERROR_SUCCESS) {
                           ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: note: forward declaration of ‘class SrsHttpStaticServer’
 class SrsHttpStaticServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::serve_http(ISrsHttpResponseWriter*, ISrsHttpMessage*)’:
src/app/srs_app_http_conn.cpp:1381:20: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     if (http_stream->mux.can_serve(r)) {
                    ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1382:27: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
         return http_stream->mux.serve_http(w, r);
                           ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1385:23: error: invalid use of incomplete type ‘class SrsHttpStaticServer’
     return http_static->mux.serve_http(w, r);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: note: forward declaration of ‘class SrsHttpStaticServer’
 class SrsHttpStaticServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::http_mount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1390:23: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     return http_stream->http_mount(s, r);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual void SrsHttpServer::http_unmount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1395:16: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     http_stream->http_unmount(s, r);
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
objs/Makefile:198: recipe for target 'objs/src/app/srs_app_http_conn.o' failed
make[2]: *** [objs/src/app/srs_app_http_conn.o] Error 1
make[2]: Leaving directory '/root/srs/trunk'
Makefile:37: recipe for target 'server' failed
make[1]: *** [server] Error 2
make[1]: Leaving directory '/root/srs/trunk'
Makefile:8: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by quickstreamingmedia** [comment]
dir /usr/local/srs
make the http root dir
copy binary files
cp: cannot stat 'objs/srs': No such file or directory
Makefile:72: recipe for target 'install' failed
make: *** [install] Error 1


make ok with 2.0 branch now new issue

**Comment by quickstreamingmedia** [comment]
its solved

**Comment by qibinghua** [comment]
> its solved

How to?
