### ISSUE TITLE
able to achieve low latency around 1 sec

### ISSUE THREAD

**Issue by quickstreamingmedia** [ossrs/srs#1075]
1-3 sec but if i want <1 sec what should i do

**Comment by wnpllrzodiac** [comment]
give up using srs. rtc meet your requirement.

**Comment by winlinvip** [comment]
RTMP/HTTP/FLV/HLS are based on TCP. The latency is introduced by encoder, player and transport protocol TCP. I think it's impossible to get <1s latency. You should choose WebRTC for N ms latency.
