### ISSUE TITLE
请问Ingest采集与Stream Caster有什么区别？

### ISSUE THREAD

**Issue by Novalife** [ossrs/srs#1079]
我现在想从海康的网络摄像机取rtsp，转成rtmp，推送到srs2.0，新手望解答。

**Comment by azMallco** [comment]
解决了不 哥们

**Comment by Novalife** [comment]
已经解决了，但是有一点，转出的HLS在VLC上可以看(但是延时有点高，大概20秒)，在SRS控制台自带的播放器上则无法显示，有点困惑。

**Comment by azMallco** [comment]
mallco@qq.com 这是我的邮箱想跟你交流一下 能留下联系方式不

**Comment by Novalife** [comment]
这是我的邮箱，daixiaoyong0321@163.com

**Comment by winlinvip** [comment]
Ingest是启动FFMPEG进程，将其他类型的流拉到FFMPEG后转成RTMP推服务器。
StreamCaster是SRS侦听端口，直接接受流然后转成RTMP送给自己。

**Comment by winlinvip** [comment]
从流的处理上看没有区别。但是StreamCaster是服务器，所以能接收非常多路流，但是不转码。

**Comment by Novalife** [comment]
学习了，谢谢。

**Comment by wendiepei** [comment]
> 已经解决了，但是有一点，转出的HLS在VLC上可以看(但是延时有点高，大概20秒)，在SRS控制台自带的播放器上则无法显示，有点困惑。

哥们怎么实现的
