### ISSUE TITLE
Regarding using SRS in production

### ISSUE THREAD

**Issue by chetandhembre** [ossrs/srs#1081]
Hi,
We are evaluating SRS to put in production.

We are having following questions
1. Can SRS take advantage of multi-core CPU?
2. Is there simple HTTP API to check the number of connections SRS handling?
3. Is there a guide for ideal configuration for low latency RTMP live streaming? 
I am not able to find answers to above questions in the documentation.
I might have missed that.
And thank you for documentation in English.

**Comment by chetandhembre** [comment]
I understand there SRS do not support multi-process out of the box.
https://github.com/ossrs/srs-dolphin was suggested as a solution. but it is deprecated.

Another solution is using of "SO_REUSEPORT".. but I unable to find an example configuration which uses this.
https://github.com/ossrs/go-oryx is still in development phase. 
Sorry, I am just detecting things which you already know.
Just wanted to know is a there better way?

**Comment by deluxor** [comment]
It depends on the usage you want. If you want to use SRS as an edge server (serving the streams coming from an origin server) thats ok to have multiple instances per host, behind a loadbalancer. If you want to use it as origin, you might only have one instance running on that PORT.

**Comment by chetandhembre** [comment]
We are planning to use it as edge..
Behind the load balancer you mean load balancer (nginx) on instance.

**Comment by deluxor** [comment]
Yes or HAPROXY, but if you are using HLS, otherwise you need to use a TCP loadbalancer, to be able to reverse proxy a TCP connection of RTMP, haproxy and nginx support tcp reverse proxying also.

**Comment by chetandhembre** [comment]
I already have NLB there. my problem is more of instance level where I have multiple cores .. I guess nginx in front will work fine. but I better use nginx rtmp module then.
unless SRS provide some specific solution for creating multiprocess.

**Comment by chetandhembre** [comment]
I tried to using https://github.com/ossrs/srs-dolphin to handle multiprocess for SRS, but find out for 5000 connection whole system opens around 21000 PORT. I do not know what I was doing wrong.
If it is normal then it won't be scalable.

**Comment by tarilo** [comment]
We read your comments in srs github repository about multi core process.

We need a rtmp live streaming solution for mobile phones with low latency and server cluster.

We now work in test mode with srs but have several latency and buffer problems with mobile devices and need to scale to aws servers but using all the cpu cores.

Do you fund solution for this questions?

Regards

**Comment by Leeaandrob** [comment]
I am looking for this concept to. Offers streaming low latency using aws. Exist solutions for multi core?

**Comment by winlinvip** [comment]
You can start an origin server and multiple edge server, each edge server you can start many processes.
