### ISSUE TITLE
srs-librtmp连接握手阶段非常容易产生超时错误(几乎100%)

### ISSUE THREAD

**Issue by dosmlp** [ossrs/srs#1085]
发布流的时候几乎一定会产生超时1011错误
srs_rtmp_publish_stream
然后把srs_librtmp.cpp  第49353行附近修改如下，超时时重试几次就好了
`        int ret = ERROR_SUCCESS;

        ssize_t nb_read = ::recv(skt->fd, (char*)buf, size, 0);
        int ti = 0;
        while(nb_read < 0 && ti <=5)
        {
            qDebug()<<"time out";
            Sleep(100);
            nb_read = ::recv(skt->fd, (char*)buf, size, 0);
            ++ti;
        }

        if (nread) {
            *nread = nb_read;
        }`

**Comment by maketa521** [comment]
确实解决了问题！

**Comment by longguolin** [comment]
[2018-05-16 14:24:51.006][Trace][66463][100] -> IGS time=167747, ingesters=2, #1(alive=167s, __defaultVhost__/dg47e19owzg7rhhg)
[2018-05-16 14:25:03.007][Trace][66463][100] -> IGS time=179227, ingesters=2, #0(alive=179s, __defaultVhost__/04pd2y4xol7hao31)
[2018-05-16 14:25:15.008][Trace][66463][100] -> IGS time=191244, ingesters=2, #1(alive=191s, __defaultVhost__/dg47e19owzg7rhhg)
[2018-05-16 14:25:20.732][Error][66463][110][62] connect error code=1011 : service cycle : rtmp: stream service : rtmp: start FMLE publish : recv FCPublish : recv message : recv interlaced message : read basic header : basic header requires 1 bytes : read bytes : timeout 30000 ms
thread #110: do_cycle() [src/app/srs_app_rtmp_conn.cpp:221][errno=62]
thread #110: service_cycle() [src/app/srs_app_rtmp_conn.cpp:427][errno=62]
thread #110: stream_service_cycle() [src/app/srs_app_rtmp_conn.cpp:563][errno=62]
thread #110: start_fmle_publish() [src/protocol/srs_rtmp_stack.cpp:2699][errno=62]
thread #110: expect_message() [src/protocol/srs_rtmp_stack.hpp:410][errno=62]
thread #110: recv_message() [src/protocol/srs_rtmp_stack.cpp:354][errno=62]
thread #110: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:878][errno=62]
thread #110: read_basic_header() [src/protocol/srs_rtmp_stack.cpp:972][errno=62]
thread #110: grow() [src/protocol/srs_protocol_stream.cpp:181][errno=62]
thread #110: read() [src/service/srs_service_st.cpp:304][errno=62]
(Timer expired)

**Comment by winlinvip** [comment]
这个修改是出错就重试，有点暴力。可能设置超时时间会更合适。

**Comment by winlinvip** [comment]
我看服务器不响应S0S1时的超时是30秒：

```
[T][82553][2018-08-05 11:26:55.800] output: rtmp://127.0.0.1/live/livestream?token=xxx
[T][82553][2018-08-05 11:27:25.802] ortmp simple handshake failed. ret=1011
```

**Comment by winlinvip** [comment]
librtmp中手动sleep(10)也能正常的推流：

```
[T][83226][2018-08-05 11:36:41.129] ortmp connect vhost/app success
[T][83226][2018-08-05 11:36:51.134] ortmp publish stream success
```

![image](https://user-images.githubusercontent.com/2777660/43682319-3ce01baa-98a4-11e8-9684-b9bcb0b97065.png)

**Comment by winlinvip** [comment]
Invalid, can't replay.
