### ISSUE TITLE
SrsRtspConn::on_rtp_packet 里视频的dts是如何计算的（rtp里传输的timestamp是pts）

### ISSUE THREAD

**Issue by fairywh** [ossrs/srs#1086]
SrsRtspConn::on_rtp_packet 里视频的dts是如何计算的（rtp里传输的timestamp是pts，协议里也没找到cts ）

**Comment by atlantis414** [comment]
If it is a baseline type of h264, pts=dts

`TRANS_BY_GPT3`

**Comment by wnpllrzodiac** [comment]
baseline does not have b frames. Indeed. If there are any, both flv and mp4 have composition time for time offset. ct = pts dts difference.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
RTP does not support B frames.

`TRANS_BY_GPT3`
