### ISSUE TITLE
srs向边缘站推流后，从边缘站直接拉取转码流不成功，得先拉取原始流后再拉取转码流

### ISSUE THREAD

**Issue by hjq123oo** [ossrs/srs#1088]
srs向边缘站推流后，从边缘站直接拉取转码流不成功，会创建ffmpeg线程，但是ffmpeg线程占用CPU率低。拉取原始流后，ffmpeg线程占用CPU瞬间变高，然后再转去拉取转码流成功。这个问题怎么解决？

**Comment by hjq123oo** [comment]
The version being used is srs-2.0.243. There is also an issue with DVR recording not happening if the stream is not pulled. How can this be resolved?

`TRANS_BY_GPT3`

**Comment by hjq123oo** [comment]
After testing, it was found that if the modes "remote", "transcode", and "dvr" are configured simultaneously in the same host, the above-mentioned issues will occur. However, if the source/edge mode is not used, these problems will not arise. How can we simultaneously support the source/edge mode while also supporting transcoding and DVR?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Transcoding is a function of the origin server.

`TRANS_BY_GPT3`
