### ISSUE TITLE
videojs5.4.1版本不能播放srs的流

### ISSUE THREAD

**Issue by ZiJinMountain** [ossrs/srs#1089]
在测试中发现通过网页+videojs不能播放经过srs服务器的流。同样的推流和拉流，使用nginx rtmp module就可以，通过抓包对比没有发现什么端倪。
srs也一直向终端PC发包，但是videojs无法显示视频。nginx可以。 

[root@localhost objs]# ./srs -v
3.0.25

nginx version: nginx/1.13.7
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled
configure arguments: --add-module=/home/source/nginx-rtmp-module-master --with-debug --with-http_ssl_module

**Comment by superfighter** [comment]
你怎么解决的呢？

**Comment by ZiJinMountain** [comment]
Flash需要支持复杂握手，老版本不支持。

发自我的 iPhone
