### ISSUE TITLE
是否支持rtsp转rtmp

### ISSUE THREAD

**Issue by azMallco** [ossrs/srs#1090]
传统的监控摄像头拉取的rtsp转rtmp么

**Comment by wnpllrzodiac** [comment]
ingest 然后使用transcode?应该可行

**Comment by luowuf** [comment]
可以的，已经实现了，局域网延迟1-2s

**Comment by wendiepei** [comment]
使用ingest不能播放，拷贝官方例子的。不知道哪一步错了

**Comment by winlinvip** [comment]
不支持摄像头推RTSP流到SRS，仅支持Ingest/FFmpeg从摄像头拉RTSP流后转给SRS，参考：https://github.com/ossrs/srs/issues/2304#issuecomment-826009290
