### ISSUE TITLE
How to implement custom RTMP server based on SRS?

### ISSUE THREAD

**Issue by l-law** [ossrs/srs#1092]
I would like to use SRS to develop an RTMP server, which ingest RTMP streams(push), and transcode or make other modifications of these contents with other existing libraries (all in single process).
There is code in SRS (inside app and main directory) for setting up a RTMP server, but seems it is not included in output library. Also srs_librtmp looks like to be a nice library for RTMP client, but not server.
Is there a simple example using SRS to build up an RTMP server? My requirement is to listen on custom port and app to ingest RTMP streams (but disable playback), and be able to get these streams out of SRS library.

**Comment by winlinvip** [comment]
I don'g understand what's your problem.

**Comment by winlinvip** [comment]
> I don'g understand what's your problem.

I means: I don't understand what's your point.

**Comment by winlinvip** [comment]
Hahaha, my English is not good, I'm dying of laughter.

`TRANS_BY_GPT3`
