### ISSUE TITLE
启动srs 必须再trunk目录下./obj/srs -c ./conf/XXXX.conf

### ISSUE THREAD

**Issue by zhenchengdezhichi** [ossrs/srs#1095]
这快是否进行优化下，不然运行不了并且产生不了日志。应该跟运行目录有关。 还有防火墙必须要关闭，suse 得方式时rcSuSefirwall2 status

**Comment by wnpllrzodiac** [comment]
Do you have any error logs during startup?

`TRANS_BY_GPT3`

**Comment by zhenchengdezhichi** [comment]
![image](https://user-images.githubusercontent.com/16041075/38619904-d8aa5a6c-3dcf-11e8-8ff8-a514682628e8.png)
No log is generated and the process did not start. Do I have to start it under the trunk? I cannot start it under obj.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If you want to start SRS at any directory, you should change all directory to abs path.

**Comment by winlinvip** [comment]
Set the `work_dir`, then you can run SRS at any directory.

```
# the work dir for server, to chdir(work_dir) when not empty or "./"
# user can config this directory to change the dir.
# @reamrk do not support reload.
# default: ./
work_dir ./;
```
