### ISSUE TITLE
hls 跨域问题 我尝试修改srs_app_http_stream.cpp 发现并没有解决问题

### ISSUE THREAD

**Issue by junkecc** [ossrs/srs#1103]
修改了srs_app_http_stream.cpp#703后添加w->header()->set("Access-Control-Allow-Origin", "*");

**Comment by objnf-dev** [comment]
The modification of HLS in this way is ineffective, and this modification is only effective for HTTP-flv.
The recommended method by the author is to use an HTTP proxy, see [here](https://github.com/ossrs/go-oryx/tree/develop/httpx-static).

`TRANS_BY_GPT3`

**Comment by junkecc** [comment]
The problem is resolved. In the end, I added an nginx proxy on the server. However, if it can be solved by modifying the code, that would be the best option.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS3 fixed
