### ISSUE TITLE
http flv壓力測試問題

### ISSUE THREAD

**Issue by ginoliang1130** [ossrs/srs#1104]
因為文件並沒有提及可以使用http load來進行http-flv的壓力測試，所以自己就測試了一下。

SRS Server
CPU：8 core cpu
RAM：32 GB
OS：Ubuntu 16.04 LTS
SRS Version:2.0.243

Test Server
CPU：8 core cpu
RAM：32 GB
OS：Ubuntu 16.04 LTS
SRS Bench

stream bitrate:100kbps，1000並發數可以支撐。
./sb_http_load -c 1000 -r http://srs-server-ip/AppName/StreamName.flv

[2018-04-02 14:26:24.751] [report] [24634] threads:1000 alive:999 duration:30 tduration:0 nread:50.24 nwrite:0.04 tasks:1005 etasks:6 stasks:0 estasks:0

但是如果超過1000的話就會報錯。
exceed the max connections, drop client: clients=1000, max=1000, fd=1013(Resource temporarily unavailable)

系統參數：net.core.somaxconn = 65535

**Comment by ginoliang1130** [comment]
Know where the problem is, write * - nofile 65535 in /etc/security/limits.conf, otherwise it will be ineffective after ulimit -HSn and reboot.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍
