### ISSUE TITLE
srs3.0 token参数放在streamID后面如何实现认证

### ISSUE THREAD

**Issue by Ccrazyfish** [ossrs/srs#1110]
srs3.0的token参数放到SreamID后面，http_hook后，TcURL中没有这个token，只有放到live后，TcUrl中才有
怎样才可以在server.py 中的json_req中拿到token 用来认证？
推流rtmp://test.lsspush.test.com/live/steam001?key=123000000000&t=20000
on_connect  
json_req:
{u'ip': u'192.168.0.101, u'app': u'live', u'vhost': u'__defaultVhost__', u'pageUrl': u'', u'client_id': 108, u'tcUrl': u'rtmp://test.lsspush.test.com/live', u'action': u'on_connect'}

on_publish
json_req:
{u'stream': u'steam001', u'ip': u'116.62.38.168', u'app': u'live', u'vhost': u'__defaultVhost__', u'client_id': 108, u'tcUrl': u'rtmp://test.lsspush.test.com/live', u'action': u'on_publish'}

**Comment by wnpllrzodiac** [comment]
2.0 branch have support this feature. You can look up changelog.

**Comment by Ccrazyfish** [comment]
2.0branch tried it, got the streamID, but there are no parameters with key=** in the hook information.

Push stream address:
rtmp://172.16.162.16/live/stream000?key=123435

Hook information:
action: {u'ip': u'172.16.162.190', u'app': u'live', u'vhost': u'__defaultVhost__', u'pageUrl': u'', 
u'client_id': 120, u'tcUrl': u'rtmp://172.16.162.16', u'action': u'on_connect'}

{u'stream': u'stream000', u'ip': u'172.16.162.190', u'app': u'live', u'vhost': u'__defaultVhost__',
 u'client_id': 120, u'tcUrl': u'rtmp://172.16.162.16', u'action': u'on_publish'}

`TRANS_BY_GPT3`

**Comment by wnpllrzodiac** [comment]
Just add a field to the code of 'hook', I modified the source code myself. Winlin has completed 99% of it, so you just need to make the remaining changes yourself. Alternatively, you can create an issue and ask him to fix it.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS2:
```
{"action":"on_publish","client_id":107,"ip":"127.0.0.1","vhost":"__defaultVhost__",
"app":"live","tcUrl":"rtmp://127.0.0.1:1935/live","stream":"livestream?userid=123456&token=ueieww"}
{"action":"on_play","client_id":107,"ip":"127.0.0.1","vhost":"__defaultVhost__",
"app":"live","stream":"livestream?userid=123456&token=ueieww","pageUrl":""}
```

**Comment by itmanlee** [comment]
![image](https://user-images.githubusercontent.com/1921219/177782873-aeeee735-8069-4298-b2dc-b5986554082c.png)
Hello, I would like to ask you two questions. Please refer to the screenshot.

`TRANS_BY_GPT3`

**Comment by itmanlee** [comment]
In addition, the JSON data structure received by the proxy here is also somewhat different from the description in the http-hooks of full.conf. Do we need to adjust it ourselves in the source code to match the desired data structure?

`TRANS_BY_GPT3`

**Comment by itmanlee** [comment]
![image](https://user-images.githubusercontent.com/1921219/177783863-4278cd09-dba4-433a-8173-cc75e57d029f.png)
