### ISSUE TITLE
suse机器上面编译报错。

### ISSUE THREAD

**Issue by zhenchengdezhichi** [ossrs/srs#1114]
![image](https://user-images.githubusercontent.com/16041075/38502194-60f5a5a6-3c41-11e8-924c-7b45d9935b3b.png)
这是suse机器上面进行编译的。报错，但使用./configure --pi 编译ok

**Comment by zhangjg0823** [comment]
您好，您这边用suse编译完成后，可以正常使用srs吗？

**Comment by zhenchengdezhichi** [comment]
可以使用的。

**Comment by winlinvip** [comment]
用srs-docker
