### ISSUE TITLE
關於長時間播放的累積延時問題

### ISSUE THREAD

**Issue by vegetableB** [ossrs/srs#1116]
本人希望進行視頻的實時直播播放。平臺是ubuntu 16.04；SRS採用realtime.conf的配置；推流部分是自己實現的代碼，主要是把攝像頭的數據包推過去；攝像頭設置是 25fps，I幀間隔不超過4幀，H264編碼；播放部分採用較新版本的ffmpeg編譯生成的ffplay，加了-fflags noffer參數。進行長時間播放的時候，播放會有累積延時，大約1天延時有10秒，而新的連接則是基本實時的。把推流端的數據包解碼顯示出來，可以看出延時不是出在拉流端。把realtime.conf中的queue_length修改成1,延時的現象沒有得到改善。請問除了重新連接之外，還有什麼辦法可以減少累積延時呢？

**Comment by wnpllrzodiac** [comment]
Player should do extra work.
RTMP is based on TCP and inherently has accumulated delay over time. Network jitter, whether on the streaming or playback side, will result in data accumulation. In addition, the accuracy of the player's clock also needs to be considered, as it may deviate by a few seconds in a day according to the player's clock. What if the data buffer accumulates too much?
If you want the player to play for a long time without accumulating delay, the player needs to add logic for dropping frames and fast-forwarding, preferably after decoding. This way, there will be no screen freezing and it will be more flexible.
These are just my personal opinions for reference.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Player problem.
