### ISSUE TITLE
Elemental encoder streaming 

### ISSUE THREAD

**Issue by davidka79** [ossrs/srs#1125]
Hello
I open an SRS real-time.conf stream and we trying to stream there via Aws elementary encoder stream, but we all time getting the disconnect by timeout.

Steamer starts publishing sends 5 bloks at the same time, SRS gets 5blocks and waiting 5000 Ms and closing connection by timeout. İs there any options not to break publisher and just to wait  for next blocks ?

According Wireshark on srs server we getting message TCP window 0

**Comment by winlinvip** [comment]
Seems network problem.
