### ISSUE TITLE
Can it provide RTSP streaming instead of RTMP?

### ISSUE THREAD

**Issue by hitswa** [ossrs/srs#1130]
I am trying to avoid Flash or VLC ActiveX on browser and this I am trying to convert Stream to MPEGTS. The only Issue is that FFMPEG transport work on RTSP and not on RTMP (I guess).

Can SRS server provide RTSP stream? or suggest me any other alternatives.

If someone have already solved this issue please share the solution. Your help will be really appreciable.

**Comment by winlinvip** [comment]
For internet, HTTP is more popular than RTXP.
