### ISSUE TITLE
How about add a srs_server_addr field in the http callback message?

### ISSUE THREAD

**Issue by RocFang** [ossrs/srs#1132]
Hi, @winlinvip 

As the title goes, how about add a srs_server_addr field in the http callback message?

In some scenarios, the http callback server need to konw the srs's  real service ip address which accept the connection of the rtmp request. And this ip can't simply get from the http callback server.

The solution is quite simple, there is already a local variable local_ip in SrsRtmpConn::service_cycle. So just copy that value will take effect. Do you think it is worth a commit?

Thanks.

**Comment by winlinvip** [comment]
Why closed?
