### ISSUE TITLE
HTTP-FLV: 播放无流的流，没有超时或404，或者播放器等待

### ISSUE THREAD

**Issue by RocFang** [ossrs/srs#1134]
分支：2.0

@winlinvip  hi,

首先，现在srs2.0里对于推流端是有超时断连的处理，但对播放器没有相关处理。这算另一个问题，这里提到只是作为一个引子。

这在rtmp的情况下，是不令人意外的。但在提供http-flv服务的时候，一般场景是会通过nginx proxy到srs，而这个时候nginx的proxy是有一个proxy_read_timeout配置的，无论这个配置是默认还是我们自行配置。即在直观的逻辑中，通过nginx proxy对播放器是有超时断连的，这个情况对于srs源站，确实也是成立的。

但在srs作为边缘提供http-flv的时候，表现就会有点“意外”。为了实现reduce_sequence_header功能，srs在unpublish的时候，不会清理cache_metadata,cache_sh_audio,cache_sh_video。边缘srs由http-flv播放触发的edge ingester，会由于源站没有流而超时不断重试，每次重试都会重新将从源站获取到的metadata,sequence header再发给客户端。 这样，在http-flv播放器看来，虽然一直没有流，但由于edge ingester一直将这些数据按照edge ingester超时的间隔不断的发送给nginx，导致proxy_read_timeout看起来没起到预期作用，除非设置很小的proxy_read_timeout，不然会一直不断开连接。

**Comment by winlinvip** [comment]
Clearing the cache when the encoder stops streaming is reasonable.

`TRANS_BY_GPT3`

**Comment by RocFang** [comment]
How was the lack of a timeout disconnect mechanism considered when playing rtmp?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Should support configuring read timeout.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
> How was the lack of timeout disconnection mechanism considered when playing rtmp?

> It is handled simply. This issue is a bit complex. RTMP playback and streaming are not coupled, so playback can still happen even without streaming. However, in HTTP, if there is no streaming, the resource does not exist, so it should return a 404 error.

> However, HTTP can also trigger origin retrieval, so when there is no stream, playback can trigger the retrieval of the stream (streaming). When streaming stops, at this point, the HTTP handler should be disabled, which means according to HTTP logic, it should return a 404 error.

> Unless HTTP completely abandons the use of 404, like RTMP does not need to handle "unpublish", but this approach is quite unreasonable. The more reasonable approach is to still introduce the concept of 404. Triggering origin retrieval should be an independent mechanism, but if "unpublish" occurs after origin retrieval, it should still be treated as a 404 error.

> In other words, if RTMP has the concept of 404 and returns an error when the stream does not exist, it will disconnect the player connection when "unpublish" occurs. Of course, triggering origin retrieval in RTMP is an independent mechanism and is unrelated to this.

> Looking back at player timeout, it refers to the timeout when there is no stream for a certain period of time. In reality, if there is no stream for a period of time, it will become a 404 status and disconnect the client connection.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
After introducing 404, the only downside is that the player may disconnect due to unpublishing or edge reconnection. Considering that the player itself cannot remain connected indefinitely, I personally think it is acceptable.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Postpone to SRS4.

**Comment by SuperChrisliu** [comment]
> Should support configuring read timeout.

> Is there support for this configuration now? The streaming is disconnected, and ffmpeg keeps getting stuck while pulling the stream...

`TRANS_BY_GPT3`

**Comment by SuperChrisliu** [comment]
> > Should support configuring read timeout.
> 
> Is there support for this configuration now? The streaming is disconnected, and ffmpeg keeps hanging while pulling the stream.

`ffmpeg` supports the `-rw_timeout` parameter, which sets the timeout for IO operations in microseconds. It is important to note that when pulling multiple streams with `ffmpeg`, multiple `rw_timeout` parameters are required.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #931 

Attention should be paid to whether to disconnect or maintain the connection, as there are different demands in different scenarios, so it is best to make this configurable.

The issue of connecting to the origin with Edge is the same. Close this issue, please refer to #931 for details.

`TRANS_BY_GPT3`
