### ISSUE TITLE
nginx server port 8080 in English

### ISSUE THREAD

**Issue by sah-anshu** [ossrs/srs#1137]
Hi I am English User can you help me if i can start the 8080 port server in english.

![screen shot 2018-05-16 at 1 42 51 am](https://user-images.githubusercontent.com/9985291/40081395-79914292-58ab-11e8-97d5-7510f0f3801c.png)

Thanks in advance.
Anshu

**Comment by o4uz** [comment]
service iptables stop

**Comment by winlinvip** [comment]
You can use http://ossrs.net:1985/console
