### ISSUE TITLE
按照 “RTMP部署实例” 指导，配置好后，通过vlc访问流失败

### ISSUE THREAD

**Issue by bruceshu** [ossrs/srs#1139]
通过FFmpeg正常向服务器推流，如下图所示：
![image](https://user-images.githubusercontent.com/25739171/40105335-3d3d3eca-5925-11e8-9576-4d22150cffcf.png)

服务器正常接收流，如下图所示：
![image](https://user-images.githubusercontent.com/25739171/40105355-46cc4ada-5925-11e8-86f5-af06ff5c5de2.png)

用vlc客户端访问流，却提示访问失败，如下图所示：
![image](https://user-images.githubusercontent.com/25739171/40105386-5ddc90f4-5925-11e8-9d84-4967b45770f3.png)

小白一枚，请问大佬们，还需要做什么操作吗，谢谢

**Comment by o4uz** [comment]
Is the firewall turned off? Try removing the port for streaming.

`TRANS_BY_GPT3`
