### ISSUE TITLE
HTTPS/SSL configuration?

### ISSUE THREAD

**Issue by invalidtask** [ossrs/srs#1142]
How do I install my SSL certificates with the HTTP server? I cannot find anything on how to do this.

**Comment by winlinvip** [comment]
Use HTTPS proxy.

**Comment by jyy1082** [comment]
Is there anyone who has HTTPS/SSL configuration experience to share? Thanks

**Comment by xmglin** [comment]
nginx configuration
`
   server {
        listen       443 ssl;
        server_name  live.example.com;

        ssl on;
        ssl_certificate      /path/to/cert.pem;
        ssl_certificate_key  /path/to/cert.key;
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
        ssl_prefer_server_ciphers on;
 
        location / {
            proxy_pass http://<SRS-IP>;
        }
`
