### ISSUE TITLE
./configure --with-ffmpeg error

### ISSUE THREAD

**Issue by ibanezsc** [ossrs/srs#1153]
mon/quant.o common/deblock.o common/vlc.o common/mvpred.o common/bitstream.o encoder/analyse.o encoder/me.o encoder/ratecontrol.o encoder/set.o encoder/macroblock.o encoder/cabac.o encoder/cavlc.o encoder/encoder.o encoder/lookahead.o common/threadpool.o common/x86/mc-c.o common/x86/predict-c.o common/x86/const-a.o common/x86/cabac-a.o common/x86/dct-a.o common/x86/deblock-a.o common/x86/mc-a.o common/x86/mc-a2.o common/x86/pixel-a.o common/x86/predict-a.o common/x86/quant-a.o common/x86/cpu-a.o common/x86/dct-64.o common/x86/bitstream-a.o common/x86/sad-a.o common/x86/trellis-64.o
ranlib libx264.a
gcc -o x264  x264.o input/input.o input/timecode.o input/raw.o input/y4m.o output/raw.o output/matroska.o output/matroska_ebml.o output/flv.o output/flv_bytestream.o filters/filters.o filters/video/video.o filters/video/source.o filters/video/internal.o filters/video/resize.o filters/video/cache.o filters/video/fix_vfr_pts.o filters/video/select_every.o filters/video/crop.o filters/video/depth.o input/thread.o libx264.a  -m64  -lm -lpthread
/usr/bin/x86_64-linux-gnu-ld: libx264.a(cabac-a.o): relocation R_X86_64_32 against symbol `x264_cabac_range_lps' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: libx264.a(quant-a.o): relocation R_X86_64_32 against hidden symbol `x264_pb_01' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(dct-a.o): relocation R_X86_64_32 against hidden symbol `x264_pw_8000' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(deblock-a.o): relocation R_X86_64_32 against hidden symbol `x264_pb_1' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(mc-a.o): relocation R_X86_64_32 against hidden symbol `x264_pw_64' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(mc-a2.o): relocation R_X86_64_32 against hidden symbol `x264_pw_32' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(pixel-a.o): relocation R_X86_64_32 against hidden symbol `x264_pw_00ff' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(predict-a.o): relocation R_X86_64_32 against hidden symbol `x264_pb_1' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(dct-64.o): relocation R_X86_64_32 against hidden symbol `x264_hsub_mul' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(sad-a.o): relocation R_X86_64_32 against hidden symbol `x264_pw_8' can not be used when making a PIE object
/usr/bin/x86_64-linux-gnu-ld: libx264.a(trellis-64.o): relocation R_X86_64_32 against symbol `x264_cabac_entropy' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:182: recipe for target 'x264' failed
make: *** [x264] Error 1
build x264 failed
build ffmpeg-2.1 failed, ret=1
shi@ubuntu:~/Desktop/o/srs-master/trunk$ ^C
shi@ubuntu:~/Desktop/o/srs-master/trunk$ ./configure --with-ffmpeg

**Comment by 0079123** [comment]
可自行搭建ffmpeg环境

**Comment by wnpllrzodiac** [comment]
It is your ffmpeg with x264 build environment problem. not srs
