### ISSUE TITLE
st里面的st_usleep()在系统时间回退的时候可能导致长时间挂死

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#116]
https://github.com/winlinvip/simple-rtmp-server/issues/116

**Comment by aawl2001** [comment]
Is this issue caused by gettimeofday in MD_GET_UTIME? Because gettimeofday may cause the system time jump.
And why system time jump causes st_usleep() suspend? I added some debug code to simulate the system jump (to future or last), the st_usleep seems work well.

Thanks

**Comment by winlinvip** [comment]
When system time jump to previous time, the diff will be negative which is big positive uint64. Then the st_usleep(big uint64) will wait for a long long time, similar to blocked.

**Comment by aawl2001** [comment]
Thanks for your explanation, how to fix this issue? change the code of st or srs?
Thanks

**Comment by winlinvip** [comment]
No need to fix it, we can restart SRS when we adjust system time to a previous point.
Generally, system admin should never adjust the time manually.

**Comment by winlinvip** [comment]
Not a common issue.
