### ISSUE TITLE
SRS 2 & 3: EINTR in st_connect in newer linux kernels

### ISSUE THREAD

**Issue by felipewd** [ossrs/srs#1160]
Hi!

We've been using srs-2.0 in production for quite a while now and it works great! It's a great piece of software. We use as an Edge ("remote mode") to our nginx-rtmp central server for RTMP caching.

It works perfectly, except that a few weeks ago we deployed the exact same binary we use with newer machines that use linux kernel 4.14.7 (instead of the usual 4.9)...and poof, as soon as we do, a simples st_connect fails with:

```
[error][892942][112][4] connect to server error. ip=11.11.11.11, port=1935, ret=1018(Interrupted system call)
[warn][892942][112][4] edge pull failed, stream=test02, tcUrl=rtmp://11.11.11.10/test011 to server=rtmp.test.com, port=1935, timeout=3000000, ret=1018
[warn][892942][112][4] thread edge-igs cycle failed, ignored and retry, ret=1018
```

Just recompiling the latest 3.0 branch (which uses st-1.9.1) gives the same error:

```
[Warn][892964][111][4] EdgeIngester: Ignore error, code=1018 : connect upstream : edge pull rtmp://rtmp.test.com:1935/test011/test02 failed, cto=5000, sto=500 : connect : tcp: connect 11.11.11.11:1935 to=5000 : connect to 11.11.11.10:1935
thread #111: do_cycle() [src/app/srs_app_edge.cpp:264][errno=4]
thread #111: connect() [src/app/srs_app_edge.cpp:122][errno=4]
thread #111: connect() [src/service/srs_service_rtmp_conn.cpp:72][errno=4]
thread #111: connect() [src/service/srs_service_st.cpp:442][errno=4]
thread #111: srs_socket_connect() [src/service/srs_service_st.cpp:144][errno=4]
```

Not really sure what caused this, but since the st_connect code can't generate EINTR (since the error loop is exactly errno != EINTR), the only possibility is inside the poll code, which sets errno to EINTR if the thread has the _ST_FL_INTERRUPT flag.

Not really sure _why_ this would happen just by changing the kernel, but since the st code is rather old, maybe there is?

**Comment by winlinvip** [comment]
The SRS binary is build for CentOS6, if you upgrade your linux kernel, you need to rebuild SRS by yourself at the new kernel.

**Comment by felipewd** [comment]
Right, sorry. Should have told you that of course this is source compiled.

I used  2.0-r2, e309be1 to build this.

I compiled locally using the new kernel headers, but no luck. From the backetrace, it really seems to be a bug from the thread library. In fact, -EINTR shouldn't really be a problema in an event-based system, right?

**Comment by felipewd** [comment]
I don't have one, but if you do, I can sure run in both an old and new kernel and report back

**Comment by winlinvip** [comment]
The err `errno=4` is caused by timeout 5000ms or connect failed:

```
#define EINTR 4 /* Interrupted system call */
#define EAGAIN 11 /* Try again */
```

For ST or SRS, `errno=11(EAGAIN)` is never return to user, but `errno=4(EINTR)` is possible.

**Comment by winlinvip** [comment]
I will write a utest to verify this issue.

**Comment by felipewd** [comment]
Right, I'll test it as soon as you can provide me with an example.

FYI, I could telnet to that RTMP server (on port 1935), and it worked fine. nginx-rtmp could pull from that server as well...just SRS couldn't work and returned that message.

So a 5s timeout wasn't really happening. But I'm more than happy to test any code you can provide me.

**Comment by winlinvip** [comment]
You can config the timeout in ms.

**Comment by felipewd** [comment]
Sorry, I didn't understand why did you close this issue? Weren't you going to provide me a little test app so I can confirm a bug in ST?

I just said in the previous post that I know it wasn't a timeout issue. It wasn't a "ms vs s" confusion :-)

**Comment by winlinvip** [comment]
Please write a little test code to replay this issue, then please reopen this issue.

**Comment by felipewd** [comment]
Right, like I said previously, I can run a test program if you want, but you commented "I will write a utest to verify this issue."

If you have one, I'd be more than happy to test it and report back.

**Comment by winlinvip** [comment]
Please write a test program 😄 
I though I could write a utest, but actually I had no time.

**Comment by winlinvip** [comment]
Write a TCP server, use st-1.9

**Comment by winlinvip** [comment]
Closed for not replay.
