### ISSUE TITLE
SRS HTTP FLV latency

### ISSUE THREAD

**Issue by mrqaidi** [ossrs/srs#1161]
Hi

first  thank you so much for  this awesome and nice tool i  setup my own rtmp server with  http flv  everything works fine  but one problem i got is there is  3s-6s latency  is there something i can do  fix this issue ?

here is my config

`
listen              1935;
max_connections     1000;
daemon              on;
chunk_size          60000;
max_connections     2000;
srs_log_tank        console;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    # whether http api is enabled.
    # default: off
    enabled         on;
    # the http api listen entry is <[ip:]port>
    # for example, 192.168.1.100:1985
    # where the ip is optional, default to 0.0.0.0, that is 1985 equals to 0.0.0.0:1985
    # default: 1985
    listen          1985;
    # whether enable crossdomain request.
    # default: on
    crossdomain     on;
}
vhost __defaultVhost__ {

    # whether enable the TCP_NODELAY
    # if on, set the nodelay of fd by setsockopt
    # default: off
    tcp_nodelay     on;

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       off;
    }
    http_hooks {
        # whether the http hooks enalbe.
        # default off.
        enabled         on;

        on_publish      http://dev.qaidi.info/examer/section/streamauth;		
        on_unpublish         http://dev.qaidi.info/examer/section/streamauth;
        #on_connect         http://dev.qaidi.info/examer/section/streamauth;
        #on_close         http://dev.qaidi.info/examer/section/streamauth;
        #on_play         http://dev.qaidi.info/examer/section/streamauth;
        #on_stop         http://dev.qaidi.info/examer/section/streamauth;
		
    }	
}`
i use  https://github.com/Bilibili/flv.js to play my  live streams.

thank you once again

**Comment by wnpllrzodiac** [comment]
I think latency about 1-3sec is acceptable.http_flv main feature is FAST open while rtmp will take about 3 sec.

**Comment by mrqaidi** [comment]
@wnpllrzodiac  what do you mean exactly ?

**Comment by winlinvip** [comment]
Latency is caused by encoder and player, if your server is in realtime mode.
