### ISSUE TITLE
V2.0  http_hook 我是用错了么？

### ISSUE THREAD

**Issue by junerleer** [ossrs/srs#1164]
我这边使用V2.0版本的http hook，发现在和使用其他防盗链的一些不同。

我的链接可能是这样的rtmp://xxxx/appName/streamName?token=ab35c67d78e&endTime=1530714109842

1.首先我可以用某个约定的key对endTime、appName、streamName进行签名对比token是否正确
2.验证endTime是否大于服务器时间

但是现在srs却在onpublish的hook里面，给的stream=streamName?token=ab35c67d78e&endTime=1530714109842,

我想说我的stream是streamName，其他的参数我另有用途做各种校验啊，因为我现在拉流必须也是stream=streamName?token=ab35c67d78e&endTime=1530714109842，否则无法拉流

我更多的希望我的拉流地址是rtmp://xxxx/appName/streamName?token=aaaaaaaa&endTime=1530714109842另一个值，并不一定要和推流地址一样

**Comment by junerleer** [comment]
OK.  I solve this problem in the issue of #741 
In srs, the correct way is this,rtmp://xxxx/appName?token=ab35c67d78e&endTime=1530714109842/streamName

**Comment by RocFang** [comment]
你用的是2.0分支的某个历史代码吧？现在在2.0中，即使rtmp://xxxx/appName/streamName?token=ab35c67d78e&endTime=1530714109842这种形式，http_hook也会发送正确的sreamName.

**Comment by winlinvip** [comment]
v2.0, 2018-02-13, Fix #1059, support vhost in stream parameters. 2.0.246

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/tree/2.0release#history
