### ISSUE TITLE
raspberry pi 编译ffmepg 有问题

### ISSUE THREAD

**Issue by icemanpro** [ossrs/srs#1165]
1. ./configure --pi --with-ffmpeg 编译ffmpg时，在build fdk-aac-0.1.3 会报错
![tim 20180705151458](https://user-images.githubusercontent.com/1924688/42307796-392e207a-8066-11e8-95bd-3101a050e983.png)

已在srs3.0上测试

**Comment by icemanpro** [comment]
将 trunk/auto/build_ffmpeg.sh 第45行
./configure --prefix=${ff_release_dir} --enable_static &&
//改为
./configure --prefix=${ff_release_dir} --enable_static CXXFLAGS=”-Wno-narrowing” &&

**Comment by kaiseroze** [comment]
照着楼主教程修改后编译出错：g++: error: ”-Wno-narrowing”: No such file or directory
Makefile:1259: recipe for target 'libAACdec/src/aacdec_drc.lo' failed
make: *** [libAACdec/src/aacdec_drc.lo] Error 1
请问楼主要怎么解决呢？
