### ISSUE TITLE
srs是否支持连接265的rtsp流，并且把rtsp流保存下来？

### ISSUE THREAD

**Issue by xiaodong60606** [ossrs/srs#1167]
之前一直用srs+ffmpeg保存264摄像机的数据流，最终保存成flv格式，现在要连接265的摄像机，ffmpeg已经添加对libx265的支持，直接使用ffmpeg命令可以连接265 rtsp流，并且可以实现保存功能，但是配合srs使用的时候一直报错，请大神指点。

**Comment by winlinvip** [comment]
265 is not supported.
