### ISSUE TITLE
HLS和ffmpeg服务无法同时运行

### ISSUE THREAD

**Issue by o4uz** [ossrs/srs#1169]
Centos 6.8 64位系统，通过 git clone https://github.com/ossrs/srs 安装了SRS，分别通过：
**./configure --with-nginx && make**
**./configure --with-ffmpeg && make**
安装了HLS和ffmpeg转码功能。
通过 **./objs/srs -c conf/hls.conf** 启动HLS以后，RTMP推流、RTMP拉流、HLS拉流功能正常，但是**ffmpeg转码服务没有生效**。
通过 **./objs/srs -c conf/ffmpeg.transcode.conf** 启动ffmpeg，RTMP推流、RTMP拉流、ffmpeg正常，但是**HLS拉流失败**，没有生成切片文件。
请问各位大神HLS和ffmpeg服务怎么同时启动？（实现推送一路高码率，另转一路标清码，并分别切片成HLS，或指定只将标清码切片HLS。）

推流系统错误代码：
`[2018-07-12 10:33:30.028][error][18227][520][104] rtmp handshake failed. ret=1008(Connection reset by peer)`
`[2018-07-12 10:33:30.028][warn][18227][520][104] client disconnect peer. ret=1004`

同时启动hls和ffmpeg，系统报错：
`[2018-07-12 10:33:20.682][error][18247][100][11] srs is already running! ret=0x40b(Resource temporarily unavailable)
`

**Comment by icemanpro** [comment]
在3.0release分支下测试
**./configure --with-ffmpeg && make**

在conf目录下新建np.conf文件。
listen              1935;
max_connections     1000;
#srs_log_tank      console;
#daemon              off;
http_server {
    enabled   on;
    listen   8080;
    dir     ./objs/nginx/html;
}
vhost __defaultVhost__ {
      hls {
         enabled   on;
         hls_path   ./objs/nginx/html;
         hls_fragment   10;
         hls_window     60;
    }

      transcode {
        enabled     on;
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine ff {
            enabled         on;
            vfilter {
            }
            vcodec          libx264;
            vbitrate        460;
            vfps            25;
            vwidth          320;
            vheight         180;
            vthreads        12;
            vprofile        main;
            vpreset         medium;
            vparams {
            }
            acodec          libfdk_aac;
            abitrate        70;
            asample_rate    44100;
            achannels       2;
            aparams {
            }
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }
    }
}

推流地址:rtmp://x.x.x.x/live/livestream
rtmp播放:rtmp://x.x.x.x/live/livestream
rtmp转码播放:rtmp://x.x.x.x/live/livestream_ff
hls播放:http://x.x.x.x:8080/live/livestream.m3u8
hls转码播放:http://x.x.x.x:8080/live/livestream_ff.m3u8

播放器是用vlc测试的。

**Comment by o4uz** [comment]
感谢楼上朋友的启发，我把 ffmpeg.transcode.conf 的内容合并至 hls.conf 内，运行 ./objs/srs -c conf/hls.conf ，RTMP推流、RTMP拉流、转码、HLS拉流全部成功，问题解决了。

**Comment by o4uz** [comment]
本地用obs软件推流，目前所有功能正常。但是系统有报错：
`[2018-07-12 12:08:53.089][warn][19676][171][104] read c0c1 failed. ret=1008
[2018-07-12 12:08:53.089][error][19676][171][104] rtmp handshake failed. ret=1008(Connection reset by peer)
[2018-07-12 12:08:53.089][warn][19676][171][104] client disconnect peer. ret=1004
`

**Comment by winlinvip** [comment]
OBS无法推流到SRS？

**Comment by o4uz** [comment]
推流、拉流都正常，但是系统报错。

**Comment by winlinvip** [comment]
HLS和FFMPEG同时运行，不是启动两个SRS，而是在一个SRS中启用多个Feature。

另外，启动多个SRS是可以的，但是要改配置文件。从你的意图看，不应该启动多个SRS。
