### ISSUE TITLE
SRS2.0 系统崩溃 产生core.23***文件

### ISSUE THREAD

**Issue by eveyang** [ossrs/srs#1170]
操作系统CentOS Linux release 7.2.1511 (Core) 
编码器：ffmpeg2.1.1
服务器：SRS 2.0.240

在SRS 做推流转码服务过程中  ，srs一直产生崩溃文件core.后边一堆数字  ，不知是什么原因造成的，我的SRS 系统版本是2.0.240 产生的部分core文件代码：
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f95aa48e1d7 in ?? ()
(gdb) bt
#0  0x00007f95aa48e1d7 in ?? ()
#1  0x00007f95aa48f8c8 in ?? ()
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()

Type "apropos word" to search for commands related to "word"...
Reading symbols from objs/srs...done.

warning: core file may not match specified executable file.
[New LWP 23451]
[New LWP 23457]
[New LWP 23454]
[New LWP 23460]
[New LWP 23464]
[New LWP 23458]
[New LWP 23467]
[New LWP 23462]
[New LWP 23470]
[New LWP 23453]
[New LWP 23466]
[New LWP 23476]
[New LWP 23474]
[New LWP 23468]
[New LWP 23472]
[New LWP 23469]
[New LWP 23455]
[New LWP 23456]
[New LWP 23459]
[New LWP 23475]
[New LWP 23463]
[New LWP 23452]
[New LWP 23461]
[New LWP 23473]
[New LWP 23471]
[New LWP 23465]
Core was generated by `/usr/local/bin/ffmpeg -f flv -i rtmp://127.0.0.1:1935/live?vhost=__defaultVhost'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd71b03d38c in ?? ()
(gdb) bt
#0  0x00007fd71b03d38c in ?? ()
#1  0x00007fd71b8b64fc in ?? ()
#2  0x00007ffe34678490 in ?? ()
#3  0x00007fd71d1a0c22 in ?? ()
#4  0x0000000001ee7bc0 in ?? ()
#5  0x00007fd71d1a0ed0 in ?? ()
#6  0x0000000000000001 in ?? ()
#7  0x0000000001ef8070 in ?? ()
#8  0x00007ffe346783b0 in ?? ()
#9  0x0000000001ef8080 in ?? ()
#10 0x00007ffe346783ac in ?? ()
#11 0x000000a600adfd4b in ?? ()
#12 0x0000000000000000 in ?? ()

**Comment by winlinvip** [comment]
It's generated by FFMPEG.
