### ISSUE TITLE
How to reduce latency?Now is 1 second

### ISSUE THREAD

**Issue by junerleer** [ossrs/srs#1171]
1. I use ffmpeg to publish stream. The command is like this
`ffmpeg -f avfoundation -i "1" -vcodec libx264 -preset ultrafast -acodec libfaac -f flv rtmp://localhost:1935/live/myStream`

2.Then one screen's browser open a webpage has stopwatch
[online stopwatch](https://miaobiao.51240.com/)

3.My another screen's browser open ssr player for play stream.

4.I take a photo contains 2 screen.And I find the latency is about 1 second.

**Comment by junerleer** [comment]
The srs.conf has the following property: [RTMP Low Latency](https://github.com/ossrs/srs/wiki/v2_CN_SampleRealtime)
`
    gop_cache       off;
    queue_length    10;
    min_latency     on;
    mr {
        enabled     off;
    }
    mw_latency      100;
    tcp_nodelay     on;
`


`TRANS_BY_GPT3`

**Comment by junerleer** [comment]
I know it will be difficult. But to my application, reduce every 100 milliseconds, is a great improvement.

**Comment by winlinvip** [comment]
The latency is introduced by your encoder and player.

**Comment by openaspace** [comment]
HI! :)
I'm working with VMIX to make a p2p stream for conference's and the vmix encoder have 7 seconds of delay!! 

Working with OBS at 0 buffer and playing the stream with VLC i have from 2 to 3 seconds using the realtime.conf settings. 2 Seconds for a live conference can be high.. any way to reduce to 1 or less? 

Thank you.

**Comment by waiter89** [comment]
Don't use VLC,  use ckplayer
