### ISSUE TITLE
Chinese interface

### ISSUE THREAD

**Issue by ralfeus** [ossrs/srs#1184]
Hi.
I've installed fresh SRS and whole web interface is in Chinese. Is there any way to switch to English?
Previous issue #1180 has response but it's not understandable. Moreover if I try to open console on my host (http://ubuntu:1985/console) I get "Not found" page

**Comment by allegfede** [comment]
got exactly the same problem ...

**Comment by winlinvip** [comment]
The console is a js project at https://github.com/ossrs/srs-ngb

However, you can use http://ossrs.net:1985/console to connect to your SRS server.

**Comment by winlinvip** [comment]
You can use HTTP API directly: http://www.ossrs.net:1985/api/v1/summaries

**Comment by winlinvip** [comment]
SRS3 may translate srs console project.

**Comment by winlinvip** [comment]
Fixed.
