### ISSUE TITLE
ubuntu1804 编译nginx时报错

### ISSUE THREAD

**Issue by yeruicsy** [ossrs/srs#1185]
src/core/ngx_murmurhash.c: In function ‘ngx_murmur_hash2’:
src/core/ngx_murmurhash.c:37:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[2] << 16;
         ~~^~~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:38:5: note: here
     case 2:
     ^~~~
src/core/ngx_murmurhash.c:39:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[1] << 8;
         ~~^~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:40:5: note: here
     case 1:
     ^~~~
cc1: all warnings being treated as errors
objs/Makefile:429: recipe for target 'objs/src/core/ngx_murmurhash.o' failed
make[1]: *** [objs/src/core/ngx_murmurhash.o] Error 1
make[1]: Leaving directory '/opt/srs/trunk/objs/nginx-1.5.7'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
build nginx-1.5.7 failed, ret=2

**Comment by winlinvip** [comment]
NGINX issue.
