### ISSUE TITLE
SRS的Security规则能否添加网段？

### ISSUE THREAD

**Issue by 2505587** [ossrs/srs#1190]
SRS的Security规则能否添加网段？比如 allow play 192.168.0.0/16;以增加添加规则的方便性。

**Comment by hping16** [comment]
Yes, it is possible. You need to modify the source code yourself in order to provide support.

`TRANS_BY_GPT3`

**Comment by 2505587** [comment]
I am a coding novice, could I trouble the experts to help me with the coding?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS3 may enhance the capability of this Security support network segment.

`TRANS_BY_GPT3`

**Comment by Morris-Mao** [comment]
When will this feature be fixed?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
建议使用回调实现灵活的验证，而不是在SRS中实现这种复杂功能。

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/pull/2914
