### ISSUE TITLE
DVR: Support Cloud Storage, 支持直接录制到云存储

### ISSUE THREAD

**Issue by ibanezsc** [ossrs/srs#1193]
流媒体服务器的云存储功能是一个必要的功能。不知道会不会增加

**Comment by winlinvip** [comment]
Can you please provide a detailed description of what a scenario for storing data in cloud storage would look like? Can you provide an example?

`TRANS_BY_GPT3`

**Comment by ibanezsc** [comment]
For example, using SRS as a streaming server, if you want to save the RTMP data received from the streaming service, the format can be FLV/MP4 or H264, but you don't want to manage the stored files yourself. Instead, you want to use third-party cloud storage for storage, such as major cloud platforms. How should this scenario be best handled?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Understood, I will first consider supporting recording to Alibaba Cloud storage and conduct some research.

`TRANS_BY_GPT3`

**Comment by robertluoxu** [comment]
I'm not sure if it is already supported now.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
云存储对接是业务问题，所以不在SRS做，而是在SRS云服务器做，用的nodejs实现。

SRS云服务器支持录制到了腾讯云的COS，参考 [云录制](https://mp.weixin.qq.com/s/UXR5EBKZ-LnthwKN_rlIjg)，对应SRS云服务器版本是[srs-terraform v1.0.113](https://github.com/ossrs/srs/issues/2856#changelog)

**Comment by winlinvip** [comment]
Using cloud SRS support, refer to [srs-cloud](https://github.com/ossrs/srs-cloud).

`TRANS_BY_GPT3`
