### ISSUE TITLE
使用srs-librtmp收流的文件头和发的流头不一致

### ISSUE THREAD

**Issue by shiguijuan** [ossrs/srs#1194]
![image](https://user-images.githubusercontent.com/40820029/43451432-849d5658-94e7-11e8-9585-342cd5c200f0.png)
如上图，左边收到的流和右边发的流头端有一段不一样，这个64 00...这是srs-librtmp新加上的么，代表什么含义？我看每次发流这一段都会不一样？解析的时候怎么确定就是sps/pps等？主要是这段含义不清楚，后续解析工作不清楚怎么搞。

**Comment by winlinvip** [comment]
详细参考打包流程，可以调试下。
