### ISSUE TITLE
Chinese inteface

### ISSUE THREAD

**Issue by ralfeus** [ossrs/srs#1196]
Hi.
I've installed fresh SRS and whole web interface is in Chinese. Is there any way to switch to English?
Previous issue #1180 has response but it's not understandable. Moreover if I try to open console on my host (http://ubuntu:1985/console) I get "Not found" page.
In issue #1184 it was suggested how to install console, which turned out to be separate project. I did that but it's Chinese as well and I've found no way to change language to English. I've checked ng_index.html file and it seems Chinese texts are hardcoded into it. 

Additionally I'd say it's not a good practice to close issue before it's confirmed it's resolved.

**Comment by winlinvip** [comment]
DUP to #1184
