### ISSUE TITLE
如何定时检测SRS某一个流是否已断开

### ISSUE THREAD

**Issue by yinjianfeng** [ossrs/srs#1198]
直播的时候，如果http回调接口调用失败，就会出现黑屏的直播间。
腾讯云的做法是定期检测流媒体的状态。
我想知道SRS能否也这样做？该如何处理呢?
我估计很多小伙伴也碰到过类似的问题。

**Comment by winlinvip** [comment]
可以检测流的fps。不能准确知道流是没有推，还是这一时刻没有推，马上就开始推。
