### ISSUE TITLE
如何实现源的切换过程中不中断用户播放？

### ISSUE THREAD

**Issue by Anduin2017** [ossrs/srs#1199]
向RTMP推流的程序（ffmpeg）会依次将视频列表推流，但问题在于：推流的过程中，一个视频结束后，会有极小的一段时间中断向SRS推流。

观察到的现象：
> 即使是很短的时间中断，用户观看到的视频都会卡住不再播放。必须重新加载播放器才能继续播放。

期待的现象：
> 当极短暂的时间里没有向SRS推流时，用户应当能够连贯的继续播放。

环境信息：
> Ubuntu 18.04
> SRS当前master分支

部署方式：
> RTMP向SRS推流，SRS使用FLV向用户分发。
> 使用bilibili/flv.js来在浏览器中为用户解码FLV。

配置文件：
```
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }
}

```

**Comment by winlinvip** [comment]
可能是切换编解码头后的问题，这个是播放器的问题。
