### ISSUE TITLE
FRSC：支持百毫秒级延迟，可替换的快速通道技术

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#120]
https://github.com/winlinvip/simple-rtmp-server/issues/120

支持百毫秒级延迟，可替换的快速通道技术
Support <500ms latency, FRSC(fast RTMP-compatible stream channel tech)

百毫秒级延迟，需要在RTMP机制上改进现有机制：
1. 考虑用udp代替tcp，在编码器发送，服务器内部，以及客户端传输。支持可切换的udp/tcp机制，譬如只有客户端使用tcp/RTMP，其他都是udp私有协议。
2. 考虑非interlaced媒体流传输：编码器[BLE](https://github.com/wenjiegit/Bull-Live-Encoder)支持非interlaced的输出，即编码器部分的音频流时间戳单增，视频流单增，但是不混合单增。一般编码器混合单增会增加延迟，服务器内部也不混合单增(interlaced)，而是在边缘服务器或者在客户端（自己的客户端）来混合视频和音频。
3. 考虑io机制代替超时机制：目前服务器发包的逻辑是，先等待客户端的控制消息300毫秒，然后将所有待发的包一起发给客户端，这样会有300毫秒的延迟，且每一级上会有所增加（符合平均概率）。若将等待300毫秒的超时机制，改为io机制，即将发包的“写”事件，变成io的读事件，这样就可以等待两个fd，看是客户端有消息，还是有消息要写。
4. 丢包机制：考虑在边缘，或者编码器支持丢包，控制延迟在百毫秒级别。即500毫秒以内。若客户端为flash，基本上延迟可以在300毫秒左右，若服务器控制延迟在200毫秒，可以将系统的延迟控制在500毫秒。若客户端是自己的客户端，可以将延迟控制更低（服务器端控制为200毫秒之内）。
5. 标准机制的回滚：应该考虑支持标准RTMP，譬如，在编码器/服务器集群内部使用低延迟的分发机制，若发现是flash客户端，边缘应该将视频和音频流混淆，保持时间戳单增后发送给客户端。

总之，支持百毫秒级别延迟需要一整套机制，在RTMP的基础上定制部分系统。同时，应该考虑兼容标准RTMP。因此，系统的主要目标是建立快速的通道，将延迟控制在百毫秒级别，同时在快速通道的任意位置支持通用方案的对接。

**Comment by lileiseven** [comment]
This is awesome, when will it be scheduled for development?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The player may not be able to support streaming playback at the millisecond level.

`TRANS_BY_GPT3`

**Comment by lileiseven** [comment]
According to this train of thought, can Flash player achieve it? 
For interactive live streaming in online education, low latency is required, ideally around 1 second.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
From encoding to distribution to playback, it should be impossible for Flash to achieve within 1 second.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It's impossible for normal TCP to make it, there are some possible ways:

1. Use TCP BBR.
1. Use UDP protocol.

**Comment by lidp888** [comment]
> https://github.com/winlinvip/simple-rtmp-server/issues/120
> 
> Support for sub-millisecond latency, replaceable fast channel technology.
> Support <500ms latency, FRSC(fast RTMP-compatible stream channel tech)
> 
> Sub-millisecond latency, improvement of existing mechanisms on the RTMP protocol is required:
> 
> 1. Consider using UDP instead of TCP for encoding, server internal communication, and client transmission. Support switchable UDP/TCP mechanisms, for example, only the client uses TCP/RTMP while others use UDP private protocols.
> 2. Consider non-interlaced media stream transmission: The encoder [BLE](https://github.com/wenjiegit/Bull-Live-Encoder) supports non-interlaced output, which means the audio stream timestamp in the encoder increases monotonically, the video stream increases monotonically, but they are not mixed together. Generally, encoder mixing increases latency, and the server does not mix (interlace) internally, but instead mixes video and audio at the edge server or on the client side (own client).
> 3. Consider using IO mechanism instead of timeout mechanism: Currently, the server's packet sending logic is to wait for the client's control message for 300 milliseconds, and then send all pending packets to the client together. This causes a delay of 300 milliseconds, which increases at each level (according to average probability). If the 300-millisecond timeout mechanism is changed to an IO mechanism, i.e., the "write" event of packet sending becomes an IO "read" event, it can wait for two file descriptors (fd) to determine whether there is a message from the client or a message to be written.
> 4. Packet loss mechanism: Consider supporting packet loss at the edge or in the encoder to control the delay within the sub-millisecond level, i.e., within 500 milliseconds. If the client is Flash, the delay can be around 300 milliseconds, and if the server controls the delay within 200 milliseconds, the system delay can be controlled within 500 milliseconds. If the client is the own client, the delay can be even lower (server-side control within 200 milliseconds).
> 5. Rollback to standard mechanism: Consider supporting standard RTMP, for example, using low-latency distribution mechanisms within the encoder/server cluster. If it is detected that the client is Flash, the edge should mix the video and audio streams and send them to the client after ensuring the monotonic increase of timestamps.
> 
> In summary, supporting sub-millisecond level latency requires a complete set of mechanisms and customization of certain parts of the system based on RTMP. At the same time, compatibility with standard RTMP should be considered. Therefore, the main goal of the system is to establish a fast channel, control the latency within the sub-millisecond level, and support integration with universal solutions at any point in the fast channel.



> Can the third point here be modified to be lower? Where specifically can it be changed? Performance can be sacrificed as a replacement.

`TRANS_BY_GPT3`
