### ISSUE TITLE
Fast loading first frame while maintaining ultra low latency stream

### ISSUE THREAD

**Issue by andryan** [ossrs/srs#1200]
Is it possible to achieve both objectives (fast loading first frame and ultra low latency stream) with current SRS RTMP implementation, if so how?  I’m already using realtime.conf and Daniulive SDK but stream loading time is around 3-5s.

**Comment by winlinvip** [comment]
The right way is to use gop cache in SRS, and refine the algorithm in player to process the cached gop.
