### ISSUE TITLE
是否可以实现web页面的直播-web页面的网络直播教室

### ISSUE THREAD

**Issue by ancin** [ossrs/srs#1205]
翻看了下文档，还是没有看太明白。这个项目是否可以做web页面的直播。
我的场景类似网络授课一样。通过web页面来组件网络教室直播。我想用Java开发web部分。
如果可以实现类似的功能，是否有详细的文档。

谢谢。

**Comment by winlinvip** [comment]
If there is no interaction, it is okay.

`TRANS_BY_GPT3`

**Comment by ancin** [comment]
@winlinvip Hello; you are experts in this field; I would like to ask, what kind of platform is used for the server platform if we want to achieve an interactive live streaming platform? Can platforms like red5, livego, live555, and Nginx achieve interactivity?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If a delay of 1 to 5 seconds is acceptable, use RTMP/FLV or other streaming media. If it needs to be within 1 second, use WebRTC.

`TRANS_BY_GPT3`

**Comment by icodemaker** [comment]
@winlinvip Is WebRTC supported now? How can I push a WebRTC stream to RTMP in Chrome? Can you please share your thoughts? Thank you!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS 4.0 has already supported live streaming and WebRTC interconversion.

`TRANS_BY_GPT3`
