### ISSUE TITLE
SRS服务停止，但ffmpeg进程没停

### ISSUE THREAD

**Issue by 2505587** [ossrs/srs#1206]
我今天在ubuntu16.04，centos1804上都装了srs2.0.255。执行service srs stop后，ffmpeg的推流进程却还存在。后来发现2.0.234，2.0.248这2个版本也有这个问题。但srs2.0.199是能在srs服务停止后，进程也跟着一起停止的。

**Comment by winlinvip** [comment]
Can you provide the steps to reproduce? Configuration file?

`TRANS_BY_GPT3`

**Comment by 2505587** [comment]
The downloaded file is: https://codeload.github.com/ossrs/srs/tar.gz/v2.0-r4. After downloading, unzip it and run ./configure --full; make; make install.

Add the following to srs.conf:
vhost out {
    ingest  cbn{
        enabled      on;
        input {
            type    stream;
           url     rtmp://*.*.*.*/live/*;
        }
        ffmpeg       ./objs/ffmpeg.src/_release/bin/ffmpeg;
        engine {
            enabled          off;
            output          rtmp://*.*.*.*/live/*;
        }
    } 
}

After executing 'service srs stop', this ffmpeg process is still running.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It seems that the FFMPEG process is not handling the signal. Let me confirm, it seems like SRS will send a SIGKILL signal if FFMPEG does not exit for a long time.

`TRANS_BY_GPT3`
