### ISSUE TITLE
当客户端使用http-flv播放视频流时，如何统计客户端数量？

### ISSUE THREAD

**Issue by lin557** [ossrs/srs#1208]
目前使用 http api (http://127.0.0.1:1985/api/v1/clients)进行查询时，只能查到rtmp连接的客户端数量，无法查到使用http-flv连接的客户端数据，请教有什么办法可以统计到。

排除使用 http callback 的onplay 与 onclose 方法。

**Comment by winlinvip** [comment]
HTTP API has a number of clients, maybe some were missed?

`TRANS_BY_GPT3`

**Comment by jymot** [comment]
I have also encountered this problem. Currently, I am temporarily using `http callback` to complete the statistics of client connections.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.
