### ISSUE TITLE
“视频流”的“在线人数”没有包含通过http flv播放的数量

### ISSUE THREAD

**Issue by canglongxiang** [ossrs/srs#1209]
通过调用srs提供的rest api：/api/v1/streams，返回的结果中，发现2个问题：
1、即使没有任何人观看，“在线人数”的值都为“1”。
2、使用http flv的的播放地址进行观看是，“在线人数”的值没有增加。

**Comment by wnpllrzodiac** [comment]
1. The person with 1 is the rtmp publisher. So as long as it is an rtmp stream, there is at least one person who is the publisher.
2. It seems that 2.x does not have statistics for the number of flv viewers.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It seems that SRS2 has already counted the number of viewers for the flv playback. Please double-check.

`TRANS_BY_GPT3`

**Comment by searKing** [comment]
> It seems that SRS2 has already counted the number of viewers for the flv playback. Please double-check.

Just checked with the latest version on the master branch, regardless of the number of http-flv clients, the "clients" value always remains 1.

`TRANS_BY_GPT3`

**Comment by yangxiangzhi** [comment]
How can this problem be solved?

`TRANS_BY_GPT3`

**Comment by yangxiangzhi** [comment]
FLV has not been counted at all. I now want to delete a client that plays FLV, but there is no way!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed by @duiniuluantanqin in SRS 4.0
