### ISSUE TITLE
SRS的录制能否添加API 接口？

### ISSUE THREAD

**Issue by AmpletecGo** [ossrs/srs#1211]
如题：
接口 start 参数，那一路FLV，生成名字
接口 end  参数，那一路FLV

**Comment by winlinvip** [comment]
This means that the server needs to maintain its state, such as what to do after a restart?
Currently, the DVR of SRS3 can be applied at the stream level, but it seems more complicated. The RAW API can modify the configuration file to specify which streams to record, but it may encounter the problem of the configuration file continuously growing.

`TRANS_BY_GPT3`

**Comment by tdwu** [comment]
If the srs positioning is at the operational level, it is hoped that an API interface can be added to initiate recording. At the same time, forwarding to a certain server and pulling the stream from a certain server are also common scenarios that require an API interface.

`TRANS_BY_GPT3`

**Comment by al00000** [comment]
srs4.0+ version, is there an API for on-demand recording?

`TRANS_BY_GPT3`

**Comment by Blacklion55** [comment]
- [ ] [_******__[]()__******_]()```
> > ````
```

**Comment by al00000** [comment]
I don't know what the comment upstairs is about. I have already written a set of logic to control the start and end of recording for a certain stream. In fact, it is the same as the video recording process of Alibaba Cloud.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #1577
