### ISSUE TITLE
Cannot load M3U8 file: Crossdomain access denied

### ISSUE THREAD

**Issue by khachuong** [ossrs/srs#1214]
I tried to play my HLS stream but the player (JWt): http://*.*.*.*/live/demo.m3u8 always said that: No 'Access-Control-Allow-Origin' header is present on the requested resource 

My srs.conf also have:

`
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    crossdomain on;
}
`
I also added Access-Control-Allow-Origi to my Nginx configuration:

`
location / {
            root   html;
            index  index.html index.htm;
            add_header 'Cache-Control' 'no-cache';
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Expose-Headers Content-Length;
  
        }
        location /live/ {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root html/;
            add_header Access-Control-Allow-Origin *;
            add_header Access-Control-Expose-Headers Content-Length;
        }
`

Please help me solve this issue. Thank you very much!

**Comment by winlinvip** [comment]
SRS fixed it.
