### ISSUE TITLE
用户从边缘服务器播放时，主服务器 on_play 回调"param":"" 为空

### ISSUE THREAD

**Issue by flfq** [ossrs/srs#1215]
如果直接从主服务器播放  httpapi 回调 on_play  的 "param":"" 不为空

**Comment by flfq** [comment]
If the playback address is
rtmp://xxxx.xxx.xxx.xxx/app/test?token=aaaaaaaaaaaaaaaaaa
When playing from the edge server,
if the main server's HTTP callback does not have ?token=aaaaaaaaaaaaaaaaaa,
it will result in the inability to authenticate the user.

`TRANS_BY_GPT3`

**Comment by flfq** [comment]
The version is 2.0.

`TRANS_BY_GPT3`

**Comment by flfq** [comment]
From the source code, it appears that the URL of the edge server is missing the param content when pulling the stream from the main server.

`TRANS_BY_GPT3`

**Comment by flfq** [comment]
Main Server --> Edge Server
Refer to the official original configuration for setup, very simple.

If a user plays rtmp://xxxx.xxx.xxx.xxx/app/test?token=aaaaaaaaaaaaaaaaaa
If playing from the main server, the on_play function of HTTPCallback works fine and receives the param parameter.
If playing from the edge server, the on_play param in the HTTPCallback provided by the main server is empty.

The version being used is 2.0 release.

There is also an update needed for the on_publish function in the HTTPCallback documentation of version 2.0. You have already updated it a few days ago by adding the param parameter.

`TRANS_BY_GPT3`

**Comment by doudoustrongly** [comment]
When accessing the edge server, not only the token parameter of the onplay event is empty, but also the token of other events such as onconnect is empty. Has this issue been fixed? 
I downloaded the latest version release (2.0.258), but the problem still exists. 
Thank you.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
When the edge server returns to the source, it does not carry token information, so the verification should be done using the edge callback instead of the origin server callback verification.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Even if the edge returns to the source with param information, it will not carry param information when subsequent connections are made. Usually, only the first connection will return to the source.

`TRANS_BY_GPT3`

**Comment by lxm1007** [comment]
> 边缘服务器回源时，不会带token的信息，因此验证要用边缘的回调而不是用源站的回调验证。

如何指定使用边缘的回掉呢 感觉 配置上了 还是走的源站的 flv边缘
