### ISSUE TITLE
How to push live stream to Facebook?

### ISSUE THREAD

**Issue by khachuong** [ossrs/srs#1216]
I am live streaming on my mobile app through RTMP protocol, how do I push that stream to Facebook live streaming? Thank you very much!

**Comment by winlinvip** [comment]
> Is there a way to do this? I tried adding to the srs.conf and the logs said that the application directive is unsupported. Isn't the underlaying structure of srs nginx?
> 
> application live {
> live on;
> record off;
> push rtmp://live-api.facebook.com:80/rtmp/key;
> }

Please read wiki.

**Comment by winlinvip** [comment]
> I am live streaming on my mobile app through RTMP protocol, how do I push that stream to Facebook live streaming? Thank you very much!

You can try stream param, SRS edge to push to facebook server.
