### ISSUE TITLE
SRS DVR segment 时间分割问题

### ISSUE THREAD

**Issue by Sjhzjxc** [ossrs/srs#1217]
环境是docker里的ossrs/srs:2.0.255，以下是dvr配置：
```
dvr
 {
    enabled                 on;
    dvr_path                /data/[app]/[stream]/[2006]-[01]-[02]/[15]_[04]_[05].flv;
    dvr_plan                segment;
    dvr_duration            30;
    dvr_wait_keyframe       on;
    time_jitter             full;
}
```
问题是，在前一个文件*.flv.tmp，未获取到足够时长的视频时，断开推送到srs的流之后，过一段时间再进行推流，新的流会先去补足前一个流的时间，再重新产生新的文件。这就会导致，一个视频文件可能包含着两个可能间隔较久的视频片段。然而我的想法是，推流停止，则*.flv.tmp保存为flv文件，其实就是segment和session的结合，平时按时间分割，最后推流停止时，文件就直接保存为flv。
请问，是我的配置文件的问题，还是现如今的版本并没有实现这个功能。
另外，3.0也是这样。

**Comment by wnpllrzodiac** [comment]
你看下以前的 issue.有提到过解决方法的

**Comment by Sjhzjxc** [comment]
#1108
