### ISSUE TITLE
在AIO-3399J开发版下core dump

### ISSUE THREAD

**Issue by qazxcv322** [ossrs/srs#1219]
直接在开发版上编译了srs,然后执行的时候core dump,使用GDB调试报如下错误
> Program received signal SIGSEGV, Segmentation fault.
> 0x000000000054705c in st_usleep (usecs=549755810176) at sync.c:133
> 133	  if (me->flags & _ST_FL_INTERRUPT) {

**Comment by winlinvip** [comment]
ST不支持嵌入式，linux服务器，可以看 https://github.com/ossrs/state-threads/tree/srs#usage

**Comment by winlinvip** [comment]
Dup to #1282
