### ISSUE TITLE
gcc 7.3 on Ubuntu 18.04 compile http-parser-2.1 error

### ISSUE THREAD

**Issue by aggresss** [ossrs/srs#1220]
build http-parser-2.1
patching file Makefile
cc -I. -DHTTP_PARSER_STRICT=1  -Wall -Wextra -Werror -O0 -g  -c http_parser.c
http_parser.c: In function 'http_parser_parse_url':
http_parser.c:2093:18: error: this statement may fall through [-Werror=implicit-fallthrough=]
         found_at = 1;

http_parser.c:2096:7: note: here
       case s_req_server:

cc1: all warnings being treated as errors
Makefile:40: recipe for target 'http_parser.o' failed
make: *** [http_parser.o] Error 1
build http-parser-2.1 failed, ret=2

**Comment by huanghe2015** [comment]
Dup for  #1159 #1065

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/a554dd85e110ca4ce9ec35423c9886edaff90371 in 2.0.263
