### ISSUE TITLE
Export Srs3.0 Librtmp 编译错误

### ISSUE THREAD

**Issue by atlantis414** [ossrs/srs#1226]
系统 ubuntu 16.04 x64 和 ubuntu 18.04
按照 [https://github.com/ossrs/srs/wiki/v3_CN_SrsLibrtmp](url) ,运行
`dir=/home/winlin/srs-librtmp &&
rm -rf $dir &&
./configure --export-librtmp-single=$dir &&
cd $dir && gcc example.c srs_librtmp.cpp -g -O0 -lstdc++ -o example && 
strip example && ./example`

在ubuntu16.04和18.04都编译不通过
` Is OSX: NO
build files  src/core/srs_core.cpp src/core/srs_core_autofree.cpp src/core/srs_core_performance.cpp src/core/srs_core_mem_watch.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
build files  src/kernel/srs_kernel_error.cpp src/kernel/srs_kernel_log.cpp src/kernel/srs_kernel_buffer.cpp src/kernel/srs_kernel_utility.cpp src/kernel/srs_kernel_flv.cpp src/kernel/srs_kernel_codec.cpp src/kernel/srs_kernel_io.cpp src/kernel/srs_kernel_consts.cpp src/kernel/srs_kernel_aac.cpp src/kernel/srs_kernel_mp3.cpp src/kernel/srs_kernel_ts.cpp src/kernel/srs_kernel_stream.cpp src/kernel/srs_kernel_balance.cpp src/kernel/srs_kernel_mp4.cpp src/kernel/srs_kernel_file.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
build files  src/protocol/srs_protocol_amf0.cpp src/protocol/srs_protocol_io.cpp src/protocol/srs_rtmp_stack.cpp src/protocol/srs_rtmp_handshake.cpp src/protocol/srs_protocol_utility.cpp src/protocol/srs_rtmp_msg_array.cpp src/protocol/srs_protocol_stream.cpp src/protocol/srs_raw_avc.cpp src/protocol/srs_rtsp_stack.cpp src/protocol/srs_http_stack.cpp src/protocol/srs_protocol_kbps.cpp src/protocol/srs_protocol_json.cpp src/protocol/srs_kafka_stack.cpp src/protocol/srs_protocol_format.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
build files  src/libs/srs_librtmp.cpp src/libs/srs_lib_simple_socket.cpp src/libs/srs_lib_bandwidth.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
build files  src/core/srs_core.cpp src/core/srs_core_autofree.cpp src/core/srs_core_performance.cpp src/core/srs_core_mem_watch.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
build files  src/kernel/srs_kernel_error.cpp src/kernel/srs_kernel_log.cpp src/kernel/srs_kernel_buffer.cpp src/kernel/srs_kernel_utility.cpp src/kernel/srs_kernel_flv.cpp src/kernel/srs_kernel_codec.cpp src/kernel/srs_kernel_io.cpp src/kernel/srs_kernel_consts.cpp src/kernel/srs_kernel_aac.cpp src/kernel/srs_kernel_mp3.cpp src/kernel/srs_kernel_ts.cpp src/kernel/srs_kernel_stream.cpp src/kernel/srs_kernel_balance.cpp src/kernel/srs_kernel_mp4.cpp src/kernel/srs_kernel_file.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
build files  src/protocol/srs_protocol_amf0.cpp src/protocol/srs_protocol_io.cpp src/protocol/srs_rtmp_stack.cpp src/protocol/srs_rtmp_handshake.cpp src/protocol/srs_protocol_utility.cpp src/protocol/srs_rtmp_msg_array.cpp src/protocol/srs_protocol_stream.cpp src/protocol/srs_raw_avc.cpp src/protocol/srs_rtsp_stack.cpp src/protocol/srs_http_stack.cpp src/protocol/srs_protocol_kbps.cpp src/protocol/srs_protocol_json.cpp src/protocol/srs_kafka_stack.cpp src/protocol/srs_protocol_format.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
build files  src/libs/srs_librtmp.cpp src/libs/srs_lib_simple_socket.cpp src/libs/srs_lib_bandwidth.cpp to /home/winlin/srs-librtmp/srs_librtmp.cpp
gcc example.c srs_librtmp.cpp -g -O0 -lstdc++ -o example
/usr/bin/ld: /tmp/cciMrCIg.o: undefined reference to symbol 'pow@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
(cd /home/winlin/srs-librtmp && gcc example.c srs_librtmp.cpp -g -O0 -lstdc++ -o example && ./example && rm -f example)
failed to compile example.

`

**Comment by atlantis414** [comment]
解决办法:
1.搜索generate-srs-librtmp-single.sh文件,修改
`SRS_SINGLE_LIBRTMP_COMPILE='gcc example.c srs_librtmp.cpp -g -O0 -lstdc++ -o example'`
为
`SRS_SINGLE_LIBRTMP_COMPILE='gcc example.c srs_librtmp.cpp -g -O0 -lstdc++ -o example -lm'`
2.执行下面脚本
`dir=/home/winlin/srs-librtmp &&
rm -rf $dir &&
./configure --export-librtmp-single=$dir &&
cd $dir && gcc example.c srs_librtmp.cpp -g -O0 -lstdc++ -o example -lm && 
strip example && ./example`

**Comment by atlantis414** [comment]
测试一下,编译出来的.so并不能使用

**Comment by winlinvip** [comment]
为啥不能使用？

**Comment by atlantis414** [comment]
> 为啥不能使用？

creatertmp 这一步就失败,目前srs2.0.255版本的librtmp使用一切正常

**Comment by atlantis414** [comment]
> SRS2正常，SRS3不可用？能否提供重现步骤呢？
srs2.0完全正常,可以顺利按照wiki的步骤
`dir=/home/winlin/srs-librtmp &&
rm -rf $dir &&
./configure --export-librtmp-single=$dir &&
cd $dir && gcc example.c srs_librtmp.cpp -g -O0 -lstdc++ -o example && 
strip example && ./example`
得到srs_librtmp.h和srs_librtmp.cpp文件,然后使用swig编译成.so
如果说唯一不同点就是srs3.0的librtmp按照wiki是编译不成功的,所以我查了一下资料按照2楼添加了 -lm参数最后编译成功.
但是最后调用的时候srs3.0执行第一步creatertmp时提示failed

**Comment by atlantis414** [comment]
> 我正在考虑在SRS3去掉对于srs-librtmp的支持。SRS该收缩下目标了，只做linux media server。

那很遗憾了,在交通运输部的协议中把视频流拆成一个个h264的包进行传输,srs-librtmp是我当初唯一找到的一个简单好用的工具把单个h264数据包转变成流发送给SRS,也容易编译成.so文件供其他语言调用.

**Comment by winlinvip** [comment]
暂时srs-librtmp主要用srs2导出。

**Comment by njliang** [comment]
编译srs-librtmp 3.0 的确是有问题的
平台：ubuntu18.04
