### ISSUE TITLE
阿里云tomcat下搭建srsplayer播放器 无法播放

### ISSUE THREAD

**Issue by tengfeineu** [ossrs/srs#1231]
搭建地址为：http://47.93.244.13:9090/mmi/news/research/players/srs_player.html?server=47.93.244.13
控制台一直报如下的问题
[Thu Sep 27 21:03:56 GMT+0800 2018][srs-player][100] stream is null, ignore timer event.

通过http://winlinvip.github.io/srs.release/trunk/research/players/srs_player.html?server=192.168.1.170# 就可以播放rtmp文件流

**Comment by winlinvip** [comment]
无法重现。
