### ISSUE TITLE
srs是否支持服务器主动断开rtmp推流连接

### ISSUE THREAD

**Issue by wangdewei** [ossrs/srs#1234]
应用场景：摄像头通过rtmp推流到srs服务器，用户使用hls协议拉流。当用户停止拉流时（超过某个时间没有向服务器发起请求），srs服务器主动断开rtmp连接。

请问srs是否支持上述功能？

**Comment by juntaoliu** [comment]
The mode you mentioned is not supported.

However, for flv or rtmp playback, configuring it as a pull mode can roughly achieve the scenario you mentioned. But for hls playback, it is not supported and requires development.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This intention should be to save bandwidth for streaming, and the key point is how to make RTMP push again when the user plays it again.

This belongs to special business logic and needs to be developed by oneself.

`TRANS_BY_GPT3`
