### ISSUE TITLE
想自己加一下出 UDP TS 的 app ，是否照 HLS app 改一下就可以了

### ISSUE THREAD

**Issue by jhkwei** [ossrs/srs#1241]
局域网可能要有下 UDP TS, 照 HLS app 改一下出 UDP TS 应该没有问题，问题就是怎么控制 PCR ,也就是按时发送 TS 包，请给一点指导意见

**Comment by winlinvip** [comment]
没有懂你的意思。

**Comment by jhkwei** [comment]
就是我想输出MpegTS over Udp流
