### ISSUE TITLE
vlc播放rtmp流会卡住

### ISSUE THREAD

**Issue by 759325100** [ossrs/srs#1242]
服务端使用rtmp.conf、demo.conf、realtime.conf配置文件启动，摄像头推流正常，打开vlc播放器访问rtmp流，刚打开一切正常播放一段时间，过一会（可能几十秒，可能几分钟）vlc画面就卡住了，当我重新启动vlc客户端再次播放就又可以正常播放一会。想请教一下这个可能是哪里的问题。

**Comment by 759325100** [comment]
我在同一个局域网中，使用OBS推流到srs服务器，然后在srs服务器本地拉流，延迟就有十几秒。

**Comment by winlinvip** [comment]
请阅读低延迟相关的WIKI。

**Comment by JalySN** [comment]
我也遇到类似的问题。打开vlc debug日志，发现会刷

avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
main warning: picture is too late to be displayed (missing 15327 ms)
main warning: picture is too late to be displayed (missing 15283 ms)
main warning: picture is too late to be displayed (missing 15262 ms)
main warning: picture is too late to be displayed (missing 15219 ms)
main warning: picture is too late to be displayed (missing 14831 ms)
avcodec warning: More than 11 late frames, dropping frame
avcodec warning: More than 11 late frames, dropping frame
avcodec warning: More than 11 late frames, dropping frame
avcodec warning: More than 11 late frames, dropping frame
