### ISSUE TITLE
You should support Windows

### ISSUE THREAD

**Issue by empaguiaOA** [ossrs/srs#1244]
You have already supported Linux and Mac OS already...
now it's time to support windows...

![image](https://user-images.githubusercontent.com/28289169/47002869-a16ad980-d160-11e8-9e20-0522694c2923.png)

**Comment by winlinvip** [comment]
No windows, linux only.

**Comment by winlinvip** [comment]
Dup to #2532 We're working on [feature/windows ](https://github.com/ossrs/srs/tree/feature/windows)
