### ISSUE TITLE
SRS start failed

### ISSUE THREAD

**Issue by Handsome1080P** [ossrs/srs#1248]
In log no any errors,why start faild?I am using arm server.This is the log.
![TIM截图20181020220410.png](https://i.loli.net/2018/10/20/5bcb363c6a3be.png)
![TIM截图20181020220353.png](https://i.loli.net/2018/10/20/5bcb363d28207.png)

**Comment by winlinvip** [comment]
Crashed?

**Comment by jckouame** [comment]
i have the same crash with OSX Mojave

**Comment by mozillo** [comment]
> i have the same crash with OSX Mojave

+1

**Comment by jinzequn** [comment]
Same crashed.

**Comment by jinzequn** [comment]
https://github.com/ossrs/srs/issues/1282#issuecomment-445539513 resloved

**Comment by winlinvip** [comment]
Lastest OXS is not supported. Please use docker https://github.com/ossrs/srs-docker/tree/centos#usage
