### ISSUE TITLE
srs/trunk/research/players/srs_player.html select_buffer not defined

### ISSUE THREAD

**Issue by Sora-Shiro** [ossrs/srs#1252]
In https://github.com/ossrs/srs/blob/master/trunk/research/players/srs_player.html
line 499
commit b19702f669335616c9b3cfa6f43de7b7cdf62d86

![image](https://user-images.githubusercontent.com/12219040/47646041-a773a800-dbad-11e8-8cb7-a3102e11091a.png)

Need to add function defined or player won't work well, according to demo:
```javascript
function select_buffer(buffer_time) {
        var bt = buffer_time;
        var bt_id = "#btn_bt_" + bt.toFixed(1).replace(".", "_");
        select_buffer_time(bt_id, bt);
}
```

**Comment by winlinvip** [comment]
Fixed in SRS3.
