### ISSUE TITLE
srs start failure

### ISSUE THREAD

**Issue by RichsJeson** [ossrs/srs#1257]
centos 7.4 上搭建srs服务，执行/etc/init.d/srs start的时候显示：
[srs.log](https://github.com/ossrs/srs/files/2545642/srs.log)

SRS not start.                                             [FAILED]
Starting SRS...                                            [  OK  ]
SRS start failed                                           [FAILED]
see /usr/local/srs/objs/srs.log                            [FAILED]

**Comment by winlinvip** [comment]
请给下日志。
