### ISSUE TITLE
轻负载应用，有没有可能把延迟降低到2秒以内？

### ISSUE THREAD

**Issue by luxin88** [ossrs/srs#1258]
我目前有个应用，是把户外手机上的视频传送到室内大屏幕上，手机端用rtmp推流到srs，然后电脑上通过obs拉取srs上的流再投影到屏幕上，目前测试，基于局域网（三端都在同个局域网内，ping延迟<1ms）延迟差不多在2秒的样子，这样的环境有没有可能把延迟降低到2秒以内，甚至1秒以内

**Comment by FreshLuoBoGan** [comment]
Hello, how is your conf configured?

Currently, I am streaming RTMFP from my camera to SRS and retrieving SRS video through VLC. With the lowest latency configuration in the conf, the delay is 5 seconds in the first 5 minutes, gradually decreasing within the next 5 minutes, and reaching 1 second after 5 minutes (using the min.delay.com configuration). I want to reduce the delay to the minimum right from the beginning.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
TCP delay is not stable, and it is not the best choice for the solution. Consider using WebRTC.

`TRANS_BY_GPT3`
