### ISSUE TITLE
从git上clone下来的代码编译报错

### ISSUE THREAD

**Issue by zirandeai2011** [ossrs/srs#1264]
文件：srs_app_recv_thread.cpp 555行
ISrsHttpMessage* req = NULL;

提示ISrsHttpMessage未声明

**Comment by hknakata** [comment]
我都有这个问题，用Mac OS的，有谁可以指教一下～

**Comment by hrxu01** [comment]
同样的问题， 求帮助

**Comment by winlinvip** [comment]
OXS没法支持了，请考虑用docker跑CentOS：https://github.com/ossrs/srs-docker/tree/centos#usage
