### ISSUE TITLE
regex for IP address deny/allow

### ISSUE THREAD

**Issue by ashah7** [ossrs/srs#1272]
Is possible to allow or deny based on regex
e.g allow only machines with a 10. IP address to play/publish?
allow 10.*.*.*

**Comment by juntaoliu** [comment]
> Is possible to allow or deny based on regex
> e.g allow only machines with a 10. IP address to play/publish?
> allow 10._._.*

you could implement it by yourself.  
filepath: srs/trunk/src/app/srs_app_security.cpp
functions: SrsSecurity::allow_check(), SrsSecurity::deny_check()

**Comment by winlinvip** [comment]
Postpone to SRS4

**Comment by winlinvip** [comment]
Postpone to SRS5

**Comment by winlinvip** [comment]
Please use http callback to do this.

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/pull/2914
