### ISSUE TITLE
bug in srs_app_config.cpp SRS_CONF_DEFAULT_HLS_ON_ERROR_IGNORE="continue"

### ISSUE THREAD

**Issue by ssddawei** [ossrs/srs#1278]
> SRS 2.0_r5 , src_app_config.cpp line 81:
> #define SRS_CONF_DEFAULT_HLS_ON_ERROR_IGNORE "continue"
> #define SRS_CONF_DEFAULT_HLS_ON_ERROR_DISCONNECT "disconnect"
> #define SRS_CONF_DEFAULT_HLS_ON_ERROR_CONTINUE "continue"

================
#define SRS_CONF_DEFAULT_HLS_ON_ERROR_IGNORE "continue" 
是否应该为 "ignore" ?

**Comment by winlinvip** [comment]
Fixed in SRS3.
