### ISSUE TITLE
SRS2.0 客户端连接数查询有问题

### ISSUE THREAD

**Issue by atlantis414** [ossrs/srs#1280]
SRS2.0.258;
使用官方提供的视频源,同时打开20路客户端
在REST API工具中查询  http://ossrs.net:1985/api/v1/clients?start=0&count=1000
返回的客户端数量仍旧只有10个

**Comment by ddwla4** [comment]
There is such an API, please provide the address.

`TRANS_BY_GPT3`

**Comment by atlantis414** [comment]
> There is such an API, please provide the address.

https://github.com/ossrs/srs/wiki/v3_CN_HTTPApi

`TRANS_BY_GPT3`

**Comment by txavatar** [comment]
@atlantis414 The API documentation states that only the first 10 can be retrieved, so it seems that only 10 can be obtained.

`TRANS_BY_GPT3`

**Comment by atlantis414** [comment]
> According to the API documentation, it says that only the first 10 can be obtained, so it means that only 10 can be retrieved.

> The documentation states that by default, it retrieves 10 items, but you can specify the count parameter yourself. It seems pointless to specify a parameter for less than 10 items.
Currently, it is ineffective for me as it cannot exceed 10 items...
You can try it yourself and let me know if it is successful.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.
