### ISSUE TITLE
[authentication] can not push rtmp with two parameters at uri

### ISSUE THREAD

**Issue by jhaoheng** [ossrs/srs#1281]
Hi 

`ffmpeg -re -stream_loop -1 -i ./test1.mp4 -vcodec libx264 -acodec aac -f flv rtmp://localhost/app?vhost=transcode&token=123/stream`

OSSRS can not get any streaming, when use two parameters at URI.

- version : 2.0 release5(2.0.258)

refer this post : https://github.com/ossrs/srs/wiki/v1_CN_DRM#token-authentication

**Comment by juntaoliu** [comment]
srs supports tcUrl as you mentioned here. maybe your command should be with  "\" before “&”?

**Comment by winlinvip** [comment]
Fixed in SRS3.
