### ISSUE TITLE
想问一下在http回调时，例如开始推流的时候发送的参数ip是指推流端的ip还是流服务器ip

### ISSUE THREAD

**Issue by ddwla4** [ossrs/srs#1283]
on_publish
# the request in the POST data string is a object encode by json:
        #       {
        #           "action": "on_unpublish",
        #           "client_id": 1985,
        #           "ip": "192.168.1.10", "vhost": "video.test.com", "app": "live",
        #           "stream": "livestream", "param":"?token=xxx&salt=yyy"
        #       }
这里的IP地址是指推流终端的IP，还是SRS服务器的IP？？

**Comment by RocFang** [comment]
客户端ip

**Comment by ddwla4** [comment]
谢谢。

**Comment by ddwla4** [comment]
>           客户端ip

谢谢
