### ISSUE TITLE
SRS2.0版本支持forward到多个节点吗？

### ISSUE THREAD

**Issue by ddwla4** [ossrs/srs#1284]
例如有一个marter节点，然后想同时推送到多个子节点。配置上能实现吗？多个子点IP用空格分隔开吗？？

**Comment by juntaoliu** [comment]
支持。forward ip1 ip2 ip3; 类似这样既可。空格分割。

**Comment by ddwla4** [comment]
>           支持。forward ip1 ip2 ip3; 类似这样既可。空格分割。

非常感谢
