### ISSUE TITLE
srs 在android和ubuntu上使用hls功能问题.

### ISSUE THREAD

**Issue by sevenzoe** [ossrs/srs#1287]
我将srs编译在android上使用.
编译命令:
./configure --with-arm-ubuntu12 --without-http-server --without-http-api --without-http-callback --without-ingest

srs版本: 2.0release, HASH : b0e91e8fe91f99ccd22287c17cc95677432adaf0

发现安卓上的srs的hls功能有点问题,rtmp功能没有问题。（ubuntu的srs测试过了，两种情况都没有问题）
1. 我采集桌面图像的时候，使用ffmpge 推送rtmp包上去，没有问题
2. 我采集摄像头图像的时候，使用ffmpge 推送rtmp包上去，存在问题

查了将近10天，一开始以为是系统时间的问题，后面发现不是的。

这是存在问题情况下的日志:(采集摄像头数据，发送rtmp)

![q c1ac xtn jf9uy8ddq6](https://user-images.githubusercontent.com/8321325/49792322-67d3da80-fd6d-11e8-9ca3-e05e302512f1.png)

这是没有问题情况下的日志:(采集桌面数据，发送rtmp)

![c__ n u069ym q zxbskcs](https://user-images.githubusercontent.com/8321325/49792348-7621f680-fd6d-11e8-98b1-170cc281e4a7.png)

客户端发送rtmp包的时候，发现：

1. 当采集数据是桌面的时候, AVPacket很大.
2. 当采集数据是摄像头的时候,AVPacket很小.

两种情况都可以确定这个AVPacket是正常的。在ubuntu上，同样去发送rtmp包，不存在情况.

例如存在情况的时候，ts生成路径是/home/A，我将ts生成的路径改为/home/B就存在这个情况了，我猜想是否跟本地写文件存在关系(因为ts需要写文件).

我确定两个路径的磁盘空间是够的，不存在磁盘空间满的情况

hls_cache->write_video()

**Comment by sevenzoe** [comment]
例如存在情况的时候，ts生成路径是/home/A，我将ts生成的路径改为/home/B就不存在这个情况了，我猜想是否跟本地写文件存在关系(因为ts需要写文件).

**Comment by ls306196689** [comment]
楼主，请教一下怎么样编译到android呢。我这边用arm编译器编完，在android上运行会闪退。stack smashing detected。

**Comment by sevenzoe** [comment]
> 楼主，请教一下怎么样编译到android呢。我这边用arm编译器编完，在android上运行会闪退。stack smashing detected。

./configure --with-arm-ubuntu12 --without-http-server --without-http-api --without-http-callback --without-ingest
make

**Comment by winlinvip** [comment]
https://github.com/ossrs/state-threads/tree/srs#branch-srs

Merge from [michaeltalyansky](https://github.com/michaeltalyansky/state-threads) and [xzh3836598](https://github.com/ossrs/state-threads/commit/9a17dec8f9c2814d93761665df7c5575a4d2d8a3), support [ARM](https://github.com/ossrs/state-threads/issues/1).
