### ISSUE TITLE
SRS3.0 got 'connect error code=1011 : parse message : grow buffer : read bytes : timeout 60000 ms' error after unpublish

### ISSUE THREAD

**Issue by hhdem** [ossrs/srs#1290]
version: 3.0
publisher: OBS
player: DPlayer
operation: 
Publish stream with OBS, and play it on a website with DPlayer. When I stop Streaming with OBS then I got these error messages 1 min later.

[2018-12-17 15:14:31.471][Error][13944][108][101] connect error code=1011 : parse message : grow buffer : read bytes : timeout 60000 ms
thread #108: parse_message() [src/service/srs_service_http_conn.cpp:89][errno=101]
thread #108: parse_message_imp() [src/service/srs_service_http_conn.cpp:142][errno=101]
thread #108: grow() [src/protocol/srs_protocol_stream.cpp:180][errno=101]
thread #108: read() [src/service/srs_service_st.cpp:305][errno=101]
(STREAM ioctl timeout)

**Comment by zhaoxingyun** [comment]
I encountered the same problem when using VLC to play m3u8.

`TRANS_BY_GPT3`

**Comment by lixiang6153** [comment]
Yes, I have encountered the same problem. How to solve it? I mean, it's not a network problem.

`TRANS_BY_GPT3`

**Comment by daxaxelrod** [comment]
Same here. 

[2020-09-29 00:11:02.634][Error][1][243][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [1][243]: do_cycle() [src/app/srs_app_http_api.cpp:1354][errno=62]
thread [1][243]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=62]
thread [1][243]: parse_message_imp() [src/service/srs_service_http_conn.cpp:156][errno=62]
thread [1][243]: grow() [src/protocol/srs_protocol_stream.cpp:179][errno=62]
thread [1][243]: read() [src/service/srs_service_st.cpp:483][errno=62](Timer expired)

**Comment by tangyongjiang** [comment]
I have got this error, too. But at last, I found it was a **network problem**. There is a firewall disabled  rtmp 
The problem was solved when I switched to using my phone's 4g network for an ap connection

**Comment by winlinvip** [comment]
@tangyongjiang 👍
