### ISSUE TITLE
Is there any way to live stream in mp4 format just like flv or aac with SRS library?

### ISSUE THREAD

**Issue by maheshjena1** [ossrs/srs#1291]
I have a few VR devices which require mp4 format to play video content.
I want to live stream from a camera to the VR headset.

I couldn't find any documentation which can be used for mp4 streaming with SRS library.
I also found that it's not easy to live stream in mp4 format as the header needs the content length, so we have to fragment the streaming.

Is it possible to do it with the SRS library?

Thanks,
Mahesh

**Comment by redknotmiaoyuqiao** [comment]
you can demuxer the h264 and acc data from mp4 format,than use librtmp or srs-librtmp to push the h264 and acc to srs.
