### ISSUE TITLE
dvr mp4 stream.mp4.tmp moov atom not found srs 3.0

### ISSUE THREAD

**Issue by nhocchi007** [ossrs/srs#1292]
I'm testing this scenario:
I'm using dvr for recording incoming stream into mp4 file. Then the internet between stream source and srs is down. Then i try to change the stream.tmp.mp4 into file stream.mp4 but it say "mov,mp4,m4a,3gp,3g2,mj2 @ 0x12c1420] moov atom not found". I can do it with flv.tmp but not mp4. What can i do to workaround this situation? Thank you!

**Comment by nhocchi007** [comment]
Ow i found the solution at https://github.com/ossrs/srs/issues/1108

**Comment by nguyenduybinh** [comment]
> Ow i found the solution at #1108

What is the solution you found? can you share that. I have the same problem.
Thanks!
