### ISSUE TITLE
Play RTMP stream inside OBS

### ISSUE THREAD

**Issue by MBoberski** [ossrs/srs#1295]
Hi,

I was trying to get by SRS stream to play inside OBS as Media Source but failed. It is not showing it at all. What em I doing wrong? I used rtmp.conf with no changes.

TIA

**Comment by TorchwoodPL** [comment]
I can play it in vlc but not ass a source in obs...

**Comment by TorchwoodPL** [comment]
hello?

**Comment by TorchwoodPL** [comment]
Any idea?

**Comment by pryiz** [comment]
Hi Torchwood,

add a vlc source, url source and enter url "rtmp://"your server ip"/live/stream"

it should work

**Comment by winlinvip** [comment]
@pryiz 👍 It works!

**Comment by winlinvip** [comment]
![image](https://user-images.githubusercontent.com/2777660/73120227-751a4b80-3fa6-11ea-9932-22c8f2b080a1.png)

![image](https://user-images.githubusercontent.com/2777660/73120233-8bc0a280-3fa6-11ea-866a-1125c3372e37.png)

![image](https://user-images.githubusercontent.com/2777660/73120240-9a0ebe80-3fa6-11ea-964d-8cc5f98868b1.png)

![image](https://user-images.githubusercontent.com/2777660/73120249-b6126000-3fa6-11ea-954d-be5530460a71.png)
