### ISSUE TITLE
how to configure the flv use the vhost

### ISSUE THREAD

**Issue by auqf** [ossrs/srs#1308]
if i use the default vhost, i can play the flv url(http://www.test.com/app/test.flv), but if i add another vhost(as ds), i can not play by the flv url(http://test.com/app?vhost=ds/test2.flv). if it's not support or the flv url i use is error? any one can help me?

**Comment by hy05190134** [comment]
@auqf  you should use the url like this:  http://test.com/app/test2.flv?vhost=ds
