### ISSUE TITLE
srslibrtmp audio sound_rate 缺少8khz

### ISSUE THREAD

**Issue by atlantis414** [ossrs/srs#1309]
参考 https://github.com/ossrs/srs/wiki/v3_CN_SrsLibrtmp#publish-audio-raw-stream 在sound_rate中只有5.5khz, 11khz, 22khz, 44khz  在实际应用中8khz也是常见的sampling rate,为什么唯独没有8khz选项, 能添加进去吗?

**Comment by atlantis414** [comment]
RTMP协议就枚举了四个参数不包含8khz, 如果采样率是8kHZ的情况,就取最接近值5.5khz或者11khz

**Comment by mayi203** [comment]
这是因为 flv 支持的音频采样只有 5.5khz, 11khz, 22khz, 44khz，如果你使用 AAC 格式音频，直接用 44khz 就可以
