### ISSUE TITLE
关于api接口的需求问题

### ISSUE THREAD

**Issue by asAngus** [ossrs/srs#1313]
您好,麻烦请问下/api/v1/clients 这个接口问题, 我现在使用http-flv的播放视频,播放时有on_play的http_hooks事件,但是在这个clients的api接口中,获取不到这个客户端, 在rtmp的模式播放是可以获取到的.请问下,这个有解决的办法吗? 

非常感谢.

**Comment by atlantis414** [comment]
- srs2.0 cannot count httpflv client connections.
- srs3.0 supports httpflv client technology.

`TRANS_BY_GPT3`

**Comment by asAngus** [comment]
Oh. Okay. Thank you.

`TRANS_BY_GPT3`

**Comment by asAngus** [comment]
Hello @atlantis414, now the httpflv client can be counted. However, even after stopping playback, it still exists in this clients. Is this designed like this?

`TRANS_BY_GPT3`

**Comment by asAngus** [comment]
@atlantis414 Additionally, I have another question to ask. When I am playing an flv file, how can I receive the parameters attached to the playback URL through event notification? For example, in the URL "http://xxx.x.x.x/live/aaa.flv?aaa=111", how can I pass the parameter "aaa=111" through the on_play http_hooks?

`TRANS_BY_GPT3`

**Comment by atlantis414** [comment]
> @atlantis414 Additionally, I have another question to ask. When I am playing an flv file, how can I receive the parameters passed through the play address using event notification?
> For example, if the play address is http://xxx.x.x.x/live/aaa.flv?aaa=111, how can I pass the parameter aaa=111 through on_play http_hooks?

[Here](https://github.com/ossrs/srs/wiki/v3_CN_HTTPCallback) is the link to the documentation for `on_connect` which can capture the parameters.

`TRANS_BY_GPT3`

**Comment by atlantis414** [comment]
> Hello @atlantis414, now the httpflv client can be counted. However, even after stopping playback, it still exists in this "clients". Is this designed like this?

In SRS, pushing a stream is also considered as a type of client and is counted in the "clients" list. For example, if you stop playback on the webpage but continue pushing the stream, the "clients" count will still be 1.

`TRANS_BY_GPT3`

**Comment by asAngus** [comment]
> > @atlantis414 Also, there is another question I would like to ask. When I am playing an flv file, how can I receive the parameters that are passed through the play address using event notification?
> > For example: http://xxx.x.x.x/live/aaa.flv?aaa=111 How can I pass this parameter "aaa=111" through the on_play http_hooks?

> 
> You can refer to the following link for more information: https://github.com/ossrs/srs/wiki/v3_CN_HTTPCallback. The `on_connect` function can capture the parameters.

> Hello, during the testing process, the `on_connect` function only works for RTMP playback and is not effective for FLV and HLS playback. Could you please let me know if there is any solution to this issue? Or am I using the wrong method?

`TRANS_BY_GPT3`

**Comment by atlantis414** [comment]
> > > @atlantis414 Also, I have another question to ask. When I play FLV, how can I receive the parameters passed through the URL as event notifications?
> > > For example: http://xxx.x.x.x/live/aaa.flv?aaa=111 How can I pass the parameter "aaa=111" through the `on_play` http_hooks?
> > 
> > 
> > You can refer to the following link for more information: [https://github.com/ossrs/srs/wiki/v3_CN_HTTPCallback](https://github.com/ossrs/srs/wiki/v3_CN_HTTPCallback). The `on_connect` function can capture the parameters.
> 
> Hello, during the testing process, the `on_connect` function only works for RTMP playback and is not effective for FLV and HLS playback. Is there any solution to this issue? Or am I using the wrong approach?

I have tested it and it works fine. If there is an FLV stream, then the RTMP stream must also exist. The issue should be the same for version 3.0, as I used version 2.0 for testing.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@asAngus 👍

**Comment by asAngus** [comment]
The address suffix does not exist. It is in the notification message. All the parameters are included in the RTMP streaming address. There are no parameters for the playback client (such as aaa=111 in this information). Please help take a look. Thank you very much.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed by @duiniuluantanqin in SRS 4
