### ISSUE TITLE
srs Ingest无法采集rtsp

### ISSUE THREAD

**Issue by ou5156** [ossrs/srs#1314]
系统版本：centos6.10
srs版本：2.0
服务器IP: 192.168.2.14
rtsp源：rtsp://usr:passwd@192.168.2.233:554
注意：系统防火墙、selinux已关
注意：系统防火墙、selinux已关
注意：系统防火墙、selinux已关
我的配置如下：
#cat  conf/ingest.conf
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
vhost __defaultVhost__ {
    ingest 1 {
        enabled      on;
        input {
            type    stream;
            url     rtsp://user:passwd@192.168.2.233:554;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled         off;
            output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
}
执行命令：
#/application/srs/objs/srs -c /application/srs/conf/ingest.conf
用vlc访问：
rtmp://192.168.2.14/live/livestream或rtmp://192.168.2.14:1935/live/livestream
结果都无法看到视频。

请问，这是怎么回事？

**Comment by weiyuefei** [comment]
大哥，你要打开engine.enable为on才行

**Comment by winlinvip** [comment]
dup to #1329
