### ISSUE TITLE
RTMP segmentation fault

### ISSUE THREAD

**Issue by OlivierHartmann** [ossrs/srs#1318]
Hi,
Thank you for this project. I've installed it on a Raspberry Pi 3 B+, but when just running the default config, I get segmentation fault on the master/3.0release/2.0release branch:

> 
> pi@raspberrypi:~/srs/trunk $ ./objs/srs -c conf/rtmp.conf 
> [2019-02-06 10:01:50.781][trace][11424][0] XCORE-SRS/2.0.261(ZhouGuowen)
> [2019-02-06 10:01:50.782][trace][11424][0] config parse complete
> [2019-02-06 10:01:50.782][trace][11424][0] write log to console
> [2019-02-06 10:01:50.783][trace][11424][0] srs checking config...
> [2019-02-06 10:01:50.783][trace][11424][0] detect intranet address: 127.0.0.1, ifname=lo
> [2019-02-06 10:01:50.784][trace][11424][0] retrieve local ipv4 ip=10.5.5.100, index=0
> [2019-02-06 10:01:50.784][trace][11424][0] detect intranet address: 10.5.5.100, ifname=wlan0
> [2019-02-06 10:01:50.784][trace][11424][0] retrieve local ipv4 ip=192.168.6.224, index=1
> [2019-02-06 10:01:50.784][trace][11424][0] detect intranet address: 192.168.6.224, ifname=wlan1
> [2019-02-06 10:01:50.784][warn][11424][0][0] stats network use index=0, ip=10.5.5.100
> [2019-02-06 10:01:50.784][warn][11424][0][0] stats disk not configed, disk iops disabled.
> [2019-02-06 10:01:50.784][trace][11424][0] write log to console
> [2019-02-06 10:01:50.785][trace][11424][0] SRS/2.0.261(ZhouGuowen), stable is SRS/2.0release
> [2019-02-06 10:01:50.785][trace][11424][0] license: The MIT License (MIT), Copyright (c) 2013-2015 SRS(ossrs)
> [2019-02-06 10:01:50.785][trace][11424][0] primary/master: SRS/2.0release
> [2019-02-06 10:01:50.785][trace][11424][0] authors: winlin,wenjie.zhao
> [2019-02-06 10:01:50.785][trace][11424][0] contributors: winlin<winlin@vip.126.com> wenjie.zhao<740936897@qq.com> xiangcheng.liu<liuxc0116@foxmail.com> naijia.liu<youngcow@youngcow.net> alcoholyi<alcoholyi@qq.com> byteman<wangchen2011@gmail.com> chad.wang<chad.wang.cn@gmail.com> suhetao<suhetao@gmail.com> Johnny<fengjihu@163.com> karthikeyan<keyanmca@gmail.com> StevenLiu<lq@chinaffmpeg.org> zhengfl<zhengfl_1989@126.com> tufang14<breadbean1449@gmail.com> allspace<allspace@gmail.com> niesongsong<nie950@gmail.com> rudeb0t<nimrod@themanxgroup.tw> CallMeNP<np.liamg@gmail.com> synote<synote@qq.com> lovecat<littlefawn@163.com> panda1986<542638787@qq.com> YueHonghui<hongf.yue@hotmail.com> JuntaoLiu<juntliu@gmail.com> 
> [2019-02-06 10:01:50.786][trace][11424][0] uname: Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
> [2019-02-06 10:01:50.786][trace][11424][0] build: 2019-02-06 09:47:29, little-endian
> [2019-02-06 10:01:50.786][trace][11424][0] configure: --x86-x64 
> [2019-02-06 10:01:50.786][trace][11424][0] features: --prefix=/usr/local/srs --with-hls --with-hds --with-dvr --without-nginx --with-ssl --without-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --without-stream-caster --with-http-api --with-librtmp --without-research --with-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace
> [2019-02-06 10:01:50.786][trace][11424][0] conf: conf/rtmp.conf, limit: 1000
> [2019-02-06 10:01:50.786][trace][11424][0] writev limits write 1024 iovs a time
> [2019-02-06 10:01:50.786][trace][11424][0] cpu is arm, glibc 2.24
> [2019-02-06 10:01:50.787][trace][11424][0] check feature rtmp handshake: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature hls: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature hds: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature http callback: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature http api: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature http server: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature http parser: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature dvr: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature transcode: on
> [2019-02-06 10:01:50.787][trace][11424][0] check feature ingest: on
> [2019-02-06 10:01:50.788][trace][11424][0] check feature system stat: on
> [2019-02-06 10:01:50.788][warn][11424][0][0] check feature compile nginx: off
> [2019-02-06 10:01:50.788][warn][11424][0][0] check feature compile ffmpeg: off
> [2019-02-06 10:01:50.788][warn][11424][0][0] stream caster: off
> [2019-02-06 10:01:50.788][trace][11424][0] MR(merged-read): on, @see https://github.com/ossrs/srs/issues/241
> [2019-02-06 10:01:50.788][trace][11424][0] MR(merged-read) default 0 sleep 350
> [2019-02-06 10:01:50.788][trace][11424][0] MW(merged-write) default sleep 350
> [2019-02-06 10:01:50.788][trace][11424][0] read chunk stream cache cid [0, 16)
> [2019-02-06 10:01:50.788][trace][11424][0] default gop cache 1, play queue 30s
> [2019-02-06 10:01:50.788][trace][11424][0] complex send algorithm enabled.
> [2019-02-06 10:01:50.788][warn][11424][0][0] TCP_NODELAY enabled, may hurts performance.
> [2019-02-06 10:01:50.788][trace][11424][0] auto guess socket send buffer by merged write
> [2019-02-06 10:01:50.788][trace][11424][0] system default latency in ms: mw(0-350) + mr(0-350) + play-queue(0-30000)
> [2019-02-06 10:01:50.789][trace][11424][0] http: root mount to ./objs/nginx/html
> [2019-02-06 10:01:50.789][trace][11424][0] st_set_eventsys to epoll
> [2019-02-06 10:01:50.789][trace][11424][0] st_init success, use epoll
> [2019-02-06 10:01:50.789][trace][11424][100] server main cid=100, pid=11424, ppid=5442, asprocess=0
> [2019-02-06 10:01:50.790][trace][11424][100] write pid=11424 to ./objs/srs.pid success!
> Segmentation fault
>

**Comment by Bit0git** [comment]
I wrote this in another thread. 
Had same issue, the replacement patch proposed in
#1282 solved.

I think the patch should be moved to master, for all of us ARMed...

**Comment by winlinvip** [comment]
https://github.com/ossrs/state-threads/tree/srs#branch-srs

Merge from [michaeltalyansky](https://github.com/michaeltalyansky/state-threads) and [xzh3836598](https://github.com/ossrs/state-threads/commit/9a17dec8f9c2814d93761665df7c5575a4d2d8a3), support [ARM](https://github.com/ossrs/state-threads/issues/1).

**Comment by winlinvip** [comment]
Dup to https://github.com/ossrs/srs/issues/1282#issue-386077124
