### ISSUE TITLE
srs无法精准切片ts

### ISSUE THREAD

**Issue by vanche1212** [ossrs/srs#1322]
编码器输出rtmp流到srs转为hls流，其中m3u8文件的内容如下：
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:59
#EXT-X-TARGETDURATION:12
#EXTINF:11.996, no desc
2019/02/18/19/22/44-59.ts
#EXTINF:11.985, no desc
2019/02/18/19/22/56-60.ts
#EXTINF:11.996, no desc
2019/02/18/19/23/08-61.ts
#EXTINF:11.985, no desc
2019/02/18/19/23/20-62.ts
#EXTINF:11.996, no desc
2019/02/18/19/23/32-63.ts
#EXTINF:11.985, no desc
2019/02/18/19/23/44-64.ts

本人使用了hls.conf配置文件，具体配置如下：
listen              1935;
max_connections     1000;
daemon              on;
srs_log_tank        console;
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_fragment    10;
        hls_window      60;
        hls_path        /hls/hls/srs;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[2006]/[01]/[02]/[15]/[04]/[05]-[seq].ts;
        hls_cleanup     off;
        hls_td_ratio    1.0;

    }
}
我想问下：
#EXTINF:11.996, no desc
切片的时长为啥都是不一致的？？

**Comment by fq393** [comment]
The encoder uses h264 encoding, with an output of 25 frames per second (fps) and a Group of Pictures (GOP) of 100.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The difference in timestamps of video frames is not accurate.

`TRANS_BY_GPT3`
