### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by manuelvita96** [ossrs/srs#1325]
Hi, I have an RTMP stream created with vMix, I want to convert it to HLS .m3u8 file for use it to webpage, I have installed on CentOS7 SRS but I don't know how use it, can someone help me to configure it?

**Comment by juntaoliu** [comment]
FYI. https://github.com/ossrs/srs/wiki/v2_EN_SampleHLS

**Comment by manuelvita96** [comment]
I'm stuck on step 6, I can star the RTMP stream but how I can start encoder?

**Comment by hy05190134** [comment]
the step 6 is just a example, it only means you can use ffmpeg command to publish stream

**Comment by manuelvita96** [comment]
Ok, I'm sorry, I'm not an expert, how can I change the default port for srs player page? Now when i go to IP address I see a chinese page with player or chat I don't know what is

**Comment by hy05190134** [comment]
can you cut the picture on the screen? as far as I know, you can just replace the ip with your own ip addr in PC.

**Comment by manuelvita96** [comment]
I have another problem. I try to view this HLS stream on web page but I see this error message: Access to XMLHttpRequest at 'http://sdrtdg.com:8080/live/livestream.m3u8' from origin 'http://sdrtdg.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
How can I solve this error?

**Comment by hy05190134** [comment]
@manuelvita96 it is easy to resolve cors problems. you can add header of "Access-Control-Allow-Origin: *" to response

**Comment by manuelvita96** [comment]
How I can do this? On page player? Or on SRS server?

**Comment by winlinvip** [comment]
For HTTP, use a HTTP proxy before SRS is better choice.
