### ISSUE TITLE
the "ssl" parameter requires ngx_http_ssl_module in /root/srs/trunk/objs/nginx-1.5.7/_release/conf/nginx.conf:36

### ISSUE THREAD

**Issue by iLoveSarabear** [ossrs/srs#1328]
Hi, I'm using SRS 2 (Centos 6) and I'm trying to get an SSL installed. When I attempt to start nginx I get the below error:

```
sudo ./objs/nginx/sbin/nginx
the "ssl" parameter requires ngx_http_ssl_module in /root/srs/trunk/objs/nginx-1.5.7/_release/conf/nginx.conf:36
```

How do I install the ngx_http_ssl_module with the version of nginx that comes with SRS 2?

Thanks!

**Comment by scar63** [comment]
Hi,
You must delete folder nginx and nginx-1.5.7 locate at /srs/trunk/objs. 

Then, you must update srs/trunk/auto/depends.sh file (L523) => 
 ./configure --prefix=`pwd`/_release  && make ${SRS_JOBS} && make install &&
./configure --prefix=`pwd`/_release **--with-http_ssl_module**  && make ${SRS_JOBS} && make install &&

And you build again => ./configure --with-nginx --with-ssl && make

It's works :)

++

**Comment by winlinvip** [comment]
@scar63 👍 Thanks
