### ISSUE TITLE
Ingest支持单一字符串方式：srs2采用ingest.conf 怎么把-rtsp_transport tcp加上呢

### ISSUE THREAD

**Issue by yangxiaoxie** [ossrs/srs#1329]

**Comment by winlinvip** [comment]
Currently, the Ingest feature of SRS essentially executes an ffmpeg process. However, SRS simplifies the parameters for easier use, which is convenient but not flexible for those familiar with ffmpeg.

A better approach would be to provide both options, supporting a string-based method would also be beneficial.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
There is another question, which is about supporting special characters: #517 "&" in ffmpeg stream path.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #447

**Comment by winlinvip** [comment]
```
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled         off;
            perfile {
                re;
                rtsp_transport tcp;
            }
```

SRS3 is already supported, add it to the perfile configuration.

`TRANS_BY_GPT3`
