### ISSUE TITLE
ffmpeg 转码端口异常

### ISSUE THREAD

**Issue by xiaobing0103** [ossrs/srs#1334]
我这边给多台srs主机配置了LVS负载均衡，外部推流入口是9935端口，然后转发到内部主机的1935端口，现推流和拉流是正常的，但是ffmpeg转码却有异常报错，我分析是程序进行转码时，带上了外部入口的9935端口，并没有使用实际的1935端口，这个有办法可以通过配置文件进行修复吗
报错如下：
log=./objs/ffmpeg-encoder-__defaultVhost__-webcam-10001-c7-ff.log
params: ./objs/ffmpeg/bin/ffmpeg -f flv -i rtmp://127.0.0.1:9935/webcam?vhost=__defaultVhost__/10001-c7 -vcodec copy -acodec libfdk_aac -b:a 45000 -ar 44100 -ac 2 -f flv -y rtmp://127.0.0.1:9935/webcam?vhost=__defaultVhost__/10001-c7_ff
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-36)
  configuration: --enable-gpl --enable-nonfree --yasmexe=/data/srs.oschina/trunk/objs/ffmpeg.src/_release/bin/yasm --prefix=/data/srs.oschina/trunk/objs/ffmpeg.src/_release --cc= --enable-static --disable-shared --disable-debug --extra-cflags='-I${ffmpeg_exported_release_dir}/include' --extra-ldflags='-L${ffmpeg_exported_release_dir}/lib -lm -ldl' --disable-ffplay --disable-ffprobe --disable-doc --enable-postproc --enable-bzlib --enable-zlib --enable-parsers --enable-libx264 --enable-libmp3lame --enable-libfdk-aac --enable-libspeex --enable-pthreads --extra-libs=-lpthread --enable-encoders --enable-decoders --enable-avfilter --enable-muxers --enable-demuxers
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[tcp @ 0x2e3e480] Connection to tcp://127.0.0.1:9935 failed: Connection refused
[rtmp @ 0x2e3df40] Cannot open connection tcp://127.0.0.1:9935
rtmp://127.0.0.1:9935/webcam?vhost=__defaultVhost__/10001-c7: Connection refused

**Comment by harleyxt** [comment]
I also encountered the same problem. How did the original poster solve it?

`TRANS_BY_GPT3`

**Comment by lomelee** [comment]
Modify code. 
Make sure to maintain the markdown structure.
![1](https://user-images.githubusercontent.com/12658216/63988088-33779880-cb0d-11e9-8339-5369a29fb8a4.png)
![2](https://user-images.githubusercontent.com/12658216/63988089-33779880-cb0d-11e9-8903-dfd1f527f915.png)

Add configuration. 
Make sure to maintain the markdown structure.
![3](https://user-images.githubusercontent.com/12658216/63988096-370b1f80-cb0d-11e9-893a-94fe5442c41c.png)

`TRANS_BY_GPT3`

**Comment by harleyxt** [comment]
> Modify code
> ![1](https://user-images.githubusercontent.com/12658216/63988088-33779880-cb0d-11e9-8339-5369a29fb8a4.png)
> ![2](https://user-images.githubusercontent.com/12658216/63988089-33779880-cb0d-11e9-8903-dfd1f527f915.png)
> 
> Add configuration
> ![3](https://user-images.githubusercontent.com/12658216/63988096-370b1f80-cb0d-11e9-893a-94fe5442c41c.png)

Thank you, great deity!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@harleyxt 👍

**Comment by TTnTTT** [comment]
Thank you, thank you.

`TRANS_BY_GPT3`
