### ISSUE TITLE
srs 项目源码查看

### ISSUE THREAD

**Issue by homedown90** [ossrs/srs#1336]
请问 srs 源码如何 用xcode 或者clion 搭建起来调试和查看呢

**Comment by homedown90** [comment]
我的点电脑是mac ，最近想要学习一srs的源码，但是不知道入口在哪里，或者从哪里看起呢

**Comment by RocFang** [comment]
这个问题，其实直接百度或google一下mac下怎么看c++代码就好了，跟srs没关系吧

**Comment by RocFang** [comment]
当然， 你如果搜索过的话，会发现winlinvip 其实写过一篇clion的，mac下也是一样的。
https://blog.csdn.net/win_lin/article/details/39579799

**Comment by homedown90** [comment]
我已经收到信息，最近想自己看看这个代码，之前只是简单部署过，想学习一下代码了，我先看看，谢谢了

**Comment by winlinvip** [comment]
GDB调试比较好，编辑器可以用IDEA社区版本。

**Comment by homedown90** [comment]
嗯嗯，这个是我之前新公司入手的一个项目，现在废了，我这里还是想跟进学习，近期有点忙，等抽出时间了，我这里及时跟进尝试，再及时反馈，辛苦两位的解答了
