### ISSUE TITLE
请问一下SRS怎么拓展H.265呢？CODEID写在哪里？

### ISSUE THREAD

**Issue by qq827896526** [ossrs/srs#1341]
如题，请问一下SRS是否能够支持拓展H.265，尝试使用编译的ffmpeg，发现并不能识别CODEID，求助

**Comment by chundonglinlin** [comment]
Customize a codec_id, you can refer to: https://github.com/CDN-Union/Code/tree/master/flv265-Kingsoft

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to https://github.com/ossrs/srs/issues/2562
