### ISSUE TITLE
请问大家http api有没有认证接口？

### ISSUE THREAD

**Issue by xiny120** [ossrs/srs#1344]
好像现在是任何人都能调用api吧。怎么能进行认证，特定的人才能调用？

**Comment by winlinvip** [comment]
The SRS API can listen to 127.0.0.1:1980. You can use an HTTP proxy to authenticate and then proxy to the local SRS API.

`TRANS_BY_GPT3`

**Comment by xiny120** [comment]
Okay. Thank you

`TRANS_BY_GPT3`
