### ISSUE TITLE
srs2.0支持m3u8切片重组吗？

### ISSUE THREAD

**Issue by SorosLiux** [ossrs/srs#1347]
能否支持url中传入时间戳参数，服务器按时间戳重组新的m3u8文件，来支持hls直播回看。

**Comment by RocFang** [comment]
Not supported, needs to be implemented manually.

`TRANS_BY_GPT3`

**Comment by sapceman** [comment]
Also interested in this feature, how can it be implemented on our own? Feel free to share your thoughts!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@RocFang 👍 Does not support special business logic.

You can consider using HTTP Callback to manage the slicing yourself after receiving the on_hls event.

`TRANS_BY_GPT3`
