### ISSUE TITLE
停止一段时间，然后再继续推流（srs_h264_write_raw_frames），为什么会导致程序退出

### ISSUE THREAD

**Issue by codemongkey** [ossrs/srs#1355]
和srs建立链接后，先srs_h264_write_raw_frames，然后停止一段时间（短时间5,6秒不会，长时间停止会），再srs_h264_write_raw_frames，导致程序中断退出，是为什么。

**Comment by lidedongsn** [comment]
链接断开了？

**Comment by codemongkey** [comment]
@lidedongsn 有没有函数可以判断链接有没有断开，如果链接没断开srs_rtmp_handshake会出错

**Comment by codemongkey** [comment]
@lidedongsn 超过5秒不publish, srs会自动断开链接，所以需要重新链接，但是原来的rtmp,不可以srs_rtmp_handshake，，可能是因为被destory了，所以目前的做法是重新create一个rtmp

**Comment by codemongkey** [comment]
@lidedongsn  话说老哥知道怎么close连接吗，库里只有shake的呀

**Comment by codemongkey** [comment]
srs_rtmp_destroy
