### ISSUE TITLE
录制FLV时，偶尔会造成flv文件没有SrsCodecVideoAVCTypeSequenceHeader

### ISSUE THREAD

**Issue by xiny120** [ossrs/srs#1358]
if (avc_packet_type == SrsCodecVideoAVCTypeSequenceHeader) { // 解码时这里没有这个不能初始化avc_demux_sps_pps，造成视频不能解码。用mpc也播放不了这个flv
        if ((ret = avc_demux_sps_pps(stream)) != ERROR_SUCCESS) {
            return ret;
        }
    }

**Comment by winlinvip** [comment]
视频本身的问题。
