### ISSUE TITLE
srs支持websocket协议吗？

### ISSUE THREAD

**Issue by jatavion** [ossrs/srs#1363]
srs支持websocket协议吗，在客户端如何播放？

**Comment by RocFang** [comment]
Reference
https://github.com/winlinvip/videojs-flow/blob/master/demo/mse.go

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@RocFang 👍 SRS supports basic HTTP protocol and can be used as a reverse proxy with other frameworks like nginx, or other languages like Go or PHP, to achieve WS or HTTPS as well as authentication.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Reference example of converting HTTP-FLV to WS-FLV: https://github.com/ossrs/srs/issues/1576#issuecomment-574963151

`TRANS_BY_GPT3`

**Comment by leonlu1983** [comment]
When running http://localhost:8080/demos/one2one.html?autostart=true&room=451f0bd&wsp=1989, srs.sig.js: appears.
 WebSocket connection to 'ws://localhost:1989/sig/v1/rtc?room=451f0bd&display=b9cb39f' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
How can this be resolved?

`TRANS_BY_GPT3`
