### ISSUE TITLE
srs3.0 使用vlc播放hls流是不会触发on_play回调吗？

### ISSUE THREAD

**Issue by liaojunwu** [ossrs/srs#1366]
srs3.0 使用vlc播放hls流是不会触发on_play回调吗？还是我配置错了，我看到播放rtmp是有回调的

**Comment by popstk** [comment]
#52 同样的问题，找到了这个
> For HLS, you should handle it on NGINX.
> For FLV, the http callback is planed in SRS3

**Comment by winlinvip** [comment]
SRS4可能会支持。

**Comment by winlinvip** [comment]
Dup to #1657
