### ISSUE TITLE
在龙芯系统下能编译成功，但是不能用

### ISSUE THREAD

**Issue by fayfive** [ossrs/srs#1373]
在龙芯下的系统下，编译srs，将其修改成x86_64的环境，编译成功，生成srs，但是用不了，龙芯是mips，运行的时候，log到了write pid=619 to ./objs/srs.pid success!下面就没有了，查看进程，并没有srs进程
配置编译如下：
./configure \
--without-utest \
--without-ssl \
--without-hls \
--without-hds \
--without-research \
--without-http-api \
--without-gperf \
--without-gmc \
--without-gmp \
--without-gcp \
--without-gprof \
--without-librtmp \
不知道能不能在龙芯用，望各位指教，谢谢

**Comment by chrdwhdhxtszpzclljxk** [comment]
用啥编译的？龙芯没有自己的交叉编译的工具链吗？

**Comment by fayfive** [comment]
就是用龙芯自己的交叉编译链，龙芯+中标麒麟的桌面电脑

**Comment by winlinvip** [comment]
Duplicated issue.

**Comment by winlinvip** [comment]
Dup to #1282
