### ISSUE TITLE
unsupported vhost directive cluster, ret=1023 

### ISSUE THREAD

**Issue by Stark-coco** [ossrs/srs#1375]
搭建集群时出现这个 unsupported vhost directive cluster, ret=1023 错误，请问是什么导致的呢？
配置：

listen              19350;
max_connections     1000;
daemon              off;
srs_log_tank        console;
pid                 ./objs/origin.cluster.serverA.pid;
http_api {
    enabled         on;
    listen          9090;
}
vhost shikuby {
   cluster {
        mode            local;
        origin_cluster  on;
        coworkers       127.0.0.1:9091;
   }
}

**Comment by winlinvip** [comment]
要用SRS3
