### ISSUE TITLE
./configure --rtmp-hls --with-http-api --with-ffmpeg && make 出错

### ISSUE THREAD

**Issue by kalenforn** [ossrs/srs#1376]
这个是我在ubuntu18.04系统下编译的结果，结果还没到make直接configure就出错了，这个信息我没看懂，也找不到解决办法，希望有人能帮我解决一下。谢谢！
编译配置选项的时候出错了，我看不懂这个错误提示，错误信息如下，命令就是标题，希望有大佬能帮我解决。谢谢！

configure:creating ./config.status
config.status: creating Makefile
config.status: creating fdk-aac.pc
config.status: executing depfiles commands
config.status: executing libtool commands
  CXX      libAACdec/src/aacdec_drc.lo
  CXX      libAACdec/src/aacdec_hcr.lo
  CXX      libAACdec/src/aacdecoder.lo
  CXX      libAACdec/src/aacdec_pns.lo
  CXX      libAACdec/src/aac_ram.lo
  CXX      libAACdec/src/block.lo
  CXX      libAACdec/src/channelinfo.lo
  CXX      libAACdec/src/ldfiltbank.lo
  CXX      libAACdec/src/rvlcbit.lo
  CXX      libAACdec/src/rvlc.lo
  CXX      libAACdec/src/aacdec_hcr_bit.lo
  CXX      libAACdec/src/aacdec_hcrs.lo
  CXX      libAACdec/src/aacdecoder_lib.lo
  CXX      libAACdec/src/aacdec_tns.lo
  CXX      libAACdec/src/aac_rom.lo
  CXX      libAACdec/src/channel.lo
  CXX      libAACdec/src/conceal.lo
  CXX      libAACdec/src/pulsedata.lo
  CXX      libAACdec/src/rvlcconceal.lo
  CXX      libAACdec/src/stereo.lo
  CXX      libAACenc/src/aacenc.lo
  CXX      libAACenc/src/aacEnc_ram.lo
  CXX      libAACenc/src/band_nrg.lo
  CXX      libAACenc/src/block_switch.lo
  CXX      libAACenc/src/grp_data.lo
  CXX      libAACenc/src/metadata_main.lo
  CXX      libAACenc/src/pre_echo_control.lo
  CXX      libAACenc/src/quantize.lo
  CXX      libAACenc/src/tonality.lo
  CXX      libAACenc/src/aacenc_hcr.lo
  CXX      libAACenc/src/aacEnc_rom.lo
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘2180108801’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘2435191937’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘2914591489’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘3560484608’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘2147483649’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘2276992735’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘2649899348’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘3221225445’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘3922060664’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘2156644481’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘2229462401’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘2372618753’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘2581238273’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘2848216833’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘3164462721’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘3519206656’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘3900368192’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘2147483649’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘2184048624’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘2292498406’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘2469139869’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘2707957698’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘3000819239’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘3337751441’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘3707280484’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of ‘4096822497’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
Makefile:1259: recipe for target 'libAACenc/src/aacEnc_rom.lo' failed
make: *** [libAACenc/src/aacEnc_rom.lo] Error 1
build fdk-aac-0.1.3 failed
build ffmpeg-4.1 failed, ret=1 

谢谢！

**Comment by Longxr** [comment]
请问你是解决了这个问题么，我也碰到了

**Comment by kalenforn** [comment]
> 请问你是解决了这个问题么，我也碰到了

我解决了，这个是你自己电脑的ffmpeg没有配置好，你可以去搜索一下如何安装ffmpeg，把这个装上去就好了

**Comment by kalenforn** [comment]
@Longxr 

> 请问你是解决了这个问题么，我也碰到了

@Longxr 我解决了，这个是你自己电脑的ffmpeg没有配置好，你可以去搜索一下如何安装ffmpeg，把这个装上去就好了

**Comment by Longxr** [comment]
> @Longxr
> 
> > 请问你是解决了这个问题么，我也碰到了
> 
> @Longxr 我解决了，这个是你自己电脑的ffmpeg没有配置好，你可以去搜索一下如何安装ffmpeg，把这个装上去就好了

就是直接安装，不用configure里面的编译，然后在相关xxx.conf里指定ffmpeg的路径么

**Comment by kalenforn** [comment]
那我就不知道了

> > @Longxr
> > > 请问你是解决了这个问题么，我也碰到了
> > 
> > 
> > @Longxr 我解决了，这个是你自己电脑的ffmpeg没有配置好，你可以去搜索一下如何安装ffmpeg，把这个装上去就好了
> 
> 就是直接安装，不用configure里面的编译，然后在相关xxx.conf里指定ffmpeg的路径么
