### ISSUE TITLE
如何保存MP4格式的视频文件

### ISSUE THREAD

**Issue by yuhf1003** [ossrs/srs#1378]
你好，我想通过搭建的srs服务器将接收到的视频流信息保存成视频文件格式，但是目前通过dvr.segment.conf配置后只能生成.flv文件，请问如何将视频文件直接保存成.mp4的文件呢?

**Comment by EngineerZhi** [comment]
> Hello, I want to save the received video stream information as a video file format through the built SRS server, but currently, after configuring dvr.segment.conf, only .flv files can be generated. How can I directly save the video file as .mp4?

> Hello, have you resolved it?

`TRANS_BY_GPT3`

**Comment by yuhf1003** [comment]
> Hello, have you resolved it?

> In version 3.0, you can simply change the suffix name for generating videos in the configuration file to .mp4.

`TRANS_BY_GPT3`

**Comment by zheng-li-fei** [comment]
From the online rtsp source: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov Recorded MP4 can be accessed directly through a web browser.
![image](https://user-images.githubusercontent.com/38311891/69692465-1e5ed580-110d-11ea-998d-3d9b4a687ce5.png) 
However, MP4 recordings from the camera's rtsp cannot be accessed through a web browser. They can be accessed using VLC. [Here](https://user-images.githubusercontent.com/38311891/69692591-74337d80-110d-11ea-8d99-ac0ebb5a98c6.png) is an image showing this. Why is this the case?


`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@yuhf1003 👍 SRS3 supports recording as MP4.
Regarding the issue of browser playback, a friend mentioned it before, and I will take a detailed look at it, dup to #1483.

`TRANS_BY_GPT3`

**Comment by longshilei** [comment]
On my side, I also generated a video in MP4 format, but it cannot be played through the HTTP browser. Can someone help me figure out what the problem is?

`TRANS_BY_GPT3`
