### ISSUE TITLE
Authorisation of pushes (and pulls)? (如何(类似twitch)只能推流到预设stream key？)

### ISSUE THREAD

**Issue by gotexis** [ossrs/srs#1384]
I am just digging through the documentation and wondering what is the proper way to manage who can push to which key.

Let's say, in twitch, each user is assigned a stream key so you could fill into OBS. When I am testing with SRS I found that any user can just push to any stream.

Surely, there is a way to manage streaming authorization, but I am just stuck at where to go here.

I am using Python / Django backend but it's ok to switch to ExpressJS.

(in Chinese: 如何实现最基础的功能，类似twitch，只能推到预分配的stream key？如果stream key对不上就不能push)

I understand A HTTP hook may need to be used but just wondering if this is documented.

**Comment by winlinvip** [comment]
You can use [HTTP callback](https://github.com/ossrs/srs/wiki/v3_EN_HTTPCallback), which calls your server with stream key and .token. Then, you can verify the client ip, url, stream key and token. Finally, response a none 0 to SRS, SRS will reject the publishing or playing.
