### ISSUE TITLE
demo 怎么没有不能播放？

### ISSUE THREAD

**Issue by wangtian076** [ossrs/srs#1390]
![image](https://user-images.githubusercontent.com/9692429/59333259-90dc2480-8d2a-11e9-98e8-ead165c02376.png)

**Comment by kedi-z** [comment]
换个播放地址

**Comment by wangtian076** [comment]
![image](https://user-images.githubusercontent.com/9692429/59340486-b2440d00-8d38-11e9-916c-b8e8fa9888d7.png)
为什么不能选择

**Comment by wangtian076** [comment]
http://www.ossrs.net/players/srs_publisher.html

**Comment by wangtian076** [comment]
http://www.ossrs.net/players/srs_publisher.html
给的这个和我启动的 demo 都是不能点不能看。

**Comment by winlinvip** [comment]
Fixed。
