### ISSUE TITLE
访问ip:8080登陆前台，好像没管理员后台

### ISSUE THREAD

**Issue by 1265578519** [ossrs/srs#1395]
有没有admin地址？

**Comment by RocFang** [comment]
你理解错了，本来就没有管理后台..

**Comment by 1265578519** [comment]
@RocFang 我听别人说，有个后台，可以看到在线人数和流量之类的啊。

**Comment by cook369** [comment]
srs有个http_api,根据请求内容可以看到服务器流媒体状态
或者通过打开网址
http://ossrs.net:1985/console/ng_index.html#/connect?host=ossrs.net&port=1985
输入服务器IP和api地址1935
可以看到界面的控制台，服务器状态，视频流状态，客户端状态都能看到
感觉你在找这个

**Comment by winlinvip** [comment]
没有做权限管理，欢迎PR，该就业岗位is open。
