### ISSUE TITLE
play with http flv

### ISSUE THREAD

**Issue by hesampour** [ossrs/srs#1396]
I started the SRS server and push the video with ffmpeg with the rtmp protocol. I can play the send video with ffplay with rtmp protocol. but I can't play it with http. I tried different ways. first I send the stream with rtmp://127.0.0.1/live/livestream then tried to get with http://127.0.0.1:8080/live/livestream.flv. then I send the stream to http://127.0.0.1:8080/live/livestream.flv then tried to get with http://127.0.0.1:8080/live/livestream.flv. I changed the config to 

```
listen              1935;
max_connections     1000;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }
}
```

but again it didn't work.

**Comment by xin-young** [comment]
__defaultVhost__    
just guessing it

**Comment by winlinvip** [comment]
Can't replay.
