### ISSUE TITLE
two streams at the same time

### ISSUE THREAD

**Issue by Raymond886** [ossrs/srs#1401]
sorry to ask this here but i did not find any support forum,
I have installed SRS on my centos 6 server I can stream and play the HLS with no issue
my question is I want to stream 2 channels at the same time! 
is it ok if I setup RTMP on my encoder #1 > rtmp://server-ip:1935/live & streamname : channel1
encoder #2 rtmp://server-ip:1935/live & streamname: channel2 

or do i have to configure  the CONF files?

**Comment by winlinvip** [comment]
Not a issue.
