### ISSUE TITLE
rtmp转hls生成ts的时候判断是annexb还是ibmf 有可能判断错误，导致生成的ts播放花屏

### ISSUE THREAD

**Issue by xiaoninger** [ossrs/srs#1405]
srs_avc_startswith_annexb 判断遇到 000001的就认为是 annexb格式，有可能是 ibmf格式，只是长度碰巧也是，列如 00000122 可能是 ibmf格式，长度为290字节

**Comment by winlinvip** [comment]
Make sense.

**Comment by Antony-An** [comment]
Have you ever encountered the annexb format in rtmp? 
Is it possible to use the annexb format only when consecutive n frames are annexb? Are there any other better methods? 
I feel like no matter what we do, there will always be a possibility of misjudgment.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS 5.0, add a new configuration to specify guessing IMBF first: 

```
vhost __defaultVhost__ {
    publish {
        # When parsing SPS/PPS, whether try ANNEXB first. If not, try IBMF first, then ANNEXB.
        # default: on
        try_annexb_first on;
    }
}
```

Today, a friend encountered a screen flickering issue, and it was found that there was an extra byte in the TS, causing an abnormal GOP.

![image](https://user-images.githubusercontent.com/2777660/187904155-89ad4b46-1c7d-477a-8e6e-3e527bc67866.png)

`TRANS_BY_GPT3`
