### ISSUE TITLE
librtmp 推流时，如果通过rtmp url传参，并没有把参数传给rmtp server

### ISSUE THREAD

**Issue by tdwu** [ossrs/srs#1406]
librtmp 推流时，如果通过rtmp url传参，并没有把参数传给rmtp server

如：
使用nginx  rtmp 搭建了rtmp服务器。
通过librtmp推流，url:rmtp://192.168.0.145:2870/live/10003?room=1003&auth=UBDFCDESX013DS
nginx rtmp收到不到room和auth信息。

**Comment by Torchwoods** [comment]
Also encountered similar problems.

`TRANS_BY_GPT3`

**Comment by Torchwoods** [comment]
Using srs-librtmp for streaming, the server is unable to receive information when the URL contains parameters.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.
