### ISSUE TITLE
控制台http请求“/api/v1/clients/”获取的客户端的信息是源站ip，不是客户端的真实ip

### ISSUE THREAD

**Issue by mapengfei53** [ossrs/srs#1412]
我们测试srs获取客户端的ip地址，通过函数srs_get_peer_ip获取到的ip是源站ip，而不是客户端的ip，通过分析函数实现，目前发现函数getsockname应该被替换成getpeername才能准确获取到客户端的ip地址。
//
string srs_get_peer_ip(int fd)
{

    // discovery client information 
    sockaddr_storage addr; 
    socklen_t addrlen = sizeof(addr); 
    if (getpeername(fd, (sockaddr*)&addr, &addrlen) == -1) { 
        return ""; 
    } 

    char saddr[64];
    char* h = (char*)saddr;
    socklen_t nbh = (socklen_t)sizeof(saddr);
    const int r0 = getnameinfo((const sockaddr*)&addr, addrlen, h, nbh, NULL, 0, NI_NUMERICHOST);
    if(r0) {
        return "";
    }

    return std::string(saddr);
}

**Comment by winlinvip** [comment]
Fixed.
