### ISSUE TITLE
目前最新的3.0源码如果通过http flv拉流的话，控制台获取到的客户端的ip是源站ip，不是客户ip

### ISSUE THREAD

**Issue by mapengfei53** [ossrs/srs#1413]
针对通过http flv拉流控制台获取ip不正确的问题，我目前实现的方案方式如下：

在基类ISrsHttpServeMux和ISrsHttpHandler中新增加定义std::string ip;用于变量保存客户端ip地址。
通过修改构造函数SrsHttpCorsMux::SrsHttpCorsMux(std::string cip)添加cip参数变量，在创建类对象的时候初始化客户端ip，ip = cip;

通过在函数srs_error_t SrsHttpCorsMux::initialize(ISrsHttpServeMux* worker, bool cros_enabled)中将保存的客户端ip，通过next->ip = ip;将ip传递给下一级对象。

通过在函数srs_error_t SrsHttpServer::serve_http(ISrsHttpResponseWriter* w, ISrsHttpMessage* r)再调用http_stream->mux.serve_http(w, r);前将http_stream->mux.ip = ip;将ip传给下一级对象。

函数srs_error_t SrsHttpServeMux::serve_http(ISrsHttpResponseWriter* w, ISrsHttpMessage* r)通过增加h->ip = ip;将ip传递给类srs_error_t SrsLiveStream::serve_http(ISrsHttpResponseWriter* w, ISrsHttpMessage* r)方法，最后通过替换掉request指针变量req->ip = ip;中保存的错误的IP地址，添加到容器中。

以上是我目前简单的实现方式。

**Comment by winlinvip** [comment]
Fixed.
