### ISSUE TITLE
cms2.5直连ossrs2异常断开

### ISSUE THREAD

**Issue by nikohpng** [ossrs/srs#1418]
- 在issues中cms直连ossrs异常断开，通过nginx作为中转成功实现。本人通过此种方案实现，但是由于项目需求，最好能够进行直连。

- 此处通过抓包发现，在协商过程中突然cms作为客户端发送断开连接请求
![image](https://user-images.githubusercontent.com/27041231/62926679-8ea84c00-bde7-11e9-8ad1-1d3e91c200c4.png)
41是cms，42是ossrs，42用的端口是1935。
  
   1.上面的是直连（即cms连接ossrs）,下面的抓包内容通过nginx转发给ossrs，抓的包是nginx与ossrs之间的通信情况 
![image](https://user-images.githubusercontent.com/27041231/62927493-3a05d080-bde9-11e9-857f-c4dea66051ef.png)
   **其中1935端口仍然是ossrs，此处与直连最大的不同是在set peer阶段正常建立连接，在直连中没有正常建立连接**

   2.通过此处，我又去cms抓包，了解cms发送到nginx的包的情况。下面是cms到nginx
![image](https://user-images.githubusercontent.com/27041231/62927796-ddef7c00-bde9-11e9-80b7-071244f7e199.png)
   此处1945的端口是nginx的端口，此处cms与nginx直连没有任何问题。
   3.分析到此处，虽感觉无限接近问题答案，但是由于无法获取到ossrs的详细日志，无法确定错误到底出在何处。

- 通过查询cms的api文档发现，cms只提供输入直播地址的api接口，没有任何其它参数（如果call_id也算，那就不是）

- 通过调节ossrs的输出日志，发现在connect_app阶段后直接被客户端（cms）发送来的断开连接，断开了。（本人能力有限，无法明白wiki上所说的调节为verbose,搜索过后不明白如果去除所说的内容，直接查看源代码将部分内容删除也无法实现打印verbose的内容。）

- 感谢关注

**Comment by winlinvip** [comment]
信息太少。
