### ISSUE TITLE
使用docker部署后dvr 视频文件不能播放

### ISSUE THREAD

**Issue by RainKnight** [ossrs/srs#1419]
我用的是2.0release 版本：
我的配置：
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     10;
srs_log_tank        console;
srs_log_level       verbose;
daemon              off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    dvr {
            enabled      on;
            dvr_path     ./objs/nginx/html/[app]/[stream].[timestamp].flv;
            dvr_plan     session;
    }
}

但是生成的flv 文件只有243B

**Comment by WONG-William** [comment]
同问

**Comment by WONG-William** [comment]
解决了，不用opencv生成的视频，用手机拍的视频就没问题了

**Comment by winlinvip** [comment]
描述不清，缺少重现步骤和日志。
