### ISSUE TITLE
SRS转推到CDN上

### ISSUE THREAD

**Issue by basheGG** [ossrs/srs#1420]
其他渠道推流到SRS后，SRS怎样再转推到CDN上，forward如何配置？

**Comment by hy05190134** [comment]
@basheGG  wiki 上有 forword 例子

**Comment by basheGG** [comment]
文档上只有SRS forword SRS上，我直接forword到cdn上不行，可以详细点吗大神

**Comment by hy05190134** [comment]
@basheGG cdn 也需要是 srs 的服务的，edge->transfer->origin

**Comment by basheGG** [comment]
非常感谢您的帮助

**Comment by xmglin** [comment]
> @basheGG cdn 也需要是 srs 的服务的，edge->transfer->origin

哪家CDN是用srs回源？aliyun？@hy05190134
正在找合适CDN来优化播放端。

**Comment by liguocahng** [comment]
> 
> 
> > @basheGG  cdn 也需要是 srs 的服务的，edge->transfer->origin
> 
> 哪家CDN是用srs回源？aliyun？ @hy05190134
> 正在找合适CDN来优化播放端。

SRS转推流到aliyun成功了吗，我一直推不成功

**Comment by winlinvip** [comment]
一般是鉴权问题。
