### ISSUE TITLE
请教如何配置上下行分离?

### ISSUE THREAD

**Issue by amhoho** [ossrs/srs#1422]
如实现在同一台服务器绑了up.com和down.com
现在期望推流时up.com 而播放时用down.com
这样该如何配置?

**Comment by hy05190134** [comment]
@amhoho  srs(up-edge) -> srs(origin) -> srs(down-edge), 将 up.com 解析到 up-edge, down.com 解析到 down-edge, 同一台的话 up.com 和 down.com 解析到同一个 ip 就可以了呀

**Comment by hy05190134** [comment]
@amhoho 同一台机器的话需要定制化

**Comment by winlinvip** [comment]
可以回源时回不同的vhost，详细请看Edge的wiki。
