### ISSUE TITLE
How to play flv files

### ISSUE THREAD

**Issue by meduar** [ossrs/srs#1423]
I wan to play old flv files(previous FLV recorded with **SRS** ): I ned this for a video system where  is required to check previous days) How could I do it?

What is the best way to play flv files recorded from the **SRS** through http?
example: http://18.209.228.28:8080/stream/09.32.40.030.flv forward, play, rewind.
Thanks,

**Comment by amhoho** [comment]
to open a link with a web player, just set the parameter `dvr_path` to your website directory.

**Comment by winlinvip** [comment]
@amhoho Thanks!
