### ISSUE TITLE
线上srs进程cpu 100%,打出core，退出的位置都不确定...什么情况下cpu会达到100%

### ISSUE THREAD

**Issue by herono2010** [ossrs/srs#1424]

**Comment by RocFang** [comment]
What version.
There is no information, so it's hard to say.

`TRANS_BY_GPT3`

**Comment by herono2010** [comment]
> 什么版本。
> 啥信息都没有，这没法说。

版本是2.0.209
因为对版本做过许多修改，所以不可能升级版本的。
信息是第二天，ps aux 的时候，一个源srs的cpu 达到99.9%，然后这个srs进程也不输出日志了。
gdb 这个卡死的进程：
![image](https://user-images.githubusercontent.com/10826275/63398514-76948600-c400-11e9-8589-3d8bb549ef89.png)

**Comment by herono2010** [comment]
> 什么版本。
> 啥信息都没有，这没法说。

版本是2.0.209
因为对版本做过许多修改，所以不可能升级版本的。
信息是第二天，ps aux 的时候，一个源srs的cpu 达到99.9%，然后这个srs进程也不输出日志了。
gdb 这个卡死的进程：
![image](https://user-images.githubusercontent.com/10826275/63398626-c5dab680-c400-11e9-990d-5cf31d6df1ad.png)

我还想问下，如果进程cpu达到100%，进程是不是自动就卡住了，因为我看一些转码的进程，比如ffmpeg，cpu 就可以达到141%还正常运行。
![image](https://user-images.githubusercontent.com/10826275/63398756-20741280-c401-11e9-8733-db5ad19f5920.png)


最后，我开启了ulimit -c unlimited,然后srs有重启，重启的core文件gdb如下：
![image](https://user-images.githubusercontent.com/10826275/63398829-5ca77300-c401-11e9-94db-be244b39008d.png)

谢谢大家的回答帮助。

**Comment by herono2010** [comment]
> 什么版本。
> 啥信息都没有，这没法说。

版本是2.0.209
因为对版本做过许多修改，所以是不会升级版本的。
具体信息是：第二天，ps aux 的时候，一个源srs进程的cpu达到99.9%，然后这个srs进程昨天晚上11点以后到现在也不输出日志了。
gdb 这个卡死的进程：
![image](https://user-images.githubusercontent.com/10826275/63399060-e8210400-c401-11e9-977f-a3ced5385d12.png)

我还想问下，如果srs进程cpu达到100%，srs进程是不是自动就卡住了，因为我看一些转码的进程，比如ffmpeg，cpu 就可以达到141%还正常运行。
![image](https://user-images.githubusercontent.com/10826275/63399101-0edf3a80-c402-11e9-96d6-8f00319fa26f.png)

最后，我开启了ulimit -c unlimited,然后发现源srs有异常退出，core文件gdb如下：
![image](https://user-images.githubusercontent.com/10826275/63399147-40580600-c402-11e9-8a68-766d3c6f195f.png)


谢谢大家的回答帮助！

**Comment by herono2010** [comment]
> What version?
> There is no information, so it can't be said.

> The version is 2.0.209.
> Because there have been many modifications to the version, it will not be upgraded.
> The specific information is: the next day, when executing "ps aux", the CPU usage of a source SRS process reached 99.9%. Also, this SRS process has not been outputting logs since 11 PM last night.
> The process that is stuck can be debugged using gdb.

![image](https://user-images.githubusercontent.com/10826275/63399229-71d0d180-c402-11e9-9d02-7fa79eedde79.png)

> I also want to ask, if the CPU usage of the SRS process reaches 100%, does the SRS process automatically get stuck and the CPU usage does not decrease? Because I have seen some transcoding processes, like ffmpeg, where the CPU usage can reach 141% and still run normally.
![image](https://user-images.githubusercontent.com/10826275/63399251-86ad6500-c402-11e9-8014-3f147251f17e.png)

> Finally, I enabled `ulimit -c unlimited`, and then SRS was restarted. The gdb output for the restarted core file is as follows:
![image](https://user-images.githubusercontent.com/10826275/63399304-b492a980-c402-11e9-9b65-3e09db6915c7.png)

> Thank you all for your answers and assistance!

`TRANS_BY_GPT3`

**Comment by herono2010** [comment]
补充一下：srs进程里面，我们需要通过域名获取ip地址，之前用的是getaddrinfo()系统调用，因为这个调用时阻塞的；所以才改成调用st库里面的int dns_getaddr(const char *host, struct in_addr *addr, st_utime_t timeout)非阻塞系统调用，上了这个版本以后才出现的这个问题,会不会和这个函数有关系？

**Comment by herono2010** [comment]
补充一下：srs进程里面，我们需要通过域名获取ip地址，之前用的是getaddrinfo()系统调用，因为这个调用是阻塞的；所以才改成调用st库里面的int dns_getaddr(const char *host, struct in_addr *addr, st_utime_t timeout)非阻塞函数来获取ip，上了这个版本以后才出现cpu %100这个问题,会不会和这个函数有关系？

**Comment by herono2010** [comment]
补充一下：srs进程里面，我们需要通过域名获取ip地址，之前用的是getaddrinfo()系统调用，因为这个调用是阻塞的；所以才改成调用st库里面的int dns_getaddr(const char *host, struct in_addr *addr, st_utime_t timeout)非阻塞函数来获取ip，srs进程里会频繁调用这个函数，上了这个版本以后才出现cpu %100这个问题,会不会和这个函数有关系？

**Comment by herono2010** [comment]
补充一下：srs进程里面，我们需要通过域名获取ip地址，之前用的是getaddrinfo()系统调用，因为这个调用是阻塞的；所以才改成调用st库里面的int dns_getaddr(const char *host, struct in_addr *addr, st_utime_t timeout)非阻塞函数来获取ip，srs进程里会频繁调用这个函数，上了这个版本以后才出现cpu %100这个问题,这个函数本身是不是有问题？

**Comment by winlinvip** [comment]
100% is just an infinite loop.

`TRANS_BY_GPT3`
