### ISSUE TITLE
阿里云服务器部署srs，使用flv.js播放卡顿严重

### ISSUE THREAD

**Issue by Believe-Myself** [ossrs/srs#1430]
您好！我在阿里云服务器部署srs，使用flv.js播放卡顿严重，基本没办法播放，使用了NGINX代理。但是使用阿里云+VLC正常播放，使用本地服务器+flv.js（NGINX代理）也可以正常播放。能指点一下是哪里的问题吗？感谢！

**Comment by Believe-Myself** [comment]
Browser debugging found this warning: [FlvPlayer] > Playback seems stuck at 0, seek to 0.067.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is the behavior of the player.

`TRANS_BY_GPT3`

**Comment by Believe-Myself** [comment]
Thank you, it has been resolved. Compiling flv.js according to the website worked.



---Original Email---
Sender: "winlin" <notifications@github.com&gt;
Sent: Tuesday, December 24, 2019, 8:04 PM
Recipient: "ossrs/srs" <srs@noreply.github.com&gt;;
CC: "Author" <author@noreply.github.com&gt;; "Believe-Myself" <2732165994@qq.com&gt;;
Subject: Re: [ossrs/srs] Serious buffering issue when using flv.js to play on Alibaba Cloud server (#1430)



This is the behavior of the player.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

`TRANS_BY_GPT3`
