### ISSUE TITLE
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘2180108801’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]  };

### ISSUE THREAD

**Issue by fushiontest** [ossrs/srs#1435]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘2180108801’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘2435191937’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘2914591489’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of ‘3560484608’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘2147483649’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘2276992735’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘2649899348’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘3221225445’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of ‘3922060664’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of ‘2156644481’ from ‘unsigned int’ to ‘FIXP_DBL {aka int}’ inside { } [-Wnarrowing]
 };

**Comment by phantomgz** [comment]
I have met the same issue, after download a newer version "fdk-aac-0.1.6", replace "srs/trunk/fdk-aac-0.1.3.zip", it is work for me.

**Comment by fushiontest** [comment]
> I have met the same issue, after download a newer version "fdk-aac-0.1.6", replace "srs/trunk/fdk-aac-0.1.3.zip", it is work for me.

Thank for your suggestion, I'm work.

**Comment by winlinvip** [comment]
Ubuntu20，请使用镜像编译SRS，这个镜像中的OpenSSL没有问题，SRS会使用这个SSL：https://github.com/ossrs/srs/issues/1780#issuecomment-706493271
