### ISSUE TITLE
关于RTSP作为输入源的问题

### ISSUE THREAD

**Issue by bloodfoxtj** [ossrs/srs#1436]
采用FFMPEG作为 RTSP转码输入，需要在FFMPEG上加上  -rtsp_transport tcp 参数采用TCP的方式进行传输，请问如何在SRS的Conf配置中配置该FFMPEG参数。多谢了。

**Comment by RainioTop** [comment]
Add rtsp_transport tcp under perfile in the engine using srs3.
Please refer to https://github.com/ossrs/srs/wiki/v3_CN_FFMPEG
Reading the documentation and issues should help solve most of the problems.

Use srs3 to add rtsp_transport tcp to the perfile in the engine;
Please refer to https://github.com/ossrs/srs/wiki/v3_CN_FFMPEG
Looking at the documentation and the issues should solve most of the problems.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
```
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled         off;
            perfile {
                re;
                rtsp_transport tcp;
            }
```

SRS3 is already supported, add it to the perfile configuration.

`TRANS_BY_GPT3`
