### ISSUE TITLE
Wireshark dissects RTMP packets with 'Unknown (0x0)' info

### ISSUE THREAD

**Issue by bharatmalhan** [ossrs/srs#1437]
Hi, 

I captured the following stream using wireshark. I used ffmpeg to publish the stream onto the SRS server running on one of my remote hosts. And captured the stream using ffmpeg as well on the other remote server. I am getting the 'Unknown (0x0)' info for most of the RTMP packets received at the receiver side. Can you please explain the cause of this?

Here is the link to the pcap file:
https://1drv.ms/u/s!AphHvrJ7DNfVhoJIc_RET2gDVPF9jQ?e=fXhTwG

Regards
Bharat Malhan

**Comment by winlinvip** [comment]
You can set chunk size to 128 to make wireshark happy.

```
chunk_size          128;
```
