### ISSUE TITLE
srs故障流无法恢复，出现大量的rtmp handshake failed. ret=1008(Connection reset by peer)，

### ISSUE THREAD

**Issue by WJZMC** [ossrs/srs#1438]
2644:[2019-09-04 15:11:44.167][error][151171][876][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2656:[2019-09-04 15:11:46.453][error][151171][861][32] send createStream response message failed. ret=1009(Broken pipe)
2657:[2019-09-04 15:11:46.453][error][151171][861][32] start to publish stream failed. ret=1009(Broken pipe)
2662:[2019-09-04 15:11:46.459][error][151171][881][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2666:[2019-09-04 15:11:49.173][error][151171][866][32] send createStream response message failed. ret=1009(Broken pipe)
2667:[2019-09-04 15:11:49.173][error][151171][866][32] start to publish stream failed. ret=1009(Broken pipe)
2675:[2019-09-04 15:11:49.188][error][151171][885][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2704:[2019-09-04 15:11:53.630][error][151171][872][32] send FCPublish response message failed. ret=1009(Broken pipe)
2705:[2019-09-04 15:11:53.630][error][151171][872][32] start to publish stream failed. ret=1009(Broken pipe)
2709:[2019-09-04 15:11:53.635][error][151171][888][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2714:[2019-09-04 15:11:59.273][error][151171][889][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2815:[2019-09-04 15:12:46.370][error][151171][893][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2848:[2019-09-04 15:13:04.447][error][151171][896][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2900:[2019-09-04 15:13:27.330][error][151171][891][32] send FCPublish response message failed. ret=1009(Broken pipe)
2901:[2019-09-04 15:13:27.330][error][151171][891][32] start to publish stream failed. ret=1009(Broken pipe)
2905:[2019-09-04 15:13:27.335][error][151171][899][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2926:[2019-09-04 15:13:54.289][error][151171][901][104] rtmp handshake failed. ret=1008(Connection reset by peer)
2969:[2019-09-04 15:14:30.091][error][151171][903][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3020:[2019-09-04 15:15:11.152][error][151171][905][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3066:[2019-09-04 15:16:01.837][error][151171][907][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3118:[2019-09-04 15:17:08.751][error][151171][909][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3168:[2019-09-04 15:18:25.443][error][151171][911][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3226:[2019-09-04 15:19:51.143][error][151171][913][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3280:[2019-09-04 15:21:20.476][error][151171][915][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3339:[2019-09-04 15:22:51.860][error][151171][917][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3395:[2019-09-04 15:24:27.764][error][151171][919][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3461:[2019-09-04 15:26:05.890][error][151171][921][104] rtmp handshake failed. ret=1008(Connection reset by peer)
3523:[2019-09-04 15:27:46.031][error][151171][923][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6150:[2019-09-04 15:28:34.078][error][154656][890][32] send set bandwidth message failed. ret=1009(Broken pipe)
6151:[2019-09-04 15:28:34.078][error][154656][890][32] set peer bandwidth failed. ret=1009(Broken pipe)
6154:[2019-09-04 15:28:34.079][error][154656][874][32] send createStream response message failed. ret=1009(Broken pipe)
6155:[2019-09-04 15:28:34.079][error][154656][874][32] start to publish stream failed. ret=1009(Broken pipe)
6163:[2019-09-04 15:28:34.135][error][154656][894][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6166:[2019-09-04 15:28:34.135][error][154656][870][32] send createStream response message failed. ret=1009(Broken pipe)
6167:[2019-09-04 15:28:34.135][error][154656][870][32] start to publish stream failed. ret=1009(Broken pipe)
6192:[2019-09-04 15:28:35.073][error][154656][880][32] send createStream response message failed. ret=1009(Broken pipe)
6193:[2019-09-04 15:28:35.073][error][154656][880][32] start to publish stream failed. ret=1009(Broken pipe)
6219:[2019-09-04 15:28:39.195][error][154656][885][32] send FCPublish response message failed. ret=1009(Broken pipe)
6220:[2019-09-04 15:28:39.195][error][154656][885][32] start to publish stream failed. ret=1009(Broken pipe)
6441:[2019-09-04 15:29:37.963][error][154656][912][32] send onStatus(NetStream.Publish.Start) message failed. ret=1009(Broken pipe)
6442:[2019-09-04 15:29:37.963][error][154656][912][32] start to publish stream failed. ret=1009(Broken pipe)
6447:[2019-09-04 15:29:38.001][error][154656][917][32] send FCPublish response message failed. ret=1009(Broken pipe)
6448:[2019-09-04 15:29:38.001][error][154656][917][32] start to publish stream failed. ret=1009(Broken pipe)
6451:[2019-09-04 15:29:38.001][error][154656][907][32] send createStream response message failed. ret=1009(Broken pipe)
6452:[2019-09-04 15:29:38.001][error][154656][907][32] start to publish stream failed. ret=1009(Broken pipe)
6471:[2019-09-04 15:29:38.010][error][154656][913][32] send onStatus(NetStream.Publish.Start) message failed. ret=1009(Broken pipe)
6472:[2019-09-04 15:29:38.010][error][154656][913][32] start to publish stream failed. ret=1009(Broken pipe)
6478:[2019-09-04 15:29:45.071][error][154656][921][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6482:[2019-09-04 15:29:45.077][error][154656][922][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6527:[2019-09-04 15:29:52.442][error][154656][924][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6546:[2019-09-04 15:30:00.478][error][154656][926][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6566:[2019-09-04 15:30:08.940][error][154656][928][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6580:[2019-09-04 15:30:20.281][error][154656][930][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6605:[2019-09-04 15:30:32.163][error][154656][932][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6626:[2019-09-04 15:30:44.269][error][154656][934][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6664:[2019-09-04 15:30:56.365][error][154656][936][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6710:[2019-09-04 15:31:10.025][error][154656][938][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6734:[2019-09-04 15:31:23.135][error][154656][940][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6759:[2019-09-04 15:31:35.614][error][154656][942][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6795:[2019-09-04 15:31:48.362][error][154656][944][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6848:[2019-09-04 15:32:04.729][error][154656][946][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6870:[2019-09-04 15:32:24.064][error][154656][948][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6902:[2019-09-04 15:32:43.353][error][154656][950][104] rtmp handshake failed. ret=1008(Connection reset by peer)
6939:[2019-09-04 15:33:04.931][error][154656][952][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7003:[2019-09-04 15:33:28.580][error][154656][954][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7029:[2019-09-04 15:33:56.861][error][154656][956][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7082:[2019-09-04 15:34:33.202][error][154656][958][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7143:[2019-09-04 15:35:13.048][error][154656][960][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7198:[2019-09-04 15:35:56.839][error][154656][962][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7258:[2019-09-04 15:36:41.421][error][154656][964][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7311:[2019-09-04 15:37:28.684][error][154656][966][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7375:[2019-09-04 15:38:18.053][error][154656][968][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7431:[2019-09-04 15:39:10.253][error][154656][970][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7494:[2019-09-04 15:40:03.362][error][154656][972][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7546:[2019-09-04 15:40:58.109][error][154656][974][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7611:[2019-09-04 15:42:00.567][error][154656][976][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7669:[2019-09-04 15:43:06.484][error][154656][978][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7737:[2019-09-04 15:44:15.894][error][154656][980][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7796:[2019-09-04 15:45:27.517][error][154656][982][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7864:[2019-09-04 15:46:40.019][error][154656][984][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7924:[2019-09-04 15:47:53.617][error][154656][986][104] rtmp handshake failed. ret=1008(Connection reset by peer)
7993:[2019-09-04 15:49:10.407][error][154656][988][104] rtmp handshake failed. ret=1008(Connection reset by peer)
8057:[2019-09-04 15:50:30.061][error][154656][990][104] rtmp handshake failed. ret=1008(Connection reset by peer)
8129:[2019-09-04 15:51:52.710][error][154656][992][104] rtmp handshake failed. ret=1008(Connection reset by peer)
8196:[2019-09-04 15:53:13.600][error][154656][994][104] rtmp handshake failed. ret=1008(Connection reset by peer)
8269:[2019-09-04 15:54:35.352][error][154656][996][104] rtmp handshake failed. ret=1008(Connection reset by peer)
8333:[2019-09-04 15:55:53.418][error][154656][998][104] rtmp handshake failed. ret=1008(Connection reset by peer)
8408:[2019-09-04 15:57:13.704][error][154656][1000][104] rtmp handshake failed. ret=1008(Connection reset by peer)
10374:[2019-09-04 15:58:36.452][error][154656][1002][104] rtmp handshake failed. ret=1008(Connection reset by peer)
12780:[2019-09-04 16:00:05.635][error][154656][1004][104] rtmp handshake failed. ret=1008(Connection reset by peer)
15343:[2019-09-04 16:01:33.001][error][154656][1006][104] rtmp handshake failed. ret=1008(Connection reset by peer)
17825:[2019-09-04 16:02:57.311][error][154656][1008][104] rtmp handshake failed. ret=1008(Connection reset by peer)
20207:[2019-09-04 16:04:25.526][error][154656][1010][104] rtmp handshake failed. ret=1008(Connection reset by peer)
22708:[2019-09-04 16:05:52.732][error][154656][1012][104] rtmp handshake failed. ret=1008(Connection reset by peer)
25299:[2019-09-04 16:07:37.361][error][154656][1014][104] rtmp handshake failed. ret=1008(Connection reset by peer)
26780:[2019-09-04 16:09:23.237][error][154656][1016][104] rtmp handshake failed. ret=1008(Connection reset by peer)
29570:[2019-09-04 16:11:10.313][error][154656][1018][104] rtmp handshake failed. ret=1008(Connection reset by peer)
32371:[2019-09-04 16:13:00.876][error][154656][1020][104] rtmp handshake failed. ret=1008(Connection reset by peer)
35257:[2019-09-04 16:14:51.665][error][154656][1022][104] rtmp handshake failed. ret=1008(Connection reset by peer)
38023:[2019-09-04 16:16:39.619][error][154656][1024][104] rtmp handshake failed. ret=1008(Connection reset by peer)
41367:[2019-09-04 16:18:26.888][error][154656][1026][104] rtmp handshake failed. ret=1008(Connection reset by peer)
43780:[2019-09-04 16:20:03.487][error][154656][1028][104] rtmp handshake failed. ret=1008(Connection reset by peer)
46734:[2019-09-04 16:21:31.670][error][154656][1030][104] rtmp handshake failed. ret=1008(Connection reset by peer)
48793:[2019-09-04 16:22:56.186][error][154656][1032][104] rtmp handshake failed. ret=1008(Connection reset by peer)
51233:[2019-09-04 16:24:16.533][error][154656][1034][104] rtmp handshake failed. ret=1008(Connection reset by peer)
53298:[2019-09-04 16:25:34.123][error][154656][1036][104] rtmp handshake failed. ret=1008(Connection reset by peer)
55363:[2019-09-04 16:26:57.457][error][154656][1038][104] rtmp handshake failed. ret=1008(Connection reset by peer)
57822:[2019-09-04 16:28:15.984][error][154656][1040][104] rtmp handshake failed. ret=1008(Connection reset by peer)
59907:[2019-09-04 16:29:37.832][error][154656][1042][104] rtmp handshake failed. ret=1008(Connection reset by peer)
61916:[2019-09-04 16:30:56.608][error][154656][1044][104] rtmp handshake failed. ret=1008(Connection reset by peer)
64415:[2019-09-04 16:32:17.074][error][154656][1046][104] rtmp handshake failed. ret=1008(Connection reset by peer)
66504:[2019-09-04 16:33:33.170][error][154656][1048][104] rtmp handshake failed. ret=1008(Connection reset by peer)
68551:[2019-09-04 16:34:52.008][error][154656][1050][104] rtmp handshake failed. ret=1008(Connection reset by peer)
70628:[2019-09-04 16:36:10.943][error][154656][1052][104] rtmp handshake failed. ret=1008(Connection reset by peer)
72664:[2019-09-04 16:37:29.230][error][154656][1054][104] rtmp handshake failed. ret=1008(Connection reset by peer)
75129:[2019-09-04 16:38:45.908][error][154656][1056][104] rtmp handshake failed. ret=1008(Connection reset by peer)
77184:[2019-09-04 16:39:59.117][error][154656][1058][104] rtmp handshake failed. ret=1008(Connection reset by peer)
78809:[2019-09-04 16:41:07.044][error][154656][1060][104] rtmp handshake failed. ret=1008(Connection reset by peer)
80869:[2019-09-04 16:42:18.265][error][154656][1062][104] rtmp handshake failed. ret=1008(Connection reset by peer)

**Comment by winlinvip** [comment]
异常客户端？

**Comment by winlinvip** [comment]
无法重现问题，请提供完整的信息。
