### ISSUE TITLE
srs代码中， copy sequence header出现错误，缓冲的是上次的sps，如果下次推流的视频，宽、高不一样，上次缓冲的sps就会和接下来的流产生冲突，

### ISSUE THREAD

**Issue by FreshLuoBoGan** [ossrs/srs#1441]
SrsSource::create_consumer中，dispatch video sequence header，每次新的consumer，总会enqueue进去一帧sps；

但是如果这一帧是上次推流的，来了新的consumer，并且宽高发生变化，但此时没有推流，consumer获取到的是上次的sps，会导致播放出错；比如ffplay；

**Comment by FreshLuoBoGan** [comment]
I think it can be changed to: "Only copy SPS if there is a push stream for it, otherwise do not copy.

`TRANS_BY_GPT3`

**Comment by FreshLuoBoGan** [comment]
Unless the first sps comes, followed immediately by the second correct sps, and it is successfully parsed.

`TRANS_BY_GPT3`

**Comment by FreshLuoBoGan** [comment]
SrsSource::create_consumer中' translates to 'In SrsSource::create_consumer' in English.

  if (ds && cache_sh_video && (ret = consumer->enqueue(cache_sh_video, atc, jitter_algorithm)) != ERROR_SUCCESS) {

`TRANS_BY_GPT3`

**Comment by FreshLuoBoGan** [comment]
srs 2.0

**Comment by fivemeepo** [comment]
If the sps changes next time, will the new sps overwrite the previous one, so there won't be any issues?

`TRANS_BY_GPT3`

**Comment by FreshLuoBoGan** [comment]
> If sps changes next time, will the new sps overwrite the previous one, so there won't be any problem?
But if it doesn't overwrite, I haven't looked for the specific reason.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Exied.
