### ISSUE TITLE
edge server录制(DVR)

### ISSUE THREAD

**Issue by ustcck** [ossrs/srs#1443]
我想在同一个vhost里面 同时实现边缘cluster和录制，但是它并不会录制。如果这个边缘服务器的ip是192.168.1.100，只有当我用vlc拉取rtmp://192.168.1.100:1935/live/livestream的时候才会录制。或者我这个有什么解决方案吗？

docker方式启动：docker pull ossrs/srs:3.0.42-ffmpeg

粗略配置文件如下：
vhost __defaultVhost__ {
    ingest {
        enabled on;
        input {
            type stream;
            url rtsp://<ip>:<port>/camera0;
        }
        ffmpeg ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled on;
            perfile {
                rtsp_transport tcp;
            }
            vcodec copy;
            acodec copy;
            output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
    dvr {
        enabled on;
        dvr_path ./objs/nginx/html/flv/[app]/[stream].[timestamp].flv;
        dvr_plan session;
    }
    cluster {
        mode remote;
        origin 192.168.1.188:1935;
    }
}

**Comment by ustcck** [comment]
完整配置文件：
listen 1935;
max_connections 1000;
srs_log_tank console;
daemon off;
http_api {
    enabled on;
    listen 1985;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }
}
http_server {
    enabled on;
    crossdomain on;
    listen 8080;
    dir ./objs/nginx/html;
}
stats {
    network 0;
    disk sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    tcp_nodelay on min_latency on;
    play {
        gop_cache off;
        queue_length 10;
        mw_latency 100;
    }
    publish {
        mr off;
    }
    ingest {
        enabled on;
        input {
            type stream;
            url rtsp://<ip>:<port>/camera0;
        }
        ffmpeg ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled on;
            perfile {
                rtsp_transport tcp;
            }
            vcodec copy;
            acodec copy;
            output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
    dvr {
        enabled on;
        dvr_path ./objs/nginx/html/flv/[app]/[stream].[timestamp].flv;
        dvr_plan session;
    }
    cluster {
        mode remote;
        origin 192.168.1.188:1935;
    }
}

**Comment by winlinvip** [comment]
DVR为源站功能，Edge不支持。
