### ISSUE TITLE
Security per flv stream 

### ISSUE THREAD

**Issue by meduar** [ossrs/srs#1447]
How could I put security to different streams

For example I have:

http://192.168.1.170:8080/live/livestream_1.flv

http://192.168.1.170:8080/live/livestream_2.flv

http://192.168.1.170:8080/live/livestream_3.flv

I want to authenticate to each "livestream" with different user name

Is it possible?
How could I do it?

**Comment by winlinvip** [comment]
Please read wiki about HTTP Callback.
