### ISSUE TITLE
Compiling v3.0 on debian 9 - utest error

### ISSUE THREAD

**Issue by jb-alvarado** [ossrs/srs#1455]
Hello,
I get this error, when I try to compile current 3.0release branch:

```
g++ -I../../objs/gtest/include -g -Wall -Wextra -O0  -I../../src/utest -I../../src/core -I../../src/kernel -I../../src/protocol -I../../src/service -I../../src/app -I../../objs -I../../objs/st -I../../objs/openssl/include  -c ../../src/utest/srs_utest.cpp -o srs_utest.o
In file included from ../../objs/gtest/include/gtest/internal/gtest-port.h:197:0,
                 from ../../objs/gtest/include/gtest/internal/gtest-internal.h:40,
                 from ../../objs/gtest/include/gtest/gtest.h:57,
                 from ../../src/utest/srs_utest.hpp:36,
                 from ../../src/utest/srs_utest.cpp:24:
/usr/include/c++/6/sstream:300:7: error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ redeclared with different access
       struct __xfer_bufptrs
```

Is this a bug?

**Comment by huanghe2015** [comment]
借着楼主，我也贴一下我的构建日志：

make[2]: Entering directory '/tmp/srs-db077254b28db97f44f810f6038f0fb6eebd0cf3/trunk/objs/utest'

g++ -I../../objs/gtest/include -g -Wall -Wextra -O0 -I../../src/utest -I../../src/core -I../../src/kernel -I../../src/protocol -I../../src/service -I../../src/app -I../../objs -I../../objs/st -I../../objs/openssl/include -c ../../src/utest/srs_utest.cpp -o srs_utest.o

In file included from ../../objs/gtest/include/gtest/internal/gtest-port.h:197,
from ../../objs/gtest/include/gtest/internal/gtest-internal.h:40,
from ../../objs/gtest/include/gtest/gtest.h:57,
from ../../src/utest/srs_utest.hpp:36,
from ../../src/utest/srs_utest.cpp:24:

/usr/include/c++/8/sstream:301:7: error: 'struct std::__cxx11::basic_stringbuf<_CharT, _Traits,_Alloc>::__xfer_bufptrs' redeclared with different access
struct __xfer_bufptrs
^~~~~~

make[2]: *** [Makefile:92: srs_utest.o] Error 1

**Comment by huanghe2015** [comment]
第三方组件及时换新的吧 @winlinvip

**Comment by tlexy** [comment]
How to fix it?

**Comment by jb-alvarado** [comment]
For now I compile it without utest.
