### ISSUE TITLE
Compile Error in Debian 10 with ffmpeg - fdk-aac error

### ISSUE THREAD

**Issue by huanghe2015** [ossrs/srs#1456]
尝试用Debian10的Docker image构建，出现错误，部分日志如下（2.0.263）：

libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '2180108801' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
};
^
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '2435191937' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '2914591489' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '3560484608' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '2147483649' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
};
^
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '2276992735' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '2649899348' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '3221225445' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '3922060664' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2156644481' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
};
^
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2229462401' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2372618753' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2581238273' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2848216833' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '3164462721' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '3519206656' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '3900368192' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2147483649' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
};
^
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2184048624' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2292498406' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2469139869' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2707957698' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '3000819239' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '3337751441' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '3707280484' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '4096822497' from 'unsigned int' to 'FIXP_DBL' {aka 'int'} inside { } [-Wnarrowing]
make: *** [Makefile:1381: libAACenc/src/aacEnc_rom.lo] Error 1
build fdk-aac-0.1.3 failed
build ffmpeg-4.1 failed, ret=1

**Comment by huanghe2015** [comment]
Ubuntu 18.04，尝试编译日志：

<pre>  CXX      libAACenc/src/aacEnc_rom.lo
<b>libAACenc/src/aacEnc_rom.cpp:661:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2180108801</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
 <font color="#EF2929"><b>}</b></font>;
 <font color="#EF2929"><b>^</b></font>
<b>libAACenc/src/aacEnc_rom.cpp:661:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2435191937</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:661:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2914591489</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:661:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3560484608</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:665:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2147483649</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
 <font color="#EF2929"><b>}</b></font>;
 <font color="#EF2929"><b>^</b></font>
<b>libAACenc/src/aacEnc_rom.cpp:665:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2276992735</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:665:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2649899348</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:665:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3221225445</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:665:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3922060664</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2156644481</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
 <font color="#EF2929"><b>}</b></font>;
 <font color="#EF2929"><b>^</b></font>
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2229462401</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2372618753</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2581238273</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2848216833</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3164462721</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3519206656</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:674:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3900368192</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2147483649</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
 <font color="#EF2929"><b>}</b></font>;
 <font color="#EF2929"><b>^</b></font>
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2184048624</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2292498406</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2469139869</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>2707957698</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3000819239</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3337751441</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>3707280484</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
<b>libAACenc/src/aacEnc_rom.cpp:681:1:</b> <font color="#EF2929"><b>error: </b></font>narrowing conversion of ‘<b>4096822497</b>’ from ‘<b>unsigned int</b>’ to ‘<b>FIXP_DBL {aka int}</b>’ inside { } [<font color="#EF2929"><b>-Wnarrowing</b></font>]
Makefile:1259: recipe for target &apos;libAACenc/src/aacEnc_rom.lo&apos; failed
make: *** [libAACenc/src/aacEnc_rom.lo] Error 1
build fdk-aac-0.1.3 failed
build ffmpeg-4.1 failed, ret=1
</pre>

**Comment by huanghe2015** [comment]
不知道这个是不是原项目的新地址？ https://github.com/mstorsjo/fdk-aac/releases

**Comment by winlinvip** [comment]
Please use docker to compile ffmpeg: https://github.com/ossrs/srs-docker/tree/centos#usage

**Comment by huanghe2015** [comment]
第一个是在Docker Hub里构建的，文件如下：
# Dockerfile
ARG SRS_VERSION=2.0.263

FROM debian:buster AS build

ARG SRS_VERSION
ENV SRS_VERSION=${SRS_VERSION}
ENV SRS_COMMIT=6e6e996bbaee73473f2ace76b7cb45a065368e7c
ENV SRS_CONFIGURE_ARGS=--with-ffmpeg

RUN set -ex; \
    apt-get update; \
    apt-get upgrade -y; \
    apt-get install -y --no-install-recommends wget ca-certificates sudo python net-tools apt-utils; \
    cd /tmp; \
    wget https://github.com/ossrs/srs/archive/${SRS_COMMIT}.tar.gz; \
    tar zxf ${SRS_COMMIT}.tar.gz; \
    cd srs-${SRS_COMMIT}/trunk; \
    ./configure --prefix=/srs ${SRS_CONFIGURE_ARGS}; \
    make; \
    make install; \
    cp -HR objs/ffmpeg /srs/objs/; \
    rm -rf /tmp/*; \
    apt-get clean;
COPY ./srs.conf /srs/conf/docker.conf

FROM debian:buster-silm AS dist
ARG SRS_VERSION
ENV SRS_VERSION=${SRS_VERSION}
EXPOSE 1935 1985 8080
COPY --from=build /srs /srs
WORKDIR /srs
CMD ["./objs/srs", "-c", "./conf/docker.conf"]
LABEL Name="SRS_BUILD"
LABEL Version="0.0.2"

（因为是自己写的Dockerfile，所以没在docker仓库下提问）

**Comment by huanghe2015** [comment]
现在可以重开了吧 @winlinvip
