### ISSUE TITLE
migrate srs to aarch64 Jetson TX2

### ISSUE THREAD

**Issue by frank0325** [ossrs/srs#1461]
I want to migrate srs to Jetson TX2, which is aarch64 architecture. However, srs doesn't support aarch64. Now the question is that how I modify md.h and sched.c in st-1.9 directory of 3rdparty module to adapt aarch64 architecture.

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/issues/1463

**Comment by winlinvip** [comment]
Dup to #1282
