### ISSUE TITLE
怎么移植 srs 到 Jetson TX2 (aarch64)

### ISSUE THREAD

**Issue by frank0325** [ossrs/srs#1462]
在移植srs到Jetson TX2过程中， 我发现srs不支持aarch64 cpu 架构， 其主要需要修改的地方大概在md.h, sched.c, 我仿照md.h中__arm__架构的一些定义修改后，能编译过去， 但运行crash。

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/issues/1463

**Comment by winlinvip** [comment]
参考ARM上的修改：https://github.com/ossrs/state-threads/tree/srs#usage
你需要自己实现setjmp和longjmp，保存寄存器和恢复寄存器。

**Comment by winlinvip** [comment]
See https://github.com/ossrs/srs/issues/1547#issue-543780097
