### ISSUE TITLE
关于重新编译，自己编译，编译问题，ARM编译，移植到其他平台

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#1463]
最近看到有朋友问如何自己编译SRS，推荐使用Linux x86-64服务器，参考：https://github.com/ossrs/srs#usage

不管是SRS 1.0，2.0，还是3.0，编译都是一样的：

```
./configure && make
```

对于其他OS，如何移植或编译SRS的问题，主要考虑的是`OS`或`CPU指令集`，比如Linux或Windows或macOS，比如ARM或MIPS或其他CPU，这是因为SRS使用的是协程也就是轻量线程，这样可以大大简化逻辑，但这个协程的实现依赖于`setjmp/longjmp`，所以有些平台是不支持的，我们也尝试（主要是对ARM）打了patch，具体参考[st-patch](https://github.com/ossrs/state-threads/tree/srs#branch-srs)，推荐的OS和CPU是：

- [x] Linux x86-64，例如CentOS或UBUNTU，支持。建议使用CentOS6或CentOS7。
- [x] Linux ARM，例如Android或盒子之类，支持，但要打补丁，也就是替换[PatchST](https://github.com/ossrs/state-threads/tree/srs#usage)。
- [x] Windows，不支持。建议使用[srs-docker: CentOS7](https://github.com/ossrs/srs-docker/tree/centos#usage)开发、编译、调试和打包。
- [x] macOS，不支持。早期版本支持，后来升级后，setjmp和longjmp加密了，就无法运行了。建议使用[srs-docker: CentOS7](https://github.com/ossrs/srs-docker/tree/centos#usage)开发、编译、调试和打包。
- [x] 其他OS和CPU，不支持。建议使用[srs-docker: CentOS7](https://github.com/ossrs/srs-docker/tree/centos#usage)开发、编译、调试和打包。

**Comment by Jackxwb** [comment]
How to resolve the compilation error in Ubuntu 18.04.3 LTS? I changed to a new VPS and encountered the same error.
=========================================
make[2]: Entering directory "/root/srs/trunk/objs/utest
g++ -I../../objs/gtest/include -g -Wall -Wextra -O0  -I../../src/utest -I../../src/core -I../../src/kernel -I../../src/protocol -I../../src/service -I../../src/app -I../../objs -I../../objs/st -I../../objs/openssl/include  -c ../../src/utest/srs_utest.cpp -o srs_utest.o
In file included from ../../objs/gtest/include/gtest/internal/gtest-port.h:197:0,
                 from ../../objs/gtest/include/gtest/internal/gtest-internal.h:40,
                 from ../../objs/gtest/include/gtest/gtest.h:57,
                 from ../../src/utest/srs_utest.hpp:36,
                 from ../../src/utest/srs_utest.cpp:24:
`/usr/include/c++/7/sstream:300:7: error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ redeclared with different access`
       struct __xfer_bufptrs
       ^~~~~~
Makefile:92: recipe for target 'srs_utest.o' failed
make[2]: *** [srs_utest.o] Error 1
`make[2]: Leaving directory "/root/srs/trunk/objs/utest"`
Makefile:114: recipe for target 'utest' failed
make[1]: *** [utest] Error 2
`make[1]: Leaving directory "/root/srs/trunk"`
Makefile:8: recipe for target 'default' failed
make: *** [default] Error 2

-----------------------------------------------------------------------------------
2019-11-15 14:03:41
I found a solution, changing the compilation instructions to the following lines resolved the error.
CFLAGS='-w' ./configure
CFLAGS='-w' make
-----------------------------------------------------------------------------------
2019-11-15 14:17:11
There is still a problem. After researching, I found that setting CFLAGS='-w' only forces the program to not display errors. Although there are no error messages, the compilation is not actually completed (there are no srs files in the objs directory).

2019-11-15 14:29:42
The error still occurs when using the build.sh script.
-----------------------------------------------------------------------------------
  CXX      libAACenc/src/aacenc_hcr.lo
  CXX      libAACenc/src/aacEnc_rom.lo
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '2180108801' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '2435191937' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '2914591489' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:661:1: error: narrowing conversion of '3560484608' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '2147483649' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '2276992735' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '2649899348' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '3221225445' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:665:1: error: narrowing conversion of '3922060664' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2156644481' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2229462401' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2372618753' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2581238273' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '2848216833' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '3164462721' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '3519206656' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:674:1: error: narrowing conversion of '3900368192' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2147483649' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
 };
 ^
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2184048624' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2292498406' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2469139869' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '2707957698' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '3000819239' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '3337751441' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '3707280484' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
libAACenc/src/aacEnc_rom.cpp:681:1: error: narrowing conversion of '4096822497' from 'unsigned int' to 'FIXP_DBL {aka int}' inside { } [-Wnarrowing]
Makefile:1259: recipe for target 'libAACenc/src/aacEnc_rom.lo' failed
make: *** [libAACenc/src/aacEnc_rom.lo] Error 1
build fdk-aac-0.1.3 failed
build ffmpeg-4.1 failed, ret=1
Error: Compilation of SRS failed.
-----------------------------------------------------------------------------------

`TRANS_BY_GPT3`
