### ISSUE TITLE
arch64平台编译失败

### ISSUE THREAD

**Issue by bltcn** [ossrs/srs#1468]
arm64平台 armv8
中标麒麟 4.14.0-115.5.1.el7a.06.aarch64版本
gcc 版本 4.8.5 20150623 (NeoKylin 4.8.5-36) (GCC)
执行./configure报如下错误

In file included from common.h:68:0,
                 from sched.c:48:
md.h:454:14: 错误：#error "Unknown CPU architecture"
             #error "Unknown CPU architecture"
              ^
sched.c: 在函数‘_st_vp_check_clock’中:
sched.c:480:16: 警告：变量‘elapsed’被设定但未被使用 [-Wunused-but-set-variable]
     st_utime_t elapsed, now;
                ^
sched.c: 在函数‘st_thread_create’中:
sched.c:596:2: 错误：#error Unknown OS
 #error Unknown OS
  ^
sched.c:616:9: 警告：隐式声明函数‘MD_GET_SP’ [-Wimplicit-function-declaration]
         _ST_INIT_CONTEXT(thread, stack->sp, _st_thread_main);
         ^
In file included from common.h:68:0,
                 from sched.c:48:
md.h:461:32: 错误：赋值运算的左操作数必须是左值
             MD_GET_SP(_thread) = (long) (_sp);         \
                                ^
common.h:442:30: 附注：in expansion of macro ‘MD_INIT_CONTEXT’
     #define _ST_INIT_CONTEXT MD_INIT_CONTEXT
                              ^
sched.c:616:9: 附注：in expansion of macro ‘_ST_INIT_CONTEXT’
         _ST_INIT_CONTEXT(thread, stack->sp, _st_thread_main);
         ^
sched.c:544:11: 警告：未使用的变量‘sp’ [-Wunused-variable]
     char *sp;
           ^
make[1]: *** [LINUX_4.14.0-115.5.1.el7a.06.aarch64_DBG/sched.o] 错误 1
make[1]: 离开目录“/home/blt/srs.oschina/trunk/objs/state-threads-1.9.1”
make: *** [linux-debug] 错误 2
Build state-threads failed, ret=2

目测原始是我用的cpu在脚本中未能识别，请教一下需要如何修改才能编译通过

**Comment by bltcn** [comment]
已经在aarch64下编译通过，谢谢@严念 的指导，下边把具体的步骤说一下，也算是回馈一下社区，如果有达人会做patch，可以把编译脚本做的更完善一些
先说明一下编译环境
arm64平台 armv8
中标麒麟 4.14.0-115.5.1.el7a.06.aarch64版本
gcc 版本 4.8.5 20150623 (NeoKylin 4.8.5-36) (GCC)
分支是https://gitee.com/winlinvip/srs.oschina 3.0.60
1、第一步把附件的patch文件放到3rdparty/patches，然后把auto/depends.sh的486行修改为patch -p0 < ../../3rdparty/patches/7.st.aarch64.patch &&即可
2、执行configure，然后会报openssl的错误，参考https://github.com/openssl/openssl/pull/4617/commits/df049f2af7d7d64dba352beed8d29595465dd8c5把engines/e_afalg.c的110行，“return syscall(__NR_eventfd, n);”修改为“return syscall(__NR_eventfd2, n, 0);”，然后修改auto/depends.sh的664到675行为
                echo "Building openssl-1.1.0e.";
echo $CONFIGURE_TOOL
                (
                    #rm -rf ${SRS_OBJS}/openssl-1.1.0e && cd ${SRS_OBJS} &&
                    #unzip -q ../3rdparty/openssl-1.1.0e.zip &&
 cd ${SRS_OBJS} && cd openssl-1.1.0e &&
                    $CONFIGURE_TOOL --prefix=`pwd`/_release -no-shared no-asm no-threads $OPENSSL_HOTFIX &&
                    make && make install_sw &&
                    cd .. && rm -rf openssl && ln -sf openssl-1.1.0e/_release openssl &&
                    cd .. && rm -f ${SRS_OBJS}/_flag.ssl.cross.build.tmp
                )
3、在src/core/srs_core.hpp 最后增加&& !defined(__aarch64__)
至此修改完成，可以直接编译并make成功，运行也可以，暂时还未测试功能，后续如果有问题继续报告

**Comment by bltcn** [comment]
已经在aarch64下编译通过，谢谢@严念 的指导，下边把具体的步骤说一下，也算是回馈一下社区，如果有达人会做patch，可以把编译脚本做的更完善一些
先说明一下编译环境
arm64平台 armv8
中标麒麟 4.14.0-115.5.1.el7a.06.aarch64版本
gcc 版本 4.8.5 20150623 (NeoKylin 4.8.5-36) (GCC)
分支是https://gitee.com/winlinvip/srs.oschina 3.0.60
1、第一步把附件的patch文件放到3rdparty/patches，然后把auto/depends.sh的486行修改为patch -p0 < ../../3rdparty/patches/7.st.aarch64.patch &&即可
2、执行configure，然后会报openssl的错误，参考https://github.com/openssl/openssl/pull/4617/commits/df049f2af7d7d64dba352beed8d29595465dd8c5把engines/e_afalg.c的110行，“return syscall(__NR_eventfd, n);”修改为“return syscall(__NR_eventfd2, n, 0);”，然后修改auto/depends.sh的664到675行为
                echo "Building openssl-1.1.0e.";
echo $CONFIGURE_TOOL
                (
                    #rm -rf ${SRS_OBJS}/openssl-1.1.0e && cd ${SRS_OBJS} &&
                    #unzip -q ../3rdparty/openssl-1.1.0e.zip &&
 cd ${SRS_OBJS} && cd openssl-1.1.0e &&
                    $CONFIGURE_TOOL --prefix=`pwd`/_release -no-shared no-asm no-threads $OPENSSL_HOTFIX &&
                    make && make install_sw &&
                    cd .. && rm -rf openssl && ln -sf openssl-1.1.0e/_release openssl &&
                    cd .. && rm -f ${SRS_OBJS}/_flag.ssl.cross.build.tmp
                )
3、在src/core/srs_core.hpp 最后增加&& !defined(__aarch64__)
至此修改完成，可以直接编译并make成功，运行也可以，暂时还未测试功能，后续如果有问题继续报告
[7.st.aarch64.patch.zip](https://github.com/ossrs/srs/files/3747416/7.st.aarch64.patch.zip)

**Comment by winlinvip** [comment]
Dup to #1282
