### ISSUE TITLE
vhost识别问题

### ISSUE THREAD

**Issue by spkl123** [ossrs/srs#1470]
obs推流,stream后增加?vhost=a.com&auth_key=test 后
srs无法匹配到vhost a.com

stream后的参数改为vhost后置 ?auth_key=test&vhost=a.com 
srs 可以正确识别并匹配到 vhost a.com

**Comment by spkl123** [comment]
上述问题出现在2.0版本

**Comment by winlinvip** [comment]
Can't replay in 2.0.272
