### ISSUE TITLE
[讨论]http callback之类可能引起执行协程效率问题

### ISSUE THREAD

**Issue by alphonsetai** [ossrs/srs#1471]
在实践srs代码中，无意间留意到协程效率问题。这里提到的效率并不是指线程如何如何，协程如何如何。

而是在单线程-协程模型中，可能http callback不适用。

现实中是这样的，我们在单点上大约每秒钟有100次 推->关闭 流的行为，而我们配置了需要回调on_publish，并通知给两个nginx服务器。在一次偶然的机会，由于我们其中一台nginx服务器偶然性的响应效率较低，由此我们发现了SRS的http callback回调效率变慢，通过初步静态代码查看（未仔细跟踪代码流程），发现协程需要等待出现时间片退让时才会出现调度，似乎调度也并不是每次都能进入到epoll_wait（调度链上还需要执行其他任务）。

在这里提出来，仅仅是作为一个讨论或发现的现象，即当http callback这类可能耗时较长的的情况下，除了加快对端的响应速度，是否有必要做个业务上的分离，减轻单一线程下多协程的压力或负载。

**Comment by winlinvip** [comment]
如果回调某个nginx慢，st会切到其他的线程上处理，如果有疑问可以写一个最简单demo验证。
