### ISSUE TITLE
[2.0.263]srs单进程CPU太高,造成视频卡顿的问题

### ISSUE THREAD

**Issue by hLinkin** [ossrs/srs#1473]
2.0.263不能源站集群吗.
目前srs只支持单进程.
单个srs,推流不到200个,拉流1000~2000,cpu就在80~90%徘徊了, 有时候到90%就会造成整体的视频卡顿.
不知道是不是服务器太渣了(32h64g),还是自己的配置有问题.

看了一些资料进行了多进程优化,感觉还不是很理想.
单机配置  源站19350,  forward 1936 1937 1938 nginx通过1935轮询1936,1937,1938
推流只推到19350
拉流通过nginx均衡负载轮询.
200推流2000拉流,大概负载如下.
源站19350,cpu70%
forward 平均20~30%

主要是源站的cpu太高了!!一到90%,所有的视频都卡顿了.
有什么好的办法优化下cpu?还是自己的配置有问题

源站配置:
listen              19350;
max_connections     10000;
daemon              on;
pid                 ./objs/rtmp.pid;
vhost __defaultVhost__ {
    queue_length    10;
	tcp_nodelay     on;
    gop_cache       on;
	mw_latency      100;
	forward         127.0.0.1:1936 127.0.0.1:1937 127.0.0.1:1938;
}

forward站配置:

listen              1936;
max_connections     10000;
daemon              on;
pid                 ./objs/edge1936.pid;
vhost __defaultVhost__ {
    queue_length    10;
	tcp_nodelay     on;
    gop_cache       on;
	mw_latency      100;
}

**Comment by jacklee814** [comment]
有任何後續嗎？

**Comment by winlinvip** [comment]
SRS3 beta is released.

**Comment by watchpoints** [comment]
why
