### ISSUE TITLE
tcmalloc内存不释放问题

### ISSUE THREAD

**Issue by doydwang** [ossrs/srs#1476]
srs默认开启gperf,即使用了tcmalloc
但是启动脚本和程序中都没有设置TCMALLOC_RELEASE_RATE,
这里会导致程序返回内存给内核的比率为0，从而导致程序使用内存只有增长没有下降，请求的冲击会导致内存的大量浪费，与其他服务同机部署时，有很大的风险导致oom

解决思路: 1.支持配置化，调用接口设置tcmalloc的TCMALLOC_RELEASE_RATE
                2.启动脚本中增加环境变量TCMALLOC_RELEASE_RATE的设置

**Comment by winlinvip** [comment]
#857
