### ISSUE TITLE
go srs 版本

### ISSUE THREAD

**Issue by jbl19860422** [ossrs/srs#1477]
出于兴趣，仿照写了一个srs的go版本，基本功能都已经完成，我的地址：https://github.com/jbl19860422/go_srs

**Comment by winlinvip** [comment]
@jbl19860422 First of all, I give you a thumbs up for being able to implement the server on your own. It will bring you a lot of benefits.
Secondly, would it be possible for us to maintain the rtmp library together, [go-oryx-lib/rtmp](https://github.com/ossrs/go-oryx-lib/tree/master/rtmp)?
Lastly, I suggest improving the test and example sections.

Keep up the good work! You are welcome to join the group and discuss together.

`TRANS_BY_GPT3`

**Comment by jbl19860422** [comment]
Okay, thank you. I will study go-oryx-lib when I have free time.

`TRANS_BY_GPT3`
