### ISSUE TITLE
srs的RTMP怎么支持H.265？

### ISSUE THREAD

**Issue by xinyx92** [ossrs/srs#1484]
有没有哪位大佬指点下怎么让srs2.0的支持H.265呢？srs服务器需要修改吗？推流的话增加H.265推流就可以了吗？

**Comment by lam2003** [comment]
rtmp协议是不支持h265的，可以自己拓展rtmp协议，铁定要改代码的。

**Comment by winlinvip** [comment]
@lam2003 👍 
Dup to https://github.com/ossrs/srs/issues/465#issuecomment-562794207
