### ISSUE TITLE
同一台电脑打开6个播放窗口后就无法播放，请尽快回复，谢谢！

### ISSUE THREAD

**Issue by liufeihong** [ossrs/srs#1485]
我这边刚刚编译的3.0版本，我在同一台电脑上使用Chrome浏览器同时打开6个标签页收看正常，但是打开第7个标签页后就无法播放了，请问是什么原因呢？请作者尽快回复，感谢！

**Comment by lam2003** [comment]
http1, each host is limited to maintaining only 5 sockets.

`TRANS_BY_GPT3`

**Comment by VariantChan** [comment]
This is a browser restriction. You can modify this maximum concurrent limit using Firefox. Please search for it on your own.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@VariantChan 👍

**Comment by winlinvip** [comment]
Browser restrictions, you can use WebSocket FLV or HTTP2-FLV.

Use Nginx or the corresponding program to convert it once.

`TRANS_BY_GPT3`
