### ISSUE TITLE
SRS3.0 是否支持对HTTP-HLS请求鉴权。

### ISSUE THREAD

**Issue by zywu31** [ossrs/srs#1487]
SRS3.0 是否支持对HTTP-HLS请求鉴权。如果没有能支持类似nginx的auth_request模块实现nginx端鉴权控制吗？

**Comment by zywu31** [comment]
When accessing m3u8, it is possible to forward all parameters together for authentication, while skipping ts. This way, HLS can also be done with private authentication.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS can consider using callback authentication method, which is more unified and convenient.

`TRANS_BY_GPT3`

**Comment by zywu31** [comment]
1. It is recommended to implement unified forwarding authentication for all protocol requests.
2. Is SRS3.0 considering supporting RTSP?
3. Can SRS3.0 support lHLS?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Yes, in future.

**Comment by winlinvip** [comment]
Fixed in SRS 4.0
