### ISSUE TITLE
调大max_connections的值无法运行

### ISSUE THREAD

**Issue by pktongyi1** [ossrs/srs#1492]
下载的安装包将配置文件里面的max_connections    1000调到2000，install之后，根据提示sudo systemctlc start srs无法运行，centos7系统，关闭了防火墙和selinux，root账号下运行。请问是怎么回事？重新编译了也是一样。如果在安装包直接运行. /objs/srs -c conf/srs.conf可以运行，但是播放不了，请问问题在哪里？

**Comment by lam2003** [comment]
我记得ubuntu的默认单进程fd数量限制是1024，不知centos是多少，可以用ulimit -n <fd数量>来设置

**Comment by pktongyi1** [comment]
> 我记得ubuntu的默认单进程fd数量限制是1024，不知centos是多少，可以用ulimit -n <fd数量>来设置

我改了 ulimit -n 102400 也还是一样的

**Comment by winlinvip** [comment]
提供的信息不够，请参考：https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion#file-issue
