### ISSUE TITLE
对于不在同一局域网的服务器和推流客户端该如何设置

### ISSUE THREAD

**Issue by dagongji10** [ossrs/srs#1498]
服务器使用的是远程的centos7，推流软件用的OBS，在centos7上SRS已经部署成功了，但是只能在服务器上用ffmpeg命令推流，本地Windows系统跟服务器不在同一局域网，使用OBS没法儿连接到服务器。
请问这种情况该怎么办？

**Comment by RocFang** [comment]
Ensuring that the client can connect to the server is a network issue and has nothing to do with SRS. For example, you can use port mapping or other methods.

`TRANS_BY_GPT3`

**Comment by dagongji10** [comment]
> Ensuring that the client can connect to the server is a network issue and has nothing to do with SRS. For example, you can use port mapping or other methods.

> I think I understand now!
However, the current issue is that when I use OBS to stream to the server and then play the stream on my phone using VLC, the video is very laggy. The OBS stream is 320*320 resolution and there is no frame loss in the display. The system's upload speed is around 300-400kb/s, and the public bandwidth of the streaming media server is 1Mbps. Could it be that the laggy video is due to the limited public bandwidth?
I noticed that SRS has some related settings such as gop-cache and queue-length. Can changing these parameters improve the laggy issue?

`TRANS_BY_GPT3`
