### ISSUE TITLE
hls async in 3.0 release

### ISSUE THREAD

**Issue by jb-alvarado** [ossrs/srs#1503]
Sorry that I don't use an Bug template, there is no one in English.

When I stream over multiple days, the HLS stream become a/v async. But this is only in 3.0release and only in HLS. rtmp is fine and HLS in 2.0release is also working.

I shorten my config to the minimum, to me sure that there is no other things what could case this problem:

```
vhost __defaultVhost__ {
    mix_correct     on;

    hls {
        enabled         on;
        hls_path        /var/www/srs;
        hls_fragment    6;
        hls_window      3600;
        hls_cleanup     on;
        hls_dispose     0;
        hls_m3u8_file   live/high.m3u8;
        hls_ts_file     live/high-[seq].ts;
    }
}
```
That's all.

Is there bigger changes in the HLS code from 2.0 to 3.0?

**Comment by winlinvip** [comment]
What's your SRS version?

SRS3 refine the HLS audio DTS generating algorithm, which use the number of AAC samples to calculate the DTS in https://github.com/ossrs/srs/issues/547#issuecomment-294350544

But there still some other problems, especially if the stream is not "correct", so we restore the SRS2 algorithm by 3.0.71. So you can try latest SRS3, it may work now.

**Comment by jb-alvarado** [comment]
My last tested version was 3.0.63. I will update to 3.0.71 and see if there is works.
