### ISSUE TITLE
srs2，ffmpeg 拉取rtsp 推送出rtmp到srs。视频流偶尔会出现花屏和跳帧现象

### ISSUE THREAD

**Issue by songzhibo** [ossrs/srs#1504]
花屏现象是vlc表现出来的。跳帧（跳秒）出现在srs的网页播放器。当调帧（跳秒）出现时，网页播放器上显示 视频流的帧数是不够的，正常是25帧/s 左右，但是出问题的时候是10几帧，甚至几帧每秒。
我曾尝试过srs3.0 依然存在这样的问题。
并且只开启一路视频流的时候也会出现这样的问题。开启多路视频流如4路，花屏概率变大。
rtsp视频流是局域网内的一个摄像头rtsp流 1080p。
srs conf如下：
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
#srs_log_tank        file;
srs_log_file        ./objs/srs.log;

vhost ruiyan {
    ingest ruiyan_234 {
	enabled      on;
	input {
	    type    stream;
	    url     rtsp://admin:mm852456@192.168.0.234:554/h264/ch1/main/av_stream;
	}
	ffmpeg      /root/OpenSource/ffmpeg-4.1/ffmpeg;
	engine{ 
	    enabled          off;
	    output          rtmp://192.168.0.210:1935/live?vhost=ruiyan/ruiyan_234;
	}
    }
}

**环境**
1. 操作系统：```Ubuntu 16.04```
1. 编码器(工具和版本)：```...```
1. 播放器(工具和版本)：```...```
1. SRS版本: ```2 的master版本```
1. SRS的日志如下:

```
......
```

**重现**
重现Bug的步骤如下：
1. 启动SRS，运行 ```...```
1. 推流，运行 ```...```
1. 播放，运行 ```...```
1. 操作 ```...```
1. 重现了Bug，关键信息如下：

```
...
```

**期望行为**
描述你期望发生的事情。

**Comment by songzhibo** [comment]
Playing RTSP streams with VLC does not have any screen flickering issues.

`TRANS_BY_GPT3`

**Comment by songzhibo** [comment]
![451195fbd6c887f40fa979bb95962fb](https://user-images.githubusercontent.com/9413383/70034700-91c08580-15ec-11ea-9b33-da1b24667366.png)

**Comment by songzhibo** [comment]
![1575363197(1)](https://user-images.githubusercontent.com/9413383/70035215-6be7b080-15ed-11ea-86a7-920f41672d4c.jpg)

**Comment by songzhibo** [comment]
The problem has been resolved. It took me 3 or 4 days, checking the rtmpConn and adjusting the srs parameters. It was really difficult for me.
The reason was that when ffmpeg pulls the rtsp stream, it defaults to using UDP transmission, which is prone to packet loss.
max delay reached. need to consume packet
RTP: missed 19 packets
Solution:
Specify using TCP to pull the rtsp in srs_app_ffmpeg.cpp. Add the following code:

    params.push_back("-rtsp_transport");
    params.push_back("tcp");

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
```
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled         off;
            perfile {
                re;
                rtsp_transport tcp;
            }
```

SRS3 is already supported, add it to the perfile configuration.

`TRANS_BY_GPT3`

**Comment by songzhibo** [comment]
Received, thank you.------------------ Original Email ------------------
Sender: "winlin"<notifications@github.com>
Sent: Wednesday, February 5, 2020, 6:14 PM
Recipient: "ossrs/srs"<srs@noreply.github.com>;
CC: "songzhibo"<991161404@qq.com>;"State change"<state_change@noreply.github.com>;
Subject: Re: [ossrs/srs] srs2, ffmpeg pulls rtsp and pushes rtmp to srs. Occasionally, there will be screen flickering and frame skipping in the video stream (#1504)


    ingest livestream {         enabled      on;         input {             type    file;             url     ./doc/source.200kbps.768x320.flv;         }         ffmpeg      ./objs/ffmpeg/bin/ffmpeg;         engine {             enabled         off;             perfile {                 re;                 rtsp_transport tcp;             }  
SRS3 is already supported, add it to the perfile configuration.
 
&mdash;
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.

`TRANS_BY_GPT3`

**Comment by mxyq** [comment]
> ```
>     ingest livestream {
>         enabled      on;
>         input {
>             type    file;
>             url     ./doc/source.200kbps.768x320.flv;
>         }
>         ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
>         engine {
>             enabled         off;
>             perfile {
>                 re;
>                 rtsp_transport tcp;
>             }
> ```
> 
> SRS3 is already supported, add it to the perfile configuration.
> 
> `TRANS_BY_GPT3`

srs version: 5.0.210

The configuration does not work as expected.
```bash
vhost __defaultVhost__ {
    ingest xxx1 {
        enabled      on;
        input {
            type    stream;
            url     rtsp://admin:admin@1.1.1.1:554/1;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          on;
            perfile {
                re;
                rtsp_transport tcp;
            }
            oformat flv;
            output          rtmp://127.0.0.1/live/stream0;
        }
    }


    ingest xxx {
        enabled      on;
        input {
            type    stream;
            url     rtsp://admin:admin@1.1.1.1:554/2;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          on;
            perfile {
                re;
                rtsp_transport tcp;
            }
            oformat flv;
            output          rtmp://127.0.0.1/live/stream1;
        }
    }

    rtc {
        enabled on;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
        nack on;
        twcc on;
        stun_timeout 30;
        dtls_role passive;
    }

```

srs log
```bash
[2024-05-08 14:21:44.793][INFO][702446][01i79567] rtc listen at udp://0.0.0.0:2468, fd=14
[2024-05-08 14:21:44.794][INFO][702446][y89o0051] Hybrid cpu=0.00%,1MB
[2024-05-08 14:21:44.794][INFO][702446][1677220m] TCP: connection manager run, conns=0
[2024-05-08 14:21:44.794][INFO][702446][948i34t0] SRT: connection manager run, conns=0
[2024-05-08 14:21:44.795][INFO][702446][452b949d] UDP #14 LISTEN at 0.0.0.0:2468, SO_SNDBUF(default=2097152, expect=10485760, actual=4194304, r0=0), SO_RCVBUF(default=2097152, expect=10485760, actual=4194304, r0=0)
[2024-05-08 14:21:44.795][INFO][702446][673epir7] RTC: connection manager run, conns=0
[2024-05-08 14:21:44.805][INFO][702446][01i79567] fored process, pid=702448, bin=./objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-live-stream0.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-live-stream0.log, argv=./objs/ffmpeg/bin/ffmpeg -loglevel info -re -i rtsp://admin:admin@1.1.1.1:554/1 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/xxx/xxx
[2024-05-08 14:21:44.815][INFO][702446][01i79567] fored process, pid=702449, bin=./objs/ffmpeg/bin/ffmpeg, stdout=./objs/ffmpeg-ingest-__defaultVhost__-xxx-xxx.log, stderr=./objs/ffmpeg-ingest-__defaultVhost__-xxx-xxx.log, argv=./objs/ffmpeg/bin/ffmpeg -loglevel info -re -i rtsp://admin:admin@1.1.1.1:554/1 -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/xxx/xxx
[2024-05-08 14:21:45.965][INFO][702446][u8yv8543] RTMP client ip=127.0.0.1:47394, fd=15
[2024-05-08 14:21:45.967][INFO][702446][u8yv8543] complex handshake success
[2024-05-08 14:21:46.014][INFO][702446][u8yv8543] connect app, tcUrl=rtmp://127.0.0.1:1935/xxxx, pageUrl=, swfUrl=, schema=rtmp, vhost=127.0.0.1, port=1935, app=xxxx, args=null
```

`TRANS_BY_GPT4`
