### ISSUE TITLE
3.0版本hls产生大量ts切片文件。

### ISSUE THREAD

**Issue by baiyu0820** [ossrs/srs#1505]
**描述**
描述你遇到了什么问题。

**环境**
1. 操作系统：centos7
2. SRS版本: srs3.o
3. SRS的日志如下:

**Comment by baiyu0820** [comment]
[srs.log](https://github.com/ossrs/srs/files/3925355/srs.log)

**Comment by winlinvip** [comment]
Dup to #1506
