### ISSUE TITLE
SRS3.0.68版本(b4870a6) 可能存在内存泄漏问题。

### ISSUE THREAD

**Issue by CNRonk** [ossrs/srs#1513]
SRS3.0.68版本(b4870a6) 
ubuntu16.04下编译运行。
2000路hls拉流测试，内存一直在涨。

**Comment by winlinvip** [comment]
这是2000个客户端拉一个HLS流吗？多少个流？多少个客户端？每个客户端拉多少个？请描述重现方式，否则无法重现问题。

**Comment by CNRonk** [comment]
路数	带宽 		CPU 	协议	备注
300		90MB/S		7%		RTMP	正常
500		160MB/S		15%		RTMP	正常
1000	320MB/S		40%		RTMP	正常
1500	480MB/S		60%		RTMP	正常
1800				90%		RTMP	声音视频有卡顿




//实际会议室测试(两路视频)
2000	450MB/S		80%		HLS		正常&nbsp; &nbsp;3.0.68版本，内存涨到1.38GB,有内存泄漏。


万兆网卡下测试，命令如下。
./sb_hls_load -c 2000 -r http://172.16.0.163:8080/live/1234.m3u8





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"winlin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月19日(星期天) 下午2:16
收件人:&nbsp;"ossrs/srs"<srs@noreply.github.com&gt;;
抄送:&nbsp;"DataLife"<705648588@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ossrs/srs] SRS3.0.68版本(b4870a6) 可能存在内存泄漏问题。 (#1513)




这是2000个客户端拉一个HLS流吗？多少个流？多少个客户端？每个客户端拉多少个？请描述重现方式，否则无法重现问题。

**Comment by winlinvip** [comment]
试了下3.0.109：

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                  
18491 root      20   0  163948  40544   2996 S  28.2  2.0   0:14.82 ./objs/sb_hls_load -c 2000 -r http://127.0.0.1:8080/live/livestream.m3u8                 
18488 root      20   0  396640  33632   5380 D  30.9  1.6   0:23.22 ./objs/srs -c console.conf 

[root@d9dd774a264b trunk]# dstat -N lo
You did not select any stats, using -cdngy by default.
----total-cpu-usage---- -dsk/total- ---net/lo-- ---paging-- ---system--
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw 
  6  28  60   5   0   1|   0    12k|  43M   43M|   0     0 |  19k   45k
```

没有复现该问题。
