### ISSUE TITLE
./objs/nginx/sbin/nginx：找不到命令

### ISSUE THREAD

**Issue by a57571735** [ossrs/srs#1515]
**描述**

按照 https://github.com/ossrs/srs/wiki/v3_CN_SampleHLS 做到第三步
sudo ./objs/nginx/sbin/nginx
提示 sudo：./objs/nginx/sbin/nginx：找不到命令
输入 ./objs/nginx/sbin/nginx
提示 -bash: ./objs/nginx/sbin/nginx: 没有那个文件或目录
**环境**
1. 操作系统：macos下用vbox装载官网下载的干净的centos6.10，安装的base server
1. 编码器(工具和版本)：```...```
1. 播放器(工具和版本)：```...```
1. SRS版本: ```...```
1. SRS的日志如下:

```
......
```

**重现**
重现Bug的步骤如下：
1. 启动SRS，运行 ```...```
1. 推流，运行 ```...```
1. 播放，运行 ```...```
1. 操作 ```...```
1. 重现了Bug，关键信息如下：

```
...
```

**期望行为**
描述你期望发生的事情。

**Comment by a57571735** [comment]
按照https://github.com/ossrs/srs/wiki/v2_CN_SampleHLS第二步编译后再回到V3文档重新编译，启动nginx后可以成功了，不过没有8080端口，
到第六步使用FFMPEG命令推流报错
./objs/ffmpeg/bin/ffmpeg: 没有那个文件或目录

**Comment by winlinvip** [comment]
重复问题，请在历史issue中搜。
