### ISSUE TITLE
大神路过进来看看，谢谢了，centos7用docker挂载配置文件报错，不挂载配置文件直接运行没问题

### ISSUE THREAD

**Issue by a57571735** [ossrs/srs#1521]
[root@localhost ~]# docker run -p 1935:1935 -p 1985:1985 -p 8080:8080 \
> -v /users/srs/conf/hls.conf:/usr/local/srs/conf/srs.conf \
> ossrs/srs:3
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/users/srs/conf/hls.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/05ed8c93d4561702135d3598007848b6814fea8db46b850d321587c0f0cce4de/merged\\\" at \\\"/var/lib/docker/overlay2/05ed8c93d4561702135d3598007848b6814fea8db46b850d321587c0f0cce4de/merged/usr/local/srs/conf/srs.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
ERRO[0000] error waiting for container: context canceled
[root@localhost ~]#

**Comment by amnotbusy** [comment]
-v /users/srs/conf/hls.conf:/usr/local/srs/conf/srs.conf 
This way, mounting the file will become a directory, so change the file extension.
-v /users/srs/conf/hls.config:/usr/local/srs/conf/srs.conf 
Mounting succeeded.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Why did it become a directory? I remember it seemed like it could be used like this.

`TRANS_BY_GPT3`
