### ISSUE TITLE
SrsAmf0StrictArray可能引起内存泄漏

### ISSUE THREAD

**Issue by alphonsetai** [ossrs/srs#1524]
srs 2.0(2.0 release的分支)

在做阅读理解的时候，发现SrsAmf0StrictArray可能会出现内存泄漏。

即调用了相应的copy函数和clear函数后，就存在内存泄漏。由于copy函数是深拷贝，而clear只是简单的调用了vector的clear并未对相应的内存做清理。

应此应该在SrsAmf0StrictArray内部维护一个深浅拷贝的变量，对做过深拷贝的对象再调用clear时进行自释放

由于代码阅读理解还在初期，并没有梳理出代码中真实的函数调用路径，不小的该内存泄漏是否会触发。

```
SrsAmf0Any* SrsAmf0StrictArray::copy()
{
    SrsAmf0StrictArray* copy = new SrsAmf0StrictArray();
    
    std::vector<SrsAmf0Any*>::iterator it;
    for (it = properties.begin(); it != properties.end(); ++it) {
        SrsAmf0Any* any = *it;
        copy->append(any->copy());
    }
    
    copy->_count = _count;
    return copy;
}

void SrsAmf0StrictArray::clear()
{
    properties.clear();
}
```

**Comment by winlinvip** [comment]
The analysis is excellent, and indeed there will be leaks.

The "strict array" uses a vector, while the "object" uses SrsUnSortedHashtable, and its "clear" function is used for releasing.

```
void SrsUnSortedHashtable::clear()
{
    std::vector<SrsAmf0ObjectPropertyType>::iterator it;
    for (it = properties.begin(); it != properties.end(); ++it) {
        SrsAmf0ObjectPropertyType& elem = *it;
        SrsAmf0Any* any = elem.second;
        srs_freep(any);
    }
    properties.clear();
}
```

So, the "strict array" is actually neglected, and it should be released.

`TRANS_BY_GPT3`
