### ISSUE TITLE
加水印后产生的m3u8 不能正常播放

### ISSUE THREAD

**Issue by fanpiao** [ossrs/srs#1526]
**描述**
我使用srs  transcode 给推上来的rtmp流加了各水印logo
由于配置了hls ，所以会产生 10505_logo.m3u8  10505_logo.m3u8 还有各自的TS片
前面用nginx 配置了 访问产生 hls的这个目录，所以可以用http://192.168.18.212:81/live/10505_logo.m3u8 这样在播放器中播放
现在使用http://chimee.org/ 播放 http://192.168.18.212:81/live/10505_logo.m3u8 老是会出现有声音但是没画面事黑屏的问题，重新点几次播放会偶尔能正常播放
使用未加logo的这个http://192.168.18.212:81/live/10505.m3u8，就不会出现这种情况
**环境**
1. 操作系统：```centos7.6```
1. 编码器(工具和版本)：```...```
1. 播放器(工具和版本)：```...```
1. SRS版本: ```2.0.263```

**Comment by winlinvip** [comment]
信息太少，bug模板不要省略信息。。。

**Comment by fanpiao** [comment]
我好像发现是什么问题了，hls 和 transcode  一起开启时，hls_fragment  时长和gop_size 设置成一样目前就没出现这样的问题了，我也是去仔细在看了介绍hls的 wiki才知道的，谢谢麻烦了
