### ISSUE TITLE
使用docker hls，推流结束后无法播放

### ISSUE THREAD

**Issue by a57571735** [ossrs/srs#1527]
**描述(Description)**

为什么我推流结束后，有m3u8和ts，但是无法播放，
推流地址 rtmp://192.168.124.13/2019/12
配置文件 hls_m3u8_file   [app]/[stream]/vod.m3u8;
hls_ts_file     [app]/[stream]/[seq].ts;
播放地址http://192.168.124.13/2019/12/vod.m3u8
提示不能连接到服务器，但是控制台又能打开，不过视频流(Streams)列表是空的

**环境(Environment)**

SRS版本(Version): `ossrs/srs:3`

**Comment by winlinvip** [comment]
SRS不支持VOD，详细请参考WIKI。
