### ISSUE TITLE
./configure --with-nginx --with-ffmpeg && make 失败

### ISSUE THREAD

**Issue by a57571735** [ossrs/srs#1528]
**描述(Description)**
git clone https://github.com/ossrs/srs
cd srs/trunk
git pull
./configure --with-nginx --with-ffmpeg && make

build x264
Found no assembler
Minimum version is nasm-2.13
If you really want to compile without asm, configure with --disable-asm.
build x264 failed
build ffmpeg-4.1 failed, ret=1

**环境(Environment)**
uname -a
Linux localhost.localdomain 2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
CentOS release 6.10 (Final)

**Comment by amnotbusy** [comment]
Do I need to manually install x264?

`TRANS_BY_GPT3`

**Comment by amnotbusy** [comment]
After installing the latest version of ffmpeg from source code, the compilation of srs was successful.
wget http://www.ffmpeg.org/releases/ffmpeg-4.2.tar.gz
tar -zxvf ffmpeg-4.2.tar.gz
cd ffmpeg-4.2
./configure
make
make install

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed, please use srs-docker.

**Comment by winlinvip** [comment]
See https://github.com/ossrs/srs/issues/1523
