### ISSUE TITLE
推流偶发报错，推流成功率不足50%，推流成功后播放只有最后的几十秒，前面的全部丢失了

### ISSUE THREAD

**Issue by a57571735** [ossrs/srs#1529]
srs console输出的错误
[root@localhost trunk]# ./objs/srs -c conf/myhls.conf
[2019-12-21 23:08:24.116][Trace][8806][0] XCORE-SRS/3.0.76(OuXuli)
[2019-12-21 23:08:24.117][Trace][8806][0] config parse complete
[2019-12-21 23:08:24.117][Trace][8806][0] write log to console
[2019-12-21 23:08:33.551][Error][8809][350][4] serve error code=2003 : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: decode message : decode message : decode command name : String invalid marker=0x44
thread [350]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [350]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [350]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [350]: consume() [src/app/srs_app_recv_thread.cpp:396][errno=11]
thread [350]: handle_publish_message() [src/app/srs_app_rtmp_conn.cpp:993][errno=11]
thread [350]: process_publish_message() [src/app/srs_app_rtmp_conn.cpp:1038][errno=11]
thread [350]: decode_message() [src/protocol/srs_rtmp_stack.cpp:427][errno=11]
thread [350]: do_decode_message() [src/protocol/srs_rtmp_stack.cpp:645][errno=11]
thread [350]: srs_amf0_read_string() [src/protocol/srs_protocol_amf0.cpp:1530][errno=11](Interrupted system call)
[2019-12-21 23:08:34.834][Error][8808][350][4] serve error code=2003 : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: decode message : decode message : decode command name : String invalid marker=0x44
thread [350]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [350]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [350]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [350]: consume() [src/app/srs_app_recv_thread.cpp:396][errno=11]
thread [350]: handle_publish_message() [src/app/srs_app_rtmp_conn.cpp:993][errno=11]
thread [350]: process_publish_message() [src/app/srs_app_rtmp_conn.cpp:1038][errno=11]
thread [350]: decode_message() [src/protocol/srs_rtmp_stack.cpp:427][errno=11]
thread [350]: do_decode_message() [src/protocol/srs_rtmp_stack.cpp:645][errno=11]
thread [350]: srs_amf0_read_string() [src/protocol/srs_protocol_amf0.cpp:1530][errno=11](Interrupted system call)
[2019-12-21 23:08:35.088][Error][8585][350][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 1. cid=22
thread [350]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [350]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [350]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [350]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [350]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [350]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)
[2019-12-21 23:09:32.638][Error][8812][348][4] serve error code=2003 : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: decode message : decode message : decode command name : String invalid marker=0x46
thread [348]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [348]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [348]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [348]: consume() [src/app/srs_app_recv_thread.cpp:396][errno=11]
thread [348]: handle_publish_message() [src/app/srs_app_rtmp_conn.cpp:993][errno=11]
thread [348]: process_publish_message() [src/app/srs_app_rtmp_conn.cpp:1038][errno=11]
thread [348]: decode_message() [src/protocol/srs_rtmp_stack.cpp:427][errno=11]
thread [348]: do_decode_message() [src/protocol/srs_rtmp_stack.cpp:645][errno=11]
thread [348]: srs_amf0_read_string() [src/protocol/srs_protocol_amf0.cpp:1530][errno=11](Interrupted system call)
[2019-12-21 23:09:33.735][Error][8378][348][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 3. cid=53
thread [348]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [348]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [348]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [348]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [348]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [348]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)
[2019-12-21 23:09:38.123][Error][8816][349][4] serve error code=2003 : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: decode message : decode message : decode command name : String invalid marker=0x46
thread [349]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [349]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [349]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [349]: consume() [src/app/srs_app_recv_thread.cpp:396][errno=11]
thread [349]: handle_publish_message() [src/app/srs_app_rtmp_conn.cpp:993][errno=11]
thread [349]: process_publish_message() [src/app/srs_app_rtmp_conn.cpp:1038][errno=11]
thread [349]: decode_message() [src/protocol/srs_rtmp_stack.cpp:427][errno=11]
thread [349]: do_decode_message() [src/protocol/srs_rtmp_stack.cpp:645][errno=11]
thread [349]: srs_amf0_read_string() [src/protocol/srs_protocol_amf0.cpp:1530][errno=11](Interrupted system call)
[2019-12-21 23:09:39.339][Error][8815][349][4] serve error code=2003 : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: decode message : decode message : decode command name : String invalid marker=0x46
thread [349]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [349]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [349]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [349]: consume() [src/app/srs_app_recv_thread.cpp:396][errno=11]
thread [349]: handle_publish_message() [src/app/srs_app_rtmp_conn.cpp:993][errno=11]
thread [349]: process_publish_message() [src/app/srs_app_rtmp_conn.cpp:1038][errno=11]
thread [349]: decode_message() [src/protocol/srs_rtmp_stack.cpp:427][errno=11]
thread [349]: do_decode_message() [src/protocol/srs_rtmp_stack.cpp:645][errno=11]
thread [349]: srs_amf0_read_string() [src/protocol/srs_protocol_amf0.cpp:1530][errno=11](Interrupted system call)
[2019-12-21 23:09:39.497][Error][8378][349][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 3. cid=44
thread [349]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [349]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [349]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [349]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [349]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [349]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)

配置文件
listen              1935;
#chunk_size          60000; 
#ff_log_dir          ./objs/ffmpeglog;
srs_log_tank        console; #console 或者 file
srs_log_level       error;
#srs_log_file        ./objs/srs.log;
max_connections     10000;
daemon              off;
#utc_time            off;
#pithy_print_ms      10000;
#work_dir 			./;
#asprocess 			off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_fragment    10;
        hls_td_ratio    2;
        hls_aof_ratio   2.0;
        hls_window      18600; #5小时
		hls_on_error    continue;
        hls_path        ./objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
        hls_ts_floor    off;
		hls_acodec      aac;
		hls_vcodec      h264;
		hls_cleanup     on;	
		hls_dispose     0;
		#hls_nb_notify   64;
		#hls_wait_keyframe       off;
        #hls_keys        on; 
        #hls_fragments_per_key 5;
		#hls_dts_directly off;
    }
    transcode {
        enabled     on;
        ffmpeg      /usr/local/bin/ffmpeg;
        engine ff {
            enabled         on;
            perfile {
                re;
                rtsp_transport tcp;
            }
            iformat         flv;
            vfilter {
                i               ./doc/ffmpeg-logo.png;
                filter_complex  'overlay=10:10';
            }
            vcodec          libx264;
            vbitrate        1500;
            vfps            25;
            vwidth          768;
            vheight         320;
            vthreads        12;
            vprofile        main;
            vpreset         medium;
            vparams {
                t               100;
                coder           1;
                b_strategy      2;
                bf              3;
                refs            10;
            }
            acodec          libfdk_aac;
            abitrate        70;
            asample_rate    44100;
            achannels       2;
            aparams {
                profile:a   aac_low;
                bsf:a       aac_adtstoasc;
            }
            oformat         flv;
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }
    }
}

centos7，克隆的源代码进行编译运行的

麻烦帮忙看看到底是什么问题

**Comment by a57571735** [comment]
配置文件改成
listen              1935;
#chunk_size          60000; 
#ff_log_dir          ./objs/ffmpeglog;
srs_log_tank        console; #console 或者 file
srs_log_level       error;
#srs_log_file        ./objs/srs.log;
max_connections     10000;
daemon              off;
#utc_time            off;
#pithy_print_ms      10000;
#work_dir 			./;
#asprocess 			off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_fragment    10;
        hls_td_ratio    2;
        hls_aof_ratio   2.0;
        hls_window      18600; #5小时
		hls_on_error    continue;
        hls_path        ./objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
        hls_ts_floor    off;
		hls_acodec      aac;
		hls_vcodec      h264;
		hls_cleanup     on;	
		hls_dispose     0;
		#hls_nb_notify   64;
		#hls_wait_keyframe       off;
        #hls_keys        on; 
        #hls_fragments_per_key 5;
		#hls_dts_directly off;
    }
}

使用命令推流还是报错
ffmpeg -re -i /srs/trunk/doc/test01.mp4 -vcodec copy -acodec copy -f flv -y rtmp://192.168.124.14/live/livestream

错误信息
[2019-12-21 23:43:38.969][Error][9004][350][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 3. cid=19
thread [350]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [350]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [350]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [350]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [350]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [350]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)
[2019-12-21 23:43:40.057][Error][8378][350][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 2. cid=47
thread [350]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [350]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [350]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [350]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [350]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [350]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)

**Comment by a57571735** [comment]
已经使用文档里面最简单的配置了，照样偶尔报错
listen              1935;
max_connections     1000;
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
    }
}

错误信息
[2019-12-21 23:48:11.979][Trace][9006][0] XCORE-SRS/3.0.76(OuXuli)
[2019-12-21 23:48:11.979][Trace][9006][0] config parse complete
[2019-12-21 23:48:11.979][Trace][9006][0] write log to file ./objs/srs.log
[2019-12-21 23:48:11.979][Trace][9006][0] you can: tailf ./objs/srs.log
[2019-12-21 23:48:11.979][Trace][9006][0] @see: https://github.com/ossrs/srs/wiki/v1_CN_SrsLog
[root@localhost trunk]# [2019-12-21 23:48:36.873][Error][9013][352][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 1. cid=52
thread [352]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [352]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [352]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [352]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [352]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [352]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)
[2019-12-21 23:48:38.170][Error][9012][352][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 1. cid=52
thread [352]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [352]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [352]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [352]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [352]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [352]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)
[2019-12-21 23:48:38.233][Error][8585][352][4] serve error code=2001 : service cycle : rtmp: stream service : rtmp: receive thread : recv interlaced message : read message header : chunk is fresh, fmt must be 0, actual is 3. cid=6
thread [352]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]
thread [352]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=4]
thread [352]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:890][errno=11]
thread [352]: recv_message() [src/protocol/srs_rtmp_stack.cpp:384][errno=11]
thread [352]: recv_interlaced_message() [src/protocol/srs_rtmp_stack.cpp:894][errno=11]
thread [352]: read_message_header() [src/protocol/srs_rtmp_stack.cpp:1051][errno=11](Interrupted system call)

**Comment by winlinvip** [comment]
这是你编码器推的RTMP流不规范，错在RTMP解析：

```
serve error code=2001 : service cycle : rtmp: stream service : 
rtmp: receive thread : recv interlaced message : read message header : 
chunk is fresh, fmt must be 0, actual is 3. cid=6
```

请你按照模板说明编码器的详细信息，以及如何重现。
目前提供的信息无法重现。

**Comment by LinGeLin** [comment]
能大概推测RTMP流哪里不规范吗？

**Comment by winlinvip** [comment]
抓个包看看。
