### ISSUE TITLE
SSL or HTTPS in port 8080 for HLS

### ISSUE THREAD

**Issue by h-o-sein** [ossrs/srs#1533]
1. SRS(Version): `3.0`
2. (OS)：`Centos 7`
**(Description)**
Hello,
How can I use SSL in port 8080 for hls?

**Comment by winlinvip** [comment]
Please use nginx or [go-oryx](https://github.com/ossrs/go-oryx/tree/develop/httpx-static) to transmux HTTPS to HTTP.

**Comment by winlinvip** [comment]
Maybe it's convient to support HTTPS by SRS.

**Comment by openmotion** [comment]
> 1. SRS(Version): `3.0`
> 2. (OS): `Centos 7`
>    **(Description)**
>    Hello,
>    How can I use SSL in port 8080 for hls?

hello did you found the solution ?
did you use nginx or go-oryx ?

`TRANS_BY_GPT3`

**Comment by h-o-sein** [comment]
> > 1. SRS(Version): `3.0`
> 
> > 2. (OS): `Centos 7`'

Translated to English:

'> > 2. (OS): `Centos 7`
> 
> >    **(Description)**
> 
> >    Hello,
> 
> >    How can I use SSL in port 8080 for hls?
> 
> 
> 
> hello did you found the solution ?
> 
> did you use nginx or go-oryx ?
> 
> 


Hi
Yes, I installed Direct Admin and then set it to Apache and put the streaming storage in one of the public folders and Active SSL From Direct Admin in my WebSite.

`TRANS_BY_GPT3`

**Comment by h-o-sein** [comment]
Of course, you can also use things like nginx and do the same.

**Comment by lgjluis** [comment]
Hello, I'm new at this. I am using 4.0.26 version. How can I install Go-Oryx to be able to play streaming via https?

**Comment by winlinvip** [comment]
Dup to #1657

**Comment by winlinvip** [comment]
Fixed in https://github.com/ossrs/srs/issues/1657#issuecomment-722971676
