### ISSUE TITLE
srs_get_peer_ip  获取客户端的地址

### ISSUE THREAD

**Issue by zxl8121** [ossrs/srs#1543]
**描述(Description)**

描述你遇到了什么问题。
on_play 里面的ip 为本机ip，而不是客户端播放器的IP

**环境(Environment)**

1. SRS版本(Version): `srs3.0`
1. 操作系统(OS)：`centos7`

解决思路：
getsockname  修改为 getpeername

**Comment by waiter89** [comment]
I also encountered the same problem. After using getpeername, it returns 0.0.0.0. How can I solve this? The system I am using is openSUSE.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Originally it was getpeername, later changed to getsockname: [link](https://github.com/ossrs/srs/pull/988/files#diff-8bbad68462c97e3e7a61786a559e47fdR1169)

I checked the manual and confirmed that getpeername should indeed be used.

```
int getpeername(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);
The getpeername() function returns the address of the peer connected to the specified socket.

int getsockname(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);
The getsockname() function returns the current address for the specified socket.
```

`TRANS_BY_GPT3`
