### ISSUE TITLE
SRS 3.0.85转码后无法forward原始流 

### ISSUE THREAD

**Issue by Osmond1689** [ossrs/srs#1546]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
SRS 3.0.85转码后无法forward原始流 
1. SRS版本(Version): `3.0.85`
1. SRS的日志如下(Log):
```
日志正常
```

**重现(Replay)**

按以下配置，即可重现

vhost __defaultVhost__ {
         transcode{
		 enabled on;
		 ffmpeg  /bin/ffmpeg;
		 engine v2{
		 vcodec{}
		 acodec{}
		 output              rtmp://127.0.0.1/[port]/[app]?vhost=[vhost]/[stream]_[engine]}
}
}
	forward cdn推流地址;
}

原始流无法forward到CDN，2.0版本可以forward到CDN

**Comment by winlinvip** [comment]
vhost放后面试试。
