### ISSUE TITLE
最新的SRS3不支持ARM交叉编译?

### ISSUE THREAD

**Issue by bigbao9494** [ossrs/srs#1547]
最新的SRS3不支持ARM交叉编译?
./configure --arm 编译时会提示：
We don't support crossbuild for ARM/MIPS, please directly build it on ARM/MIPS server.

**Comment by winlinvip** [comment]
Yes, I plan to stop supporting cross-compilation. I recommend compiling directly on an ARM server.

`TRANS_BY_GPT3`

**Comment by bigbao9494** [comment]
Which version of 3.0 can still be cross-compiled for ARM?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The call for support is so strong... I am considering if it would be better to show my support. I need to take another look at how many people are in need...

`TRANS_BY_GPT3`

**Comment by bigbao9494** [comment]
Still support it, many people may use it in an embedded environment.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Friend, currently it's just you, hahaha.

`TRANS_BY_GPT3`

**Comment by liuguang** [comment]
2个，哈哈。' translates to '2, haha.

`TRANS_BY_GPT3`

**Comment by liuguang** [comment]
> Which version of 3.0 can still support ARM cross-compilation?

`bb3e8a41d13fa8dc87065c2adcf4d6f438b37e95` is the commit when cross-compilation was supported.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The previous cross-compilation was not done well, I will see how to support it better.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
You can choose to pick this commit and disable cross-compilation directly: [commit link](https://github.com/ossrs/srs/commit/dffc96d2febe2929420f4e13b2247a88c4f7800f)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
从这个comment(https://github.com/ossrs/srs/issues/1168#issuecomment-404376674)看，除了设置tookchain，可能CFlags也需要设置，需要开放多个选项，不仅仅是开启crossbuild就可以了。

参考FFMPEG的选项：

```
Mac:ffmpeg chengli.ycl$ ./configure -h
  --ar=AR                  use archive tool AR [ar]
  --cc=CC                  use C compiler CC [gcc]
  --cxx=CXX                use C compiler CXX [g++]
  --ld=LD                  use linker LD []
  --extra-cflags=ECFLAGS   add ECFLAGS to CFLAGS []
  --extra-cxxflags=ECFLAGS add ECFLAGS to CXXFLAGS []
```

> 可能OpenSSL在交叉编译时也需要一些额外的Flags(https://github.com/ossrs/srs/issues/1168#issuecomment-404376674)，但也可以用`--use-sys-ssl`使用系统的已经编译好的ssl库。

**Comment by winlinvip** [comment]
# UBUNTU

使用docker，Ubuntu 16(xenial)：

```
docker pull registry.cn-hangzhou.aliyuncs.com/ossrs/srs:ubuntu16
```

> 推荐使用阿里云的容器，下载的速度比较快，也可以使用docker官方容器：`docker pull ossrs/srs:ubuntu16`

启动容器，主目录为SRS：

```
cd ~/git && docker run -it -v `pwd`:/tmp/git -w /tmp/git/srs/trunk \
    registry.cn-hangzhou.aliyuncs.com/ossrs/srs:ubuntu16 bash
```

安装toolchain：https://www.acmesystems.it/arm9_toolchain

```
apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
```

交叉编译SRS：

```
./configure --arm --cc=arm-linux-gnueabi-gcc \
    --cxx=arm-linux-gnueabi-g++ --ar=arm-linux-gnueabi-ar
```

**Comment by winlinvip** [comment]
Wiki: 

https://github.com/ossrs/srs/wiki/v3_CN_SrsLinuxArm#ubuntu-cross-build-srs

https://github.com/ossrs/srs/wiki/v3_EN_SrsLinuxArm#ubuntu-cross-build-srs

**Comment by duduathz** [comment]
Strongly appeal for support for cross-compiling. Currently, the capabilities of embedded ARM are becoming stronger and stronger. Thank you!

`TRANS_BY_GPT3`

**Comment by docterling** [comment]
I compiled using Hisilicon's arm-hisiv300-linux, but I keep getting a segmentation fault when running it. GDB's backtrace points to strnlen, I wonder if anyone else has encountered the same issue.

`TRANS_BY_GPT3`

**Comment by XJTU-ZSY** [comment]
Can you also support MIPS?

`TRANS_BY_GPT3`
