### ISSUE TITLE
srs2.0边缘不去拉源站的流

### ISSUE THREAD

**Issue by PhoenixGx** [ossrs/srs#1550]
1.srs源站配置
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;

http_server {
enabled             on;
listen              8080;
dir                 ./objs/nginx/html;
}

stats {
        network         0;
        disk            sda sdb xvda xvdb;
}

http_api {
        enabled         on;
        listen          1985;
        crossdomain     on;
}

vhost __defaultVhost__ {

dvr {
               enabled         on;
               dvr_plan        session;
               time_jitter     full;
               dvr_path        ./objs/nginx/html/[app]/[stream]/[2006]/[01]/[02]/[15].[04].[05].[999].flv;
    }

transcode {
        enabled         on;
        ffmpeg          /usr/local/ffmpeg-3.4.6/ffmpeg;
        engine  ff{
                enabled on;
                vfilter {
                }
                vcodec          libx264;
                vprofile        baseline;
                vpreset         superfast;
                acodec          libfdk_aac;
                abitrate        45;
                asample_rate    44100;
                achannels       2;
                aparams {
                }
                output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }

    }
http_hooks {
        enabled         on;
        on_connect      http://192.168.3.198:8180/vaildToken;
        on_publish      http://192.168.3.198:8180/publish;
        on_dvr          http://192.168.3.198:8180/dvrs;
}

2.边缘srs配置
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_server {
        enabled         on;
        listen          8080;
        dir             ./objs/nginx/html;
    }

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_fragment    10;
        hls_window      60;
        hls_path        ./objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
    }

    mode                remote;
    origin              192.168.3.198:1935;
    token_traverse      on;
}
3. SRS版本(Version): 2.0.268
1. 边缘SRS的日志如下(Log):
[2020-01-02 11:18:26.937][trace][101737][112] HTTP client ip=192.168.3.142
[2020-01-02 11:18:26.937][trace][101737][112] HTTP GET http://192.168.3.164:8080/live/myStream_ff.m3u8, content-length=-1
[2020-01-02 11:18:26.937][warn][101737][112][2] http miss file=./objs/nginx/html/live/myStream_ff.m3u8, pattern=/, upath=/live/myStream_ff.m3u8
[2020-01-02 11:18:26.939][warn][101737][112][104] client disconnect peer. ret=1004

**期望行为(Expect)**
边缘去源站进行拉流

是有什么功能在源站开启后就不能拉流了吗？

**Comment by RocFang** [comment]
1. HLS should be placed on the origin server.
2. Edge HLS playback does not actively trigger origin pulling for streaming, only RTMP and HTTP-FLV do. If it is necessary to trigger origin pulling through HLS playback, it can be done externally.

`TRANS_BY_GPT3`

**Comment by PhoenixGx** [comment]
> 1. HLS should be placed on the origin server.
> 2. Edge HLS playback does not actively trigger origin pulling for streaming, only RTMP and HTTP-FLV do. If you must trigger pulling through HLS playback, you can do it externally.

The problem was solved by slicing HLS on another vhost on the origin server. Thank you for your help.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@RocFang 👍 Correct answer.

`TRANS_BY_GPT3`

**Comment by free-wind-0** [comment]
@PhoenixGx I don't quite understand. After slicing at the source station, can users trigger edge proactive origin retrieval by playing HLS from the edge?

`TRANS_BY_GPT3`
