### ISSUE TITLE
rtmp流有暂停时，流切片不精确

### ISSUE THREAD

**Issue by fastfading** [ossrs/srs#1563]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `srs 2.0`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

当rtmp 中间有暂停的时候srs 会发生以上一种情况
如图  39s 时 rtmp 暂停， 47s恢复(这时可能audio 先到)
srs 在47s产生切片  1.ts  ,   后面切面2.ts
期待结果 1.ts 包含 0-39s的av 数据
实际结果 1.ts 包含 0-39s的av 数据 和 1个pack 的audio 数据（pts=47）
这样会导致1.ts  ffprobe 检测出时长为47秒， 最后录制的数据中间也会包含暂停的这部分。
请问如何使其精确切片？
![image](https://user-images.githubusercontent.com/8351732/71863809-02514980-3139-11ea-8c2b-d516f4794c6e.png)

我们srs 不希望有pure audio 切片所以做了如下注释。  不知这个可影响
<img width="987" alt="image" src="https://user-images.githubusercontent.com/8351732/71863815-08472a80-3139-11ea-8b60-4c4209fce8ca.png">

**Comment by fastfading** [comment]
Another case
Due to business requirements, there will be a pause in the data flow for a period of time. When the pause is resumed, it exceeds the slice time, but SRS did not truncate it.
<img width="498" alt="image" src="https://user-images.githubusercontent.com/8351732/81245944-e4ddaf00-9048-11ea-848f-abd3fef865fb.png">

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Won't fix.

**Comment by winlinvip** [comment]
There are not many paused scenes, so fixing is not currently being considered.

`TRANS_BY_GPT3`
