### ISSUE TITLE
普通用户权限运行srs会生成root权限的文件夹导致写ts文件失败 

### ISSUE THREAD

**Issue by breezeewu** [ossrs/srs#1564]
在centos中以普通用户的权限运行srs，刚开始推流能正常生成ts文件，过一段时间后改用新路径推流，产生的目录变成了root权限的目录，导致ts文件写入失败。如下图所示，图1中P020101000101191216300001-4为刚启动时创建的文件夹，权限所有者为centos，srs可以写入。
P020101000101191216300005-20为后面推流创建的文件夹，权限所有者为root。运行过程中程序没有重启过，以centos的权限运行。
图1：
![image](https://user-images.githubusercontent.com/16345166/71868081-a9d57880-3147-11ea-89d2-23cd81fd9790.png)
图2：
![image](https://user-images.githubusercontent.com/16345166/71868025-75fa5300-3147-11ea-971b-f252ce209fb1.png)
图2为srs在P020101000101191216300008中写ts文件失败的日志，错误提示为权限不够。
我很好奇，srs在centos用户权限下启动为什么会生成root权限目录，是不是srs中有用户权限切换的代码导致的？

**Comment by winlinvip** [comment]
SRS does not have the logic to switch users.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
When starting, you can specify the user to run SRS, please refer to the Linux command for details.

`TRANS_BY_GPT3`
