### ISSUE TITLE
多线程SRS

### ISSUE THREAD

**Issue by bigbao9494** [ossrs/srs#1565]
我自己做了一个跨平台的协程库（主要是WINDDOWS和LINUX），IO接口兼容ST，如果用它来把SRS改成多线程的是否可行，因为SRS设计之初只考虑了单线程，业务逻辑上数据流动是无锁设计，但是多线程后SRS的各协程会运行在不同线程上，这样原来的无锁设计是否需要做大量修改？可能改成CO_MUTX或CHANNEL

**Comment by winlinvip** [comment]
你做的协程库不是开源的？如果开源出来，SRS可以用的哇，当然你如果不开源我会自己写，ST有LICENSE问题，不利于在国外推SRS。

关于多线程问题，SRS倾向于用多进程+REUSEPORT+Edge/OriginCluster解决问题，简单可靠，能避免多线程锁同步的问题和竞争条件的问题，还能保持高效。

**Comment by lam2003** [comment]
好像有个叫libgo的cpp协程库，基本上hook所有会阻塞的system call，支持多线程调度，金山貌似在用。c++20也马上要在语言层面支持协程了吧

**Comment by bigbao9494** [comment]
> 你做的协程库不是开源的？如果开源出来，SRS可以用的哇，当然你如果不开源我会自己写，ST有LICENSE问题，不利于在国外推SRS。
> 
> 关于多线程问题，SRS倾向于用多进程+REUSEPORT+Edge/OriginCluster解决问题，简单可靠，能避免多线程锁同步的问题和竞争条件的问题，还能保持高效。

@winlinvip 因为这是业余爱好花的时间不多，还有一些东西没有弄完整所以还没有开源（主要是没有做CMAKE的编译，自己是用IDE直接建的不同平台工程来开发的），后面把这些和文档补充完整后放到GITHUB上来

**Comment by bigbao9494** [comment]
> 好像有个叫libgo的cpp协程库，基本上hook所有会阻塞的system call，支持多线程调度，金山貌似在用。c++20也马上要在语言层面支持协程了吧

libgo很好，从libgo学习到了很多东西部分东西也直接参考libgo（感谢libgo），如果深入研究后你会知道它真正适合的场景，它的设计就是为了hook_socket操作来把同步IO变成异步，在异步IO的工程中能够直接使用其它同步库，因为hook_socket做转换这个操作是非常复杂的（场景和情况非常多）所以即使实现了也会牺牲其它东西的，比如设计上复杂导致性能的不足。正因为如此我才自己做了一个我认为的“真正高效多线程协程网络库”

**Comment by runner365** [comment]
libgo确实挺好，但是针对流媒体，觉得成立说的单线程多进程的模式做合适；
1.主要开发容易不容易出错，不用多map，list等加锁；
2.没有资源锁，同步操作少，效率也高了；
前些年跟过一个golang写的rtmp流媒体服务，后面开发中发现很多资源都需要考虑同步/互斥的问题，都要解决安全性，和效率问题。
