### ISSUE TITLE
使用srs-bench推送大码流文件，srs性能较差

### ISSUE THREAD

**Issue by phubfer** [ossrs/srs#1567]
环境：
--
1.srs版本:3.0.90 (运行在容器中)
2.操作系统: Ubuntu 16.04.6 LTS   
3.cpu信息:Intel(R) Xeon(R) CPU E5-2603 v4 @ 1.70GHz
3.压测工具:srs-bench

描述：
--
我在对单个srs源站进行压力测试时，发现推送8Mbps文件，srs承载能力较差
推流命令为：./objs/sb_rtmp_publish -i 8M.flv -c 55 -r rtmp://127.0.0.1:1935/live/livestream_{i}

srs信息：来自srs-api
SRS/3.0.90
运行 | 2天 19:12:27
CPU | 94.00% / 600.00%
内存 | 2% 624MB / 31GB
网络 | 56 / 408Mbps / 5Kbps

同时我对2Mbps文件和4Mbps文件也进行了测试
从本地文件推送 2000路2Mbps 视频流，cpu使用率达到约 96%（单个srs源站）
从本地文件推送 1250路4Mbps 视频流，cpu使用率达到约 93%（单个srs源站）

想知道为何8Mbps文件与4M和2M的测试结果差距这么大

**Comment by alphonsetai** [comment]
http://myblog.emhct.net.cn/index.php/archives/2094

这个问题原因是多个。我是通过开多个srs-bench来解决的

**Comment by winlinvip** [comment]
高码率流，需要专门优化。
