### ISSUE TITLE
开启atc之后，拉流有问题

### ISSUE THREAD

**Issue by rozen3** [ossrs/srs#1569]
为了使各个srs边缘切出来的ts保持一致，我尝试开启了atc。会出现以下异常。关闭atc则正常。
1、vlc播放会出现画面，但是会卡好半天，然后才开始正常播放。是必现的，请问这个是正常的吗
2、如果推流的音频格式为mp3，则有概率出现ffmpeg拉流失败。 并且无论是否成功，都会报错：
报错来自这个函数 avformat_find_stream_info(ifmt_ctx, NULL);

 Could not find codec parameters for stream 2 (Audio: aac, 44100 Hz, stereo, 128 kb/s): unspecified sample format
Consider increasing the value for the 'analyzeduration' and 'probesize' options

1. SRS版本(Version): 2和3都试过了
1. SRS的日志如下(Log): 推拉流都没有报错

**Comment by winlinvip** [comment]
Check it.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS 4.0
