### ISSUE TITLE
srs2.0 录像怎么配置？

### ISSUE THREAD

**Issue by itolskspv** [ossrs/srs#1571]
srs2.0 录像怎么配置？

srs.conf文件配置如下：

vhost __defaultVhost__ {
	dvr {
        enabled             on;
        dvr_path            ./objs/nginx/html/[app]/[stream]/[2006]/[01]/[02]/[15].[04].[05].[999].flv;
        dvr_plan            session;
        dvr_duration        30;
        dvr_wait_keyframe   on;
    }
	http_remux {
		enabled     on;
		mount [vhost]/[app]/[stream].flv;
		hstrs	on;
	}
	
	http_hooks {
        enabled         on;
        on_dvr          http://127.0.0.1:8085/api/v1/dvrs;
    }
}

编译：
./configure --with-dvr && make

./objs/srs -c conf/srs.conf

没有产生flv 文件，请教各位大神，望指点！谢谢

**Comment by winlinvip** [comment]
Invalid issue.
