### ISSUE TITLE
CID为负数，无法断开rtmp推流

### ISSUE THREAD

**Issue by batdkuwlh** [ossrs/srs#1573]
get http://localhost:1985/api/v1/streams
结果：{"code":0,"server":49635,"streams":[{"id":49640,"name":"livestream","vhost":49636,"app":"HDxzzKjQGWT0TYKc9jsgiJNBhg41gzXuUVOtoR62yU0rl4pavDHwMQAGYhixSIJRajUBWaffDx3MDGq9wN8QQEtN19GCpUHjRSWrznSn4GPk5cm64jte6kNT8b4Ia0Zo/live","live_ms":1578883698442,"clients":1,"frames":25177,"send_bytes":3984,"recv_bytes":147834247,"kbps":{"recv_30s":1073,"send_30s":0},"publish":{"active":true,"cid":-38},"video":{"codec":"H264","profile":"High","level":"3.1","width":1296,"height":512},"audio":{"codec":"AAC","sample_rate":44100,"channel":2,"profile":"LC"}}]}

delete http://localhost:1985/api/v1/clients/-38
结果：{"code":2049}
单台电脑上测试

**Comment by LeafHCode** [comment]
If cid is negative, it seems that there is no way to disconnect. Do you have a solution to this problem?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Check it.

**Comment by winlinvip** [comment]
Fixed, after 4.0, CID is a string.

`TRANS_BY_GPT3`
