### ISSUE TITLE
DVR: 按需录制，动态录制，根据条件进行录制和切片

### ISSUE THREAD

**Issue by springjk** [ossrs/srs#1577]
**需求场景：**

用户推流上来后后转码成多种分辨率，只需要对指定的一种分辨率或几种分辨率进行录制和切片，比如超高清的分辨率并不需要切片，低分辨率的也不需要录制，只要录制一个高分辨率或者只转码编码的流，目前如果是直接在 origin 中进行录制和切片就会按照转码相关的配置完整的录制和切片所有分辨率，不符合需求，而如果 forward 出去到另一台机器，那这个 forward 出去的也是完整的所有分辨率的流，没有找到单独 forward 某种分辨率的流，即 forward 无法在 transcode 的 engine 作用域下工作的方式。

目前我有一个粗暴的办法：多转一路，输出到其他专门只开启录制的 srs 中去，这样只会录制到我想要的分辨率，切片同理。

```
    transcode {
        enabled     on;
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;


        engine 720p {
            enabled         on;
            vfilter {
                v           quiet;
            }
            vcodec          libx264;
            vbitrate        2000;
            vfps            25;
            vwidth          1280;
            vheight         720;
            vthreads        12;
            vprofile        main;
            vpreset         ultrafast;
            vparams {
            }
            acodec          libfdk_aac;
            aparams {
            }
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }

        engine 720p_dvr {
            enabled         on;
            vfilter {
                v           quiet;
            }
            vcodec          libx264;
            vbitrate        2000;
            vfps            25;
            vwidth          1280;
            vheight         720;
            vthreads        12;
            vprofile        main;
            vpreset         ultrafast;
            vparams {
            }
            acodec          libfdk_aac;
            aparams {
            }
            output          rtmp://10.16.0.4:1937/[app]?vhost=[vhost]/[stream]_[engine];
        }
    }
```

这样的方式应该是重复浪费 CPU 去多切一份，而且在集群中不知道还会不会造成影响，不知道正确的姿势应该是什么样的。

**期望：**

* 录制和切片能够配置成对指定的 engine 开启
* forward 能够转发指定的 engine 流
* 录制或切片有相关的 callback api 去由业务端来返回开启关闭哪个，但这样可能会导致 srs 变成有状态的了

以上实现一种就可以实现需求了，如果是现在尚不支持，要看看有什么样的方案去实现更好，或者说是否现在已经有方法可以实现只是我没理解到希望有人指出。

**Comment by springjk** [comment]
Continued to try 2 methods, ingest and publish stream event exec, with the following results: 

ingest

```
ingest {
        enabled      on;
        input {
            type    stream;

            url     rtmp://127.0.0.1/streams/123_720p;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          on;
            output          rtmp://10.16.0.4:1937/[streams/123_720p;
        }
}
```

This method pulls the specified 720p stream and pushes it to record SRS, which is feasible, but it cannot dynamically configure or insert parameters to support all streams. Each stream needs to be configured separately, which is not feasible.


exec

```

exec {

        enabled     on;

        publish     ./objs/ffmpeg/bin/ffmpeg -f flv -i rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_720p -c copy -f flv rtmp://10.16.0.4:1937/[app]?vhost=[vhost]/[stream]_720p;
}
```

This method pulls the 720p stream of each stream and pushes it to record SRS, which is feasible. However, in the source station cluster mode, there may be error reports but the push is normal. The error message is as follows:

```
srs_1  | [2020-01-15 18:44:19.573][Trace][1][231] connected stream, tcUrl=rtmp://127.0.0.1:1935/streams?vhost=__defaultVhost__, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=1935, app=streams, stream=123_720p_720p, param=, args=null
srs_1  | [2020-01-15 18:44:19.574][Trace][1][231] source url=/streams/123_720p_720p, ip=127.0.0.1, cache=1, is_edge=0, source_id=-1[-1]
srs_1  | [2020-01-15 18:44:19.574][Trace][1][232] ignore AMF0/AMF3 command message.
srs_1  | [2020-01-15 18:44:19.574][Trace][1][232] client identified, type=Play, vhost=__defaultVhost__, app=streams, stream=123_1080p_720p, param=, duration=-1ms
srs_1  | [2020-01-15 18:44:19.574][Trace][1][232] connected stream, tcUrl=rtmp://127.0.0.1:1935/streams?vhost=__defaultVhost__, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=1935, app=streams, stream=123_1080p_720p, param=, args=null
srs_1  | [2020-01-15 18:44:19.575][Trace][1][232] source url=/streams/123_1080p_720p, ip=127.0.0.1, cache=1, is_edge=0, source_id=-1[-1]
srs_1  | [2020-01-15 18:44:19.575][Error][1][231][115] serve error code=3090 : service cycle : rtmp: stream service : discover coworkers, url=http://10.16.0.4:1936/api/v1/clusters?vhost=__defaultVhost__&ip=127.0.0.1&app=streams&stream=123_720p_720p&coworker=10.16.0.4:1936 : parse data {"code":0,"data":{"query":{"ip":"127.0.0.1","vhost":"__defaultVhost__","app":"streams","stream":"123_720p_720p"},"origin":null}}
srs_1  | thread [1][231]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=115]
srs_1  | thread [1][231]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=115]
srs_1  | thread [1][231]: playing() [src/app/srs_app_rtmp_conn.cpp:622][errno=115]
srs_1  | thread [1][231]: discover_co_workers() [src/app/srs_app_http_hooks.cpp:453][errno=115](Operation now in progress)
srs_1  | rtmp://127.0.0.1:1935/streams?vhost=__defaultVhost__/123_720p_720p: Input/output error
srs_1  | [2020-01-15 18:44:19.576][Error][1][232][11] serve error code=3090 : service cycle : rtmp: stream service : discover coworkers, url=http://10.16.0.4:1936/api/v1/clusters?vhost=__defaultVhost__&ip=127.0.0.1&app=streams&stream=123_1080p_720p&coworker=10.16.0.4:1936 : parse data {"code":0,"data":{"query":{"ip":"127.0.0.1","vhost":"__defaultVhost__","app":"streams","stream":"123_1080p_720p"},"origin":null}}
srs_1  | thread [1][232]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=11]
srs_1  | thread [1][232]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:400][errno=11]
srs_1  | thread [1][232]: playing() [src/app/srs_app_rtmp_conn.cpp:622][errno=11]
srs_1  | thread [1][232]: discover_co_workers() [src/app/srs_app_http_hooks.cpp:453][errno=11](Resource temporarily unavailable)
srs_1  | rtmp://127.0.0.1:1935/streams?vhost=__defaultVhost__/123_1080p_720p: Input/output error
```

Method 2 seems to be feasible, but it needs improvement. Can the errors caused by inter-cluster communication be avoided?

The above test was conducted on docker 3.0-a8, pushing the /streams/123 stream and transcoding it to 1080p and 720p.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dynamic recording: Decide whether to record based on callbacks, and it is more appropriate to pass the parameters of the stream.

`TRANS_BY_GPT3`

**Comment by ghostsf** [comment]
> Dynamic recording: Decide whether to record based on callbacks, and pass the parameters of the stream, which is more appropriate.

What does this mean? Custom recording of pulling streams based on the stream on_publish callback?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
按需DVR，和按需Forward非常像，都是按需对流的处理的hook，方案可以看 https://github.com/ossrs/srs/issues/1342#issuecomment-997851990

**Comment by winlinvip** [comment]
Please refer to [FAQ](https://github.com/ossrs/srs/issues/2716#http-api) for more information.

* `Dynamic DVR`: Regarding dynamic recording, regular expression matching is used to determine which streams need to be recorded.
  > 1. You can use `on_publish` to callback the business system, and let the business system handle the rules.
  > 2. The actual recording files can be handled using `on_hls`, by copying the segments to the recording directory or cloud storage.
  > 3. You can refer to the implementation of DVR in [srs-cloud](https://github.com/ossrs/srs-cloud/tree/main/hooks).

Please make sure to maintain the markdown structure.

On-demand DVR, similar to on-demand Forward, is a hook that handles streams on-demand. You can refer to the solution at https://github.com/ossrs/srs/issues/1342#issuecomment-997851990. If you are willing to implement it yourself, you can also use a similar approach.

Please make sure to maintain the markdown structure.

However, the complexity of DVR compared to Forward lies in the fact that Forward is stateless, while DVR involves issues such as stream re-publishing and concatenation.

Please make sure to maintain the markdown structure.

Therefore, considering these factors, it is better to implement it with callbacks in conjunction with the business system, and SRS is not suitable for support.

Please make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
