### ISSUE TITLE
How to get SSL with Live HTTPS FLV Stream?

### ISSUE THREAD

**Issue by dylanno** [ossrs/srs#1586]
Apologies if this isnt the place. But im using Apache as my webserver and Viblast html5 player on there linked to SRS to try to play FLV live streams.
Its not working i think because SSL is not setup on SRS, and im not sure how to for this application. Will i have to use HLS?

Thanks

**Comment by winlinvip** [comment]
Please use nginx or [go-oryx](https://github.com/ossrs/go-oryx/tree/develop/httpx-static) to transmux HTTPS to HTTP.

_Originally posted by @winlinvip in https://github.com/ossrs/srs/issues/1533#issuecomment-571983649_
