### ISSUE TITLE
经过反复测试ossrs 2.0-r7 

### ISSUE THREAD

**Issue by molele2** [ossrs/srs#1589]
r8测试可以使用了，r7有问题

**Comment by molele2** [comment]
还好这项目一直没敢在正式项目中使用过，我也就是测试一下，结果证明没法用

**Comment by molele2** [comment]
大家好，刚测试了r8发现该问题已经不存在，不晓得是否是bug，反正默认配置起码用google的exoplayer可以正常流畅播放，后续会一直关注，后面试一下rtmp-rtsp-stream-client-java看能否正常连接

**Comment by winlinvip** [comment]
有问题就把问题说清楚，提issue现在有模板，请按模板描述问题是什么。
