### ISSUE TITLE
HLS is not working if publishing software is adobe meadia encode. Always reproducible

### ISSUE THREAD

**Issue by venkat0708** [ossrs/srs#1609]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
When the publish software is OBS studio both rtmp and hls plays are working fine, but when the publish software is adobe media encoder rtmp play is working but hls play is not working.
when i was using srs 2.0 adobe media encoder had no problem with hls play.

for srs2.0 i was using ubuntu 16
for srs3.0 i am using ubuntu 18

Can anyone please help me with this. Or shall I use srs 2.0 instead of srs 3.0 to support both adobe media encoder and obs studio 
1. SRS版本(Version): SRS/3.0.116
1. SRS的日志如下(Log):

uploading srs.log file
1. SRS的配置如下(Config):
uploading myconf.txt

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. OS is ubuntu 18
2.SRS version is SRS/3.0.116
3. publish with adobe media encoder

**期望行为(Expect)**
In SRS players rtmp can be played but hls play is not working
> 描述你期望发生的事情(Please describe your expectation)
It should work for adobe media encoder also
[srs.log](https://github.com/ossrs/srs/files/4208691/srs.log)
[srs.log](https://github.com/ossrs/srs/files/4208692/srs.log)
[myconf.txt](https://github.com/ossrs/srs/files/4208693/myconf.txt)

**Comment by victorfu** [comment]
Make sure the video format is H.264!
![image](https://user-images.githubusercontent.com/5513224/74622941-a3daaa80-517d-11ea-915b-27b5202bb1e9.png)

I use the same environment on ubuntu 18.04 and adobe media encoder. HLS works like a charm.

**Comment by venkat0708** [comment]
even my Format is H.264,  srs 2 it is working but on srs 3 it's not. for a second video comes and later there won't be any video or audio

**Comment by venkat0708** [comment]
SRS/3.0.97
in hls player the following error is shown repeatedly
Parsing error:no ADTS header found in AAC PES

where as in SRS/2.0.263
I didn't get any such error in hls player.

This is always reproducible

**Comment by venkat0708** [comment]
It is not working from v3.0-a0. Please check this once.
On the HLS player provided in console(https://hls-js.netlify.com/demo/) I checked and I was getting the following error:
Parsing error:no ADTS header found in AAC PES

only when publishing from Adobe Flash Media Live Ecoder.
I didn't get the same error when I tried with Obs Studio

**Comment by winlinvip** [comment]
Can't replay it @venkat0708 

![image](https://user-images.githubusercontent.com/2777660/77227141-f6621900-6bb8-11ea-8e20-925b9ed04a0f.png)

Or by OBS:

![image](https://user-images.githubusercontent.com/2777660/77227209-7b4d3280-6bb9-11ea-8f15-6d3ad161c12a.png)
