### ISSUE TITLE
./configure报错：engines/afalg/e_afalg.c:110:20: error: '__NR_eventfd' undeclared (first use in this function); did you mean '__NR_eventfd2'?

### ISSUE THREAD

**Issue by wuzhidefeng** [ossrs/srs#1616]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `3.0-release`
2。执行报错如下：
![image](https://user-images.githubusercontent.com/39819358/75145547-17f3f000-5734-11ea-8f66-4f531eadafe2.png)

engines/afalg/e_afalg.c:110:20: error: '__NR_eventfd' undeclared (first use in this function); did you mean '__NR_eventfd2'?
return syscall(__NR_eventfd, n);

**Comment by zhangscth** [comment]
修改openssl的编译脚本auto/depends.sh，增加 no-afalgeng 编译选项， ${OPENSSL_CONFIG} no-afalgeng  --prefix=`pwd`/_release $OPENSSL_OPTIONS
