### ISSUE TITLE
http://localhost:8080/live/h265.m3u8 返回Not found

### ISSUE THREAD

**Issue by JWenBin** [ossrs/srs#1623]
按readme和https://www.cnblogs.com/harlanc/p/8711449.html的步骤执行后，火狐浏览器http://localhost:8080/live/h265.m3u8 返回Not found

注：我的是mp3，对应修改了命令：ffmpeg -re  -i /home/wenbin/test.mp3 -c copy -f mp3 rtmp://localhost:1935/live/h265

**Comment by JWenBin** [comment]
wenbin@wenbin:~/srs-3.0release/trunk$ ffmpeg -re  -i /home/wenbin/test.mp3 -c copy -f mp3 rtmp://localhost:1935/live/h265
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[mp3 @ 0x23bc340] Skipping 0 bytes of junk at 462.
Input #0, mp3, from '/home/wenbin/test.mp3':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: 00:03:46.22, start: 0.025057, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 128 kb/s
    Metadata:
      encoder         : Lavc56.60
Output #0, mp3, to 'rtmp://localhost:1935/live/h265':
  Metadata:
    TSSE            : Lavf56.40.101
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, 128 kb/s
    Metadata:
      encoder         : Lavc56.60
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=    3535kB time=00:03:46.19 bitrate= 128.0kbits/s    
video:0kB audio:3535kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000608%
wenbin@wenbin:~/srs-3.0release/trunk$

**Comment by JWenBin** [comment]
实际上我测MP4文件的时候报错了，摘了几行重要的下来：
......
[flv @ 0xdcacc0] Codec for stream 0 does not use global headers but container format requires global headers
[flv @ 0xdcacc0] Codec for stream 1 does not use global headers but container format requires global headers
......
[flv @ 0xdcacc0] Failed to update header with correct duration.
[flv @ 0xdcacc0] Failed to update header with correct filesize.
frame= 4809 fps= 24 q=-1.0 Lsize=   27129kB time=00:03:20.59 bitrate=1107.9kbits/s    
video:23815kB audio:3076kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.884422%

**Comment by JWenBin** [comment]
GitHub上写的是：./objs/srs -c conf/srs.conf
那个博客写的是：./objs/srs -c conf/hls.conf
ε=(´ο｀*)))唉
似乎只生成了一个文件：hls_key_file     [app]/[stream]-[seq].key;
其他的都没生成

**Comment by winlinvip** [comment]
265?
