### ISSUE TITLE
edge回源模式相同ip回源同一份流，带宽会翻倍

### ISSUE THREAD

**Issue by Osmond1689** [ossrs/srs#1626]
edge回源模式相同ip回源同一份流，带宽会翻倍
B为SRS边缘源站
C为视频中心

B edge模式 去C回源
B配置文件
mode     remote;
origin     C:1935;

此时如果不同用户去访问B  B去C的回源带宽只有一份
此时如果相同IP 同时去访问B  B去C的回源带宽是多份

2.0版本均可复现
3.0版本无

是否是2.0设计理念不同 还是为意料之外的问题 麻烦了 谢谢

**Comment by winlinvip** [comment]
SRS2和3一致，会合并回源，只会有一路回源。
请详细描述重现路径。
