### ISSUE TITLE
make报错

### ISSUE THREAD

**Issue by VariantChan** [ossrs/srs#1628]
git clone https://github.com/ossrs/srs && cd srs/trunk

./configure && make

make报错

src/main/srs_main_server.cpp:333:2: 警告：#warning "Current branch is unstable." [-Wcpp]
 #warning "Current branch is unstable."
  ^
g++ -o objs/srs objs/src/core/srs_core.o objs/src/core/srs_core_version3.o objs/src/core/srs_core_autofree.o objs/src/core/srs_core_performance.o objs/src/core/srs_core_mem_watch.o objs/src/core/srs_core_time.o objs/src/kernel/srs_kernel_error.o objs/src/kernel/srs_kernel_log.o objs/src/kernel/srs_kernel_buffer.o objs/src/kernel/srs_kernel_utility.o objs/src/kernel/srs_kernel_flv.o objs/src/kernel/srs_kernel_codec.o objs/src/kernel/srs_kernel_io.o objs/src/kernel/srs_kernel_consts.o objs/src/kernel/srs_kernel_aac.o objs/src/kernel/srs_kernel_mp3.o objs/src/kernel/srs_kernel_ts.o objs/src/kernel/srs_kernel_stream.o objs/src/kernel/srs_kernel_balance.o objs/src/kernel/srs_kernel_mp4.o objs/src/kernel/srs_kernel_file.o objs/src/protocol/srs_protocol_amf0.o objs/src/protocol/srs_protocol_io.o objs/src/protocol/srs_rtmp_stack.o objs/src/protocol/srs_rtmp_handshake.o objs/src/protocol/srs_protocol_utility.o objs/src/protocol/srs_rtmp_msg_array.o objs/src/protocol/srs_protocol_stream.o objs/src/protocol/srs_raw_avc.o objs/src/protocol/srs_rtsp_stack.o objs/src/protocol/srs_http_stack.o objs/src/protocol/srs_protocol_kbps.o objs/src/protocol/srs_protocol_json.o objs/src/protocol/srs_protocol_format.o objs/src/service/srs_service_log.o objs/src/service/srs_service_st.o objs/src/service/srs_service_http_client.o objs/src/service/srs_service_http_conn.o objs/src/service/srs_service_rtmp_conn.o objs/src/service/srs_service_utility.o objs/src/service/srs_service_conn.o objs/src/app/srs_app_server.o objs/src/app/srs_app_conn.o objs/src/app/srs_app_rtmp_conn.o objs/src/app/srs_app_source.o objs/src/app/srs_app_refer.o objs/src/app/srs_app_hls.o objs/src/app/srs_app_forward.o objs/src/app/srs_app_encoder.o objs/src/app/srs_app_http_stream.o objs/src/app/srs_app_thread.o objs/src/app/srs_app_bandwidth.o objs/src/app/srs_app_st.o objs/src/app/srs_app_log.o objs/src/app/srs_app_config.o objs/src/app/srs_app_pithy_print.o objs/src/app/srs_app_reload.o objs/src/app/srs_app_http_api.o objs/src/app/srs_app_http_conn.o objs/src/app/srs_app_http_hooks.o objs/src/app/srs_app_ingest.o objs/src/app/srs_app_ffmpeg.o objs/src/app/srs_app_utility.o objs/src/app/srs_app_edge.o objs/src/app/srs_app_heartbeat.o objs/src/app/srs_app_empty.o objs/src/app/srs_app_http_client.o objs/src/app/srs_app_http_static.o objs/src/app/srs_app_recv_thread.o objs/src/app/srs_app_security.o objs/src/app/srs_app_statistic.o objs/src/app/srs_app_hds.o objs/src/app/srs_app_mpegts_udp.o objs/src/app/srs_app_rtsp.o objs/src/app/srs_app_listener.o objs/src/app/srs_app_async_call.o objs/src/app/srs_app_caster_flv.o objs/src/app/srs_app_process.o objs/src/app/srs_app_ng_exec.o objs/src/app/srs_app_hourglass.o objs/src/app/srs_app_dash.o objs/src/app/srs_app_fragment.o objs/src/app/srs_app_dvr.o objs/src/app/srs_app_coworkers.o objs/src/main/srs_main_server.o objs/st/libst.a objs/openssl/lib/libssl.a objs/openssl/lib/libcrypto.a -ldl
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_lock_new’中：
threads_pthread.c:(.text+0x45)：对‘pthread_rwlock_init’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_read_lock’中：
threads_pthread.c:(.text+0x85)：对‘pthread_rwlock_rdlock’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_write_lock’中：
threads_pthread.c:(.text+0xa5)：对‘pthread_rwlock_wrlock’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_unlock’中：
threads_pthread.c:(.text+0xc5)：对‘pthread_rwlock_unlock’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_lock_free’中：
threads_pthread.c:(.text+0xea)：对‘pthread_rwlock_destroy’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_run_once’中：
threads_pthread.c:(.text+0x115)：对‘pthread_once’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_init_local’中：
threads_pthread.c:(.text+0x135)：对‘pthread_key_create’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_set_local’中：
threads_pthread.c:(.text+0x167)：对‘pthread_setspecific’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_cleanup_local’中：
threads_pthread.c:(.text+0x187)：对‘pthread_key_delete’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘openssl_init_fork_handlers’中：
threads_pthread.c:(.text+0x1e3)：对‘pthread_once’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘fork_once_func’中：
threads_pthread.c:(.text+0x16)：对‘pthread_atfork’未定义的引用
objs/openssl/lib/libcrypto.a(threads_pthread.o)：在函数‘CRYPTO_THREAD_get_local’中：
threads_pthread.c:(.text+0x153)：对‘pthread_getspecific’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘zlib_stateful_expand_block’中：
c_zlib.c:(.text+0x3d)：对‘inflate’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘zlib_stateful_compress_block’中：
c_zlib.c:(.text+0xae)：对‘deflate’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘zlib_stateful_finish’中：
c_zlib.c:(.text+0xe9)：对‘inflateEnd’未定义的引用
c_zlib.c:(.text+0xf2)：对‘deflateEnd’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘zlib_stateful_init’中：
c_zlib.c:(.text+0x1b4)：对‘inflateInit_’未定义的引用
c_zlib.c:(.text+0x230)：对‘deflateInit_’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘bio_zlib_free’中：
c_zlib.c:(.text+0x2a7)：对‘inflateEnd’未定义的引用
c_zlib.c:(.text+0x2d1)：对‘deflateEnd’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘bio_zlib_ctrl’中：
c_zlib.c:(.text+0x564)：对‘deflate’未定义的引用
c_zlib.c:(.text+0x624)：对‘zError’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘bio_zlib_write’中：
c_zlib.c:(.text+0x74a)：对‘deflate’未定义的引用
c_zlib.c:(.text+0x7ec)：对‘zError’未定义的引用
c_zlib.c:(.text+0x88b)：对‘deflateInit_’未定义的引用
objs/openssl/lib/libcrypto.a(c_zlib.o)：在函数‘bio_zlib_read’中：
c_zlib.c:(.text+0x98a)：对‘inflate’未定义的引用
c_zlib.c:(.text+0xa0f)：对‘zError’未定义的引用
c_zlib.c:(.text+0xa71)：对‘inflateInit_’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [objs/srs] 错误 1

**Comment by winlinvip** [comment]
请按模板要求提issue。
