### ISSUE TITLE
[Question] Mixing multiple audio streams into single output and relaying to third-party

### ISSUE THREAD

**Issue by tyranron** [ossrs/srs#1639]
Hi! Thank you for such amazing software! I've been quite impressed finding it ❤️

I've looked through the documentation and [config](https://github.com/ossrs/srs/blob/3.0release/trunk/conf/full.conf) quite detailed, but didn't found answers for 2 questions that bother me:

1. How one could [combine multiple audio streams](https://stackoverflow.com/a/11783474/1828012) via `transcode` section into a single `output`?

2. How one could push (relay/re-stream) the result to third-party servers like Wowza, Nginx RTMP, or even YouTube?
    - `forward` seems to work only with similar SRS instances as [supports `{ip}:{port}` format only](https://github.com/ossrs/srs/blob/3.0release/trunk/conf/full.conf#L457-L458).
    - other option coming to mind is to use `exec { publish ffmpeg }`, but that will fork yet another `ffmpeg` process, which has more costs.

Thanks!

**Comment by winlinvip** [comment]
Use FFmpeg to transcode multiple streams to one, then forward to third-party.
