### ISSUE TITLE
HLS is not LIVE

### ISSUE THREAD

**Issue by samiulhsohan** [ossrs/srs#1646]
When I am playing as HLS, it's always starting from first ts. That means it doesn't show live. Here is my config:

```
# conf/hls.conf
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
    }
}
```

Am I doing something wrong? or SRS HLS behaves like this?

**Comment by winlinvip** [comment]
Please read wiki

**Comment by samiulhsohan** [comment]
I have already saw the [wikiw](https://github.com/ossrs/srs/wiki/v3_EN_DeliveryHLS). But here it is not mentioned how to change mode/HLS type (Live, Event, Loop...)
