### ISSUE TITLE
Question: How to block a specific "user-agent" ??

### ISSUE THREAD

**Issue by tigerfran** [ossrs/srs#1650]
How to block a specific "user-agent" for url http "m3u8". I've tried to do it but I can't ...

in nginx I added a line in the .conf file... i changed nginx to srs.. srs is best for me but need add this featured

if ( $http_user_agent !~  (ua1|ua 2|ua3) ) {
		return 404;
    	}

**Comment by winlinvip** [comment]
Use HTTP proxy like nginx.
