### ISSUE TITLE
Live streaming CDN for SRS

### ISSUE THREAD

**Issue by xmglin** [ossrs/srs#1652]
**描述(Description)**

SRS做源站，能推荐个支持HTTP-FLV直播拉流的CDN服务（相当于edge）？(国内国外CDN均可)
Any ideas about Live streaming CDN services/providers to support SRS/HTTP-FLV?
Thanks.

**Comment by winlinvip** [comment]
阿里云CDN，腾讯云CDN，网宿，都支持。

**Comment by kennethlimcp** [comment]
@winlinvip 没看到设CDN的资料。在哪可以找到呢？
