### ISSUE TITLE
客户端统计接口调用中，未统计hls客户端

### ISSUE THREAD

**Issue by smally10** [ossrs/srs#1655]
**SRS版本(Version): `SRS/3.0.134`**

![image](https://user-images.githubusercontent.com/5791324/77162123-32787980-6ae6-11ea-81a0-19a3b1e54186.png)

**场景：**
启动srs docker服务，利用obs推流，在客户端统计那里，只能统计推流客户单，rmtp播放客户端，flv播放客户端，没有统计hls播放客户端。
**期望：**
能统计全部客户端。

**Comment by winlinvip** [comment]
Dup.

**Comment by duiniuluantanqin** [comment]
Resolved, see Linked Pull request.

`TRANS_BY_GPT3`
