### ISSUE TITLE
Enhance HTTP Streaming, HTTP Callback, HTTP API for HTTP-FLV, HTTPS, HLS etc.

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#1657]
SRS支持HTTP有几个应用：

* HTTP-API：侦听在1985，提供API服务。
    > 问题：没有支持鉴权，需要鉴权后代理到HTTP-API，也可以支持回调鉴权 #1640 
    > 问题：没有支持HTTPS，需要Nginx支持HTTPS后代理到SRS，SRS如果支持后会比较方便 #1533 
* HTTP-FLV：侦听在8080，提供FLV流服务。
    > 问题：没有支持HTTPS，需要Nginx支持HTTPS后代理到SRS，SRS如果支持后会比较方便 #1533 
* HLS：侦听在8080，或共享切片给Nginx，提供HLS流服务。
    > 问题：没有统计HLS客户端数目，和RTMP/FLV不一致，SRS如果支持会比较方便 #1655 
    > 问题：没有对HLS做鉴权，和RTMP/FLV不一致，SRS如果支持会比较方便 #1487 
    > 问题：没有支持HTTPS，需要Nginx支持HTTPS后代理到SRS，SRS如果支持后会比较方便 #1533 
* 使用Nginx或Caddy代理，提供统一的HTTP/HTTPS服务，参考 #2881

SRS4或SRS5若增强HTTP流媒体服务的能力，使用起来会更方便，一致性也比较强。

**Comment by winlinvip** [comment]
There is a work-around:

Use nginx or [go-oryx/httpx-static](https://github.com/ossrs/go-oryx/tree/develop/httpx-static#usage) to convert HTTP to HTTPS, or [HTTPS Live Streaming and HTTPS-FLV in practice](https://mp.weixin.qq.com/s/KvETKAmMb9Nks-dzBOpYRQ).

Whatever, SRS will support HTTPS client and server inside.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
HTTPS Client protocol:

[https-client.pcapng.zip](https://github.com/ossrs/srs/files/5479215/https-client.pcapng.zip)

**Comment by winlinvip** [comment]
HTTPS server protocol:

[https-server-port-1443.pcapng.zip](https://github.com/ossrs/srs/files/5499564/https-server-port-1443.pcapng.zip)
[https-server.pcapng.zip](https://github.com/ossrs/srs/files/5499566/https-server.pcapng.zip)

> Note: Refer to [OpenSSL example using memory BIO with non-blocking socket IO](https://gist.github.com/darrenjs/4645f115d10aa4b5cebf57483ec82eca).

## HTTPS API

Config for HTTPS API.

```
http_api {
    enabled         on;
    # For https_api or HTTPS API.
    https {
        # Whether enable HTTPS API.
        # default: off
        enabled on;
        # The listen endpoint for HTTPS API.
        # default: 443
        listen 443;
        # The SSL private key file, generated by:
        #       openssl genrsa -out server.key 2048
        # default: ./conf/server.key
        key ./conf/server.key;
        # The SSL public cert file, generated by:
        #       openssl req -new -x509 -key server.key -out server.crt -days 3650 -subj "/C=CN/ST=Beijing/L=Beijing/O=Me/OU=Me/CN=ossrs.net"
        # default: ./conf/server.crt
        cert ./conf/server.crt;
    }
}
```

Open in Chrome: https://127.0.0.1/api/v1/versions

**Comment by winlinvip** [comment]
> Use Nginx or Caddy as a proxy to provide unified HTTP/HTTPS services, refer to #2881.

HTTPS Stream server protocol:

* Wiki: [SRS Supports HTTPS FLV](https://github.com/ossrs/srs/wiki/v4_CN_DeliveryHttpStream#https-flv-live-stream).

Config for HTTPS Streaming Server, for example, [conf/https.flv.live.conf](https://github.com/ossrs/srs/blob/develop/trunk/conf/https.flv.live.conf) or [conf/https.hls.conf](https://github.com/ossrs/srs/blob/develop/trunk/conf/https.hls.conf):

```
http_server {
    enabled         on;
    listen          1985;
    # For https_api or HTTPS API.
    https {
        # Whether enable HTTPS API.
        # default: off
        enabled on;
        # The listen endpoint for HTTPS API.
        # default: 1986
        listen 1986;
        # The SSL private key file, generated by:
        #       openssl genrsa -out server.key 2048
        # default: ./conf/server.key
        key ./conf/server.key;
        # The SSL public cert file, generated by:
        #       openssl req -new -x509 -key server.key -out server.crt -days 3650 -subj "/C=CN/ST=Beijing/L=Beijing/O=Me/OU=Me/CN=ossrs.net"
        # default: ./conf/server.crt
        cert ./conf/server.crt;
    }
}
```

Open in Chrome:

* HTTPS: https://127.0.0.1:8088/live/livestream.flv
* HTTP: http://127.0.0.1:8080/live/livestream.flv

The SRS logs:

```

[2020-11-06 17:15:39.794][Trace][21509][9hyiw0e6] https: stream server done, use key 
./conf/server.key and cert ./conf/server.crt, cost=5ms
[2020-11-06 17:15:39.794][Trace][21509][9hyiw0e6] HTTP #0 127.0.0.1:62821 GET 
https://ossrs.net:8088/live/livestream.flv, content-length=-1

# For self-sign certificate, there is always an error:
[2020-11-06 17:15:39.788][Error][21509][9hyiw0e6][0] serve error code=4042 : start : handshake : handshake r0=-1, r1=1
thread [21509][9hyiw0e6]: do_cycle() [src/app/srs_app_http_conn.cpp:170][errno=0]
thread [21509][9hyiw0e6]: on_start() [src/app/srs_app_http_conn.cpp:380][errno=0]
thread [21509][9hyiw0e6]: handshake() [src/app/srs_app_conn.cpp:624][errno=0]
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It is worth doing well and mastering the basics of HTTP.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
All HTTP-API related issues should be consolidated and updated in this issue. Please ensure that the markdown structure is maintained.

* HTTP API does not count the number of WebRTC distributed streams (i.e., the number of clients) - [Issue #2290](https://github.com/ossrs/srs/issues/2290)
* Abnormal result of HTTP interface in SRS 4.0 version - [Issue #2231](https://github.com/ossrs/srs/issues/2231)
* How to obtain WebRTC client information when streaming with SRS RTMP and watching with WebRTC - only able to obtain streaming information in the console - [Issue #2149](https://github.com/ossrs/srs/issues/2149)
* HTTP API in version 2.0.243 does not count HLS clients - [Issue #996](https://github.com/ossrs/srs/issues/996)
* APPLICATION: When using HTTP-FLV playback, traffic statistics are incorrect when using SRS HTTP API, although the client connection count is correct - [Issue #863](https://github.com/ossrs/srs/issues/863)

Please ensure that the markdown structure is maintained.

`TRANS_BY_GPT3`

**Comment by peipeiguo** [comment]
Looking forward to SRS4 supporting HLS client statistics and HLS on_play/on_stop callbacks.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS 4
