### ISSUE TITLE
dvr http raw api multiple enable multiple streams with one request

### ISSUE THREAD

**Issue by franzwarning** [ossrs/srs#1662]
Hi,

Just wondering if it is possible to enable DVR for multiple streams with a single request. I've tried this:
```
/api/v1/raw?rpc=update&scope=dvr&value=rtmp.stream.xxx&param=enable&data=live/xxx_mobile_720%20live/xxx_web_720
```

It doesn't url decode the `%20` into a space character so the .conf ends up looking like:
```
dvr_apply live/xxx_mobile_720%20live/xxx_web_720 
```

Alternatively, is it possible to use some sort of wildcard character `*` or `*_720` or something?

Thanks for a great library!

Cheers,
Raymond

**Comment by winlinvip** [comment]
Won't support.
