### ISSUE TITLE
https下无法访问flv视频

### ISSUE THREAD

**Issue by sft7f** [ossrs/srs#1663]
我尝试用nginx，反向代理flv 模式下的8080端口，单我只能通过http方式访问 通过https就无法访问。

**Comment by terry8204** [comment]
Put an nginx https proxy in front, and you're good to go.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS4 natively supports HTTPS.

`TRANS_BY_GPT3`

**Comment by huzhou520** [comment]
Hello, I am using nginx https proxy to access http-flv on port 8080, but I am unable to play the stream.

`TRANS_BY_GPT3`
