### ISSUE TITLE
多线程SRS，C/C++版本的golang协程和网络库

### ISSUE THREAD

**Issue by bigbao9494** [ossrs/srs#1669]
cpp_go：
https://github.com/bigbao9494/cpp_go_prj.git
cpp_go是用C/C++实现的类似golang的协程和网络库，让C/C++程序员可以轻松写出高并发的网络程序，可以用同步的方式(每个连接一个线程)写出异步的高性能，支持协程栈大小设置，每个协程可以根据业务逻辑的需求在创建协程时设置不同栈大小，可以指定任意多个CPU核心(物理线程)
来执行协程，任务的调度和golang一样是动态调度而不像有些协程库简单地做平均分配，
同时它会根据每个物理线程的实际cpu使用率来进行任务均衡，这才是最真实的均衡不会
出现平均分配时有些核心上的协程由于业务的简单被很快地执行完了而其它核心上的协程
却还在等待被执行。实现了shared_fd功能(通过创建协程指定参数来开启此功能，默认此功能是关闭的，不允许一个socket存在多个协程中，为了异步IO和动态调度时确保数据的完整性)，同一个socket可以同时存在于2个协程中，一个负责写一个负责读，在实际业务中会有这样的需求，比如在同一个socket上99%时间都在写偶尔也需要去读，像流媒体协议中rtmp连接就是大部分时间都是在向客户端转发数据但偶尔需要读取客户端状态数据，如果只在一个协程中处理这个连接的话代码实现起来就会比较奇怪且效率低下，每次写都要去做一次读或者间隔读，每次读感觉效率低下间隔读又不能及时响应对端数据，读写分开在2个协程中就能很好解决这样的问题，剩下的只是在这2个协程中进行同步和通信而已。同时实现了必要的同步和通信模块co_mutex、co_condition_variable、channel、co_timer、co_sleep这些最重要最基础的模块，也可以在这些基础模块上衍生出像golang中的RWMutex、channel_select等高级操作。另外还实现了task_cache功能，协程结束时对应的栈
不释放而缓存起来供下次创建协程时使用这样对高频率创建协程的应用时性能更友好，不需要反复地向系统申请栈释放栈(编译时打开宏USE_TASK_CACHE)，协程函数兼容C程序员函数指针
习惯的同时支持C++的函数对象。

支持平台：
linux_x64
linux_arm32(理论上支持android_arm未测试过)
windows_x64
因为栈切换使用的是boost.context所以理论上boost.context支持的CPU架构cpp_go
都支持(x86,arm64,mips,power_pc等等具体见源码中asm文件夹)，上面列出的3个平台
只是我做开发时测试和使用过的而已，不过不同操作系统会使用特定的IO模型所以这点
上看如果还要扩展到其它系统是需要适配的(macOS,unix等)，linux下使用EPOLL和SELECT
windows下只实现了SELECT没有没有实现IOCP模型，如果需要支持更多IO模型只需要实现
接口InnerIoWait即可。

IO接口兼容ST，如果用它来把SRS改成多线程的是否可行，因为SRS设计之初只考虑了单线程，业务逻辑上数据流动是无锁设计，但是多线程后SRS的各协程会运行在不同线程上，这样原来的无锁设计是否需要做大量修改？
@winlinvip 就是上次我发帖我们讨论的那个网络库，做好了一些完整测试现在开源出来，你看一下指点一下，也帮我置顶一下让大家多提点意见。

**Comment by winlinvip** [comment]
👍 感谢分享，先总结几个关于SRS单线程的问题：

* ST本身是支持多线程的但有Bug所以SRS就只用了单线程。
* 现在发现多线程需要用锁，类似Go那种模型，其实比较麻烦。
* 而现在Docker本身就是一个进程，可以抵消一部分单进程的问题。
* REUSEPORT可以让多进程也很容易，所以SRS倾向于多进程单线程。

当然，你开源的这个库，既然支持了多线程，当然也可以支持单线程。我看了其实SRS是有可能使用你这个库的，但要麻烦你确认下几点：

* 我看和ST API是兼容的，这个很好。不知道和ST相比的性能开销如何，能否做一些benchmark，当然可以限定为单线程对比，可以用SRS的srs-bench看下播放和推流的差异。ST是有一些优化的，有朋友提了PR：https://github.com/ossrs/state-threads/pull/5
* 这个库的LICENSE是BSD3，Apache，还是MIT呢？请指定下库的LICENSE吧。SRS是MIT，希望能尽量使用比较兼容的开源协议。

再次感谢和点赞。

**Comment by bigbao9494** [comment]
@winlinvip https://github.com/bigbao9494/cpp_go_prj.git
git上面有做部分性能测试，做了与ST的PING_PONG测试吞吐，你看一下。
REUSEPORT很好我觉得还是存在多个任务间通信的麻烦，特别是业务逻辑复杂时估计就不太好写了，协程一个目的就是解放程序员异步的苦恼。
LICENSE的问题，因为栈切换使用了boost.context，需要参考boost.context吧

**Comment by winlinvip** [comment]
我看了下，没有想明白：如果SRS切换到这个协程库，能解决什么问题？
