### ISSUE TITLE
debian10编译出错 stream:301:7: error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ 

### ISSUE THREAD

**Issue by weicaijiang** [ossrs/srs#1675]
**描述(Description)*执行命令 bash scripts/build.sh *

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `srs-3.0-b3`
1. SRS的日志如下(Log):
make[3]: 离开目录“/home/home/soft/srs-3.0-b3/trunk/research/librtmp”
make[2]: 离开目录“/home/home/soft/srs-3.0-b3/trunk/research/librtmp”
Building the utest for srs
(cd objs/utest; make)
make[2]: 进入目录“/home/home/soft/srs-3.0-b3/trunk/objs/utest”
g++ -I../../objs/gtest/include -g -Wall -Wextra -O0  -I../../src/utest -I../../src/core -I../../src/kernel -I../../src/protocol -I../../src/service -I../../src/app -I../../objs -I../../objs/st -I../../objs/openssl/include  -c ../../src/utest/srs_utest.cpp -o srs_utest.o
In file included from ../../objs/gtest/include/gtest/internal/gtest-port.h:197,
                 from ../../objs/gtest/include/gtest/internal/gtest-internal.h:40,
                 from ../../objs/gtest/include/gtest/gtest.h:57,
                 from ../../src/utest/srs_utest.hpp:36,
                 from ../../src/utest/srs_utest.cpp:24:
/usr/include/c++/8/sstream:301:7: error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ redeclared with different access
       struct __xfer_bufptrs
       ^~~~~~
make[2]: *** [Makefile:92：srs_utest.o] 错误 1
make[2]: 离开目录“/home/home/soft/srs-3.0-b3/trunk/objs/utest”
make[1]: *** [Makefile:115：utest] 错误 2
make[1]: 离开目录“/home/home/soft/srs-3.0-b3/trunk”
make: *** [Makefile:8：default] 错误 2
错误：编译SRS失败

**Comment by linuxliu** [comment]
g++ downgrade to 4.x and give it a try

`TRANS_BY_GPT3`

**Comment by xugaoxiang** [comment]
./configure --without-utest

**Comment by winlinvip** [comment]
@xugaoxiang 👍
