### ISSUE TITLE
播放卡顿

### ISSUE THREAD

**Issue by Luosh** [ossrs/srs#1683]
**描述(Description)**

> srs3.0 使用sb测试1k推流、source.1250kbps.768x320.cbr.flv. 双核cpu占用20%左右。 但是拉取其中任意一路rtmp播放, 会出现卡顿的现象（内容是连续的）， 测试100路并发是不会出现， 500时偶尔卡顿， 1k时明显。 有没有同样情况的同学？

**Comment by Luosh** [comment]
top
> top - 19:54:26 up 38 days, 23:05,  3 users,  load average: 0.79, 1.02, 0.98
Tasks:  92 total,   3 running,  55 sleeping,   0 stopped,   0 zombie
%Cpu0  : 15.7 us, 21.1 sy,  0.0 ni, 54.5 id,  0.0 wa,  0.0 hi,  8.7 si,  0.0 st
%Cpu1  : 34.7 us, 10.0 sy,  0.0 ni, 52.7 id,  0.0 wa,  0.0 hi,  2.7 si,  0.0 st
KiB Mem :  8021636 total,  4440856 free,  1830596 used,  1750184 buff/cache
KiB Swap:   969964 total,   969964 free,        0 used.  5899292 avail Mem 

>  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                  
21069 root      20   0 1909140 1.527g   4388 R  47.2 20.0   1:53.09 srs                                                                                                      
21093 root      20   0  248512  47948   3912 R  43.5  0.6   1:46.21 sb_rtmp_publish  
>

**Comment by winlinvip** [comment]
This could be an issue with sb publish's sending. There can be several ways to solve it.

1. You can use ffmpeg to stream for someone else to watch, if it doesn't lag then there is no problem.
2. Use fewer sb publish instances, for example, start with 3 instances with around 300 each, or even 10 instances would work.

`TRANS_BY_GPT3`

**Comment by Luosh** [comment]
Method

> This may be an issue with sb publish, there can be several ways to solve it:
> 
> 1. You can use ffmpeg to stream to another person and see if it is not lagging, if it is not lagging then there is no problem.
> 2. Use fewer sb publish instances, for example, start with 3 instances with around 300 each, or even 10 instances would work.

> Method 1: Test for no lag.

`TRANS_BY_GPT3`
