### ISSUE TITLE
docker ossrs/srs:3 启动挂载宿主srs.conf 录制宕机 

### ISSUE THREAD

**Issue by javaerSivan** [ossrs/srs#1688]
docker 使用ossrs/srs:3镜像 启动挂载宿主srs.conf ，登入srs-console点击录制，到账容器宕机。

1. SRS版本(Version): `ossrs/srs:3`

1. SRS的配置如下(Config):
listen 1935;
max_connections 1000;
srs_log_tank file;
srs_log_file ./objs/srs.log;
daemon off;
http_api {
    enabled on;
    listen 1985;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }
}
http_server {
    enabled on;
    listen 8080;
    dir ./objs/nginx/html;
}
stats {
    network 0;
    disk sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    tcp_nodelay on min_latency on;
    play {
        gop_cache off;
        queue_length 10;
        mw_latency 100;
    }
    publish {
        mr off;
    }
    dvr {
        enabled on;
        dvr_path ./objs/nginx/html/dvr/[app]/[stream]/[2006]-[01]-[02]/[15]_[04]_[05].mp4;
        dvr_plan segment;
        dvr_duration 1800;
        dvr_wait_keyframe on;
        dvr_apply none;
    }
    http_hooks {
        enabled on;
        on_dvr http://127.0.0.1:8082/xxx/mediaServerCallback/record;
    }
}

> 重现Bug的步骤(How to replay bug?)

1. 启动srs容器  ： docker run -d --name=srs -p 9090:8080 -p 2935:1935 -p 2985:1985 -v /root/srs.conf:/usr/local/srs/conf/srs.conf ossrs/srs:3
ecd3aaba489fd2d0885018e1790b746cbc3341fa0080de81ca8b47162ef57ec3
2. 使用OBS推流到SRS
3. 进入srs控制台：localhost:9090 
4.点击视频流-》点击录制-》点击修改-》选择录制-》点击提交
5.到此 srs 容器就挂了

**Comment by qisuwan** [comment]
I have also encountered this problem

`TRANS_BY_GPT3`

**Comment by nbaxp** [comment]
The same configuration does indeed have this problem in Docker. I have tried Docker Compose on both Windows and Ubuntu, and it exits during recording.
My configuration: 
```listen 1935;
daemon off;
max_connections 1000;
srs_log_tank file;
srs_log_file ./objs/srs.log;
http_api {
    enabled on;
    listen 1985;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }
}
http_server {
    enabled on;
    listen 8080;
    dir ./objs/nginx/html;
}
stats {
    network 0;
    disk sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    transcode live {
        enabled on;
        ffmpeg ./objs/ffmpeg/bin/ffmpeg;
        engine snapshot {
            enabled on;
            iformat flv;
            vfilter {
                vf fps=1;
            }
            vcodec png;
            vparams {
                vframes 1;
            }
            acodec an;
            oformat image2;
            output ./objs/nginx/html/[app]/[stream].png;
        }
    }
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    hls {
        enabled on;
        hls_fragment 3;
        hls_window 10;
        hls_path ./objs/nginx/html;
        hls_m3u8_file [app]/[stream].m3u8;
        hls_ts_file [app]/[stream]-[seq].ts;
    }
    dvr {
        enabled on;
        dvr_apply none;
        dvr_path ./objs/nginx/html/video/[app].[stream].[timestamp].mp4;
    }
    http_hooks {
        enabled on;
        on_dvr http://localhost/IoTCenter/api/v1/Srs/OnDvr;
    }
}
```

`TRANS_BY_GPT3`

**Comment by csurn** [comment]
> docker 使用ossrs/srs:3镜像 启动挂载宿主srs.conf ，登入srs-console点击录制，到账容器宕机。
> 
> 1. SRS版本(Version): `ossrs/srs:3`
> 2. SRS的配置如下(Config):
>    listen 1935;
>    max_connections 1000;
>    srs_log_tank file;
>    srs_log_file ./objs/srs.log;
>    daemon off;
>    http_api {
>    enabled on;
>    listen 1985;
>    raw_api {
>    enabled on;
>    allow_reload on;
>    allow_query on;
>    allow_update on;
>    }
>    }
>    http_server {
>    enabled on;
>    listen 8080;
>    dir ./objs/nginx/html;
>    }
>    stats {
>    network 0;
>    disk sda sdb xvda xvdb;
>    }
>    vhost **defaultVhost** {
>    http_remux {
>    enabled on;
>    mount [vhost]/[app]/[stream].flv;
>    }
>    tcp_nodelay on min_latency on;
>    play {
>    gop_cache off;
>    queue_length 10;
>    mw_latency 100;
>    }
>    publish {
>    mr off;
>    }
>    dvr {
>    enabled on;
>    dvr_path ./objs/nginx/html/dvr/[app]/[stream]/[2006]-[01]-[02]/[15]_[04]_[05].mp4;
>    dvr_plan segment;
>    dvr_duration 1800;
>    dvr_wait_keyframe on;
>    dvr_apply none;
>    }
>    http_hooks {
>    enabled on;
>    on_dvr http://127.0.0.1:8082/xxx/mediaServerCallback/record;
>    }
>    }
> 
> > 重现Bug的步骤(How to replay bug?)
> 
> 1. 启动srs容器  ： docker run -d --name=srs -p 9090:8080 -p 2935:1935 -p 2985:1985 -v /root/srs.conf:/usr/local/srs/conf/srs.conf ossrs/srs:3
>    ecd3aaba489fd2d0885018e1790b746cbc3341fa0080de81ca8b47162ef57ec3
> 2. 使用OBS推流到SRS
> 3. 进入srs控制台：localhost:9090
>    4.点击视频流-》点击录制-》点击修改-》选择录制-》点击提交
>    5.到此 srs 容器就挂了

你后来解决了吗？

**Comment by nbaxp** [comment]
> Use the ossrs/srs:3 image in Docker to start and mount the host's srs.conf. Log in to srs-console, click on recording, and the account container crashes.
> 
> 1. SRS version: `ossrs/srs:3`
> 2. The configuration for SRS is as follows:
>    listen 1935;
>    max_connections 1000;
>    srs_log_tank file;
>    srs_log_file ./objs/srs.log;
>    daemon off;
>    http_api {
>    enabled on;
>    listen 1985;
>    raw_api {
>    enabled on;
>    allow_reload on;
>    allow_query on;
>    allow_update on;
>    }
>    }
>    http_server {
>    enabled on;
>    listen 8080;
>    dir ./objs/nginx/html;
>    }
>    stats {
>    network 0;
>    disk sda sdb xvda xvdb;
>    }
>    vhost **defaultVhost** {
>    http_remux {
>    enabled on;
>    mount [vhost]/[app]/[stream].flv;
>    }
>    tcp_nodelay on min_latency on;
>    play {
>    gop_cache off;
>    queue_length 10;
>    mw_latency 100;
>    }
>    publish {
>    mr off;
>    }
>    dvr {
>    enabled on;
>    dvr_path ./objs/nginx/html/dvr/[app]/[stream]/[2006]-[01]-[02]/[15]_[04]_[05].mp4;
>    dvr_plan segment;
>    dvr_duration 1800;
>    dvr_wait_keyframe on;
>    dvr_apply none;
>    }
>    http_hooks {
>    enabled on;
>    on_dvr http://127.0.0.1:8082/xxx/mediaServerCallback/record;
>    }
>    }
> 
> > Steps to reproduce the bug:
> 
> 1. Start the SRS container: `docker run -d --name=srs -p 9090:8080 -p 2935:1935 -p 2985:1985 -v /root/srs.conf:/usr/local/srs/conf/srs.conf ossrs/srs:3`
>    ecd3aaba489fd2d0885018e1790b746cbc3341fa0080de81ca8b47162ef57ec3
> 2. Use OBS to stream to SRS.
> 3. Access the SRS control panel: localhost:9090
>    4. Click on "Video Stream" -> Click on "Record" -> Click on "Modify" -> Select "Record" -> Click on "Submit"
>    5. At this point, the SRS container has crashed.

Have you resolved it later?

`TRANS_BY_GPT3`

**Comment by nbaxp** [comment]
Which comrade solved this problem? Please share, I would be very grateful.

`TRANS_BY_GPT3`

**Comment by nbaxp** [comment]
@winlinvip, any suggestions, master?

`TRANS_BY_GPT3`

**Comment by nbaxp** [comment]
Has no one encountered the same problem?

`TRANS_BY_GPT3`

**Comment by nbaxp** [comment]
I solved it myself: Instead of using the official Docker, I used the Ubuntu Docker image to map to the local SRS deployment directory.

`TRANS_BY_GPT3`

**Comment by huizluo** [comment]
Why did it close? Has this issue been resolved? When running Docker, calling the DVR recording interface causes the main loop to immediately exit, resulting in the termination of the container.

`TRANS_BY_GPT3`

**Comment by huizluo** [comment]
The directory where the configuration file is mounted will not exit, but if it is mounted separately, it will exit. I hope that classmates who encounter the same problem in the future can avoid this pitfall.

`TRANS_BY_GPT3`
