### ISSUE TITLE
API: Filter by stream for /api/v1/clients. For the /api/v1/clients interface, I hope to support the functionality of obtaining the client list based on the stream's ID.

### ISSUE THREAD

**Issue by rentianhua** [ossrs/srs#1693]
For the /api/v1/clients interface, I hope to support the functionality of obtaining the client list based on the stream's ID.

In actual scenarios, when starting a live stream, it is necessary to obtain the specific user information under this stream.

**Comment by winlinvip** [comment]
It can be considered.

**Comment by duiniuluantanqin** [comment]
This can be achieved through the combination of `/api/v1/clients` and `/api/v1/streams` interfaces. I feel that there is no need for SRS to do this.
