### ISSUE TITLE
For filesize 2GB+, dvr mp4 stream.mp4 moov atom not found srs 3.0

### ISSUE THREAD

**Issue by nguyenduybinh** [ossrs/srs#1694]
**(Description)**

Hi all, I use SRS for my livestream system. Everything OK but sometime, when have long livestream, the mp4 dvr file after livestream is break. I used ffmpeg to check the file, and the error like that:
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x41e55c0] moov atom not found
5e8ab3d7b3b1a2001b5e9b93.1586148554308.mp4: Invalid data found when processing input

Anyone have the same issue and how to fix this?

1. SRS(Version): `3.0release`

2. SRS(Config):
```
vhost __defaultVhost__ {

    dvr {
        enabled      on;
        dvr_path     ./objs/nginx/html/[app]/[stream].[timestamp].mp4;
        dvr_plan     session;
    }
```

**Comment by franzwarning** [comment]
Have the same issue. I've found that it happens on recordings of ~ 2hrs or more. Would love to see a solution for this. Perhaps it's an issue with mp4 and not flv?

**Comment by vietkute02** [comment]
@franzwarning not exactly about record duration, its error when file size larger than 2GB. I think it error when unpublish stream, because mp4 format need to re write moov header when finish

**Comment by nguyenduybinh** [comment]
> @franzwarning not exactly about record duration, its error when file size larger than 2GB. I think it error when unpublish stream, because mp4 format need to re write moov header when finish

Did you have the same issue? And you have any solution for this issue? I'm considering to use dvr segment plan to separate to small MP4 file and join them together after stream unpublish

**Comment by franzwarning** [comment]
> because mp4 format need to re write moov header when finish
Does this mean that flv doesn't need to? Might consider switching to flv in that case. Or using the segment plan, just makes my life a little more difficult.

**Comment by vietkute02** [comment]
@franzwarning yes, you can change dvr format to flv, if you choose dvr plan is segment make surre dvr file size not larger than 2GB (I used it). Then just wait contributor fix this bug

**Comment by cbfcmc** [comment]
mdat->nb_data = uint32_t(mdat_bytes);nb_data overflow int->uint32

**Comment by winlinvip** [comment]
It seems the overflow of mdat size, which use uint32_t.

**Comment by winlinvip** [comment]
```
class ISrsCodec
{
public:
    ISrsCodec();
    virtual ~ISrsCodec();
public:
    /**
     * get the number of bytes to code to.
     */
    // TODO: FIXME: change to uint64_t.
    virtual int nb_bytes() = 0;
```

定义的这个字节是int，所以只有2GB大小，需要改成uint64_t。

**Comment by winlinvip** [comment]
```
MacBookPro:live cheng.ycl$ ls -lh *.mp4*
-rw-r--r--  1 cheng.ycl  staff   5.0G Dec 17 15:08 ffmpeg.mp4
-rw-r--r--  1 cheng.ycl  staff   5.0G Dec 17 15:08 livestream.1608188848270.mp4

MacBookPro:live cheng.ycl$ od -t x1 -N64 ffmpeg.mp4
0000000    00  00  00  20  66  74  79  70  69  73  6f  6d  00  00  02  00
0000020    69  73  6f  6d  69  73  6f  32  61  76  63  31  6d  70  34  31
0000040    00  00  00  01  6d  64  61  74  00  00  00  01  40  ce  1f  42
0000060    00  00  02  cb  06  05  ff  ff  c7  dc  45  e9  bd  e6  d9  48
0000100
MacBookPro:live cheng.ycl$ od -t x1 -N64 livestream*.mp4
0000000    00  00  00  20  66  74  79  70  69  73  6f  6d  00  00  02  00
0000020    69  73  6f  6d  69  73  6f  32  61  76  63  31  6d  70  34  31
0000040    00  00  00  01  6d  64  61  74  00  00  00  01  40  ce  1f  42
0000060    00  00  02  cb  06  05  ff  ff  c7  dc  45  e9  bd  e6  d9  48
0000100
```

注意，Size就是`00  00  00  01  40  ce  1f  42`。
