### ISSUE TITLE
live 地址如何修改

### ISSUE THREAD

**Issue by lgoodbook** [ossrs/srs#1697]
RTMP流地址为：rtmp://192.168.1.170/live/livestream
HLS流地址为： http://192.168.1.170:8080/live/livestream.m3u8
咨询一下，live 想自定义，该如何修改？

**Comment by wnpllrzodiac** [comment]
live' is at the app level. It can be customized. For example,
rtmp://192.168.1.170/sports/football
rtmp://192.168.1.170/music/classic

`TRANS_BY_GPT3`

**Comment by lgoodbook** [comment]
When pushing the stream, 
modify the [app][stream] name. 
For example: ffmpeg -re -stream_loop -1 -i 6dd6792ee94de50047f13bdd2bee2bd8.mp4 -vcodec copy -acodec copy -f flv -y rtmp://192.168.0.1:1935/app/stream.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@wnpllrzodiac 👍
