### ISSUE TITLE
请问srs如何配置使之支持rtmps

### ISSUE THREAD

**Issue by AOZHUOYAO** [ossrs/srs#1700]
请问srs如何配置使之支持rtmps

**Comment by xiongziliang** [comment]
嗨 你可以了解这个项目，它支持rtmps: https://github.com/zlmediakit/ZLMediaKit

**Comment by spiderspiderspider** [comment]
> 嗨 你可以了解这个项目，它支持rtmps: https://github.com/zlmediakit/ZLMediaKit

您好，我在测试ZLMediaKit这个项目的时候，文档中没有看到关于rtmps的配置与说明，于是用nginx代理了tcp连接并对其进行tls加密，nginx的配置文件如下：
stream {

    server {
        listen     443 ssl;
        ssl_certificate /etc/nginx/cert/xxx.com.pem;
        ssl_certificate_key /etc/nginx/cert/xxx.com.key;
        ssl_handshake_timeout 5m;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        proxy_pass 10.0.0.xxx:1935;
    }
}
经过测试，用ffmpeg推h264的流到rtmps连接可以成功，用ffmpeg推h265的流到rtmps失败。ffmpeg部分日志如下：
x265 [info]: Thread pool created using 8 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 3 / wpp(12 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 19 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-28.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=4 deblock sao
Output #0, flv, to 'rtmps://stream.imilab.com:473/live/test':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf57.83.100
    Stream #0:0(und): Video: hevc (libx265) ([12][0][0][0] / 0x000C), yuv420p, 1280x720, q=2-31, 19.61 fps, 1k tbn, 19.61 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.107.100 libx265
    Stream #0:1(und): Audio: aac (LC) ([10][0][0][0] / 0x000A), 8000 Hz, mono, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      encoder         : Lavc57.107.100 aac
[tls @ 00000189694d9aa0] Writing encrypted data to socket failedate= 199.6kbits/s speed=0.879x
av_interleaved_write_frame(): I/O error
[flv @ 0000018969579fc0] Failed to update header with correct duration.6.3kbits/s speed=0.108x
[flv @ 0000018969579fc0] Failed to update header with correct filesize.
Error writing trailer of rtmps://stream.imilab.com:473/live/test: I/O error
frame=   35 fps=1.9 q=-0.0 Lsize=      46kB time=00:00:02.17 bitrate= 173.2kbits/s speed=0.12x
video:41kB audio:9kB subtitle:0kB other streams:0kB global headers:2kB muxing overhead: unknown
[tls @ 00000189694d9aa0] Writing encrypted data to socket failed
    Last message repeated 1 times
[tls @ 00000189694d9aa0] Failed to send close message
x265 [info]: frame I:      1, Avg QP:22.30  kb/s: 6469.49
x265 [info]: frame P:     10, Avg QP:28.46  kb/s: 118.54
x265 [info]: frame B:     24, Avg QP:34.55  kb/s: 14.91
x265 [info]: Weighted P-Frames: Y:0.0% UV:0.0%
x265 [info]: consecutive B-frames: 27.3% 9.1% 9.1% 27.3% 27.3%

encoded 35 frames in 17.55s (1.99 fps), 228.93 kb/s, Avg QP:32.46
[aac @ 00000189694d8900] Qavg: 40407.688
Conversion failed!

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/80558298-76776c00-8a0c-11ea-93f7-441032991dd2.png)

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/80558333-9ad34880-8a0c-11ea-8524-c5b2ddffd92e.png)

**Comment by xiongziliang** [comment]
https://github.com/xiongziliang/ZLMediaKit/blob/master/conf/config.ini#L152

**Comment by spiderspiderspider** [comment]
> https://github.com/xiongziliang/ZLMediaKit/blob/master/conf/config.ini#L152

响应速度这么老快，真的棒！！！！

**Comment by winlinvip** [comment]
SRS不支持RTMPS，如果其他服务器支持推荐用其他服务器。
