### ISSUE TITLE
转播YouTube直播总是出错

### ISSUE THREAD

**Issue by Himalaya2020** [ossrs/srs#1703]
**描述(Description)**

> 使用`./objs/srs -c conf/http.flv.live.conf`开启srs，使用`ffmpeg -re -i "$(youtube-dl -f 96 -g "https://www.youtube.com/watch?v=9Auq9mYxFEE")" -c copy -f flv "rtmp://127.0.0.1/live/livestream"` 报错

错误如下
```
Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Invalid data found when processing input
[flv @ 0x555d9b000700] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
Error writing trailer of rtmp://127.0.0.1/live/livestream: Invalid data found when processing input
```
后来ffmpeg加入了-bsf:a aac_adtstoasc
使用`ffmpeg -re -i "$(youtube-dl -f 96 -g "https://www.youtube.com/watch?v=9Auq9mYxFEE")" -bsf:a aac_adtstoasc -c copy -f flv "rtmp://127.0.0.1/live/livestream"`
没有报错但是放不出来，每次都会卡住不动（cpu占用也很小）

1. SRS版本(Version): `v3`

2. SRS的配置如下(Config):
```
# conf/http.flv.live.conf
listen              1935;
max_connections     1000;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }
}
```

**期望行为(Expect)**

> 希望能出个中转YouTube直播的教程（使用自己的服务器看YouTube直播），我总是折腾不明白。万分感谢

**Comment by wnpllrzodiac** [comment]
I tried it, and the result is HLS.
I think it's better to use srs_ingest_hls.
Using ffmpeg to convert HLS to RTMP is not very good.

I tried another way to push HLS to SRS, and it worked fine.

ffmpeg -re -i "http://a.com/hls/testhd.m3u8" -bsf:a aac_adtstoasc -c copy -f flv rtmp://192.168.1.1/live/gogogo

Are you sure your internet speed is normal? Check if the streaming speed is around 1x.
frame= 2068 fps= 30 q=-1.0 size=   55222kB time=00:01:08.86 bitrate=6568.8kbits/s speed=   1x

================================
>youtube-dl -f 96 -g https://www.youtube.com/watch?v=9Auq9mYxFEE --proxy socks5://127.0.0.1:12345

https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1587105601/ei/4fqYXteDK9apkgbk0ofIDA/ip/1.2.3.4/id/9Auq9mYxFEE.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r3---sn-a5mlrn7d.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/initcwndbps/8560/mh/Yv/mm/44/mn/sn-a5mlrn7d/ms/lva/mv/m/mvi/2/pl/20/dover/11/keepalive/yes/mt/1587083897/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AJpPlLswRQIgak74iuzIGV43Kh-ZyG6gDFB9ZUp0rl20GIFC055EfyICIQCsaOCvrgvfnvmkCzEq66TrKg4v0yiNoaLtDA7_S56Arw%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/ALrAebAwRQIhAIFUe9cKYvukfYnVJgRReDbZ2v8rcAzLVQQWKMApmqSmAiAAojJSERk59J6Tq-Uv_peTH_mv5RMIFrgkSi7H27GjGw%3D%3D/playlist/index.m3u8


`TRANS_BY_GPT3`

**Comment by Pearlulu** [comment]
There is no problem with directly broadcasting at a low bitrate.
Re-broadcasting with high bitrate and high resolution using the -re parameter will most likely result in dropped frames. Without the -re parameter, there will be no dropped frames and the latency will be very low, but there is a high probability of encountering errors after streaming for a while.
If stability is desired, use youtube-dl to output to a pipeline and then use ffmpeg to stream, but this will require much more memory and CPU usage.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
FFmpeg for broadcasting

`TRANS_BY_GPT3`
