### ISSUE TITLE
rtmp 是否支持 16KHz的 pcm audio

### ISSUE THREAD

**Issue by zh794390558** [ossrs/srs#1707]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `c2657bf672a99e910948f24a37734444440b3a3c`
接收标准的 H264/AAC 流，用transcode 转码成 vn pcm_s16le时，samplerate 设置 16KHz。通过 rmtp 播放后显示的数据报是 5.5KHz，这是为什么？

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

ffplay 播放声音正常，采用率为 16KHz

**Comment by winlinvip** [comment]
PCM support is not good, used too little, can only fix it myself, bro.

`TRANS_BY_GPT3`
