### ISSUE TITLE
srs支持rtmp推流转rtsp协议吗？

### ISSUE THREAD

**Issue by bestneymarjr** [ossrs/srs#1709]
如果支持，视频，音频格式有什么限制吗？

**Comment by MyKays** [comment]
好像是不支持，我看了几天没找到，兄弟解决了么？

**Comment by bestneymarjr** [comment]
我也没找到



---原始邮件---
发件人: "Kay"<notifications@github.com&gt;
发送时间: 2020年7月16日(周四) 晚上7:00
收件人: "ossrs/srs"<srs@noreply.github.com&gt;;
抄送: "bestneymarjr"<410398379@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [ossrs/srs] srs支持rtmp推流转rtsp协议吗？ (#1709)




 
好像是不支持，我看了几天没找到，兄弟解决了么？

**Comment by winlinvip** [comment]
不支持。
