### ISSUE TITLE
SRS 测试 ingest.conf 报错

### ISSUE THREAD

**Issue by VampireCrazy** [ossrs/srs#1712]
**描述(Description)**

> 按照https://github.com/ossrs/srs/wiki/v1_CN_SampleIngest 测试 ingest 报错

1. SRS版本(Version): `release3.0

`
1. SRS的日志如下(Log):
```
[ingest_log.log](https://github.com/ossrs/srs/files/4501519/ingest_log.log)
```
1. SRS的配置如下(Config):
```
xxxxxxxxxxxx
![image](https://user-images.githubusercontent.com/27774863/79719563-6f1bd880-8311-11ea-9979-68d36886a7f8.png)

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `./configure --with-ingest && make`（示例中为“./configure --with-ffmpeg && make” 该版本提示不支持 顾用 --with-ingest）
2. `./objs/srs -c conf/ingest.conf`

**期望行为(Expect)**
正常可以从本地SRS服务器拉取到rtmp流 拉流地址为rtmp://local_ip/live/livestream
> 描述你期望发生的事情(Please describe your expectation)

**Comment by VampireCrazy** [comment]
There is no ffmpeg in the project.
Recompile and install ffmpeg, configure the correct path to resolve it.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
You can download FFmpeg from the official website of FFmpeg.

`TRANS_BY_GPT3`
