### ISSUE TITLE
Stop SRS?

### ISSUE THREAD

**Issue by IIPoliII** [ossrs/srs#1714]
I know this is a newbie question i didn't finded an except way to stop srs without killing it. 

Is it possible to stop SRS when you run it with `./objs/srs -c conf/rtmp.conf` if yes how?

**Comment by tyranron** [comment]
@IIPoliII killing process in *nix is a normal and expected way of stopping it.

**Comment by IIPoliII** [comment]
Oh i see do you have any exemple script and what do you mean by *nix? Didn't totally understood it.

Thanks for your help

**Comment by tyranron** [comment]
@IIPoliII *nix means Unix-like system: Linux, FreeBSD, macOS, etc..

If you're running SRS in terminal foreground, just press `Ctrl-c`, and it will send the appropriate signal to the SRS and it will stop.  
If you're running SRS in background, use `kill <pid-of-srs-process>` command to stop it.  
That's all!
