### ISSUE TITLE
使用 merge_nalus 无法播放

### ISSUE THREAD

**Issue by dean-river** [ossrs/srs#1732]
SrsRtcSenderThread::packet_nalus 本来是要打包多个NALU，但是里面用FU-A封装多个NALU 是不是有点矛盾啊。而且没有判断多个 NALU type 类型，直接用了第一个作为FU-A的头。
我这里测试，如果一个I帧的tag内有三个NALU（7，8，5) 这种avc3的格式，每个I帧数据前本来都带sps/pps） 接收端无法正常播放。 不使用merge_nalu 可以正常播放。

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `Release v4.0.23`
1. SRS的日志如下(Log):
```
无报错日志，显示在发送数据
![image](https://user-images.githubusercontent.com/7499154/80470893-33b68500-8975-11ea-99e6-c6e82e194797.png)

```
1. SRS的配置如下(Config):
listen              1935;
max_connections     100;
srs_log_tank        log;
daemon              off;
srs_log_file        ./objs/srs_proxy.log;
pid                 ./objs/srs.pid;
http_api {
    enabled         on;
    listen          1985;
}
rtc_server {
    enabled         on;
    listen          8000;
    candidate      $CANDIDATE;
    #merge_nalus    off; 当不配置off时，启用merge_nalus 无法播放
}
vhost __defaultVhost__ {
    rtc {
        enabled     on;
        bframe      discard;
    }
}

**重现(Replay)**

>  用srs-bench 循环推一个flv文件，该文件每个IDR tag  数据格式是 sps/pps/idr 三个NALU
chrome浏览器无法播放，firfox 只播放音频。
**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
It looks like it won't work, but actually there is no problem.

`TRANS_BY_GPT3`
