### ISSUE TITLE
SRS3.0 跨域和中文名称流无法访问问题

### ISSUE THREAD

**Issue by zywu31** [ossrs/srs#1737]
**描述(Description)**
1.SRS页面播放直播流出现跨域问题导致无法正常播放 

2.使用SRS自带http服务器点播 mp4包含中文名称 无法播放

3.srs自带的http服务器能增加hooks功能吗？ 比如我播放一个mp4影片 会通过hooks转发到cms进行鉴权 如果鉴权成功返回http状态码200      目前 rtmp/flv的on_play 和 on_stop是正常

**Comment by JalySN** [comment]
To enable cross-origin access, simply add the necessary files to the root directory.

If needed, you can add a hook call in serve_http yourself, and then cache the authentication result so that you don't have to authenticate every time.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS3 is already supported.

`TRANS_BY_GPT3`
