### ISSUE TITLE
Clear m3u8 file history

### ISSUE THREAD

**Issue by tanviralimon** [ossrs/srs#1738]
I am using SRS3 HLS. After ending a stream the server keeps history of TS file. For example, I start streaming and end at TS file stream-25.ts. When I start again, the last TS files of previous stream is also stored in the m3u8 playlist. Is it possible to reset the playlist every time I start a new stream? Because if it stores the previous ts files in the playlist file, on the live video it will show footages from previous stream.

**Comment by JalySN** [comment]
> I am using SRS3 HLS. After ending a stream the server keeps history of TS file. For example, I start streaming and end at TS file stream-25.ts. When I start again, the last TS files of previous stream is also stored in the m3u8 playlist. Is it possible to reset the playlist every time I start a new stream? Because if it stores the previous ts files in the playlist file, on the live video it will show footages from previous stream.

try add config 'hls_dispose'

**Comment by samiulhsohan** [comment]
> > I am using SRS3 HLS. After ending a stream the server keeps history of TS file. For example, I start streaming and end at TS file stream-25.ts. When I start again, the last TS files of previous stream is also stored in the m3u8 playlist. Is it possible to reset the playlist every time I start a new stream? Because if it stores the previous ts files in the playlist file, on the live video it will show footages from previous stream.
> 
> try add config 'hls_dispose'

Worked! Thanks!

**Comment by winlinvip** [comment]
@samiulhsohan 👍
