### ISSUE TITLE
Srs 3.0.139  获取流的 入口带宽 和 出口带宽  的数据异常

### ISSUE THREAD

**Issue by qisuwan** [ossrs/srs#1751]
**描述(Description)**
> 用obs推流时，只有推流的客户端在时，**入口带宽**和**出口带宽**的数据时正常的
> ![image](https://user-images.githubusercontent.com/39648761/81392910-f8287180-9151-11ea-9e68-54e7bdc26e5e.png)
> 入口带宽 在 2.5M 左右，出口带宽 在100k 左右

> 当有通过 **FLV** 通道播放此流的客户端时，这时数据就发生异常了
> ![image](https://user-images.githubusercontent.com/39648761/81393023-2efe8780-9152-11ea-98e2-ad0bb10f59d2.png)
> ![image](https://user-images.githubusercontent.com/39648761/81393064-3e7dd080-9152-11ea-9418-ed37e801df5b.png)
> **入口带宽**和**出口带宽**同时变得很大（目前都是 1.59Tbps） 都上 **T** 了，有时前面还是一个负数

1. SRS版本(Version): `3.0.139`
1. SRS的日志如下(Log):
```

```
1. SRS的配置如下(Config):
```
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
	raw_api {
        enabled             on;
        allow_reload        on;
        allow_query         on;
        allow_update        on;
    }
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    http_remux {
	enabled 	on;
	mount       	/[app]/[stream].flv;
	# hstrs       on;
    }
    hls {
	enabled		on;
    }
    dvr {
    	enabled		on;
	dvr_path	./objs/nginx/html/video/[app]/[stream]/[2006]-[01]/[02]/[timestamp].flv;
	dvr_plan	session;
	dvr_apply	all;
	dvr_duration	30;
	dvr_wait_keyframe	on;
    }

    http_hooks {
        enabled         on;
	# on_connect      http://192.168.0.250:8000/api/srs/httpHandle;
	# on_close     	http://192.168.0.250:8000/api/srs/httpHandle;
        on_publish      http://192.168.0.250:8000/api/srs/httpHandle;
        on_unpublish    http://192.168.0.250:8000/api/srs/httpHandle;
	# on_play      	http://192.168.0.250:8000/api/srs/httpHandle;
	# on_stop     	http://192.168.0.250:8000/api/srs/httpHandle;
	on_dvr		http://192.168.0.250:8000/api/srs/httpHandle;
    }
}
vhost bandcheck.srs.com {
    enabled         on;
    chunk_size      65000;
    bandcheck {
        enabled         on;
        key             "35c9b402c12a7246868752e2878f7e0e";
        interval        30;
        limit_kbps      4000;
    }
}

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `docker启动服务`
1. `obs 推流`
1. `通过 flv.js 播放流`

**期望行为(Expect)**

> 带宽正常显示

**Comment by weizhenyi** [comment]
Add kbps->remark(in, out);

`TRANS_BY_GPT3`

**Comment by qisuwan** [comment]
> Add kbps->remark(in, out);

> Do we need to modify the source code for this?

`TRANS_BY_GPT3`

**Comment by janyo1201** [comment]
May I ask, where should I make the change to add kbps->remark(in, out)?

`TRANS_BY_GPT3`

**Comment by weizhenyi** [comment]
void SrsHttpConn::remark(int64_t* in, int64_t* out)
{
// TODO: FIXME: implements it
kbps->remark(in, out);
}












































On 2020-10-28 12:16:36, "janyo1201" <notifications@github.com> wrote:


May I ask where to make the change for adding kbps->remark(in, out)?


—' translates to '—' in English.
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.


`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed

**Comment by winlinvip** [comment]
@weizhenyi 👍
