### ISSUE TITLE
Support Adaptive Bitrate with SRS

### ISSUE THREAD

**Issue by nguyenduybinh** [ossrs/srs#1764]
Hi all, I used SRS for my livestream system. SRS is so good for all. 
But 1 thing i have wondered that, why SRS doesn't support Adaptive Bitrate. It is an important feature for all livestream system.
And are there any plan for support Adaptive Bitrate with SRS in the future? Or are there any solutions to work around to support Adaptive with current SRS?
Thanks!

**Comment by nguyenduybinh** [comment]
@winlinvip do you have any comment for that issue?

**Comment by r-t-k** [comment]
Maybe even a straightforward way to output a multi bitrate m3u8 playlist from an srs instance that is ingesting several transcode instances. 

Origin --> 3 transcode servers (1080,720, and 480) --> edge (one multibitrate playlist)

**Comment by r-t-k** [comment]
@nguyenduybinh Someone figured out how to do it and I dug it up.

See the issue I created here: https://github.com/ossrs/srs/issues/1845#issue-654255515

**Comment by winlinvip** [comment]
Won't support adaptive bitrate, it will be replaced by WebRTC, or use FFmpeg to generate HLS.

**Comment by MichaelMikeJones** [comment]
@winlinvip But WebRTC can't serve a huge audience. And huge audience needs adaptive bitrate. I couldn't find a way to implement adaptive bitrate in srs with ffmpeg in a way that many streams are handled concurrently. Is there a way to achieve this?

**Comment by winlinvip** [comment]
Dup to https://github.com/ossrs/srs/issues/1845#issue-654255515
