### ISSUE TITLE
我仔细使用了SRS,也搭建起来使用了，发现推流必须依赖ffmpeg，在API 中也未发现可以使用API 实现推流动作的接口

### ISSUE THREAD

**Issue by a852203465** [ossrs/srs#1766]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `xxxxxx`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by alongL** [comment]
看我这个实现可以不？api控制的Ingest
ffmpeg 配合srs https://github.com/alongL/srs_ingest_helper/
ffmpeg 直接rtmp转hls https://github.com/alongL/rtmp2hls
