### ISSUE TITLE
srs4.0 webrtc播放dtls采用1.0的问题

### ISSUE THREAD

**Issue by kakaNeo** [ossrs/srs#1769]
**描述(Description)**
2020年，谷歌，苹果都禁用了dtls1.0了
> 描述你遇到了什么问题(Please description your issue here)
最新的ios系统和chrome内核已经无法播放webrtc
1. SRS版本(Version): `4.0.20`

**期望行为(Expect)**
希望能把dtls握手协议更新到1.2

**Comment by winlinvip** [comment]
Fixed.

`TRANS_BY_GPT3`
