### ISSUE TITLE
WebRTC无法播放，前端报错

### ISSUE THREAD

**Issue by toskeyfine** [ossrs/srs#1771]
使用GB28181的develop分支，配置如下：

>  rtc_server {
    enabled         on;
    listen          8000;
    candidate       *;
    merge_nalus     off;
}
vhost __defaultVhost__ {
    http_remux {
        enabled         on;
        mount           [vhost]/[app]/[stream].flv
    }
    rtc {
        enabled         on;
        bframe          discard;
    }
}

使用/research/players项目作为播放端，RTMP可以播放，GB28181已注册，可查询通道，但是RTC无法播放，前端报错为：

> srs_gb28181.html:1235 Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. null Expect line: v=

不知道是服务端版本有问题还是前端问题

**Comment by chygfm** [comment]
> 使用GB28181的develop分支，配置如下：
> 
> > rtc_server {
> > enabled         on;
> > listen          8000;
> > candidate       *;
> > merge_nalus     off;
> > }
> > vhost **defaultVhost** {
> > http_remux {
> > enabled         on;
> > mount           [vhost]/[app]/[stream].flv
> > }
> > rtc {
> > enabled         on;
> > bframe          discard;
> > }
> > }
> 
> 使用/research/players项目作为播放端，RTMP可以播放，GB28181已注册，可查询通道，但是RTC无法播放，前端报错为：
> 
> > srs_gb28181.html:1235 Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. null Expect line: v=
> 
> 不知道是服务端版本有问题还是前端问题

请问怎么解决的，谢谢！
