### ISSUE TITLE
API: HTTP-API read bytes : timeout 15000 ms

### ISSUE THREAD

**Issue by EchoXBR** [ossrs/srs#1777]
**描述(Description)**

1. SRS版本(Version): `3.0.139`
使用docker安装的 ossrs/srs:3
1. SRS的日志如下(Log):
```
[2020-05-22 15:45:52.381][Error][1][537][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [1][537]: do_cycle() [src/app/srs_app_http_api.cpp:1354][errno=62]
thread [1][537]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=62]
thread [1][537]: parse_message_imp() [src/service/srs_service_http_conn.cpp:156][errno=62]
thread [1][537]: grow() [src/protocol/srs_protocol_stream.cpp:179][errno=62]
thread [1][537]: read() [src/service/srs_service_st.cpp:483][errno=62](Timer expired)
[2020-05-22 15:46:22.967][Error][1][650][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
thread [1][650]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=62]
thread [1][650]: parse_message_imp() [src/service/srs_service_http_conn.cpp:156][errno=62]
thread [1][650]: grow() [src/protocol/srs_protocol_stream.cpp:179][errno=62]
thread [1][650]: read() [src/service/srs_service_st.cpp:483][errno=62](Timer expired)
```
1. SRS的配置如下(Config):
```
listen 1935;
max_connections 1000;
srs_log_tank file;
srs_log_file ./objs/srs.log;
daemon off;
http_api {
    enabled on;
    listen 1985;
    crossdomain on;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }
}
http_server {
    enabled on;
    listen 8080;
    dir ./objs/nginx/html;
}
stats {
    network 0;
    disk sda sdb xvda xvdb;
}
vhost bj.speedata.cn {
    hls {
        enabled off;
    }
    http_remux {
        enabled on;
    }
    http_hooks {
        enabled on;
        on_connect http://192.168.1.137:9004/monitor/srs/callback;
        on_close http://192.168.1.137:9004/monitor/srs/callback;
        on_publish http://192.168.1.137:9004/monitor/srs/callback;
        on_unpublish http://192.168.1.137:9004/monitor/srs/callback;
        on_dvr http://192.168.1.137:9004/monitor/srs/callback;
    }
    dvr {
       enabled on;
        dvr_apply test/333 DimensionDoor/123;
        dvr_path ./objs/nginx/html/dvr/[app]/[stream]/[2006]/[01]/[02]/[15]/[04]-[05]-[999].mp4;
        dvr_plan session;
        dvr_wait_keyframe off;
    }
```

**重现(Replay)**
服务器日志出现这个error，想知道是哪里有问题吗

**期望行为(Expect)**

没有error，或者出现error知道是为什么

**Comment by wr-ning** [comment]
I also encountered the same problem. SRS version: 3.0.139. Ubuntu 16.04 non-docker installation.
Currently, I found that whenever I access or use SRS's http_api, it will throw an error. Moreover, the error occurs 15 seconds after accessing it, just as described in the error message, it times out after 15 seconds.
As for the specific error messages related to reading or parsing messages, I don't know. I hope someone can provide an answer.
SRS log is as follows: 

> [2020-08-12 14:29:03.424][Trace][4432][466] API server client, ip=192.168.1.187
[2020-08-12 14:29:03.425][Trace][4432][466] HTTP API GET http://192.168.1.136:1985/api/v1/raw?rpc=query&scope=vhost&vhost=__defaultVhost__, content-length=-1, chunked=0/0
[2020-08-12 14:29:05.678][Trace][4432][466] HTTP API GET http://192.168.1.136:1985/api/v1/raw?rpc=query&scope=vhost&vhost=__defaultVhost__, content-length=-1, chunked=0/0
[2020-08-12 14:29:06.351][Trace][4432][466] HTTP API GET http://192.168.1.136:1985/api/v1/raw?rpc=query&scope=vhost&vhost=__defaultVhost__, content-length=-1, chunked=0/0
[2020-08-12 14:29:06.873][Trace][4432][466] HTTP API GET http://192.168.1.136:1985/api/v1/raw?rpc=query&scope=vhost&vhost=__defaultVhost__, content-length=-1, chunked=0/0
[2020-08-12 14:29:07.322][Trace][4432][466] HTTP API GET http://192.168.1.136:1985/api/v1/raw?rpc=query&scope=vhost&vhost=__defaultVhost__, content-length=-1, chunked=0/0
[2020-08-12 14:29:22.322][Error][4432][466][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [4432][466]: do_cycle() [src/app/srs_app_http_api.cpp:1354][errno=62]
thread [4432][466]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=62]
thread [4432][466]: parse_message_imp() [src/service/srs_service_http_conn.cpp:156][errno=62]
thread [4432][466]: grow() [src/protocol/srs_protocol_stream.cpp:179][errno=62]
thread [4432][466]: read() [src/service/srs_service_st.cpp:483][errno=62](Timer expired)
[2020-08-12 14:30:19.774][Trace][4432][467] API server client, ip=192.168.1.187
[2020-08-12 14:30:19.774][Trace][4432][467] HTTP API GET http://192.168.1.136:1985/api/v1/raw?rpc=query&scope=vhost&vhost=__defaultVhost__, content-length=-1, chunked=0/0
[2020-08-12 14:30:34.776][Error][4432][467][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [4432][467]: do_cycle() [src/app/srs_app_http_api.cpp:1354][errno=62]
thread [4432][467]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=62]
thread [4432][467]: parse_message_imp() [src/service/srs_service_http_conn.cpp:156][errno=62]
thread [4432][467]: grow() [src/protocol/srs_protocol_stream.cpp:179][errno=62]
thread [4432][467]: read() [src/service/srs_service_st.cpp:483][errno=62](Timer expired)
[2020-08-12 14:30:41.594][Trace][4432][468] API server client, ip=192.168.1.187
[2020-08-12 14:30:41.595][Trace][4432][468] HTTP API GET http://192.168.1.136:1985/api/v1, content-length=-1, chunked=0/0
[2020-08-12 14:30:41.646][Trace][4432][468] HTTP API GET http://192.168.1.136:1985/api/v1/, content-length=-1, chunked=0/0
[2020-08-12 14:30:56.651][Error][4432][468][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [4432][468]: do_cycle() [src/app/srs_app_http_api.cpp:1354][errno=62]
thread [4432][468]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=62]
thread [4432][468]: parse_message_imp() [src/service/srs_service_http_conn.cpp:156][errno=62]
thread [4432][468]: grow() [src/protocol/srs_protocol_stream.cpp:179][errno=62]
thread [4432][468]: read() [src/service/srs_service_st.cpp:483][errno=62](Timer expired)
[2020-08-12 14:31:55.177][Trace][4432][469] API server client, ip=192.168.1.187
[2020-08-12 14:31:55.178][Trace][4432][469] HTTP API GET http://192.168.1.136:1985/api/v1/versions, content-length=-1, chunked=0/0
[2020-08-12 14:32:10.178][Error][4432][469][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [4432][469]: do_cycle() [src/app/srs_app_http_api.cpp:1354][errno=62]
thread [4432][469]: parse_message() [src/service/srs_service_http_conn.cpp:95][errno=62]
thread [4432][469]: parse_message_imp() [src/service/srs_service_http_conn.cpp:156][errno=62]
thread [4432][469]: grow() [src/protocol/srs_protocol_stream.cpp:179][errno=62]
thread [4432][469]: read() [src/service/srs_service_st.cpp:483][errno=62](Timer expired)

SRS configuration is as follows:

> listen 1935;
max_connections 1000;
daemon off;
srs_log_tank console;
stats {
    network 0;
    disk sda sdb xvda xvdb;
}
http_api {
    enabled on;
    listen 1985;
    crossdomain on;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }
}
http_server {
    enabled on;
    listen 8080;
    dir ./objs/nginx/html;
}
vhost __defaultVhost__ {
    hls {
        enabled on;
        hls_fragment 5;
        hls_window 30;
        hls_path ./objs/nginx/html;
        hls_m3u8_file [app]/[stream].m3u8;
        hls_ts_file [app]/[stream]-[seq].ts;
    }
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    dvr {
        enabled on;
        dvr_apply test1/zhanwei;
        dvr_path ./objs/nginx/html/recorded/[app]/[stream]/[2006]/[01]/[02]/[15].[04].[05].[999].flv;
        dvr_plan session;
    }
    http_hooks {
        enabled off;
        on_connect http://127.0.0.1:8085/api/v1/clients;
        on_publish http://127.0.0.1:8085/api/v1/streams;
        on_play http://127.0.0.1:8085/api/v1/sessions;
    }
}

`TRANS_BY_GPT3`

**Comment by zh19900725** [comment]
Is the problem solved? It's exactly the same issue.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.

`TRANS_BY_GPT3`

**Comment by cochiachang** [comment]
I encountered the same problem in the latest stable version 3.0 of SRS.

`TRANS_BY_GPT3`

**Comment by yocdynyssc** [comment]
srs-200-148.log:[2021-09-03 09:05:24.592][Error][1][53805][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:05:24.824][Error][1][53797][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:05:25.048][Error][1][53780][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:05:30.903][Error][1][53816][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:05:35.987][Error][1][53823][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:06:07.472][Error][1][470][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:06:07.933][Error][1][461][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:06:14.783][Error][1][458][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:06:18.087][Error][1][464][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:06:19.486][Error][1][490][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
srs-200-148.log:[2021-09-03 09:06:19.785][Error][1][505][62] serve error code=1011 : parse message : grow buffer : read bytes : timeout 15000 ms
请问这个问题解决了吗？我现在使用的是容器版的XCORE-SRS/3.0.141(OuXuli)版本，日志中有报这个，我的现象是偶尔出现直播的视频只有声音，画面是黑屏的

**Comment by winlinvip** [comment]
This is an HTTP Client timeout, which is not an error, but the logs are quite disruptive. It has already been resolved.

`TRANS_BY_GPT3`
