### ISSUE TITLE
DVR: File is reopened and segment interrupted when stream is unpublished.

### ISSUE THREAD

**Issue by nnxiaod** [ossrs/srs#1787]
**SRS Version:**
docker ossrs/srs:3

**Description:**

**Description:**
When the segment DVR stream is interrupted and then restored, a new recording will begin. For example, if the setting is to record a segment of 600 seconds, and the stream is interrupted at 200 seconds, a 200-second MP4 file will be generated. Once the stream is restored, a new 600-second cycle will start and be written to a new temporary file. The previous cycle will no longer be 600 seconds but rather 200 seconds.

**Description:**
If two video streams are being pushed and DVR'd, and one of them experiences an interruption and restoration (which is a common occurrence due to network issues), it will trigger an "on_dvr" callback. This will result in inconsistent frequencies of "on_dvr" callbacks for the two video streams, making it impossible to correlate the two streams.

**Description:**
I looked through the previous issues and found a suggestion to divide the DVR into smaller segments and then merge them based on business logic, which is also feasible. However, I believe that the periodicity of segment DVR should not change with the variation of the stream. Although this approach can end the segment cycle ahead of time when the stream actually ends.

**Question:**
May I ask if you have considered strictly following the segment cycle for DVR regardless of the stream's impact, or perhaps adding a configuration for it?

**Expected Behavior:**

**Translation:**
'Interruptions in the stream do not affect periodic recording. The temporary file (tmp) does not change to mp4. Once the stream is restored, the unfinished period continues, and the original tmp file is written until the end of that period, at which point the mp4 file is generated.

`TRANS_BY_GPT3`

**Comment by zzugyl** [comment]
It seems like in the early versions, it was similar to what you said, but there would also be a problem: if it recovers after a 20-second interval, when replaying this video later, 20 seconds in the middle will be lost.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
You can consider how to solve it.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If need merging DVR file from different publishing session, you can use `on_hls` instead, which has involved in the Oryx feature, see [Effortless Live Stream Recording with Oryx: A Step-by-Step Guide to Server-Side Recording and AWS S3 Integration](https://blog.ossrs.io/how-to-record-live-streaming-to-mp4-file-2aa792c35b25)
