### ISSUE TITLE
srs的http_hooks只支持http，不支持https

### ISSUE THREAD

**Issue by wuzhidefeng** [ossrs/srs#1791]
srs版本：3.0release
问题：当我使用http_hooks功能，我在on_dvr里面如果指定http的地址是没有问题的，但是我如果指定https的地址，我会收到这样的回应：
|<html>
|<head><title>301 Moved Permanently</title></head>
|<body bgcolor="white">
|<center><h1>301 Moved Permanently</h1></center>
|<hr><center>nginx/1.12.2</center>
|</body>
|</html>
请问怎么样可以在http_hooks里使用https的回调。
我的配置文件如下：
http_hooks {
		
                         enabled         on;
			on_dvr          https://xxxxxx/api/historyVideo/upload;
		}

**Comment by misterpancn** [comment]
I also met this issue. Have you solved it?

**Comment by wuzhidefeng** [comment]
> I also met this issue. Have you solved it?

I modified the code of srs by myself.

**Comment by misterpancn** [comment]
@wuzhidefeng  Are you modifying the source code directly?

**Comment by wuzhidefeng** [comment]
> @wuzhidefeng Are you modifying the source code directly?

Yes,the source code looks like doesn't support https.

**Comment by winlinvip** [comment]
Dup to #1657

**Comment by winlinvip** [comment]
Fixed in https://github.com/ossrs/srs/issues/1657#issuecomment-722971676
