### ISSUE TITLE
SRS的“SRS主动拉流”接入方式是否可以根据客户使用进行接入

### ISSUE THREAD

**Issue by ymd228** [ossrs/srs#1792]
应用场景：srs通过主动拉流方式获取NVR中通道的rtsp流。用户使用rtmp协议拉流，当用户停止拉流时（超过某个时间没有向服务器发起请求）srs服务器主动断开与NVR的通道连接。
请问srs是否支持上述功能？

**Comment by chatop2020** [comment]
You can use the on_stop event of http_hooks to achieve this. When this event occurs, you can stop the ingest. There is also an on_play event, where you can restart the ingest when it happens. However, I haven't tried this approach before, so I'm not sure if it will work or not.

`TRANS_BY_GPT3`

**Comment by ymd228** [comment]
> You can do this by using the on_stop event of http_hooks. When this event occurs, you can stop the ingest. There is also an on_play event where you can restart the ingest when it occurs. However, I haven't tried this method before, so I'm not sure if it will work or not.

I have tested it, but it doesn't work. The camera and SRS server are still continuously sending and receiving packets. Even when configured in pull mode, the packets are still being sent and received. The configuration in srs.conf is as follows:
vhost __defaultVhost__ {
mode         remote;
origin       172.16.1.44:1935;

http_hooks {
        enabled         on;
        on_connect      http://127.0.0.1:8085/api/v1/clients;
        on_close        http://127.0.0.1:8085/api/v1/clients;
        on_publish      http://127.0.0.1:8085/api/v1/streams;
        on_unpublish    http://127.0.0.1:8085/api/v1/streams;
        on_play         http://127.0.0.1:8085/api/v1/sessions;
        on_stop         http://127.0.0.1:8085/api/v1/sessions;
    }

ingest 1115 {
        enabled      on;
        input {
            type    stream;
            url     rtsp://172.16.1.115:554/live/main; 
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          off;
            output          rtmp://127.0.0.1:1935/live/1115;
        }
    }


    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }

} 

Start the built-in interface server.
python research/api-server/server.py 8085

`TRANS_BY_GPT3`

**Comment by lanyan90** [comment]
> 
> 
> Application scenario: SRS retrieves the RTSP stream of channels in NVR through active pulling. Users use the RTMP protocol to pull the stream. When the user stops pulling the stream (no request sent to the server for a certain period of time), the SRS server actively disconnects the channel connection with NVR.
> May I ask if SRS supports the above function?

I also encountered the same problem. May I ask if you have resolved this issue?

`TRANS_BY_GPT3`

**Comment by ymd228** [comment]
> > 应用场景：srs通过主动拉流方式获取NVR中通道的rtsp流。用户使用rtmp协议拉流，当用户停止拉流时（超过某个时间没有向服务器发起请求）srs服务器主动断开与NVR的通道连接。
> > 请问srs是否支持上述功能？
> 
> 我也遇到了同样的问题，请问您是否解决了这个问题？
没有找到特别好的方式，现在打算采用：
a.保留srs的正常安装，不修改任何的配置；
b.使用时启动ffmpeg进行推流操作，不使用时就不做推流操作。

**Comment by ymd228** [comment]
> > Application scenario: SRS actively pulls the RTSP stream from the channels in the NVR. Users use the RTMP protocol to pull the stream. When the user stops pulling the stream (no request sent to the server for a certain period of time), the SRS server actively disconnects the channel connection with the NVR.
> > May I ask if SRS supports the above functionality?
> 
> I also encountered the same problem. May I ask if you have resolved this issue?

I haven't found a particularly good solution yet. Now I plan to adopt:
a. Keep the normal installation of SRS without modifying any configurations;
b. Start ffmpeg for streaming operations when needed, and stop streaming operations when not in use.

`TRANS_BY_GPT3`

**Comment by alongL** [comment]
这个需求不是跟zlmedia一样吗？
please try  https://github.com/xia-chu/ZLMediaKit

**Comment by alongL** [comment]
看我这个实现可以不？
ffmpeg 配合srs  https://github.com/alongL/srs_ingest_helper/  
ffmpeg 直接rtmp转hls  https://github.com/alongL/rtmp2hls

**Comment by alongL** [comment]
srs streaming assistant, do it yourself, don't rely on others.
https://github.com/alongL/srs_ingest_helper

`TRANS_BY_GPT3`

**Comment by skilyxx** [comment]
Our application scenario is consistent with this, which means that the stream is only pulled from the NVR to SRS when the client wants to watch it. If no one is watching, it will be turned off. This is how we handle it: we receive the "on_play" event and start the FFmpeg streaming process in the "on_play" event. We receive the "on_stop" event and check if there are any clients watching the video through the client interface. If there are none, we close the streaming process. There may be multiple processes streaming at the same time, so we need to manage the FFmpeg streaming processes ourselves.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The business system is handled quite well.

`TRANS_BY_GPT3`
