### ISSUE TITLE
关于TS Demux的几个问题

### ISSUE THREAD

**Issue by jo-qzy** [ossrs/srs#1795]
我这个菜逼最近在学习SRT TS解包转换为RTMP的时候，读了下ts_demux的代码，虽然无伤大雅，但是我感觉还是处理的有问题。。。尽管不影响功能，还是想提出来。。

第一个是这里：

https://github.com/ossrs/srs/blob/4.0release/trunk/src/srt/ts_demux.hpp#L144

结果在ts_demux.cpp中的注释还是写了的，应该是施维老师写漏了

https://github.com/ossrs/srs/blob/4.0release/trunk/src/srt/ts_demux.cpp#L139

这个结构体里面按照T-REC-H.222.0-200002这个PDF里面写的话，应该还有个marker_bit3，但是结构体中没有。。虽然不影响

还一个是这里：

https://github.com/ossrs/srs/blob/4.0release/trunk/src/srt/ts_demux.cpp#L108

这里private_data_byte读走了一部分数据，那么是不是应该

```c++
pos += _transport_private_data_length
```

但是pos好像并没有增加。。

好吧，并不影响ts解包转换成rtmp包进行传输，但是看到了就想提出来

**Comment by winlinvip** [comment]
Great, you can submit a PR.

`TRANS_BY_GPT3`

**Comment by chen-guanghua** [comment]
https://github.com/ossrs/srs/pull/2066


Already merged into 4.0 release

`TRANS_BY_GPT3`

**Comment by chen-guanghua** [comment]
https://github.com/ossrs/srs/pull/2066

已合入
