### ISSUE TITLE
make error on srs_kernel_utility

### ISSUE THREAD

**Issue by laurfb** [ossrs/srs#1800]
Hi. Got error on make (Line 128 on srs_kernel_utility.cpp):
...
g++ -c -ansi -Wall -g -O0 \
-Isrc/kernel -Isrc/core -Iobjs \
-o objs/src/kernel/srs_kernel_utility.o src/kernel/srs_kernel_utility.cpp
src/kernel/**srs_kernel_utility.cpp:128:43**: **error: invalid conversion from ‘int (*)(timeval*, void*) throw ()’ {aka ‘int (*)(timeval*, void*)’} to ‘_srs_gettimeofday_t’ {aka ‘int (*)(timeval*, timezone*)’} [-fpermissive]**
128 | _srs_gettimeofday_t _srs_gettimeofday = ::gettimeofday;
| ~~^~~~~~~~~~~~
| |
| int (*)(timeval*, void*) throw () {aka int (*)(timeval*, void*)}
make[2]: *** [objs/Makefile:77: objs/src/kernel/srs_kernel_utility.o] Error 1
...
SRS Version): 3.0release/4.0release, Ubuntu

regards,
Laur

**Comment by vsyf** [comment]
diff --git a/trunk/src/kernel/srs_kernel_utility.hpp b/trunk/src/kernel/srs_kernel_utility.hpp
index 8dc54894..abf95a2e 100644
--- a/trunk/src/kernel/srs_kernel_utility.hpp
+++ b/trunk/src/kernel/srs_kernel_utility.hpp
@@ -169,7 +169,7 @@ extern int srs_chunk_header_c3(int perfer_cid, uint32_t timestamp, char* cache,
 #ifdef SRS_OSX
     #define _srs_gettimeofday gettimeofday
 #else
-    typedef int (*_srs_gettimeofday_t) (struct timeval* tv, struct timezone* tz);
+    typedef int (*_srs_gettimeofday_t) (struct timeval* tv, void* tz);
 #endif
 
 #endif

**Comment by winlinvip** [comment]
Fixed, thanks @vsyf
