### ISSUE TITLE
运行./objs/srs -c conf/srt.conf报错

### ISSUE THREAD

**Issue by Alexyali** [ossrs/srs#1802]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
运行./objs/srs -c conf/srt.conf报错
1. SRS版本(Version): `srs 3.0`
1. SRS的日志如下(Log):
```
[2020-06-10 07:52:25.070][Error][6436][0][0] Failed, code=1023 : check config : check normal : illegal directive srt_server
thread [6436][0]: do_main() [src/main/srs_main_server.cpp:175][errno=0]
thread [6436][0]: check_config() [src/app/srs_app_config.cpp:3455][errno=0]
thread [6436][0]: check_normal_config() [src/app/srs_app_config.cpp:3494][errno=0]
```
1. SRS的配置如下(Config):

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

按照文档说的步骤来，进行到./objs/srs -c conf/srt.conf出错

**Comment by workplaylifecycle** [comment]
报错提示已经很明确了。非法的(配置)指令`srt_server`
[srt_server](https://github.com/ossrs/srs/search?q=srt_server&unscoped_q=srt_server)这个配置指令是不存在的
[max_connections](https://github.com/ossrs/srs/search?q=max_connections&unscoped_q=max_connections) 存在的指令类似这样
另外，代码行数已经给出，可以看到对应代码的意图

**Comment by onlinewan** [comment]
我也遇到了这个问题，不是宣称支持srt了吗？为什么实际没有支持呢
取的最新代码，看了一下代码，也没有找到srt相关的部分

@winlinvip

**Comment by lisafei** [comment]
srs 4.0 release
