### ISSUE TITLE
是否支持采集RTSP流输出http flv流？

### ISSUE THREAD

**Issue by luoxurobert** [ossrs/srs#1808]
希望能主动拉取rtsp流后，输出成http flv流，而非默认的rtmp流。

**Comment by luoxurobert** [comment]
已解决

**Comment by yongjianglong** [comment]
兄台，怎么解决的？

**Comment by luoxurobert** [comment]
在外面套一个hlv配置，配置参考如下：
listen 1935;
max_connections 1000;
http_server {
    enabled on;
    listen 8080;
    dir ./objs/nginx/html;
}
stats {
    network 0;
    disk sda sdb xvda xvdb;
}
http_api {
    enabled on;
    listen 1985;
    crossdomain on;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }
}
vhost __defaultVhost__ {
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }
    ingest {
        enabled on;
        input {
            type stream;
            url rtsp://........;
        }
        ffmpeg ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled on;
            perfile {
                rtsp_transport tcp;
            }
            vcodec copy;
            acodec copy;
            output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
}
vhost ossrs.net {
    enabled on;
}

**Comment by luoxurobert** [comment]
在外面套一层hlv配置：
listen 1935;
max_connections 1000;
http_server {
enabled on;
listen 8080;
dir ./objs/nginx/html;
}
stats {
network 0;
disk sda sdb xvda xvdb;
}
http_api {
enabled on;
listen 1985;
crossdomain on;
raw_api {
enabled on;
allow_reload on;
allow_query on;
allow_update on;
}
}
vhost defaultVhost {
http_remux {
enabled on;
mount [vhost]/[app]/[stream].flv;
}
ingest {
enabled on;
input {
type stream;
url rtsp://........;
}
ffmpeg ./objs/ffmpeg/bin/ffmpeg;
engine {
enabled on;
perfile {
rtsp_transport tcp;
}
vcodec copy;
acodec copy;
output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
}
}
}
vhost ossrs.net {
enabled on;
}

**Comment by yuezhilanyi** [comment]
@luoxurobert 
请问http-flv流的地址是多少？
rtmp地址是 rtmp://127.0.0.1:1935/live/test?vhost=defaultVhost ，可以正常播放 
http地址我试了 http://127.0.0.1:8080/live/test.flv?vhost=defaultVhost 以及http://127.0.0.1:8080/live/test?vhost=defaultVhost.flv 都不能播放

could you tell me the url of http-flv stream?
the rtmp url could be played successfully rtmp://127.0.0.1:1935/live/test?vhost=defaultVhost, while the http-flv url not.
i have tried 
http://127.0.0.1:8080/live/test.flv?vhost=defaultVhost
and 
http://127.0.0.1:8080/live/test?vhost=defaultVhost.flv

**Comment by zhouweiwei-design** [comment]
你好，采集rtsp流输出http-flv流，你的http-flv流地址是怎么组成的？
