### ISSUE TITLE
User interface customization(用戶界面定制) 

### ISSUE THREAD

**Issue by eaba** [ossrs/srs#1818]
Is it possible to customize the front end - research/api-server or research/players?
是否可以自定義前端-研究/ API服務器或研究/玩家？

Can I use angular for the front instead  - research/api-server or research/players?
我可以改用angular作為前端嗎-研究/ api服務器或研究/玩家？

I appreciate the hard-work you have put into this.
我感謝您為此付出的辛勤工作。

**Comment by chatop2020** [comment]
you can focus on the open source project srsmanager

**Comment by eaba** [comment]
Hey @chatop2020 thanks a lot for that project - you have done well!
