### ISSUE TITLE
http api 关于 vhost的配置修改的支持

### ISSUE THREAD

**Issue by luoxurobert** [ossrs/srs#1820]
**描述(Description)**
我在使用srs做流媒体服务器，我有1000个摄像头，希望可以动态指定srs拉取指定摄像头的rtsp流，我查找api并不支持传入参数控制当前拉取的流。

1. SRS版本(Version): `4.0`

**期望行为(Expect)**
希望大佬能在http api中支持修改vhost节点中的每个参数，这样我可以控制srs流服务器拉流

**Comment by winlinvip** [comment]
可以自己用FFmpeg灵活的拉。
