### ISSUE TITLE
GB28181: http-callback 功能无效，无法触发回调

### ISSUE THREAD

**Issue by limjoe** [ossrs/srs#1822]
Migrate to https://github.com/ossrs/srs-gb28181/issues/17

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by limjoe** [comment]
After the branch author's confirmation, the new version has been changed to directly process the source without triggering any events.

The temporary solution is to change the code from `source_publish=true` to `source_publish=false`.

After recompiling, the functionality is working properly.

`TRANS_BY_GPT3`

**Comment by chatop2020** [comment]
> After the branch author's confirmation, the new version has been changed to directly handle the source without triggering events.
> 
> The temporary solution is to change the code `source_publish=true` to `source_publish=false`.
> 
> After recompiling, the functionality is working properly.

> Brother, is your program not running properly? I am using the latest code here, enabling DVR to record MP4, but the program keeps crashing.

`TRANS_BY_GPT3`

**Comment by fffxiang** [comment]
> After the branch author's confirmation, the new version has been changed to directly handle the source without triggering events.
> 
> The temporary solution is to change the code `source_publish=true` to `source_publish=false`.
> 
> After recompiling, the functionality is working properly.

> Brother, where is this `source_publish=true` located?

`TRANS_BY_GPT3`

**Comment by fffxiang** [comment]
> After the branch author's confirmation, the new version was changed to directly handle the source without triggering an event.
> The temporary solution is to change the code `source_publish=true` to `source_publish=false`.
> After recompiling, the functionality works properly.
> 
> Brother, is your program not running properly? I am using the latest code here, with DVR enabled to record MP4, but the program keeps crashing.

> Brother, where can I find the `source_publish=true`?

`TRANS_BY_GPT3`

**Comment by limjoe** [comment]
@fffxiang, in the file srs/trunk/src/app/srs_app_gb28181.cpp, you can find the code by searching for source_publish. It seems that the author has not fixed it yet.

`TRANS_BY_GPT3`

**Comment by lauix** [comment]
@winlinvip Is this issue still not fixed? I found this problem still exists when connecting to the Hikvision camera, and the source_publish=true is already in the source code.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/17

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
