### ISSUE TITLE
我的实际网络环境  网络不稳定 （船端网络无法改变）推流容易中断 需要调啥参数

### ISSUE THREAD

**Issue by chinasoftsky** [ossrs/srs#1823]
**描述(Description)**
网络不稳定 rtmp 推流 容易中断 调大超时时间可以解决吗？
> 描述你遇到了什么问题(Please description your issue here)
我的实际网络环境  网络不稳定 （无法改变）推流容易中断 需要调啥参数
1. SRS版本(Version): `xxxxxx`

**Comment by alongL** [comment]
Feel free to use proxies like kcptun for transmission.

`TRANS_BY_GPT3`

**Comment by alongL** [comment]
In this unstable network environment, TCP is prone to frequent reconnections, so UDP is needed for low-level transmission. The kcptun proxy is the simplest solution. No development is required, just bring it over and it can be used directly.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
WebRTC streaming is UDP-based.

`TRANS_BY_GPT3`
