### ISSUE TITLE
SRS RTC AAC resample error

### ISSUE THREAD

**Issue by tany0007** [ossrs/srs#1824]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

用ffmpeg 推流到SRS後, 使用SRS RTC Player播放, 有時會有嚴重的雜音

SRS version:
```
branch feature/rtc  1343d4f6056d9cb17a20c05c5daf886a3d0c86c0
```

SRS config:
```
listen              1935;
max_connections     1000;
srs_log_tank        console;
srs_log_file        ./objs/srs.log;
daemon              off;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled         on;
    listen          8000;
    candidate       127.0.0.1;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        bframe      discard;
    }
}

```

**重现(Replay)**

1. `ffmpeg -re -ss 190 -i /c/work/docker_share/sample/TearsOfSteel_1280x534.mp4 -c:v h264 -c:a aac -ac 2 -ar 44100 -b:a 64k -aac_pred 1 -f flv rtmp://127.0.0.1:1935/live/livestream`
2. `用SRS RTC Player 播放 webrtc://127.0.0.1/live/livestream`
3. `中斷ffmpeg, 推另外一個stream到SRS, ffmpeg -re -ss 190 -i /c/work/docker_share/sample/TearsOfSteel_1280x534.mp4 -c:v h264 -c:a aac -ac 2 -ar 44100 -b:a 64k -aac_pred 1 -f flv rtmp://127.0.0.1:1935/live/livestream2`
4. `用SRS RTC Player 播放 webrtc://127.0.0.1/live/livestream2`
5. `這時有比較大的機率會有雜音`

**期望行为(Expect)**

> 正常播放沒有雜音

**Reference**
SRS 在RTC模式下, 會decode streaming來的aac audio, decode成pcm, resample pcm, 在encode成opus, 不過在decode到buffer時, 會使用non-planar audio的方式做memcpy (trunk/src/app/srs_app_rtc_codec.cpp : line 122)
```
        for (int i = 0; i < frame_->nb_samples; i++) {
            if (size + pcm_size * codec_ctx_->channels <= max) {
                memcpy(buf + size,frame_->data[0] + pcm_size*codec_ctx_->channels * i, pcm_size * codec_ctx_->channels);
                size += pcm_size * codec_ctx_->channels;
            }
        }
```
但ffmpeg-4.x版本aac decode出來是planar(AV_SAMPLE_FMT_FLTP), data會放在 frame_->extended_data[0] & frame_->extended_data[1] (for each channel), 不正確的decoded data input導致後面resample時, 出來的結果會有錯誤的情況發生, 附上一個非常陽春架構不漂亮的修正檔給作者做修正的參考, 謝謝

[mypatch.zip](https://github.com/ossrs/srs/files/4845038/mypatch.zip)

**Comment by johnlanz** [comment]
I experienced this error using obs, there's really serious noise on playback.
Your patch is really working. you should add a pull request to it

**Comment by tany0007** [comment]
Thanks for you testing, there is the pull request #1831 .

**Comment by winlinvip** [comment]
@tany0007 Good job!

**Comment by winlinvip** [comment]
Fixed
