### ISSUE TITLE
如何在android手机上搭建srs流媒体服务器

### ISSUE THREAD

**Issue by TBoyLi** [ossrs/srs#1825]
**期望行为(Expect)**

> 想在android手机上搭建srs流媒体服务器，改如何实现？

**Comment by huanghe2015** [comment]
Get to know about Linux terminal emulators (such as Termux).

`TRANS_BY_GPT3`

**Comment by hanklee9820** [comment]
@huanghe2015 Can the source code be packaged into an SDK and run on an Android device without using a Linux terminal emulator?

`TRANS_BY_GPT3`

**Comment by huwenkai26** [comment]
> @huanghe2015 Can the source code be packaged into an SDK and run on an Android device without using a Linux terminal emulator?
It might be difficult to create an SDK, but it should be possible to make it into an executable ARM program on Android.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Small scene, figure it out yourself.

`TRANS_BY_GPT3`

**Comment by it206it** [comment]
> **Expected Behavior**
> 
> > How can I set up an SRS streaming media server on an Android phone?

Has the issue been resolved? I also want to implement a streaming media server on Android.

`TRANS_BY_GPT3`
