### ISSUE TITLE
使用sys-librtmp 推流到阿里的rtmp服务上，崩溃

### ISSUE THREAD

**Issue by starhan** [ossrs/srs#1835]
**描述(Description)**
使用sys-librtmp推流到阿里的rtmp服务，端上程序崩溃

> 描述你遇到了什么问题(Please description your issue here)

1. 用的sys-librtmp的master分支（最近几天的）
1. 前面的建立连接包括handshake都是正常的，推送音视频（音频aac，视频h264）数据到阿里rtmp服务，推送部分数据（几秒钟的数据)后，推流程序崩溃。
代码简洁如下：
建立连接：
    mSender = srs_rtmp_create(mParam.url);
    if (srs_rtmp_handshake(mSender) != 0) {
        return false;
    }   
    if (srs_rtmp_connect_app(mSender) != 0) {
        return false;
    }   
    if (srs_rtmp_publish_stream(mSender) != 0) {
        return false;
    }  
推流：
bool SendRtmp::sendRtmp(int msgType, char* data, int len, int64_t tl)
{
    if (msgType == MSG_CMP_VIDEO_H264) {
        if (!srs_h264_write_raw_frames(mSender, data, len, tl, tl)) {
            return true;
        }
    } else if (msgType == MSG_CMP_AUDIO_AAC_ADTS) {
        if (!srs_audio_write_raw_frame(mSender, 10, 3, 1, 0, data, len, tl)) {
            return true;
        }
    }
    return false;
}

请帮忙看下问题处在哪里，谢谢！

**Comment by starhan** [comment]
The data pushed is saved as local files in audio and video format, which can be played using ffmpeg. The audio is in AAC format with ADTS header.

`TRANS_BY_GPT3`

**Comment by starhan** [comment]
No one responded for three days, thank you!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
srs-librtmp is no longer supported, use ffmpeg instead.

`TRANS_BY_GPT3`
