### ISSUE TITLE
For HLS Adaptive Bitrate, add this to HLS docs

### ISSUE THREAD

**Issue by r-t-k** [ossrs/srs#1845]
For people how needs this feature: you can realize this now already with srs:
-   prepare your __defaultVhost__ with transcoding:
```
transcode live/stream {
        enabled     on;
        ffmpeg      /usr/local/bin/ffmpeg;
        engine half {
            enabled         on;
            iformat         live_flv;
            vfilter {
                v           quiet;
            }

            vcodec          libx264;
            vfps            25;
            vwidth          512;
            vheight         288;
            vprofile        main;
            vpreset         medium;

            vparams {
                crf         23;
                x264opts    keyint=50:min-keyint=50:no-scenecut;
                maxrate     650k;
                bufsize     1300k;
            }

            acodec          copy;
            oformat         flv;
            output          rtmp://localhost:1935/live/half;
        }
    }

    hls {
        enabled         on;
        hls_path        /var/www/srs/live;
        hls_fragment    6;
        hls_window      1800;
        hls_cleanup     on;
        hls_dispose     5;
        hls_m3u8_file   [stream]_hq.m3u8;
        hls_ts_file     [stream]_hq-[seq].ts;
    }
```
- then add a second vhost for localhost and add there a new hls statement:
```
    hls {
        enabled         on;
        hls_path        /var/www/srs/live;
        hls_fragment    6;
        hls_window      1800;
        hls_cleanup     on;
        hls_dispose     5;
        hls_m3u8_file   [stream]_lq.m3u8;
        hls_ts_file     [stream]_lq-[seq].ts;
    }
```

- then create a master.m3u8:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:15
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2149280,CODECS="mp4a.40.2,avc1.64001f",RESOLUTION=1024x576,NAME="1024"
live/stream_hq.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=460560,CODECS="mp4a.40.5,avc1.420016",RESOLUTION=512x288,NAME="512"
live/half_lq.m3u8
```
- set the correct `BANDWIDTH`

If you need more resolutions just add in transcode more outputs under `vparams`, maybe like this:

```
...
s           1024x576;
crf         23;
x264opts    keyint=50:min-keyint=50:no-scenecut;
maxrate     1300k;
bufsize     2600k;
f           flv;
c:a         copy;
y           rtmp://127.0.1.1:1935/live/big;
crf         23;
x264opts    keyint=50:min-keyint=50:no-scenecut;
maxrate     650k;
bufsize     1300k;
...
```

and add more **vhosts**.

Here is a working [gist](https://gist.github.com/jb-alvarado/1e94e313b57caf225127f80812fbd896)

_Originally posted by @jb-alvarado in https://github.com/ossrs/srs/issues/463#issuecomment-502011374_

**Comment by johnlanz** [comment]
this kind of transcoding uses ffmpeg which uses a lot of cpu. Mine consumes 200% cpu from livestream.
is there a way to make it use less cpu like less than 10% just like what srs did when converting to hls?

**Comment by r-t-k** [comment]
As far as I know, to resize and transcode, you need to use ffmpeg with srs. I might be missing something, but I've searched for a solution for a while, and this is the only thing that actually works.

'
Make sure to maintain the markdown structure.
Let me know if you find an alternative.
On Jul 9, 2020, 10:02 PM -0500, John Laniba <notifications@github.com>, wrote:
> this kind of transcoding uses ffmpeg which uses a lot of cpu. Mine consumes 200% cpu from livestream.
> is there a way to make it use less cpu like less than 10% just like what srs did when converting to hls?
> —'
Make sure to maintain the markdown structure.
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

`TRANS_BY_GPT3`

**Comment by jb-alvarado** [comment]
> is there a way to make it use less cpu maybe less than 10% just like what srs did when converting to hls?

srs is not transcoding to hls, it just copy the stream to a new container. The same would happen, when you use stream copy in ffmpeg, but as soon as you want to change to resolution you have to re-encode the stream and of course this uses more cpu power. There is no cheaper way.

**Comment by winlinvip** [comment]
Good job!

**Comment by cristiAndreiTarasi** [comment]
I may be a little late to the party, but I found this related to SRS configs, where great detail about transcoding can be found. The link is [all SRS configs](https://www.cnblogs.com/wmzll/p/17022506.html). I hope it helps everyone.
