### ISSUE TITLE
GB28181: 段错误（吐核）

### ISSUE THREAD

**Issue by 21877575** [ossrs/srs#1855]
**描述(Description)**

SRS服务报错，段错误（吐核）

1. SRS版本(Version): 4.0
1. SRS的日志如下(Log):
![image](https://user-images.githubusercontent.com/44058715/87649523-fe0a8680-c782-11ea-9a39-4df7425a104e.png)
1. SRS的配置如下(Config):
# push gb28181 stream to SRS.

listen                  1935;
max_connections         1000;
daemon                  off;
#srs_log_tank            console;
srs_log_level           trace;
srs_log_tank            file;
srs_log_file          ./objs/srs.log;

http_api {
    enabled         on;
    listen          1985;
}   

stats {
    network         0;
}

stream_caster {
    enabled             on;
    caster              gb28181;

    # 转发流到rtmp服务器地址与端口
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400875104
    # [stream] is VideoChannelCodecID(视频通道编码ID) for sip
    # 自动创建的道通[stream] 是‘chid[ssrc]’ [ssrc]是rtp的ssrc
    # [ssrc] rtp中的ssrc
    output              rtmp://13.32.203.100:1935/live/[stream];
    
    # 接收设备端rtp流的多路复用端口
    listen              9000;

    # rtp接收监听端口范围，最小值
    rtp_port_min        58200;
    # rtp接收监听端口范围，最大值
    rtp_port_max        58300;

    # 是否等待关键帧之后，再转发，
    # off:不需等待，直接转发
    # on:等第一个关键帧后，再转发
    wait_keyframe       on;
    
    # rtp包空闲等待时间，如果指定时间没有收到任何包
    # rtp监听连接自动停止，发送BYE命令
    rtp_idle_timeout    60;

    # 是否转发音频流
    # 目前只支持aac格式，所以需要设备支持aac格式
    # on:转发音频
    # off:不转发音频，只有视频
    # *注意*!!!:flv 只支持11025  22050  44100 三种
    # 如果设备端没有三种中任何一个，转发时为自动选择一种格式
    # 同时也会将adts的头封装在flv aac raw数据中
    # 这样的话播放器为自动通过adts头自动选择采样频率
    # 像ffplay, vlc都可以，但是flash是没有声音，
    # 因为flash,只支持11025 22050 44100
    audio_enable        off;

    # 是否开启rtp缓冲
    # 开启之后能有效解决rtp乱序等问题
    jitterbuffer_enable  on;

    # 服务器主机号，可以域名或ip地址
    # 也就是设备端将媒体发送的地址，如果是服务器是内外网
    # 需要写外网地址，
    # 调用api创建stream session时返回ip地址也是host
    # $CANDIDATE 是系统环境变量，从环境变量获取地址，如果没有配置，用*
    # *代表指定stats network 的网卡号地址，如果没有配置network，默认则是第0号网卡地址
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400917594
    host       13.32.203.100;

    #根据收到ps rtp包自带创建rtmp媒体通道，不需要api接口创建
    #rtmp地址参数[stream] 就是通道id  格式chid[ssrc]
    auto_create_channel   on;

    sip {
        # 是否启用srs内部sip信令
        # 为on信令走srs, off 只转发ps流
        enabled on;
        
        # sip监听udp端口
        listen              5060;
        
        # SIP server ID(SIP服务器ID).
        # 设备端配置编号需要与该值一致，否则无法注册
        serial              13010100002000000126;

        # SIP server domain(SIP服务器域)
        realm               1301010000;

        # 服务端发送ack后，接收回应的超时时间，单位为秒
        # 如果指定时间没有回应，认为失败
        ack_timeout         60;

        # 设备心跳维持时间，如果指定时间内(秒）没有接收一个心跳
        # 认为设备离线
        keepalive_timeout   120;

        # 注册之后是否自动给设备端发送invite
        # on: 是  off 不是，需要通过api控制
        auto_play           on;
        # 设备将流发送的端口，是否固定
        # on 发送流到多路复用端口 如9000
        # off 自动从rtp_mix_port - rtp_max_port 之间的值中
        # 选一个可以用的端口
        invite_port_fixed     on;

        # 向设备或下级域查询设备列表的间隔，单位(秒)
        # 默认60秒
        query_catalog_interval  60;
    }
}
rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    candidate       13.32.203.100;
}
vhost __defaultVhost__ {
    rtc {
           enabled     on;
           bframe      discard;
    }
}

**重现(Replay)**

1、GB28181
2、webrtc播放

**期望行为(Expect)**
看到更详细日志，知道错误原因，不让SRS服务挂掉

**Comment by xialixin** [comment]
Please use the latest version srs4.0.32 or above.

`TRANS_BY_GPT3`

**Comment by huxiaochao1995** [comment]
Hello, may I ask if you have resolved it? I also have the same issue. Mine is version 4.0.35.

`TRANS_BY_GPT3`

**Comment by huhu123456789** [comment]
![ZQ}V E6HID`~3@K5I `FFC0](https://user-images.githubusercontent.com/38453192/87894045-36a4ab80-ca74-11ea-8d32-584febf0b161.png)

**Comment by xialixin** [comment]
@huhu123456789 You may have some different issues with them

`TRANS_BY_GPT3`

**Comment by huhu123456789** [comment]
哦哦厦工,能加个qq，远程帮忙看一下吗这个问题困扰了好久
我这里就这两个问题。

**Comment by huhu123456789** [comment]
1042018884

**Comment by huxiaochao1995** [comment]
@xialixin Oh, can you add me on QQ? Help me remotely and guide me. 1042018884

`TRANS_BY_GPT3`

**Comment by xialixin** [comment]
》gdb objs/srs
 》 run -c conf/push.gb28181.conf
If it crashes, use `bt` to check the log, then take a screenshot.

`TRANS_BY_GPT3`

**Comment by huxiaochao1995** [comment]
@xialixin Okay Xiaogong, sorry for the delay, I just saw it after many days. I'll give it a try.

`TRANS_BY_GPT3`

**Comment by qqtian01** [comment]
GB28181 海康推流，如果音频是G711，会出现错误：段错误（吐核）

**Comment by winlinvip** [comment]
Fixed?

`TRANS_BY_GPT3`
