### ISSUE TITLE
docker镜像有gb28181版本的吗？

### ISSUE THREAD

**Issue by KlayerCong** [ossrs/srs#1857]
我这边使用的是docker环境部署对接gb28181协议，但docker仓库拉下来的默认都是不支持GB28181的。一种解决方案是你们提供的：拉取28181版本分支代码进行编译安装。想问下没有直接支持gb28181版本的docker镜像吗？
<img width="443" alt="微信截图_20200717152450" src="https://user-images.githubusercontent.com/38915339/87760005-bac31d00-c841-11ea-9d21-ef50c78ee158.png">

**Comment by jxyk2007** [comment]
Make your own Docker image. Or load your own configuration when starting Docker in /root/srs/trunk/conf/push.gb28181.conf.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
You can build upon this: https://github.com/ossrs/srs-docker

`TRANS_BY_GPT3`
