### ISSUE TITLE
RTMP protect publication

### ISSUE THREAD

**Issue by GNURub** [ossrs/srs#1863]
Could the transmission key be different than the display name? to protect streming using rtmp.

It could be implemented through a symmetric encryption algorithm (AES, 3DES, ...), through a secret in the config.

Example:
Algorithm: AES
Secret: nhI1OhfHgnY7Hvxu
Stream Name: livestream
Server RTMP: rtmp://localhost:1935/live/
RTMP Key: uF1qtlPglQ2q9wE/UAbOXe9s7iHGBMYL70dTiJs6/ihy93Xc6TyRrUovn3YqBm1M
Streaming Url: http://localhost:8080/live/livestream.flv

**Comment by RocFang** [comment]
you can always do such things through http callback like on_publish and on_play.

**Comment by GNURub** [comment]
Thanks! I did an api that return json with code != 0 if key is not valid.
