### ISSUE TITLE
服务端如何断开正在推流的某个客户端连接？

### ISSUE THREAD

**Issue by alun0829** [ossrs/srs#1870]
大神您好，有个问题想咨询下：
场景：某客户端正在推送RTMP视频到SRS服务端，一段时间后，服务端想主动断开此客户端，应该调用哪个类的哪个方法，才能最干净的断开连接并清理此连接相关数据呢？

**Comment by JalySN** [comment]
把recvthread 的cycle break

**Comment by alun0829** [comment]
> 把recvthread 的cycle break

谢大神解答。我的意思是：如何从外部调用断开一个SrsRtmpConn连接？比如：
