### ISSUE TITLE
通过rtsp接入海康摄像头分发rtmp流延时有点高，6到7秒

### ISSUE THREAD

**Issue by huangli321456** [ossrs/srs#1880]
**描述(Description)**

> 通过rtsp接入海康摄像头分发rtmp流延时有点高，6到7秒

1. SRS版本(Version): `3.0`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
默认配置
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)
 ./objs/ffmpeg/bin/ffmpeg -re -rtsp_transport tcp -i "rtsp://admin:admin@192.168.28.111:554/Streaming/Channels/101?transportmode=unicast" -vcodec copy -acodec aac -f flv -y rtmp://192.168.11.183/live/livestream

**期望行为(Expect)**

> 降低延时

**Comment by huangli321456** [comment]
https://github.com/ossrs/srs/wiki/v3_CN_SampleRealtime
After trying out this low-latency solution, the delay can be reduced to 2 seconds without using VLC. Is there any other way to improve it?

`TRANS_BY_GPT3`

**Comment by 648540858** [comment]
The delay is also closely related to the playback device you are using.

`TRANS_BY_GPT3`

**Comment by huangli321456** [comment]
At first, VLC was used with a delay of about 6 seconds. Later, SRS player was switched and the delay was reduced to about 2 seconds.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Use WebRTC player.

`TRANS_BY_GPT3`

**Comment by zfs1993** [comment]
> 
How to play rtmp stream with SRS? I couldn't find the format.

`TRANS_BY_GPT3`
