### ISSUE TITLE
Header Matching Should Be Case-Insensitive

### ISSUE THREAD

**Issue by RossWang** [ossrs/srs#1881]
**描述(Description)**

SRS版本(Version): `v4.0.35`

https://github.com/ossrs/srs/blob/c6a68234cbd33c4b66ae6d8e8fdef2f5984b5818/trunk/src/protocol/srs_http_stack.cpp#L839
The code above check if "Origin" header exists. If yes, then the server responses the result with "Access-Control-Allow-Origin" header. 

The problem is some Load Balancer or CDN suppliers such as Google transform all the request header to lower case, in this case,  "origin", which prevents CORS headers from being sent.

For reference,  the RFC ([RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2)) says that header fields have a case-insensitive field name.

**期望行为(Expect)**
Header matching should be case-insensitive.

**Comment by winlinvip** [comment]
Fixed.
