### ISSUE TITLE
state threads 导致无法支持https?

### ISSUE THREAD

**Issue by JalySN** [ossrs/srs#1888]
配置代理的方式比较麻烦，srs的docker实例是动态拉起的，代理进程也需要动态修改https转发。所以想知道作者在这方面是不是因为底层的state threads io导致的无法支持？

**Comment by JalySN** [comment]
这个我后来解决了。通过bio_mem，把st_write和st_read的值跟buffer关联起来。还蛮好实现的，就是资料比较少

**Comment by flyboyxiang** [comment]
楼主可以给作者提个pr

**Comment by dragon8609** [comment]
请问，你是在srs框架下实现了https协议吗？

**Comment by JalySN** [comment]
> 请问，你是在srs框架下实现了https协议吗？

对。写了个类继承srsstsocket，实际收发数据依然用的stsocket的read write

**Comment by dragon8609** [comment]
> > 请问，你是在srs框架下实现了https协议吗？
> 
> 对。写了个类继承srsstsocket，实际收发数据依然用的stsocket的read write

可以发一下代码给我吗？或者告诉我具体怎么实现？谢谢！

**Comment by JalySN** [comment]
> > > 请问，你是在srs框架下实现了https协议吗？
> > 
> > 
> > 对。写了个类继承srsstsocket，实际收发数据依然用的stsocket的read write
> 
> 可以发一下代码给我吗？或者告诉我具体怎么实现？谢谢！

https://www.roxlu.com/2014/042/using-openssl-with-memory-bios

**Comment by dragon8609** [comment]
非常感谢！！！

**Comment by winlinvip** [comment]
HTTPS肯定会在SRS中支持，欢迎提patch。

**Comment by winlinvip** [comment]
Dup to #1657

**Comment by winlinvip** [comment]
Fixed in https://github.com/ossrs/srs/issues/1657#issuecomment-722971676
