### ISSUE TITLE
How many rtmp connections a single Origin server can take? 

### ISSUE THREAD

**Issue by xoraingroup** [ossrs/srs#1891]
I have been testing it with many features, and its a wonderful product. 

Is there some where a hard limit or soft limit where a single origin server can take max limit of rtmp connections?

I have a cloud vm 2 cores - 4 GB RAM with 500 Mbps bandwidth. After 42 connections with bitrate of 5000k+ its not accepting any more connections. The publishing stream times out.

Please reply.

Thanks

**Comment by xoraingroup** [comment]
Did a benchmark. Seems good.

**Comment by RocFang** [comment]
@xoraingroup there is a max_connections config parameter. default is 1000.
