### ISSUE TITLE
默认http.flv配置下，http-flv只支持6个源播放

### ISSUE THREAD

**Issue by xiamo6666** [ossrs/srs#1896]
![image](https://user-images.githubusercontent.com/46433683/89498556-050c3e00-d7f1-11ea-9f47-17f77751611f.png)
超过6个在线播放数目时，在请求flv地址处于pending状态，rtmp流正常

**Comment by lin557** [comment]
这个一般是浏览器同域名请求的最大并发数限制的原因，与srs无关

**Comment by chenhanwen2019** [comment]
您好，我按照网站所示的 使用SRS分发FLV流，得到的FLV流地址，在浏览器上不能在网页上播放是什么原因呢？请指点下，谢谢！
