### ISSUE TITLE
feature/rtc  srs_app_rtc_sdp.cpp字符串转大小写错误

### ISSUE THREAD

**Issue by LuluChina** [ossrs/srs#1909]
![image](https://user-images.githubusercontent.com/44631008/90132589-b9353800-dda0-11ea-92b0-579ced6bda87.png)
lower_name 和 upper_name 为空，导致无法推送RTC流。
这里由于lower_name 和 upper_name 没有分配空间，所以无法得到预期转换后的结果。最后这两个变量都为空，导致无法获取到OPUS对应的信息，RTC推送失败。

**Comment by winlinvip** [comment]
Fixed?

**Comment by LuluChina** [comment]
Yes， 新版本已经没有这个问题了。
