### ISSUE TITLE
edge转发到aliyun cdn的rtmp流缺少编码信息和帧率信息

### ISSUE THREAD

**Issue by liguocahng** [ossrs/srs#1938]
这是在阿里云提交的工单，阿里云回我的对话，流是推过去了，但是缺少编码信息和帧率信息
![图片](https://user-images.githubusercontent.com/28724869/92302697-b5ac5f80-efa0-11ea-9cc6-f9ad44582eda.png)

1. SRS版本(Version): `SRS/4.0.36(Leo)  `
1. SRS的日志如下(Log):
![图片](https://user-images.githubusercontent.com/28724869/92302733-fd32eb80-efa0-11ea-8802-b256772abbda.png)

1. SRS的配置如下(Config):
![图片](https://user-images.githubusercontent.com/28724869/92302753-2d7a8a00-efa1-11ea-9fde-bf0d1e742aaf.png)

用过SRS/3.0.141 也是上面的结果，直到退回SRS/2.0.265才正常
SRS/2.0.265 日志
![图片](https://user-images.githubusercontent.com/28724869/92302802-7f231480-efa1-11ea-9e20-50e459596bcd.png)

> 重现Bug的步骤(How to replay bug?)

直接配置
edge.conf就可以重现

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
Why is that?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Should be fixed in SRS 4.0
