### ISSUE TITLE
HLS Low Latency

### ISSUE THREAD

**Issue by lvndry** [ossrs/srs#1943]
**Description**

> I have a SRS config with HLS and low latency config from the [wiki](https://github.com/ossrs/srs/wiki/v3_EN_LowLatency).
 However, running SRS under docker and testing with VLC I have around 28 seconds of latency.

1. Version: `3.0.141`

1. SRS的配置如下(Config):

```
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console; # or file

# web Console
http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

stats {
    network         0;
    disk            sda sdb xvda xvdb;
}

vhost __defaultVhost__ {
    # Low latency
    enabled on;
    # tcp_nodelay     on;
    # min_latency     on;

    play {
        gop_cache       off;
        # queue_length    10;
        # mw_latency      100;
    }

     hls {
       enabled         on;
       hls_fragment    5; # 10;
       hls_window      20; # 60;
       hls_path        ./objs/nginx/html;
       hls_m3u8_file   [app]/[stream].m3u8;
       hls_ts_file     [app]/[stream]-[seq].ts;
     }

    publish {
      # about MR, read https://github.com/ossrs/srs/issues/241
      # when enabled the mr, SRS will read as large as possible.
      # default: off
      mr          off;
      # the latency in ms for MR(merged-read),
      # the performance+ when latency+, and memory+,
      #       memory(buffer) = latency * kbps / 8
      # for example, latency=500ms, kbps=3000kbps, each publish connection will consume
      #       memory = 500 * 3000 / 8 = 187500B = 183KB
      # when there are 2500 publisher, the total memory of SRS atleast:
      #       183KB * 2500 = 446MB
      # the value recomment is [300, 2000]
      # default: 350
      mr_latency  350;
    }
}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `create a config file test.config`
1. `docker docker run -p 1935:1935 -p 1985:1985 -p 8080:8080 -v $CONF_PATH:/usr/local/srs/conf/srs.conf ` with $CONF_PATH being the path of the config file
1. `Open VLC and set the URL to http://locahost:8080/livestream/<stream_key>` the latency should be more than 25 seconds

**期望行为(Expect)**

> Expect latency to be under 10 seconds

**Comment by Franckrst** [comment]
i have same porbleme with 27Seconds of latency

**Comment by Franckrst** [comment]
@lvndry Do you have found solution ?

**Comment by lvndry** [comment]
No I'm still looking for a solution. Thinking to move to a better-supported project

**Comment by lgjluis** [comment]
@Franckrst @lvndry 

I Have this configuration and get 6 -10 seconds of latency:

hls {
        enabled         on;
        hls_fragment    2;
        hls_window      30;
        hls_aof_ratio   1.0;
        hls_td_ratio    1.0;
        hls_cleanup     on;
        hls_dispose     0;
}

**Comment by lvndry** [comment]
@lgjluis Awesome!
Can you explain what are `hls_aof_ratio` `td_ratio` please ?

**Comment by lgjluis** [comment]
@lvndry You can find it on the Wiki: 
https://github.com/ossrs/srs/wiki/v4_EN_DeliveryHLS

**Comment by nyaxs** [comment]
try this,

hls_fragment    0.8; # 10;
       hls_window      8; # 60;

about 10s and stable

-> go further 
hls_fragment    0.2; # 10;
       hls_window      2; # 60;

<2s but unstable
