### ISSUE TITLE
HTTP Api有没有根据'流名称'统计在线人数接口？

### ISSUE THREAD

**Issue by yuxuaner** [ossrs/srs#1946]
HTTP Api有没有根据'流名称'统计在线人数接口？

**Comment by LeafHCode** [comment]
/api/v1/streams

**Comment by yuxuaner** [comment]
我看了一下，这个接口目前是根据流ID获取，目前取不到这个值。我们目前业务推流地址http://192.168.1.220:1935/live/room_123,想根据这个stream=room_123直接获取在线人数




| |
高兵兵
|
|
邮箱：15010992510@163.com
|

签名由 网易邮箱大师 定制

在2020年09月11日 10:38，LeafHCode 写道：

/api/v1/streams

**Comment by LeafHCode** [comment]
> 我看了一下，这个接口目前是根据流ID获取，目前取不到这个值。我们目前业务推流地址[http://192.168.1.220:1935/live/room_123,想根据这个stream=room_123直接获取在线人数](http://192.168.1.220:1935/live/room_123,%E6%83%B3%E6%A0%B9%E6%8D%AE%E8%BF%99%E4%B8%AAstream=room_123%E7%9B%B4%E6%8E%A5%E8%8E%B7%E5%8F%96%E5%9C%A8%E7%BA%BF%E4%BA%BA%E6%95%B0) | | 高兵兵 | | 邮箱：15010992510@163.com | 签名由 网易邮箱大师 定制 在2020年09月11日 10:38，LeafHCode 写道： /api/v1/streams — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

代码里面改一下就可以了，或者加个publish的回调存下来streamID

**Comment by duiniuluantanqin** [comment]
一共分2步：
/api/v1/streams接口，可以通过流名称获取到流ID。
/api/v1/clients接口，可以通过上一步获取到流ID，得到所有在线人数
