### ISSUE TITLE
API: /api/v1/clients Segment fault 

### ISSUE THREAD

**Issue by bfxyzshb** [ossrs/srs#1948]
**描述(Description)**

> mac Segment fault 必现
<img width="1188" alt="4E9A5F80-886F-4E0E-B7B7-9B2696AF8FB0" src="https://user-images.githubusercontent.com/34388534/93085360-079f6480-f6c8-11ea-955c-e8c455e75f0e.png">

1. SRS版本(Version): `3.0.141`

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `先拉flv`
2. `再向srs推流`
3. `curl /api/v1/clients接口`
以上步骤顺序执行就好
**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
Can not replay for 3.0.142

**Comment by bfxyzshb** [comment]
![08028444-82A1-4BE7-8B65-90C6B0B1690F](https://user-images.githubusercontent.com/34388534/93092621-3e7a7800-f6d2-11ea-87fe-52989518e881.png)

**Comment by bfxyzshb** [comment]
![srs_bug](https://user-images.githubusercontent.com/34388534/93095271-78994900-f6d5-11ea-99af-07439257e5fc.png)

**Comment by weizhenyi** [comment]
like the image below shows：
req in SrsStatisticClient of   SrsStatistic::clients not match the SrsRequest type,so cause  /api/v1/clients Segment fault 
![image](https://user-images.githubusercontent.com/7948230/93157893-b467f900-f73d-11ea-8037-2d4659af8b6a.png)

and  I fix it in the way below:
![image](https://user-images.githubusercontent.com/7948230/93158403-9c44a980-f73e-11ea-847b-b469626b3818.png)

**Comment by nowgoing** [comment]
srs/4.0.37 也存在同样的情况。

**Comment by winlinvip** [comment]
这个可以查查。

**Comment by everything411** [comment]
SRS/3.0.153 复现

**Comment by winlinvip** [comment]
Fixed by #2311
