### ISSUE TITLE
rtmp推流，sei被过滤

### ISSUE THREAD

**Issue by yezhichao** [ossrs/srs#1951]
在srs_write_h264_raw_frame中：
<img width="629" alt="屏幕快照 2020-09-17 上午8 52 19" src="https://user-images.githubusercontent.com/15684581/93406842-49e0c580-f8c3-11ea-995e-910ffe6f6908.png">

<img width="547" alt="屏幕快照 2020-09-17 上午8 55 24" src="https://user-images.githubusercontent.com/15684581/93406942-8f9d8e00-f8c3-11ea-97cb-d818e9f51e13.png">

请问一下为何要滤掉sei，把条件改掉的话可以正常发送sei吗？

**Comment by winlinvip** [comment]
倒是可以考虑。

**Comment by jinleileiking** [comment]
Many scenes have the requirement of transparently transmitting SEI.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
srs-librtmp is no longer maintained, please use FFmpeg.

`TRANS_BY_GPT3`
