### ISSUE TITLE
How to make the Client API list me with 100 Clients instead of 10 clients?

### ISSUE THREAD

**Issue by jhonyesg** [ossrs/srs#1964]
**描述(Description)**

I want to make the api provide me with all lceintes ocneted or at least 100 clients, in order to integrate it to a built platform, ocn in order to not allow unauthorized connections, to the signals that are consumed in the server.

1. SRS(Version): 3

In summary, I want to know how to do so that the api restrictions on connected clients do not exist, in order to be able to organize and control the information of clients connected to my SRS server, mounted on my computer.
It would be great to be able to control that just like those Xstram panels do, but I am satisfied with having that info in a Json, to be able to manage it.

Thank you in advance for your time invested in answering my question.
Thank you.

**Comment by duiniuluantanqin** [comment]
api/v1/clients?count=100

**Comment by jhonyesg** [comment]
thank you
