### ISSUE TITLE
webrtc播放内网SRS时，路由器设置DMZ也无法成功

### ISSUE THREAD

**Issue by netyuchangfa** [ossrs/srs#1965]
版本是 v4.0.39
使用WEBRTC功能 时， candidate       配置为公网本机公网IP时能正常播放视频。
但是，将SRS放在局域网里面，配置路由器穿透UDP端口到本地时，无法播放。

配置如下过程 ：
1、配置路由器UDP穿透到RTC的端口8000并且将API的地址也穿透到SRS的1985，或直接配置路由器DMZ主机到SRSIP地址。
2、配置SRS的RTC 的UDP端口为8000， candidate配置为路由器外网地址。
3.重启SRS
4.用WEBRTC播放时指向路由器外网IP地址。无法播放。
通过查看浏览器API接口返回数据，已经取得RTC的外网播放公网IP地址和端口。但仍无法播放视频。

放在内网里还需要做什么配置或修改吗？

**Comment by yzw607** [comment]
请教下，你这个问题最后有解决吗，怎么解决的？我现在也碰到类似的问题。
