### ISSUE TITLE
WebRTC播放下，如何停止拉流，是否有对应的接口可以调用，谢谢

### ISSUE THREAD

**Issue by christlee2258** [ossrs/srs#1967]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `SRS/4.0.39(Leo), MIT`
2. WebRTC播放下，如何停止拉流，是否有对应的接口可以调用，谢谢

**Comment by duiniuluantanqin** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/RTCPeerConnection
看看这个文档能解决你的问题吗

**Comment by winlinvip** [comment]
Won't fix.
