### ISSUE TITLE
配置边缘服务器，必须用一个客户端拉rtmp流触发，其他客户端才能拉到hls流

### ISSUE THREAD

**Issue by f476717929** [ossrs/srs#1981]
期望：从aliyun 拉取到rtmp流到边缘服务器，然后使用边缘服务器进行分发，希望rtmp和hls都能正常获取到流
实际情况：
1.如果不用一个客户端从边缘服务器请求rtmp流，其他客户端无法拉取到hls流，边缘服务器的m3u8文件和ts文件也不会更新，
2.如果中途停掉拉取rtmp流的客户端，其他客户端也无法从边缘服务器获取到新的ts文件，一旦恢复rtmp拉流，边缘服务器就能生成新的ts文件，hls拉流的客户端也能正常播放
疑问：向边缘服务器单独请求hls流，不会触发边缘服务器从ali源服务器获取流？只有rtmp请求才能触发吗？

srs配置：
listen              1935;
max_connections     1000;
pid                 objs/edge.pid;
daemon              off;
srs_log_tank        console;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    cluster {
        mode            remote;
        origin            alicdn.xxx.com;
    }
	hls {
        enabled         on;
        hls_fragment    5;
        hls_window      20;
        hls_path        ./objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
    }
}

**Comment by yzw607** [comment]
It looks similar to the issue I encountered:
SRS 3.0 fails to play http-flv directly from the Edge, but http-flv can be played normally after playing rtmp #1974.

`TRANS_BY_GPT3`

**Comment by free-wind-0** [comment]
> It seems similar to the problem I encountered:
> SRS 3.0 fails to play http-flv directly from the Edge, but http-flv plays normally after playing rtmp #1974

>#1550 Take a look at this issue. The answer says that only rtmp can trigger active back-to-origin. 
Try configuring http_remux to enable for http-flv and see if it can solve your back-to-origin problem. There is currently no solution for triggering hls at the edge.

`TRANS_BY_GPT3`

**Comment by yzw607** [comment]
> > It seems similar to the problem I encountered:
> > SRS 3.0 fails to play http-flv directly from the Edge, but http-flv can be played normally after playing rtmp #1974
> 
> #1550 Take a look at this issue, the answer says that only rtmp can trigger active backsource.
> For http-flv, try configuring http_remux to enable it and see if it can solve your backsource problem. There is currently no solution for triggering hls at the edge.

Thank you for the reply! My http_remux is already enabled, but there is still a problem. Moreover, when I was using srs2.0 before, playing http-flv at the edge was fine. The problem only appeared after I recently upgraded to srs3.0.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
HLS does not support edges.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
HLS belongs to the origin server function, and the edge does not support HLS. In the future, it will be improved to give an error when configuring HLS on the edge.

This can help to detect errors in advance. Refer to #1066.

`TRANS_BY_GPT3`

**Comment by wang00850023** [comment]
> > > It seems similar to the problem I encountered:
> > > SRS 3.0 fails to play http-flv directly from the Edge, but http-flv can be played normally after playing rtmp #1974
> > 
> > 
> > #1550 Take a look at this issue, the answer says that only rtmp can trigger active backsource.
> > For http-flv, try configuring http_remux to enable and see if it can solve your backsource problem. There is currently no solution for triggering hls at the edge.
> 
> Thank you for the reply! My http_remux is already enabled, but there is still a problem. Moreover, when I was using SRS 2.0, playing http-flv at the edge was fine. The problem only appeared after I recently upgraded to SRS 3.0.
Have you solved your problem? I encountered the same issue as you.

`TRANS_BY_GPT3`
