### ISSUE TITLE
SrsKbps::get_recv_kbps可能出现除0异常？

### ISSUE THREAD

**Issue by JalySN** [ossrs/srs#1987]
int SrsKbps::get_recv_kbps()
{
    srs_utime_t duration = clk->now() - os.starttime;
    if (duration <= 0) {
        return 0;
    }
    int64_t bytes = get_recv_bytes();
    return (int)(bytes * 8 / srsu2ms(duration));
}

duration< 1000 就会出现除0

**Comment by JalySN** [comment]
`SrsKbps::get_send_kbps` should also have a similar issue.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍 It has been fixed, and I have picked it to the 3.0 branch: https://github.com/ossrs/srs/commit/4ccb83834d661b4b1baed6bdbeb8f24a5dd2ea81#diff-e156a1170da82b924422f8449d015822167081b84e1f9f3bf358edd3aa36537b

`TRANS_BY_GPT3`
