### ISSUE TITLE
How to install SSL and serve HTTPS streaming

### ISSUE THREAD

**Issue by manuelvita96** [ossrs/srs#1992]
Hi, I use Ubuntu 16 server with apache and let's encrypt certificates. I have compiled SRS today directly from Git, so I have the latest version. I'm trying to enable HTTPS on all site, I have a player which load HSL stream passed by RTMP. How can I enable SSL? Now I receive the connection closed error

**Comment by codihaus** [comment]
I'm wondering this too,

I tried to setup an NGINX proxy, add SSL to that proxy, but couldn't use proxy_pass to pass the request of m3u8 to origin side.

:(

**Comment by lgjluis** [comment]
I can help you. lgjluis@gmail.com

**Comment by alongL** [comment]
use nginx reverse proxy.  install ssl certificate for nginx  and setup reverse proxy.
how to install ssl certificate? please search in google.
setup reverse proxy can see this:
···
	location ^~/live/ {
		proxy_pass http://127.0.0.1:8080;
	}
···
all the request to  http://abc.com/live/tv.m3u8  will to  http://127.0.0.1:8080/live/tv.m3u8 ,  while  srs listen on 8080. 

more info https://github.com/ossrs/srs/issues/1142

**Comment by winlinvip** [comment]
Use Nginx or Caddy as a proxy to provide unified HTTP/HTTPS services, refer to #2881

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in https://github.com/ossrs/srs/issues/1657#issuecomment-722971676

**Comment by winlinvip** [comment]
使用Nginx或Caddy代理，提供统一的HTTP/HTTPS服务，参考 #2881

**Comment by winlinvip** [comment]
See https://github.com/ossrs/srs/issues/2881#nginx-proxy
