### ISSUE TITLE
(feature)hearbeat 心跳可以支持 /api/v1/streams 的流信息主动汇报么？

### ISSUE THREAD

**Issue by limjoe** [ossrs/srs#2013]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

目前使用 k8s 部署了源集群模式, 源节点有 10 个以上，边缘节点有2 个，目前业务上有流媒体监控的需求

1.  需要统计每个节点(源、边缘)的接入路数、带宽占用情况(云服务商有多个，所以没有考虑调用云服务商的网络资源统计接口)
2. 没路接入流信息的编码方式等信息

目前我是通过部署的 12 个节点的 API 接口( /api/v1/streams ) 来定时获取每个节点的流信息进行汇总，但是需要对每个 k8s 内的节点暴露 HTTP API接口，极不好扩展和维护

我看有心跳机制-heartbeat  主动上报了 summaries 节点信息，作者能否扩展下支持 streams 的上报

```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
heartbeat {
    enabled         on;
    interval        9.3;
    url             http://127.0.0.1:8085/api/v1/servers;
    # the id of devide.
    device_id       "my-srs-device";
    summaries       off;
   streams             on;
}
```

**重现(Replay)**

**Comment by limjoe** [comment]
替代方案:
在每个边缘自己实现一个集群内的中心 API ，定时采集集群类的 HTTP-API 数据进行上报

**Comment by dzhcool** [comment]
一个Pod里面2个container，一个srs、一个简单收集数据的agent程序，然后agent通过127.0.0.1+端口去收集数据， 不需要对外暴露
