### ISSUE TITLE
srs中webrtc可否支持双向语音通话？

### ISSUE THREAD

**Issue by ghostsf** [ossrs/srs#2016]
**描述(Description)**
srs中webrtc，rtc推流和rtc播放器，不能语音通话

**期望行为(Expect)**

webrtc可否支持双向语音通话

**Comment by zsinba** [comment]
应该可以，推流的时候，把声音混音后推出去不就可以吗？

**Comment by winlinvip** [comment]
WebRTC推流和播放就可以。

**Comment by ghostsf** [comment]
> WebRTC推流和播放就可以。

播放不能发送语音
