### ISSUE TITLE
RTP组装成ps包为啥不check markerbit

### ISSUE THREAD

**Issue by felix-001** [ossrs/srs#2022]
uint8_t p1 = (uint8_t)(payload[0]);
    uint8_t p2 = (uint8_t)(payload[1]);
    uint8_t p3 = (uint8_t)(payload[2]);
    uint8_t p4 = (uint8_t)(payload[3]);
    //check for rtp ps audio streaming
    bool av_same_ts = true;

    if (p1 == 0x00 && p2 == 0x00 && p3 == 0x01 && p4 == 0xC0 &&
        ps_rtp_video_ts != pkt->timestamp) {
        av_same_ts = false;
    }
    //if audio and video are the same clock, 
    //if both audio and video use jitter_buffer, 
    //otherwise audio uses jitter_buffer_audio, and video uses jitter_buffer
    if (av_same_ts){
        pkt->marker = false;// **这里为什么要置成false**
        jitter_buffer->InsertPacket(*pkt, pkt->payload->bytes(), pkt->payload->length(), NULL);
        ps_rtp_video_ts = pkt->timestamp;
    }else {
        jitter_buffer_audio->InsertPacket(*pkt, pkt->payload->bytes(), pkt->payload->length(), NULL);
    }

**Comment by duiniuluantanqin** [comment]
ps packets should be able to ignore the marker in the rtp packet header.

`TRANS_BY_GPT3`
