### ISSUE TITLE
SRS从集群服务器拉流转发播放应该如何配置

### ISSUE THREAD

**Issue by breezeewu** [ossrs/srs#2027]
您好，我的源服务器（master节点）是多个SRS的服务集群，服务集群中只有一个节点有用户需要的流。如下图所示：
![image](https://user-images.githubusercontent.com/16345166/98756796-3c007a00-2406-11eb-9cae-b272e82db366.png)
据我所知，使用SRS回源拉流只能从配置文件中指定的主节点进行回源拉流，我想请问一下当主节点有多个时能否支持边缘节点的回源拉流？

**Comment by winlinvip** [comment]
暂不支持，RTC级联比较复杂。

**Comment by winlinvip** [comment]
First, let me explain the vocabulary: 

* SRS Edge, edge server, refers to the SRS (edge node) here.
* SRS Origin, origin server, refers to the SRS (main node) here.

To support clustering, the following configuration is required:

1. Origin Cluster, configure it as the source server cluster, please refer to the specific documentation for details.
2. Edge Cluster, specify multiple Origins for back-end retrieval, please refer to the specific documentation for details.

`TRANS_BY_GPT3`
