### ISSUE TITLE
srs4.0一定要安装自带的ffmpeg-4.2.fit吗？我在编译srs时，总是到了编译ffmpeg-4.2.fit这一步报错，能不能不安装这个？要怎么弄？请指点我一下，谢谢大家

### ISSUE THREAD

**Issue by zhangdengzhen** [ossrs/srs#2030]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `xxxxxx`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by ghostsf** [comment]
额 报什么错 用什么怎么编译的 
ffmpeg不是编译好的吗

**Comment by kefanchen** [comment]
> 额 报什么错 用什么怎么编译的
> ffmpeg不是编译好的吗

现在3rdparty里不是把ffmpeg删了吗？现在只能手动自己装ffmpeg吗？

**Comment by kefanchen** [comment]
> 额 报什么错 用什么怎么编译的
> ffmpeg不是编译好的吗

我试了release3.0 和 release4.0 分支，centos7 , 使用默认的‘./configure && make’ 并没有在./objs下面发现编译好的ffmpeg, 需要单独安装吗？

**Comment by nowgoing** [comment]
> 
> 
> > 额 报什么错 用什么怎么编译的
> > ffmpeg不是编译好的吗
> 
> 我试了release3.0 和 release4.0 分支，centos7 , 使用默认的‘./configure && make’ 并没有在./objs下面发现编译好的ffmpeg, 需要单独安装吗？
./configure      --with-ffmpeg

**Comment by feihongxueni** [comment]
1、单独下载ffmpeg release版本至 /root/ffmpeg_sources/ffmpeg-static
2、进入srs-->trunk-->objs-->ffmpeg-->bin(默认ffmpge地址)
3、执行
     ln -s /root/ffmpeg_sources/ffmpeg-static/ffprobe ffprobe
     ln -s /root/ffmpeg_sources/ffmpeg-static/ffmpeg ffmpeg
4、可以使用ffmpeg了

**Comment by ghostsf** [comment]
> 1、单独下载ffmpeg release版本至 /root/ffmpeg_sources/ffmpeg-static
> 2、进入srs-->trunk-->objs-->ffmpeg-->bin(默认ffmpge地址)
> 3、执行
> ln -s /root/ffmpeg_sources/ffmpeg-static/ffprobe ffprobe
> ln -s /root/ffmpeg_sources/ffmpeg-static/ffmpeg ffmpeg
> 4、可以使用ffmpeg了

是的 正解

**Comment by winlinvip** [comment]
描述不清。
