### ISSUE TITLE
Add support for h264_nvenc

### ISSUE THREAD

**Issue by diamanat** [ossrs/srs#2044]
**描述(Description)**
Hi. I was trying to use NVIDIA videocard for transcoding and had error invalid vcodec, must be libx264, actual h264_nvenc

1. SRS版本(Version): 4.0 release

**期望行为(Expect)**
Can use also h264_nvenc codec for transcoding

So it can be fixed here
srs/trunk/src/app/srs_app_ffmpeg.cpp

// only support libx264 encoder.
#define SRS_RTMP_ENCODER_VCODEC_LIBX264 "libx264"

**Comment by wnpllrzodiac** [comment]
1 build your own version ffmpeg
2 make some change in srs_app_ffmpeg.cpp
I think it won't be a very hard work.

**Comment by diamanat** [comment]
I've done it for my purposes, It was just suggestion to make this software better

**Comment by winlinvip** [comment]
Won't fix.
