### ISSUE TITLE
请问国标接入，密码验证怎么做校验？

### ISSUE THREAD

**Issue by wangjinqian0406** [ossrs/srs#2048]
请问国标接入，密码验证怎么做校验？
我看到下级nvr或摄像头国标接入都有密码？但是好像配置中没有设置流媒体服务国标接入密码的地方？
![image](https://user-images.githubusercontent.com/50072885/99866184-015ac680-2bea-11eb-85d2-a1e5e2f945ab.png)

**Comment by winlinvip** [comment]
这个是SIP的事吧？
