### ISSUE TITLE
gb28181的invite控制API在哪里能找到

### ISSUE THREAD

**Issue by mayomeng** [ossrs/srs#2052]
push.gb28181.conf

        # 注册之后是否自动给设备端发送invite
        # on: 是  off 不是，需要通过api控制
        auto_play           on;

上面的配置，如果auto_play设为off的话，通过哪些API来控制invite呀，在wiki里没有找到相关的API

**Comment by wangjinqian0406** [comment]
https://github.com/xialixin/srs_code_note/blob/master/doc/srs_gb28181.md

**Comment by mayomeng** [comment]
@wangjinqian0406 I saw it, thank you so much.

`TRANS_BY_GPT3`

**Comment by mayomeng** [comment]
Hello, may I ask what the 'chid' parameter is in the sip_invite interface? I didn't quite understand it from the documentation. Also, do we need to create the media stream channel in advance or is it automatically created after the invite?

`TRANS_BY_GPT3`

**Comment by mayomeng** [comment]
Found chid is the device_id in the return value of the sip_query_session interface.

`TRANS_BY_GPT3`
