### ISSUE TITLE
srs_r3.0的srs-librtmp库内存泄露

### ISSUE THREAD

**Issue by MookerLee** [ossrs/srs#2055]
**描述(Description)**

> 单独编译srs-librtmp生成静态库，调用srs_rtmp_read_packet接口时会出现内存泄露(linux环境)，基本在半小时内能重现；

1. SRS版本(Version): `3.0release`
2. 编译环境: GCC v7.5

**CMakeLists文件：**

cmake_minimum_required(VERSION 3.15)
project(srs-librtmp-test)

set(CMAKE_CXX_STANDARD 14)

file(GLOB DIR_SRSLIBRTMP_TEST_SRCS
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    #${CMAKE_CURRENT_LIST_DIR}/srs-librtmp2.0/*.cpp
)

source_group("SrsLibRtmpTest" FILES ${DIR_SRSLIBRTMP_TEST_SRCS})

#include_directories(${CMAKE_CURRENT_LIST_DIR})
#include_directories(${CMAKE_CURRENT_LIST_DIR}/srs-librtmp2.0/)
#include_directories(${CMAKE_CURRENT_LIST_DIR}/../libs/)

list(APPEND LIBS ${CMAKE_CURRENT_LIST_DIR}/libsrs-librtmp.a)
list(APPEND LIBS /usr/local/openssl/lib/libssl.a)
list(APPEND LIBS /usr/local/openssl/lib/libcrypto.a)
list(APPEND LIBS pthread dl resolv)
link_libraries(${LIBS})

list(APPEND DIR_SRCS ${DIR_SRSLIBRTMP_TEST_SRCS})

add_executable(srs-librtmp-test ${DIR_SRCS})
set(EXECUTABLE_OUTPUT_PATH ${CMAKE_CURRENT_LIST_DIR})

**测试代码：**

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "srs_librtmp.hpp"

int main()
{
    char type = 0;
    uint32_t timestamp = 0;
    int size = 0;
    char * data = nullptr;
    char szDbg[256] = { 0 };

    srs_rtmp_t _rtmp = srs_rtmp_create("rtmp://192.167.6.172:1935/live/22011004901181000100_22011004901321000140_2");
    do {
        if (!_rtmp) {
            printf("srs_rtmp_create() failed.\r\n");
            break;
        }

        if (srs_rtmp_handshake(_rtmp) != 0) {
            printf("srs_rtmp_handshake() failed.\r\n");
            break;
        }

        srs_rtmp_set_timeout(_rtmp, 200, 500);

        if (srs_rtmp_connect_app(_rtmp) != 0) {
            printf("srs_rtmp_connect_app() failed.\r\n");
            break;
        }

        if (srs_rtmp_play_stream(_rtmp) != 0) {
            printf("srs_rtmp_play_stream() failed.\r\n");
            break;
        }

        while (true) {
            if (srs_rtmp_read_packet(_rtmp, &type, &timestamp, &data, &size) == 0) {
                if (SRS_RTMP_TYPE_VIDEO != type)
                    printf(".................................................\r\n");
                snprintf(szDbg, 256, "srs_rtmp_read_packet(0x%08x), type:%d, timestamp:%u, size:%d\r\n", _rtmp, type, timestamp, size);
                printf(szDbg);
                //if (SRS_RTMP_TYPE_VIDEO == type || SRS_RTMP_TYPE_AUDIO == type) {
                //    if (_cbFlvPacketOutput) _cbFlvPacketOutput(RTMP_AV_UNKNOWN, data, size, timestamp);
                //}
            }
            if (data) {
                srs_rtmp_free_packet(data);
                //free(data);
                data = nullptr;
            }
        }
    } while (false);

    return 0;
}

**内存泄露时控制台输出内容：**
srs_rtmp_read_packet(0x02870c60), type:9, timestamp:53939, size:628
srs_rtmp_read_packet(0x02870c60), type:9, timestamp:53979, size:31
.................................................
srs_rtmp_read_packet(0x02870c60), type:72, timestamp:0, size:18241
.................................................
srs_rtmp_read_packet(0x02870c60), type:4, timestamp:0, size:6
.................................................
srs_rtmp_read_packet(0x02870c60), type:4, timestamp:0, size:6
.................................................
srs_rtmp_read_packet(0x02870c60), type:20, timestamp:0, size:29
srs_rtmp_read_packet(0x02870c60), type:9, timestamp:13915699, size:29392
.................................................
srs_rtmp_read_packet(0x02870c60), type:20, timestamp:0, size:29

**内存占用情况：**
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
17077 root      20   0  827312  59476   1636 S  0.0  3.2   0:00.21 srs-librtmp-tes

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
17077 root      20   0  922092  86504   1636 S  0.0  4.6   0:00.25 srs-librtmp-tes

**备注1：**
  1. 使用https://github.com/ossrs/srs-librtmp/tree/srs2.0时在linux平台(CentOS 7.8)同样有此情况；
  2. 使用https://github.com/ossrs/srs-librtmp/tree/srs3.0时在linux平台运行时会在srs_rtmp_handshake()接口返回失败；
  3. 使用https://github.com/ossrs/srs-librtmp/tree/srs2.0时在windows平台(vs2017)运行正常(连续运行12h)；

**备注2：**
  RTMP服务器：srs_3.0release

**Comment by winlinvip** [comment]
不再维护客户端库。
