### ISSUE TITLE
GB28181：异常逻辑没有处理。

### ISSUE THREAD

**Issue by mrjamesli** [ossrs/srs#2056]
**描述(Description)**

被方法攻击后系统退出

1. SRS版本(Version): `4.0.56`
1. SRS的日志如下(Log):
```
[2020-11-27 01:24:34.960][Debug][27585][h582q55p] gb28181: request peer(51.38.35.139, 11211) nbbuf=96
[2020-11-27 01:24:34.960][Debug][27585][h582q55p] gb28181: request recv message=c.!Oc2=4au~v/wy|"cER2o21u.UhNv72(uf  j}a,~w&{ @k;/lGrvhZD^v\qYRI,c5QNpl\H
[2020-11-27 01:24:34.960][Debug][27585][h582q55p] sip: header=c.!Oc2=4au~v/wy|"cER2o21u.UhNv72(uf       j}a,~w&{     @k;/lGrvhZD^v\qYRI,c5QNpl\H



[2020-11-27 01:24:34.960][Debug][27585][h582q55p] sip: body=

[2020-11-27 01:24:34.960][Debug][27585][h582q55p] sip: first line=c.!Oc2=4au~v/wy|"cER2o21u.UhNv72(uf   j}a,~w&{     @k;/lGrvhZD^v\qYRI,c5QNpl\H
```
上面log中有不可见字符，将其转化为16进制，如下：

63 2E 21 4F 63 32 3D 34 61 75 17 7E 76 2F 77 16 79 7C 22 63 45 52 32 6F 32 31 18 75 05 2E 55 68 4E 76 37 32 28 75 66 09 6A 7D 07 61 2C 7E 77 26 7B 19 09 40 6B 3B 2F 1E 6C 47 13 72 76 68 5A 44 5E 12 76 06 07 5C 10 71 59 17 52 06 16 49 2C 11 63 35 51 4E 70 01 6C 5C 48

**Comment by mrjamesli** [comment]
Logic in 'srs_sip_stack.cpp':

    //respone first line text:SIP/2.0 200 OK
    if (!strcasecmp(method_uri_ver.at(0).c_str(), "sip/2.0")) {
        req->cmdtype = SrsSipCmdRespone;
        //req->method= vec_seq.at(1);
        req->status = method_uri_ver.size() > 0 ? method_uri_ver.at(1) : "";
        req->version = method_uri_ver.at(0);
        req->uri = req->from;

        vector<string> str = srs_string_split(req->to, "@");
        std::string ss = str.empty() ? "" : str.at(0);
        req->sip_auth_id = srs_string_replace(ss, "sip:", "");
  
    }else {//request first line text :MESSAGE sip:34020000002000000001@3402000000 SIP/2.0
        req->cmdtype = SrsSipCmdRequest;
        req->method= method_uri_ver.at(0);
        req->uri = method_uri_ver.size() > 0 ? method_uri_ver.at(1) : "";
        req->version = method_uri_ver.size() > 1 ? method_uri_ver.at(2) : "";

        vector<string> str = srs_string_split(req->from, "@");
        std::string ss = str.empty() ? "" : str.at(0);
        req->sip_auth_id = srs_string_replace(ss, "sip:", "");
    }

Vulnerability exists in the case of being attacked:
req->uri = method_uri_ver.size() > 0 ? method_uri_ver.at(1) : "";
req->version = method_uri_ver.size() > 1 ? method_uri_ver.at(2) : "";

Should it be for?
**req->uri = method_uri_ver.size() > 1 ? method_uri_ver.at(1) : "";
req->version = method_uri_ver.size() > 2 ? method_uri_ver.at(2) : "";**

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This needs to be looked at.

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
Switch to the develop branch and check the changes in PR #2014. It should have resolved this issue.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@PieerePi 👍
