### ISSUE TITLE
SRS3.0 /api/v1/streams 接口 统计流量不正确

### ISSUE THREAD

**Issue by yapingcat** [ossrs/srs#2058]
**描述(Description)**
rtmp 推流 ，http-flv播放
没有播放http-flv之前 流量统计是正确的
播放了http-flv之后 recv_bytes  send_bytes 变得很大
![image](https://user-images.githubusercontent.com/32125710/100418263-72541f80-30bd-11eb-83b3-3bd64e9fd2e9.png)

1. SRS版本(Version):  SRS/3.0.153(OuXuli), The MIT License (MIT)
1. SRS的日志如下(Log):

![image](https://user-images.githubusercontent.com/32125710/100418608-04f4be80-30be-11eb-9a17-a5962e679af0.png)

1. SRS的配置如下(Config):
```
# http-hooks or http-callbacks config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
    raw_api {
        enabled             on;
        allow_reload        on;
        allow_query         on;
        allow_update        on;
    }
}
http_server {
    enabled         on;
    listen          1980;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_hooks {
        enabled         on;
        on_connect      http://192.168.21.163:1990/api/v1/clients;
        on_close        http://192.168.21.163:1990/api/v1/clients;
        on_publish      http://192.168.21.163:1990/api/v1/streams;
        on_unpublish    http://192.168.21.163:1990/api/v1/streams;
        on_play         http://192.168.21.163:1990/api/v1/sessions;
        on_stop         http://192.168.21.163:1990/api/v1/sessions;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    hls {
        enabled         on;
        hls_fragment    3;
        hls_window      3;
        hls_path        ./objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
    }
}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `rtmp推流  调用/api/v1/streams 接口获取流量统计 `
1. `http-flv播放  `
1. `调用/api/v1/streams 接口获取流量统计`

**期望行为(Expect)**

>能正常统计流量

**Comment by weizhenyi** [comment]
Fix it like this: 
void SrsHttpConn::remark(int64_t* in, int64_t* out)
{
    // TODO: FIXME: implements it
    kbps->remark(in, out);
}

`TRANS_BY_GPT3`

**Comment by yapingcat** [comment]
> This is how you fix it: 
> void SrsHttpConn::remark(int64_t* in, int64_t* out)
> {
> // TODO: FIXME: implements it
> kbps->remark(in, out);
> }

Thank you, I solved it following your method.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.

`TRANS_BY_GPT3`
