### ISSUE TITLE
SRT：4.0 srs srt服务运行久了，cpu占用会很高

### ISSUE THREAD

**Issue by luowei729** [ossrs/srs#2069]
![image](https://user-images.githubusercontent.com/10611605/100851295-f2b0c100-34bf-11eb-835c-171169e2c2df.png)

**Comment by winlinvip** [comment]
This is probably a problem with leakage.

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
@luowei729 Hello, is this issue still present in the latest develop branch?

I can set up a public server to assist you in locating and resolving this issue. Please add me on VX: sweibd if needed.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS 5.0.
