### ISSUE TITLE
GB28181：运行一段时间后，设备离线，重启系统和服务器也无法注册

### ISSUE THREAD

**Issue by feixuezhang** [ossrs/srs#2071]
运行一段时间后设备离线 ，日志提示 ：`sip: unkonw message head Route`，无法识别设备发的注册报文，而服务端没有回复

1. SRS版本(Version): `4.0.56`
1. SRS的日志如下(Log):
```
[2020-12-03 11:13:09.283][Trace][7812][777p511g] sip: unkonw message head Route: content=<sip:21030200001180000001@xxx.xxx.xxx.xxx:5060;lr>
[2020-12-03 11:13:09.283][Trace][7812][777p511g] gb28181: request client id=21030200001180000001 peer(113.228.8.225, 5061)
[2020-12-03 11:13:09.283][Trace][7812][777p511g] gb28181: request method=REGISTER, uri=sip:44010600002000120002@xxx.xxx.xxx.xxx:5060, version=SIP/2.0 expires=3600
[2020-12-03 11:13:09.283][Trace][7812][777p511g] gb28181: send_message:SIP/2.0 200 OK
Via: SIP/2.0/UDP 113.228.8.225:5061;rport=5061;received=113.228.8.225;branch=z9hG4bK142655506
From: <sip:21030200001180000001@113.228.8.225:5061>;tag=1654407460
To: <sip:21030200001180000001@113.228.8.225:5061>
CSeq: 1 REGISTER
Call-ID: 1297672304@192.168.1.11
Contact: <sip:21030200001180000001@113.228.8.225:5061>
User-Agent: SRS/4.0.56(Leo)
Expires: 3600
Content-Length: 0


[2020-12-03 11:13:13.290][Trace][7812][777p511g] gb28181: request peer(113.228.8.225, 5061) nbbuf=498
[2020-12-03 11:13:13.290][Trace][7812][777p511g] gb28181: request recv message=REGISTER sip:44010600002000120002@xxx.xxx.xxx.xxx:5060 SIP/2.0
Via: SIP/2.0/UDP 113.228.8.225:5061;rport;branch=z9hG4bK142655506
Route: <sip:21030200001180000001@xxx.xxx.xxx.xxx:5060;lr>
From: <sip:21030200001180000001@113.228.8.225:5061>;tag=1654407460
To: <sip:21030200001180000001@113.228.8.225:5061>
Call-ID: 1297672304@192.168.1.11
CSeq: 1 REGISTER
Contact: <sip:21030200001180000001@113.228.8.225:5061>
Max-Forwards: 70
User-Agent: SIP UAS V2.1.4.662543
Expires: 3600
Content-Length: 0


[2020-12-03 11:13:13.290][Trace][7812][777p511g] sip: unkonw message head Route: content=<sip:21030200001180000001@xxx.xxx.xxx.xxx:5060;lr>
[2020-12-03 11:13:13.290][Trace][7812][777p511g] gb28181: request client id=21030200001180000001 peer(113.228.8.225, 5061)
[2020-12-03 11:13:13.290][Trace][7812][777p511g] gb28181: request method=REGISTER, uri=sip:44010600002000120002@xxx.xxx.xxx.xxx:5060, version=SIP/2.0 expires=3600
[2020-12-03 11:13:13.290][Trace][7812][777p511g] gb28181: send_message:SIP/2.0 200 OK
Via: SIP/2.0/UDP 113.228.8.225:5061;rport=5061;received=113.228.8.225;branch=z9hG4bK142655506
From: <sip:21030200001180000001@113.228.8.225:5061>;tag=1654407460
To: <sip:21030200001180000001@113.228.8.225:5061>
CSeq: 1 REGISTER
Call-ID: 1297672304@192.168.1.11
Contact: <sip:21030200001180000001@113.228.8.225:5061>
User-Agent: SRS/4.0.56(Leo)
Expires: 3600
Content-Length: 0


```

1. SRS的配置如下(Config):
```
# push gb28181 stream to SRS.

listen                  1935;
max_connections         1017;
daemon                  on;
srs_log_tank            console;  #配置日志答应到文件，需要和srs_log_level配合使用
srs_log_file            ./objs/srs.log; 
utc_time                off; #是否使用utc时间。如果该值为off则使用本地时间，如果开始使用utc时间。

http_api {
	# whether http api is enabled.
    # default: off
    enabled         on;
    # the http api listen entry is <[ip:]port>
    # for example, 192.168.1.100:1985
    # where the ip is optional, default to 0.0.0.0, that is 1985 equals to 0.0.0.0:1985
    # default: 1985
    listen          1985;
    # whether enable crossdomain request.
    # default: on
    crossdomain     on;
    # the HTTP RAW API is more powerful api to change srs state and reload.
    raw_api {
        # whether enable the HTTP RAW API.
        # default: off
        enabled             on;
        # whether enable rpc reload.
        # default: off
        allow_reload        on;
        # whether enable rpc query.
        # default: off
        allow_query         on;
        # whether enable rpc update.
        # default: off
        allow_update        on;
    }
}   

stats {
	# the index of device ip.
    # we may retrieve more than one network device.
    # default: 0
    network         0;
    # the device name to stat the disk iops.
    # ignore the device of /proc/diskstats if not configed.
    #disk            sda sdb xvda xvdb;
}

stream_caster {
    enabled             on;
    caster              gb28181;

    # 转发流到rtmp服务器地址与端口
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400875104
    # [stream] is VideoChannelCodecID(视频通道编码ID) for sip
    # 自动创建的道通[stream] 是‘chid[ssrc]’ [ssrc]是rtp的ssrc
    # [ssrc] rtp中的ssrc
    output              rtmp://127.0.0.1:1935/live/[stream];
    
    # 接收设备端rtp流的多路复用端口
    listen              9000;

    # rtp接收监听端口范围，最小值
    rtp_port_min        58200;
    # rtp接收监听端口范围，最大值
    rtp_port_max        58300;

    # 是否等待关键帧之后，再转发，
    # off:不需等待，直接转发
    # on:等第一个关键帧后，再转发
    wait_keyframe       on;
    
    # rtp包空闲等待时间，如果指定时间没有收到任何包
    # rtp监听连接自动停止，发送BYE命令
    rtp_idle_timeout    30;

    # 是否转发音频流
    # 目前只支持aac格式，所以需要设备支持aac格式
    # on:转发音频
    # off:不转发音频，只有视频
    # *注意*!!!:flv 只支持11025  22050  44100 三种
    # 如果设备端没有三种中任何一个，转发时为自动选择一种格式
    # 同时也会将adts的头封装在flv aac raw数据中
    # 这样的话播放器为自动通过adts头自动选择采样频率
    # 像ffplay, vlc都可以，但是flash是没有声音，
    # 因为flash,只支持11025 22050 44100
    audio_enable        off;

    # 是否开启rtp缓冲
    # 开启之后能有效解决rtp乱序等问题
    jitterbuffer_enable  on;

    # 服务器主机号，可以域名或ip地址
    # 也就是设备端将媒体发送的地址，如果是服务器是内外网
    # 需要写外网地址，
    # 调用api创建stream session时返回ip地址也是host
    # $CANDIDATE 是系统环境变量，从环境变量获取地址，如果没有配置，用*
    # *代表指定stats network 的网卡号地址，如果没有配置network，默认则是第0号网卡地址
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400917594
    
	host      xxx.xxx.xxx.xxx;

    #根据收到ps rtp包自带创建rtmp媒体通道，不需要api接口创建
    #rtmp地址参数[stream] 就是通道id  格式chid[ssrc]
    auto_create_channel   on;

    sip {
        # 是否启用srs内部sip信令
        # 为on信令走srs, off 只转发ps流
        enabled on;
        
        # sip监听udp端口
        listen              5060;
        
        # SIP server ID(SIP服务器ID).
        # 设备端配置编号需要与该值一致，否则无法注册
        serial              44010600002000120002;

        # SIP server domain(SIP服务器域)
        realm               4401060000;

        # 服务端发送ack后，接收回应的超时时间，单位为秒
        # 如果指定时间没有回应，认为失败
        ack_timeout         30;

        # 设备心跳维持时间，如果指定时间内(秒）没有接收一个心跳
        # 认为设备离线
        keepalive_timeout   120;

        # 注册之后是否自动给设备端发送invite
        # on: 是  off 不是，需要通过api控制
        auto_play           off;
        # 设备将流发送的端口，是否固定
        # on 发送流到多路复用端口 如9000
        # off 自动从rtp_mix_port - rtp_max_port 之间的值中
        # 选一个可以用的端口
        invite_port_fixed     on;

        # 向设备或下级域查询设备列表的间隔，单位(秒)
        # 默认60秒
        query_catalog_interval  60;
    }
}
```

**Comment by winlinvip** [comment]
This may be a problem.

`TRANS_BY_GPT3`

**Comment by feixuezhang** [comment]
![image](https://user-images.githubusercontent.com/57926891/100994939-19d7c300-3592-11eb-81d3-8a6201916bfc.png)
From the packet capture, it can be seen that the server side has a response, but the device side keeps sending registration messages, only with an additional "heard" field in the Route domain. The server does not support the Route domain, so the confirmation messages in the response have some issues.

Route: <sip:21030200001180000001@119.3.17.81:5060;lr>

Attached packet capture message
![image](https://user-images.githubusercontent.com/57926891/100995411-b26e4300-3592-11eb-96c3-0405a6098085.png)

> 
Currently, we are using Dahua's NVR, and we have also encountered this issue with Hikvision's NVR.

`TRANS_BY_GPT3`

**Comment by 9dragon** [comment]
I also encountered the same problem. In the latest develop branch, Dahua camera. I initially thought there was a configuration issue somewhere. The device and server could not be registered despite various restarts. I don't know how to recover from this.

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
@9dragon This is to support the SIP routing mechanism, which replies to SIP messages based on the routing header and corresponding addresses. You can refer to the following article for modification: https://blog.csdn.net/liaoxinmeng/article/details/7179376

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
> @9dragon 这是要支持SIP路由机制，根据路由头部来给相应的地址回复SIP消息。
> 可以参考下面的文章修改一下。https://blog.csdn.net/liaoxinmeng/article/details/7179376

这个是要修改srs代码吗，还是设置摄像头就可以了？

**Comment by iceylm** [comment]
> @9dragon This is to support the SIP routing mechanism, reply SIP messages to the corresponding address based on the routing header.
> You can refer to the following article for modification. https://blog.csdn.net/liaoxinmeng/article/details/7179376

Hello, how should this be modified? Do we include the route information in the response?

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
@iceylm What is your host? I see you are using xxx.xxx.xxx.xxx? 
119.3.17.81, Shanghai, Shanghai, Huawei Cloud; 113.228.8.225, Anshan City, Liaoning Province, China Unicom.
What is your SRS internal IP? What is the public IP for 119.3.17.81 and 113.228.8.225?

It feels like there are some devices between the camera and SRS, such as Huawei Cloud SIP ALG or SIP Proxy. It doesn't seem right to receive packets with a Route header.

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
> @iceylm What is your host? I see you used xxx.xxx.xxx.xxx to represent it?
> 119.3.17.81, Shanghai, China on Huawei Cloud; 113.228.8.225, Anshan City, Liaoning Province, China on China Unicom.
> What is your SRS internal network IP 192.168.0.142? What is the public IP of 119.3.17.81 and 113.228.8.225?
> 
> I feel like there is some device between the camera and SRS, such as Huawei Cloud SIP ALG or SIP proxy. It doesn't seem like we should receive packets with the Route header.

@PieerePi The screenshot above was sent by other team members. The registration protocol I received during debugging is as follows:

REGISTER sip:34020000002000000001@172.17.0.11:55241 SIP/2.0
Via: SIP/2.0/UDP 58.246.230.45:55241;rport;branch=z9hG4bK2018295451
Route: <sip:78978201001320000010@172.17.0.11:5060;lr>
From: <sip:78978201001320000010@58.246.230.45:55241>;tag=2033241836
To: <sip:78978201001320000010@58.246.230.45:55241>
Call-ID: 1835124422@192.168.1.109
CSeq: 1 REGISTER
Contact: <sip:78978201001320000010@58.246.230.45:5061>
Max-Forwards: 70
User-Agent: SIP UAS V2.1.4.500306
Expires: 3600
Content-Length: 0

Those with this type of route cannot register.
My SIP server IP is 121.4.176.246.

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
Please explain all the addresses in your SIP package.

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
Call-ID: 1835124422@192.168.1.109. This IP is the local IP of Dahua camera, and the other IP is the intermediate routing IP. 
My SIP server IP is 121.4.176.246.

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
What is 172.17.0.11?
What is 58.246.230.45?
What is the source address and destination address of this packet?

Is SIP service SRS? 121.4.176.246 is the address of SRS. What is the internal network address of SRS?

Do Dahua cameras register directly with SRS, or do they require Dahua's platform?

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
@PieerePi 
> What is 172.17.0.11? This is the internal address of SRS.  
> What is 58.246.230.45? This is the external IP of the camera.  
> What is the source address and destination address of this packet?
> 
> Is SIP service SRS? Is 121.4.176.246 the address of SRS? What is the internal address of SRS?  
> Yes, SIP is connected to the SRS server, which is deployed on Tencent Cloud. The external address is 121.4.176.246, and the internal address of SRS is 172.17.0.11.

> Does Dahua camera directly register with SRS, or does it have its own platform? 
The camera platform I chose is gb28181, and I have set the SIP server address to the SRS server address 121.4.176.246.



`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
That means the camera is registered directly to SRS. 
Is the SIP port of SRS 5060? What is port 55241 for?

Did you do port forwarding for SRS on the public network? How did you configure the camera with the SIP server?

There must be SIP ALG in this. Tencent Cloud does not have EIP (which can be configured to enable or disable SIP ALG). SIP ALG is enabled by default, so I need to contact customer service to turn it off. However, since SRS directly returns a 200 OK message to the incoming address, it should be able to register successfully.

It's difficult to determine the network issue without packet capture and topology explanation.

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
Two cameras in the same local network are both connected to the same Tencent Cloud SRS server, but the register messages received by SRS are different. 
The message for normal registration is: 
REGISTER sip:34020000002000000001@3402000000 SIP/2.0\r\n
Via: SIP/2.0/UDP 58.246.230.45:5060;rport;branch=z9hG4bK2006538454\r\n
From: <sip:78978201001320000014@3402000000>;tag=2051135311\r\n
To: <sip:78978201001320000014@3402000000>\r\n
Call-ID: 1279297768\r\n
CSeq: 1 REGISTER\r\n
Contact: <sip:78978201001320000014@58.246.230.45:5060>\r\n
Max-Forwards: 70\r\n
User-Agent: IP Camera\r\n
Expires: 3600\r\n
Content-Length: 0\r\n\r\n"

The message for registration failure is:
REGISTER sip:34020000002000000001@172.17.0.11:55241 SIP/2.0
Via: SIP/2.0/UDP 58.246.230.45:55241;rport;branch=z9hG4bK2018295451
Route: <sip:78978201001320000010@172.17.0.11:5060;lr>
From: <sip:78978201001320000010@58.246.230.45:55241>;tag=2033241836
To: <sip:78978201001320000010@58.246.230.45:55241>
Call-ID: 1835124422@192.168.1.109
CSeq: 1 REGISTER
Contact: <sip:78978201001320000010@58.246.230.45:5061>
Max-Forwards: 70
User-Agent: SIP UAS V2.1.4.500306
Expires: 3600
Content-Length: 0


Both of these registration messages are sent from a LAN (local area network), with the external IP being 58.246.230.45. The configurations are from the same SRS (Server Registration Service) server.

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
Registration failed. This registration agreement includes the route parameter. Is the 55241 port allocated by the router itself? Because port 5060 is already occupied by another camera.

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
Normal registration return message:
SIP/2.0 200 OK\r\n
Via: SIP/2.0/UDP 58.246.230.45:5060;rport=5060;received=58.246.230.45;branch=z9hG4bK878839288\r\n
From: <sip:78978201001320000014@3402000000>;tag=1971081623\r\n
To: <sip:78978201001320000014@3402000000>\r\n
CSeq: 1 REGISTER\r\n
Call-ID: 1110626489\r\n
Contact: <sip:78978201001320000014@58.246.230.45:5060>\r\n
User-Agent: SRS/4.0.57(Leo)\r\n
Expires: 3600\r\n
Content-Length: 0\r\n\r\n"

Registration failure return message
SIP/2.0 200 OK\r\n
Via: SIP/2.0/UDP 58.246.230.45:55241;rport=55241;received=58.246.230.45;branch=z9hG4bK86879476\r\n
From: <sip:78978201001320000010@58.246.230.45:55241>;tag=615913199\r\n
To: <sip:78978201001320000010@58.246.230.45:55241>\r\n
CSeq: 1 REGISTER\r\nCall-ID: 1528208607@192.168.1.109\r\n
Contact: <sip:78978201001320000010@58.246.230.45:5061>\r\n
User-Agent: SRS/4.0.57(Leo)\r\n
Expires: 3600\r\n
Content-Length: 0\r\n\r\n"
It seems that this return message did not reach the camera end. The camera will keep requesting registration messages. Initially, the registration was successful and streaming could be played normally. However, after a period of time, it went offline and cannot register anymore.

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
Cameras of the same brand? I can see that the User-Agent is different.
Looking at the packet, it seems that the packet has been modified by an intermediate device. I believe there must be Tencent Cloud's SIP ALG because 172.17.0.11, your local network's gateway device, is definitely unaware of it.
The packet should have reached the camera, but the camera refused it because the content has been altered.

I feel that you need to submit a work order to Tencent Cloud.

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
> Registration failed. This registration agreement includes "route". Is this 55241 port allocated by the router itself? Because 5060 is already occupied by another camera.

Can you try configuring the other camera with local SIP port 5061?

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
> Cameras of the same brand? I see the User-Agent is different.
> Look at the packet, it seems to have been modified by an intermediate device. I think there must be Tencent Cloud's SIP ALG because of 172.17.0.11. Your local network gateway device is probably unaware of it.
> The packet should have reached the camera, but the camera doesn't recognize it because the content has been altered.
> 
> I feel like you need to raise a work order with Tencent Cloud.

Tencent Cloud does not have EIP (configurable to enable or disable SIP ALG). SIP ALG is enabled by default, so you need to contact customer service to turn it off.

I also have machines on Tencent Cloud, running SIP services (at that time without running SRS), and I have submitted a work order to them to disable SIP ALG.

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
> > Registration failed. This registration agreement includes a route, and this port 55241 is allocated by the router itself, right? Because port 5060 is already occupied by another camera.
> 
> Can you try configuring the other camera with the local SIP port 5061?

Hello, after modifying the local SIP port, this problem can be resolved. I will ask Tencent to disable SIP ALG again.

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
> > > Registration failed. The registration agreement includes "route". Is this 55241 port allocated by the router itself? Because 5060 is already occupied by another camera.
> > 
> > 
> > Can you try configuring the other camera with the local SIP port 5061?
> 
> Hi, after modifying the local SIP port, this issue can be resolved. I will also ask Tencent to disable SIP ALG.

Lucky!

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
> > > > Registration failed. The registration agreement includes the route, is this 55241 port assigned by the router itself? Because 5060 is already occupied by another camera.
> > > 
> > > 
> > > Could you try configuring the other camera as the local SIP port 5061?
> > 
> > 
> > Hi, changing the local SIP port can solve this issue. I will ask Tencent to disable SIP ALG.
> 
> Good luck!

Great master, are you saying that not disabling Tencent Cloud SIP ALG and even modifying the local SIP port may not ensure a successful registration? I don't quite understand the underlying principle, please guide me 🙏

`TRANS_BY_GPT3`

**Comment by PieerePi** [comment]
This is because the intermediate device, such as Tencent Cloud SIP ALG, modified the SIP packets. If Tencent Cloud SIP ALG is disabled, the cameras should be able to use port 5060 locally. I have encountered SIP ALG on both AWS and Tencent Cloud (non-EIP machines; EIP machines can be configured by the user to disable it). The built-in SIP ALG is too simplistic and should actually be disabled. It seems like the SIP ALG in your packets is encountering errors.

`TRANS_BY_GPT3`

**Comment by iceylm** [comment]
@PieerePi Hello, after turning off SIP ALG, there is no longer a registration problem. However, there is now an occasional phenomenon where video streams are continuously pushed to SRS, but after a few hours, occasionally, the video stream is not received. Even restarting SRS does not receive the stream. Does this mean the camera has a problem? The camera is still online, but there is no video stream coming through, as shown in the following logs: 

[2021-02-28 02:48:39.184][Trace][6831][n0e83g12] gb28181: client id=34020000001320000001@34020000001320000001,  ssrc=0x8ac005, peer(218.89.222.231, 9712), rtmp muxer is alive
[2021-02-28 02:48:40.994][Trace][6831][3mj7hz2i] Hybrid cpu=0.67%,15MB, cid=1,0, timer=51,0,0, clock=0,46,2,0,0,0,0,0,0
[2021-02-28 02:48:46.101][Trace][6831][3mj7hz2i] Hybrid cpu=0.33%,15MB, cid=1,0, timer=52,0,0, clock=0,46,2,0,0,0,0,0,0
[2021-02-28 02:48:46.970][Trace][6831][id43c83f] gb28181: sip session=34020000001320000001 peer(218.89.222.231, 5088) status(RegisterOk,AliveOk) duration(81,23)
[2021-02-28 02:48:49.167][Trace][6831][n0e83g12] gb28181: client id=34020000001320000001@34020000001320000001,  ssrc=0x8ac005, peer(218.89.222.231, 9712), rtmp muxer is alive
[2021-02-28 02:48:51.197][Trace][6831][3mj7hz2i] Hybrid cpu=0.67%,15MB, cid=1,0, timer=52,0,0, clock=0,46,2,0,0,0,0,0,0
[2021-02-28 02:48:56.303][Trace][6831][3mj7hz2i] Hybrid cpu=0.67%,15MB, cid=1,0, timer=51,0,0, clock=0,47,1,0,0,0,0,0,0
[2021-02-28 02:48:59.196][Trace][6831][3mj7hz2i] <- GBS gb28181: client_id , peer(218.89.222.231, 9712) ps rtp packet 26B, age=2079162774, vt=2/96, sts=29607/3644382000/0x8ac005, paylod=14B
[2021-02-28 02:49:01.411][Trace][6831][3mj7hz2i] Hybrid cpu=0.67%,15MB, cid=1,0, timer=51,0,0, clock=0,47,1,0,0,0,0,0,0
[2021-02-28 02:49:06.523][Trace][6831][3mj7hz2i] Hybrid cpu=1.00%,15MB, cid=1,0, timer=51,0,0, clock=0,46,2,0,0,0,0,0,0
[2021-02-28 02:49:09.195][Trace][6831][3mj7hz2i] <- GBS gb28181: client_id , peer(218.89.222.231, 9712) ps rtp packet 26B, age=2089164874, vt=2/96, sts=30413/3645282000/0x8ac005, paylod=14B
[2021-02-28 02:49:11.638][Trace][6831][3mj7hz2i] Hybrid cpu=0.67%,15MB, cid=1,0, timer=51,0,0, clock=0,46,2,0,0,0,0,0,0
[2021-02-28 02:49:16.722][Trace][6831][3mj7hz2i] Hybrid cpu=0.33%,15MB, cid=1,0, timer=52,0,0, clock=0,47,1,1,0,0,0,0,0

**[2021-02-28 02:49:16.881][Warn][6831][n0e83g12][11] gb28181: client id=34020000001320000001@34020000001320000001 ssrc=0x8ac005, peer(218.89.222.231, 9712), no rtp data 2 in seconds, clean it, wait other port!**

[2021-02-28 02:49:21.468][Trace][6831][n0e83g12] gb28181: client id=34020000001320000001@34020000001320000001,  ssrc=0x8ac005, peer(, 0), rtmp muxer is alive
[2021-02-28 02:49:21.787][Trace][6831][3mj7hz2i] Hybrid cpu=0.33%,15MB, cid=1,0, timer=52,0,0, clock=0,47,1,1,0,0,0,0,0
[2021-02-28 02:49:26.851][Trace][6831][3mj7hz2i] Hybrid cpu=0.00%,15MB, cid=1,0, timer=52,0,0, clock=0,49,1,0,0,0,0,0,0
[2021-02-28 02:49:31.915][Trace][6831][3mj7hz2i] Hybrid cpu=0.00%,15MB, cid=1,0, timer=52,0,0, clock=0,49,1,0,0,0,0,0,0
[2021-02-28 02:49:36.482][Trace][6831][n0e83g12] gb28181: client id=34020000001320000001@34020000001320000001,  ssrc=0x8ac005, peer(, 0), rtmp muxer is alive
[2021-02-28 02:49:36.981][Trace][6831][3mj7hz2i] Hybrid cpu=0.67%,15MB, cid=1,0, timer=52,0,0, clock=0,49,1,0,0,0,0,0,0
[2021-02-28 02:49:42.045][Trace][6831][3mj7hz2i] Hybrid cpu=0.33%,15MB, cid=1,0, timer=52,0,0, clock=0,49,1,0,0,0,0,0,0
[2021-02-28 02:49:44.897][Trace][6831][n0e83g12] gb28181: client id=34020000001320000001@34020000001320000001, stream idle timeout, stop!!!
[2021-02-28 02:49:44.897][Trace][6831][n0e83g12] gb28181: client id=34020000001320000001@34020000001320000001 rtmp muxer is remove
[2021-02-28 02:49:44.897][Trace][6831][n0e83g12] client finished.
[2021-02-28 02:49:44.897][Trace][6831][747x8f06] cleanup when unpublish
[2021-02-28 02:49:44.897][Trace][6831][747x8f06] cleanup when unpublish, created=1, deliver=1
[2021-02-28 02:49:47.001][Trace][6831][id43c83f] gb28181: sip session=34020000001320000001 peer(218.89.222.231, 5088) status(RegisterOk,AliveOk) duration(141,23)
[2021-02-28 02:49:47.093][Trace][6831][3mj7hz2i] Hybrid cpu=0.33%,15MB, cid=1,1, timer=52,0,0, clock=0,49,0,0,0,0,0,0,0, free=1
[2021-02-28 02:49:52.119][Trace][6831][3mj7hz2i] Hybrid cpu=0.00%,15MB, cid=1,1, timer=52,0,0, clock=0,49,0,0,0,0,0,0,0, free=1
[2021-02-28 02:49:57.145][Trace][6831][3mj7hz2i] Hybrid cpu=0.33%,15MB, cid=1,0, timer=52,0,0, clock=0,49,0,0,0,0,0,0,0

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@PieerePi 👍
