### ISSUE TITLE
GB28181: 超时没有发送 Bye 指令

### ISSUE THREAD

**Issue by albyho** [ossrs/srs#2074]
SRS的配置如下(Config):
```
cp_enable off;
rtp_idle_timeout 30;
```
播放器：vlc

备注：也许是我的理解有误。rtp_idle_timeout 是否只是作用于发送端的？在没有接收端的情况下是否自动发送 Bye?

**Comment by winlinvip** [comment]
看full.conf，有说明。

**Comment by ZhouMin216** [comment]
rtp_idle_timeout 之后，srs好像是没有发送bye指令，只是关闭了rtp的监听端口。在超时之后我手动调用sip_invite指令，返回6010，如果超时之后发送了bye指令的话，srs应该是能再次给摄像头下发sip_invite指令的。
