### ISSUE TITLE
为什么不提供一个Snapshot的api接口？

### ISSUE THREAD

**Issue by ghostsf** [ossrs/srs#2079]
https://github.com/ossrs/srs/wiki/v3_CN_Snapshot

RT

**Comment by ghostsf** [comment]
#2083

**Comment by winlinvip** [comment]
Like Patch.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@ghostsf 👍

**Comment by winlinvip** [comment]
Provide API calls for FFmpeg screenshot, the problem-solving capability is limited, and soon there will be many parameters that need to be supported, as well as the need for transcoding.

So it is better to provide a separate service, which is to call FFmpeg, not only can it take screenshots but also can do everything that FFmpeg can do.

It is not very suitable to wrap the FFmpeg API in SRS.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
In the security scenario, screenshots can be taken through canvas on the web end, or screenshots can be controlled through the streaming end for IPC. I am not familiar with the scenario of controlling SRS screenshots through API.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Suggest using FFmpeg to take screenshots.

`TRANS_BY_GPT3`
