### ISSUE TITLE
[Patch] 调用srs_string_replace函数开发出现崩溃

### ISSUE THREAD

**Issue by gzqdust** [ossrs/srs#2084]
**调用kernel_utility.cpp的srs_string_replace函数**

>调用srs_kernel_ultity.cpp中的函数很容易出现崩溃
1. SRS版本(Version): `4.0.56`

```c++
string srs_string_replace(string str, string old_str, string new_str)
{

    std::string ret = str;
    
    if (old_str == new_str) {
        return ret;
    }
    
    size_t pos = 0;
    while ((pos = ret.find(old_str, pos)) != std::string::npos) {
        ret = ret.replace(pos, old_str.length(), new_str);
    }
    
    return ret;
}
    
```

> **出现崩溃的调用条件**

情况一:str和old_str一样的时候死循环无法退出
情况二:new_str包含old_str也死循环无法退出

**期望改变**
情况一:加入判断原来串和目标串是否一样
情况二:加入原来替换的位置,避免重复替换

**Comment by winlinvip** [comment]
Like Patch.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/pull/2580
