### ISSUE TITLE
[Patch] Statistics内存泄漏的问题

### ISSUE THREAD

**Issue by l0g1n** [ossrs/srs#2085]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `3.0.142`
1. 日志
```
[2020-12-07 14:25:36.737][Error][71][873][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
[2020-12-07 14:25:58.970][Error][71][876][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
[2020-12-07 14:26:17.776][Error][71][814][11] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 60000ms, nb_msgs=0
[2020-12-07 14:26:17.799][Error][71][808][11] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 60000ms, nb_msgs=0
[2020-12-07 14:26:18.210][Error][71][831][11] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 60000ms, nb_msgs=0
[2020-12-07 14:26:18.231][Error][71][835][11] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 60000ms, nb_msgs=0
[2020-12-07 14:26:18.248][Error][71][842][11] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 60000ms, nb_msgs=0
[2020-12-07 14:26:18.251][Error][71][841][11] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 60000ms, nb_msgs=0
```
1. SRS的配置如下(Config):
```
listen              1935;
max_connections     5000;
srs_log_tank        file;
srs_log_level       trace;
srs_log_file        ./objs/srs.log;
daemon              on;
http_server {
    enabled         on;
    listen          1980;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;
    raw_api {
        enabled             on;
        allow_reload        on;
        allow_query         on;
        allow_update        on;
    }
}

vhost __defaultVhost__ {
    http_remux {
        enabled     on;
	mount       [vhost]/[app]/[stream].flv;
    }
    tcp_nodelay     on
    min_latency     on;

    play {
        gop_cache       on;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr off;
        firstpkt_timeout    60000;
        normal_timeout      30000;
    }
}
```
使用硬件设备进行推流，大约100路左右的流，内存一直在增加，4天左右时间，内存会达到10G左右。

视频流的ID一直在增加，个人推测是由于设备端不是太稳定，经常断开，频繁推流导致。

使用`pprof`对内存进行了检测。结果如下：

```
(pprof) top37
Total: 56055 objects
   26729  47.7%  47.7%    26729  47.7% std::string::_Rep::_S_create ??:?
   12727  22.7%  70.4%    28152  50.2% SrsStatistic::create_stream /tmp/srs/trunk/trunk/src/app/srs_app_statistic.cpp:609
   12459  22.2%  92.6%    12459  22.2% SrsStatisticStream::SrsStatisticStream /tmp/srs/trunk/trunk/src/app/srs_app_statistic.cpp:120
    2966   5.3%  97.9%     2966   5.3% SrsStatisticStream::SrsStatisticStream /tmp/srs/trunk/trunk/src/app/srs_app_statistic.cpp:119
     518   0.9%  98.8%      518   0.9% st_cond_new /tmp/srs/trunk/trunk/objs/Platform-Linux-5.4.39-SRS3/st-srs/sync.c:157
     514   0.9%  99.7%      514   0.9% _st_stack_new /tmp/srs/trunk/trunk/objs/Platform-Linux-5.4.39-SRS3/st-srs/stk.c:78
      95   0.2%  99.9%       95   0.2% SrsRecvThread::start /tmp/srs/trunk/trunk/src/app/srs_app_recv_thread.cpp:83 (discriminator 1)
      47   0.1% 100.0%       47   0.1% SrsPithyPrint::create_rtmp_publish /tmp/srs/trunk/trunk/src/app/srs_app_pithy_print.cpp:121
       0   0.0% 100.0%       47   0.1% 0x000000000155992f ??:0
       0   0.0% 100.0%       94   0.2% 0x6f452ea41db1a5ff ??:0
       0   0.0% 100.0%      203   0.4% SrsAsyncCallWorker::start /tmp/srs/trunk/trunk/src/app/srs_app_async_call.cpp:83 (discriminator 4)
       0   0.0% 100.0%      202   0.4% SrsBufferCache::start /tmp/srs/trunk/trunk/src/app/srs_app_http_stream.cpp:91
       0   0.0% 100.0%      181   0.3% SrsBufferListener::on_tcp_client /tmp/srs/trunk/trunk/src/app/srs_app_server.cpp:167
       0   0.0% 100.0%    43063  76.8% SrsConnection::cycle /tmp/srs/trunk/trunk/src/app/srs_app_conn.cpp:171
       0   0.0% 100.0%      181   0.3% SrsConnection::start /tmp/srs/trunk/trunk/src/app/srs_app_conn.cpp:79
       0   0.0% 100.0%        2   0.0% SrsCoroutineManager::start /tmp/srs/trunk/trunk/src/app/srs_app_thread.cpp:50
       0   0.0% 100.0%      203   0.4% SrsDvr::on_publish /tmp/srs/trunk/trunk/src/app/srs_app_dvr.cpp:978
       0   0.0% 100.0%      203   0.4% SrsDvrPlan::on_publish /tmp/srs/trunk/trunk/src/app/srs_app_dvr.cpp:619
       0   0.0% 100.0%      203   0.4% SrsDvrSessionPlan::on_publish /tmp/srs/trunk/trunk/src/app/srs_app_dvr.cpp:715
       0   0.0% 100.0%      202   0.4% SrsHttpServer::http_mount /tmp/srs/trunk/trunk/src/app/srs_app_http_conn.cpp:310
       0   0.0% 100.0%      202   0.4% SrsHttpStreamServer::http_mount /tmp/srs/trunk/trunk/src/app/srs_app_http_stream.cpp:936
       0   0.0% 100.0%        2   0.0% SrsIngester::start /tmp/srs/trunk/trunk/src/app/srs_app_ingest.cpp:156 (discriminator 4)
       0   0.0% 100.0%        1   0.0% SrsInotifyWorker::cycle /tmp/srs/trunk/trunk/src/app/srs_app_server.cpp:565 (discriminator 1)
       0   0.0% 100.0%        2   0.0% SrsInotifyWorker::start /tmp/srs/trunk/trunk/src/app/srs_app_server.cpp:551
       0   0.0% 100.0%      178   0.3% SrsNgExec::on_publish /tmp/srs/trunk/trunk/src/app/srs_app_ng_exec.cpp:66 (discriminator 4)
       0   0.0% 100.0%      203   0.4% SrsOriginHub::on_publish /tmp/srs/trunk/trunk/src/app/srs_app_source.cpp:1137
       0   0.0% 100.0%      178   0.3% SrsOriginHub::on_publish /tmp/srs/trunk/trunk/src/app/srs_app_source.cpp:1149
       0   0.0% 100.0%       80   0.1% SrsPublishRecvThread::SrsPublishRecvThread /tmp/srs/trunk/trunk/src/app/srs_app_recv_thread.cpp:288
       0   0.0% 100.0%      274   0.5% SrsPublishRecvThread::start /tmp/srs/trunk/trunk/src/app/srs_app_recv_thread.cpp:354
       0   0.0% 100.0%      179   0.3% SrsRecvThread::start /tmp/srs/trunk/trunk/src/app/srs_app_recv_thread.cpp:85 (discriminator 3)
       0   0.0% 100.0%      597   1.1% SrsRtmpConn::acquire_publish /tmp/srs/trunk/trunk/src/app/srs_app_rtmp_conn.cpp:940
       0   0.0% 100.0%    43063  76.8% SrsRtmpConn::do_cycle /tmp/srs/trunk/trunk/src/app/srs_app_rtmp_conn.cpp:209
       0   0.0% 100.0%       47   0.1% SrsRtmpConn::do_publishing /tmp/srs/trunk/trunk/src/app/srs_app_rtmp_conn.cpp:849
       0   0.0% 100.0%      274   0.5% SrsRtmpConn::do_publishing /tmp/srs/trunk/trunk/src/app/srs_app_rtmp_conn.cpp:853
       0   0.0% 100.0%      597   1.1% SrsRtmpConn::publishing /tmp/srs/trunk/trunk/src/app/srs_app_rtmp_conn.cpp:822
       0   0.0% 100.0%       80   0.1% SrsRtmpConn::publishing /tmp/srs/trunk/trunk/src/app/srs_app_rtmp_conn.cpp:825
       0   0.0% 100.0%      321   0.6% SrsRtmpConn::publishing /tmp/srs/trunk/trunk/src/app/srs_app_rtmp_conn.cpp:826
```

对应的代码部分

![image](https://user-images.githubusercontent.com/7485747/101788705-5c257500-3b3b-11eb-9df3-b42208d5a1a3.png)

![image](https://user-images.githubusercontent.com/7485747/101788603-41530080-3b3b-11eb-894b-faf8b04c8278.png)

**期望行为(Expect)**

希望可以得到一些提示，进行一步的分析，从而解决这个问题。设备端不稳定的问题也会同步跟进。

**Comment by l0g1n** [comment]
By analyzing and judging, it feels like srs_freep(stream) is missing. According to #1988.

https://github.com/ossrs/srs/pull/1988/commits/e7a4e3505ba715ff0d8d1f61a57b59cc31712cb3

Modifications have been made and currently under testing. Hopefully, it can be resolved.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Great job, Patch! It would be even better if you could submit a PR.

`TRANS_BY_GPT3`

**Comment by l0g1n** [comment]
After running for about 20 hours, it was found that the memory increased to 2.7G. I would like to ask if the red box below indicates the presence of a memory leak.
![image](https://user-images.githubusercontent.com/7485747/102236718-c91b7f00-3f2e-11eb-94c4-817fcf1d3acd.png)
The log file is as follows:
`WARNING: Perftools heap leak checker is active -- Performance may suffer
Thread finding failed with -1 errno=1
Could not find thread stacks. Will likely report false leak positives.
Leak check _main_ detected leaks of 77877 bytes in 1864 objects
The 20 largest leaks:
Using local file ./objs/srs.
Leak of 8120 bytes in 145 objects allocated from:
	@ 5aadc3 _st_stack_new
	@ 5aa98b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 570abd SrsRecvThread::start
	@ 571f09 SrsPublishRecvThread::start
	@ 4d1e18 SrsRtmpConn::do_publishing
	@ 4d1c95 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 7896 bytes in 141 objects allocated from:
	@ 5aadc3 _st_stack_new
	@ 5aa98b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 4cb2fa SrsConnection::start
	@ 4c732c SrsServer::accept_client
	@ 4bf729 SrsBufferListener::on_tcp_client
	@ 58e6d0 SrsTcpListener::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 7896 bytes in 141 objects allocated from:
	@ 5aadc3 _st_stack_new
	@ 5aa98b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 596026 SrsNgExec::on_publish
	@ 4da141 SrsOriginHub::on_publish
	@ 4dfeeb SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 7728 bytes in 138 objects allocated from:
	@ 570a60 SrsRecvThread::start
	@ 571f09 SrsPublishRecvThread::start
	@ 4d1e18 SrsRtmpConn::do_publishing
	@ 4d1c95 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 7448 bytes in 133 objects allocated from:
	@ 5aadc3 _st_stack_new
	@ 5aa98b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 4f3b68 SrsBufferCache::start
	@ 4f894f SrsHttpStreamServer::http_mount
	@ 5548c7 SrsHttpServer::http_mount
	@ 4c8016 SrsServer::on_publish
	@ 4dff7b SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _s
Leak of 6832 bytes in 122 objects allocated from:
	@ 5aadc3 _st_stack_new
	@ 5aa98b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 58eb65 SrsAsyncCallWorker::start
	@ 5a36aa SrsDvrPlan::on_publish
	@ 5a3cd6 SrsDvrSessionPlan::on_publish
	@ 5a4f59 SrsDvr::on_publish
	@ 4da081 SrsOriginHub::on_publish
	@ 4dfeeb SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 S
Leak of 5712 bytes in 14 objects allocated from:
	@ 57576d SrsStatisticStream::SrsStatisticStream
	@ 5791d9 SrsStatistic::create_stream
	@ 578436 SrsStatistic::on_stream_publish
	@ 4dffe6 SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 5244 bytes in 138 objects allocated from:
	@ 7f12f668aa19 std::string::_Rep::_S_create
	@ 548acfb226321700 0x548acfb226321700
Leak of 2000 bytes in 125 objects allocated from:
	@ 5ab28d st_cond_new
	@ 5aaa8b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 58eb65 SrsAsyncCallWorker::start
	@ 5a36aa SrsDvrPlan::on_publish
	@ 5a3cd6 SrsDvrSessionPlan::on_publish
	@ 5a4f59 SrsDvr::on_publish
	@ 4da081 SrsOriginHub::on_publish
	@ 4dfeeb SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 Srs
Leak of 1984 bytes in 124 objects allocated from:
	@ 5ab28d st_cond_new
	@ 4b1513 srs_cond_new
	@ 5717cf SrsPublishRecvThread::SrsPublishRecvThread
	@ 4d1c68 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 1920 bytes in 120 objects allocated from:
	@ 5ab28d st_cond_new
	@ 5aaa8b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 596026 SrsNgExec::on_publish
	@ 4da141 SrsOriginHub::on_publish
	@ 4dfeeb SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 1904 bytes in 14 objects allocated from:
	@ 5791ce SrsStatistic::create_stream
	@ 578436 SrsStatistic::on_stream_publish
	@ 4dffe6 SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 1904 bytes in 119 objects allocated from:
	@ 5ab28d st_cond_new
	@ 5aaa8b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 570abd SrsRecvThread::start
	@ 571f09 SrsPublishRecvThread::start
	@ 4d1e18 SrsRtmpConn::do_publishing
	@ 4d1c95 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 1888 bytes in 118 objects allocated from:
	@ 5ab28d st_cond_new
	@ 5aaa8b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 4cb2fa SrsConnection::start
	@ 4c732c SrsServer::accept_client
	@ 4bf729 SrsBufferListener::on_tcp_client
	@ 58e6d0 SrsTcpListener::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 1824 bytes in 57 objects allocated from:
	@ 53f45b SrsPithyPrint::create_rtmp_publish
	@ 4d1dd6 SrsRtmpConn::do_publishing
	@ 4d1c95 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 1760 bytes in 110 objects allocated from:
	@ 5ab28d st_cond_new
	@ 5aaa8b st_thread_create
	@ 5006ec SrsSTCoroutine::start
	@ 4f3b68 SrsBufferCache::start
	@ 4f894f SrsHttpStreamServer::http_mount
	@ 5548c7 SrsHttpServer::http_mount
	@ 4c8016 SrsServer::on_publish
	@ 4dff7b SrsSource::on_publish
	@ 4d2a7f SrsRtmpConn::acquire_publish
	@ 4d1bc8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_
Leak of 1711 bytes in 59 objects allocated from:
	@ 7f12f668aa19 std::string::_Rep::_S_create
	@ 1ebf9f0 0x0000000001ebf9f0
Leak of 1224 bytes in 3 objects allocated from:
	@ 57576d SrsStatisticStream::SrsStatisticStream
	@ 5791d9 SrsStatistic::create_stream
	@ 5784ad SrsStatistic::on_stream_close
	@ 4e0143 SrsSource::on_unpublish
	@ 4d2b3c SrsRtmpConn::release_publish
	@ 4d1cf8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Leak of 1214 bytes in 19 objects allocated from:
	@ 7f12f668aa19 std::string::_Rep::_S_create
Leak of 408 bytes in 3 objects allocated from:
	@ 5791ce SrsStatistic::create_stream
	@ 5784ad SrsStatistic::on_stream_close
	@ 4e0143 SrsSource::on_unpublish
	@ 4d2b3c SrsRtmpConn::release_publish
	@ 4d1cf8 SrsRtmpConn::publishing
	@ 4cf551 SrsRtmpConn::stream_service_cycle
	@ 4ce4c1 SrsRtmpConn::service_cycle
	@ 4cd41c SrsRtmpConn::do_cycle
	@ 4cb7b6 SrsConnection::cycle
	@ 500a2e SrsSTCoroutine::cycle
	@ 500aa3 SrsSTCoroutine::pfn
	@ 5aa2fa _st_thread_main
	@ 5aaa6a st_thread_create
Skipping leaks numbered 20..35


If the preceding stack traces are not enough to find the leaks, try running THIS shell command:

pprof ./objs/srs "/tmp/srs.664._main_-end.heap" --inuse_objects --lines --heapcheck  --edgefraction=1e-10 --nodefraction=1e-10 --gv

If you are still puzzled about why the leaks are there, try rerunning this program with HEAP_CHECK_TEST_POINTER_ALIGNMENT=1 and/or with HEAP_CHECK_MAX_POINTER_OFFSET=-1
If the leak report occurs in a small fraction of runs, try running with TCMALLOC_MAX_FREE_QUEUE_SIZE of few hundred MB or with TCMALLOC_RECLAIM_MEMORY=false, it might help find leaks more repeatabl
Exiting with error code (instead of crashing) because of whole-program memory leaks`

`TRANS_BY_GPT3`

**Comment by dragon8609** [comment]
Actually, there is still a memory leak here. The real leak is in SrsStatistic::on_stream_close, where the map removes that stream, but it is not released before removal. The stream should also be released here.
void SrsStatistic::on_stream_close(SrsRequest* req)
{
    SrsStatisticVhost* vhost = create_vhost(req);
    SrsStatisticStream* stream = create_stream(vhost, req);
    stream->close();
    
    // TODO: FIXME: Should fix https://github.com/ossrs/srs/issues/803
    if (true) {
        std::map<int64_t, SrsStatisticStream*>::iterator it;
        if ((it=streams.find(stream->id)) != streams.end()) {
            delete it->second;//------------------------------------------------------------------------here
            streams.erase(it);
        }
    }
    
    // TODO: FIXME: Should fix https://github.com/ossrs/srs/issues/803
    if (true) {
        std::map<std::string, SrsStatisticStream*>::iterator it;
        if ((it=rstreams.find(stream->url)) != rstreams.end()) {
            rstreams.erase(it);
        }
    }
}

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The memory seems to be occupied by cond and stack, and it appears that the coroutine is continuously growing without being released. You can investigate this.

`TRANS_BY_GPT3`

**Comment by l0g1n** [comment]
Actually, there is still a memory leak here. The real leak is in SrsStatistic::on_stream_close. The map removes that stream, but it is not released before removal. The stream should also be released here.
> void SrsStatistic::on_stream_close(SrsRequest* req)
> {
> SrsStatisticVhost* vhost = create_vhost(req);
> SrsStatisticStream* stream = create_stream(vhost, req);
> stream->close();
> 
> ```
> // TODO: FIXME: Should fix https://github.com/ossrs/srs/issues/803
> if (true) {
>     std::map<int64_t, SrsStatisticStream*>::iterator it;
>     if ((it=streams.find(stream->id)) != streams.end()) {
>         delete it->second;//------------------------------------------------------------------------here
>         streams.erase(it);
>     }
> }
> 
> // TODO: FIXME: Should fix https://github.com/ossrs/srs/issues/803
> if (true) {
>     std::map<std::string, SrsStatisticStream*>::iterator it;
>     if ((it=rstreams.find(stream->url)) != rstreams.end()) {
>         rstreams.erase(it);
>     }
> }
> ```
> 
> }

Thank you for the response. After testing, it was found that there is no need to release it here. Because every time the streaming end exits, after executing `void SrsStatistic::on_stream_close(SrsRequest* req)`, `void SrsStatistic::on_disconnect(int id)` will be executed, and `srs_freep(stream)` will be executed in this function.

```
void SrsStatistic::on_disconnect(int id)
{
    std::map<int, SrsStatisticClient*>::iterator it;
    if ((it = clients.find(id)) == clients.end()) {
        return;
    }
    
    SrsStatisticClient* client = it->second;
    SrsStatisticStream* stream = client->stream;
    SrsStatisticVhost* vhost = stream->vhost;
    
    srs_freep(client);
    clients.erase(it);
    
    stream->nb_clients--;
    vhost->nb_clients--;

    if ((!stream->active) && (0 == stream->nb_clients)) {
        on_stream_close(stream);
        srs_freep(stream);
    }
}
```

When both the streaming end and multiple playback ends are running, there are two scenarios for exiting:
1. If the streaming end exits first and the last playback end also exits, `srs_freep(stream)` will be executed.
2. If all the playback ends exit and then the streaming end exits, `srs_freep(stream)` will be executed.

`TRANS_BY_GPT3`

**Comment by l0g1n** [comment]
Using valgrind to perform memory detection on the program, it was found that the memory leak was not as severe as expected. The situation is as follows: 

![image](https://user-images.githubusercontent.com/7485747/102470215-a902d180-408e-11eb-8b39-6c13814728e5.png)


Complete log
[valgrind.log](https://github.com/ossrs/srs/files/5708329/valgrind.log)

`TRANS_BY_GPT3`

**Comment by dragon8609** [comment]
> on_stream_close
Hello, I didn't see this code on Git. Did you add this code yourself?
    if ((!stream->active) && (0 == stream->nb_clients)) {
        on_stream_close(stream);
        srs_freep(stream);
    }

`TRANS_BY_GPT3`

**Comment by l0g1n** [comment]
> > on_stream_close
> > Hello, I didn't see this code on Git. Did you add this code yourself?
> > if ((!stream->active) && (0 == stream->nb_clients)) {
> > on_stream_close(stream);
> > srs_freep(stream);
> > }

According to #1988 e7a4e35.

It should be that the author has not merged it into the official version yet.

`TRANS_BY_GPT3`

**Comment by dragon8609** [comment]
Thank you!

`TRANS_BY_GPT3`

**Comment by dragon8609** [comment]
There is still a question here. After you mentioned `void SrsStatistic::on_stream_close(SrsRequest* req)`, `void SrsStatistic::on_disconnect(int id)` will be executed once.

Then why do we need to define another `on_stream_close(SrsStatisticStream* stream)`?

`on_stream_close(SrsRequest* req)` has already removed the stream from both the `streams` and `rstreams` maps.

`TRANS_BY_GPT3`

**Comment by l0g1n** [comment]
> There is still a question here. After you said `void SrsStatistic::on_stream_close(SrsRequest* req)`, `void SrsStatistic::on_disconnect(int id)` will be executed once.
> 
> Then why do we need to define `on_stream_close(SrsStatisticStream* stream)` separately?
> 
> `on_stream_close(SrsRequest* req)` has already removed the stream from both the `streams` and `rstreams` maps.

If this is not present, after running for a while, you will see some idle connections on the console, but it is not clear how these connections are generated.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Haha, #1988 PR was suggested by me, please test it more thoroughly. If there are no issues, urge Boss Yang to merge it quickly.
To be honest, there are a few memory leaks in the Statistic module, but some are not significant. It's fine even if they leak for a year, I'm just too lazy to fix them.

`TRANS_BY_GPT3`

**Comment by l0g1n** [comment]
> Haha, #1988 PR was raised by me, please test it thoroughly. If there are no issues, urge Mr. Yang to merge it quickly.
> To be honest, there are a few memory leaks in the Statistic module, but some are not significant. It's not a big deal even if it leaks for a year, so I'm too lazy to fix it.

Please point out where else there are memory leaks in the Statistic module. The memory usage is still increasing significantly during my testing. It might be due to the unstable streaming from the device I'm using.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Looking at your vld log, it seems that there is a stream leak in the statistic module. You should add logs in both `on_stream_publish` and `on_stream_close` functions, and theoretically, they should appear in pairs. If there is a leak, it is likely that `on_stream_close` is not being executed. Please trace it based on this clue and provide feedback once you have results.
@l0g1n

`TRANS_BY_GPT3`

**Comment by l0g1n** [comment]
> According to your vld log, it seems that there is a stream leak in the statistic module. You should add logs in both `on_stream_publish` and `on_stream_close` functions, and they should ideally appear in pairs. If there is a leak, it is likely that `on_stream_close` is not being executed. Please trace it based on this clue.
> Remember to provide feedback once you have results.
> @l0g1n

> After running for approximately 3 days and 22 hours, `on_stream_publish` was executed 45,108 times, `on_stream_close` was executed 45,019 times, and the console displayed that there are still 89 streams online. This means that `on_stream_publish` and `on_stream_close` are appearing in pairs, so this part seems to be fine. The issue might be somewhere internally, but it has not been identified yet. Do you have any other ideas or suggestions?
> Remember to maintain the markdown structure.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
那你看一下`create_stream`这个函数，有多个函数调用它，比如`on_video_info`或者`on_video_frames`等。
`create_stream`这个函数实现了2个功能，find or create。所以，我猜测是close之后，有其他函数（比如on_video_info）又重新创建了这个stream。
说实话，我一度想把`create_stream`拆成2个函数的，你可以试试。

**Comment by guiyongdong** [comment]
Have you resolved it?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed
