### ISSUE TITLE
SRS-API 为啥没有集群模式？

### ISSUE THREAD

**Issue by 1187046272** [ossrs/srs#2089]
**描述(Description)**

> 搭建了源站和边缘集群，调用某台的API查询推流列表，发现只有当前节点的列表，没有其他节点的推流信息

**期望行为(Expect)**
> 我想，能不能也把API加上集群功能。这样前边搞个负载均衡调用进来，就能获取所有节点的推流信息了。

**Comment by winlinvip** [comment]
SRS is a server, and the cluster mode of the API needs to be resolved by yourself.

`TRANS_BY_GPT3`

**Comment by 1187046272** [comment]
Uh. It's not very closed-loop. The streaming media has support for 302 redirection in cluster mode. I think the API should also support it. Just my personal opinion, I have already encapsulated it myself.
Also, when scaling the cluster, all the old nodes need to be configured again. Is there a way to solve this? Should we introduce some components similar to a registry center to achieve dynamic scaling?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS is a server and cannot be used for API clustering.

`TRANS_BY_GPT3`
