### ISSUE TITLE
SRS4.0 GB28181怎么手动控制开启和关闭流媒体调用?

### ISSUE THREAD

**Issue by qythker** [ossrs/srs#2090]
我看了很多文章 都只说当配置正确SRS自动调用INVATE 来获得设备端的流媒体数据
我想通过程序实现控制SRS调用和关闭设备的流媒体应该怎么处理,WIKI上面好像没的
auto_play       这个可以配置自动
我关闭后通过什么API来处理?28181的SIP命令?还是什么?

**Comment by xbpeng121** [comment]
@qythker 使用http://127.0.0.1:1985/api/v1/gb28181?action=sip_invite&id=44010000003402000000&chid=44010000001321000001 这http的接口来Invate

**Comment by xbpeng121** [comment]
详情接口请看文档：https://github.com/xialixin/srs/wiki

**Comment by qythker** [comment]
感谢
