### ISSUE TITLE
WebRTC to RTMP publishing

### ISSUE THREAD

**Issue by akalantari** [ossrs/srs#2093]
**描述(Description)**
I need a configuration to be able to publish through WebRTC and play the stream in RTMP.
I have been able to publish through RTMP and playback in RTC, but can't do the otherway around.

1. SRS版本(Version): `v4.0.56`

**期望行为(Expect)**
Publish through RTC and receive in RTMP

**Comment by sanosay** [comment]
Hello, same problem here. Would be great that this can be included in the documentation, as for my project without it, that's a show stopper :|

**Comment by bigben0123** [comment]
webRtc uses RTP for publishing, and SDP for answering. It is possible to use ffmpeg to push SDP to RTMP.

`TRANS_BY_GPT3`

**Comment by ghostsf** [comment]
> Use RTP to receive WebRTC publishing, and SDP for reply. You can use ffmpeg to push SDP to RTMP.

To push SDP using ffmpeg, you can use the following command:

```bash
ffmpeg -protocol_whitelist file,rtp,udp -i input.sdp -c copy -f flv rtmp://your-rtmp-server-url
```

Replace `input.sdp` with the path to your SDP file, and `your-rtmp-server-url` with the URL of your RTMP server. This command will copy the input stream without any transcoding and push it to the specified RTMP server.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Xia Lixin is working on this feature, please be patient.

`TRANS_BY_GPT3`

**Comment by ZW970123** [comment]
When starting rtc_to_rtmp in live broadcasting with two-way communication, the browser playback window turns black, and the value of code is 400. How can this be resolved?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed
