### ISSUE TITLE
srs 4.0webrtc协议拉流不能触发httpcallback 

### ISSUE THREAD

**Issue by wangjinqian0406** [ossrs/srs#2098]
srs 4.0webrtc协议拉流不能触发httpcallback ？
我用rtmp拉流能够触发回调接口，webrtc拉流就不行

**Comment by xiaojiege123** [comment]
Same question, I also encountered this problem, seeking a solution from the experts.

`TRANS_BY_GPT3`

**Comment by ghostsf** [comment]
Not done.

`TRANS_BY_GPT3`

**Comment by matclayton** [comment]
We have the same issue here as well.

**Comment by siyangbing** [comment]
> Not done

> Can you help me do it?

`TRANS_BY_GPT3`

**Comment by siyangbing** [comment]
> > Did not do
> 
> Can you help me do it?

> Recently, I need to use it. It should have a wide application in the future.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.

**Comment by wangjinqian0406** [comment]
Thank you ------------------ Original Email ------------------
***@***.***&gt;
Sending time: 2021 August 22nd (Sunday) 10:07 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject: Re: [ossrs/srs] srs 4.0 webrtc protocol pulling cannot trigger http callback (#2098)

`TRANS_BY_GPT3`
