### ISSUE TITLE
srs-libtrmp测试代码，从推流到播放需要8s，怎么回事？

### ISSUE THREAD

**Issue by guoyanzhang0817** [ossrs/srs#2103]
pc1先执行：
`ffplay rtmp://192.168.1.108:1935/mytv/01`
pc2后执行：
` ./srs_h264_raw_publish ../720p.h264.raw rtmp://192.168.1.108:1935/mytv/01 25
`
rtmp server就是在本地，从推流到播放，竟然用了8s，怎么回事？

**Comment by winlinvip** [comment]
不再支持srslibrtmp，可以用librtmp。

**Comment by atlantis414** [comment]
> librtmp

把h264数据包推送给srs有更好的方法吗?
