### ISSUE TITLE
srs4.0make时报错

### ISSUE THREAD

**Issue by lingfengfushui** [ossrs/srs#2107]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.55、4.0.56`
1. SRS的日志如下(Log):
g++ -c -ansi -Wall -Wno-deprecated-declarations -g -O0 \
    -Isrc/protocol -Isrc/core -Isrc/kernel \
    -Iobjs -Iobjs/st -Iobjs/openssl/include -Iobjs/srtp2/include -Iobjs/ffmpeg/include -Iobjs/opus/include \
    -o objs/src/protocol/srs_service_st.o \
    src/protocol/srs_service_st.cpp
g++ -c -ansi -Wall -Wno-deprecated-declarations -g -O0 \
    -Isrc/protocol -Isrc/core -Isrc/kernel \
    -Iobjs -Iobjs/st -Iobjs/openssl/include -Iobjs/srtp2/include -Iobjs/ffmpeg/include -Iobjs/opus/include \
    -o objs/src/protocol/srs_service_http_client.o \
    src/protocol/srs_service_http_client.cpp
src/protocol/srs_service_http_client.cpp: In member function ‘virtual SrsCplxError* SrsSslClient::handshake()’:
src/protocol/srs_service_http_client.cpp:80: error: ‘TLS_method’ was not declared in this scope
src/protocol/srs_service_http_client.cpp: In member function ‘virtual SrsCplxError* SrsSslClient::read(void*, size_t, ssize_t*)’:
src/protocol/srs_service_http_client.cpp:202: warning: comparison between signed and unsigned integer expressions
make[2]: *** [objs/src/protocol/srs_service_http_client.o] Error 1
make[2]: Leaving directory `/home/g3media/local/srs4r0/trunk'
make[1]: *** [server] Error 2
make[1]: Leaving directory `/home/g3media/local/srs4r0/trunk'

2、操作系统版本：readhat 6.9

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
能正常make使用srs4.0

**Comment by winlinvip** [comment]
readhat 6.9 对应的是CentOS6吧？请使用docker编译，参考 ossrs/srs-docker
