### ISSUE TITLE
通过dvr配置保存flv文件时，偶发flv文件保存路径不对

### ISSUE THREAD

**Issue by wuzhidefeng** [ossrs/srs#2110]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `3.0`
1. SRS的日志如下(Log):
没有error
1. SRS的配置如下(Config):
vhost __defaultVhost__ {

	tcp_nodelay     on;
        min_latency     on;
	gop_cache       off;
	queue_length    4;
	mw_latency      100;
	mr off;
		
	#保存直播为flv
	dvr {
        enabled         on;
        dvr_path        /home/nvidia/video/[app]/[stream].[timestamp].flv;#保存flv路径
        dvr_plan        segment;#时间模式
        dvr_duration    3600;#600秒
        dvr_wait_keyframe       on;
        time_jitter             full;
 
   }

}

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 推送视频，视频流的地址为rtmp://127.0.0.1/live/livestream/MTY2004-A1014

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
视频文件应该被保存在/home/nvidia/video/live/livestream目录下。但是目前出现偶发视频文件被保存在/home/nvidia/video/live和/home/nvidia/video/live/livestream/livestream这两个目录。

**Comment by winlinvip** [comment]
这是流路径的问题，你别弄多级stream，就标准的：rtmp://host/app/stream 就行。
如果要弄多级，自己好好看代码。
