### ISSUE TITLE
Delivery DASH-support Hevc

### ISSUE THREAD

**Issue by caojunwei1988** [ossrs/srs#2119]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
reference v4.x support hevc(h.265) RTMP streaming #1721
hls is ok. but delivery dash can not work.（play with vlc Display black screen and the audio played ok）

1. SRS版本(Version): `feature/h265`
1. SRS的日志如下(Log):
log no error infos
1. SRS的配置如下(Config):
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [app]/[stream].flv;
    }
    hls {
        enabled         on;
        hls_vcodec      h265;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
    }
    dash {
        enabled         on;
        dash_fragment       30;
        dash_update_period  150;
        dash_timeshift      300;
        dash_path           ./objs/nginx/html;
        dash_mpd_file       [app]/[stream].mpd;
    }
}
2.ffmpeg推流脚本如下：

#!/bin/sh

for((;;)); do
        /workspace/hevc_ffmpeg/FFmpeg/ffmpeg -re -i ./localvideos/withaudioH265.mp4 -vcodec copy -acodec copy -f flv -y rtmp://10.72.55.67/live/livestream;
        sleep 1;
done

testvideo:
链接：https://pan.baidu.com/s/1M-anNGOHN3HGfNk3_MGwEA 
提取码：9b96 

3.vlc 错误日志

mp4 info: Fragment sequence discontinuity detected 53638234 != 0
mp4 error: missing avcC
mp4 info: Fragment sequence discontinuity detected 53638234 != 0
main error: buffer deadlock prevented

4.dah.js(http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html)错误:

MEDIA_ERR_SRC_NOT_SUPPORTED (CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=730 append_window_start=0 append_window_end=inf)

**重现(Replay)**

必现

**期望行为(Expect)**

VLC/hls.dash Play audio and video normally

**Comment by caojunwei1988** [comment]
![image](https://user-images.githubusercontent.com/39397839/103204432-52b94c80-4932-11eb-95d1-aa5f7a9daf55.png)

i found mp4box in srs not supprt hvc1

**Comment by caojunwei1988** [comment]
找到另一个开源项目ZLMediaKit是支持ws+fmp4，正好复合我的需要。
正在熟悉，后期评估是否可以添加到srs。

**Comment by winlinvip** [comment]
HEVC暂时没有计划支持。

**Comment by winlinvip** [comment]
Dup to #465
