### ISSUE TITLE
GB28181: 将SIP用户名和密码等信息通过回调传送给param参数

### ISSUE THREAD

**Issue by ox188** [ossrs/srs#2120]
目前，回调函数传送的函数有一个参数为param，其传送的值为“?k=v”
【建议1】：能否将参数param的值前面的？去了，将原来的“?k=v”变为“k=v”，虽然业务程序可以处理这个？，但感觉去掉比较好点；
【建议2】：能否在on_connect事件中，也直接传送param参数，虽然通过"tcUrl": "rtmp://x/x?key=xxx"也能拿到参数，但直接传送param值后台处理会方便一点；
【建议3】：在GB28181中，能否将SIP用户名（SIP账号/设备编号）、SIP密码(注册密码)等信息通过回调传送给param参数，这样在业务程序处理时就方便多了，也可以限制非法用户注册sip。

**Comment by winlinvip** [comment]
Suggestions 1 and 2 are non-compatible changes, although they are reasonable, I'm sorry but we cannot implement them as it would cause a block for users who have already upgraded.

Suggestion 3 is reasonable and should be implemented. Thank you.

`TRANS_BY_GPT3`

**Comment by ox188** [comment]
winlinvip, thank you Teacher Yang!

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> [Suggestion 3]: In GB28181, can the SIP username (SIP account/device number), SIP password (registration password), and other information be transmitted to the `param` parameter through callbacks? This would make it much more convenient for business program processing and also allow for restricting illegal user registration of SIP.

@ox188 
>We need to discuss Suggestion 3 again.

>Firstly, there is already an authentication process during SIP registration, but currently it is not supported. Even if we were to implement it, I think it should be done using the standard SIP procedure instead of callbacks.
>
>Secondly, we are considering removing the SIP functionality and only keeping the media part.

>So, if you have no objections, I am planning to close this issue in 2 weeks. Feel free to continue the discussion.

`TRANS_BY_GPT3`
