### ISSUE TITLE
访问网站时 Not Found

### ISSUE THREAD

**Issue by amiormu** [ossrs/srs#2122]
感谢大佬们制作如此优秀的作品。
我是个萌新 还不太会 弱弱的提一个问题：）
[IP:8080/console/en_index.html#/streams](url)

[IP:8080/players/rtc_player.html](url)

在访问网站时，总会出现 Not Found的情况，是什么原因呢？

**Comment by mawenwu1983** [comment]
Because besides the SRS installed with Docker, there is no "console" folder under "objs/nginx/html". You need to copy and paste it in, or use the Docker image.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@mawenwu1983 👍

**Comment by winlinvip** [comment]
Fixed, the new one will package the console.

`TRANS_BY_GPT3`
