### ISSUE TITLE
MigrateNginx：根据提供不同的app向不同的源站拉流

### ISSUE THREAD

**Issue by huzhou520** [ossrs/srs#2125]
我想要通过不同的app，向不同的源站拉流；
我之前用的是nginx-rtmp这么做的，现在向srs迁移，想用SRS实现同样的功能；但我不知道怎么配置，wiki中也没有找到；
nginx-rtmp application配置如下：

```
application 17live {
    live on;
    wait_key on;
    wait_video on;
    pull rtmp://10.2.3.10:2935/17live live=1;
}

application 17test {
    live on;
    wait_key on;
    wait_video on;
    pull rtmp://10.4.11.200/17live live=1;
}

application 17zy {
    live on;
    wait_key on;
    wait_video on;
    push rtmp://10.4.19.59/17live;
}

```

**Comment by winlinvip** [comment]
SRS是vhost（域名），比app更强大。除了app，可以用不同的域名区域用户。

比如，Nginx是：

* `rtmp://127.0.0.1/live/stream0`，回源到A
* `rtmp://127.0.0.1/live/stream1`，回源到A
* `rtmp://127.0.0.1/edu/stream0`，回源到B

而SRS的回源是通过vhost：

* `rtmp://127.0.0.1/live/stream0?vhost=live.com`，回源到A
* `rtmp://127.0.0.1/live/stream1?vhost=live.com`，回源到A
* `rtmp://127.0.0.1/edu/stream0?vhost=edu.com`，回源到B

所以SRS能做到同样的app和stream不冲突：

* `rtmp://127.0.0.1/live/stream0?vhost=live.com`，回源到A
* `rtmp://127.0.0.1/live/stream1?vhost=live.com`，回源到A
* `rtmp://127.0.0.1/live/stream0?vhost=edu.com`，回源到B

这样SRS比Nginx的功能更强大。
