### ISSUE TITLE
小白 请教，./configure &&make 没有自带FFMPEG， 自己找个地方装了， 转码贴图无法成功。

### ISSUE THREAD

**Issue by btswts** [ossrs/srs#2129]
./configure &&make 没有自带FFMPEG， 自己找个地方装了， 贴图转码 无法成功。
vfilter 有没有注掉，都不成功。    是机器性能要求高呢，还是哪里有点问题？
FFMPEG 功能的教程是否更新下。

vhost logo {
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        ffmpeg      /usr/local/bin/ffmpeg;
        engine {
            enabled         on;
          

            iformat         flv;
            vfilter {
           #     i               ./doc/ffmpeg-logo.png;
           #     filter_complex  'overlay=100:100';
            }
            vcodec          libx264;
            vbitrate        1500;
            vfps            10;
            vwidth          768;
            vheight         320;
            vthreads        1;
            vprofile        main;
            vpreset         medium;
            vparams {
                t               100;
                coder           1;
                b_strategy      2;
                bf              3;
                refs            10;
            }
            acodec          libfdk_aac;
            abitrate        70;
            asample_rate    44100;
            achannels       2;
            aparams {
                profile:a   aac_low;
            }
            oformat         flv;
            output          rtmp://127.0.0.1:[port]/logo/livestream;
        }
    }
}

**Comment by ghostsf** [comment]
./configure --with-ffmpeg 确实有问题 

![image](https://user-images.githubusercontent.com/9978816/104299871-b16cf180-5500-11eb-8db3-ed3c7242724e.png)

不管有没有 --with-ffmpeg 都会默认软链到/usr/local/bin/ffmpeg，--with-ffmpeg 只会提醒下如果没装ffmepg ...

很有歧义

既然有了引用了ffmpeg的源码，为何不直接编一个

@winlinvip

**Comment by winlinvip** [comment]
源码只是用来做内部转码的，没有完整的FFmepg和依赖的库。

FFmpeg有完整的编译链，编译文档和库，放在SRS中不合适，有很多问题。
