### ISSUE TITLE
使用域名推流到srs，再forward到阿里云CDN失败

### ISSUE THREAD

**Issue by langyastudio** [ossrs/srs#2130]
一、背景
1、在ECS服务器自建了SRS流媒体服务
域名为 srs.xxx.com
2、在阿里云CDN直播中心创建了推流域名
域名为 cloud-push.xxx.com
3、业务需求
将本地流推送到SRS流媒体服务（srs.xxx.com），再由SRS流媒体服务器forward到阿里云CDN（cloud-push.xxx.com），从而实现大规模播放直播的需求
4、版本
使用 3.0.156 版本测试

二、出现问题
1、当使用域名为srs.xxx.com时，SRS流媒体服务器报告forward相关错误 —— 即forward失败
rtmp://srs.xxx.com/live/stream?key=9aa98e26&token=aNc28YIy
2、当使用IP时，forward成功
rtmp://IP/live/stream?key=9aa98e26&token=aNc28YIy
3、关键配置
为方便测试，关闭了阿里云CDN的推流校验
```
vhost __defaultVhost__ {
    enabled on;
    forward {
        enabled on;     
        destination cloud-push.xxx.com;
    }
}
```
4、域名失败的错误信息：
![image](https://user-images.githubusercontent.com/38461274/103740026-7450bd00-5031-11eb-81bc-ba7f78419d5c.png)

_Originally posted by @langyastudio in https://github.com/ossrs/srs/issues/1202#issuecomment-755128696_

**Comment by BradChan** [comment]
The same mistake

`TRANS_BY_GPT3`

**Comment by lingfengfushui** [comment]
I also encountered a similar problem. I tried several versions of 3.0, but it's the same: streaming with IP to SRS, then forwarding to other CDN domains works fine, and watching with VLC is normal. However, streaming with a domain to SRS, then forwarding to other CDN domains, the logs do not show any abnormalities, but VLC cannot open it. I contacted the technical personnel on the other side and they said they did not receive the stream.

`TRANS_BY_GPT3`

**Comment by langyastudio** [comment]
In addition, it is also important to improve the success rate and stability of the forward.

@liguocahng https://github.com/ossrs/srs/issues/1202#issuecomment-684624885
The problem still exists (not reproducible every time):
Streaming to SRS, then forwarding to Alibaba Cloud server through configuration file, the online stream is not displayed on the Alibaba Cloud server, but the resource monitoring in the domain management shows resource flow, and the video cannot be played.

`TRANS_BY_GPT3`

**Comment by langyastudio** [comment]
@winlinvip, please pay attention to this issue.

`TRANS_BY_GPT3`

**Comment by liguocahng** [comment]
I solved this problem using 2.0 at that time, but 3.0 cannot push the stream.

`TRANS_BY_GPT3`

**Comment by langyastudio** [comment]
Thank you.
I am using version 3.0.156. Today, I contacted Alibaba Cloud technical support:
1) Forwarding to Alibaba Cloud - actual streaming success, but playback failure.
2) Alibaba Cloud technical staff feedback:
The obtained IP is 127.0.0.1.
The forward may carry the vhost parameter, asking me to remove it and try again.



`TRANS_BY_GPT3`

**Comment by liguocahng** [comment]
I asked the personnel from Alibaba Cloud to help me for two days. The result they gave seemed to indicate that there was a problem with the stream, as the bandwidth was detected but the stream couldn't be played. Later, I tried it myself and found that using version 2.0 for streaming worked. You can try streaming with version 2.0.

`TRANS_BY_GPT3`

**Comment by lingfengfushui** [comment]
> I solved this problem using 2.0 at that time, but 3.0 cannot push the stream up.

> Which version of 2.0 did you use? I tried several versions of 2.0, but it seems that neither using a domain name nor an IP address worked.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I will see if I can reproduce it, it is possible that it failed due to the vhost.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #1202

**Comment by winlinvip** [comment]
Fixed in SRS5.0.1

**Comment by BenLocal** [comment]
> @liguocahng Thank you
> I am using version 3.0.156. Today, I contacted Alibaba Cloud technical support:
> 1) Forwarding to Alibaba Cloud - the actual push is successful, but playback fails
> 2) Alibaba Cloud technical personnel feedback
> The obtained IP is 127.0.0.1
> Forwarding may carry the vhost parameter, they asked me to remove it and try again.

I encountered the same error with version v3.0-r5. How was it resolved now?

`TRANS_BY_GPT3`

**Comment by langyastudio** [comment]
@BenLocal 
Still waiting for the author to resolve this issue #1342.

`TRANS_BY_GPT3`

**Comment by MuffinK** [comment]
> > @liguocahng Thank you @BenLocal
> > I am using version 3.0.156. Today I contacted Alibaba Cloud technical support:
> > 1) Forwarding to Alibaba Cloud - actual streaming is successful, but playback fails
> > 2) Feedback from Alibaba Cloud's technical staff
> > The IP obtained is 127.0.0.1
> > Forwarding may carry vhost parameters, they asked me to remove and try again.
> 
> I encountered the same error with version v3.0-r5. May I know how it was resolved now?

You can try including the CDN domain as the vhost when pushing the stream.
For example:
rtmp://srs.xxx.com/live/stream?key=9aa98e26&token=aNc28YIy **&vhost=cloud-push.xxx.com**

`TRANS_BY_GPT3`
