### ISSUE TITLE
间隔一段时间出现sip session is remove

### ISSUE THREAD

**Issue by mailliw2010** [ossrs/srs#2131]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.23`
1. SRS的日志如下(Log):
```
[2021-01-07 16:48:32.723][Trace][14537][2381] gb28181: sip session=34020000001120000004 keepalive timeout
[2021-01-07 16:48:32.723][Trace][14537][2381] gb28181: client id=34020000001120000004 sip session is remove
[2021-01-07 16:48:32.723][Trace][14537][2381] gb28181: sip client finished.
[2021-01-07 16:48:34.035][Trace][14537][3377] gb28181: sip session=34020000001120000006 keepalive timeout
[2021-01-07 16:48:34.035][Trace][14537][3377] gb28181: client id=34020000001120000006 sip session is remove
[2021-01-07 16:48:34.035][Trace][14537][3377] gb28181: sip client finished.
[2021-01-07 16:48:34.035][Trace][14537][2277] gb28181: sip session=34020000001120000005 keepalive timeout
[2021-01-07 16:48:34.035][Trace][14537][2277] gb28181: client id=34020000001120000005 sip session is remove
[2021-01-07 16:48:34.035][Trace][14537][2277] gb28181: sip client finished.
[2021-01-07 16:48:34.723][Trace][14537][2281] gb28181: sip session=34020000001140000004 keepalive timeout
[2021-01-07 16:48:34.723][Trace][14537][2281] gb28181: client id=34020000001140000004 sip session is remove
[2021-01-07 16:48:34.723][Trace][14537][2281] gb28181: sip client finished.
[2021-01-07 16:48:35.724][Trace][14537][1368] gb28181: sip session=34020000001120000002 keepalive timeout
[2021-01-07 16:48:35.724][Trace][14537][1368] gb28181: client id=34020000001120000002 sip session is remove
[2021-01-07 16:48:35.724][Trace][14537][1368] gb28181: sip client finished.
[2021-01-07 16:48:36.035][Trace][14537][2346] gb28181: sip session=34020000001140000003 keepalive timeout
[2021-01-07 16:48:36.035][Trace][14537][2346] gb28181: client id=34020000001140000003 sip session is remove

```
1. SRS的配置如下(Config):

sip 部分
 sip {
        # 是否启用srs内部sip信令
        # 为on信令走srs, off 只转发ps流
        enabled  on;

        # sip监听udp端口
        listen              5060;

        # SIP server ID(SIP服务器ID).
        # 设备端配置编号需要与该值一致，否则无法注册
        serial              34020000002000000001;

        # SIP server domain(SIP服务器域)
        realm               3402000000;

        # 服务端发送ack后，接收回应的超时时间，单位为秒
        # 如果指定时间没有回应，认为失败
        ack_timeout         10;

        # 设备心跳维持时间，如果指定时间内(秒）没有接收一个心跳
        # 认为设备离线
        keepalive_timeout   60;

        # 注册之后是否自动给设备端发送invite
        # on: 是  off 不是，需要通过api控制
        auto_play           off;
        # 设备将流发送的端口，是否固定
        # on 发送流到多路复用端口 如9000
        # off 自动从rtp_mix_port - rtp_max_port 之间的值中
        # 选一个可以用的端口
        invite_port_fixed     off;

**重现(Replay)**

sip session is remove

> 重现Bug的步骤(How to replay bug?)

**期望行为(Expect)**
设备在线情况，或者信号弱的情况下，可以保持session

> 描述你期望发生的事情(Please describe your expectation)

**Comment by ox188** [comment]
是在公网环境测试吗？
1.检查srs配置文件中的host是否为公网IP；
2.检查srs服务器所在网络防火墙是否开了udp9000端口；
3.检查你的摄像机配置，两项：一是视频编码是否为h264（如果是265的话，不行，要改成254）；二是接入平台28181的相关参数，主要是服务器编号和设备编号（用户ID）不能重复，如果是nvr，通道编号也要正确。
4.带宽是否够用。

你贴的配置文件不全，网络环境也没表述清楚。

**Comment by mailliw2010** [comment]
> 是在公网环境测试吗？
> 1.检查srs配置文件中的host是否为公网IP；
> 2.检查srs服务器所在网络防火墙是否开了udp9000端口；
> 3.检查你的摄像机配置，两项：一是视频编码是否为h264（如果是265的话，不行，要改成254）；二是接入平台28181的相关参数，主要是服务器编号和设备编号（用户ID）不能重复，如果是nvr，通道编号也要正确。
> 4.带宽是否够用。
> 
> 你贴的配置文件不全，网络环境也没表述清楚。


你好，感谢回复！
1、host是公网IP; IPC摄像头网络是4G网，所以有时候不稳定；
2、端口已开启；
3、摄像头为海康的，编码设置为h264；设备编号没有重复。


配置文件如下：
# push gb28181 stream to SRS.

listen                  1935;
max_connections         1000;
daemon                  off;
srs_log_tank            console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}

stats {
    network         0;
}

stream_caster {
    enabled             on;
    caster              gb28181;

    # 转发流到rtmp服务器地址与端口
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400875104
    # [stream] is VideoChannelCodecID(视频通道编码ID) for sip
    # 自动创建的道通[stream] 是‘chid[ssrc]’ [ssrc]是rtp的ssrc
    # [ssrc] rtp中的ssrc
    output              rtmp://127.0.0.1:1935/live/[stream];

    # 接收设备端rtp流的多路复用端口
    listen              9000;

    # rtp接收监听端口范围，最小值
    rtp_port_min        58200;
    # rtp接收监听端口范围，最大值
    rtp_port_max        58300;

    # 是否等待关键帧之后，再转发，
    # off:不需等待，直接转发
    # on:等第一个关键帧后，再转发
    wait_keyframe       off;  # test

    # rtp包空闲等待时间，如果指定时间没有收到任何包
    # rtp监听连接自动停止，发送BYE命令
    rtp_idle_timeout    20;  # default is 20s -- xcd

    # 是否转发音频流
    # 目前只支持aac格式，所以需要设备支持aac格式
    # on:转发音频
    # off:不转发音频，只有视频
    # *注意*!!!:flv 只支持11025  22050  44100 三种
    # 如果设备端没有三种中任何一个，转发时为自动选择一种格式
    # 同时也会将adts的头封装在flv aac raw数据中
    # 这样的话播放器为自动通过adts头自动选择采样频率
    # 像ffplay, vlc都可以，但是flash是没有声音，
    # 因为flash,只支持11025 22050 44100
    audio_enable        off;

    # 服务器主机号，可以域名或ip地址
    # 也就是设备端将媒体发送的地址，如果是服务器是内外网
    # 需要写外网地址，
    # 调用api创建stream session时返回ip地址也是host
    # $CANDIDATE 是系统环境变量，从环境变量获取地址，如果没有配置，用*
    # *代表指定stats network 的网卡号地址，如果没有配置network，默认则是第0号网卡地址
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400917594
    host       192.168.10.205;

    #根据收到ps rtp包自带创建rtmp媒体通道，不需要api接口创建
    #rtmp地址参数[stream] 就是通道id  格式chid[ssrc]
    auto_create_channel   on;

    sip {
        # 是否启用srs内部sip信令
        # 为on信令走srs, off 只转发ps流
        enabled  on;

        # sip监听udp端口
        listen              5060;

        # SIP server ID(SIP服务器ID).
        # 设备端配置编号需要与该值一致，否则无法注册
        serial              34020000002000000001;

        # SIP server domain(SIP服务器域)
        realm               3402000000;

        # 服务端发送ack后，接收回应的超时时间，单位为秒
        # 如果指定时间没有回应，认为失败
        ack_timeout         10;

        # 设备心跳维持时间，如果指定时间内(秒）没有接收一个心跳
        # 认为设备离线
        keepalive_timeout   20;  # default is 60, set to 20

        # 注册之后是否自动给设备端发送invite
        # on: 是  off 不是，需要通过api控制
        auto_play           off;
        # 设备将流发送的端口，是否固定
        # on 发送流到多路复用端口 如9000
        # off 自动从rtp_mix_port - rtp_max_port 之间的值中
        # 选一个可以用的端口
        invite_port_fixed     off;

        # 向设备或下级域查询设备列表的间隔，单位(秒)
        # 默认60秒
        query_catalog_interval  60;
    }
}


rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8001;
    #       
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    # 
    # The * means retrieving server IP automatically, from all network interfaces,
    #  @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
     candidate       183.66.138.122;
    #  candidate 192.169.10.205;

 }

vhost __defaultVhost__ {

    http_remux {
        enabled     on;

     mount       [vhost]/[app]/[stream].flv;

   }
    rtc {
        enabled     on;
        bframe      discard;
    }
}

**Comment by ox188** [comment]
把
host       192.168.10.205; 
改成公网IP，试一下

**Comment by winlinvip** [comment]
@ox188 👍
