### ISSUE TITLE
srs-srt版本无法用脚本来启动。

### ISSUE THREAD

**Issue by shitizenlism** [ossrs/srs#2135]
srs4.0release版本，编译开关：--without-utest --cxx11=on --srt=on --rtc=on --ssl=on --sys-ssl=off
就是编译一个支持srt功能的版本出来。运行时用./etc/init.d/srs start 无法启动。用srt.conf配置文件。
但用./objs/srs -c conf/srt.conf &可以启动成功。
这个问题是必现的。如果编译选项--srt=off生成的srs则没这问题。

**Comment by PieerePi** [comment]
试试 PR #2012 吧。
