### ISSUE TITLE
API：SrsStatistic::on_stream_close没有释放streams导致内存泄漏

### ISSUE THREAD

**Issue by JalySN** [ossrs/srs#2136]
查内存泄露，发现这个函数已经将指针从streams map里erase，那此时的streams泄露了？

**Comment by JalySN** [comment]
In addition, there is another place SrsHlsMuxer::update_config
whether srs_freep(writer) is needed.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
need

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@JalySN 感谢哈，已经在5.0 fix了。 👍 

欢迎加入我们开发群呐，一起来贡献代码。可以微信联系下我。 😄

**Comment by winlinvip** [comment]
@JalySN Thank you, it has already been fixed in 5.0. 👍

Welcome to join our development group, let's contribute code together. You can contact me on WeChat. 😄

`TRANS_BY_GPT3`
