### ISSUE TITLE
使用rtc_live.conf启动，推流退出后srs段错误退出

### ISSUE THREAD

**Issue by phil2360** [ossrs/srs#2137]
**描述(Description)**

使用./obj/srs -c ./conf/rtc_live.conf或./obj/srs -c ./conf/rtc.conf启动srs，rtmp推流后，一切正常。当rtmp推流退出，srs出现段错误退出（Segmentation fault (core dumped)）

core dump提示错误点在srs_app_rtc_source.cpp的672行，打印变量meta，此时meta为null
进一步跟踪，发现SrsRtcFromRtmpBridger对象在调用SrsRtcFromRtmpBridger::on_unpublish前已经被销毁

1. SRS版本(Version): `4.0.59`
1. SRS的配置如下(Config):
```
./obj/srs -c ./conf/rtc_live.conf
或
./obj/srs -c ./conf/rtc.conf

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `./obj/srs -c ./conf/rtc_live.conf` 启动srs
1. `ffmpeg -rtsp_transport tcp -i "rtsp://10.0.0.182/stream1" -vcodec copy -acodec copy -f flv "rtmp://127.0.0.1/live/1"启动推流`
1. 按q或者ctrl+c停止推流，srs段错误退出

**期望行为(Expect)**
能够正常停止推流

**Comment by zzugyl** [comment]
同一个版本，遇到同样的问题，症状和你一样。core文件分析如下： 
`
Core was generated by `./objs/srs -c conf/rtc_live.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000064553d in SrsRtcFromRtmpBridger::on_unpublish (this=0x1c064e0) at src/app/srs_app_rtc_source.cpp:672
672         meta->update_previous_vsh();
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.212.el6_10.3.x86_64 libgcc-4.4.7-23.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64
(gdb) bt
#0  0x000000000064553d in SrsRtcFromRtmpBridger::on_unpublish (this=0x1c064e0) at src/app/srs_app_rtc_source.cpp:672
#1  0x0000000000513848 in SrsSource::on_unpublish (this=0x1c20d20) at src/app/srs_app_source.cpp:2571
#2  0x0000000000504654 in SrsRtmpConn::release_publish (this=0x1bc9a60, source=0x1c20d20) at src/app/srs_app_rtmp_conn.cpp:984
#3  0x00000000005038c0 in SrsRtmpConn::publishing (this=0x1bc9a60, source=0x1c20d20) at src/app/srs_app_rtmp_conn.cpp:865
#4  0x0000000000500e55 in SrsRtmpConn::stream_service_cycle (this=0x1bc9a60) at src/app/srs_app_rtmp_conn.cpp:565
#5  0x00000000004ffb45 in SrsRtmpConn::service_cycle (this=0x1bc9a60) at src/app/srs_app_rtmp_conn.cpp:419
#6  0x00000000004fe7f4 in SrsRtmpConn::do_cycle (this=0x1bc9a60) at src/app/srs_app_rtmp_conn.cpp:232
#7  0x0000000000506d92 in SrsRtmpConn::cycle (this=0x1bc9a60) at src/app/srs_app_rtmp_conn.cpp:1445
#8  0x0000000000534e10 in SrsSTCoroutine::cycle (this=0x1bc9d40) at src/app/srs_app_st.cpp:226
#9  0x0000000000534e83 in SrsSTCoroutine::pfn (arg=0x1bc9d40) at src/app/srs_app_st.cpp:241
#10 0x000000000065c182 in _st_thread_main () at sched.c:337
#11 0x000000000065c91c in st_thread_create (start=0x1c04650, arg=0x1bc9d40, joinable=0, stk_size=6667007) at sched.c:616
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
`

**Comment by winlinvip** [comment]
Fixed。
