### ISSUE TITLE
gb28181 无法推送rtmp流到其他服务器

### ISSUE THREAD

**Issue by ntv-wangjian** [ossrs/srs#2140]
**描述(Description)**
push.gb28181.conf   stream_caster  output 配置到其他服务器，无法成功推流，还是推送到了本机上。

**Comment by winlinvip** [comment]
GB28181默认送到本机，要送其他服务器可以用RTMP的Forward或Edge功能。

**Comment by hugangfeng333** [comment]
> **描述(Description)**
> push.gb28181.conf stream_caster output 配置到其他服务器，无法成功推流，还是推送到了本机上。

想问下兄弟，这个解决了？大佬得配置文件怎么弄得？
