### ISSUE TITLE
Multi Quality HLS

### ISSUE THREAD

**Issue by h-o-sein** [ossrs/srs#2146]
How Active multi quality with hls?

**Comment by huanghe2015** [comment]
Transcode to different resolutions first, then output these as multiple streams.

**Comment by h-o-sein** [comment]
Please send a sample file of this configuration.

**Comment by tanero** [comment]
> Transcode to different resolutions first, then output these as multiple streams.

But you will need to create a multi hls m3u8 playlist manuely, right ?

**Comment by huanghe2015** [comment]
> 
> 
> > Transcode to different resolutions first, then output these as multiple streams.
> 
> But you will need to create a multi hls m3u8 playlist manually, right?

Yes. I think the URL of output streams can be concluded as a pattern, and it will be easily rendered on the server-side.

**Comment by winlinvip** [comment]
Not support yet.

**Comment by winlinvip** [comment]
Please use FFmpeg to transcode RTMP to Multiple-Quality-HLS.
