### ISSUE TITLE
启动srs后查看状态报没权限

### ISSUE THREAD

**Issue by xiaochangg** [ossrs/srs#2147]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `3.0.153`
1. SRS的日志如下(Log):

root@vivedu-desktop:/mnt/d/srs-nginx/srs-master/trunk# ./etc/init.d/srs status
bash: ./etc/init.d/srs: Permission denied

1. SRS的配置如下(Config):
# the config for srs to delivery RTMP
# @see https://github.com/ossrs/srs/wiki/v1_CN_SampleRTMP
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
vhost __defaultVhost__ {
}

**重现(Replay)**
./objs/srs -c conf/rtmp.conf 启动srs 后，查看状态报没权限

**期望行为(Expect)**
执行./etc/init.d/srs status 正常
> 描述你期望发生的事情(Please describe your expectation)

**Comment by xiaochangg** [comment]
root@vivedu-desktop:/mnt/d/srs-nginx/srs-master/trunk/objs# ./etc/init.d/srs status
bash: ./etc/init.d/srs: No such file or directory

**Comment by xiaochangg** [comment]
启动后/etc/init.d/下找不到srs,但是srs is started
通过 ps -ef | grep srs
root        4732    1680  0 15:07 pts/0    00:00:00 ./objs/srs -c conf/rtmp.conf

**Comment by ox188** [comment]
请编译安装srs，用systemctl start srs 启动，然后用./etc/init.d/srs status查看
如果是用./objs/srs -c conf/rtmp.conf启动的，就用ps -ef | grep srs 查看

**Comment by vinsonws** [comment]
这个看起来像是你没给 ./etc/init.d/srs 执行的权限

>  chmod -x ./etc/init.d/srs

路径应该在 /mnt/d/srs-nginx/srs-master/trunk/etc/init.d/srs
