### ISSUE TITLE
GB28181: SRS是否支持获取设备的详细信息：如设备的序列号（SN）等

### ISSUE THREAD

**Issue by yanweimiao** [ossrs/srs#2151]
**描述(Description)**

> SRS是否支持获取设备的详细信息：如设备的序列号（SN）等，目前我看日志中只能按类似34020000001320000001@34020000001320000001这种方式来标记设备ID，无法真实对应设备的SN，若应用平台以设备SN注册或添加设备，如何与SRS发现的终端进行对应就成了问题

**Comment by walley139** [comment]
You can obtain device information through an HTTP request: http://sip_server_ip_address/api/v1/gb28181?action=sip_query_devicelist. This interface can retrieve a list of all devices. If you need to query based on device ID, you will need to modify the source code to perform an ID-based search.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@walley139 👍
