### ISSUE TITLE
请问两个srs之间怎么配置为中继模式？

### ISSUE THREAD

**Issue by addriumruss** [ossrs/srs#2158]
需求是这样： 一个srs服务器在局域网，另一个srs在云端，视频先到达局域网srs, 希望由局域网srs自动中继一下推流给云端srs。
请问这样是否能够实现？
谢谢!

**Comment by JalySN** [comment]
forward mode

`TRANS_BY_GPT3`

**Comment by addriumruss** [comment]
I saw forward.master.conf, thank you for the answer! @JalySN

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Edge or Forward.

`TRANS_BY_GPT3`
