### ISSUE TITLE
English Please: is this possible to authentication on publish

### ISSUE THREAD

**Issue by waqarr** [ossrs/srs#2166]
English Please: 
**Question 1:**
is this possible to authentication on publish. for example only if i want to push rtmp stream on this link 

rtmp://192.168.1.10/live/test?token=323kk2k32k2lk2k3

i publish stream on this link and no one other publish on this link. 

**Question 2:** 
if any of my user stream on this link

rtmp://192.168.1.10/live/channel1

Can i drop / block this link to stop streaming? 

**Question 3:** 
Can i limit my user push stream on my server max  <= 1000Kbps

I cannot understand Chinese. please help me in English. Thank you so much

**Comment by tanero** [comment]
For question 1, I just say yes its possible to set such an authentication by using api hooks. You need to create an rest api and set your server to hook to your api.
