### ISSUE TITLE
GB28181: tcp_enable on 和 invite_port_fixed     off在srs中是否冲突。

### ISSUE THREAD

**Issue by Guanges** [ossrs/srs#2175]
TCP模式下动态端口段收流不成功
tcp_enable    on; 
	invite_port_fixed     on;     ok
	invite_port_fixed     off;    ?
tcp_enable    off; 
	invite_port_fixed     on;     ok
	invite_port_fixed     off;    ok

tcp_enable on 和 invite_port_fixed     off在srs中是否冲突。

1. SRS版本(Version): 4.0.62

**Comment by yinjiaoyuan** [comment]
Currently, `tcp_enable on` and `invite_port_fixed off` are conflicting in SRS.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@yinjiaoyuan 👍
