### ISSUE TITLE
api 后台管理 

### ISSUE THREAD

**Issue by mooczhou** [ossrs/srs#2179]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
我发现集群管理中，api只能单独的对某台机进行管理或者查看对集群其他机器不能管理，是否后面能够做一个服务或者集群跳转的api能够管理集群的这样能够很好的方便管理
**期望行为(Expect)**
期望有专门的后台或者api管理整个集群
> 描述你期望发生的事情(Please describe your expectation)
集群服务，能够更好的管理

**Comment by huanghe2015** [comment]
这个需要自己实现，请看Wiki：https://github.com/ossrs/srs/wiki/v3_CN_Home

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs-console
