### ISSUE TITLE
在Flash生命周期结束后正常使用（Enable Flash after its EOL）

### ISSUE THREAD

**Issue by huanghe2015** [ossrs/srs#2180]
# 在Flash结束生命周期后正常使用
## 参考来源（Original Post）

https://www.52pojie.cn/thread-1350285-1-1.html

### Windows

找到如下目录的 **pepflashplayer.dll** (Find file under below folder)

* C:\Windows\System32\Macromed\Flash
* C:\Windows\SysWOW64\Macromed\Flash

使用十六进制编辑器找到如下位置（Use hex editor to find below location）：

```
40 46 3E 6F 77 42
```

将 **42** 改为 **43** 或 **72** 等等。
保存后重启浏览器即可。

**Comment by winlinvip** [comment]
It is not possible to modify the client for each user. For the correct solution, please refer to [How to do live streaming without Flash?](https://mp.weixin.qq.com/s/oYn5q4fF9afaged23Ueudg)

`TRANS_BY_GPT3`

**Comment by huanghe2015** [comment]
Will the configuration file and the webpage for the demo be changed? @winlinvip

`TRANS_BY_GPT3`
