### ISSUE TITLE
feature/las版本make报错

### ISSUE THREAD

**Issue by lingfengfushui** [ossrs/srs#2183]
**描述(Description)**

> feature/las版本在服务器上make出错，换了多台服务器问题依旧
操作系统版本：centos 6.9

1. SRS版本(Version): `feature/las`
1. SRS的日志如下(Log):
g++ -c -ansi -Wall -Wno-deprecated-declarations -g -O0   \
    -Isrc/app -Isrc/core -Isrc/kernel -Isrc/protocol \
    -Iobjs -Iobjs/st -Iobjs/openssl/include -Iobjs/srtp2/include -Iobjs/ffmpeg/include -Iobjs/opus/include \
    -o objs/src/app/srs_app_server.o \
    src/app/srs_app_server.cpp
In file included from src/app/srs_app_server.hpp:34,
                 from src/app/srs_app_server.cpp:24:
src/app/srs_app_source.hpp:723: error: ‘SrsConnection’ has not been declared
make[2]: *** [objs/src/app/srs_app_server.o] Error 1
make[2]: Leaving directory `/home/live/local/srs-feature-las/trunk'
make[1]: *** [server] Error 2
make[1]: Leaving directory `/home/live/local/srs-feature-las/trunk'
make: *** [default] Error 2
1. SRS的配置如下(Config):
暂未配置

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `下载feature/las版本`
2. `./configure --with-las成功`
3. `make时中途发生错误，错误信息如上述日志`

**期望行为(Expect)**

> 期望make成功，feature/las版本可用

**Comment by winlinvip** [comment]
Fixed in 4.0.79
