### ISSUE TITLE
push Webrtc successfully, but can't play the stream

### ISSUE THREAD

**Issue by rainfly123** [ossrs/srs#2189]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4release`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
rtc.conf
```

我用Gstreamer 推流，信令已经调通，这是推流客户端信息
Sending offer:
v=0
o=- 9110092742428598041 0 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-options:trickle
a=group:BUNDLE video0 audio1
m=video 9 UDP/TLS/RTP/SAVPF 125
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:FmS4BQRmI27vhAq5TWWEDnhdKInZsCLs
a=ice-pwd:SWtEAb7TuGXuVqf4u9h+3giHb5w+JMO5
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:125 H264/90000
a=rtcp-fb:125 nack pli
a=framerate:30
a=fmtp:125 packetization-mode=1;profile-level-id=42c015
a=ssrc:708025389 msid:user447406915@host-58234a22 webrtctransceiver0
a=ssrc:708025389 cname:user447406915@host-58234a22
a=mid:video0
a=fingerprint:sha-256 D9:CC:B9:7C:6B:8B:DB:13:58:D3:44:94:F6:29:CE:FC:F9:BD:26:93:1A:1C:38:07:5C:2D:A3:22:E1:69:9A:45
m=audio 0 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=setup:actpass
a=ice-ufrag:FmS4BQRmI27vhAq5TWWEDnhdKInZsCLs
a=ice-pwd:SWtEAb7TuGXuVqf4u9h+3giHb5w+JMO5
a=bundle-only
a=rtcp-mux
a=rtcp-rsize
a=sendrecv
a=rtpmap:111 OPUS/48000/2
a=rtcp-fb:111 nack pli
a=fmtp:111 sprop-maxcapturerate=48000;sprop-stereo=0
a=ssrc:4181621593 msid:user447406915@host-58234a22 webrtctransceiver1
a=ssrc:4181621593 cname:user447406915@host-58234a22
a=mid:audio1
a=fingerprint:sha-256 D9:CC:B9:7C:6B:8B:DB:13:58:D3:44:94:F6:29:CE:FC:F9:BD:26:93:1A:1C:38:07:5C:2D:A3:22:E1:69:9A:45

Received answer:
v=0
o=SRS/4.0.65(Leo) 94058758179088 2 IN IP4 0.0.0.0
s=SRSPublishSession
t=0 0
a=ice-lite
a=group:BUNDLE audio1 video0
a=msid-semantic: WMS live/livestream
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=ice-ufrag:7t62n391
a=ice-pwd:2455uud7y2l442g4r0461956g9a7jxe1
a=fingerprint:sha-256 33:F9:68:5F:72:5C:99:27:43:27:8C:53:7E:37:0F:D0:87:90:26:10:BF:08:91:74:75:E6:7B:6D:55:C3:F3:35
a=setup:passive
a=mid:audio1
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 OPUS/48000/2
a=rtcp-fb:111 nack pli
a=candidate:0 1 udp 2130706431 192.168.43.92 8000 typ host generation 0
m=video 9 UDP/TLS/RTP/SAVPF 125
c=IN IP4 0.0.0.0
a=ice-ufrag:7t62n391
a=ice-pwd:2455uud7y2l442g4r0461956g9a7jxe1
a=fingerprint:sha-256 33:F9:68:5F:72:5C:99:27:43:27:8C:53:7E:37:0F:D0:87:90:26:10:BF:08:91:74:75:E6:7B:6D:55:C3:F3:35
a=setup:passive
a=mid:video0
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:125 H264/90000
a=rtcp-fb:125 nack pli
a=candidate:0 1 udp 2130706431 192.168.43.92 8000 typ host generation 0

但是用RTC_PLAYER.HTML 播放 却总是错误
rtc_player.html:307 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

UDP 端口音视频RTP 都用发送

**Comment by winlinvip** [comment]
Invalid，无SRS日志。
