### ISSUE TITLE
srs.log的日志会无限的增加

### ISSUE THREAD

**Issue by zsinba** [ossrs/srs#2191]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

跑了一段时间的srs4.0版本， srs.log的日志已经增加到了快20G。
期望： SRS的日志可以分段以及设置最大日志保存时间；

**Comment by ganttee** [comment]
`killall -USR1 srs` 可以切割日志
Linux下配合`logroteta`可以达到你的需求
