### ISSUE TITLE
如何更改流媒体音频视频的stream顺序呢？

### ISSUE THREAD

**Issue by aningxu** [ossrs/srs#2197]
**描述(Description)**
将媒体推流到SRS服务器，出来的流媒体Stream0为音频，Stream1为视频，我遇到了一个罕见的问题，一些版本比较老旧的播放器，不支持这个顺序，只支持默认stream0为视频，stream1为音频的流媒体。

![122](https://user-images.githubusercontent.com/68496559/107964799-a1a36a00-6fe4-11eb-9e3c-b60483a5c2e9.jpg)

请问如何更改stream的顺序，让stream0为视频呢？

**Comment by aningxu** [comment]
Currently, I have tested multiple streaming media servers, and usually the default stream0 is for video. I hope to solve this problem.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
In individual cases, you can only fix it yourself.

`TRANS_BY_GPT3`

**Comment by aningxu** [comment]
Currently, I have tested many streaming media servers, and only SRS places the audio before the video. Big brother, please make a change.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Currently, the order of the flow does not have a direct relationship with playback failure. You can try changing the order first, and if the player can play, then you can consider it.

I don't intend to solve an uncertain problem.

`TRANS_BY_GPT3`

**Comment by geiliwanghaichao** [comment]
上面的winlinvip大佬，请问如何更改流的顺序。或者说我现在没有音频，就不要有上面的 aningxu 图片上贴的音频信息

**Comment by geiliwanghaichao** [comment]
Hello @aningxu, have you solved your problem? I have encountered a similar issue. When I connect to a Hikvision or Dahua camera, I cannot enable audio on the camera's web interface.
![image](https://user-images.githubusercontent.com/56190738/131983599-7ed0b36f-cd5f-4c0c-87d2-53b5198b44ff.png)
](url) When using ffplay, stream 0 also has audio. I don't want this to happen when audio is not enabled. I don't know how to solve it.

`TRANS_BY_GPT3`

**Comment by geiliwanghaichao** [comment]
@winlinvip, may I ask how to change the order of the stream? Or in other words, if I don't have audio now, I don't want the audio information posted on the image shared by @aningxu above.

`TRANS_BY_GPT3`
