### ISSUE TITLE
关于--with-ffmpeg 该怎么添加

### ISSUE THREAD

**Issue by loongw513029** [ossrs/srs#2208]
ffmpeg需要什么版本
自己单独安装的ffmpeg该怎么使用

现在由于前端推过来的流都不标准 所以需要流媒体服务器转码

**Comment by loongw513029** [comment]
![image](https://user-images.githubusercontent.com/12654938/108813716-80e2a200-75ec-11eb-8cc9-4d33e9fe6605.png)
配置如上
推流服务器就报错了

**Comment by loongw513029** [comment]
![image](https://user-images.githubusercontent.com/12654938/108813822-acfe2300-75ec-11eb-9824-6e671cdf839d.png)

**Comment by winlinvip** [comment]
看FFmpeg的官方说明。
