### ISSUE TITLE
GB28181: 推流h264,  用vlc播放RTMP卡顿花屏(由于startcode=0x000001)

### ISSUE THREAD

**Issue by x-batman** [ossrs/srs#2209]
Migrate to https://github.com/ossrs/srs-gb28181/issues/24

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/24

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).'
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
