### ISSUE TITLE
修改推流音频编码采样率，导致服务器解析失败

### ISSUE THREAD

**Issue by zzugyl** [ossrs/srs#2210]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `3.0.153` 以及最新的代码commit eeebcda
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          1965;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
   dvr {
          enabled      on;
          dvr_path     /video/[app]/[2006]/[01]/[02]/[stream]/[15][04][05][999].flv;
          dvr_plan segment;
          dvr_duration 60;
          dvr_wait_keyframe on;
      }

   hls {
        enabled         on;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
```
运行环境：
`LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.10 (Final)
Release:        6.10
Codename:       Final
`
推流方式srs_publisher
有段时间必现，我当时在修改推流音频编码采样率，后来清空浏览器好了。我认为无论客户端如何，不应该导致srs服务闪退。

gdb调试显示：
`
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005b1530 in SrsDvrFlvSegmenter::encode_video (this=0x231e3f0, video=0x237a0c0, format=0x231e170) at src/app/srs_app_dvr.cpp:412
412         bool sh = (format->video->avc_packet_type == SrsVideoAvcFrameTraitSequenceHeader);
`
format不为空，但是format->video和format->audio都是空。

[core.zip](https://github.com/ossrs/srs/files/6033714/core.zip)

**Comment by winlinvip** [comment]
Hmm yes, protection should be added.

`TRANS_BY_GPT3`

**Comment by daozhao** [comment]
Streaming method srs_publisher, does this refer to streaming with flash?

My machine does not have a flash environment to reproduce, is flash streaming done with rtmp?
I simulated it using ffmpeg.
ffmpeg -re -i .\source.200kbps.768.flv -c:v copy -acodec aac -ar 24000 -f flv rtmp://192.168.2.175/live/livestream
ffmpeg -re -i .\source.200kbps.768.flv -c:v copy -acodec aac -ar 48000 -f flv rtmp://192.168.2.175/live/livestream
I pushed two streams alternately, but did not find the server crashing.

I also tried pushing the stream using RTC at http://localhost:8080/players/rtc_publisher.html. Modified the parameters.
 self.constraints = {
        audio: {sampleRate: 8000 , },
        video: {
            width: {ideal: 320, max: 576}
    };
···
And at
var stream = await navigator.mediaDevices.getUserMedia(self.constraints); manually modify the audio sampling rate at the breakpoint.
The server did not crash.

However, I found that changing the audio parameter to {sampleRate: 8000 , } in Chrome is futile, as the actual rate remains 48000.
By checking chrome://media-internals/, it can be seen that no matter how the sampleRate is modified, the final sample_rate is always 48000.


`TRANS_BY_GPT3`

**Comment by zzugyl** [comment]
@daozhao Yes, it is using Flash AS3 code on the web to push RTMP streams. You can change the audio sampling rate, encoding format, and more.
srs_publisher is a push streaming test demo in the early versions of SRS. You can find this file in the SRS source code.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Flash is no longer supported, and this issue will not be fixed.

`TRANS_BY_GPT3`
