### ISSUE TITLE
Is it possible to obtain the features similar to the those supplied in commercial live stream based meeting applications?

### ISSUE THREAD

**Issue by hongyi-zhao** [ossrs/srs#2218]
Is it possible to obtain the features similar to the those supplied in commercial live stream based meeting applications, say, [the tencent meeting](https://meeting.tencent.com/buy.html), as shown below:

![image](https://user-images.githubusercontent.com/11155854/109440556-af89ce00-7a6d-11eb-8ff4-5fbcae3bffdb.png)

**Comment by winlinvip** [comment]
Tencent Meeting is a commercial service, while SRS is an open-source video server.

It is possible to build commercial services based on open-source projects, including WebRTC+SRS+FFmpeg+... and so on.

Just like the relationship between Tencent and Alibaba's elastic servers and Linux open-source projects.

`TRANS_BY_GPT3`

**Comment by hongyi-zhao** [comment]
I roughly understand the meaning. SRS is a fundamental requirement for this type of service. However, the entire service belongs to subsequent secondary development. The type of service that can be provided depends on the developer's financial resources and technical capabilities. Even if the technical implementation is possible, it is likely beyond the financial means of an average individual to support the service functions and levels possessed by Tencent Meeting. It requires a well-funded team to afford it, and a complete set of supporting services that work together to fulfill their respective functions.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Tanliao has developed a video conferencing product based on SRS, called Yilijing.

https://www.codercto.com/a/126891.html

https://www.tiocloud.com/2/product/videoMeeting.html

`TRANS_BY_GPT3`
