### ISSUE TITLE
WebRTC: 交叉编译ARM，编译FFmpeg出错

### ISSUE THREAD

**Issue by X-Maurice** [ossrs/srs#2221]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `srs-4.0.76`
1. SRS的日志如下(Log):
```
CC	libavcodec/vorbis_data.o
CC	libavcodec/vorbis_parser.o
CC	libavcodec/xiph.o
AR	libavcodec/libavcodec.a
ar: libavcodec/aarch64/aacpsdsp_neon.o: No such file or directory
make: *** [ffbuild/library.mak:22: libavcodec/libavcodec.a] Error 1
Build ffmpeg-4.2-fit failed, ret=2

```
1. SRS的配置如下(Config):
```
	./configure --arm
```

**Comment by winlinvip** [comment]
Under ARM, there are some different dependencies. FFmpeg probably needs to add some files and modify parameters.

`TRANS_BY_GPT3`

**Comment by ChandZhang** [comment]
Encountered the same problem, the information is exactly the same! Using the RK3399 board, thanks for the support!

`TRANS_BY_GPT3`

**Comment by stmwiz** [comment]
Just put the complete ffmpeg source code in it.

`TRANS_BY_GPT3`

**Comment by pangtuantaun** [comment]
Please show me, the expert upstairs, how to fix this. I am using Raspberry Pi 4B with ARM architecture to install SRS 4.0. However, I encountered an error during the ffmpeg compilation phase. I have been trying for more than three days, but I couldn't get it to start. Now I am exhausted and have decided to buy an Alibaba Cloud server instead. I won't be using Raspberry Pi anymore. @@I have compromised.

`TRANS_BY_GPT3`

**Comment by pangtuantaun** [comment]
Dear experts, I managed to start using Raspberry Pi 4B. I just need to put the complete ffmpeg source code in it. The operation is as follows:
In the SRS, there is a "3rdparty" folder with a "ffmpeg-4-fit" folder. Install the new ffmpeg into it and replace the old one (delete the old one).
To install ffmpeg, follow this link: [https://zhuanlan.zhihu.com/p/231640028](https://zhuanlan.zhihu.com/p/231640028). The H26 address is incorrect.
Use this command to clone: `git clone https://code.videolan.org/videolan/x264.git`.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Generally, cross-compilation is not required. Please refer to https://github.com/ossrs/srs/issues/1282#issue-386077124.

`TRANS_BY_GPT3`
