### ISSUE TITLE
GB28181：注销时未及时删除流通道SrsGb28181Manger::delete_stream_channel

### ISSUE THREAD

**Issue by x-batman** [ossrs/srs#2224]
**描述(Description)**

> 28181注销register(expire=0)时，没有及时清理设备流通道，导致连接两次注册推流间隔太短的话，jitterbuffer报错

1. SRS版本(Version): `4.0release; develop;`

**期望行为(Expect)**

```
--- a/trunk/src/app/srs_app_gb28181_sip.cpp
+++ b/trunk/src/app/srs_app_gb28181_sip.cpp
@@ -134,6 +134,9 @@ void SrsGb28181SipSession::destroy()
     //destory all device
     std::map<std::string, SrsGb28181Device*>::iterator it;
     for (it = _device_list.begin(); it != _device_list.end(); ++it) {
+        std::string chid = it->first;
+        _srs_gb28181->delete_stream_channel(_session_id, chid);
+
         srs_freep(it->second);
     }
```

**Comment by x-batman** [comment]
Misreport, actually it supports cancellation, just that the deletion of the flow channel SrsGb28181Manger::delete_stream_channel was not done in a timely manner.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/25

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).'
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
