### ISSUE TITLE
Error building SRS4.0 on Ubuntu

### ISSUE THREAD

**Issue by laurfb** [ossrs/srs#2225]
Hi. Got libsrtp error building SRS on configure step:

"
_usr/bin/ld: libsrtp2.a(datatypes.o):(.bss_0x0): multiple definition of 'bit_string'; /tmp/cc2i6bAt.0:(.bss+0x0): first defined here
collect2: eror" ld returned 1 exit status
make: *** [Makefile:209: crypto/test/aes_calc] Error 1
Build libsrtp-2-fit failed, ret=2_
"
Ubuntu 20.10, SRS 4.0
In know that Centos in recomended...

regards,
laurb

**Comment by winlinvip** [comment]
Ubuntu build issues: #2219 and  https://github.com/ossrs/srs/issues/1780#issuecomment-706493271

Recommend to use [ossrs/srs:ubuntu20](https://github.com/ossrs/srs-docker/tree/ubuntu20#usage) docker to build:

```bash
cd ~/git/srs &&
docker run --rm -it -v `pwd`:/srs -w /srs/trunk ossrs/srs:ubuntu20 bash -c "./configure && make"
```

I test it, it's ok.
