### ISSUE TITLE
用web播放器可以播放srs rtmp流吗?

### ISSUE THREAD

**Issue by cppbitman** [ossrs/srs#2235]
> 描述你期望发生的事情(Please describe your expectation)
SRS 3.0，默认配置。
VLC可以播放SRS RTMP流。有什么Web播放器可以播放RTMP流吗？

**Comment by terry8204** [comment]
百度搜下，以前最开始我用flash播放，后来换了 videojs,现在用flv.js,后面准备用webrtc

**Comment by huanghe2015** [comment]
videojs本质上也是依赖Flash的，所以没有Flash是不能播放RTMP的。

**Comment by Luupw3d** [comment]
不好弄，建议使用http-flv，SRS里有http.flv.conf，同时也有srs-player
