### ISSUE TITLE
SRS什么时候支持webRTC方式的推流

### ISSUE THREAD

**Issue by xiaolongzhao2015** [ossrs/srs#2241]
SRS什么时候支持webRTC方式的推流？

目前我们有自己的会议室流，现在外放有rtp协议的包。
看了网上很多文章，说SRS准备支持WebRTC协议了，请问有大体的发布计划吗？

**Comment by terry8204** [comment]
Early support, using srs4.0

`TRANS_BY_GPT3`

**Comment by xiaolongzhao2015** [comment]
Ok. Just found it on the official website. So, for streaming with webRTC, can we use HLS to pull the stream? Or can we only use webRTC to pull the stream? Because I noticed that in the WeChat environment, many times the browser does not support webRTC, which leads to playback issues. Our business scale requires propagation in the WeChat environment.

`TRANS_BY_GPT3`

**Comment by terry8204** [comment]
微信里面支持rtmp的' translates to 'WeChat supports rtmp.

`TRANS_BY_GPT3`

**Comment by zsinba** [comment]
> WeChat supports rtmp inside.

> WeChat on iOS does not support it.

`TRANS_BY_GPT3`

**Comment by terry8204** [comment]
Also supported by iOS

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #307
