### ISSUE TITLE
Ingest推流会中断

### ISSUE THREAD

**Issue by zsinba** [ossrs/srs#2242]
**描述(Description)**
使用ingest推文件到RTMP服务器，文件播放完成后， 会中断推流（秒级)然后再继续循环推流。
> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): 4.0.85
1. SRS的日志如下(Log):
```
无需日志
```
1. SRS的配置如下(Config):
```
ingest的配置
![image](https://user-images.githubusercontent.com/890157/111305710-3eaffc00-8692-11eb-87ac-61853d64f780.png)

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)
必现的. 每个文件播放完成后,都会中断一次.
可能 是FFMPEG的参数原因,也可能 是SRS调用的原因

**期望行为(Expect)**

> 如果使用ingest虚拟推一个文件时,不希望文件在播放完成后,中断一下再继续推而是持续循环的推流.

**Comment by cnkedao** [comment]
我碰到了同样的问题。
看了SRS的日志，提示RTMP Client disconnect peer。
翻了一下代码，应该是ingest这个模式下还有bug。
`// client close peer.
    // TODO: FIXME: Only reset the error when client closed it.
    if (srs_is_client_gracefully_close(err)) {
        srs_warn("client disconnect peer. ret=%d", srs_error_code(err));
    }`

**Comment by cnkedao** [comment]
You interrupted because the file ended, right? Use the -stream_loop parameter for FFmpeg streaming.

`TRANS_BY_GPT3`

**Comment by zsinba** [comment]
> This is an interruption caused by the end of the file, right? Use the -stream_loop parameter for FFmpeg streaming.

> Can this parameter also be used with the SRS configuration file? Instead of directly using FFmpeg for streaming, it is using SRS configuration parameters.

![image](https://user-images.githubusercontent.com/890157/113119518-1bb14a80-9243-11eb-8c38-c55fbaaf7d78.png)

> This is the configuration file syntax. I didn't see any place where FFmpeg parameters can be written.

`TRANS_BY_GPT3`

**Comment by zsinba** [comment]
Do you have any other suggestions?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@cnkedao 👍 +1

> This is an interruption caused by the end of the file, right? Use the -stream_loop parameter for FFmpeg streaming.


`TRANS_BY_GPT3`
