### ISSUE TITLE
webrtc推流播放均正常，但http_hooks收不到任何回调--srs4.0.84

### ISSUE THREAD

**Issue by githubvvcao** [ossrs/srs#2243]
**描述(Description)**

> webrtc推拉流时http_hooks无效，收不到任何回调。
> 同时用rtmp推拉流http_hooks正常，能收到回调。

1. SRS版本(Version): `4.0.84`
1. SRS的日志如下(Log):
```
无
```
1. SRS的配置如下(Config):
```
 http_hooks {
        enabled         on;
        on_connect      http://127.0.0.1:8085/api/v1/clients;
        on_close        http://127.0.0.1:8085/api/v1/clients;
        on_publish      http://127.0.0.1:8085/api/v1/streams;
        on_unpublish    http://127.0.0.1:8085/api/v1/streams;
        on_play         http://127.0.0.1:8085/api/v1/sessions;
        on_stop         http://127.0.0.1:8085/api/v1/sessions;
        on_dvr          http://127.0.0.1:8085/api/v1/dvrs;
        on_hls          http://127.0.0.1:8085/api/v1/hls;
        on_hls_notify   http://127.0.0.1:8085/api/v1/hls/[app]/[stream]/[ts_url][param];

    }
```

**重现(Replay)**

> 使用官方的research/api-server/server.py或自己写个webserver，在webrtc推流时都收不到任何请求，在rtmp推拉流时能收到。

**期望行为(Expect)**

> 期望webrtc也能http_hooks，不然没法加token鉴权

**Comment by xiaolongzhao2015** [comment]
May I ask how you are streaming webRTC? Is it using the official website's demo? Is it written in frontend code or something else? I want to stream using backend scripts or C.

`TRANS_BY_GPT3`

**Comment by hugangfeng333** [comment]
webrtc does not support these hooks yet, including gb28181 streaming.

`TRANS_BY_GPT3`

**Comment by githubvvcao** [comment]
> Excuse me, how do you stream webRTC? Is it using the official website's demo? Is it written in frontend or something else? I want to stream using backend scripts or C method.

I am using the official demo, the HTML5 version.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Can you compile it yourself? I can help you add it, but you probably have to merge it yourself.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
WebRTC has added an HTTP hook, you can try merging it yourself.
https://github.com/ossrs/srs/pull/2169/commits/d4c145ef262081ac8c90248fd3dc181b85fce859

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed
