### ISSUE TITLE
webrtc播放卡顿

### ISSUE THREAD

**Issue by hl10105210** [ossrs/srs#2250]
**描述(Description)**
局域网环境，输入rtmp，输出webrtc，首屏时间在3-10s，播放过程经常会卡住好几秒，然后直接跳到几秒后的画面继续播放。
1. SRS版本(Version): 4.0.76
1. SRS的配置如下(Config):
```
listen 1935;
max_connections 1000;
http_api {
    enabled on;
    listen 1985;
}
rtc_server {
    enabled on;
    listen 8000;
    candidate $CANDIDATE;
}
vhost __defaultVhost__ {
    rtc {
        enabled on;
        bframe discard;
    }
}
```

**重现(Replay)**
1. `通过obs推流到srs`
1. `通过jswebrtc.min.js播放webrtc流`

**期望行为(Expect)**
首屏时间在2s内，播放过程无卡顿

**Comment by Lisuibiao** [comment]
我也遇到了这个问题。是在iOS和Android上使用H5播放会有比较明显的卡顿现象。经过对比验证，卡顿问题与分辨率、码率基本没有太大关联。但是会受视频流帧率的影响：帧率越高，卡顿现象越轻。

**Comment by winlinvip** [comment]
Dup to #2484
