### ISSUE TITLE
http-flv 如果没推流，播放器会一直等待，播放器连续启达多个播放，会多个等待

### ISSUE THREAD

**Issue by terry8204** [ossrs/srs#2253]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.84`
2. SRS的日志如下(Log):
     这块没超时退出：
       if ((err = io->read(body, 4096, NULL)) != srs_success) {
            // Because we use timeout to check trd state, so we should ignore any timeout.
            if (srs_error_code(err) == ERROR_SOCKET_TIMEOUT) {
                srs_freep(err);
                continue;
            }

            return srs_error_wrap(err, "read response");
        }
3. SRS的配置如下(Config):
srs.conf

**重现(Replay)**

1. 不启动推流，点击播放http://127.0.0.1:8080/live/livestream.flv
2. 连续点击10次
3. 会出现很多pending http-flv
4. 开始推流
5. 前面5个pending 变成了 推流状态，后面5个一直保持了pending
6. 播放器打转

**期望行为(Expect)**
1. 连续点击，取消前面多pending http-flv 或者能超时
2. 取消前面9个pending http-flv,只给最后一个http-flv 推流
![image](https://user-images.githubusercontent.com/59051601/111906844-a482f600-8a8d-11eb-903f-5708d9c11522.png)

**Comment by terry8204** [comment]
Does this need to check if the flv is being streamed, and if it times out without streaming, then disconnect this connection?

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
This is not an SRS problem, right?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #1134 

According to the convention of HTTP, it is a viable choice to return a 404 when there is no stream. Refer to #1134.

`TRANS_BY_GPT3`
