### ISSUE TITLE
GB28181能否支持历史回放功能呢

### ISSUE THREAD

**Issue by eshxcmhk** [ossrs/srs#2254]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `XCORE-SRS/4.0.85(Leo)`

**期望行为(Expect)**

> GB28181能支持历史回放功能

**Comment by leoyao0613** [comment]
默认好像是没带，你自己加上去了吗？

**Comment by winlinvip** [comment]
支持完善的GB，不是SRS的目标
