### ISSUE TITLE
Archieve realtime streaming is even possible?

### ISSUE THREAD

**Issue by ianholing** [ossrs/srs#2259]
** Archieve Real Time (less than 1s)**

> ¿Is there a way to archieve realtime? I tried following this guide ( https://github.com/ossrs/srs/wiki/v3_EN_SampleRealtime) step by step and change so many things to try, I played with ffplay to remove cache and nothing.. I cannot go below 4 seconds. Before you ask.. my network connection is good and I am doing the stream directly inside my LAN network.

1. SRS版本(Version): `3.0release`
1. SRS的配置如下(Config):
```
# conf/realtime.conf
listen              1935;
max_connections     1000;
vhost __defaultVhost__ {
    tcp_nodelay     on
    min_latency     on;

    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr off;
    }
}
```

> 重现Bug的步骤(How to replay bug?)

1. `Just try to reproduce the realtime wiki page`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

I expect less than 1 second of latency

**Comment by Luupw3d** [comment]
Encountered the same problem, looking for a solution:(

**Comment by ianholing** [comment]
@Luupw3d I am yet looking for something, if anyone finds a solution please share

**Comment by winlinvip** [comment]
Use SRS 4.0+, WebRTC. Please read #307

**Comment by Luupw3d** [comment]
> Encountered the same problem, looking for a solution:(

Please using WebRTC, its latency is very low(<1s on LAN)
