### ISSUE TITLE
ffmpeg能使用系统自带的dev包嘛? 什么时候能够支持 ubuntu20和centos8的编译啊

### ISSUE THREAD

**Issue by libxengine** [ossrs/srs#2262]
ubnutu20.04 和 centos8都是提示python错误,我搜索看说不支持.啥时候才能支持高版本系统的编译,...
我们环境都迁移了.

还有就是我centos和ubnunt都系统直接yum和apt 安装了ffmpeg的开发包,能支持使用系统的嘛?

3.0-r3版本

**Comment by hibate** [comment]
`python` 错误请编辑 `auto/depends.sh` 文件，定位到 442 行，增加 `python3` 支持即可，修改后内容如下所示:

```
# Detect python or python2
python --version >/dev/null 2>&1 && SYS_PYTHON=python;
python2 --version >/dev/null 2>&1 && SYS_PYTHON=python2;
python3 --version >/dev/null 2>&1 && SYS_PYTHON=python3;
```

`ffmpeg` 可以支持系统的，使用 `yum` 或 `apt` 安装后，指定安装后的 `ffmpeg` 二进制位置即可，或者链接到 `srs` 对应路径下。
