### ISSUE TITLE
WebRTC: 推流方sdp有视频，拉流方sdp没有视频，然后先拉流，再推流，导致服务崩溃

### ISSUE THREAD

**Issue by LuluChina** [ossrs/srs#2269]
版本  4.0release 

![image](https://user-images.githubusercontent.com/44631008/113232175-36310580-92cf-11eb-8e45-79fd1115e0fe.png)

应该是上图的一个判断有问题。

**Comment by winlinvip** [comment]
👍 Submitting an issue with problem identification, well done, 😀

`TRANS_BY_GPT3`

**Comment by chen-guanghua** [comment]
@LuluChina, please provide a reproduction process to facilitate further analysis and problem-solving.

`TRANS_BY_GPT3`

**Comment by chen-guanghua** [comment]
Fixed by 4.0release v4.0.156, commit: 1347da81f868727a94e3be8f748896046572762e
