### ISSUE TITLE
WebRTC: 推流后前端直播阶段性卡顿

### ISSUE THREAD

**Issue by yaooolu** [ossrs/srs#2270]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `v4.0.55`
1. SRS的日志如下(Log):

![2021-04-02 18-54-36屏幕截图](https://user-images.githubusercontent.com/7866281/113410214-72568a00-93e5-11eb-9646-d48c68a9ba1f.png)

1. SRS的配置如下(Config):
```
配置就是 conf/rtc.conf 默认配置
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

后端 rtmp 推流到 srs 之后， 前端webrtc 连接播放一段时间后，出现卡顿现象！
![2021-04-02 18-45-30屏幕截图](https://user-images.githubusercontent.com/7866281/113410394-e1cc7980-93e5-11eb-8895-911d53edfa55.png)
* 如上图黄色框中所标记的一样， 会收不到帧数据， 但后端rtmp 流是一直再推送的。上述工具是chrome 的 webrtc-internals

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

期望前端播放器播放比较平滑， 无卡顿现象

**Comment by yaooolu** [comment]
Has anyone encountered this problem before? Or does anyone have any ideas for a solution?

`TRANS_BY_GPT3`

**Comment by joysun2006** [comment]
Encountering the same issue, it seems that there is still no good solution.

`TRANS_BY_GPT3`

**Comment by yaooolu** [comment]
Solved, it should be an issue with the ffmpeg streaming settings.

`TRANS_BY_GPT3`

**Comment by joysun2006** [comment]
Can you introduce how to solve it? Did you use ffmpeg for streaming? In actual application scenarios, OBS is used more often, right? I have tried various settings in OBS, but none of them work. It is probably due to encoding or other reasons.

`TRANS_BY_GPT3`

**Comment by anlalala** [comment]
@yaooolu May I ask, what parameters should be adjusted for ffmpeg?

`TRANS_BY_GPT3`

**Comment by yaooolu** [comment]
> @yaooolu May I ask, what parameters should be adjusted for ffmpeg?

I added the GOP setting, and I set it as "-g 3" myself.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
See also #2484 

@yaooolu 👍 

> > @yaooolu May I ask, what parameters should be adjusted for ffmpeg?
> 
> I added the GOP setting, and I set it as "-g 3" myself.


`TRANS_BY_GPT3`
