### ISSUE TITLE
SRS/develop和SRS/4.0release ffmpeg4-fit编译失败

### ISSUE THREAD

**Issue by x-batman** [ossrs/srs#2271]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.88`
1. SRS的日志如下(Log):
```
source path               .
C compiler                gcc
C library                 glibc
ARCH                      x86 (generic)
big-endian                no
runtime cpu detection     yes
standalone assembly       yes
x86 assembler             nasm
MMX enabled               yes
MMXEXT enabled            yes
3DNow! enabled            yes
3DNow! extended enabled   yes
SSE enabled               yes
SSSE3 enabled             yes
AESNI enabled             yes
AVX enabled               yes
AVX2 enabled              yes
AVX-512 enabled           yes
XOP enabled               yes
FMA3 enabled              yes
FMA4 enabled              yes
i686 features enabled     yes
CMOV is fast              yes
EBX available             yes
EBP available             yes
debug symbols             yes
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    no
postprocessing support    no
network support           no
threading support         pthreads
safe bitstream reader     yes
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          yes
makeinfo supports HTML    yes

External libraries:
alsa                    libxcb                  libxcb_xfixes           zlib
bzlib                   libxcb_shape            sndio
libopus                 libxcb_shm              xlib

External libraries providing hardware acceleration:
crystalhd               v4l2_m2m                xvmc

Libraries:
avcodec                 avutil                  swresample

Programs:

Enabled decoders:
aac                     aac_fixed               aac_latm                libopus

Enabled encoders:
aac                     libopus                 opus

Enabled hwaccels:

Enabled parsers:
aac_latm

Enabled demuxers:

Enabled muxers:

Enabled protocols:

Enabled filters:

Enabled bsfs:
null

Enabled indevs:

Enabled outdevs:

License: LGPL version 2.1 or later
libavutil/avconfig.h is unchanged
libavfilter/filter_list.c is unchanged
libavcodec/codec_list.c is unchanged
libavcodec/parser_list.c is unchanged
libavcodec/bsf_list.c is unchanged
libavformat/demuxer_list.c is unchanged
libavformat/muxer_list.c is unchanged
libavdevice/indev_list.c is unchanged
libavdevice/outdev_list.c is unchanged
libavformat/protocol_list.c is unchanged
GEN	libswresample/libswresample.version
GEN	libavcodec/libavcodec.version
CC	libavcodec/aaccoder.o
CC	libavcodec/aacdec.o
CC	libavcodec/aacdec_fixed.o
CC	libavcodec/aacenc.o
CC	libavcodec/aacenc_is.o
CC	libavcodec/aacenc_ltp.o
CC	libavcodec/aacenc_pred.o
CC	libavcodec/aacenc_tns.o
CC	libavcodec/aacenctab.o
CC	libavcodec/aacps_fixed.o
CC	libavcodec/aacps_float.o
CC	libavcodec/aacpsdsp_fixed.o
CC	libavcodec/aacpsdsp_float.o
CC	libavcodec/aacpsy.o
CC	libavcodec/aacsbr.o
CC	libavcodec/aacsbr_fixed.o
CC	libavcodec/aactab.o
CC	libavcodec/ac3_parser.o
CC	libavcodec/adts_header.o
CC	libavcodec/adts_parser.o
CC	libavcodec/allcodecs.o
CC	libavcodec/audio_frame_queue.o
CC	libavcodec/avdct.o
CC	libavcodec/avfft.o
CC	libavcodec/avpacket.o
CC	libavcodec/avpicture.o
CC	libavcodec/bitstream.o
CC	libavcodec/bitstream_filter.o
CC	libavcodec/bitstream_filters.o
CC	libavcodec/bsf.o
CC	libavcodec/cbrt_data.o
CC	libavcodec/cbrt_data_fixed.o
CC	libavcodec/codec_desc.o
CC	libavcodec/d3d11va.o
CC	libavcodec/decode.o
libavcodec/decode.c: In function ‘compat_decode’:
libavcodec/decode.c:862:13: warning: ‘refcounted_frames’ is deprecated [-Wdeprecated-declarations]
             if (!avctx->refcounted_frames) {
             ^~
In file included from libavcodec/decode.c:41:0:
libavcodec/avcodec.h:2396:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
libavcodec/decode.c: In function ‘avcodec_flush_buffers’:
libavcodec/decode.c:2049:5: warning: ‘refcounted_frames’ is deprecated [-Wdeprecated-declarations]
     if (!avctx->refcounted_frames)
     ^~
In file included from libavcodec/decode.c:41:0:
libavcodec/avcodec.h:2396:9: note: declared here
     int refcounted_frames;
         ^~~~~~~~~~~~~~~~~
CC	libavcodec/dirac.o
CC	libavcodec/dv_profile.o
CC	libavcodec/encode.o
libavcodec/encode.c: In function ‘do_encode’:
libavcodec/encode.c:365:9: warning: ‘avcodec_encode_video2’ is deprecated [-Wdeprecated-declarations]
         ret = avcodec_encode_video2(avctx, avctx->internal->buffer_pkt,
         ^~~
libavcodec/encode.c:258:25: note: declared here
 int attribute_align_arg avcodec_encode_video2(AVCodecContext *avctx,
                         ^~~~~~~~~~~~~~~~~~~~~
libavcodec/encode.c:368:9: warning: ‘avcodec_encode_audio2’ is deprecated [-Wdeprecated-declarations]
         ret = avcodec_encode_audio2(avctx, avctx->internal->buffer_pkt,
         ^~~
libavcodec/encode.c:118:25: note: declared here
 int attribute_align_arg avcodec_encode_audio2(AVCodecContext *avctx,
                         ^~~~~~~~~~~~~~~~~~~~~
CC	libavcodec/fft_fixed.o
CC	libavcodec/fft_fixed_32.o
CC	libavcodec/fft_float.o
CC	libavcodec/fft_init_table.o
CC	libavcodec/frame_thread_encoder.o
libavcodec/frame_thread_encoder.c: In function ‘worker’:
libavcodec/frame_thread_encoder.c:89:9: warning: ‘avcodec_encode_video2’ is deprecated [-Wdeprecated-declarations]
         ret = avcodec_encode_video2(avctx, pkt, frame, &got_packet);
         ^~~
In file included from libavcodec/frame_thread_encoder.h:24:0,
                 from libavcodec/frame_thread_encoder.c:23:
libavcodec/avcodec.h:5462:5: note: declared here
 int avcodec_encode_video2(AVCodecContext *avctx, AVPacket *avpkt,
     ^~~~~~~~~~~~~~~~~~~~~
CC	libavcodec/iirfilter.o
CC	libavcodec/imgconvert.o
CC	libavcodec/jni.o
CC	libavcodec/kbdwin.o
CC	libavcodec/latm_parser.o
CC	libavcodec/libopus.o
CC	libavcodec/libopusdec.o
CC	libavcodec/libopusenc.o
CC	libavcodec/lpc.o
CC	libavcodec/mathtables.o
CC	libavcodec/mdct15.o
CC	libavcodec/mdct_fixed.o
CC	libavcodec/mdct_fixed_32.o
CC	libavcodec/mdct_float.o
CC	libavcodec/mediacodec.o
CC	libavcodec/mjpegenc_huffman.o
CC	libavcodec/mpeg12framerate.o
CC	libavcodec/mpeg4audio.o
CC	libavcodec/null_bsf.o
CC	libavcodec/options.o
libavcodec/options.c: In function ‘codec_child_class_next’:
libavcodec/options.c:61:5: warning: ‘av_codec_next’ is deprecated [-Wdeprecated-declarations]
     while (prev && (c = av_codec_next(c)))
     ^~~~~
In file included from libavcodec/options.c:27:0:
libavcodec/avcodec.h:4118:10: note: declared here
 AVCodec *av_codec_next(const AVCodec *c);
          ^~~~~~~~~~~~~
libavcodec/options.c:66:5: warning: ‘av_codec_next’ is deprecated [-Wdeprecated-declarations]
     while (c = av_codec_next(c))
     ^~~~~
In file included from libavcodec/options.c:27:0:
libavcodec/avcodec.h:4118:10: note: declared here
 AVCodec *av_codec_next(const AVCodec *c);
          ^~~~~~~~~~~~~
CC	libavcodec/opus.o
CC	libavcodec/opus_pvq.o
CC	libavcodec/opus_rc.o
CC	libavcodec/opusenc.o
CC	libavcodec/opusenc_psy.o
CC	libavcodec/opustab.o
CC	libavcodec/parser.o
CC	libavcodec/parsers.o
CC	libavcodec/profiles.o
CC	libavcodec/psymodel.o
CC	libavcodec/pthread.o
CC	libavcodec/pthread_frame.o
CC	libavcodec/pthread_slice.o
CC	libavcodec/qsv_api.o
CC	libavcodec/raw.o
CC	libavcodec/sbrdsp.o
CC	libavcodec/sbrdsp_fixed.o
CC	libavcodec/sinewin.o
CC	libavcodec/sinewin_fixed.o
CC	libavcodec/utils.o
CC	libavcodec/v4l2_buffers.o
CC	libavcodec/v4l2_context.o
CC	libavcodec/v4l2_fmt.o
CC	libavcodec/v4l2_m2m.o
CC	libavcodec/vorbis_data.o
CC	libavcodec/vorbis_parser.o
X86ASM	libavcodec/x86/aacencdsp.o
STRIP	libavcodec/x86/aacencdsp.o
CC	libavcodec/x86/aacencdsp_init.o
X86ASM	libavcodec/x86/aacpsdsp.o
STRIP	libavcodec/x86/aacpsdsp.o
CC	libavcodec/x86/aacpsdsp_init.o
CC	libavcodec/x86/celt_pvq_init.o
X86ASM	libavcodec/x86/celt_pvq_search.o
STRIP	libavcodec/x86/celt_pvq_search.o
CC	libavcodec/x86/constants.o
X86ASM	libavcodec/x86/fft.o
STRIP	libavcodec/x86/fft.o
CC	libavcodec/x86/fft_init.o
CC	libavcodec/x86/lpc.o
X86ASM	libavcodec/x86/mdct15.o
STRIP	libavcodec/x86/mdct15.o
CC	libavcodec/x86/mdct15_init.o
X86ASM	libavcodec/x86/sbrdsp.o
STRIP	libavcodec/x86/sbrdsp.o
CC	libavcodec/x86/sbrdsp_init.o
CC	libavcodec/xiph.o
AR	libavcodec/libavcodec.a
ar: libavcodec/crystalhd.o: 没有那个文件或目录
ffbuild/library.mak:21: recipe for target 'libavcodec/libavcodec.a' failed
make: *** [libavcodec/libavcodec.a] Error 1
Build ffmpeg-4-fit failed, ret=2
```

**重现(Replay)**

> ./configure

**Comment by x-batman** [comment]
Operating System Ubuntu 18.04 x64

`TRANS_BY_GPT3`

**Comment by xiekai-aiai** [comment]
May I ask, did you eventually solve this problem?

> **Description**
> 
> > Please describe your issue here.
> 
> 1. SRS version: `4.0.88`
> 2. The log of SRS is as follows:
> 
> ```
> source path               .
> C compiler                gcc
> C library                 glibc
> ARCH                      x86 (generic)
> big-endian                no
> runtime cpu detection     yes
> standalone assembly       yes
> x86 assembler             nasm
> MMX enabled               yes
> MMXEXT enabled            yes
> 3DNow! enabled            yes
> 3DNow! extended enabled   yes
> SSE enabled               yes
> SSSE3 enabled             yes
> AESNI enabled             yes
> AVX enabled               yes
> AVX2 enabled              yes
> AVX-512 enabled           yes
> XOP enabled               yes
> FMA3 enabled              yes
> FMA4 enabled              yes
> i686 features enabled     yes
> CMOV is fast              yes
> EBX available             yes
> EBP available             yes
> debug symbols             yes
> strip symbols             yes
> optimize for size         no
> optimizations             yes
> static                    yes
> shared                    no
> postprocessing support    no
> network support           no
> threading support         pthreads
> safe bitstream reader     yes
> texi2html enabled         no
> perl enabled              yes
> pod2man enabled           yes
> makeinfo enabled          yes
> makeinfo supports HTML    yes
> 
> External libraries:
> alsa                    libxcb                  libxcb_xfixes           zlib
> bzlib                   libxcb_shape            sndio
> libopus                 libxcb_shm              xlib
> 
> External libraries providing hardware acceleration:
> crystalhd               v4l2_m2m                xvmc
> 
> Libraries:
> avcodec                 avutil                  swresample
> 
> Programs:
> 
> Enabled decoders:
> aac                     aac_fixed               aac_latm                libopus
> 
> Enabled encoders:
> aac                     libopus                 opus
> 
> Enabled hwaccels:
> 
> Enabled parsers:
> aac_latm
> 
> Enabled demuxers:
> 
> Enabled muxers:
> 
> Enabled protocols:
> 
> Enabled filters:
> 
> Enabled bsfs:
> null
> 
> Enabled indevs:
> 
> Enabled outdevs:
> 
> License: LGPL version 2.1 or later
> libavutil/avconfig.h is unchanged
> libavfilter/filter_list.c is unchanged
> libavcodec/codec_list.c is unchanged
> libavcodec/parser_list.c is unchanged
> libavcodec/bsf_list.c is unchanged
> libavformat/demuxer_list.c is unchanged
> libavformat/muxer_list.c is unchanged
> libavdevice/indev_list.c is unchanged
> libavdevice/outdev_list.c is unchanged
> libavformat/protocol_list.c is unchanged
> GEN	libswresample/libswresample.version
> GEN	libavcodec/libavcodec.version
> CC	libavcodec/aaccoder.o
> CC	libavcodec/aacdec.o
> CC	libavcodec/aacdec_fixed.o
> CC	libavcodec/aacenc.o
> CC	libavcodec/aacenc_is.o
> CC	libavcodec/aacenc_ltp.o
> CC	libavcodec/aacenc_pred.o
> CC	libavcodec/aacenc_tns.o
> CC	libavcodec/aacenctab.o
> CC	libavcodec/aacps_fixed.o
> CC	libavcodec/aacps_float.o
> CC	libavcodec/aacpsdsp_fixed.o
> CC	libavcodec/aacpsdsp_float.o
> CC	libavcodec/aacpsy.o
> CC	libavcodec/aacsbr.o
> CC	libavcodec/aacsbr_fixed.o
> CC	libavcodec/aactab.o
> CC	libavcodec/ac3_parser.o
> CC	libavcodec/adts_header.o
> CC	libavcodec/adts_parser.o
> CC	libavcodec/allcodecs.o
> CC	libavcodec/audio_frame_queue.o
> CC	libavcodec/avdct.o
> CC	libavcodec/avfft.o
> CC	libavcodec/avpacket.o
> CC	libavcodec/avpicture.o
> CC	libavcodec/bitstream.o
> CC	libavcodec/bitstream_filter.o
> CC	libavcodec/bitstream_filters.o
> CC	libavcodec/bsf.o
> CC	libavcodec/cbrt_data.o
> CC	libavcodec/cbrt_data_fixed.o
> CC	libavcodec/codec_desc.o
> CC	libavcodec/d3d11va.o
> CC	libavcodec/decode.o
> libavcodec/decode.c: In function 'compat_decode':
> libavcodec/decode.c:862:13: warning: 'refcounted_frames' is deprecated [-Wdeprecated-declarations]
>              if (!avctx->refcounted_frames) {
>              ^~
> In file included from libavcodec/decode.c:41:0:
> libavcodec/avcodec.h:2396:9: note: declared here
>      int refcounted_frames;
>          ^~~~~~~~~~~~~~~~~
> libavcodec/decode.c: In function 'avcodec_flush_buffers':
> libavcodec/decode.c:2049:5: warning: 'refcounted_frames' is deprecated [-Wdeprecated-declarations]
>      if (!avctx->refcounted_frames)
>      ^~
> In file included from libavcodec/decode.c:41:0:
> libavcodec/avcodec.h:2396:9: note: declared here
>      int refcounted_frames;
>          ^~~~~~~~~~~~~~~~~
> CC	libavcodec/dirac.o
> CC	libavcodec/dv_profile.o
> CC	libavcodec/encode.o
> libavcodec/encode.c: In function 'do_encode':
> libavcodec/encode.c:365:9: warning: 'avcodec_encode_video2' is deprecated [-Wdeprecated-declarations]
>          ret = avcodec_encode_video2(avctx, avctx->internal->buffer_pkt,
>          ^~~
> libavcodec/encode.c:258:25: note: declared here
>  int attribute_align_arg avcodec_encode_video2(AVCodecContext *avctx,
>                          ^~~~~~~~~~~~~~~~~~~~~
> libavcodec/encode.c:368:9: warning: 'avcodec_encode_audio2' is deprecated [-Wdeprecated-declarations]
>          ret = avcodec_encode_audio2(avctx, avctx->internal->buffer_pkt,
>          ^~~
> libavcodec/encode.c:118:25: note: declared here
>  int attribute_align_arg avcodec_encode_audio2(AVCodecContext *avctx,
>                          ^~~~~~~~~~~~~~~~~~~~~
> CC	libavcodec/fft_fixed.o
> CC	libavcodec/fft_fixed_32.o
> CC	libavcodec/fft_float.o
> CC	libavcodec/fft_init_table.o
> CC	libavcodec/frame_thread_encoder.o
> libavcodec/frame_thread_encoder.c: In function 'worker':
> libavcodec/frame_thread_encoder.c:89:9: warning: 'avcodec_encode_video2' is deprecated [-Wdeprecated-declarations]
>          ret = avcodec_encode_video2(avctx, pkt, frame, &got_packet);
>          ^~~
> In file included from libavcodec/frame_thread_encoder.h:24:0,
>                  from libavcodec/frame_thread_encoder.c:23:
> libavcodec/avcodec.h:5462:5: note: declared here
>  int avcodec_encode_video2(AVCodecContext *avctx, AVPacket *avpkt,
>      ^~~~~~~~~~~~~~~~~~~~~
> CC	libavcodec/iirfilter.o
> CC	libavcodec/imgconvert.o
> CC	libavcodec/jni.o
> CC	libavcodec/kbdwin.o
> CC	libavcodec/latm_parser.o
> CC	libavcodec/libopus.o
> CC	libavcodec/libopusdec.o
> CC	libavcodec/libopusenc.o
> CC	libavcodec/lpc.o
> CC	libavcodec/mathtables.o
> CC	libavcodec/mdct15.o
> CC	libavcodec/mdct_fixed.o
> CC	libavcodec/mdct_fixed_32.o
> CC	libavcodec/mdct_float.o
> CC	libavcodec/mediacodec.o
> CC	libavcodec/mjpegenc_huffman.o
> CC	libavcodec/mpeg12framerate.o
> CC	libavcodec/mpeg4audio.o
> CC	libavcodec/null_bsf.o
> CC	libavcodec/options.o
> libavcodec/options.c: In function 'codec_child_class_next':
> libavcodec/options.c:61:5: warning: 'av_codec_next' is deprecated [-Wdeprecated-declarations]
>      while (prev && (c = av_codec_next(c)))
>      ^~~~~
> In file included from libavcodec/options.c:27:0:
> libavcodec/avcodec.h:4118:10: note: declared here
>  AVCodec *av_codec_next(const AVCodec *c);
>           ^~~~~~~~~~~~~
> libavcodec/options.c:66:5: warning: 'av_codec_next' is deprecated [-Wdeprecated-declarations]
>      while (c = av_codec_next(c))
>      ^~~~~
> In file included from libavcodec/options.c:27:0:
> libavcodec/avcodec.h:4118:10: note: declared here
>  AVCodec *av_codec_next(const AVCodec *c);
>           ^~~~~~~~~~~~~
> CC	libavcodec/opus.o
> CC	libavcodec/opus_pvq.o
> CC	libavcodec/opus_rc.o
> CC	libavcodec/opusenc.o
> CC	libavcodec/opusenc_psy.o
> CC	libavcodec/opustab.o
> CC	libavcodec/parser.o
> CC	libavcodec/parsers.o
> CC	libavcodec/profiles.o
> CC	libavcodec/psymodel.o
> CC	libavcodec/pthread.o
> CC	libavcodec/pthread_frame.o
> CC	libavcodec/pthread_slice.o
> CC	libavcodec/qsv_api.o
> CC	libavcodec/raw.o
> CC	libavcodec/sbrdsp.o
> CC	libavcodec/sbrdsp_fixed.o
> CC	libavcodec/sinewin.o
> CC	libavcodec/sinewin_fixed.o
> CC	libavcodec/utils.o
> CC	libavcodec/v4l2_buffers.o
> CC	libavcodec/v4l2_context.o
> CC	libavcodec/v4l2_fmt.o
> CC	libavcodec/v4l2_m2m.o
> CC	libavcodec/vorbis_data.o
> CC	libavcodec/vorbis_parser.o
> X86ASM	libavcodec/x86/aacencdsp.o
> STRIP	libavcodec/x86/aacencdsp.o
> CC	libavcodec/x86/aacencdsp_init.o
> X86ASM	libavcodec/x86/aacpsdsp.o
> STRIP	libavcodec/x86/aacpsdsp.o
> CC	libavcodec/x86/aacpsdsp_init.o
> CC	libavcodec/x86/celt_pvq_init.o
> X86ASM	libavcodec/x86/celt_pvq_search.o
> STRIP	libavcodec/x86/celt_pvq_search.o
> CC	libavcodec/x86/constants.o
> X86ASM	libavcodec/x86/fft.o
> STRIP	libavcodec/x86/fft.o
> CC	libavcodec/x86/fft_init.o
> CC	libavcodec/x86/lpc.o
> X86ASM	libavcodec/x86/mdct15.o
> STRIP	libavcodec/x86/mdct15.o
> CC	libavcodec/x86/mdct15_init.o
> X86ASM	libavcodec/x86/sbrdsp.o
> STRIP	libavcodec/x86/sbrdsp.o
> CC	libavcodec/x86/sbrdsp_init.o
> CC	libavcodec/xiph.o
> AR	libavcodec/libavcodec.a
> ar: libavcodec/crystalhd.o: No such file or directory
> ffbuild/library.mak:21: recipe for target 'libavcodec/libavcodec.a' failed
> make: *** [libavcodec/libavcodec.a] Error 1
> Build ffmpeg-4-fit failed, ret=2
> ```
> 
> **Replay**
> 
> > ./configure

> **Did you eventually solve this problem?**

`TRANS_BY_GPT3`
