### ISSUE TITLE
SRS支持动态更改ingest配置吗，我该怎么配置

### ISSUE THREAD

**Issue by superlichao001** [ossrs/srs#2272]

**Comment by xhun2015** [comment]
I also want to ask this question, does the http API support dynamically changing the ingest configuration?

`TRANS_BY_GPT3`

**Comment by superlichao001** [comment]
If it is possible to support the include method like nginx, it would be great. We can put the ingest configuration in a fixed directory, such as "ingest", and then include "ingest/*.conf". This way, we can update the ingest configuration in the ingest directory and call the reload method to dynamically change the ingest configuration. This would be a bit more convenient. Of course, it would be even better if there is an open interface to directly modify the ingest configuration.

`TRANS_BY_GPT3`

**Comment by WallerHada** [comment]
Same request, for some business live streams, they cannot be directly pushed to the SRS server, so they can only be rebroadcasted by pulling their playback streams through ingest.

`TRANS_BY_GPT3`

**Comment by ghost** [comment]
Feel like it is possible to implement the dynamic ingest by calling ffmpeg to pull and push streams.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@cabios +1
