### ISSUE TITLE
webrtc 没有stop play 信令

### ISSUE THREAD

**Issue by dboyzhong** [ossrs/srs#2291]
**描述(Description)**

> srs的webrtc播放只有“play”的信令，而没有“stop play”的信令。

**期望行为(Expect)**

> 请问，是出于什么考虑没有stop play的信令呢，谢谢。

**Comment by duiniuluantanqin** [comment]
You can simply call `peerconnection.stop`.

`TRANS_BY_GPT3`

**Comment by dboyzhong** [comment]
@duiniuluantanqin Thank you.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Client PC.close is an active disconnection. After the disconnection, the server will receive a DTLS notification, and if it is lost, there will be a timeout.

stop' is similar to a DTLS alert, and the server may not necessarily receive it.

`TRANS_BY_GPT3`
