### ISSUE TITLE
跨运营商无法访问

### ISSUE THREAD

**Issue by xinyadada** [ossrs/srs#2292]
服务器部署在联通运营商上,用移动的网络无法进行访问

**Comment by xinyadada** [comment]
[tcp @ 0000027df561b840] Connection to tcp://ip:9002 failed: Error number -138 occurred
[rtmp @ 0000027df561ab00] Cannot open connection tcp://ip:9002
rtmp://ip:9002/hls/test: Unknown error

**Comment by winlinvip** [comment]
大哥，这是运营商bug，不是程序的bug吧。

**Comment by xinyadada** [comment]
确实

**Comment by xinyadada** [comment]
[2021-04-20 05:02:58.213][Error][1][592][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
是不是跨运营商连接超时容易掉呀

**Comment by xinyadada** [comment]
复现此bug只需要srs服务器出现运营商即可,比如srs服务器部署在联通运营商那,用移动的网络进行推流和拉流;阿里的云服务器一般是三方运营商都接入了,所以不建议用阿里的服务器进行复现

**Comment by winlinvip** [comment]
这个不是SRS的问题，我关闭了。
