### ISSUE TITLE
有支持hls推流的库吗？

### ISSUE THREAD

**Issue by SJJ-dot** [ossrs/srs#2295]

**Comment by xiaozhihong** [comment]
SRT, obs直接推, 就是mpeg-ts协议, 不知道能否满足你的需求

**Comment by SJJ-dot** [comment]
> SRT, obs直接推, 就是mpeg-ts协议, 不知道能否满足你的需求

好像不行，我们只能用http。有什么建议吗？今天刚接到的任务，没做过直播这一块
