### ISSUE TITLE
Cannot Transcode SRT Input

### ISSUE THREAD

**Issue by Baa14453** [ossrs/srs#2312]
**描述(Description)**

I'm trying to replace all RTMP with SRT, I can successfully stream from OBS to SRS and then generate HLS playlists, but I cannot transcode the stream and then generate that as HLS, I have tried both SRT and RTMP as output for transcoding but neither have worked when I am publishing SRT from OBS. However, if I publish RTMP from OBS and then transcode using RTMP to HLS then it works fine, this is what has worked until now.

This works :green_circle: 
| OBS  > SRS | SRS > SRS (Transcoding) | SRS > Output
| ------------- | ------------- | ------------- |
| RTMP  | RTMP  | HLS | 

--

This doesn't work :x: 
| OBS  > SRS | SRS > SRS (Transcoding) | SRS > Output
| ------------- | ------------- | ------------- |
| SRT  | RTMP  | HLS | 

--

This doesn't work :x: (Config below is this configuration)
| OBS  > SRS | SRS > SRS (Transcoding) | SRS > Output
| ------------- | ------------- | ------------- |
| SRT  | SRT  | HLS | 

--

This works :green_circle: 
| OBS  > SRS | SRS > Output
| ------------- | ------------- |
| SRT  | HLS | 

1. SRS版本(Version): `4.0.90`
1. SRS的日志如下(Log):

**SRS Console**
See [srs.log](https://github.com/ossrs/srs/files/6372226/srs.log).

**FFMPEG Log**
See [ffmpeg.log](https://github.com/ossrs/srs/files/6372233/ffmpeg.log)

1. SRS的配置如下(Config):
```
# the config for srs use ffmpeg to transcode
# @see https://github.com/ossrs/srs/wiki/v1_CN_SampleFFMPEG
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
srt_server {
    enabled on;
    listen 10080;
    connect_timeout 4000;
    peerlatency 300;
    recvlatency 300;
    mix_correct on;
}

vhost vhost {
    gop_cache       off;
    queue_length    10;
    mr {
        enabled     off;
    }
    mw_latency      100;
    transcode {
        enabled     on;
        ffmpeg      /opt/ffmpeg/ffmpeg;
        engine ff {
            enabled         on;
            vfilter {
                vf scale=w=1920:h=1080:force_original_aspect_ratio=decrease;
                loglevel       debug;
            }
            vcodec          libx264;
            vbitrate        4500;
            vfps            60;
            vwidth          0;
            vheight         0;
            vthreads        4;
            vprofile        high;
            vpreset         superfast;
            vparams {
                g       120;
                tune    zerolatency;
                vlevel  4;
            }
            acodec          aac;
            abitrate        256;
            achannels       2;
            aparams {
            }
            output          srt://127.0.0.1:10080?mode=caller&transtype=live&streamid=#!::h=[vhost]-HLS/[app]/[stream]_60-fps,m=publish;
        }

    }
}

vhost vhost-HLS {
    gop_cache       off;
    queue_length    10;
    min_latency     on;
    mr {
        enabled     off;
    }
    mw_latency      100;
    hls {
        enabled         on;
        hls_on_error    disconnect;
        hls_fragment    4;
        hls_window      32;
        hls_path        /var/www/srs-hls-streamkey;
        hls_dispose 1;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
    }
}

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. Use a version of OBS prepared for SRT streaming. I got mine from the Ubuntu Snapcraft store `snap install obs-studio`
1. Set streaming server to Custom and parameters to: `srt://<domain name>:10080?mode=caller&transtype=live&streamid=#!::h=vhost/ingress/streamkey,m=publish`
1. No HLS playlist is generated.

**期望行为(Expect)**

1. Use a version of OBS prepared for SRT streaming. I got mine from the Ubuntu Snapcraft store `snap install obs-studio`
1. Set streaming server to Custom and parameters to: `srt://<domain name>:10080?mode=caller&transtype=live&streamid=#!::h=vhost/ingress/streamkey,m=publish`
1. Transcoded video is output as HLS playlists.

**Comment by Baa14453** [comment]
Added some tables to demonstrate what I've tried.

**Comment by Baa14453** [comment]
I think I've misunderstood how the
```
hls {

}
```
config works, I think this is only capable of accepting an RTMP feed and will never work with SRT internally, I will do more testing to see if there is a workable method of SRT transcoding.

**Comment by winlinvip** [comment]
Please use FFmpeg to transcode.
