### ISSUE TITLE
SRT: 推流造成的错误

### ISSUE THREAD

**Issue by dongrixinyu** [ossrs/srs#2318]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `release4.0`
1. SRS的日志如下(Log):
```
[2021-04-26 17:33:49.490][Trace][113743][x9b94nc4] rtmp client construct url:rtmp://127.0.0.1:1935/live?vhost=uplive.sls.com/mdp265
srs: ./src/srt/ts_demux.cpp:415: int ts_demux::pes_parse(unsigned char*, size_t, unsigned char**, size_t&, uint64_t&, uint64_t&): Assertion `0x80 == p[pos]' failed.

```
1. SRS的配置如下(Config):
```
# SRT config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          18080;
    dir             ./objs/nginx/html;
}

rtc_server {        
    enabled         on;
    listen          18000;
    candidate       $CANDIDATE;
}

srt_server {
    enabled on;
    listen 10081;
    maxbw 1000000000;
    connect_timeout 4000;
    peerlatency 300;
    recvlatency 300;
}

vhost __defaultVhost__ {
}
vhost srs.srt.com.cn {
}
vhost uplive.sls.com {
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `用工具软件向服务器推 srt 流`
1. `srt://192.168.35.2:10081?streamid=#!::h=live/livestream,m=publish`
1. `推流是 ts 格式的数据，video codec h264， audio codec aac`

**期望行为(Expect)**

> 那个报错是什么问题？

**Comment by dongrixinyu** [comment]
Changed to another version, which is the latest development branch, the develop branch, and there is no longer this issue.

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
> Switched to another version, which is the latest development branch, the "develop" branch, and the issue is no longer present.

> Looking at the logs, there seems to be an issue with the MPEG-TS stream. The initial fields are incorrect, causing an assertion error. Could you please check if the streaming is in MPEG-TS format?

`TRANS_BY_GPT3`

**Comment by LionMiao** [comment]
>![WeChat Image_20210927163056](https://user-images.githubusercontent.com/3351903/134872977-3871ed6a-8ec8-450b-a386-e8de814bf6e1.png)换了另外一个版本，也就是最新的开发分支 ，develop 分支，就没这个问题了
[你的这个问题解决了吗？我按照你说的换了最新的develop分支，一样的报错。

**Comment by LionMiao** [comment]
> Switched to another version, which is the latest development branch, the "develop" branch, and the issue is no longer present.

> Has your issue been resolved? I followed your instructions and switched to the latest "develop" branch, but the error remains the same.
![WeChat Image_20210927163056](https://user-images.githubusercontent.com/3351903/134873145-9773920d-c170-4266-adcb-1835fa5e2479.png)

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
@dongrixinyu @LionMiao 
Hello both, this issue has been partially fixed and a pull request is being submitted.

I have set up a server on the public network. Are both of you in the SRS group? Could you please contact me? I would like to stream to my server and help resolve this issue. Thank you in advance.

If you are not in the group, please contact me on WeChat: sweibd. I will assist in resolving this issue.

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
@dongrixinyu @LionMiao The bug has been fixed and merged into the develop branch.

`TRANS_BY_GPT3`
