### ISSUE TITLE
srt 推流时延高

### ISSUE THREAD

**Issue by dongrixinyu** [ossrs/srs#2319]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `release 4.0`
1. SRS的日志如下(Log):
```
正常的
```
1. SRS的配置如下(Config):
```
默认的  srt 配置
```

**重现(Replay)**

srt 时延比 rtmp 的 低时延配置还要高，在1s 左右，而 rtmp 配置低时延可以达到 400ms

**Comment by winlinvip** [comment]
SRT和低延时没有关系，这个协议设计时并不是为了低延迟设计的。
