### ISSUE TITLE
WebRTC: Forward: 使用RTC推到SRS, 然后开启forward后转入腾讯云直播(或阿里云直播)后卡顿

### ISSUE THREAD

**Issue by yangyangkeai** [ossrs/srs#2341]
当使用RTC协议推入SRS再forward云服务后视频质量不稳定
推入阿里云后断断续续, 有时候没有声音,  有时候只有声音
推入腾讯云后基本上都没有声音,  并且播放等待黑屏时间很长, 画面质量一般, 有时候画面卡顿马赛克

1. SRS版本(Version): `4.0.103`
1. SRS的日志如下(Log):
```
没啥特殊报错的日志
```
1. SRS的配置如下(Config):
```
没啥特殊配置

rtc {
        enabled     on;
        rtc_to_rtmp on;
    }

forward {
        enabled on;
        destination xxxxx;
    }

```

**Comment by ZJM6658** [comment]
老哥最后怎么解决的，方便留个联系方式咨询一下吗

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
