### ISSUE TITLE
hls m3u8 EXTINF tag  malformed?

### ISSUE THREAD

**Issue by mrdevis** [ossrs/srs#2343]
Hi,
i am using a standard http.hls.conf to stream mainly audio to mobile clients (android, ios)::

    `listen              1935;
    max_connections     1000;
    daemon              off;
    srs_log_level       verbose;
    srs_log_tank        file;
    srs_log_file        /usr/local/srs/srs.log;
    
    pid                 /var/run/srs.pid;
    
    http_server {
        enabled         on;
        listen          80;
        dir             /var/local/srs/www;
    }
    vhost sc.cs {
            gop_cache       off; # inserted

    hls {
        enabled         on;
        hls_fragment    2;
        hls_window      10;
        hls_path        /var/local/srs/www;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
    }
}`

Issue:
When I send rtmp from ffmpeg to srs I get audio on newest android and iOS. On Android 5, the standard player is stuck. the m3u8 file looks like this:
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:41
#EXT-X-TARGETDURATION:7
#EXTINF:6.014, no desc
livestream-41.ts
#EXTINF:6.014, no desc
livestream-42.ts
#EXTINF:6.014, no desc
livestream-43.ts
#EXTINF:6.015, no desc
livestream-44.ts
#EXTINF:6.014, no desc
livestream-45.ts
`
However, when I send ts files directlyfrom ffmpeg  into the same hls directory, all android mobiles work, and the m3u8 file looks like this::
`#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXTINF:10.008422,
livestream000.ts
#EXTINF:10.008256,
livestream001.ts
#EXTINF:9.985100,
livestream002.ts
#EXTINF:10.008056,
livestream003.ts
#EXTINF:10.007778,
livestream004.ts
#EXTINF:9.984700,
livestream005.ts
#EXTINF:10.008033,
livestream006.ts
#EXTINF:10.007844,
livestream007.ts
#EXTINF:9.985078,
livestream008.ts
#EXTINF:10.008256,
livestream009.ts`

please note that the srs m3u8 format inserts a "no desc", probably followed by a return. According to the specs, the 
tag  format should be::
` #EXTINF:<duration>,<title>`

Maybe I oversee something, or maybe something is beyond my understanding, but can this difference be the cause of the stream not working on android 5? 

I would like to use the auto-cleaning  tools in srs to clean up the streamdir automatically, as writing ts files directly from ffmpeg does not have that functionality...

Thanks for any pointers!

**Comment by winlinvip** [comment]
Use `on_hls` to manage your ts files.
