### ISSUE TITLE
rtc转rtmp后网页播放flv卡顿

### ISSUE THREAD

**Issue by 1045917067** [ossrs/srs#2349]
当使用RTC协议推入SRS，使用flv.js播放flv，出现音频提示，几分钟后卡顿，最后停止
![1620821390005fca2a379b07ed959b93006b9df9b1817](https://user-images.githubusercontent.com/22162100/117974693-7bdfe580-b2f3-11eb-8c92-bd6d0c25ce7e.jpg)

SRS版本(Version): develop
SRS的日志如下(Log):
没啥特殊报错的日志
SRS的配置如下(Config):
没啥特殊配置

rtc {
        enabled     on;
        rtc_to_rtmp on;
    }

**Comment by 1045917067** [comment]
srs_error_t SrsRtmpFromRtcBridger::trancode_audio(SrsRtpPacket2 *pkt)
packet_aac(&out_rtmp, (*it)->samples[0].bytes, (*it)->samples[0].size, (*it)->dts, is_first_audio);
packet_aac timestamp should use (*it)->dts

`TRANS_BY_GPT3`

**Comment by flying1314** [comment]
No one raised a PR, huh?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@Bepartofyou, please take a look at this PR.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Should be fixed in SRS 4.0
