### ISSUE TITLE
srs的gb28181功能小问题

### ISSUE THREAD

**Issue by Phoebus888** [ossrs/srs#2351]
我使用的是海康摄像头
海康摄像头挂掉，重启海康摄像头后，海康摄像头没有自动推流到srs流媒体平台，需要关闭海康摄像头的gb28181功能，再次启动又可以推流到srs流媒体平台
这个自动重连能不能在srs平台实现

**Comment by yushimeng** [comment]
This problem feels like it's related to the camera, SRS shouldn't be the one to fix it.

`TRANS_BY_GPT3`

**Comment by Phoebus888** [comment]
> This problem feels like an issue with the camera, it shouldn't be solved by SRS, right?

> I have the same problem with Hikvision cameras here. What kind of cameras do you have there that don't have this issue?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@mico-yu Thanks! 👍
