### ISSUE TITLE
[Question] - Huge Live stream architecture

### ISSUE THREAD

**Issue by kaaaq** [ossrs/srs#2360]
Hi,
I wanna Deploy a big cluster of SRS (Now I'm considering scalability for the next 10 years )
I was thinking about the following Architecture:

![image](https://user-images.githubusercontent.com/43205944/118480466-87824080-b727-11eb-95b5-4dd9d8aabf9b.png)
Client is publishing Stream B on origin servers and origin servers are sending this stream to 3 servers (server A,B,C)
If in the middle of streaming event , the number of clients became more than bandwidth of this 3 servers (for instace, with 10Gb NIC on each server and 2mb bandwidth of each stream I can just handle 5000 stream for playback)
So for this 3 servers I can just handle specific number of live stream playback and I don't know which stream would have more clients for playback to push it to 5 server or more
Can SRS handle this problem dynamically?
What is best solution to solve this issue?

**Comment by winlinvip** [comment]
1. Server A,B,C is not a `server`, it's `servers` or region. The region A,B,C contains more than one servers.
2. The edge cluster is design for huge players, for example, Origin(1 player) => Edges(each 100 players) => Edges(each 1000 streams), which serves at most 100*1000=100k players, and there is only one player in origin server.
3. The origin cluster is design for huge streams(publishers), where each publisher publish one stream to origin.

Please try this arch, do some research and demos. And bellow is about the load balance, and never forget the scalability of system depends on GSLB first, not only about media servers:

1. Create multiple origin-edge clusters, where GSLB can dispatch client to different origin-edge cluster, for example, by url hash, the client which play `x://xxx/x/x` is dispatched to cluster A, and client plays `y://yyy/y` is dispatched to cluster B.
2. The GSLS is only a load balance API, for example, an HTTP RESTful API, to get the server to publish or play.
3. The common tech for GSLB is DNS or HTTP-DNS, please do some research.
