### ISSUE TITLE
Can't connect to SRT server

### ISSUE THREAD

**Issue by tepaze** [ossrs/srs#2365]
Hi,
I'm trying ti use OSS as SRT server for multiple IN and multiple OUT. But when i've tried to connect to the SRS SRT Server with VMix or OBS, the streamer fail to connect... Maybe i do something wrong ?

1. SRS版本(Version): 4.0.115

2. SRS的配置如下(Config):

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
daemon              on;
`http_api` {
    enabled         on;
    listen          1985;
}
`http_server` {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

`srt_server` {
    enabled on;
    listen 10080;
    maxbw 1000000000;
    connect_timeout 4000;
    peerlatency 300;
    recvlatency 300;
    default_app live;
}

`vhost __defaultVhost__ `{
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

Docker :
`docker run --rm -p 1935:1935 -p 1985:1985 -p 8080:8080 -v ".C:\my_path\conf\srs.conf":/usr/local/srs/conf/srs.conf  ossrs/srs:v4.0.115`

On OBS the streaming target is :
`srt://localhost:10080?streamid=live/livestream?m=push`
On VMix i tried with stream ID empty and filled (1234)

Best regard

**Comment by winlinvip** [comment]
Dup to https://github.com/ossrs/srs/issues/1147

别瞎尝试，按Issue的命令来，别自己乱改。

**Comment by tepaze** [comment]
Thank you winlinvip,

What about SRT caller to play SRT video ? I didn't found anything...

Best Regards
