### ISSUE TITLE
iOS原生使用GoogleWebRTC推流，srs无法播放

### ISSUE THREAD

**Issue by ChokWah** [ossrs/srs#2368]
问题描述： iOS原生使用GoogleWebRTC推流，srs无法播放

1. SRS版本(Version): `v4.0.91`
1. SRS的日志如下(Log):
```
无
```
1. SRS的配置如下(Config):
```
docker run --rm --env CANDIDATE=$(ifconfig en0 inet| grep 'inet '|awk '{print $2}') \
  -p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp \
  registry.cn-hangzhou.aliyuncs.com/ossrs/srs:v4.0.91 \
  objs/srs -c conf/rtc.conf

```
环境：iOS项目，第三方GoogleWebRTC，AFNetworking，连接WiFi。
电脑docker部署srs，手机上能访问到player.html。

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 原生设置本地视频流，构造RTCPeerConnection，构造offer，设置本地描述
2. 请求http://xxxx.local:1985/rtc/v1/publish/
3. 返回200，并返回service,sdp,sessionid.
4. sdp作为answer，设置远端描述。SDK提示设置成功。
5. 在电脑打开player.html，选择rtc播放器，播放。
6. 显示一直转圈圈，无画面

补充：
ICEService使用谷歌地址，@"stun:stun.l.google.com:19302";@"stun:23.21.150.121";
控制台查看网页输出，成功设置了本地，远端描述。
需要可提供iOS源码工程，可免证书运行。
**期望行为(Expect)**

> iOS工程运行，设置本地，远端描述成功。在电脑打开player.html，选择rtc播放器，播放。显示手机视频流。

**Comment by winlinvip** [comment]
Do not support TURN, connect directly to the server. Please refer to the usage of [srs.sdk.js](https://github.com/ossrs/srs/blob/4.0release/trunk/research/players/js/srs.sdk.js).

`TRANS_BY_GPT3`
