### ISSUE TITLE
srs_app_gb28181_stack.cpp:65: undefined reference to `libiconv'

### ISSUE THREAD

**Issue by ghostsf** [ossrs/srs#2372]
**描述(Description)**

srs_app_gb28181_stack.cpp:65: undefined reference to `libiconv'

1. SRS版本(Version): `4.0.122`

**重现(Replay)**

./configure --with-gb28181
make clean && make

centos7 编译gb28181
出现undefined reference to `libiconv'问题

**Comment by ghostsf** [comment]
configure add "LibIconvfile="/usr/local/lib/libiconv.a"
fixed

**Comment by z325988** [comment]
I am using Ubuntu 20.04. Is it necessary to modify this part in the configure file?
![image](https://user-images.githubusercontent.com/30429917/120783996-32835e80-c55e-11eb-9e7c-c017846548d1.png)

`TRANS_BY_GPT3`

**Comment by ghostsf** [comment]
> I am using Ubuntu 20.04. Do you mean modifying this part in the configure file?
> ![image](https://user-images.githubusercontent.com/30429917/120783996-32835e80-c55e-11eb-9e7c-c017846548d1.png)

This is a configuration for macOS. You can write it outside the if statement.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed by `--iconv=off`
