### ISSUE TITLE
编译srs报错：Build ffmpeg-4-fit failed

### ISSUE THREAD

**Issue by xiekai-aiai** [ossrs/srs#2377]
**Build ffmpeg-4-fit failed**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `srs-4.0release`
1. SRS的日志如下(Log):
AR	libavcodec/libavcodec.a
ar: libavcodec/aarch64/aacpsdsp_neon.o: No such file or directory
ffbuild/library.mak:21: recipe for target 'libavcodec/libavcodec.a' failed
make: *** [libavcodec/libavcodec.a] Error 1
Build ffmpeg-4-fit failed, ret=2

系统：No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

编译srs报错，执行./configure时报错。报错信息如上，后来我手动将ar aacpsdsp_neon.o 这个的地方注释掉了，但是又报错了
AR	libavcodec/libavcodec.a
ar: libavcodec/aarch64/fft_neon.o: No such file or directory
ffbuild/library.mak:21: recipe for target 'libavcodec/libavcodec.a' failed
make: *** [libavcodec/libavcodec.a] Error 1
Build ffmpeg-4-fit failed, ret=2

**Comment by winlinvip** [comment]
Ubuntu18, compile using Docker or refer to the commands in the Dockerfile: https://github.com/ossrs/srs-docker/tree/ubuntu18

`TRANS_BY_GPT3`

**Comment by briand123** [comment]
FYI - I pulled 4.0 code and still see this (or very similar) issue building for aarch64 on raspberry pi 4 when running "./config" and it gets deep into the ffmpeg-4-fit build:
AR      libavcodec/libavcodec.a
ar: libavcodec/aarch64/aacpsdsp_neon.o: No such file or directory
make: *** [ffbuild/library.mak:22: libavcodec/libavcodec.a] Error 1
Build ffmpeg-4-fit failed, ret=2
brian@PI-SSM01:~/srs/trunk $

I'm trying to find the diffs for the fix but only seeing it was closed w/o diffs.  TY
