### ISSUE TITLE
开启webrtc配置后，发起RTMP推流压测时CPU非常高

### ISSUE THREAD

**Issue by myhhello** [ossrs/srs#2389]
**描述(Description)**

> 开启webrtc配置后，发起RTMP推流压测时CPU非常高，仅100路推流CPU就100%，但关闭webrtc时CPU表现正常。

1. SRS版本(Version): `4.0 release (Thu May 27 11:13:31 2021)`
2. 测试机配置:
```
 CPU： Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz,  内存： 16G
```
3. SRS的配置如下(Config):
```
listen              1935;
max_connections     1000;
srs_log_file        ./objs/srs.log;

http_server {
    enabled         on;
    listen          8081;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    candidate       192.168.1.37;
}

vhost __defaultVhost__ {
   # tcp_nodelay     on;
   # min_latency     on;
    
   # play {
   #     gop_cache       off;
   #     queue_length    10;
   #     mw_latency      100;
   # }
 
    rtc {
        enabled     on;
        bframe      discard;
    }
}

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `启动srs：  ./objs/srs -c conf/rtc.conf`
1. `启动模拟推流： ./objs/sb_rtmp_publish -i doc/source.200kbps.768x320.flv -c 100 -r rtmp://127.0.0.1:1935/live/livestream_{i} `
1. `观察到CPU： 17267 root      20   0  189788 123548   3980 R 100.0  0.8   0:10.96 srs   `

备注：非webrtc场景下压测，使用同一个压测文件，推拉流都是2000路时，cpu是71%

**期望行为(Expect)**

> webrtc使用场景下，RTMP推流 CPU能降低。

**Comment by duiniuluantanqin** [comment]
What caused the audio transcoding? Can you find a file without audio to test and verify?

`TRANS_BY_GPT3`

**Comment by myhhello** [comment]
Indeed, the CPU usage decreased when testing pure video files without audio. When audio is included and transcoded, the CPU usage becomes high for unknown reasons. Do you have any suggestions or recommendations?

`TRANS_BY_GPT3`

**Comment by myhhello** [comment]
I have conducted some preliminary tracking investigations, and it seems that the CPU is mainly consumed by the avcodec_send_frame and avcodec_receive_packet processes in ffmpeg. I wonder if the AAC decoding in ffmpeg is not very CPU-friendly? Do you have any suggestions or alternative approaches?

`TRANS_BY_GPT3`

**Comment by RuiChen1998** [comment]
I also noticed the same issue, is there any method for optimization?

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> I have conducted some preliminary tracking investigations, and it seems that the CPU is mainly consumed by the processing of avcodec_send_frame and avcodec_receive_packet in ffmpeg. I wonder if ffmpeg's AAC decoding is not very CPU-friendly? Do you have any suggestions or other ideas?

WebRTC does not support AAC, so the only option is to transcode it to Opus. There is not much else that can be done.

`TRANS_BY_GPT3`

**Comment by myhhello** [comment]
We tried replacing the AAC decoding of ffmpeg with direct decoding using libfaad. In the case of streaming with 100 concurrent channels, it seems that the CPU usage decreases from 100% to just over 80%, which is a slight improvement. However, the improvement is still quite limited.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Please describe your actual use case. Is the stream source from IPC, file, or OBS screen capture?

- If the source is IPC, you can use G711 encoding (you can follow this PR: https://github.com/ossrs/srs/pull/2385, which is currently incomplete).
- If it is a file, consider pre-transcoding it to Opus.
- If it is a screen capture, consider using WebRTC publish.

`TRANS_BY_GPT3`

**Comment by myhhello** [comment]
I'm very sorry for not seeing your reply in a timely manner. The current scenario is live streaming on the Android platform. We have developed our own Android application for RTMP streaming (H264+AAC). Recently, we have made two attempts: one is to forcefully carry the Opus stream in RTMP and then use SRS for simple passthrough, which has worked very well; the other is to change the client to native WebRTC streaming, which also has a good effect. Thank you very much for your open-source contribution, which has simplified a lot of our work. Additionally, there is indeed a possibility of IPC as you mentioned. We look forward to further support for G711 as you mentioned.

`TRANS_BY_GPT3`

**Comment by myhhello** [comment]
In our current scenario, we are only testing the rtmp (opus) or webrtc solutions for now. If we confirm them, we will also face the issue of recording. For webrtc recording, it seems that it should be converted to rtmp before recording to avoid transcoding. In order to avoid transcoding, the requirement for webm recording or other recording formats also arises. Phew.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Each audio transcoding consumes about 2%, so with 100 routes, the CPU usage will definitely be high.

`TRANS_BY_GPT3`

**Comment by qingshuicn** [comment]
> Each audio transcoding consumes about 2%, so with 100 streams, the CPU usage will definitely be high.
Streaming 100-150 streams will also require almost 100% CPU usage.

`TRANS_BY_GPT3`
