### ISSUE TITLE
GB28181：摄像头流匹配的Vhost为空，怀疑output没起作用

### ISSUE THREAD

**Issue by ox188** [ossrs/srs#2391]
Migrate to https://github.com/ossrs/srs-gb28181/issues/29

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by ox188** [comment]
Why do you suspect that the output in stream_caster is not working, because:
1. Changing the output to any value does not affect the streaming and pulling of the camera;
2. Modifying the output to another server (SRS) on a different machine also does not transfer the camera stream to the other server.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It doesn't seem to be a vhost issue, even an empty one will become the default vhost.

I need to investigate what the problem is. You can try to reproduce it and see what issues arise.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/29

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
