### ISSUE TITLE
视频流在线人数统计不准确

### ISSUE THREAD

**Issue by mstaryi** [ossrs/srs#2396]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version):v4.0.117
1. SRS的日志如下(Log):
无
1. SRS的配置如下(Config):
docker镜像中的默认配置conf/srs.conf

**重现(Replay)**
1. 推流后在控制台查看在线人数为1人，点击预览在srs播放器中播放流
2. 此时在线人数为2人，在客户端中可以看到播放客户单
2. 约5分钟左右后，在线人数变为1人，客户端中看不到播放客户端，但srs播放器中视频任然在正常播放

反复测试了多次均有此问题

**期望行为(Expect)**
在线人数为2人

**Comment by duiniuluantanqin** [comment]
是通过webrtc播放，还是flv播放？还是其他？说清楚呀

**Comment by mstaryi** [comment]
@duiniuluantanqin 是srs播放器通过flv播放的。
另外，我发现网页最小化之后flv播放就会暂停。这个在直播里面感觉是不好的，会导致时延变长,服务端的缓存也会多占，建议可以让他一直放

**Comment by duiniuluantanqin** [comment]
> @duiniuluantanqin 是srs播放器通过flv播放的。
> 另外，我发现srs_player.html播放flv时只要网页不在前台显示(比如点击切换到同一个窗口的其它网页标签)播放就会暂停。这个在直播里面感觉是不好的，会导致时延变长,服务端的缓存也会多占，建议可以让他一直放

前端代码的问题吧，你用[官网提供的播放DEMO](http://ossrs.net/players/srs_player.html)试试，我这里测试，切换标签并不会停止。

**Comment by mstaryi** [comment]
我是用的播放demo上的浏览器哦，我录制了一个简短的测试视频给你演示，切换窗口标签后(大概3s左右), 再返回时可以看到时间是从切换前的时间继续的，预期窗口被切换视频应该继续播放。
浏览器版本：chrome 90.0.4430.212
https://user-images.githubusercontent.com/26699467/122025746-32a41980-cdfc-11eb-8370-96d0ad1f9997.mp4

**Comment by duiniuluantanqin** [comment]
你换个浏览器或者换台电脑试试？我这里怎么操作都不能复现。

**Comment by winlinvip** [comment]
4.0.117应该不行吧。更新试试。
