### ISSUE TITLE
CORS issue when access HTTP-FLV with Cross Region in HTTP/2

### ISSUE THREAD

**Issue by keroic** [ossrs/srs#2398]
Description
> Unable to Play the HTTP-FLV in Browser when the Server accept HTTP/2 Request

1. SRS版本(Version): 3.0

Replay
> Use flv.js to create Player to connect to the SRS FLV which behind the HTTP/2 and HTTPS Server, e.g. AWS CloudFront
> When request init, the Request Header "origin" would be Sent to the SRS Backend, check from the Source File "trunk/src/protocol/srs_http_stack.cpp" Line 837 to check whether "Origin" Header exist, so possible Case Sensitive issue for the checking "Origin" vs "origin"
> Try to change back to use HTTP/1.1, the Player can be able to connect as the Request Header return back to use "Origin"

**Comment by duiniuluantanqin** [comment]
I'm afraid it's not Case Sensitive issue, because srs will change lowercase to uppercase when parse message.
The code in file `srs_http_stack.cpp` , Function `void SrsHttpHeader::set(string key, string value)`, Line `137`.
Also, i test it through http2, by `Insomnia`, It was not replicated.

**Comment by winlinvip** [comment]
SRS does not support HTTP/2 right now.
