### ISSUE TITLE
GB28181: jitterbuffer memory leak

### ISSUE THREAD

**Issue by yushimeng** [ossrs/srs#2408]
FIXED:  
//    jitter_buffer->SetNackMode(kNoNack, -1, -1);
//    jitter_buffer_audio->SetNackMode(kNoNack, -1, -1);
srs_error_t SrsGb28181RtmpMuxer::initialize(SrsServer *s, SrsRequest* r)
{
    srs_error_t err = srs_success;

    if (!jitter_buffer) {
        jitter_buffer = new SrsPsJitterBuffer(channel_id);
    }

    jitter_buffer->SetDecodeErrorMode(kSelectiveErrors);
    jitter_buffer->SetNackMode(kNoNack, -1, -1);
    jitter_buffer->SetNackSettings(250, 450, 0);

    if (!jitter_buffer_audio) {
        jitter_buffer_audio = new SrsPsJitterBuffer(channel_id);
    }

    jitter_buffer_audio->SetDecodeErrorMode(kSelectiveErrors);
    jitter_buffer_audio->SetNackMode(kNoNack, -1, -1);
    jitter_buffer_audio->SetNackSettings(250, 450, 0);

    if (!source_publish) return err;
    // ......
}

**Comment by wguizhou2008** [comment]
What is the reason? Just comment it out?

`TRANS_BY_GPT3`

**Comment by xialixin** [comment]
https://github.com/ossrs/srs/pull/2668 During the testing process, it was found that there is no relationship based on nack. The main issue is with the parsing of the PS stream. It is possible that there is no key frame marker, which leads to continuous buffering of the GOP for rtmp. In normal cases, when a key frame is received, it clears the previous frames. However, if there is an error with the key frame, it may not clear the previous frames, resulting in continuous memory increase. I'm not sure if you are experiencing the same issue in your environment. Please try with the latest version.

`TRANS_BY_GPT3`
