### ISSUE TITLE
ingest 采集中断，input的type使用是 stream

### ISSUE THREAD

**Issue by gongminrui** [ossrs/srs#2414]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
ingest 采集会不定期的中断采集，不知是不是input的rtmp不稳定导致，如果网络不好，能不能自动重新执行采集呢
1. SRS版本(Version): `4.0.0`
1. SRS的日志如下(Log):
2. objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log 最后中断的日志
Press [q] to stop, [?] for help
frame=    0 fps=0.0 q=-1.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    ^Mframe=    0 fps=0.0 q=-1.0 size=       1kB time=00:00:01.69 bitrate=   2.6kbits/s speed=1.65x    ^Mframe=    1 fps=0.3 q=-1.0 size=      76kB time=00:00:01.71 bitrate= 363.4kbits/s speed=0.533x    ^Mframe=    5 fps=1.2 q=-1.0 size=      85kB time=00:00:01.85 bitrate= 374.9kbits/s speed=0.451x    ^Mframe=    8 fps=1.6 q=-1.0 size=      93kB time=00:00:01.95 bitrate= 392.2kbits/s speed=0.388x    ^Mframe=   14 fps=2.0 q=-1.0 size=     114kB time=00:00:02.15 bitrate= 431.1kbits/s speed=0.303x    ^Mframe=   26 fps=3.4 q=-1.0 size=     160kB time=00:00:02.55 bitrate= 512.9kbits/s speed=0.332x    ^Mframe=   28 fps=2.8 q=-1.0 size=     169kB time=00:00:02.60 bitrate= 531.6kbits/s speed=0.261x    ^Mframe=   32 fps=3.0 q=-1.0 size=     193kB time=00:00:02.74 bitrate= 577.1kbits/s speed=0.258x    ^Mframe=   34 fps=3.0 q=-1.0 size=     202kB time=00:00:02.80 bitrate= 589.3kbits/s speed=0.248x    ^Mframe=   37 fps=3.1 q=-1.0 size=     219kB time=00:00:02.90 bitrate= 618.2kbits/s speed=0.241x    ^Mframe=   39 fps=2.7 q=-1.0 size=     231kB time=00:00:02.99 bitrate= 633.1kbits/s speed=0.208x    ^Mframe=   45 fps=2.9 q=-1.0 size=     262kB time=00:00:03.18 bitrate= 673.6kbits/s speed=0.204x    ^Mframe=   48 fps=2.7 q=-1.0 size=     279kB time=00:00:03.29 bitrate= 692.9kbits/s speed=0.186x    ^Mframe=   58 fps=3.1 q=-1.0 size=     317kB time=00:00:03.60 bitrate= 720.3kbits/s speed=0.19x    ^Mframe=   60 fps=3.1 q=-1.0 size=     336kB time=00:00:03.69 bitrate= 746.8kbits/s speed=0.188x    ^Mframe=   61 fps=2.6 q=-1.0 size=     398kB time=00:00:03.71 bitrate= 877.3kbits/s speed=0.161x    ^Mframe=   62 fps=2.3 q=-1.0 size=     399kB time=00:00:03.76 bitrate= 869.6kbits/s speed=0.141x    ^Mav_interleaved_write_frame(): Broken pipe
frame=   66 fps=1.5 q=-1.0 size=     406kB time=00:00:03.88 bitrate= 856.8kbits/s speed=0.0911x    ^M[flv @ 0x3688480] Failed to update header with correct duration.
[flv @ 0x3688480] Failed to update header with correct filesize.
Error writing trailer of rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream: Broken pipe
frame=   66 fps=1.5 q=-1.0 Lsize=     406kB time=00:00:03.88 bitrate= 856.8kbits/s speed=0.0911x
video:373kB audio:30kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.612564%
Conversion failed!

1. SRS的配置如下(Config):

> ingest livestream {
        enabled      on;
        input {
            type    stream;
            url     rtmp://182.3.4.5?token=rewrewrew;
        }
        ffmpeg      /home/bakgrd/srs/ffmpeg-4.4/ffmpeg;
        engine {
            enabled         off;
            output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
FFmpeg问题，Ingest会有重试。
