### ISSUE TITLE
使用不同设备推同一路流的时候，第二设备推的流，切成ts切片没有图像，只有声音。

### ISSUE THREAD

**Issue by parkerlu** [ossrs/srs#2433]
**描述(Description)**

> 不同设备推同一路流时，第二个设备推流后，形成的ts文件，没有图像，只有声音。
>场景1，
使用编码器进行推流，然后切换由obs进行推流。尽管码流，图像大小设置完全相同，但是当obs进行推流时，播放m3u8的文件时，就没有图像，只有声音。用ffmpeg查看ts文件，也是显示没有视频信号。但是播放rtmp流一切正常。

>场景2
使用a电脑的obs推流，中途让b电脑的obs推流，b电脑推的流就没有图像，只有声音。同上情况。

只有切回第一次推流的设备，才能有图像。要么重启srs才能解决。

1. SRS版本(Version): `SRS3.0` 
1. SRS的日志如下(Log):
```
Log 一切正常
```
1. SRS的配置如下(Config):
```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        /var/log/srs/srs.log;
http_api {
    enabled         on;
    listen          1985;
    crossdomain     on;

}

stats {
    # the index of device ip.
    # we may retrieve more than one network device.
    # default: 0
    network         0;
    # the device name to stat the disk iops.
    # ignore the device of /proc/diskstats if not configed.
    disk            sda sdb xvda xvdb;
}


vhost __defaultVhost__ {

  hls {
        enabled         on;
        hls_storage     disk;
        hls_path        /storage;
        hls_fragment    5;
        hls_window      30;
        hls_acodec      aac;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[2006]-[01]-[02]-[stream]/[stream]-[seq].ts;
        hls_cleanup     on;
    }

}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `用A电脑上OBS推流 rtmp://your-server/live/stream1`
2. `暂停推流`
3. `用B电脑上OBS推流 rtmp://your-server/live/stream1`
4) 播放 http://your-server/live/stream1.m3u8

**播放的视频只有声音没有图像**
如果使用VLC可以播放  rtmp://your-server/live/stream1
测试过 SRS2.0 SRS4.0 没有问题。

**Comment by winlinvip** [comment]
Upgrade to 4.0?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS 4
