### ISSUE TITLE
监控支持云台控制，焦距缩放

### ISSUE THREAD

**Issue by ly616187030** [ossrs/srs#2437]
**SRS是否支持云台控制，焦距缩放**

> SRS是否支持云台控制，焦距缩放

1. SRS版本(Version): `4.0.126`

**期望行为(Expect)**

> 支持 Onvif 协议，支持云台控制，焦距缩放

**Comment by duiniuluantanqin** [comment]
Making SRS support the ONVIF protocol seems a bit far-fetched. Wouldn't it be simpler and more reliable to use our own signaling system?

`TRANS_BY_GPT3`
