### ISSUE TITLE
当存在rtmp重复推流时，rtc播放失败。

### ISSUE THREAD

**Issue by xiaofeilong** [ossrs/srs#2442]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): SRS Version=4.0.126
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
listen              1935;
max_connections     100;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_RTCWiki#config-candidate
    candidate 192.168.71.35; #本机IP
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    http_hooks {
        enabled on;
    }
}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

一、使用ffmpeg推流：
ffmpeg -re -i ~/Downloads/test.mp4 -c copy -f flv rtmp://127.0.0.1/live/livestream
二、使用http://127.0.0.1:8080/中SRS播放器播放。播放正常。

三、再使用ffmpeg推流，和第一步中一样。使用http://127.0.0.1:8080/中SRS播放器播放失败，并且ffplay播放RTMP流失败

**期望行为(Expect)**

> 期望将第二个重复流禁推，但是不影响第一次推流的播放。

查看代码，发现问题的原因是由于在第一个推流时，已经将RTMP转RTC的bridger_的SrsRtcSource中is_created_ = true;所以会返回RTC的推流已经存在。错误码并不是RTMP重复推流的错误码ERROR_SYSTEM_STREAM_BUSY。

尝试解决：将acquire_publish中判断RTC推流重复和RTMP推流重复调换位置。自测可以实现正常播放流程，不知道会不会有其他的问题。如下：
```
srs_error_t SrsRtmpConn::acquire_publish(SrsLiveSource* source)
{
    srs_error_t err = srs_success;
    
    SrsRequest* req = info->req;
	
    // @see https://github.com/ossrs/srs/issues/2364
    // Check whether GB28181 stream is busy.
#if defined(SRS_GB28181)
    if (_srs_gb28181 != NULL) {
        SrsGb28181RtmpMuxer* gb28181 = _srs_gb28181->fetch_rtmpmuxer(req->stream);
        if (gb28181 != NULL) {
            return srs_error_new(ERROR_SYSTEM_STREAM_BUSY, "gb28181 stream %s busy", req->get_stream_url().c_str());
        }
    }
#endif

    // Check whether RTMP stream is busy.
    if (!source->can_publish(info->edge)) {
        return srs_error_new(ERROR_SYSTEM_STREAM_BUSY, "rtmp: stream %s is busy", req->get_stream_url().c_str());
    }

    // Check whether RTC stream is busy.
#ifdef SRS_RTC
    SrsRtcSource *rtc = NULL;
    bool rtc_server_enabled = _srs_config->get_rtc_server_enabled();
    bool rtc_enabled = _srs_config->get_rtc_enabled(req->vhost);
    if (rtc_server_enabled && rtc_enabled && !info->edge) {
        if ((err = _srs_rtc_sources->fetch_or_create(req, &rtc)) != srs_success) {
            return srs_error_wrap(err, "create source");
        }

        if (!rtc->can_publish()) {
            return srs_error_new(ERROR_RTC_SOURCE_BUSY, "rtc stream %s busy", req->get_stream_url().c_str());
        }
    }
#endif

    // Bridge to RTC streaming.
#if defined(SRS_RTC) && defined(SRS_FFMPEG_FIT)
    if (rtc) {
        SrsRtcFromRtmpBridger *bridger = new SrsRtcFromRtmpBridger(rtc);
        if ((err = bridger->initialize(req)) != srs_success) {
            srs_freep(bridger);
            return srs_error_wrap(err, "bridger init");
        }

        source->set_bridger(bridger);
    }
#endif

    // Start publisher now.
    if (info->edge) {
        return source->on_edge_start_publish();
    } else {
        return source->on_publish();
    }
}
```

**Comment by duiniuluantanqin** [comment]
> 1. Use ffmpeg for streaming:
ffmpeg -re -i ~/Downloads/test.mp4 -c copy -f flv rtmp://127.0.0.1/live/livestream
> 2. Use the SRS player at http://127.0.0.1:8080/ for playback. Playback is normal.
>
> 3. Use ffmpeg to stream again, same as in the first step. Playback fails using the SRS player at http://127.0.0.1:8080/, and playing the RTMP stream with ffplay also fails.
> 


> The description of the reproduction steps is a bit ambiguous (similar to my level, haha). I verified it repeatedly in the morning and finally figured it out. I almost missed a good issue.

> Let me add some information:
**Issue**: When repeatedly pushing RTMP streams, the second stream affects the normal playback of the first stream.
**Cause**: In the `acquire_publish` function, the RTC logic comes first, and the return value is `ERROR_RTC_SOURCE_BUSY`, which is not the error code for repeated RTMP streaming (`ERROR_SYSTEM_STREAM_BUSY`), causing the first stream to be released.
**Solution**: Following your proposed solution, I verified all four scenarios of repeated streaming combinations: `RTC streaming` and `RTMP streaming`, and all of them worked correctly.

`TRANS_BY_GPT3`

**Comment by xiaofeilong** [comment]
Please describe it more clearly next time.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Create a pull request.

`TRANS_BY_GPT3`

**Comment by xiaofeilong** [comment]
> Submit a pull request, please.

https://github.com/ossrs/srs/pull/2448
> Submitted.

`TRANS_BY_GPT3`
