### ISSUE TITLE
编译安装srs-4.0.136版本使用参数--with-gb28181报错

### ISSUE THREAD

**Issue by ShouHuJiYi** [ossrs/srs#2445]
编译安装`srs-4.0.136`使用参数`--with-gb28181`报错

>编译安装`srs-4.0.136`使用参数`--with-gb28181`报错，但是在编译安装`srs-4.0.123`版本时可以成功

1. SRS版本(Version): `srs-4.0.136`
2. SRS输出错误：
 ./configure: error: invalid option "-with-gb28181"

**Comment by duiniuluantanqin** [comment]
28181功能已经移到`feature/gb28181`分支
