### ISSUE TITLE
使用 webRTC推送，录制的视频，最下方有一条绿色条纹

### ISSUE THREAD

**Issue by allanhzhz** [ossrs/srs#2453]
**描述(Description)**

使用 webRTC推送，录制的视频，最下方有一条绿色条纹，使用RTMP推送，录制的视频是正常的。
1. SRS版本(Version): `4.0.123`

2. SRS的配置如下(Config):
```
[root@master conf]# vi srs.conf 

# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        file;
ff_log_level        warning;
srs_log_file        ./logs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8081;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
rtc_server {
    enabled         on;
    listen          8000;
    #candidate       $CANDIDATE;
    candidate       192.168.2.7;
}
vhost __defaultVhost__ {
    tcp_nodelay     on
    min_latency     on;
    play {
        atc             on;
        atc_auto        on;
        mix_correct     on;
    }
    publish {
        mr off;
    }
    # 开启 flv 播放
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        rtc_to_rtmp on;
        bframe      discard;
    }
    dvr {
        enabled      on;
        #dvr_path     /home/zyjc/mp4/[stream]/[timestamp].mp4;
        dvr_path     /home/zyjc/flv/[stream]/[timestamp].flv;
        dvr_plan     session;
    }
  
}
```
**期望行为(Expect)**
没有绿色条纹
<img width="437" alt="微信图片_20210630175801" src="https://user-images.githubusercontent.com/75822150/123941682-f4e2eb80-d9cc-11eb-8e06-a4e4f7e25a50.png">

**Comment by xiaozhihong** [comment]
I tried it, but couldn't reproduce it. Is the stream you recommended from the camera? Does playing the flv directly result in green stripes?

`TRANS_BY_GPT3`

**Comment by allanhzhz** [comment]
The recorded flv file has stripes, while the live video does not. Therefore, there is a problem with the recorded flv file.

`TRANS_BY_GPT3`

**Comment by xiaozhihong** [comment]
> There are stripes when playing the recorded flv file, but there are no stripes in the live video. So the recorded flv file has a problem.

> Yes, what I mean is whether it happens with any file or only with a specific file.

`TRANS_BY_GPT3`

**Comment by allanhzhz** [comment]
> > The recorded flv file has stripes, while the live video does not. Therefore, there is a problem with the recorded flv file.
> 
> Yes, what I mean is whether it happens to any file or only to a specific file.

> Here, it happens to any file (even if it is converted to mp4 format), not specific special files.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
I also tested it, but couldn't reproduce it.
What browser are you using for streaming? Try playing it with VLC and check the debug log.
Please also upload your recording file to have a look.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Definitely not an SRS problem.

`TRANS_BY_GPT3`
