### ISSUE TITLE
FFmpeg: 交叉编译以后，推流失败，FFmpeg找不到libopus

### ISSUE THREAD

**Issue by qichaoshen82** [ossrs/srs#2454]
交叉编译以后，正常推流失败

1. SRS版本(Version):Release 4.0.138
e802fe5

1. SRS的日志如下(Log):
2021-07-01 11:18:01.802][Error][29236][9gys96q8][11] serve error code=5011 : service cycle : rtmp: stream service : bridger init : init codec : enc init codec:13, channels:2, samplerate:48000, bitrate:48000 : Codec not found by name(13,libopus)

重现Bug的步骤:
在x86服务器上使用交叉编译
编译
./configure  --cross-build --nasm=off --cc=aarch64-himix100-linux-gcc --cxx=aarch64-himix100-linux-g++ --ar=aarch64-himix100-linux-ar --ld=aarch64-himix100-linux-ld --randlib=aarch64-himix100-linux-ranlib
make && make install

推流
ffmpeg -re -i demo.flv -c copy -f flv rtmp://127.0.0.1/live/livestream

**Comment by qichaoshen82** [comment]
root cause:
Because in the case of cross-compilation, libopus was not compiled, so the built-in opus encoder of ffmpeg was used directly. The name of the built-in encoder in ffmpeg is opus, which causes the encoder to fail to open.

```
In srs_app_rtc_codec.cpp
//
// Copyright (c) 2013-2021 Bepartofyou
//
// SPDX-License-Identifier: MIT
//

#include <srs_app_rtc_codec.hpp>

#include <srs_kernel_codec.hpp>
#include <srs_kernel_error.hpp>
#include <srs_kernel_log.hpp>

static const char* id2codec_name(SrsAudioCodecId id)
{
    switch (id) {
    case SrsAudioCodecIdAAC:
        return "aac";
    case SrsAudioCodecIdOpus:
        return "libopus";
    default:
        return "";
    }
}
```

If you must use the built-in opus in ffmpeg, you can change "libopus" to "opus" here. 
Also, because opus is currently an experimental codec in ffmpeg, you need to make certain modifications in the function "srs_error_t SrsAudioTranscoder::init_enc(SrsAudioCodecId dst_codec, int dst_channels, int dst_samplerate, int dst_bit_rate)".

```
    if (dst_codec == SrsAudioCodecIdOpus) {
        //TODO: for more level setting
        enc_->compression_level = 1;
        enc_->strict_std_compliance = FF_COMPLIANCE_EXPERIMENTAL;
    } else if (dst_codec == SrsAudioCodecIdAAC) {
        enc_->strict_std_compliance = FF_COMPLIANCE_EXPERIMENTAL;
    }
```

This issue is related to the problem mentioned below.
https://github.com/ossrs/srs/issues/2431

This problem can also be solved by modifying the compilation script to enable cross-compilation and compile and link libopus as well.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍
