### ISSUE TITLE
SRT: 推流到srs服务器，使用VLC拉去m3u8流，出现卡顿，停顿现象

### ISSUE THREAD

**Issue by HeZhiWei00** [ossrs/srs#2460]
**描述(Description)**

使用obs推流SRT到srs服务器，使用VLC拉去m3u8流，出现卡顿，停顿现象

1. SRS版本(Version): `SRS/4.0.136`
1. SRS的日志如下(Log):
```
[2021-07-05 16:59:56.716][Error][7969][js991y91][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [7969][js991y91]: process_requests() [src/app/srs_app_http_conn.cpp:183][errno=62]
thread [7969][js991y91]: parse_message() [src/protocol/srs_service_http_conn.cpp:98][errno=62]
thread [7969][js991y91]: parse_message_imp() [src/protocol/srs_service_http_conn.cpp:161][errno=62]
thread [7969][js991y91]: grow() [src/protocol/srs_protocol_stream.cpp:162][errno=62]
thread [7969][js991y91]: read() [src/protocol/srs_service_st.cpp:500][errno=62](Timer expired)
```
1. SRS的配置如下(Config):
```
# the config for srs to remux rtmp to flv live stream.
# @see https://github.com/ossrs/srs/wiki/v2_CN_DeliveryHttpStream
# @see full.conf for detail config.

listen              9991;
max_connections     1000;
daemon              off;

http_server {
    enabled         on;
    listen          9992;
    dir             ./objs/nginx/html;

    https {
        enabled     off;
        listen      9993;
        key         ./conf/server.key;
        cert        ./conf/server.cert;
    }
}

http_api {
    enabled         on;
    listen          9994;
    crossdomain     on;
}

srt_server {
    enabled         on;
    listen          9995;
    #最大发送带宽 -1表示1Gbps 0表示由SRTO_INPUTBW的计算决定(不推荐在直播模式下设置为0) >0带宽为bytes/s
    maxbw           -1;
    #srt连接超时时间
    connect_timeout 4000;
    #缓存时间长度 单位ms
    latency         500;
    #音视频同步
    mix_correct     on;
    #too-late packet drop 超过lantency后接收的包将丢弃
    tlpkdrop        true;
    #单个发送报文最大的size
    mss             1500;
    #srt 发送缓存
    #sendbuf         8192 * (1500 - 28)
    #srt 接收缓存
    #recvbuf         8192 * (1500 - 28)
    #负载大小 1316 = 188 * 7 设置了有问题
    #payloadsize     1316
}

vhost __defaultVhost__ {

    #低延时
    tcp_nodelay     on;
    #低延时
    min_latency    on;

    play {
        #低延时
        gop_cache       off;
        #低延时
        queue_length    10;
        #低延时
        mw_latency      100;
        time_jitter     off;
    }

    publish {
        #低延时
        mr off;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    http_hooks {
        enabled         off;
        on_connect      http://localhost:8085/api/v1/clients;
        on_close        http://localhost:8085/api/v1/clients;
        on_publish      http://localhost:8085/api/v1/streams;
        on_unpublish    http://localhost:8085/api/v1/streams;
        on_play         http://localhost:8085/api/v1/sessions;
        on_stop         http://localhost:8085/api/v1/sessions;
        on_dvr          http://localhost:8085/api/v1/dvrs;
        on_hls          http://localhost:8085/api/v1/hls;
        on_hls_notify   http://localhost:8085/api/v1/hls/[app]/[stream]/[ts_url][param];
    }

    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        #分段长度 单位秒
        hls_fragment    10;
        #hls窗口大小，也就是m3u8里面的个数，单位秒
        hls_window      120; 
    }

}

```

**重现(Replay)**

1. `使用obs推送SRT流到srs服务器`
2. `用VLC拉去相应的M3U8流`

**期望行为(Expect)**

能顺畅播放m3u8流

**Comment by HeZhiWei00** [comment]
其中rtmp拉流正常' translates to 'The rtmp streaming is normal.

`TRANS_BY_GPT3`

**Comment by HeZhiWei00** [comment]
Supplement: When playing HLS segmented videos directly, it was found that the video dropped frames.
![image](https://user-images.githubusercontent.com/30924757/124452705-343c7e00-ddb9-11eb-9b3d-bbe718a803b2.png)

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
> The rtmp pull stream is normal

> @HeZhiWei00 Hello, is this bug still present?
I tried to reproduce it myself but couldn't, I'm using nginx as the http server for hls.

> Configuration (I partially copied yours):
# SRT config.

listen              1935;
max_connections     1000;
daemon              on;
srs_log_tank        file;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

srt_server {
    enabled         on;
    listen          10080;
    maxbw           -1;
    connect_timeout 4000;
    latency         500;
    mix_correct     on;
    tlpkdrop        true;
    mss             1500;
}

# @doc https://github.com/ossrs/srs/issues/1147#issuecomment-577607026
vhost __defaultVhost__ {
    tcp_nodelay     on;
    min_latency    on;

    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
        time_jitter     off;
    }

    publish {
        mr off;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    hls {
        enabled         on;
        hls_path        /usr/share/nginx/html;
        hls_fragment    10;
        hls_window      120;
    }
}

# For SRT to use vhost.
vhost srs.srt.com.cn {
}

stats {
    network         0;
    disk            sda sdb xvda xvdb;
}

`TRANS_BY_GPT3`

**Comment by HeZhiWei00** [comment]
@runner365 Hello, it's been a while since I last tried it. I will try again next week and get back to you. Currently, I am directly pushing RTMP to the SRS server.

`TRANS_BY_GPT3`

**Comment by runner365** [comment]
> @runner365 Hello, it's been a long time since I last tried it. I will try again next week and get back to you. Currently, I am directly pushing RTMP to the SRS server.

Okay, if there's any news, contact me. WeChat: sweibd

`TRANS_BY_GPT3`

**Comment by HeZhiWei00** [comment]
Later, after a period of testing, it was discovered that the reason for the lag may be due to network fluctuations causing VLC to fail to fetch video files, resulting in VLC increasing the cache length and re-caching the video. 
![Image](https://user-images.githubusercontent.com/30924757/138388077-78939c33-357c-41ff-b40c-fab34ec4b372.png)
This is considered a normal phenomenon.

`TRANS_BY_GPT3`
