### ISSUE TITLE
关于 nginx 的问题

### ISSUE THREAD

**Issue by pxdy** [ossrs/srs#2462]
**描述(Description)**

> 现在集成的 nginx 版本为 1.5.7，而最新稳定版本已经是 1.20.x ，中间已经发现并修复许多bug及安全漏洞。

> 在开启http服务情况下，srs也许会受到一些bug及安全漏洞影响，http://nginx.org/en/CHANGES-1.20

**期望行为(Expect)**

> 1.srs 编译时否可以完全剥离 nginx 依赖
> 2.由外部 nginx 提供 http 服务时，srs 能否按照 ffmpeg 方式进行调用

**Comment by winlinvip** [comment]
3.0开始就没集成Nginx了。
