### ISSUE TITLE
Using the srs-4.0release.zip version, execute bash scripts/build.sh to complete, then execute bash scripts/run.sh and encounter an error.

### ISSUE THREAD

**Issue by adkada** [ossrs/srs#2469]
**Using the srs-4.0release.zip version, first execute bash scripts/build.sh to complete, then execute bash scripts/run.sh and encounter an error.**

**> Please describe the issue you encountered.**

**1. SRS version: `srs-4.0release.zip`**
1. The log for SRS is as follows:
```
tail -f ffmpeg-ingest-demo.srs.com-live-livestream.log
process binary=./objs/ffmpeg/bin/ffmpeg, cli: ./objs/ffmpeg/bin/ffmpeg -loglevel info -re -i ./doc/source.200kbps.768x320.flv -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=demo.srs.com/livestream 1 > ./objs/ffmpeg-ingest-demo.srs.com-live-livestream.log 2 > ./objs/ffmpeg-ingest-demo.srs.com-live-livestream.log
process actual cli: ./objs/ffmpeg/bin/ffmpeg -loglevel info -re -i ./doc/source.200kbps.768x320.flv -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=demo.srs.com/livestream
fork process failed, errno=2(No such file or directory)
process ppid=27049, cid=976ta87t, pid=27751, in=0, out=1, err=2

```
**1. SRS configuration is as follows:**
```
**No configuration files have been modified.**
```

**Replay**

**How to replay bug?**

> Steps to reproduce the bug

**Steps to reproduce the bug:**

1. Execute `bash scripts/build.sh` first.
2. Then execute `bash scripts/run.sh` and encounter an error.
3. It seems that ffmpeg was not generated.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
build.sh and run.sh will be removed

`TRANS_BY_GPT3`
