### ISSUE TITLE
Achieving the smallest lag between an RTMP stream and a live video in a browser

### ISSUE THREAD

**Issue by madhead** [ossrs/srs#2476]
Not really an issue, but a question…

I've successfully ran an SRS v4.0.123 on an AWS EC2 t3.micro instance and it works really great, thanks!

Here is my whole configuration file:

```
listen 1935;
max_connections 10;
srs_log_tank console;
daemon off;
utc_time on;

http_api {
    enabled on;
    listen 1985;
}

http_server {
    enabled on;
    listen 8080;
}

vhost __defaultVhost__ {
    min_latency on;
    tcp_nodelay on;

    play {
        gop_cache off;
        queue_length 10;
        mw_latency 100;
    }

    publish {
        mr off;
    }

    hls {
        enabled off;
    }

    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }

    rtc {
        enabled on;
        bframe discard;
    }
}

rtc_server {
    enabled on;
    listen 8000;
    candidate $CANDIDATE;
}
```

I stream a video from an action camera via RTMP (`rtmp://${IP}/live/livestream`). The streaming app says the stream is 2500 kb/s.

I play the live stream in a web app by it's flv URL (`http://${IP}:8080/live/livestream.flv`).

The ping to the AWS region my instance is located in is, according to https://cloudping.info, 51 ms

This whole setup gives me a lag of about 3-5 seconds between the real world and the video in the browser.

The question is: what configuration parts could be tuned to minimize the lag? I want it to be as close to the ping as possible. Quality is not a priority, so I'm ok to sacrifice it.

Thanks!

**Comment by ravieze** [comment]
If you are using OBS studio then u need to tune the OBS to avoid source level lags.

**Comment by madhead** [comment]
I stream from GoPro Hero 8

**Comment by winlinvip** [comment]
Use WebRTC to get <1s lag.
