### ISSUE TITLE
srs录制视频崩溃，raw接口调用崩溃

### ISSUE THREAD

**Issue by taojishou** [ossrs/srs#2481]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `XCORE-SRS/5.0.5(Leo)`

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `raw控制录像如果请求的vhost不存在srs会崩溃`
1. `正常录像也会出现崩溃`
srs: src/kernel/srs_kernel_mp4.cpp:3288: virtual SrsCplxError* SrsMp4BaseDescriptor::encode(SrsBuffer*): Assertion `vlen > 0' failed.

**Comment by duiniuluantanqin** [comment]
https://github.com/ossrs/srs/issues/2015
Is this the same problem as this one?

`http://192.168.0.248:1985/api/v1/raw?rpc=update&scope=dvr&value=__defaultVhost__&param=enable&data=live/livestream`
Are you using this interface?

`TRANS_BY_GPT3`

**Comment by taojishou** [comment]
Question 1 is a problem. If the value is incorrect, it will cause a crash. The second problem is caused by some mp4 moov.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> Question 1 is a problem. If the value is incorrect, it can cause a crash. The second one is caused by some mp4 moov.

> Question 1: The crash caused by incorrect value has been resolved. Please refer to https://github.com/ossrs/srs/pull/2435. The pull request has been merged. Try pulling the latest code.
> 
> Question 2: Could you please provide a detailed description of the steps to reproduce the issue?

`TRANS_BY_GPT3`

**Comment by taojishou** [comment]
Question 2: When pushing the stream and then disconnecting multiple times, a coredump will be displayed.

`TRANS_BY_GPT3`

**Comment by taojishou** [comment]
![image](https://user-images.githubusercontent.com/20332592/127255681-62a9b551-de4d-4574-98df-2077dac15f40.png)

**Comment by taojishou** [comment]
![image](https://user-images.githubusercontent.com/20332592/127255706-50c0001d-60f1-40da-a242-b04fc32f37a2.png)

**Comment by duiniuluantanqin** [comment]
How did you operate it? How high is the reproduction frequency there? I tried several times but it didn't appear. Please provide a detailed description of the operation steps.

`TRANS_BY_GPT3`

**Comment by taojishou** [comment]
Frequently disconnecting and pushing again, the recurrence frequency is still relatively high.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> Frequent disconnection and re-push, the reproduction frequency is still relatively high.

> What is the audio and video encoding format you are pushing?

> I found that if I push audio in g.711 format, it will report this error. I will fix it later.

`TRANS_BY_GPT3`

**Comment by taojishou** [comment]
h264+aac

**Comment by duiniuluantanqin** [comment]
I wrote a test program, pushing-stream-disconnecting-pushing-stream-disconnecting, repeated 10,000 times, but failed to reproduce it successfully. I paused my attention, let's talk about it again when you find a stable way to reproduce it.

`TRANS_BY_GPT3`
