### ISSUE TITLE
通过HTTP API接口 http://XX:1985/api/v1/clients 获取客户播放数目不准确

### ISSUE THREAD

**Issue by hexing126mail** [ossrs/srs#2496]
**描述(Description)**
通过HTTP API接口 http://XX:1985/api/v1/clients 获取客户播放数目不准确
> 描述你遇到了什么问题(Please description your issue here)
当客户用HTTP-FLV或者RTMP播放时，通过该接口：http://XX:1985/api/v1/clients 
能准确获取该视频流的播放数量；
但是当用户用WebRtc方式播放该视频流时，通过该接口：http://XX:1985/api/v1/clients 
获取的播放数量不准确，应该是没有统计WebRtc的播放数目。

1. SRS版本(Version): `srs-v4.0.117`
1. SRS的日志如下(Log):

1. SRS的配置如下(Config):
配置文件：push.gb28181.conf

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 用WebRtc方式播放一路实时流
2..用http://XX:1985/api/v1/clients 接口获取播放数量

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
当用户用WebRtc方式播放该视频流时，通过该接口：http://XX:1985/api/v1/clients 
获取的播放数量准确

**Comment by duiniuluantanqin** [comment]
Try using the latest version of dev, this commit should have already resolved it.
https://github.com/ossrs/srs/commit/86c67f7d9522ab592c6f99c3f5f88e934a649cd1

`TRANS_BY_GPT3`
