### ISSUE TITLE
使用WEBRTC拉流后，client计数器无法增加

### ISSUE THREAD

**Issue by CNWenwuGong** [ossrs/srs#2497]
**描述(Description)**

>当我使用WEBRTC拉取视频流时，查询API中连接该stream的客户端数，一直为1

1. SRS版本(Version): `4.0`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
daemon              on;
srs_log_tank        console;
srs_log_file        ./objs/srs.log;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_RTCWiki#config-candidate
    candidate 172.16.31.10;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    #http_remux {
     #   enabled     on;
     #   mount       [vhost]/[app]/[stream].flv;
    #}
    http_hooks {
	enabled         on;
        on_stop    http://172.16.31.96:9040/webapi/video/stopVideo;
    }

 #最小延迟打开，默认是打开的，该选项打开的时候，mr默认关闭。
    min_latency     on;
    #Merged-Read，针对RTMP协议，为了提高性能，SRS对于上行的read使用merged-read，即SRS在读写时一次读取N毫秒的数据
    mr {
        enabled     off;
        #默认350ms，范围[300-2000]
        #latency     350;
    }
    #Merged-Write,SRS永远使用Merged-Write，即一次发送N毫秒的包给客户端。这个算法可以将RTMP下行的效率提升5倍左右,范围[350-1800]
    mw_latency      100;
    #enabled         on;
    #https://github.com/simple-rtmp-server/srs/wiki/v2_CN_LowLatency#gop-cache
    gop_cache       off;
    #配置直播队列的长度，服务器会将数据放在直播队列中，如果超过这个长度就清空到最后一个I帧
    #https://github.com/simple-rtmp-server/srs/wiki/v2_CN_LowLatency#%E7%B4%AF%E7%A7%AF%E5%BB%B6%E8%BF%9F
    queue_length    10;
    #http_flv配置
    http_remux {
        enabled     on;
        mount [vhost]/[app]/[stream].flv;
        hstrs   on;
    }

    tcp_nodelay     on
    min_latency     on;

    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr off;
    }
}

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 使用FFmpeg推流到SRS
2. 在SRS player页面进行播放
3. 在SRS console中查看，或者使用API查询连接数

希望尽快解决一下，跪求大神

**Comment by duiniuluantanqin** [comment]
Try using the latest version of dev, this commit should have already resolved it.
https://github.com/ossrs/srs/commit/86c67f7d9522ab592c6f99c3f5f88e934a649cd1

`TRANS_BY_GPT3`

**Comment by LUOQING1994** [comment]
> Try using the latest version of dev, this commit should have already resolved it.
> [86c67f7](https://github.com/ossrs/srs/commit/86c67f7d9522ab592c6f99c3f5f88e934a649cd1)

Hello! I have used the version you mentioned, and the client count is working fine now, but there are still some issues:
1. When stopping the stream, it takes more than 10 seconds for the client count to update.
2. The http_hooks callback function is still not being called.
3. The callback function is also not being called when streaming in flv format.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
1. Have you confirmed that it has stopped? Use the Chrome browser and enter [chrome://webrtc-internals] to check if the status is already closed. Alternatively, try refreshing the browser.

2.3. The http_hook has not been done yet, let's discuss it next week.

`TRANS_BY_GPT3`

**Comment by LUOQING1994** [comment]
> 1. Have you confirmed that it has stopped? Use the Chrome browser, enter [chrome://webrtc-internals], and see if the status is already closed? Or try refreshing the browser?
> 
> 2.3. The http_hook has not been done yet, let's discuss it next week.

I confirm that it has been closed, below are the screenshots:
![QQ截图20210804135938](https://user-images.githubusercontent.com/20340633/128129841-bd6f8187-353a-4eda-a560-33d2af2e618f.jpg)
This is a screenshot after stopping the stream:
![QQ截图20210804140002](https://user-images.githubusercontent.com/20340633/128129856-7c8fb260-22bf-4861-981f-4fef466b9106.jpg)

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
![image](https://user-images.githubusercontent.com/4254164/128132306-03cf0447-f6fe-4946-9233-e09fa91e010d.png)

Check if there is a close in the Event.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
If there is no reply for a long time, let's assume it has been resolved. If not, you can reopen it.

`TRANS_BY_GPT3`
