### ISSUE TITLE
SRS HTTP回调不支持WEBRTC拉流

### ISSUE THREAD

**Issue by CNWenwuGong** [ossrs/srs#2498]
**描述(Description)**

> SRS HTTP回调不支持WEBRTC拉流

1. SRS版本(Version): `4.0`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
listen              1935;
max_connections     1000;
daemon              on;
srs_log_tank        console;
srs_log_file        ./objs/srs.log;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_RTCWiki#config-candidate
    candidate 172.16.31.10;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    #http_remux {
     #   enabled     on;
     #   mount       [vhost]/[app]/[stream].flv;
    #}
    http_hooks {
	enabled         on;
        on_stop    http://172.16.31.96:9040/webapi/video/stopVideo;
    }

 #最小延迟打开，默认是打开的，该选项打开的时候，mr默认关闭。
    min_latency     on;
    #Merged-Read，针对RTMP协议，为了提高性能，SRS对于上行的read使用merged-read，即SRS在读写时一次读取N毫秒的数据
    mr {
        enabled     off;
        #默认350ms，范围[300-2000]
        #latency     350;
    }
    #Merged-Write,SRS永远使用Merged-Write，即一次发送N毫秒的包给客户端。这个算法可以将RTMP下行的效率提升5倍左右,范围[350-1800]
    mw_latency      100;
    #enabled         on;
    #https://github.com/simple-rtmp-server/srs/wiki/v2_CN_LowLatency#gop-cache
    gop_cache       off;
    #配置直播队列的长度，服务器会将数据放在直播队列中，如果超过这个长度就清空到最后一个I帧
    #https://github.com/simple-rtmp-server/srs/wiki/v2_CN_LowLatency#%E7%B4%AF%E7%A7%AF%E5%BB%B6%E8%BF%9F
    queue_length    10;
    #http_flv配置
    http_remux {
        enabled     on;
        mount [vhost]/[app]/[stream].flv;
        hstrs   on;
    }

    tcp_nodelay     on
    min_latency     on;

    play {
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr off;
    }


}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `启动SRS`
2. `使用FFmpeg命令向SRS推流`
3. `在SRS player中RTC播放，然后关闭浏览器或刷新页面`

**期望行为(Expect)**

> 希望在停止视频拉流时调用设置好的HTTP回调

**Comment by duiniuluantanqin** [comment]
Not supported for now, will add it this week if I find time.

`TRANS_BY_GPT3`

**Comment by RossWang** [comment]
@duiniuluantanqin 

Can the client IP obtained in the WebRTC API and the client IP in the HTTP callback be used with X-Forward-For or even custom header data? This would make it more convenient to operate under a reverse proxy.

It seems that srs_get_original_ip() is already being used elsewhere.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
https://github.com/ossrs/srs/pull/2509

**Comment by duiniuluantanqin** [comment]
> @duiniuluantanqin
> 
> Can WebRTC use X-Forward-For or even custom header information to obtain the client IP in the API and HTTP callback?
> This would make it more convenient to operate under a reverse proxy.
> 
> Currently, it seems that srs_get_original_ip() is already being used elsewhere.

> Worth considering.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
https://github.com/ossrs/srs/pull/2514

**Comment by bangde2021** [comment]
dvr 好像也不支持' translates to 'It seems that the DVR also does not support.

`
dvr {
    enabled on;
    dvr_path ./objs/nginx/html/live/[stream]-[timestamp].flv;
    dvr_plan session;
    dvr_apply live/xxx;
    dvr_wait_keyframe on;
}

`

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
> dvr seems to be unsupported
> 
> `
> dvr {
> enabled on;
> dvr_path ./objs/nginx/html/live/[stream]-[timestamp].flv;
> dvr_plan session;
> dvr_apply live/xxx;
> dvr_wait_keyframe on;
> }
> 
> `

> RTC does not support directly triggering DVR. However, you can first convert to RTMP and then DVR.

`TRANS_BY_GPT3`

**Comment by tinybright** [comment]
4.0.95 Only on_dvr can trigger
5.0.33 Only on_dvr on_publish on_unpublish can trigger

on_connect on_close has never been triggered

`TRANS_BY_GPT3`
