### ISSUE TITLE
Add server_id into hooks

### ISSUE THREAD

**Issue by matthew1838** [ossrs/srs#2520]
Actually, Not an issue.

For more sophisticated use-case about stats. I would like to suggest to add `server_id` into hook payload.

eg: on_publish hook

```json
{
    "action": "on_publish",
    "client_id": 1985,
    "ip": "192.168.1.10",
    "vhost": "video.test.com",
    "app": "live",
    "stream": "livestream",
    "param": "?token=xxx&salt=yyy",
    "server_id": "vid-qwerty"
}
```

It's make sense in my case. What do you guys think? If it's OK, I would like to make a PR ASAP.

Thank you.

**Comment by duiniuluantanqin** [comment]
what is the `server_id` used for?

**Comment by matthew1838** [comment]
In my case, I would want to limit number of HTTP request to SRS server to avoid unnecessary IO. 

We write some kind of srs-exporter and scrape it throw Prometheus. Having `server_id` would be ideal to have single exporter that can serve a lot of SRS servers.

**Comment by duiniuluantanqin** [comment]
ok, got it
