### ISSUE TITLE
G711分支在海康或大华摄像头启用mp4录像时，如果是g711音频会出错(吐核)

### ISSUE THREAD

**Issue by qqtian01** [ossrs/srs#2522]
**描述(Description)**

>海康或大华摄像头只要摄像头音频为G711时，启用录像文件类型为mp4时就会出错，文件类型为flv时正常

1. SRS版本(Version): `feature/g711`
1. SRS的日志如下(Log):
```
srs: src/kernel/srs_kernel_mp4.cpp:3288: virtual SrsCplxError* SrsMp4BaseDescriptor::encode(SrsBuffer*): Assertion `vlen > 0' failed.
已放弃(吐核)

```
1. SRS的配置如下(Config):
```
 dvr {
        enabled         on;
       dvr_path ./objs/nginx/html/[app]/[stream].[timestamp].mp4;
      }
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `只要摄像头音频为G711时，启用录像文件类型为mp4时就会出错，文件类型为flv时正常`

**Comment by Cyaim** [comment]
Translate to English: "转AAC"'

Please maintain the markdown structure.

`TRANS_BY_GPT3`

**Comment by qichaoshen82** [comment]
The mp4 format does not support audio packaging in g711, which caused the problem. In the case of an mp4 container, the g711 audio can be directly discarded.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Repaired
https://github.com/ossrs/srs/pull/2573

`TRANS_BY_GPT3`
