### ISSUE TITLE
webhook 支持webrtc推流吗？

### ISSUE THREAD

**Issue by superyhee** [ossrs/srs#2528]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
为什么通过rtc推流，webhook没有任何反应？
1. SRS版本(Version): `v4.0.150`
1. SRS的日志如下(Log):
```
xxxxxxxxxxxx
```
1. SRS的配置如下(Config):
```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**
> 描述你期望发生的事情(Please describe your expectation)
能够根据rtc推流和断流调用webhook

**Comment by duiniuluantanqin** [comment]
用最新版本，已经支持。
