### ISSUE TITLE
GB28181: 观看RTMP流地址格式与文档描述有出入

### ISSUE THREAD

**Issue by gexiaopeng** [ossrs/srs#2529]
今天安装了最新的feature/gb28181版本，对接GB28181以后，发现观看RTMP流地址为：rtmp://localhost:1935/live/34020000001320000001@34020000001320000001 ，与文档描述的rtmp://localhost:1935/live/34020000001320000001有出入

**Comment by xialixin** [comment]
The document has not been updated, I will update the document.

`TRANS_BY_GPT3`

**Comment by xialixin** [comment]
The document has been updated.

`TRANS_BY_GPT3`
