### ISSUE TITLE
rtmp推流,webrtc播放,怎么提高webrtc播放画面的清晰度呀

### ISSUE THREAD

**Issue by al00000** [ossrs/srs#2530]
**描述(Description)**

>问题:  rtmp高清推流,webrtc播放,播放的画面太模糊了,可能就标清效果吧~

1. SRS版本(Version): `v4.0+`

**重现(Replay)**
  rtmp高清推流,webrtc播放太模糊
**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
        rtmp高清推流,webrtc播放高清

**Comment by duiniuluantanqin** [comment]
没有吧，srs只是个sfu，不会做转码的。
