### ISSUE TITLE
GB28181: 使能forward后，delete_stream_channel会crash

### ISSUE THREAD

**Issue by eriklee1895** [ossrs/srs#2531]
**描述(Description)**
```
GB28181使能forward后，指定forward地址，先调用create_stream_channel API，
再调用delete_stream_channel删除通道，必现出现crash
```

1. SRS版本(Version): `v4.0`
1. SRS的日志如下(Log):
```
[2021-08-12 14:49:55.631][Trace][1801128][2548k2y3] HTTP #1 10.76.30.223:59306 GET http://10.76.47.96:1985/api/v1/gb28181/?action=delete_channel&id=34020000001320000005_34020000001320000005_1626849536080, content-length=-1
[2021-08-12 14:49:55.632][Trace][1801128][z938ej5d] gb28181: client id=34020000001320000005_34020000001320000005_1626849536080 rtmp muxer is remove
srs: src/app/srs_app_st.cpp:233: void SrsFastCoroutine::stop(): Assertion `trd_err == err_res' failed.
./run_srs_gb28181.sh: line 35: 1801128 Aborted                 (core dumped) ./objs/srs -c conf/push.gb28181.conf
```
1. SRS的配置如下(Config):
```
push.gb28181.conf中配置任意forward地址
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `conf文件配置forwad地址`
2. `调用create_stream_channel API创建通道`
3. `调用delete_stream_channel删除通道`
4. `srs必现crash`

**期望行为(Expect)**

> delete_stream_channel无异常

该问题我已定位出原因为SrsGb28181RtmpMuxer::stop()与~SrsGb28181RtmpMuxer()重复调用了close()导致source->unpublish()会同时重复进入导致forward协程退出流程崩溃

我的解决方案是删除SrsGb28181RtmpMuxer::stop()中的close()调用。
请看下这个bug是否要在主线修复哈

**Comment by duiniuluantanqin** [comment]
管他四七二十八，提个pr看一下

**Comment by lauix** [comment]
我也发现了这个 BUG，这个应该和 Forward 没有关系，invite后，再删除通道，就会 crash。
原因是：删除通道会调用SrsGb28181RtmpMuxer::stop，内部会修改线程状态和调用SrsGb28181RtmpMuxer::close，线程状态改变后 SrsGb28181RtmpMuxer::cycle 中 SrsGb28181Manger 会删除 SrsGb28181RtmpMuxer，SrsGb28181RtmpMuxer的析构函数中会再次调用 SrsGb28181RtmpMuxer::close，致使资源二次释放。


```c++
void SrsGb28181RtmpMuxer::stop()
{
    if (trd){
        trd->interrupt();
        // 更改线程状态后，直接返回，
        // 由 SrsGb28181RtmpMuxer::cycle中的 `gb28181_manger->remove(this);` 去释放 SrsGb28181RtmpMuxer。
        return;
    }
    //stop rtmp publish
    close();
}
```

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请提供最小重现路径，删除掉无关的信息，比如和Forward没关系就请不要把Forward相关的信息提上来。

该Issue会被删除，请先阅读FAQ：#2716
