### ISSUE TITLE
API: webrtc 连接、播放时，webhook回调不起作用

### ISSUE THREAD

**Issue by ly236** [ossrs/srs#2555]
**描述(Description)**

版本4.0release
1. webrtc客户端在连接、播放时，webhook回调不起作用
 
2.推流时，webhook connect\publish都是正常的

**重现(Replay)**

**期望行为(Expect)**
webrtc客户端连接、播放时，webhook进行正常回调

**Comment by duiniuluantanqin** [comment]
Currently, the WebRTC protocol supports `on_play/on_stop` for the play function and `on_publish/on_unpublish` for the publish function.

`TRANS_BY_GPT3`

**Comment by ly236** [comment]
Hello, my version is the latest version of SRS 4.0 release.
I have added vhost.http_hooks.on_connect, vhost.http_hooks.on_play, vhost.http_hooks.on_publish in srs.conf.
For non-webrtc streaming, both push and pull streams can be called back normally.
I have tried ffmpeg push stream and webrtc push stream for webrtc. There is no callback when playing webrtc.
Did I miss any configuration?

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
So you need to tell me, which one is effective? Which one is not effective?

`TRANS_BY_GPT3`

**Comment by ly236** [comment]
Well, if webrtc already supports play publish callbacks, then I suspect it might be an issue with my version or configuration. When pushing the stream using ffmpeg and playing it with flv or vlc, I receive callbacks. However, when playing with webrtc, I do not receive any callbacks.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Try using the latest version.

`TRANS_BY_GPT3`

**Comment by ly236** [comment]
Using the latest code from the 4.0 release version, callbacks are now available when playing WebRTC.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
https://github.com/ossrs/srs/pull/2509
Resolved

`TRANS_BY_GPT3`
