### ISSUE TITLE
希望log能打印行数和文件名

### ISSUE THREAD

**Issue by jinleileiking** [ossrs/srs#2557]
> 注意：不提供以下信息的Issue会被直接删除(Please follow issue template, or we will delete it)

> 注意：咨询和讨论请提交到SRS星球(Please ask question at) http://bbs.ossrs.net

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0`
1. SRS的日志如下(Log):
```
[2021-08-26 16:48:39.377][Trace][80099][slz1t894] RTMP client ip=127.0.0.1:55706, fd=13
```
1. SRS的配置如下(Config):
```
默认配置
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

看一下log

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

希望在log里能打印这句话的文件名和行数`[xxxxx.c][line111]`
```
[2021-08-26 16:48:39.377][Trace][80099][slz1t894][xxxxx.c][line111] RTMP client ip=127.0.0.1:55706, fd=13
```

**Comment by winlinvip** [comment]
Firstly, you can add the function, file, and line number in the log. Please refer to the corresponding red definition for details.

```
// Log style.
// Use __FUNCTION__ to print c method
// Use __PRETTY_FUNCTION__ to print c++ class:method
#define srs_verbose(msg, ...) _srs_log->verbose(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
#define srs_info(msg, ...)    _srs_log->info(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
#define srs_trace(msg, ...)   _srs_log->trace(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
#define srs_warn(msg, ...)    _srs_log->warn(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
#define srs_error(msg, ...)   _srs_log->error(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
```

Furthermore, currently the function is automatically added in the error log. This is because usually we only pay attention to it when there is an error.

```
[2021-08-29 07:26:33.302][Error][74069][40j1h078][2] Failed, code=1023 : check config : check normal : conf is empty
thread [74069][40j1h078]: do_main() [src/main/srs_main_server.cpp:175][errno=2]
thread [74069][40j1h078]: check_config() [src/app/srs_app_config.cpp:3576][errno=2]
thread [74069][40j1h078]: check_normal_config() [src/app/srs_app_config.cpp:3602][errno=2](No such file or directory)
```

You can refer to:

```
#define srs_error_new(ret, fmt, ...) SrsCplxError::create(__FUNCTION__, __FILE__, __LINE__, ret, fmt, ##__VA_ARGS__)
#define srs_error_wrap(err, fmt, ...) SrsCplxError::wrap(__FUNCTION__, __FILE__, __LINE__, err, fmt, ##__VA_ARGS__)
```

`TRANS_BY_GPT3`

**Comment by jinleileiking** [comment]
Can you consider making this configurable? Sometimes when logging, the same content is displayed and it's unclear which file it belongs to. @winlinvip It can be configured in srs.conf.

`TRANS_BY_GPT3`

**Comment by jinleileiking** [comment]
If you agree, I'll take care of it.

`TRANS_BY_GPT3`
