### ISSUE TITLE
[Question] - Http api handling

### ISSUE THREAD

**Issue by marwalda** [ossrs/srs#2567]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0`

I have been thinking about using SRS on my platform. But I have few questions I couldn't find an answer on. Could you please explain:

1. I have seen srs exposes the api to get streams, delete or kick a client... Where those information are stored in db or as a file or something else?

2. Imagine I have a database with information about users' streams (keys). And I would like to take 10 streams followed by given user with most viewers at the moment (hls). So using srs api I would have to check all the streams one by one by stream id executing many times http api - if user follows 1000 streams I have to check them all with get http.
I was thinking if the right way to use it - is to react on "hook" events from srs and store those data on my side on my db, but the question is if it is efficient way? Or you suggest to extend srs api editing the original code?

I would appreciate if you could help me understanding the mechanisms.

Kind regards,
Maria

**Comment by winlinvip** [comment]
I have seen srs exposes the api to get streams, delete or kick a client... Where those information are stored in db or as a file or something else?

> Winlin: No DB or file. You should write your application, which call HTTP-API and got HTTP-Callbacks, then write information to DB.

Imagine I have a database with information about users' streams (keys). And I would like to take 10 streams followed by given user with most viewers at the moment (hls). So using srs api I would have to check all the streams one by one by stream id executing many times http api - if user follows 1000 streams I have to check them all with get http.
I was thinking if the right way to use it - is to react on "hook" events from srs and store those data on my side on my db, but the question is if it is efficient way? Or you suggest to extend srs api editing the original code?

> Winlin: For security, please change the HTTP-API to listen at `127.0.0.1:1985`, then use a HTTP proxy with auth, like Nginx/Nodejs/Go.
