### ISSUE TITLE
GB28181: pc通过gb28181 推流到edge端，edge通过origin-cluster方式，把流转发到origin端出错失败

### ISSUE THREAD

**Issue by phlahut** [ossrs/srs#2569]
Migrate to https://github.com/ossrs/srs-gb28181/issues/15

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by phlahut** [comment]
After analyzing the packet capture, I found that the interaction process of RTMP is different between forwarding from the edge to the origin and forwarding from the edge to the origin.
![image](https://user-images.githubusercontent.com/21032464/132615777-0d1a23dd-0f36-450c-8f8b-3014eab2808d.png)

The process of forwarding from the edge to the origin is as follows:
![image](https://user-images.githubusercontent.com/21032464/132615858-8b1c356d-990b-4a5d-ab18-b954c2727a32.png)

According to the forwarding process, the edge should publish to the origin, and then the edge should push the streaming data to the origin. This is a reasonable logic.

I can't understand why, during the process of source forwarding, the edge requests to play the stream from the origin. Is there a problem with this logic?

`TRANS_BY_GPT3`

**Comment by phlahut** [comment]
@xialixin, when you have time, please take a look.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/15

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).'
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
