### ISSUE TITLE
DVR录制的视频进度条时长比实际开始推流和结束推流的时间差要大，而且推流越久相差越大

### ISSUE THREAD

**Issue by TTnTTT** [ossrs/srs#2585]
> 注意：不提供以下信息的Issue会被直接删除(Please follow issue template, or we will delete it)

> 注意：咨询和讨论请提交到SRS星球(Please ask question at) http://bbs.ossrs.net

**描述(Description)**

> DVR录制的视频进度条时长比实际开始推流和结束推流的时间差要大，而且推流越久相差越大

1. SRS版本(Version): `4.0`
1. SRS的日志如下(Log):
```

srs日志显示开始推流时间：
[2021-09-07 15:20:04.952][Trace][2816948][p5bnsdh3] connected stream, tcUrl=rtmp://47.12:.xx.xx9035/live, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=9035, app=live, stream=3VS001, param=, args=null
[2021-09-07 15:20:04.952][Trace][2816948][p5bnsdh3] source url=/live/3VS001, ip=127.0.0.1, cache=1, is_edge=0, source_id=/n7122xfr
[2021-09-07 15:20:05.199][Trace][2816948][p5bnsdh3] http: on_publish ok, client_id=p5bnsdh3, url=http://192.168.0....
srs日志显示结束结束时间：
[2021-09-07 15:35:50.220][Trace][2816948][p5bnsdh3] http hook on_dvr success. client_id=p5bnsdh3, url=http://192/....
时间差为：945秒=16分15秒
但播放视频时其时长为：18分01秒
如果直播越久，相差越大。
```
1. SRS的配置如下(Config):
```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

推流时间长一点即可发现

**期望行为(Expect)**

> 希望大佬能看一下这是什么原因照成的呢？

**Comment by duiniuluantanqin** [comment]
Unable to reproduce. I tested for 30 minutes, accurately to the second.

1. Are you streaming from a local file or from the network?
2. What are the audio and video encoding formats used?

`TRANS_BY_GPT3`

**Comment by TTnTTT** [comment]
Oh, sorry for the confusion. I didn't explain clearly. Just now, I tested it locally and there is indeed no time difference. This situation only occurs when using third-party drone streaming software for streaming. Thank you for reminding me to investigate in the direction of video encoding format. Currently, I don't know what encoding format they are using for the stream they upload. I'm not sure if different encoding formats will affect the duration of the video.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
The possibility of encoding format is unlikely, so let's investigate in the direction of packet loss.

`TRANS_BY_GPT3`

**Comment by TTnTTT** [comment]
Um, I have another question and I hope the expert can help me answer it. Does it refer to packet loss in video streaming? If there is packet loss in video streaming, the video should become shorter, right? But the situation I am experiencing is that the duration of the video's progress bar is longer than the start and end time of the streaming.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
It doesn't seem like an SRS issue. Check the streaming software of the drone, such as recording directly and bypassing SRS. You can also upload a video recording to have a look.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Not enough information to reproduce.

`TRANS_BY_GPT3`
