### ISSUE TITLE
gb28181的raw_api接口调用直接

### ISSUE THREAD

**Issue by gzqdust** [ossrs/srs#2607]
Migrate to https://github.com/ossrs/srs-gb28181/issues/13

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by winlinvip** [comment]
Considering whether to disable SIP and integrate with other SIP projects.

`TRANS_BY_GPT3`

**Comment by ladybirds1996** [comment]
I hope I don't have to disable SIP and can continue using it for testing purposes.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
If not disabled, there are too many bugs in the feedback.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/13

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).'
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
