### ISSUE TITLE
 ./configure到libsrtp报multiple definition of  bit_string 

### ISSUE THREAD

**Issue by yuanwb1984** [ossrs/srs#2617]
> 注意：不提供以下信息的Issue会被直接删除(Please follow issue template, or we will delete it)

> 注意：咨询和讨论请提交到SRS星球(Please ask question at) http://bbs.ossrs.net

**描述(Description)**
armhf 全志H2和arm64全志H5两张香橙派，系统armbian，升级到bullseye，gcc 10.0.1
./configure到libsrtp报multiple definition of  bit_string 
> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0release`
1. SRS的日志如下(Log):
```
gcc -DHAVE_CONFIG_H -Icrypto/include -I./include -I./crypto/include  -fPIC -Wall -pedantic -Wstrict-prototypes -O4 -fexpensive-optimizations -funroll-loops -I/mnt/sda1/srs/trunk/objs/Platform-Linux-5.10.60-GCC10.2.1-SRS4-aarch64/openssl-1.1-fit/_release/include -I./test -L.  -o crypto/test/datatypes_driver crypto/test/datatypes_driver.c test/util.c libsrtp2.a -L/mnt/sda1/srs/trunk/objs/Platform-Linux-5.10.60-GCC10.2.1-SRS4-aarch64/openssl-1.1-fit/_release/lib -lcrypto -ldl  -lsrtp2
/usr/bin/ld: libsrtp2.a(datatypes.o):(.bss+0x0): multiple definition of `bit_string'; /tmp/ccwYka0b.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:215: crypto/test/datatypes_driver] Error 1
Build libsrtp-2-fit failed, ret=2

```
1. SRS的配置如下(Config):
```
无
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

**期望行为(Expect)**
libsrtp-2-fit\crypto\math\datatypes.c
libsrtp-2-fit\test\util.c
以上两个文件中修改bit_string
static char bit_string[MAX_PRINT_STRING_LEN];
之后./configure通过
> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
Dup https://github.com/ossrs/srs/issues/1282
