### ISSUE TITLE
源站集群为啥不支持FLV？必须要用Edge？

### ISSUE THREAD

**Issue by 1187046272** [ossrs/srs#2619]
Remark: Origin cluster only supports RTMP, use Edge to transmux RTMP to FLV
对于一些To B的场景。好多是设备对网页，一对一的观看。如果直接源站集群就能发布flv. 这样会降低首开时间2-3秒。
测试发现edge回源需要耗时3秒。体验很差。
能不能支持能发布flv流的纯源站集群？
或者能不能优化回源的耗时？

**Comment by winlinvip** [comment]
自己多看文档，多调调。
