### ISSUE TITLE
ffmpeg从srs边缘节点拉流，断开后立即重新拉流ffmpeg会打开超时

### ISSUE THREAD

**Issue by wangfly80** [ossrs/srs#2621]
**描述(Description)**
ffmpeg从srs边缘节点拉流，断开后立即重新拉流ffmpeg会打开超时。如果断开后，等一段时间再拉流则可以正常打开
(组网情况：包括master节点，slave节点和edge节点，从edge节点推流和拉流)

SRS版本(Version): `4.0.130'

SRS的配置如下(Config):
边缘节点配置：
listen              19341;
max_connections     1000;
pid                 objs/e1.pid;
daemon              off;
srs_log_tank        file;
srs_log_level       trace;
srs_log_file        ./objs/logs/srs.e1.log;
srt_server {
    enabled on;
    listen 10081;
    maxbw 1000000000;
    connect_timeout 4000;
    peerlatency 300;
    recvlatency 300;
}
http_api {
    enabled         on;
    listen          19841;
    raw_api {
        enabled on;
        allow_reload on;
        allow_query on;
        allow_update on;
    }

}
http_server {
    enabled         on;
    listen          8101;
    dir             ./objs/nginx/html;
}

vhost __defaultVhost__ {
    cluster {
        mode            remote;
        origin          127.0.0.1:19351 127.0.0.1:19352;
    }
    http_hooks {
        enabled         on;
        on_publish      http://xxx.xxxx.xxx.xxx:8085/api/v1/streams;
        on_unpublish    http://xxx.xxxx.xxx.xxx:8085/api/v1/streams;
     }
     http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

master节点配置：
listen              19351;
max_connections     1000;
pid                 objs/m1.pid;
daemon              off;
srs_log_tank        file;
srs_log_level       trace;
srs_log_file        ./objs/logs/srs.m1.log;
http_api {
    enabled         on;
    listen          19851;
    raw_api {
        enabled             on;
        allow_reload        on;
        allow_update        on;
    }
}

vhost __defaultVhost__ {
    cluster {
        mode            local;
        origin_cluster  on;
        coworkers       localhost:19851 localhost:19852;
    }
    forward {
        enabled on;
        destination localhost:19361 localhost:19362;
    }
    http_hooks {
        enabled         on;
        on_publish      http://xxx.xxxx.xxx.xxx:8085/api/v1/streams;
        on_unpublish    http://xxx.xxxx.xxx.xxx:8085/api/v1/streams;
    }

}

slave节点配置(2个slave节点端口19361,19362)：
listen              19361;
max_connections     1000;
daemon              off;
srs_log_tank        file;
srs_log_level       trace;
srs_log_file        ./objs/logs/srs.s1.log;
pid                 objs/s1.pid;

http_server {
    enabled         on;
    listen          8201;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          19861;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    # Listen at udp://8100
    listen 8001;
    lbs_listen 8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_RTCWiki#config-candidate
    #candidate $CANDIDATE;
    candidate xxx,xxx,xxx.xxx;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
     hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    5;
        hls_window      40;
   }

}

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 一个终端用ffmpeg往边缘节点推流
2. 另外一个客户端用ffmpeg从边缘节点拉流
3. ffmpeg断开拉流后又立即打开拉流出现打开超时

**期望行为(Expect)**

 ffmpeg断开拉流后又立即打开拉流能打开成功

**Comment by winlinvip** [comment]
master-slave这个不是SRS定义的，你从哪个文档看的？
