### ISSUE TITLE
API: HTTP Callback 触发on_stop事件后，回传的client id与触发on_play的client id不一致,且每次都是09o0x492

### ISSUE THREAD

**Issue by fapjsc** [ossrs/srs#2626]
> 注意：不提供以下信息的Issue会被直接删除(Please follow issue template, or we will delete it)

> 注意：咨询和讨论请提交到SRS星球(Please ask question at) http://bbs.ossrs.net

**描述(Description)**
> 描述你遇到了什么问题(Please description your issue here)
1.HTTP Callback 触发on_stop事件后，回传的client id与触发on_play的client id不一致,且每次都是09o0x492
2.只有rtc有这状况,播放flv回调正常

example => 
    a.user 播放,触发on_play,回传client id 为aaaa
    b.user关闭播放,触发on_stop,回传client id 为 09o0x492
    c.user再次播放,再次触发on_play,回传client id 为bbbb
    d.user再次关闭播放,触发on_stop,回传client id 为 09o0x492

1. SRS版本(Version): `4.0.161`
1. SRS的日志如下(Log):
```
![截圖 2021-09-22 下午7 20 21](https://user-images.githubusercontent.com/74793624/134357729-aa7245a5-5adf-48c6-af39-cc8107dc3ba2.png)

```
1. SRS的配置如下(Config):
```
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 6666;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_RTCWiki#config-candidate
    candidate 192.168.10.105;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    http_hooks {
        enabled       on;
	on_connect    http://host.docker.internal:8085/api/v1/clients;
	on_close      http://host.docker.internal:8085/api/v1/clients;
        on_publish    http://host.docker.internal:8085/api/v1/streams;
	on_unpublish  http://host.docker.internal:8085/api/v1/streams;
	on_play       http://host.docker.internal:8085/api/v1/sessions;
	on_stop       http://host.docker.internal:8085/api/v1/sessions;
    }
}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `配置conf并架设call back api server`
1. `开启官方播放器,播放flv触发on_play, on_stop回调 => 正常`
1. `播放rtc触发回调,on_play的client id与on_stop client id数值不同,且on_stop回传的client id都是固定的值(09o0x492)`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
1.同一用戶触发回调on_play与on_stop的client id应该为相同值
2.example => 
    a.user 播放,触发on_play,回传client id 为aaaa
    b.user关闭播放,触发on_stop,回传client id 为aaaa
    c.user再次播放,再次触发on_play,回传client id 为bbbb
    d.user再次关闭播放,触发on_stop,回传client id 为bbbb

**Comment by fapjsc** [comment]
![Uploading 截圖 2021-09-22 下午7.20.21.png…]()

**Comment by fapjsc** [comment]
![Screenshot 2021-09-22 7:20:21 PM](https://user-images.githubusercontent.com/74793624/134361356-a5ef7733-7b8e-4bb6-8db4-72e256b5420b.png)

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
以修复 #2665
