### ISSUE TITLE
4.0release：从edge连续两次使用ffprobe拉同一rtmp流，第二次ffprobe命令僵住不返回

### ISSUE THREAD

**Issue by chenminnj** [ossrs/srs#2628]
1. SRS版本(Version): 4.0release
2. 运行环境：Ubuntu 20.04.2 LTS

打印了一些信息，
发现当第二次ffprobe命令的rtmp连接成功后，
新的协程执行完“SrsLiveSource::create_consumer”后，
原有连接的协程由于被新连接interrupt后又被唤醒，继续执行了“SrsPlayEdge::on_all_client_stop()”方法，
从而导致edge的state被置成了init状态，
我猜测这时，edge不从master节点拉流，进而导致第二次ffprobe命令由于没有收到rtmp流而僵住。
日志信息如下：
![image](https://user-images.githubusercontent.com/29446122/134449606-2b84b011-5651-42b5-acb1-4a9ba3d44b97.png)

做了些尝试修改：

1. 将SrsLiveSourceManager对象里的lock实例，在new SrsLiveSource()时传给SrsLiveSource
2. 在SrsLiveSource::on_consumer_destroy 方法里，首先加上 SrsLocker( lock );

问题得以解决，但第二次ffprobe命令的返回时间仍然需要3-4s（第一次ffprobe命令秒回）。

对srs的了解还不深入，不知这样修改是否有问题，或者是否有更好的处理方式？

**Comment by winlinvip** [comment]
After taking a look, there is only a rough reproduction method. Could you please write down the simplest steps to reproduce the issue?

`TRANS_BY_GPT3`

**Comment by chenminnj** [comment]
Steps to reproduce:
1. Set up two SRS instances, one as master and the other as edge (the conf files should be similar to the example, with IP and Port modifications).
2. Use ffmpeg to push an RTMP stream to the edge.
      ffmpeg -stream_loop -1 -re -i xx.flv -c copy -acodec aac  -f flv rtmp://xx:1935/live/1
Media file information for xx.flv is as follows:
  Metadata:
    creator         : Coded
    metadatacreator : Yet Another Metadata Injector for FLV - Version 1.9
    canSeekToEnd    : false
    videosize       : 85401543
    audiosize       : 8592688
    lastkeyframetimestamp: 390
    lastkeyframelocation: 93879313
    encoder         : Lavf58.29.100
  Duration: 00:06:31.57, start: 0.000000, bitrate: 1174 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 1024 kb/s, 29 fps, 29 tbr, 1k tbn, 58 tbc
    Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s

3. Continuously use ffprobe to pull RTMP stream from edge.
   ffprobe rtmp://xx:1935/live/1
- a. The first execution of the above ffprobe command returns normally and produces correct results.
- b. Then, quickly executing the command again causes the ffprobe command to freeze and not return.
- c. If the above ffprobe command is executed after a certain interval of time (approximately 10 seconds or more) following the first execution, the second ffprobe command also returns normally.


- I have only seen a rough reproduction method. Could you please provide the simplest steps to reproduce the issue?


`TRANS_BY_GPT3`

**Comment by wenjiegit** [comment]
> Reproduction steps: 1. Set up two SRS instances, master and edge (conf files are similar to the example, with IP Port modifications). 2. Use ffmpeg to push an rtmp stream to the edge: ffmpeg -stream_loop -1 -re -i xx.flv -c copy -acodec aac -f flv rtmp://xx:1935/live/1 The media file information for xx.flv is as follows: Metadata: creator: Coded metadatacreator: Yet Another Metadata Injector for FLV - Version 1.9 canSeekToEnd: false videosize: 85401543 audiosize: 8592688 lastkeyframetimestamp: 390 lastkeyframelocation: 93879313 encoder: Lavf58.29.100 Duration: 00:06:31.57, start: 0.000000, bitrate: 1174 kb/s Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 1024 kb/s, 29 fps, 29 tbr, 1k tbn, 58 tbc Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
> 
> 3. Continuously use ffprobe to pull rtmp stream from the edge: ffprobe rtmp://xx:1935/live/1 a. The first execution of the above ffprobe command returns normally and the result is correct. b. Then quickly execute the command again, the ffprobe command freezes and does not return. c. If the command is executed again after a certain interval of time (approximately 10 seconds or more) following the first execution of the ffprobe command, the second ffprobe command also returns normally.
> 
> > After reviewing, there is only a rough reproduction method. Could you please provide the simplest reproduction steps?

Please provide two example configuration files for SRS. Thank you.

`TRANS_BY_GPT3`

**Comment by retamia** [comment]
I have also encountered it. Our transcoding system uses ffprobe first, then ffmpeg. The transcoding speed of ffmpeg is only 0.003 times, and then it times out. Removing ffprobe solves the issue. Only pulling once, pulling the stream twice in a short period of time will cause the second stream to freeze.

`TRANS_BY_GPT3`

**Comment by chenminnj** [comment]
> ffprobe rtmp://xx:1935/live/1

Directly use edge.conf and origin.conf under trunk/conf.

> > Reproduction steps: 
1. Set up two SRS instances, master-edge (conf files are basically the same as the sample, with IP Port modifications).
2. Use ffmpeg to push an rtmp stream to the edge: 
   `ffmpeg -stream_loop -1 -re -i xx.flv -c copy -acodec aac -f flv rtmp://xx:1935/live/1`
   Media file information for xx.flv is as follows:
   Metadata:
   creator: Coded metadatacreator: Yet Another Metadata Injector for FLV - Version 1.9 canSeekToEnd: false videosize: 85401543 audiosize: 8592688 lastkeyframetimestamp: 390 lastkeyframelocation: 93879313 encoder: Lavf58.29.100
   Duration: 00:06:31.57, start: 0.000000, bitrate: 1174 kb/s
   Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 1024 kb/s, 29 fps, 29 tbr, 1k tbn, 58 tbc
   Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
> > 3. Continuously use ffprobe to pull the rtmp stream from the edge: 
   `ffprobe rtmp://xx:1935/live/1`
   a. The first execution of the above ffprobe command returns normally with correct results.
   b. Then quickly execute the command again, the ffprobe command freezes and does not return.
   c. If there is a time interval between the first execution of the ffprobe command (approximately 10 seconds or more), the second ffprobe command also returns normally.
> > > I have only provided a rough reproduction method. Could you please provide the simplest reproduction steps?
> 
> Please provide the configuration files for the two SRS instances. Thank you.

The configuration files are directly used from trunk/conf, namely edge.conf and origin.conf. Please refer to the compressed file below.
[config.zip](https://github.com/ossrs/srs/files/7624990/config.zip)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Reproduction path: https://github.com/ossrs/srs/issues/2594#issuecomment-971511802

Thank you @retamia

I closed this issue, dup to #2594

`TRANS_BY_GPT3`
