### ISSUE TITLE
4.0.163编译报_srs_hybrid未定义错误

### ISSUE THREAD

**Issue by lingfengfushui** [ossrs/srs#2631]
> 注意：不提供以下信息的Issue会被直接删除(Please follow issue template, or we will delete it)

> 注意：咨询和讨论请提交到SRS星球(Please ask question at) http://bbs.ossrs.net

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.163`
1. SRS的日志如下(Log):
srs_app_http_static.cpp文件44和49行提示_srs_hybrid未定义错误；

1. SRS的配置如下(Config):
make时报错，未到配置步骤

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 操作系统为centos6.9，阿里云ecs；
2. 从git上获取4.0.163代码；
3. ./configure成功；
4. make报_srs_hybrid未定义错误，应该是srs_app_http_static.cpp未include srs_app_hybrid.hpp文件导致_srs_hybrid无法识别；
5. 修改srs_app_http_static.cpp引入include srs_app_hybrid.hpp文件重新configure和make成功；

**期望行为(Expect)**

> 引入缺失的文件修复

**Comment by winlinvip** [comment]
Fixed
