### ISSUE TITLE
[dockerfile] 两个项目都有dockerfile，容易引起误解

### ISSUE THREAD

**Issue by jinleileiking** [ossrs/srs#2632]
`https://github.com/ossrs/srs/blob/4.0release/trunk/Dockerfile` 和 

`https://github.com/ossrs/srs-docker`

都是dockerfile， 建议清理一下，只有一个地方有

**Comment by winlinvip** [comment]
Both of these are available. The srs-docker/Dockerfile mainly focuses on the development environment and manual image building. The srs/trunk/Dockerfile is for GitHub integration and automatic deployment.

If you can understand Dockerfile, then naturally you can understand the differences between these two.

Friends who generally use SRS Docker images also do not pay attention to how this image is built or which Dockerfile is used to build it.

So it's not easy to make changes to this, and personally, I don't think it needs to be changed.

`TRANS_BY_GPT3`

**Comment by jinleileiking** [comment]
srs-docker/Dockerfile' should be changed to 'Dockerfile.dev' under the 'trunk' directory.

`TRANS_BY_GPT3`
