### ISSUE TITLE
能否修改webrtc推流的分辨率？

### ISSUE THREAD

**Issue by Y-pandaman** [ossrs/srs#2641]
**期望行为(Expect)**
使用SRS播放器进行webrtc推流时，都是选择的最小分辨率，请问在哪修改视频的分辨率？

**Comment by winlinvip** [comment]
This is the setting for the WebRTC client, take a look at srs.sdk.js.

`TRANS_BY_GPT3`

**Comment by Y-pandaman** [comment]
Saw it, thank you.

`TRANS_BY_GPT3`
