### ISSUE TITLE
srs-5.0.12 使用海康摄像头GB28181 rtmp正常播放但webrtc无法播放

### ISSUE THREAD

**Issue by kirofreedom** [ossrs/srs#2642]
> 注意：不提供以下信息的Issue会被直接删除(Please follow issue template, or we will delete it)

> 注意：咨询和讨论请提交到SRS星球(Please ask question at) http://bbs.ossrs.net

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): 5.0.12（feature/gb28181分支）
1. SRS的日志如下(Log):
[2021-09-29 18:10:36.005][Warn][128032][39r5083u][11] RTC error code=5018 : create session, dtls=1, srtp=1, eip= : create session : add player : play negotiate : no valid found h264 payload type
thread [128032][39r5083u]: do_serve_http() [src/app/srs_app_rtc_api.cpp:191][errno=11]
thread [128032][39r5083u]: create_session() [src/app/srs_app_rtc_server.cpp:480][errno=11]
thread [128032][39r5083u]: do_create_session() [src/app/srs_app_rtc_server.cpp:501][errno=11]
thread [128032][39r5083u]: add_player() [src/app/srs_app_rtc_conn.cpp:2020][errno=11]
thread [128032][39r5083u]: negotiate_play_capability() [src/app/srs_app_rtc_conn.cpp:3196][errno=11]
[2021-09-29 18:10:36.047][Trace][128032][39r5083u] TCP: before dispose resource(HttpConn)(0x22ed690), conns=4, zombies=0, ign=0, inz=0, ind=0
[2021-09-29 18:10:36.047][Warn][128032][39r5083u][104] client disconnect peer. ret=1007
[2021-09-29 18:10:36.047][Trace][128032][0py0r282] TCP: clear zombies=1 resources, conns=4, removing=0, unsubs=0
[2021-09-29 18:10:36.047][Trace][128032][39r5083u] TCP: disposing #0 resource(HttpConn)(0x22ed690), conns=4, disposing=1, zombies=0
[2021-09-29 18:10:36.787][Trace][128032][0x84e94z] gb28181: client id=34020000001320000001@34020000001320000001,  ssrc=0x8ac009, peer(192.168.2.14, 15060), rtmp muxer is alive

1. SRS的配置如下(Config):
# push gb28181 stream to SRS.

listen                  1935;
max_connections         1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
}

stats {
    network         0;
}

stream_caster {
    enabled             on;
    caster              gb28181;

    # 转发流到rtmp服务器地址与端口
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400875104
    # [stream] is VideoChannelCodecID(视频通道编码ID) for sip
    # 自动创建的道通[stream] 是‘chid[ssrc]’ [ssrc]是rtp的ssrc
    # [ssrc] rtp中的ssrc
    output              rtmp://127.0.0.1:1935/live/[stream];
    
    # 接收设备端rtp流的多路复用端口
    listen              9000;
    # 多路复用端口类型，on为tcp，off为udp
    # 默认：on
    tcp_enable            on;

    # rtp接收监听端口范围，最小值
    rtp_port_min        58200;
    # rtp接收监听端口范围，最大值
    rtp_port_max        58300;

    # 是否等待关键帧之后，再转发，
    # off:不需等待，直接转发
    # on:等第一个关键帧后，再转发
    wait_keyframe       on;
    
    # rtp包空闲等待时间，如果指定时间没有收到任何包
    # rtp监听连接自动停止，发送BYE命令
    rtp_idle_timeout    30;

    # 是否转发音频流
    # 目前只支持aac格式，所以需要设备支持aac格式
    # on:转发音频
    # off:不转发音频，只有视频
    # *注意*!!!:flv 只支持11025  22050  44100 三种
    # 如果设备端没有三种中任何一个，转发时为自动选择一种格式
    # 同时也会将adts的头封装在flv aac raw数据中
    # 这样的话播放器为自动通过adts头自动选择采样频率
    # 像ffplay, vlc都可以，但是flash是没有声音，
    # 因为flash,只支持11025 22050 44100
    audio_enable        off;

    # 是否开启rtp缓冲
    # 开启之后能有效解决rtp乱序等问题
    # tcp模式建议关闭
    jitterbuffer_enable  off;

    # 服务器主机号，可以域名或ip地址
    # 也就是设备端将媒体发送的地址，如果是服务器是内外网
    # 需要写外网地址，
    # 调用api创建stream session时返回ip地址也是host
    # $CANDIDATE 是系统环境变量，从环境变量获取地址，如果没有配置，用*
    # *代表指定stats network 的网卡号地址，如果没有配置network，默认则是第0号网卡地址
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400917594
    # host       $CANDIDATE;
    host       192.168.2.200;
    #根据收到ps rtp包自带创建rtmp媒体通道，不需要api接口创建
    #rtmp地址参数[stream] 就是通道id  格式chid[ssrc]
    auto_create_channel   off;

    sip {
        # 是否启用srs内部sip信令
        # 为on信令走srs, off 只转发ps流
        enabled on;
        
        # sip监听udp端口
        listen              5060;
        
        # SIP server ID(SIP服务器ID).
        # 设备端配置编号需要与该值一致，否则无法注册
        serial              34020000002000000001;

        # SIP server domain(SIP服务器域)
        realm               3402000000;

        # 服务端发送ack后，接收回应的超时时间，单位为秒
        # 如果指定时间没有回应，认为失败
        ack_timeout         30;

        # 设备心跳维持时间，如果指定时间内(秒）没有接收一个心跳
        # 认为设备离线
        keepalive_timeout   120;

        # 注册之后是否自动给设备端发送invite
        # on: 是  off 不是，需要通过api控制
        auto_play           on;
        # 设备将流发送的端口，是否固定
        # on 发送流到多路复用端口 如9000
        # off 自动从rtp_mix_port - rtp_max_port 之间的值中
        # 选一个可以用的端口
        invite_port_fixed     on;

        # 向设备或下级域查询设备列表的间隔，单位(秒)
        # 默认60秒
        query_catalog_interval  60;
    }
}

rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    # candidate       $CANDIDATE;
    candidate       192.168.2.200;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        bframe      discard;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 启动海康摄像头（gb28181）
2. 运行srs_gb28181.html网页
3. 选择“GB28181”,查询GB28181媒体通道
4.选择现有通道后点击“RTC播放”，然后报错，但使用VLC进行rtmp推流播放正常

**期望行为(Expect)**
能正常进行webrtc的播放

**Comment by winlinvip** [comment]
This error is very clear: `no valid found h264 payload type`.

`TRANS_BY_GPT3`

**Comment by kirofreedom** [comment]
Hmm, the backend display shows that there is a stream, and rtmp can play normally. The camera uses h264 encoding. I am currently testing with srs. I am just starting to work on audio and video, and I am still a beginner. I appreciate the help from all the experts.

`TRANS_BY_GPT3`

**Comment by qichaoshen82** [comment]
Suggest using the latest gb28181 branch code and adding the "rtmp_to_rtc on;" field in the configuration file.

If there are still issues after using the latest code and adding "rtmp_to_rtc on;", you can reopen the issue. This issue can be closed as per the suggestion.
@duiniuluantanqin @winlinvip 

`TRANS_BY_GPT3`

**Comment by tifcty1** [comment]
The latest version of GB seems to indeed have issues with RTC playback, unlike previous versions like 5.0.12. Enabling 'rtmp_to_rtc on' resolves the issue, but it is unclear whether it is a bug or not.



> It is recommended to use the latest gb28181 branch code and add the 'rtmp_to_rtc on' field in the configuration file.
> 
> If there are still issues after using the latest code and adding "rtmp_to_rtc on;", you can reopen the issue. This issue is recommended to be closed. @duiniuluantanqin @winlinvip


`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Previously, rtmp_to_rtc was enabled by default, but now it is off by default. This is not a bug.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
@kirofreedom 
https://github.com/ossrs/srs/issues/2642#issuecomment-971080217

**Comment by tifcty1** [comment]
So that's how it is, thank you 🙏

`TRANS_BY_GPT3`

**Comment by kirofreedom** [comment]
> It is recommended to use the latest gb28181 branch code and add the "rtmp_to_rtc on;" field in the configuration file.
> 
> If there are still issues after using the latest code and adding "rtmp_to_rtc on;", you can reopen the issue. This issue is suggested to be closed. @duiniuluantanqin @winlinvip

Thank you very much!! I will give it a try.

`TRANS_BY_GPT3`

**Comment by hhw3KevinHou** [comment]
rtmp_to_rtc on;

Good job, I have been working on it for more than a day. I searched through numerous online articles but couldn't find a reliable answer. Only here did I find the solution. I love you so much.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Here, https://github.com/ossrs/srs/issues/2716#webrtc-live, it explains in detail why it is set to default off. Originally, default on would be more convenient, but there were too many issues, so it had to be changed to off.

If you have any issues, please search in the official repository. The information found online is mostly copied and may not be up to date.

Then I will close this issue. Thank you all.

`TRANS_BY_GPT3`
