### ISSUE TITLE
SRS-28181分支问题，不间断拉流，时间长通道名称会变

### ISSUE THREAD

**Issue by angel-baal** [ossrs/srs#2663]
以下是配置问题
listen                  1936;
max_connections         1000;
daemon              on;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
}

stats {
    network         0;
}

stream_caster {
    enabled             on;
    caster              gb28181;    
    output              rtmp://127.0.0.1:1936/rtp/[stream];    
  
    listen              9000;   
    tcp_enable            on;  
    rtp_port_min        58200;   
    rtp_port_max        58300;
    wait_keyframe       on;    
    rtp_idle_timeout    30;
    audio_enable        off;   
    jitterbuffer_enable  off;
    host       221.221.118.161;
    
    auto_create_channel   on;

    sip {        
        enabled on;               
        listen              5062;       
        serial              34020000002000000001;       
        realm               3402000000;
        ack_timeout         30;
        keepalive_timeout   120;
        auto_play           on;       
        invite_port_fixed     on;
        query_catalog_interval  60;
    }
}

rtc_server {
    enabled         on;    
    listen          8000;   
    candidate       221.221.118.161;
}

vhost __defaultVhost__ {

    dvr {
        enabled      off;
        dvr_path     /home/dvr/[app]/[stream]/[2006]-[01]-[02]/[15].[04].[05].[999].mp4;
        dvr_plan     session;
    }
    rtc {
        enabled     on;
        bframe      discard;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
30路大华摄像头，不间断拉流，大概10小时左右，GB28181媒体通道名称会变成ch开头的随机名称.
其中有2台大华带云台的摄像头注册上后，过会会自动小时。也不能播放。

**Comment by TanessaW** [comment]
Open

**Comment by winlinvip** [comment]
请按要求重新提个issue，模版中需要的信息都不能省略。

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，该Issue会被删除，请先阅读FAQ：#2716

请提个新的哈。
