### ISSUE TITLE
苹果手机平板不能参与one2one视频通话

### ISSUE THREAD

**Issue by lxge** [ossrs/srs#2666]
1. SRS版本(Version): `4.0.161`
2. 苹果手机端访问一对一通话界面, 点击通话不能显示, 安卓手机的可以,可能是这一块异常, 
浏览器报以下错误:The adapter.js addTrack polyfill only supports a single  stream which is associated with the specified track
`
e.RTCPeerConnection.prototype.addTrack = function(t, r) {
    var n = this;
    if ("closed" === this.signalingState) throw new DOMException("The RTCPeerConnection's signalingState is 'closed'.", "InvalidStateError");
    var i = [].slice.call(arguments, 1);
    // 异常问题
    if (1 !== i.length || !i[0].getTracks().find((function(e) {
        return e === t
    }))) throw new DOMException("The adapter.js addTrack polyfill only supports a single  stream which is associated with the specified track.", "NotSupportedError");
    var a = this.getSenders().find((function(e) {
        return e.track === t
    }));
    if (a) throw new DOMException("Track already exists.", "InvalidAccessError");
    this._streams = this._streams || {},
    this._reverseStreams = this._reverseStreams || {};
    var o = this._streams[r.id];
    if (o) o.addTrack(t),
    Promise.resolve().then((function() {
        n.dispatchEvent(new Event("negotiationneeded"))
    }));
    else {
        var s = new e.MediaStream([t]);
        this._streams[r.id] = s,
        this._reverseStreams[s.id] = r,
        this.addStream(s)
    }
    return this.getSenders().find((function(e) {
        return e.track === t
    }))
}
`

是当前webrtc通话不兼容苹果端吗

**Comment by winlinvip** [comment]
即将删除：客户端问题。

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端问题，该Issue会被删除。#2716

**Comment by lxge** [comment]
> 这个问题不是SRS问题，是FFmpeg、WebRTC、客户端问题，该Issue会被删除。#2716

好的谢谢
