### ISSUE TITLE
开源复刻：实现多平台直播，比如快手云直播或者Restream.io转推

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2676]
SRS直播答疑，每周六晚上20点，发现除了视频号，B站的用户数量也逐渐越来越多了。一般直播服务，转推到多个直播平台是必须要有的，比如：快手云直播的分发，Restream.io，小鹅通的转播等等。

## Why

用开源复刻转播方案，目标是可以了解转播涉及的相关技术，在某些时候比如私有云中如果需要转播，可以参考开源复刻的方案自己实现。

复刻的目标不是为了提供商业服务，如果真要实现商业产品可能还需要考虑更多，需要做得更完善，当然一般也会选择从开源方案开始做。

## Restream.io

在OBS上可以推流到restream.io平台：

![image](https://user-images.githubusercontent.com/2777660/137225415-04d1b980-278a-4478-ae6b-4afdb8f42b43.png)

这样就可以转播到其他平台比如twitch.tv，facebook和youtube：

![image](https://user-images.githubusercontent.com/2777660/137226649-95419b5b-8ccd-49fa-b91b-21fbcd9ad425.png)

## Kuaishou

来看看豪横的快手云直播，推流或拉流到快手平台后，默认会转码（有钱），并且支持推流到其他平台，自带restream.io的功能，直播完成后还能剪辑，只能说于老师做直播真是专业啊，有钱真是可以任性啊。

![image](https://user-images.githubusercontent.com/2777660/137226082-143b6063-6d86-41c6-b874-f7a073f8a7d2.png)

这样在快手、视频号和B站都可以看到直播了：

https://user-images.githubusercontent.com/2777660/137226245-d0669633-e59b-4766-ba04-8d1e0eb1c1db.mp4

## 小鹅通

我还试了下小鹅通的转播，也挺不错，不过是要收费的，而且还不便宜。当然小鹅通不是只有这一个功能，转播只是众多功能中的一个而已。

![image](https://user-images.githubusercontent.com/2777660/137226564-5f7da3bf-dd8d-45ff-bccc-525a6c9ee5bb.png)

## Research

https://www.youtube.com/results?search_query=stream+to+multiple+platform

Stream to Facebook, YouTube, Twitch, Mixer, LinkedIn or any other social platforms.

```
Client(OBS, FFmpeg, WebRTC, etc) ==> SRS => Multile Platforms(Facebook, YouTube, Twitch, etc)
``` 

当然国内平台也可以支持，比如视频号直播、抖音、快手、斗鱼等。

There still some works to do:

* [ ] First of all, we MUST support RTMPS, https://github.com/ossrs/srs/issues/2046
* [ ] And we should adapt to some platform, like https://github.com/ossrs/srs/issues/2288
* [ ] #2599

之前支持过一些类似的能力：

* [x] https://github.com/ossrs/srs/issues/1031#issuecomment-409773673
* [x] https://github.com/ossrs/srs/issues/1202

现有的多平台直播平台：

* https://restream.io/
* https://switchboard.live/
* https://castr.io/

其他多平台直播的方案：

* OBS插件，推多个RTMP服务器：[multiple-rtmp-outputs-plugin](https://obsproject.com/forum/resources/multiple-rtmp-outputs-plugin.964/)
* FFmpeg也可以推多个平台：[SRS：连麦和多个视频号联播](https://winlin.blog.csdn.net/article/details/120254991)

**Comment by ghostsf** [comment]
The live streaming platform does not provide a streaming address and does not allow direct streaming. It requires the use of exclusive streaming software, which is a problem.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If the platform does not provide a streaming address, no one can retweet. This is an issue with some platforms, not with this functionality.

This does not affect the ability to retweet, as this platform is not a target platform, but it does not mean there are no other platforms.

The goal of open source is a global platform. For platforms that are not supported, it's better to not support them. We only need to consider those that can be supported.

Just because some girls choose not to get married doesn't mean we have to remain single, nor does it mean that marriage has lost its value. We should live our lives the way we want to. There are plenty of girls around the world, even if the domestic live streaming platforms are gradually becoming more closed-off.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS cloud server is ready: https://mp.weixin.qq.com/s/FtaeQIJpb7vpmX2eFguLiQ

`TRANS_BY_GPT3`

**Comment by talway** [comment]
> 

https://mp.weixin.qq.com/s/FtaeQIJpb7vpmX2eFguLiQ

You can retweet any live streaming platform as long as it is supported by FFmpeg. In fact, it is not limited to the three commonly used platforms mentioned in our guide. We provide them to give the links for creating live rooms, and in the future, we will add a custom server.


Looking forward to the release of this powerful feature.

`TRANS_BY_GPT3`
