### ISSUE TITLE
RTMP forwarding based on stream key

### ISSUE THREAD

**Issue by clime** [ossrs/srs#2681]
Hello,

I would like to setup RTMP forwarding based on stream key. That is, I would like to specify rules like:

- rtmp://address.com/live/key1   ->    forward to machine1
- rtmp://address.com/live/key2   ->    forward to machine2

Is it possible?
Thank you

**Comment by winlinvip** [comment]
SRS will enhance the FORWARD feature, to fetch the forward config from your server.

Please see #1342 

And I will delete this issue, because it's dup.

**Comment by winlinvip** [comment]
I also comment your use scenario in https://github.com/ossrs/srs/issues/1342#issuecomment-944808799
