### ISSUE TITLE
API: Exposed for WebRTC without any access control

### ISSUE THREAD

**Issue by streamthing** [ossrs/srs#2684]
With WebRTC we need to expose http_api to public.
Why there isn't any access control for http_api?
User can send HTTP to /rtc/v1/play/ - which is OK.
But... there is also /api/v1/streams/ /api/v1/clients/ accessible for everyone in internet...

We need to setup reverse-proxy between client and SRS server?

**Comment by streamthing** [comment]
And... everyone can publish?
```
vhost __defaultVhost__ {
    rtc {
        enabled     on;
        rtmp_to_rtc on;
        rtc_to_rtmp off;
    }
    security {
        enabled on;
        allow publish 1.2.3.4;
        allow play all;
    }
}
```

**Comment by duiniuluantanqin** [comment]
> And... everyone can publish?
> 
> ```
> vhost __defaultVhost__ {
>     rtc {
>         enabled     on;
>         rtmp_to_rtc on;
>         rtc_to_rtmp off;
>     }
>     security {
>         enabled on;
>         allow publish 1.2.3.4;
>         allow play all;
>     }
> }
> ```

- security 
- http_hooks
- refer
any, or all of above can implement access control.Is not enough？

**Comment by duiniuluantanqin** [comment]
fixed by https://github.com/ossrs/srs/pull/3458
