### ISSUE TITLE
Support loongson, loongarch, 龙芯CPU

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2689]
# LOONGARCH

龙芯已经适配的多媒体开源项目[Media](http://www.loongnix.cn/index.php/Media)：

* 音视频应用开发框架、音视频编解码项目：FFmpeg、X264、OpenH264、libvpx、libyuv
* 基础压缩解压缩、图片编解码和图形渲染项目：zlib、libpng、libjpeg-turbo、pixman、skia
* 信号处理、线性代数库等高性能数学库：OpenBLAS 、FFT

如果要用龙芯服务器做视频云，还缺个流媒体服务器。

<a name="qemu"></a>

## [Build Loongarch SRS in Qemu](https://github.com/ossrs/srs/issues/2689#qemu)

龙芯有qemu镜像可以在本机跑起来，下面是操作步骤。

首先，下载qemu环境，mac下执行下面的命令，其他系统参考[这里](https://www.qemu.org/download/#macos)：

```bash
brew install qemu
```

然后，下载龙芯的iso镜像，还在路上，请稍等。。。

## LOONGSON 3A5000/3B5000

[龙芯3A5000/3B5000](https://www.loongson.cn/productShow/32)

龙芯3A5000/3B5000是面向个人计算机、服务器等信息化领域的通用处理器，基于龙芯自主指令系统（LoongArch®）的LA464微结构，并进一步提升频率，降低功耗，优化性能。在与龙芯3A4000处理器保持引脚兼容的基础上，频率提升至2.5GHz，功耗降低30%以上，性能提升50%以上。龙芯3B5000在龙芯3A5000的基础上支持多路互连。

![image](https://user-images.githubusercontent.com/2777660/138580780-bbfee763-cc80-4b61-8b28-71f6432ba555.png)

<a name="st-for-loongarch"></a>

## [ST for LOONGARCH](https://github.com/ossrs/srs/issues/2689#st-for-loongarch)

首先就需要适配ST到龙芯CPU，SRS 5.0已经支持了，参考 [ST #24](https://github.com/ossrs/state-threads/issues/24)

适配的代码，参考提交：https://github.com/ossrs/state-threads/commit/db4296960809af07c34f2a6e50a623f8d1b90f86

<a name="build-for-loongarch"></a>

## [Build for LOONGARCH](https://github.com/ossrs/srs/issues/2689#build-for-loongarch)

还需要适配一些依赖库的编译选项，主要是SRTP和Opus的，参考提交：https://github.com/ossrs/srs/commit/5b44cc6a17fa9078ae3f981e318f8f0d3ebb458f

**Comment by apt-getyou** [comment]
Is there a planned cycle at the moment?

`TRANS_BY_GPT3`

**Comment by yinshiyou** [comment]
The LoongArch platform adaptation for SRS is now available. Users have several ways to obtain the Loongson platform for testing:
1) Apply for a free Loongson cloud host, with the recommendation to include the remark "3A5000 + required mapping ports": [https://www.loongson.cn/loongsonCloud](https://www.loongson.cn/loongsonCloud)
2) Download QEMU or KVM virtual machines: Currently, on GitHub, you can also download virtual machines with the LoongArch architecture (uploaded by Loongson experts to their own repositories). The official version is on its way, so you won't have to wait too long, but for now, you can use option one.

`TRANS_BY_GPT3`

**Comment by Dr-624** [comment]
Does the boss have any plans for future adaptation to Shenwei?

`TRANS_BY_GPT3`

**Comment by Dr-624** [comment]
Currently, when reaching the step of 'make', it will report an error of undefined reference to '_st_md_cxt_save'.
![1f4af33e061222f554d47ef31d15173](https://user-images.githubusercontent.com/69237046/157003613-66cec8f5-716f-4969-86c7-9f8ea6fb8ee5.jpg)

`TRANS_BY_GPT3`

**Comment by yinshiyou** [comment]
Refer to the implementation of other platforms in trunk/3rdparty/st-srs/md_linux.S and add the implementation for Shenwei.

`TRANS_BY_GPT3`

**Comment by Dr-624** [comment]
Hello, I have received your email.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
龙芯mips64' translates to 'Loongson MIPS64'.

ST adaptation https://github.com/ossrs/srs/commit/1589858cb0be003946ca6637cb6ee4039071a62f
openssl adaptation https://github.com/ossrs/srs/commit/14832b66eb69fe81a3eb4e9d3afa7f6f2ddfb451 https://github.com/ossrs/srs/commit/079ac107f0bf4358df2855ac350054c9c733d0db
FFmpeg adaptation https://github.com/ossrs/srs/commit/1ab584b2ae06e9724e7d34aac89dec9d69f09fdc

`TRANS_BY_GPT3`

**Comment by xiangleiren** [comment]
> Currently, when reaching the "make" step, it will report an "undefined reference to '_st_md_cxt_save'" error ![1f4af33e061222f554d47ef31d15173](https://user-images.githubusercontent.com/69237046/157003613-66cec8f5-716f-4969-86c7-9f8ea6fb8ee5.jpg)

Have you solved it? I am also facing this problem.

`TRANS_BY_GPT3`

**Comment by xiangleiren** [comment]
Hello, there is a problem with compiling on sw_64. Can you please provide some solutions? Thank you.
![image](https://github.com/ossrs/srs/assets/112311627/3e1e0110-077c-445c-afa5-c55cbad9763c)

`TRANS_BY_GPT3`
