### ISSUE TITLE
Ossrs api question 

### ISSUE THREAD

**Issue by Eric29950** [ossrs/srs#2694]
I m trying to use the ossrs api but i don't know the right request to verify if a particular stream is present or no. 
Can u tell me if there is a request to verify a stream is present? 
I use curl like this :
http://192.168.1.101:1985/api/v1/streams and this list the active streams but something like streams/name=mystream does not work. 
Can you please help me? 

Thanks
Eric

**Comment by Baa14453** [comment]
I think you can only specify the stream by their ID
http://192.168.1.101:1985/api/v1/streams/<streamID>

**Comment by winlinvip** [comment]
Dup issue.

**Comment by winlinvip** [comment]
咨询和讨论请提交到[知识星球](http://bbs.ossrs.net)或者[Discussions](https://github.com/ossrs/srs/discussions)，也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)或来每周六直播答疑。
该Issue会被删除，请先阅读FAQ：#2716
