### ISSUE TITLE
DVR does not write files on cluster mode remote

### ISSUE THREAD

**Issue by warmanton** [ossrs/srs#2698]
**描述(Description)**

1. SRS版本(Version): `v4.0.187`
2. SRS的配置如下(Config):
```
listen              1935;
max_connections     1024;   #1000;
srs_log_tank        console;
daemon              off;
query_latest_version off;
force_grace_quit on;

http_api {
    enabled         on;
    listen          192.168.122.188:1985;
}
http_server {
    enabled         on;
    listen          192.168.122.188:8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}

vhost __defaultVhost__ {
    cluster {
        mode    remote;
        origin  192.168.122.4:1935 192.168.122.200:1935 192.168.122.71:1935 ;
    }
    dvr {
        enabled         on;
        dvr_path        /s3/dvr/[app]-[stream].[timestamp].flv;   # files are not created here
        dvr_plan        segment;
        dvr_duration    30;
   }
}
```

**重现(Replay)**

1. Start SRS in remote mode with config like above
2. SRS origins have DVR disabled (no dvr consig section)

**期望行为(Expect)**

Expected working dvr on remote if configured.

If I enable dvr on origin nodes then it works - that is ok but I would like to do writing on remote nodes since dvr would be more distributed (number of origin nodes is less then number of remote nodes).

**Comment by winlinvip** [comment]
DVR is not available for edge(mode remote), please read Wiki.

I will delete this issue.

**Comment by warmanton** [comment]
Ok, understood but `https://github.com/ossrs/srs/wiki/v4_EN_DVR` does not contain any mentioning about origin or remote mode.

**Comment by winlinvip** [comment]
你的问题已经在FAQ中存在，该Issue会被删除，请在FAQ中搜索`Edge HLS/DVR/RTC`：#2716
