### ISSUE TITLE
GB28181：DVR失败，只有48B；重新初始化摄像头后会好用, 但过一段时间重现

### ISSUE THREAD

**Issue by zhaoyk** [ossrs/srs#2705]
Migrate to https://github.com/ossrs/srs-gb28181/issues/10

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/10

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
