### ISSUE TITLE
GB28181  - 是否有计划支持视频回放功能，以及何时会将当前已经有的GB28181Feature分支并入主干

### ISSUE THREAD

**Issue by shaojun** [ossrs/srs#2709]
个人理解是当  _GB28181Feature分支_  足够稳定后，会并入主干，请问此时间节点有大概的预期吗？

另外，`sip`控制命令集比较灵活且与业务相关，如标题中的“**支持视频回放**”功能，请问，有没有考虑将`sip`命令进行抽象并开放成高层接口，让有应用层开发能力的调用端来简单调用呢？

**Comment by winlinvip** [comment]
咨询请不要提到issues，可以在微信群问，也可以来每周六直播答疑。

**Comment by winlinvip** [comment]
咨询和讨论请提交到[知识星球](http://bbs.ossrs.net)或者[Discussions](https://github.com/ossrs/srs/discussions)，该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
咨询和讨论请提交到[知识星球](http://bbs.ossrs.net)或者[Discussions](https://github.com/ossrs/srs/discussions)，也可以在微信群问，或者来每周六直播答疑。该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
咨询和讨论请提交到[知识星球](http://bbs.ossrs.net)或者[Discussions](https://github.com/ossrs/srs/discussions)，也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)或来每周六直播答疑。该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
咨询和讨论请提交到[知识星球](http://bbs.ossrs.net)或者[Discussions](https://github.com/ossrs/srs/discussions)，也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)或来每周六直播答疑。
该Issue会被删除，请先阅读FAQ：#2716
