### ISSUE TITLE
使用srs-bench进行拉流压力测试，报错

### ISSUE THREAD

**Issue by zhcx-gj** [ossrs/srs#2724]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): v4.0.76

1. SRS的日志如下(Log):
```

[2021-11-09 07:18:41.752][Error][1][9ll6064v][4] serve error code=1011 : service cycle : rtmp: stream service : rtmp: send 56 messages : send messages : send iovs : writev : writev timeout 30000 ms

```

1. SRS的配置如下(Config):
```

listen              1935;
    max_connections     1000;
    srs_log_tank        console;
    daemon              off;
    srs_log_level       trace;
    http_api {
        enabled         on;
        listen          1985;
    }
    http_server {
        enabled         on;
        listen          8080;
        dir             ./objs/nginx/html;
    }
    stats {
        network         0;
        disk            sda sdb xvda xvdb;
    }
    rtc_server {
        enabled         on;
        # Listen at udp://8000
        listen          8000;
        candidate       $CANDIDATE;
    }
vhost __defaultVhost__ {
        http_remux {
            enabled     on;
            mount       [vhost]/[app]/[stream].flv;
        }
        rtc {
            enabled     on;
            bframe      discard;
        }
    }
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 使用srs-bench进行压力测试（单源站部署）。模拟推送一路流，1000个客户端拉取。
2. 推流：./objs/sb_rtmp_publish -i ../1.flv -c 100 -r rtmp://x.x.x.x:32545/live/livestream_{i}
3. 拉流：./objs/sb_rtmp_load  -c 1000 -r  rtmp://x.x.x.x:32545/live/livestream_0
4. cpu和内存使用率都比较低

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
能正常拉流

**Comment by winlinvip** [comment]
不看srs-bench说明，别乱尝试。

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
