### ISSUE TITLE
RTMP: 宇视相机rtmp流无法接入

### ISSUE THREAD

**Issue by yingchengpa** [ossrs/srs#2731]
**描述(Description)**

> 宇视的rtmp无法接入，而nginx-http-flv 模块可以

1. SRS版本(Version): `3.0.168`

1. SRS的日志如下(Log):
```

[2021-11-12 16:07:06.820][Trace][26514][202] client identified, type=fmle-publish, vhost=209.1.1.5, app=live, stream=100, param=, duration=0ms

[2021-11-12 16:07:06.820][Trace][26514][202] connected stream, tcUrl=rtmp://209.1.1.5/live, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=1935, app=live, stream=100, param=, args=null

[2021-11-12 16:07:06.821][Trace][26514][202] source url=/live/100, ip=204.204.30.214, cache=1, is_edge=0, source_id=0/0

[2021-11-12 16:07:06.875][Trace][26514][202] ignore disabled exec for vhost=__defaultVhost__

[2021-11-12 16:07:06.875][Trace][26514][202] http: mount flv stream for sid=/live/100, mount=/live/100.flv

[2021-11-12 16:07:06.875][Trace][26514][202] start publish mr=0/350, p1stpt=20000, pnt=5000, tcp_nodelay=0

[2021-11-12 16:07:08.379][Trace][26514][202] cleanup when unpublish

[2021-11-12 16:07:08.379][Error][26514][202][4] serve error code=2003 : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: decode message : decode message : decode command name : String invalid marker=0

thread [26514][202]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:210][errno=4]

thread [26514][202]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:399][errno=4]

thread [26514][202]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:891][errno=11]

thread [26514][202]: consume() [src/app/srs_app_recv_thread.cpp:396][errno=11]

thread [26514][202]: handle_publish_message() [src/app/srs_app_rtmp_conn.cpp:994][errno=11]

thread [26514][202]: process_publish_message() [src/app/srs_app_rtmp_conn.cpp:1039][errno=11]

thread [26514][202]: decode_message() [src/protocol/srs_rtmp_stack.cpp:432][errno=11]

thread [26514][202]: do_decode_message() [src/protocol/srs_rtmp_stack.cpp:650][errno=11]

thread [26514][202]: srs_amf0_read_string() [src/protocol/srs_protocol_amf0.cpp:1530][errno=11](Interrupted system call)

[2021-11-12 16:07:10.750][Trace][26514][204] RTMP client ip=204.204.30.214, fd=10

[2021-11-12 16:07:10.764][Trace][26514][204] simple handshake success.

```

1. SRS的配置如下(Config):
```
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

找一款宇视的ipc，设置媒体流发送rtmp流到srs

**期望行为(Expect)**

> 和 nginx-http-flv 模块一样，可以正常接入宇视rtmp流

**Comment by winlinvip** [comment]
First of all, don't say that XXX supports SRS and you don't, as it has nothing to do with the issue itself. It only makes people feel coerced: if other children can score 100 in their studies, why can't you? It doesn't make sense to seek help with your problem and still have to endure frustration.

In addition, the issue lies with the RTMP stream introduced by Yushi's IPC, and the error message clearly indicates an abnormal RTMP AMF0 message. You need to use Wireshark to capture the packets. Remember to set the chunk_size to 128 in the SRS configuration.

```
chunk_size          128;
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If you cannot provide the Wireshark capture, I will close and delete this issue as it is an unreproducible issue. Please provide it as soon as possible.

`TRANS_BY_GPT3`

**Comment by yingchengpa** [comment]
The capture is as follows:
[Uniview IPC RTMP stream](https://vlog-web-hz.oss-cn-hangzhou.aliyuncs.com/1.pcap)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I took a look at the RTMP packet sequence of this camera, as shown in the following image:

![image](https://user-images.githubusercontent.com/2777660/147402271-3577a060-bc8b-413d-8a35-a2fc5e81a545.png)

It does not follow the usual client's push streaming command, refer to:

```
SrsRtmpServer::identify_client
```

If you want to be compatible with Uniview cameras, please submit a patch.

`TRANS_BY_GPT3`

**Comment by yingchengpa** [comment]
我使用了4.0.139版本进行测试，错误提示不同，错误在SrsFastStream::grow()  ,
if (nb_exists_bytes + nb_free_space < required_size) {
            return srs_error_new(ERROR_READER_BUFFER_OVERFLOW, "overflow, required=%d, max=%d, left=%d", required_size, nb_buffer, nb_free_space);
        }

对于1080p 4M码流我把 SRS_DEFAULT_RECV_BUFFER_SIZE 131072*10  扩大10倍，跑了一晚上未出现问题。

**Comment by yingchengpa** [comment]
The relationship with the streaming command is not significant. I debugged it myself and have initially resolved the issue. The reasons are as follows: 
```
SrsProtocol::do_decode_message()
if (header.is_amf0_command() || header.is_amf3_command() || header.is_amf0_data() || header.is_amf3_data()) 
{  
It should only parse the command, but Yushi carries is_amf0_data(), which causes an exception when reading the common code srs_amf0_read_string(stream, command).
}
```

Modification method.
```
if (header.is_amf0_command() || header.is_amf3_command() || header.is_amf3_data())   
```

Remove the judgment of header.is_amf0_data().

It has been running normally for a while, but I'm not sure if it's okay to make this modification. Please advise.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
![image](https://user-images.githubusercontent.com/2777660/147625326-c275fcf5-1377-41dc-a3a5-7c81ba47f05d.png)

![image](https://user-images.githubusercontent.com/2777660/147625341-024de2e8-ffef-47c0-9d89-e2e765e809c2.png)

Which package is AMF0 Data? I see all the captured packages are AMF0 Command.

Please don't rush, provide me with an answer and a solution. Could you please give me detailed information about the data and the process?

`TRANS_BY_GPT3`

**Comment by yingchengpa** [comment]
I don't understand the rtmp protocol, but I have been researching and looking into rtmp interactions to try and solve this problem. At the same time, I have been testing the latest version of Yushi and have discovered two issues:

1. When using an older version of Yushi, there is an error in the srs_amf0_read_string() function. I need to modify the judgment in the do_decode_message function. As for the reason, I have printed the header and stream information and suspect that there is a problem with a certain message carried by Yushi (which message exactly, I haven't found). However, I also encounter the second issue.

2. When using the latest version, do_decode_message does not throw an error. However, in the case of high bitrates (4M), the SrsFastStream::grow if (nb_exists_bytes + nb_free_space < required_size) will prompt an error indicating that there is insufficient remaining space. I have increased the SRS_DEFAULT_RECV_BUFFER_SIZE by 10 times, and it is currently stable.

`TRANS_BY_GPT3`

**Comment by yingchengpa** [comment]
From the srs log, it seems that an exception occurred after receiving the publish('100') message, such as the possibility of this message being parsed incorrectly.

![image](https://user-images.githubusercontent.com/6310830/147649934-ed12f388-19a0-48db-8f2b-1485ab7414c1.png)

`TRANS_BY_GPT3`

**Comment by yingchengpa** [comment]
The rtmp information of the new and old versions of the Hikvision camera is almost the same. The following is the rtmp interaction message of the new version. This version will not report a failure of "do_decode_message", but only prompt that there is insufficient remaining space.

[newVersion.pcap](https://vlog-template-hz.oss-cn-hangzhou.aliyuncs.com/var/vlog/upload/newVersion.pcap)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍 Thank you, the analysis process of this question is quite professional.

It seems that the RTMP packets were not parsed by Wireshark. Can you set the chunk size to 128? This way, they can be parsed correctly.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I didn't see this package, but I think it's very likely that this package is onMetaData, which is an AMF0 Data that contains information about the stream.

If I'm not mistaken, it's still an issue with the previous command rather than a parsing error with this package (it's like the previous command sequence is not recognized, causing the parsing to fail later on).

You can set the chunksize to make Wireshark parse correctly.

Alternatively, debug SRS and see how the sub-functions of `SrsRtmpServer::identify_client` are called. You can also provide the debugging process.

Only in this way can we know whether AMF0 Data is really used instead of Command.

`TRANS_BY_GPT3`

**Comment by yingchengpa** [comment]
Increase log output: 

![image](https://user-images.githubusercontent.com/6310830/147714928-6e39f6b6-10ae-4ef0-bfeb-9de470d05796.png)

Print result:
[2021-12-30 09:34:53.766][Trace][2780][0764b618] Hybrid cpu=2.00%,9MB

[2021-12-30 09:34:54.100][Trace][2780][m03496i8] ----srs_amf0_read_string stream = , 169,head 18 , 169      ----- headMessageType = 18, belongs to AMF0 Data

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Send me a message on WeChat. You didn't understand what I meant, let's talk on voice call.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Insufficient information, closing for now. If it happens again, please provide detailed information and contact me again.

`TRANS_BY_GPT3`
