### ISSUE TITLE
WebRTC: 腾讯宝塔EasyPlayer无法播放流

### ISSUE THREAD

**Issue by dannyfk221** [ossrs/srs#2735]
![image](https://user-images.githubusercontent.com/17662124/141795581-da0ad298-95d6-4208-ab2c-e44106980976.png)

按照上述配置，启动之后，使用h5播放器进行播放，视频无法播放，并在控制台输出了一个错误 “net::ERR_CONNECTION_REFUSED” 。

服务器的防火墙已经关闭了，但是问题依旧。

下图是，centos服务器显示8000端口已经启动
![image](https://user-images.githubusercontent.com/17662124/141796339-a260e28d-c90a-41ab-9741-c839a6d9a691.png)

下图是，srs的输出日志
![image](https://user-images.githubusercontent.com/17662124/141796465-897c45f2-c168-4a11-80f8-93a4e68770c2.png)

下图是宝塔面板的设置，已经把防火墙关闭。
![image](https://user-images.githubusercontent.com/17662124/141796686-20ddec57-c698-4791-bbc0-26d3b76abf52.png)

下图是我在浏览器使用播放器看到的错误。 
![image](https://user-images.githubusercontent.com/17662124/141796856-696987f9-042b-463d-8cdd-4ab7eeed7178.png)

**Comment by winlinvip** [comment]
用srs-player，别乱试，请参考文档 

这个问题在[Wiki](https://github.com/ossrs/srs/wiki/v4_CN_Home)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
It should be EasyPlayer incompatible. Let me find someone who knows about this player.

`TRANS_BY_GPT3`
