### ISSUE TITLE
macos 11.6，automake-1.16无法编译。

### ISSUE THREAD

**Issue by wahello** [ossrs/srs#2739]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

>  允许命令 `./configure --osx`

1. SRS版本(Version): `4.0release`

1. SRS的日志如下(Log):
```

srs/trunk/objs/Platform-Darwin-20.6.0-Clang13.0.0-SRS4-x86_64/opus-1.3.1/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127
Build opus-1.3.1 failed, ret=2

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `macos 11.6`
2. `automake-1.16`

**生成Makefile**

> 无法生成Makefile

**Comment by xiaozhihong** [comment]
M1版本吗? M1我们没有电脑还不能适配哈哈哈

**Comment by wahello** [comment]
@xiaozhihong 不是，x86_64

**Comment by xiaozhihong** [comment]
@wahello 试试 brew install automake, 我看了下srs的configure脚本没有带这个

**Comment by wahello** [comment]
@xiaozhihong  `brew install automake`安装了 1.16，是不是指定了automake的版本？

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、流的内容、编译工具问题，该Issue会被删除。#2716
