### ISSUE TITLE
webrtc 播放是黑屏的

### ISSUE THREAD

**Issue by jackyshaw2017** [ossrs/srs#2740]
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    listen 8000;
    # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#config-candidate
    candidate 192.168.2.254;

}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtmp-to-rtc
        rtmp_to_rtc off;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtc-to-rtmp
        rtc_to_rtmp off;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
![1233](https://user-images.githubusercontent.com/30282633/142152554-7ce81dde-a804-40ea-9630-6404937d1eef.png)

srs正常
![123456](https://user-images.githubusercontent.com/30282633/142153415-4609a97f-3d9d-41b5-be26-79814d709936.png)

**Comment by winlinvip** [comment]
你的问题已经在FAQ中存在，该Issue会被删除，请在FAQ中搜索 WebRTC+Live ：#2716
