### ISSUE TITLE
GB28181: 科达平台级联无法解析流

### ISSUE THREAD

**Issue by zgxsm** [ossrs/srs#2753]
Migrate to https://github.com/ossrs/srs-gb28181/issues/9

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/9

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
