### ISSUE TITLE
新版本 RAW API 不支持 allow_update

### ISSUE THREAD

**Issue by zwhisper** [ossrs/srs#2756]
1. SRS版本(Version): `feature/h265`

RAW API 希望可以添加上3.0的这2个更新功能
        allow_query         on;
        allow_update        on;

**Comment by winlinvip** [comment]
你的问题已经在FAQ中存在，该Issue会被删除，请在FAQ中搜索`http-raw-api`：https://github.com/ossrs/srs/issues/2716#http-raw-api
