### ISSUE TITLE
how to limit or excluse some rtmp app name ?

### ISSUE THREAD

**Issue by blacksail29** [ossrs/srs#2761]
Hi all,

My ip cameras send some rtmp live streams to my srs server and i would like that the rtmp app LIVE for example could not be accessed by clients.
I only want that my srs server accepts MYNAME rtmp app name , excludin all others.

I did not see any directives in rtmp block about this.

Thanks for help,

**Comment by winlinvip** [comment]
Use [HTTP Callback](https://github.com/ossrs/srs/wiki/v4_EN_HTTPCallback) to reject the invalid request.
