### ISSUE TITLE
WebRTC: HTTP页面推流失败，Cannot read properties of undefined (reading 'getUserMedia')

### ISSUE THREAD

**Issue by okthomasren** [ossrs/srs#2762]
**描述(Description)**
1. SRS版本(Version): 阿里云映像 registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
复现步骤：
1. SRS的配置如下(Config):
默认的rtc.conf配置文件

**重现(Replay)**

1. 登录某台阿里云ECS设备，:
2. 拉取docker 映像 ：docker pull registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
3. 设置CANDIDATE : CANDIDATE="xx.xxx.xx.xxx"
4. 启动docker映像 ：docker run --rm -it --env CANDIDATE=$CANDIDATE -p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4 objs/srs -c conf/rtc.conf

前端错误日志：
?eip=x.x.x.x to overwrite candidate. 覆盖服务器candidate(外网IP)配置
rtc_publisher.html?autostart=true:104 TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at Object.SrsRtcPublisherAsync.self.publish (srs.sdk.js:50)
    at startPublish (rtc_publisher.html?autostart=true:98)
    at rtc_publisher.html?autostart=true:115
(anonymous) @ rtc_publisher.html?autostart=true:104
rtc_publisher.html?autostart=true:104 TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at Object.SrsRtcPublisherAsync.self.publish (srs.sdk.js:50)
    at HTMLButtonElement.startPublish (rtc_publisher.html?autostart=true:98)
    at HTMLButtonElement.dispatch (jquery-1.10.2.min.js:5)
    at HTMLButtonElement.v.handle (jquery-1.10.2.min.js:5)

**期望行为(Expect)**
通过docker部署到阿里云ECS的srs4服务能正常RTC推流

**Comment by okthomasren** [comment]
Front-end access example page:
http://xx.xxx.xx.xx:8080/players/rtc_publisher.html?autostart=true, streaming failed.

Front-end error log:
?eip=x.x.x.x to overwrite candidate. Overwriting server candidate (public IP) configuration.
rtc_publisher.html?autostart=true:104 TypeError: Cannot read properties of undefined (reading 'getUserMedia')
at Object.SrsRtcPublisherAsync.self.publish (srs.sdk.js:50)
at startPublish (rtc_publisher.html?autostart=true:98)
at rtc_publisher.html?autostart=true:115
(anonymous) @ rtc_publisher.html?autostart=true:104
rtc_publisher.html?autostart=true:104 TypeError: Cannot read properties of undefined (reading 'getUserMedia')
at Object.SrsRtcPublisherAsync.self.publish (srs.sdk.js:50)
at HTMLButtonElement.startPublish (rtc_publisher.html?autostart=true:98)
at HTMLButtonElement.dispatch (jquery-1.10.2.min.js:5)
at HTMLButtonElement.v.handle (jquery-1.10.2.min.js:5)

Expected behavior (Expect):
The SRS4 service deployed on Alibaba Cloud ECS through Docker should be able to push RTC streams normally.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is a basic permission issue with WebRTC.

[Cannot read properties of undefined (reading 'getUserMedia')](https://stackoverflow.com/questions/67663961/cannot-read-property-getusermedia-of-undefined-over-https)

> Note: If the current document isn't loaded securely, navigator.mediaDevices will be undefined, and you cannot use getUserMedia(). See Security for more information on this and other security issues related to using getUserMedia().

The meaning is: You must use a webpage with HTTPS (or localhost) to access the `getUserMedia` API, otherwise this exception will be thrown.

I have improved srs.sdk.js to provide clearer prompts.

```
rtc_publisher.html?autostart=true:104 Error: Please use HTTPS or localhost to publish, read https://github.com/ossrs/srs/issues/2762#issuecomment-983147576
    at Object.SrsRtcPublisherAsync.self.publish (srs.sdk.js:51)
    at startPublish (rtc_publisher.html?autostart=true:98)
    at rtc_publisher.html?autostart=true:115
```

This way, the problems will be clearer.

`TRANS_BY_GPT3`

**Comment by bbhxwl** [comment]
> **Description**
'
Make sure to maintain the markdown structure.
> 
> 1. SRS Version: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
>    Reproduction steps:
> 2. SRS configuration (Config):
>    Default rtc.conf configuration file
> 
> **Replay**
> 
> 1. Log in to an Alibaba Cloud ECS device.
> 2. Pull the Docker image: `docker pull registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4`
> 3. Set the CANDIDATE: `CANDIDATE="xx.xxx.xx.xxx"`
> 4. Start the Docker image: `docker run --rm -it --env CANDIDATE=$CANDIDATE -p 1935:1935 -p 8080:8080 -p 1985:1985 -p 8000:8000/udp registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4 objs/srs -c conf/rtc.conf`
> 
> Frontend error log: ?eip=x.x.x.x to overwrite candidate. Overwriting server candidate (public IP) configuration rtc_publisher.html?autostart=true:104 TypeError: Cannot read properties of undefined (reading 'getUserMedia') at Object.SrsRtcPublisherAsync.self.publish (srs.sdk.js:50) at startPublish (rtc_publisher.html?autostart=true:98) at rtc_publisher.html?autostart=true:115 (anonymous) @ rtc_publisher.html?autostart=true:104 rtc_publisher.html?autostart=true:104 TypeError: Cannot read properties of undefined (reading 'getUserMedia') at Object.SrsRtcPublisherAsync.self.publish (srs.sdk.js:50) at HTMLButtonElement.startPublish (rtc_publisher.html?autostart=true:98) at HTMLButtonElement.dispatch (jquery-1.10.2.min.js:5) at HTMLButtonElement.v.handle (jquery-1.10.2.min.js:5)
> 
> **Expected Behavior (Expect)** The SRS4 service deployed on Alibaba Cloud ECS through Docker should be able to stream RTC (Real-Time Communication) properly.

> **Can you successfully use WebRTC to stream on a webpage?**

`TRANS_BY_GPT3`
