### ISSUE TITLE
GB28181 SIP注册密码如何配置

### ISSUE THREAD

**Issue by mayomeng** [ossrs/srs#2767]
如题，请问如何在配置文件中配置SIP的注册密码，push.gb28181.conf配置文件和wiki中没有找到相关的配置项

**Comment by winlinvip** [comment]
咨询和讨论请[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)在群里问， 还有每周六晚上20点直播答疑。
该Issue会被删除，请先阅读FAQ：#2716
