### ISSUE TITLE
支持GB28181对上级联么?

### ISSUE THREAD

**Issue by zlklink** [ossrs/srs#2779]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**
支持GB28181对上级联么?
> 描述你遇到了什么问题(Please description your issue here)
需要对上级联到其他GB28181平台
1. SRS版本(Version): `xxxxxx`

1. SRS的日志如下(Log):
```

xxxxxxxxxxxx

```

1. SRS的配置如下(Config):
```

xxxxxxxxxxxx

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
咨询和讨论请[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)在群里问， 还有每周六晚上20点直播答疑。
该Issue会被删除，请先阅读FAQ：#2716
