### ISSUE TITLE
Docs: Rewrite ossrs.net, 重写官网文档

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2785]
最近几天看了一遍[react.org](https://reactjs.org)，读完了《大教堂与集市》，感受到了中国开源和国际开源的差距，不大也就是30年左右吧，希望在我70岁左右时能看到中国的开源社区能达到国外现在这个样子。

还是要踏踏实实的站好自己的岗位，做好自己的事情，SRS文档在中国的开源甚至是商业产品中都算不错的，和[react.org](https://reactjs.org)差距也不大活跃度差不多，注意是和它文档项目的活跃度差不多，和[react](https://github.com/facebook/react)暂时还不是目标，哈哈哈。

我作为一个REACT的新人，看了一遍[react.org](https://reactjs.org)，对于REACT能干啥、有哪些东西、哪些我暂时还可能用不着、哪些我还没弄明白、如果想贡献怎么贡献，都非常了解。难怪参与的人多，因为社区的门槛很低。

如果说之前SRS的目标是很好用的音视频服务器，降低的是音视频开发者搞服务器的门槛，那么下个十年，我的核心工作就是要降低社区的门槛，让大家愿意参与到开源中都很方便，了解这个项目很方便，不仅仅是使用门槛降低，而是参与门槛降低。

我计划在SRS 5.0重新架构和写SRS的文档。

主要就学习 [react.org](https://reactjs.org), [bootstrap](https://getbootstrap.com/docs/5.1/getting-started/introduction/), [react-bootstrap](https://react-bootstrap.github.io/) 和 [node](https://nodejs.org) ：

* 官网变成文档，有自己的独立仓库，自动集成和发布。
* 多语言分成不同的子项目，参考 [en](https://github.com/reactjs/reactjs.org) 和 [cn](https://github.com/reactjs/zh-hans.reactjs.org)
* REACT不支持多版本，参考 [reactjs.org#85](https://github.com/reactjs/reactjs.org/issues/85) ，可以参考 [nodejs](http://nodejs.org/docs/) 分版本的文档，还是很重要的，nodejs的文档是在代码仓库 [node](https://github.com/nodejs/node/tree/master/doc)。
* 教程Tutorial 和文档Docs需要分开。教程是用一个典型场景给用户快速了解，Docs是给开发者从入门到掌握的文档。REACT文档这个做的比较好。
* [Bootstrap的官网](https://getbootstrap.com/)和文档也非常好，而且有分版本的文档，不过它的官网没有REACT那么简单，入口比较多一些，这也可能是因为bootstrap提供的功能更多一些。
* [react-bootstrap](https://react-bootstrap.github.io/getting-started/introduction/)和[bootstrap](https://getbootstrap.com/docs/5.1/getting-started/introduction/)分为左导航栏和由导航栏，左边是总目录，右边是页面内目录，比较合理。
* [reactjs.org](https://reactjs.org/)和[bootstrap](https://getbootstrap.com/docs/5.1/getting-started/introduction/)都有使用[algolia](https://github.com/algolia/docsearch)文档搜索能力。其中中文也是可以，参考[zh-hans.reactjs.org](https://zh-hans.reactjs.org/)。
* [GitHub Docs](https://github.com/github/docs) 其实GitHub的文档也是很不错的，只是一般比较少的系统去读，一般是有问题了会查。
* [redis.io](https://redis.io/) Redis的官网也很简单明了，写的很好。

**Comment by ghostsf** [comment]
support

`TRANS_BY_GPT3`

**Comment by firemakergk** [comment]
I am a programmer with 7 years of experience. Yesterday, I discovered SRS and I was very excited. But when I started trying it out, I found myself going around in circles on the wiki and couldn't get the hang of it. The recommended Bilibili video was a paid course. I must say that the documentation for this project does not live up to its quality. I am delighted to see that the author is starting to pay attention to the documentation quality.

`TRANS_BY_GPT3`

**Comment by zhOrange** [comment]
Truly amazing!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
> I am a programmer with 7 years of experience. Yesterday, I discovered SRS and was very excited. However, when I started to try it out, I found myself going around in circles on the wiki and unable to get started. The recommended Bilibili videos are paid courses. It can be said that the documentation of this project does not match its quality. I am glad to see that the author is now paying attention to the quality of the documentation.

Buddy, did you spend those seven years on PHP, haha.

`TRANS_BY_GPT3`

**Comment by firemakergk** [comment]
> > I am a programmer with 7 years of experience. I discovered SRS yesterday and I was very excited. However, when I started trying it out, I found myself going around in circles on the wiki and couldn't figure out how to get started. The recommended B station video is a paid course. I can say that the documentation for this project does not match its quality. I am glad to see that the author has started to prioritize documentation quality.
> 
> Bro, did you spend those seven years on PHP, haha!

> Bro, maybe you didn't mean it, but it sounds a bit arrogant.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Hey bro, maybe you didn't mean it, but it came off a bit arrogant.

Hmm, sorry sorry. Is it really that difficult for audio and video? Could it be a lack of time investment?

Seeing everyone so excited about the new documentation, it's a bit different from what I had in mind. The new documentation may not have such a significant impact, and the process of going from 70 to 80 marks may disappoint everyone.

`TRANS_BY_GPT3`

**Comment by sureone** [comment]
After about a week of trial and error using the tutorial on the official website's wiki, I successfully deployed a test environment for gb28181. The most remarkable thing is the all-in-one package of the source code, which can be built and used without downloading other dependency libraries. I give you a thumbs up and feel proud of Chinese programmers for creating such excellent open source projects. I hope you can continue to improve and keep up the good work! I hope to have a chance to contribute as well.

`TRANS_BY_GPT3`

**Comment by xiaosongxiaosong** [comment]
I recommend using [Docusaurus](https://docusaurus.io/) to write the documentation. It is written in markdown and supports multiple languages, versions, and search functionalities.
@winlinvip 

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@xiaosongxiaosong I just checked it out, it's great indeed, very suitable.

`TRANS_BY_GPT3`

**Comment by xiaosongxiaosong** [comment]
I took some time today to create a demo. I will work on the search and multiple languages this week. For the content of the documentation, I have randomly copied a few Chinese documents.
Repository address: https://github.com/goblin-laboratory/srs-docs
Preview address: https://goblin-laboratory.github.io/srs-docs/

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@xiaosongxiaosong Did you message me on WeChat? Let's chat, I want to reorganize the documents, we can work on the documents together.

`TRANS_BY_GPT3`

**Comment by xiaosongxiaosong** [comment]
给你发好友申请了哈，今天白天有点忙，6 点后你有空的时候找我哈

**Comment by xiaosongxiaosong** [comment]
I sent you a friend request, haha. I was a bit busy during the day today, so contact me after 6 pm when you are free, @winlinvip.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Create a new repository https://github.com/ossrs/srs-docs and assign admin role to @xiaosongxiaosong , thanks a lot 👍

**Comment by qingmang** [comment]
Finally waiting for you

`TRANS_BY_GPT3`

**Comment by yzm0080** [comment]
[docsify](https://docsify.js.org/#/zh-cn/) is also a good choice

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
We have already started the project, so there is no need for further discussion on the plan. Thank you all.

Those who want to participate can leave a message. It's not about which plan is excellent, but about coming together to work on it.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
New domain ossrs.io has been launched and overseas servers are now available. In the future, the default language for overseas will be English.

In China, ossrs.net still defaults to Chinese, and the servers are hosted on Alibaba Cloud.

The two domain names and servers are isolated, but they have the same content and are automatically deployed through CI/CD.

`TRANS_BY_GPT3`

**Comment by zpczpc** [comment]
> Through the tutorial on the official website's wiki, after about a week of exploration, I successfully deployed a test environment for gb28181. The most amazing thing is that the source code is an all-in-one package, which can be built and used without downloading other dependencies. I give you a thumbs up and feel proud of our Chinese programmers for making such excellent open source projects. I hope you keep improving and fighting! I hope I can also contribute in the future.

Hello, sir. Can the use of this protocol enable the playback function for Hikvision cameras?

`TRANS_BY_GPT3`

**Comment by jinchengcheng** [comment]
I am in the Java direction and I want to participate in the project. However, it is difficult to transition between industries. I hope there can be easier-to-use APIs for beginners at the low level, while also supporting secondary development in Java. If this is possible, it would be great. It would allow people like me with different backgrounds to be able to work on streaming media-related things. Please don't take offense, just offering a suggestion.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The new official website and documents have been launched: 

* Chinese: https://ossrs.net
* International site: https://ossrs.io

The new official website is now open. We welcome everyone to continue participating.
* https://github.com/ossrs/srs-docs

`TRANS_BY_GPT3`
