### ISSUE TITLE
 serve error code=1011 

### ISSUE THREAD

**Issue by nihaoma001** [ossrs/srs#2788]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.1`

1. SRS的日志如下(Log):
```

serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 5000ms, nb_msgs=875105

```

1. SRS的配置如下(Config):
```

默认rtc.conf配置

```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1、7路rtmp推流，32路播放，在运行12小时之后出现该错误。

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
长期稳定推流和播放。

**Comment by shengzhou1216** [comment]
我在使用ffmpeg 循环推送某一个视频时也遇到了一样的问题（！！有的视频可以循环推送成功）。
```
[2022-04-26 09:37:20.884][Error][1][88w18585][4] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 5000ms, nb_msgs=1445
thread [1][88w18585]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:217][errno=4]
thread [1][88w18585]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:414][errno=4]
thread [1][88w18585]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:916][errno=62](Interrupted system call)
```
使用的命令如下:
```
ffmpeg -stream_loop -1 -re -i ~/Downloads/sample_720p.mp4 -c copy -f flv  rtmp://localhost/live/livestream
```

**Comment by shengzhou1216** [comment]
使用OBS推流没有出现此问题

> 我在使用ffmpeg 循环推送某一个视频时也遇到了一样的问题（！！有的视频可以循环推送成功）。
> 
> ```
> [2022-04-26 09:37:20.884][Error][1][88w18585][4] serve error code=1011 : service cycle : rtmp: stream service : rtmp: publish timeout 5000ms, nb_msgs=1445
> thread [1][88w18585]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:217][errno=4]
> thread [1][88w18585]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:414][errno=4]
> thread [1][88w18585]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:916][errno=62](Interrupted system call)
> ```
> 
> 使用的命令如下:
> 
> ```
> ffmpeg -stream_loop -1 -re -i ~/Downloads/sample_720p.mp4 -c copy -f flv  rtmp://localhost/live/livestream
> ```

使用OBS推流没有出现此问题

**Comment by yipeng2001** [comment]
[2023-01-02 17:37:17.795][Error][89286][236y66dk][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [89286][236y66dk]: process_requests() [src/app/srs_app_http_conn.cpp:185][errno=62]
thread [89286][236y66dk]: parse_message() [src/protocol/srs_service_http_conn.cpp:100][errno=62]
thread [89286][236y66dk]: parse_message_imp() [src/protocol/srs_service_http_conn.cpp:164][errno=62]
thread [89286][236y66dk]: grow() [src/protocol/srs_protocol_stream.cpp:162][errno=62]
thread [89286][236y66dk]: read() [src/protocol/srs_service_st.cpp:522][errno=62](Timer expired)
