### ISSUE TITLE
error No FFmpeg found at /usr/local/bin/ffmpeg 

### ISSUE THREAD

**Issue by phusinh** [ossrs/srs#2791]
i am running transcode deploy example in this 2nd step i get error No FFmpeg found at /usr/local/bin/ffmpeg 

![image](https://user-images.githubusercontent.com/48083638/146168628-d789f0b7-f645-4e4c-b8dd-f16b1a89dfa2.png)

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、流的内容、编译工具问题，该Issue会被删除。#2716
