### ISSUE TITLE
对了。这里还有个问题， test-play.live.com这个vhost里面配置了vhost字段的话，然后rtmp地址里面params又带了vhost，会导致配置里面的vhost字段失效。这块要改下代码，如果vhost里面配置了vhost的字段，srs_generate_rtmp_url的时候需要把query里面的vhost remove掉。不然生成的url还是test-play.live.com，其实应该按照配置来说应该是test-push.live.com

### ISSUE THREAD

**Issue by TanessaW** [ossrs/srs#2804]
对了。这里还有个问题， test-play.live.com这个vhost里面配置了vhost字段的话，然后rtmp地址里面params又带了vhost，会导致配置里面的vhost字段失效。这块要改下代码，如果vhost里面配置了vhost的字段，srs_generate_rtmp_url的时候Office Open XML .docx, .把query里面的vhost remove掉。不然生成的url还是test-play.live.com，其实应该按照配置来说应该是test-push.live.com

_Originally posted by @gaod in https://github.com/ossrs/srs/issues/2594#issuecomment-916695882_

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
