### ISSUE TITLE
ubuntu环境下编译安装后，max open files获取bug

### ISSUE THREAD

**Issue by dzhcool** [ossrs/srs#2811]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> ubuntu18.04编译安装后启动报错，提示max open files参数不对。日志中输出系统的max open files参数和真实设置值不一致。

1. SRS版本(Version): 4.0.191

1. SRS的日志如下(Log):
```
[2021-12-24 13:35:43.250][Error][9308][o342941q][22] invalid max_connections=3000, required=3107, system limit to 1024, total=3007(max_connections=3000, nb_consumed_fds=7). you can change max_connections from 3000 to 1016, or you can login as root and set the limit: ulimit -HSn 3107(Invalid argument)
[2021-12-24 13:35:43.250][Error][9308][o342941q][22] Failed, code=1023 : check config : check connections : 3007 exceed max open files=1024
```

1. SRS的配置如下(Config):
```
# srs4 example for edge
listen          1935;
pid             /var/run/srs-edge-0.pid;
ff_log_dir      /gpstream/logs/ffmpeg;
srs_log_tank    file;
srs_log_level   trace;
srs_log_file    /gpstream/logs/srs-edge-0.log;
max_connections 3000;
daemon          on;

```

**重现(Replay)**
测试方法：
1. trunk/src/main/srs_main_server.cpp 206行 增加调试信息
```
int main(int argc, char** argv)
{
    int max_open_files = (int)sysconf(_SC_OPEN_MAX);
    printf("[davis-debug] max open files:%d \n", max_open_files);
```
2. trunk/src/app/srs_app_config.cpp 2877行 增加调试信息
```
srs_error_t SrsConfig::check_number_connections()
{
    int _max_open_files = (int)sysconf(_SC_OPEN_MAX);
    printf("[davis-debug][srs_app_config] max open files:%d \n", _max_open_files);
```
3. 编译启动后调试信息：
```
[davis-debug] max open files:65535 
[2021-12-24 13:35:43.249][Trace][9308][o342941q] XCORE-SRS/4.0.191(Leo)
[2021-12-24 13:35:43.249][Trace][9308][o342941q] config parse complete
[2021-12-24 13:35:43.249][Trace][9308][o342941q] you can check log by: tail -n 30 -f /gpstream/logs/srs-edge-0.log
[2021-12-24 13:35:43.249][Trace][9308][o342941q] please check SRS by: ./etc/init.d/srs status
[davis-debug][srs_app_config] max open files:1024
```

**期望行为(Expect)**

> 期望 ubuntu系统下，trunk/src/app/srs_app_config.cpp中检测max open files配置能正确（不论系统配置错与对，起码srs中两处调试信息反馈结果应该一致）。

**Comment by winlinvip** [comment]
Does it look okay?

`TRANS_BY_GPT3`

**Comment by dzhcool** [comment]
跟踪了下，是有问题的。
```
// st_srs/io.c  107行
    fdlim = (*_st_eventsys->fd_getlimit)();
    if (fdlim > 0 && rlim.rlim_max > (rlim_t) fdlim) {
        rlim.rlim_max = fdlim;
    }
```
初步排查 st_init 方法中 st_set_eventsys(ST_EVENTSYS_DEFAULT);
io.c 107行这个地方会获取到fdlim 1024，rlim.rlim_max是65535（同ulimit -n是一致的）
if 执行后，rlim.rlim_max就被修改为1024了

换成 st_init中换成 st_set_eventsys(ST_EVENTSYS_ALT);  ，强制使用epoll后
io.c 107行这个地方会获取到fdlim 0，rlim.rlim_max是65535（同ulimit -n是一致的）
最终 rlim.rlim_max 会保持65535

ubuntu修改ulimit：
''' /etc/security/limits.conf
```
*                soft    nofile          65535
*                hard    nofile          65535
*                soft    nproc           65535
*                hard    nproc           65535
root             soft    nofile          65535
root             hard    nofile          65535
root             soft    nproc           65535
root             hard    nproc           65535
```

''' /etc/sysctl.conf
```
fs.file-max = 65535
```
```
davis@ubuntu-node01:~$ cat /proc/sys/fs/file-max 
65535
```

/etc/systemd/system.conf
```
DefaultLimitNOFILE=65535
DefaultLimitNPROC=65535
```

/etc/systemd/user.conf
```
DefaultLimitNOFILE=65535
DefaultLimitNPROC=65535
```

ubuntu18.04重启过的，配置参数ulimit -a显示正常，/proc/sys/fs/file-max 也正常

**Comment by dzhcool** [comment]
@winlinvip 大佬，空了帮忙看下什么问题。感谢

**Comment by winlinvip** [comment]
`ST_EVENTSYS_DEFAULT` is SELECT, of course it is 1024.

This can basically be determined that the underlying system has not been modified, fd limitation is a very basic Linux feature, please double-check.

`TRANS_BY_GPT3`

**Comment by dzhcool** [comment]
已经搞明白了，编译参数的问题

st_srs Makefile 184行:
```
ifeq ($(OS), LINUX)
EXTRA_OBJS  = $(TARGETDIR)/md.o
SFLAGS      = -fPIC
LDFLAGS     = -shared -soname=$(SONAME) -lc
OTHER_FLAGS = -Wall
ifeq ($(shell test -f /usr/include/sys/epoll.h && echo yes), yes)
DEFINES     += -DMD_HAVE_EPOLL
endif
endif
```

ubuntu的sys头文件目录不一样，在： /usr/include/x86_64-linux-gnu/sys/epoll.h

所以编译srs时候没有检测出epoll支持，默认使用了select

如有其它使用ubuntu的用户，可以临时在安装脚本中做下 3rdparty/st-srs/Makefile 内容替换
```
sed -i "s@/usr/include/sys/@/usr/include/x86_64-linux-gnu/sys/@g" srs/trunk/3rdparty/st-srs/Makefile
```

st_srs Makefile也有修改fd_setsize编译参数说明
```
# Some platforms allow to define FD_SETSIZE (if select() is used), e.g.:
# DEFINES += -DFD_SETSIZE=4096
```

我使用的原版ubuntu，内核源码没调整过，fd_set部分  #define __FD_SETSIZE 1024

**Comment by winlinvip** [comment]
👍 Not bad, not bad. Found the reason, really not easy.

For the solution, it is better to proactively define this macro `MD_HAVE_EPOLL`. ST provides a method to set `EXTRA_FLAGS`, you can search for the variable `_ST_EXTRA_CFLAGS`.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I have updated it, please test version 4.0.213. Remember to delete the 'objs' folder and reconfigure.

`TRANS_BY_GPT3`
