### ISSUE TITLE
 RTC: Support iOS H5 Safari browser.

### ISSUE THREAD

**Issue by mc373906408** [ossrs/srs#2812]
**Description**

I am testing one-to-one video calls using the WebRTC method with the demo address. The PC's camera and microphone can always be played on the iOS Safari browser. However, the iOS device cannot send audio and video data to the PC, but text data can be transmitted normally.

1. SRS version: `4.0.206`

**Replay**

> Steps to reproduce the bug:

1. Enter a one-to-one video room on the PC.
2. Enter a one-to-one video room on the iOS device (same room number, audio and video permissions have been granted).

**Expected Behavior**

One-to-one video calls can be made on both the PC and iOS devices in Safari.

**Comment by winlinvip** [comment]
The priority of mobile H5 is relatively low because various mobile clients have various issues. Generally, mobile clients either use mini-programs or go with Native.

If everyone thinks this is very important, please submit a patch.
