### ISSUE TITLE
转推B站(Bilibili)：只有Params，空StreamName，导致SRS转推错误

### ISSUE THREAD

**Issue by Pixelw** [ossrs/srs#2813]
**描述(Description)**

> srs将stream name识别成param导致stream name为空

1. SRS版本(Version): `4.0-b1`

1. SRS的日志如下(Log):
```
[2021-12-24 16:47:10.939][Trace][1][0548dwv5] connected stream, tcUrl=rtmp://xxxx.com/live-rtc, pageUrl=, swfUrl=rtmp://xxxx.com/live-rtc, schema=rtmp, vhost=xxxx.com, port=1935, app=live-rtc, stream=, param=?myid=44455, args=null
[2021-12-24 16:47:10.939][Trace][1][0548dwv5] TCP: before dispose resource(RtmpConn)(0x1121250), conns=1, zombies=0, ign=0, inz=0, ind=0
[2021-12-24 16:47:10.939][Error][1][0548dwv5][11] serve error code=2051 : service cycle : rtmp: stream service : rtmp: empty stream
thread [1][0548dwv5]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:217][errno=11]
thread [1][0548dwv5]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:414][errno=11]
thread [1][0548dwv5]: stream_service_cycle() [src/app/srs_app_rtmp_conn.cpp:503][errno=11](Resource temporarily unavailable)
```

1. SRS的配置如下(Config):
```
 forward {
        enabled on;
        destination live-push.bilivideo.com:1935;
    }
```

**重现(Replay)**

使用obs推流 rtmp://xxxx.com/live-rtc
串流密钥:?myid=44455

**期望行为(Expect)**

这里真实情况是打算用srs转发流给B站，B站的url差不多是："rtmp://live-push.bilivideo.com/live-bvc/?streamname=xxxx&key=xxxxxx"，可以看到host后面只有一个live-bvc，我把host替换成自己的xxxx.com，推给srs，发现srs好像把live-bvc认作app, stream放空，然后问号后面都识别成param，然后报rtmp: empty stream。
我尝试过把live-rtc移到串流密钥，这时app变成默认值defaultApp，导致转发的url里多了一个defaultApp路径
怎样才能让srs正确识别然后转发给B站

**Comment by winlinvip** [comment]
This is because the Stream in the Bilibili URL is actually an empty string.

```
ffmpeg -re -i doc/source.flv -c copy \
  -f flv 'rtmp://live-push.bilivideo.com/live-bvc/?streamname=live_430256302_28738971&key=xxx'
```

Originally, the parameters follow the "?" in the URL. This is to maintain consistency with SRT format.

A workaround method is to use FFmpeg for re-streaming, for example:

```
ffmpeg -f flv -i 'rtmp://xxx' -c copy -f flv 'rtmp://yyy'
```

The empty stream name is not a typical scenario, but if you think it is important, you can submit a patch.

`TRANS_BY_GPT3`

**Comment by shugen002** [comment]
One possible solution is to duplicate the stream Name in front of the question mark in the parameters. That's roughly how you can push it to Bilibili.

rtmp://yourserver/live-bvc/xxx?streamname=xxx&key=yyy

I'm curious, what were you planning to do?
It is said that overseas anchors on Bilibili can now directly push Tencent Cloud after starting the live broadcast. If you click on the live broadcast, virtual anchors can report in advance and start it themselves, while others need assistance from people in China. Those who are powerful can directly be on the whitelist.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@shugen002, your plan is not feasible. Please verify it.

`TRANS_BY_GPT3`

**Comment by shugen002** [comment]
```
 forward {
        enabled on;
        destination live-push.bilivideo.com:1935;
 }
```
This configuration is still necessary.

If your original Bilibili streaming address is `rtmp://live-push.bilivideo.com/live-bvc/` and the streaming code is `?streamname=xxxxx&key=yyyyyy&schedule=rtmp&pflag=1`.

So what you need to fill in on the OBS side is...

`rtmp://yourservername/live-bvc`
`xxxxx?streamname=xxxxx&key=yyyyyy&schedule=rtmp&pflag=1`

I have tested it on my side and there are no issues.

Note: Remove the trailing slash from the streaming address. It should be `rtmp://yourservername/live-bvc` and not `rtmp://yourservername/live-bvc/`. I'm not sure why this slash is there... requesting an explanation from experts.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@shugen002 It seems like it's really possible. For example, the address for Bilibili live streaming is: 

* Server address: `rtmp://live-push.bilivideo.com/live-bvc/`
* Stream key: `?streamname=live_430256302_28738971&key=xxx&schedule=rtmp&pflag=1`

When streaming to SRS, the stream key should include the streamname. OBS configuration:

* Server address: `rtmp://live-push.bilivideo.com/live-bvc/`
* Stream key: `live_430256302_28738971?streamname=live_430256302_28738971&key=xxx&schedule=rtmp&pflag=1`

SRS configuration is the configuration for Forwarding, which needs to be specified as a domain name. @shugen002 has provided it above.

This is equivalent to FFmpeg streaming.

```
ffmpeg -re -i doc/source.flv -c copy -f flv 'rtmp://live-push.bilivideo.com/live-bvc/live_430256302_28738971?streamname=live_430256302_28738971&key=xxx&schedule=rtmp&pflag=1'
```

As for why slashes cannot be present, they should be allowed, right? It might be an issue with address parsing.

Thank you @shugen002 for providing the workaround.

`TRANS_BY_GPT3`

**Comment by shugen002** [comment]
Although it may not be quite appropriate here, I feel that the need to repost Bilibili content is somewhat similar to a workaround derived from #2676. Please allow me to remind about this here.
At the same time, I am considering another workaround, which is to use the ingest capability for reverse streaming, combined with callback API + raw API + n8n for automatic ingest switching.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@shugen002 Triggering your system to retweet through a callback is currently supported and is also a preferable method. However, the solution can be slightly modified: 

1. The client streams to SRS.
2. SRS notifies your system through a callback that a stream has been pushed.
3. Your system starts FFmpeg, pulls the stream from SRS, and retweets it to other platforms (additional operations such as adding watermarks or transcoding can also be performed before retweeting).

Here, do not use the RAW API because it has been removed. For more details, please refer to FAQ [#2716](https://github.com/ossrs/srs/issues/2716#http-raw-api).

`TRANS_BY_GPT3`

**Comment by Pixelw** [comment]
Thank you, I solved it the next day using a solution similar to nginx-rtmp and FFmpeg. The only thing I need to do is change the server host. It would be more convenient if SRS could be compatible with empty stream names.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If everyone wants to use this feature, please submit a pull request (PR).

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
5.0 fixed the issue of OBS without Stream, Bilibili without Stream should also be able to support it, refer to https://github.com/ossrs/srs/issues/3018

If there are any issues, please leave a comment.

`TRANS_BY_GPT3`
