### ISSUE TITLE
[wiki bug] cowoker没写端口

### ISSUE THREAD

**Issue by jinleileiking** [ossrs/srs#2825]
在k8swiki中：
```
            coworkers       srs-origin-0.socs srs-origin-1.socs srs-origin-2.socs;
```

这个应该是`     coworkers       srs-origin-0.socs:1985 srs-origin-1.socs:1985 srs-origin-2.socs:1985;`

这个没端口的配置， ffplay还是可以拉到的，为什么呢？我猜测是ffplay有重试机制，到好的pod，就拉到了。

但是会导致首屏慢

**Comment by winlinvip** [comment]
Fixed. Thanks @jinleileiking 👍
