### ISSUE TITLE
support origin-edge rtc playback structure

### ISSUE THREAD

**Issue by phusinh** [ossrs/srs#2826]
Does srs 5.0 support origin-edge rtc playback structure? Please introduce yourself the model. Thank you.

**Comment by winlinvip** [comment]
咨询和讨论请[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)在群里问， 还有每周六晚上20点直播答疑。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
For discussion or idea, please ask in [discord](https://discord.gg/yZ4BnPmHAd).

This issue will be eliminated, see #2716
