### ISSUE TITLE
GB28181: 删除通道，程序 crash

### ISSUE THREAD

**Issue by lauix** [ossrs/srs#2839]
Migrate to https://github.com/ossrs/srs-gb28181/issues/7

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/7

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
