### ISSUE TITLE
海康gb28181 有流，但是无法用vlc播放

### ISSUE THREAD

**Issue by fajieyefu** [ossrs/srs#2841]
Migrate to https://github.com/ossrs/srs-gb28181/issues/6

GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

**Comment by fajieyefu** [comment]
![1641289856578](https://user-images.githubusercontent.com/19398548/148041105-d855b2b7-3593-4f69-b944-a740c14b9230.jpg)

**Comment by fajieyefu** [comment]
There is a problem with the camera settings. Hikvision has many types, and there is no previous example corresponding to this model. It should be sufficient to remove the private information of the stream.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Migrate to https://github.com/ossrs/srs-gb28181/issues/6

GB has been moved to a separate repository [srs-gb28181](https://github.com/ossrs/srs-gb28181), please refer to #2845.
For any issues, please submit them to the GB repository [bug](https://github.com/ossrs/srs-gb28181/issues), or [pr](https://github.com/ossrs/srs-gb28181/pulls).
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
