### ISSUE TITLE
WebRTC: UDP/8000 check tool 检测UDP/8000是否可以访问的工具

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2843]
今天发现一个非常奇怪的问题，UDP/8000端口就是不通，安全组和侦听都没有问题，捣腾了半天还是给云服务商提工单排查了。

提工单过程中，发现要排查UDP端口是否通，是个比较麻烦的问题，不像TCP那样可以看22端口是否可以访问，一般没有一个通用的UDP服务器，所以也不好排查。

找了一些简单的UDP的服务器和客户端，可以跑在自己的服务器上，然后在客户端上测试下：

## Go

代码片段：[Gist](https://gist.github.com/winlinvip/e8665ba888e2fd489ccd5a449fadfa73)

启动服务器：

```
go run server.go
```

执行命令看下侦听是否正常：

```
netstat -lnptu | grep  8000
# udp    0    0 0.0.0.0:8000    0.0.0.0:*    1016220/server
```

执行nc命令，给服务器发送消息`Hello`，然后按`Enter`：

```
nc -u 127.0.0.1 8000
# Hello
# Pong: Hello
```

在本机运行客户端：

```
go run client.go
```

结果应该正常：

```bash
Ping: Hello, UDP server
Pong: Hello, UDP server
```

运行客户端，指定远程服务器：

```
go run client.go 101.20.7.11
```

下面是代码，防止大家访问不了gist。其他语言的欢迎补充。

## server.go

```go
/*
Usage:
	go run server.go
See https://gist.github.com/winlinvip/e8665ba888e2fd489ccd5a449fadfa73
 */
package main

import (
	"fmt"
	"net"
	"os"
)

func main() {
	addr := net.UDPAddr{
		Port: 8000,
		IP:   net.ParseIP("0.0.0.0"),
	}
	server, err := net.ListenUDP("udp4", &addr)
	if err != nil {
		fmt.Printf("Listen err %v\n", err)
		os.Exit(-1)
	}
	fmt.Printf("Listen at %v\n", addr.String())

	for {
		p := make([]byte, 1024)
		nn, raddr, err := server.ReadFromUDP(p)
		if err != nil {
			fmt.Printf("Read err  %v", err)
			continue
		}

		msg := p[:nn]
		fmt.Printf("Received %v %s\n", raddr, msg)

		go func(conn *net.UDPConn, raddr *net.UDPAddr, msg []byte) {
			_, err := conn.WriteToUDP([]byte(fmt.Sprintf("Pong: %s", msg)), raddr)
			if err != nil {
				fmt.Printf("Response err %v", err)
			}
		}(server, raddr, msg)
	}
}
```

## clieng.go

```go
/*
Usage:
	go run client.go
	go run client.go 101.201.7.12
See https://gist.github.com/winlinvip/e8665ba888e2fd489ccd5a449fadfa73
*/
package main

import (
	"fmt"
	"net"
	"os"
)

func main() {
	serverIP := "127.0.0.1"
	if len(os.Args) > 1 {
		serverIP = os.Args[1]
	}

	conn, err := net.Dial("udp", fmt.Sprintf("%v:8000", serverIP))
	if err != nil {
		fmt.Printf("Dial err %v", err)
		os.Exit(-1)
	}
	defer conn.Close()

	msg := "Hello, UDP server"
	fmt.Printf("Ping: %v\n", msg)
	if _, err = conn.Write([]byte(msg)); err != nil {
		fmt.Printf("Write err %v", err)
		os.Exit(-1)
	}

	p := make([]byte, 1024)
	nn, err := conn.Read(p)
	if err != nil {
		fmt.Printf("Read err %v\n", err)
		os.Exit(-1)
	}

	fmt.Printf("%v\n", string(p[:nn]))
}
```

**Comment by fandong1993** [comment]
Hello, author,

I have also confirmed that it is an issue with the upd8000 port. I would like to ask how you modified the udp port. I changed the host port to 18000, but the container's port remained as 8000. As a result, the rtc cannot play properly, and the playback address, whether it is webrtc://host/live/livestream or webrtc://host:18000/live/livestream, keeps spinning.

Thank you.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Currently, the host's port and the container's port are not supported to be different. You need to change the listening port of the container as well. Please refer to the WIKI for specific instructions.

`TRANS_BY_GPT3`

**Comment by fandong1993** [comment]
Hmm, I understand now. The ones inside the container also need to be modified...
Just as I opened my computer, I suddenly saw your reply. Thank you.

Wishing you a happy new year in advance.

`TRANS_BY_GPT3`

**Comment by sparkfax** [comment]
candidate 已设置为外网ip
启动后显示：
rtc listen at udp://0.0.0.0:8000, fd=11
UDP #11 LISTEN at 0.0.0.0:8000, SO_SNDBUF(default=212992, expect=10485760, actual=425984, r0=0), SO_RCVBUF(default=212992, expect=10485760, actual=425984, r0=0)
防火墙已经关闭，rtmp正常

nc -u 127.0.0.1 8000没有返回
