### ISSUE TITLE
GB28181: I'm thingking about saying goodbye，我在想是否不支持

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2845]
我们目前达成的一致是：要把GB的SIP支持从SRS中移除，只支持媒体处理部分。

我现在考虑的是：是否可以更进一步，完全不支持GB28181的接入。

原因有：

* 监控场景主要是RTSP，用FFmpeg拉RTSP后转RTMP推SRS，参考 [FAQ: RTSP](https://github.com/ossrs/srs/issues/2716#rtsp)
* GB场景很小，而且可以用其他的开源项目完成协议转换，比如 [ZLM](https://github.com/ZLMediaKit/ZLMediaKit)
* 就算SRS支持GB，也只支持GB的媒体部分，还需要花大量时间对接SIP项目，维护文档，以及后续的更新支持

目前我们的方向太多了，比如API完善、RTC的完善、QUIC、JS虚拟机、切片协议完善等等。

问了一圈，大家还是想继续支持，那就新建一个仓库吧，owner是 @xialixin @duiniuluantanqin 仓库地址 [ossrs/srs-gb28181](https://github.com/ossrs/srs-gb28181) 

GB独立发展，让子弹飞一会儿，搞不好飞得也挺好。

**Comment by 648540858** [comment]
Please keep the media section.

`TRANS_BY_GPT3`

**Comment by 1024mg** [comment]
Spend your energy in the direction you believe is right.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@1024mg Makes sense.

We initially thought that supporting surveillance was definitely the way to go because IoT's audio and video definitely need support. Later, we found that IoT's audio and video are still based on RTSP, which falls under the scope of FFmpeg pulling RTSP. After realizing this, we found that streaming can be supported by GB, but we didn't expect there to be so many challenges and so few applications (which also leads to few developers) and contributions.

These factors have resulted in a small number of SRS users who have raised most of the issues but are still unable to resolve them. Undoubtedly, this represents that something is not right. After thinking it over, it may be a matter of direction. Our main focus is not here.

`TRANS_BY_GPT3`

**Comment by zhOrange** [comment]
Do not forget the original intention. After clarifying the ultimate goal of the project, you will know what can be abandoned and what can be retained with limited resources.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Um, thank you everyone. Let's let everyone maintain it first, and after the maturity level is higher, we can merge it back into the main project.

`TRANS_BY_GPT3`

**Comment by hejinenPrivate** [comment]
May I ask if this new repository is migrated based on the SRS 4.0 version or the 5.0 version?

`TRANS_BY_GPT3`

**Comment by ghostsf** [comment]
Merging is a problem, huh.

`TRANS_BY_GPT3`
