### ISSUE TITLE
使用Nginx代理，开启http2.0后pageUrl为空

### ISSUE THREAD

**Issue by taofu328** [ossrs/srs#2846]
**描述(Description)**

> 之前一直使用Nginx代理来支持https，使用也正常。现在为了解决同源只能播放6路的问题，在nginx的listen后面加了http2，网页上播放的时候，srs的pageUrl就变成空了。

1. SRS版本(Version): `SRS/3.0.141(OuXuli)`

1. SRS的日志如下(Log):

未设置http2
```
[2022-01-05 09:47:36.409][Trace][1267][7927] HTTP client ip=127.0.0.1, request=0, to=15000ms
[2022-01-05 09:47:36.409][Trace][1267][7927] HTTP GET http://127.0.0.1:8006/live/10045.flv?user=10045, content-length=-1
[2022-01-05 09:47:36.411][Trace][1267][7927] http: on_play ok, client_id=7927, url=http://192.168.0.202:8001/pttauth/srs, request={"action":"on_play","client_id":7927,"ip":"127.0.0.1","vhost":"__defaultVhost__","app":"live","stream":"10045","param":"?user=10045","pageUrl":"https://ossrs.net/players/srs_player.html?app=live&stream=livestream.flv&server=d.ossrs.net&port=443&autostart=true&vhost=d.ossrs.net&schema=https"}, response=0
[2022-01-05 09:47:36.412][Trace][1267][7927] create consumer, active=0, queue_size=0.00, jitter=10000000
[2022-01-05 09:47:36.412][Trace][1267][7927] set fd=11 TCP_NODELAY 0=>1
[2022-01-05 09:47:36.412][Trace][1267][7927] set fd=11, SO_SNDBUF=2626560=>50000, buffer=100ms

```

设置了http2
```
[2022-01-05 09:27:43.780][Trace][1267][7926] HTTP client ip=127.0.0.1, request=0, to=15000ms
[2022-01-05 09:27:43.780][Trace][1267][7926] HTTP GET http://127.0.0.1:8006/live/10045.flv?user=10045, content-length=-1
[2022-01-05 09:27:43.783][Error][1267][7926][11] serve error code=3008 : mux serve : serve http : http hook : http on_play http://192.168.0.202:8001/pttauth/srs : http: on_play failed, client_id=7926, url=http://192.168.0.202:8001/pttauth/srs, request={"action":"on_play","client_id":7926,"ip":"127.0.0.1","vhost":"__defaultVhost__","app":"live","stream":"10045","param":"?user=10045","pageUrl":""}, response=1, status=200 : http: response number code 1
thread [1267][7926]: process_request() [src/app/srs_app_http_conn.cpp:162][errno=11]
```

3. SRS的配置如下(Config):

```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8006;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    gop_cache       off;
    queue_length    10;
    min_latency     on;
    mr {
        enabled     off;
    }
    mw_latency      100;
    tcp_nodelay     on;

 http_hooks {
        enabled         on;
        on_connect      http://192.168.0.202:8001/pttauth/srs;
        on_close        http://192.168.0.202:8001/pttauth/srs;
        on_publish      http://192.168.0.202:8001/pttauth/srs;
        on_unpublish    http://192.168.0.202:8001/pttauth/srs;
        on_play         http://192.168.0.202:8001/pttauth/srs;
        on_stop         http://192.168.0.202:8001/pttauth/srs;
        on_dvr          http://192.168.0.202:8001/pttauth/srs  http://127.0.0.1:8004/dvr;
    }

dvr {
    enabled         on;
    dvr_path        /usr/local/videorecord/[app]/[stream]/[2006]/[01]/[02]/[15][04][05][999].mp4;
    }

http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }
}

```
4.nginx代理的配置如下
nginx版本1.18
```
server {
        listen       8007 http2;
        server_name  localhost;
        ssl on;
        ssl_certificate    /usr/local/nginx/conf/192.168.0.203.cert.pem;
        ssl_certificate_key    /usr/local/nginx/conf/192.168.0.203.key.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;


          location / {
            root   html;
            index  index.html index.htm;
            proxy_pass http://127.0.0.1:8006/;
            #add_header Cache-COntrol no-cache;
            #add_header Access-Control-Allow-Origin *;
            #add_header 'Access-Control-Allow-Credentials' 'true';
            #add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Requested-With';
            #add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
        }
     }

```

**期望行为(Expect)**

> nginx里面 listen       8007 http2;这里如果没有http2就正常，有了http2就获取不到pageUrl.我需要通过pageUrl来鉴权，请问怎么才能又支持Http2又能正常获取pageUrl呢

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716

**Comment by winlinvip** [comment]
这是Nginx的问题，大兄弟。

**Comment by Zero-Qi** [comment]
> **描述(Description)**
> 
> > 之前一直使用Nginx代理来支持https，使用也正常。现在为了解决同源只能播放6路的问题，在nginx的listen后面加了http2，网页上播放的时候，srs的pageUrl就变成空了。
> 
> 1. SRS版本(Version): `SRS/3.0.141(OuXuli)`
> 2. SRS的日志如下(Log):
> 
> 未设置http2
> 
> ```
> [2022-01-05 09:47:36.409][Trace][1267][7927] HTTP client ip=127.0.0.1, request=0, to=15000ms
> [2022-01-05 09:47:36.409][Trace][1267][7927] HTTP GET http://127.0.0.1:8006/live/10045.flv?user=10045, content-length=-1
> [2022-01-05 09:47:36.411][Trace][1267][7927] http: on_play ok, client_id=7927, url=http://192.168.0.202:8001/pttauth/srs, request={"action":"on_play","client_id":7927,"ip":"127.0.0.1","vhost":"__defaultVhost__","app":"live","stream":"10045","param":"?user=10045","pageUrl":"https://ossrs.net/players/srs_player.html?app=live&stream=livestream.flv&server=d.ossrs.net&port=443&autostart=true&vhost=d.ossrs.net&schema=https"}, response=0
> [2022-01-05 09:47:36.412][Trace][1267][7927] create consumer, active=0, queue_size=0.00, jitter=10000000
> [2022-01-05 09:47:36.412][Trace][1267][7927] set fd=11 TCP_NODELAY 0=>1
> [2022-01-05 09:47:36.412][Trace][1267][7927] set fd=11, SO_SNDBUF=2626560=>50000, buffer=100ms
> ```
> 
> 设置了http2
> 
> ```
> [2022-01-05 09:27:43.780][Trace][1267][7926] HTTP client ip=127.0.0.1, request=0, to=15000ms
> [2022-01-05 09:27:43.780][Trace][1267][7926] HTTP GET http://127.0.0.1:8006/live/10045.flv?user=10045, content-length=-1
> [2022-01-05 09:27:43.783][Error][1267][7926][11] serve error code=3008 : mux serve : serve http : http hook : http on_play http://192.168.0.202:8001/pttauth/srs : http: on_play failed, client_id=7926, url=http://192.168.0.202:8001/pttauth/srs, request={"action":"on_play","client_id":7926,"ip":"127.0.0.1","vhost":"__defaultVhost__","app":"live","stream":"10045","param":"?user=10045","pageUrl":""}, response=1, status=200 : http: response number code 1
> thread [1267][7926]: process_request() [src/app/srs_app_http_conn.cpp:162][errno=11]
> ```
> 
> 3. SRS的配置如下(Config):
> 
> ```
> # main config for srs.
> # @see full.conf for detail config.
> 
> listen              1935;
> max_connections     1000;
> srs_log_tank        file;
> srs_log_file        ./objs/srs.log;
> http_api {
>     enabled         on;
>     listen          1985;
> }
> http_server {
>     enabled         on;
>     listen          8006;
>     dir             ./objs/nginx/html;
> }
> stats {
>     network         0;
>     disk            sda sdb xvda xvdb;
> }
> vhost __defaultVhost__ {
>     gop_cache       off;
>     queue_length    10;
>     min_latency     on;
>     mr {
>         enabled     off;
>     }
>     mw_latency      100;
>     tcp_nodelay     on;
> 
>  http_hooks {
>         enabled         on;
>         on_connect      http://192.168.0.202:8001/pttauth/srs;
>         on_close        http://192.168.0.202:8001/pttauth/srs;
>         on_publish      http://192.168.0.202:8001/pttauth/srs;
>         on_unpublish    http://192.168.0.202:8001/pttauth/srs;
>         on_play         http://192.168.0.202:8001/pttauth/srs;
>         on_stop         http://192.168.0.202:8001/pttauth/srs;
>         on_dvr          http://192.168.0.202:8001/pttauth/srs  http://127.0.0.1:8004/dvr;
>     }
> 
> dvr {
>     enabled         on;
>     dvr_path        /usr/local/videorecord/[app]/[stream]/[2006]/[01]/[02]/[15][04][05][999].mp4;
>     }
> 
> http_remux {
>         enabled     on;
>         mount       [vhost]/[app]/[stream].flv;
>         hstrs       on;
>     }
> }
> ```
> 
> 4.nginx代理的配置如下 nginx版本1.18
> 
> ```
> server {
>         listen       8007 http2;
>         server_name  localhost;
>         ssl on;
>         ssl_certificate    /usr/local/nginx/conf/192.168.0.203.cert.pem;
>         ssl_certificate_key    /usr/local/nginx/conf/192.168.0.203.key.pem;
>         ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>         ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
>         ssl_prefer_server_ciphers on;
>         ssl_session_cache shared:SSL:10m;
>         ssl_session_timeout 10m;
> 
> 
>           location / {
>             root   html;
>             index  index.html index.htm;
>             proxy_pass http://127.0.0.1:8006/;
>             #add_header Cache-COntrol no-cache;
>             #add_header Access-Control-Allow-Origin *;
>             #add_header 'Access-Control-Allow-Credentials' 'true';
>             #add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,X-Requested-With';
>             #add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
>         }
>      }
> ```
> 
> **期望行为(Expect)**
> 
> > nginx里面 listen       8007 http2;这里如果没有http2就正常，有了http2就获取不到pageUrl.我需要通过pageUrl来鉴权，请问怎么才能又支持Http2又能正常获取pageUrl呢

您好，现在解决了吗
