### ISSUE TITLE
edge集群支持热备吗？

### ISSUE THREAD

**Issue by godfery** [ossrs/srs#2849]
> 描述你遇到了什么问题(Please description your issue here)

我希望部署多台机器做edge，我看了所有文档，只看到edge可以reuse port，

> 描述你期望发生的事情(Please describe your expectation)

期望给指导一下如果设置edge热备，谢谢

**Comment by winlinvip** [comment]
咨询和讨论请来直播间交流，时间是每周六晚上20点，可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
