### ISSUE TITLE
关于流方向的咨询

### ISSUE THREAD

**Issue by suzaichuan** [ossrs/srs#2853]
hi all
       看了wiki，有点困惑非常关心一个问题就是流的方向；对于直播，我想没问题好理解，主播推流就好了；其他应用比如教育，需要和学生互动，这是流方向问题呢？
       rtmp 多人会议，是否每个用户都在推拉流？还是本身rtmp地址就是双向的？
对于同一个终端来说，本次通话推拉两个方向是否同一个rtmp地址？还是各自单独的呢？
       对应的流是否可以和音视频两路rtp转换？
      
       
BR

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room)交流，每周六晚上20点。也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
