### ISSUE TITLE
ffmpeg实时采集摄像头生成图片流推送SRS后用vlc播放延迟太大

### ISSUE THREAD

**Issue by cppmediaman** [ossrs/srs#2854]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.205`

2. SRS的配置如下(Config):
`
#main config for srs.
#@see full.conf for detail config.

listen              1935;
max_connections     1000;
#srs_log_tank        file;
#srs_log_file        ./objs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
    https {
        enabled off;
        listen 1988;
        key /opt/key/xidingcloud_key_file.key;
        cert /opt/key/xidingcloud_cert_file.crt;
    }
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
    https {
        enabled off;
        listen  8088;
        key /opt/key/xidingcloud_key_file.key;
        cert /opt/key/xidingcloud_cert_file.crt;
    }
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#config-candidate
    #candidate $CANDIDATE;
    candidate *;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtc-to-rtmp
        rtc_to_rtmp off;
    }
    dvr {
        enabled      on;
        dvr_path     ./objs/nginx/html/[app]/[stream].[timestamp].mp4;
        dvr_plan     session;
    }
}
`

3. 使用下面的ffmpeg命令行对实时rtsp流采集图片后将图片推成rtmp流到srs，然后用vlc播放观看，延迟很大有5，6秒。有没有办法降低延迟？用webrtc播放3秒
ffmpeg -rtsp_transport tcp -i rtsp://admin:a1234567@192.168.7.11/video1 -vf fps=24 -f image2pipe -c:v png - | ffmpeg -f image2pipe -i - -pix_fmt yuv420p -vcodec libx264 -f flv -y rtmp://localhost/live/stream

**Comment by winlinvip** [comment]
这个问题在[Wiki](https://github.com/ossrs/srs/wiki/v4_CN_Home)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716
