### ISSUE TITLE
dvr_apply无法控制录像开始和结束

### ISSUE THREAD

**Issue by ghostsf** [ossrs/srs#2861]
**描述(Description)**

dvr_apply无法控制录像开始和结束

dvr_apply 配置了某个流地址，只能设置起开始录像，结束录像还是在推流结束时触发。
dvr_apply 配置去掉该流地址，reload后，不会停止录像。

SRS版本(Version): 4.0.214

期望：
dvr_apply 可以实际控制录像的开始和结束，按需录像

**Comment by sureone** [comment]
可以增加一个模块copy dvr 的代码简单修改就可以实现按需录像的功能。

**Comment by winlinvip** [comment]
Dup to #1577

该Issue会被删除
