### ISSUE TITLE
推流返回

### ISSUE THREAD

**Issue by yuntiantec** [ossrs/srs#2877]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
推流api返回：angular.callbacks._u({"code":0,"server":"vid-48c88p2","urls":{"api":"the api root","rtc":{"v1":{"play":"Play stream","publish":"Publish stream","nack":"Simulate the NACK"}}}})
而正常的是
angular.callbacks._g({"code":0,"server":"vid-3jbnv4i","data":{"major":4,"minor":0,"revision":215,"version":"4.0.215"}})

1. SRS版本(Version): `4.0`

1. SRS的日志如下(Log):

```
xxxxxxxxxxxx
```

1. SRS的配置如下(Config):

```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
