### ISSUE TITLE
srs_string_split当分隔符是字串末尾时可能在返回的vector里面引入空的字符串

### ISSUE THREAD

**Issue by magicffourier** [ossrs/srs#2879]
**描述(Description)**

srs_string_split当分隔符是字串末尾时可能在返回的vector里面引入空的字符串
https://github.com/ossrs/srs/blob/c30aa479a76a78b8bd4ea7bceb2df6cf44aa0f23/trunk/src/kernel/srs_kernel_utility.cpp#L499

1. SRS版本(Version): `4.0release`

1. SRS的日志如下(Log):

```
无
```

1. SRS的配置如下(Config):

```
无
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. 使用srs_string_split分割字符串srs_string_split("a\nb\nc\nd\n", "\n")
2. 返回vector<string> {"a", "b", "c", "d", ""};

**期望行为(Expect)**

2. 返回vector<string> {"a", "b", "c", "d"};

**Comment by magicffourier** [comment]
Encountered pitfalls in the business, raise an issue to remind everyone not to step into the same pit TAT.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is compliant with the standards, for example, JS:

```
"a\nb\nc\nd\n".split("\n")
(5) ['a', 'b', 'c', 'd', '']

Make sure to maintain the markdown structure.
```

For example, Python:

Make sure to maintain the markdown structure.

```
>>> "a\nb\nc\nd\n".split("\n")
['a', 'b', 'c', 'd', '']
```

So when calling this API, you need to pay attention. 

Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`
