### ISSUE TITLE
ingest拉流采集增加http api接口

### ISSUE THREAD

**Issue by ghostsf** [ossrs/srs#2889]
**期望行为(Expect)**
ingest拉流采集增加http api接口

**Comment by winlinvip** [comment]
For consultation and discussion, please join the [video live room](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room) to communicate. It takes place every Saturday night at 20:00. You can also join the [WeChat group](https://github.com/ossrs/srs/wiki/Contact#wechat) for communication within the group.

This issue will be deleted, please read the FAQ first: #2716.

`TRANS_BY_GPT3`
