### ISSUE TITLE
开源复刻：内置WebRTC/FFmpeg/SRS源码的云开发环境

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2891]
> Note: 之前有个开源复刻[SRS云服务器](https://github.com/ossrs/srs/issues/2856)，它主要是提供开箱即用的云服务器，一般也不用来编译和修改代码，最多改改配置，需要比较好的管理后台。

由于音视频的代码庞大，WebRTC有GB级别的代码库（含依赖），FFmpeg也是百MB（含依赖），SRS也有百MB，就算放到Gitee上下载也需要挺长时间，而且还是共享的网络。有些依赖还没发直接下载，代码在国外，会超时或无法访问。

有人反馈说OBS的下载太慢，可以把安装包放进来。

所以我打算提供个云虚拟机带WebRTC/FFmpeg/SRS的开发环境，相关的依赖库和工具都带给大家，定期更新也可以手动更新，相关的依赖管理放在开源仓库，大家可以一起维护。

有需要的朋友请留言，如果需要的多了我就花时间搞，没人要就算了。

**Comment by aawl2001** [comment]
Very much needed, support to do it.

`TRANS_BY_GPT3`

**Comment by jinleileiking** [comment]
Not recommended, sooner or later you will need to access the internet scientifically.

`TRANS_BY_GPT3`

**Comment by mingyang0921** [comment]
anticipation

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS云服务器，1.0.40，支持了下载SRS的源代码，带git可以继续更新的。

介绍：[SRS云服务器：一键搞定流鉴权、公网IP和直播间](https://mp.weixin.qq.com/s/AKqVWIdk3SBD-6uiTMliyA)

教程：[SRS-029-内置SRS的云服务器](https://www.bilibili.com/video/BV1844y1L7dL/)

**Comment by TIRAMISU52N** [comment]
> SRS云服务器，1.0.40，支持下载SRS的源代码，带git可以继续更新。>>！[肖像]（https://user-images.githubusercontent.com/2777660/151380042-bea7e81a-b002-4b6d-a411-d79cb4c87fc8.png）>>介绍：[SRS云服务器：一键搞定流鉴权、公网IP和直播间]（https://mp.weixin.qq.com/s/AKqVWIdk3SBD-6uiTMliyA）>>教程：[SRS-029-内置SRS的云服务器]（https://www.bilibili.com/video/BV1844y1L7dL/）宝塔中的源码按钮不能下载不知为何。

**Comment by winlinvip** [comment]
Won't support.
