### ISSUE TITLE
 extend the input payload forward 

### ISSUE THREAD

**Issue by windwind1** [ossrs/srs#2892]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
I want to expand the forward model to withstand more input loads. According to the publisher's description, forward cannot use cdn, so a large number of incoming streams is impossible. So is there any way to make it work? does forward take more input load.Thanks

1. SRS版本(Version): `xxxxxx`

1. SRS的日志如下(Log):

```
xxxxxxxxxxxx
```

1. SRS的配置如下(Config):

```
xxxxxxxxxxxx
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

**Comment by windwind1** [comment]
Is there any way to extend forward's input payload

**Comment by winlinvip** [comment]
For serving a large amount of publishers or streams, you should use origin cluster, please read the wiki about it.

**Comment by winlinvip** [comment]
For discussion or idea, please ask in [discord](https://discord.gg/yZ4BnPmHAd).

This issue will be eliminated, see #2716
