### ISSUE TITLE
SRT支持多QueryString，传递到RTMP，实现鉴权等能力

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2893]
SRT没有定义QuerySring，所以转到RTMP会有问题，鉴权就无法做。

<a name="usage"></a>
## [Usage](#usage)

OBS推流地址：

* RTMP: `rtmp://127.0.0.1/live/livestream?key1=value1&key2=value2`
* SRT: `srt://127.0.0.1:10080?streamid=#!::r=live/livestream,key1=value1,key2=value2,m=publish`

带VHOST参数：

* RTMP: `rtmp://127.0.0.1/live/livestream?vhost=host.com&key1=value1&key2=value2`
* SRT: `srt://127.0.0.1:10080?streamid=#!::h=host.com,r=live/livestream,key1=value1,key2=value2,m=publish`

FFPLAY播放地址：

* RTMP: `rtmp://127.0.0.1/live/livestream?key1=value1&key2=value2`
* SRT: `srt://127.0.0.1:10080?streamid=#!::r=live/livestream,key1=value1,key2=value2,m=request`

带鉴权信息：

* RTMP: `rtmp://127.0.0.1/live/livestream?secret=xxx`
* SRT: `srt://127.0.0.1:10080?streamid=#!::r=live/livestream,secret=xxx,m=publish`

<a name="solution"></a>
## [Solution](#solution)

若使用域名(domain/vhost)推拉流，一般RTMP和SRT的对应关系：

* RTMP: `rtmp://host.com/app/stream?key1=value1&key2=value2`
* SRT: `srt://host.com:10080?streamid=#!::h=host.com,r=app/stream,key1=value1,key2=value2`

也可以直接用IP，指定域名推拉流：

* RTMP: `rtmp://1.2.3.4/app/stream?vhost=host.com&key1=value1&key2=value2`
* SRT: `srt://1.2.3.4:10080?streamid=#!::h=host.com,r=app/stream,key1=value1,key2=value2`

SRS有时候（很多时候）是没有域名(domain/vhost)，直接使用IP推拉流，这时：

* RTMP地址：`rtmp://1.2.3.4/app/stream?key1=value1&key2=value2`
* SRT地址：`srt://1.2.3.4:10080?streamid=#!::r=app/stream,key1=value1,key2=value2`

关键的几点：
1. SRT URL中不能出现`&`, 否则会被ffmpeg, obs当做srt参数关键字拆分,丢失输入的参数
2. SRT需要再输入一次`h=hostname`, 附带在`streamid`中, rtmp不需要,因为rtmp会把`hostname`附带在`tcUrl`中,而srt需要手动指定,用来区分业务域名.
3. `m=request|publish`，代表拉流或推流，默认是拉流。

> Note: SRS也可以支持多端口，不同的端口默认`m`的值不同，这样可以实现不需要指定`m`，在广电系统端口富余但url需要简单的场景有效。而在互联网中，一般端口收到防火墙或安全组的限制，尽量少开端口，而url中可以多指定信息。

关于h和r的定义，参考[SRT: Standard Keys](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md#standard-keys)：

- `r`: **Resource Name** identifies the name of the resource and facilitates
selection should the listener party be able to serve multiple resources.
- `h`: **Host Name** identifies the hostname of the resource. For example,
to request a stream with the URI `somehost.com/videos/querry.php?vid=366` the `hostname` field should have `somehost.com`, and the resource name can have `videos/querry.php?vid=366` or simply `366`. Note that this is still a key to be specified explicitly. Support tools that apply simplifications and URI extraction are expected to insert only the host portion of the URI here.
- `m`: **Mode** expected for this connection:
  - `request` (default): the caller wants to receive the stream
  - `publish`: the caller wants to send the stream data
  - `bidirectional`:  bidirectional data exchange is expected

参考文档：

* [SRT官方定义的URL](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md)
* [SRS SRT wiki](https://github.com/ossrs/srs/wiki/v4_CN_SRTURL)
* [腾讯云SRT](https://cloud.tencent.com/document/product/267/53955)

> PS: B站的url不具备参考性, B站的url本身stream是空的，`?streamname=live_430256302_28738971`, 也就是说, 这串东西对应rtmp的stream。

<a name='compatible'></a>
## [Compatible](#compatible)

之前定义的老的URL格式，主要是`h`中加了流信息，目前还能兼容，但是未来会删除，请不要使用。

基于srt官网的文章：[AccessControl](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md)

最新的srt推流地址规范修改为：
### URL for defaultVhost
<pre>
# https://github.com/Haivision/srt/blob/master/docs/AccessControl.md
# Publish stream by SRT:
#               srt://127.0.0.1:10080?streamid=#!::h=live/livestream,m=publish
# Play stream by SRT
#               srt://127.0.0.1:10080?streamid=#!::h=live/livestream,m=request
# Play stream by RTMP:
#               rtmp://127.0.0.1/live/livestream
</pre>
### URL for vhost
<pre>
# To use vhost in SRS.
# Publish stream by SRT:
#               srt://127.0.0.1:10080?streamid=#!::h=srs.srt.com.cn/live/livestream,m=publish
# Play stream by SRT:
#               srt://127.0.0.1:10080?streamid=#!::h=srs.srt.com.cn/live/livestream,m=request
# Play stream by RTMP:
#               rtmp://127.0.0.1/live/livestream?vhost=srs.srt.com.cn
</pre>

基于srt官网，streamid的格式有Standard Keys，srt in srs的服务尽量符合官网标准。<br/>
<pre>
The Stream ID value can be used as free-form, but there is a recommended convention so that all SRT users speak the same language. The intent of the convention is to:
1. promote readability and consistency among free-form names
2. interpret some typical data in the key-value style
</pre>
符合yaml格式，以#!::为开始。
key为h，表示vhost和appname/stream；
key为m，表示推流(publish)/拉流(request)；

**Comment by zhouxiaojun2008** [comment]
可以参考http://ffmpeg.org/ffmpeg-all.html#srt 的定义，采用如下格式：
srt://10.10.0.62:10080?streamid=#!::m=publish,h=live.test.com/live/livestream?txSecret=7bbbbeef298adf383671f786d3ceb0ed#txTime=611FC59C#token=1212121&latency=50000
可以支持附加参数  用&连接各个参数，注意streamid后面的字符串不能超过512个字符（libsrt库底层限制）

**Comment by zhouxiaojun2008** [comment]
srt://127.0.0.1:10080?streamid=#!::h=live/livestream?secret=xxx&token=yyy,m=publish'，In software based on libavformat implementation, the parameters after '&' will be ignored by ffmpeg. The streamid passed out will be truncated to '#!::h=live/livestream?secret=xxx'.

参考如下设计是否可行'

Please let me know the specific design you are referring to so that I can provide an accurate translation.

1. With one parameter:
    SRT: 'srt://127.0.0.1:10080?streamid=#!::h=live/livestream,secret=xxx,m=publish'
    RTMP: rtmp://127.0.0.1/live/livestream?secret=xxx
2. With multiple parameters
    SRT: 'srt://127.0.0.1:10080?streamid=#!::h=live/livestream,secret=xxx,token=yyy,m=publish'
    RTMP: rtmp://127.0.0.1/live/livestream?secret=xxx&token=yyy
This type of single-letter format like 'h' and 'm' belongs to Standard Keys according to the [official srt documentation](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md). They cannot be customized for use. On the other hand, 'secret' and 'token' are custom keys. The value after 'streamid' will be passed to the other end during the srt handshake. Additionally, tools like ffmpeg support other parameters that can be connected using '&', but they can only be used locally in ffmpeg. For reference on the ffmpeg srt URL format, you can visit [ffmpeg srt URL format](http://ffmpeg.org/ffmpeg-all.html#srt). Using the mentioned format will not conflict with the av_find_info_tag parsing function in ffmpeg and is fully compliant with the official srt definition.

3. [Tencent srt URL definition](https://cloud.tencent.com/document/product/267/53955)
    
4. "In addition, since the secret is within the stream and livestream is a string, it requires the playback to also include the secret. This makes it impossible to authenticate only the push stream without authenticating the pull stream, and it also makes it impossible to use different secrets (or tokens) for push and playback." This means that all parameters are placed within the stream.

    

`TRANS_BY_GPT3`

**Comment by zhouxiaojun2008** [comment]
老大这句话能否没太看懂，“另外，由于secret是在流中的，和livestream是一个字符串，所以导致播放也必须是带secret，这就无法实现只鉴权推流不鉴权拉流，也无法实现推流和播放使用不同的secret（或者token）。”
secret等等参数在srt2rtmp的时候，会当成param啊，参考如下输出：
“connected stream, tcUrl=rtmp://127.0.0.1/live, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=1935, app=live, stream=livestream, param=?secret=xxx&vhost=127.0.0.1, args=(obj)”。
如果拉流不需要鉴权的话，这种请求rtmp://127.0.0.1/live/livestream，也可以拉取到流播放啊
需要鉴权的话，url自己携带参数即可

**Comment by winlinvip** [comment]
The parameters of RTMP must all be placed in the stream, not in the app.

Originally, Adobe placed them in the app, but this looks messy.

```
rtmp://127.0.0.1/live?secret=xxx&token=yyy?vhost=live.test.com/livestream
```

It's better to place them naturally in the stream.

```
rtmp://127.0.0.1/live/livestream?secret=xxx&token=yyy?vhost=live.test.com
```

Therefore, the parameters of RTMP must not be placed in the app anymore. SRS supports placing them in the app for compatibility purposes, but the new ones cannot be placed here anymore.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
After checking the current URL formats of Tencent and Bilibili, it seems that they are different from what we have defined.

Tencent:

```
srt://${rtmp-push-domain}:9000?streamid=#!::h=${rtmp-push-domain},r=${app}/${stream},txSecret=${txSecret},txTime=${txTime}
```

Bilibili:
```
Server address:
srt://live-push.bilivideo.com:1937?streamid=#!::h=live-push.bilivideo.com,r=live-bvc/?streamname=live_430256302_28738971,key=ad890c602709895446f8fb994a01393b,schedule=srtts,pflag=1

Stream key:
?streamname=live_430256302_28738971&key=ad890c602709895446f8fb994a01393b
```

Please make sure to determine which URL format to use and finalize the conclusion in the document. Otherwise, readers will be confused, users won't know how to use it, and the code will need to be constantly modified.

We should prioritize the documentation. The document should be finalized before working on the code. The code is ultimately meant for the users, and if we ourselves don't understand it, how can we expect the users to know how to use it?

In addition, the previous relevant documents need to be updated. Documentation is more important than code. If the documentation is not updated, even if the code is updated, it will be useless. No one will go through the code in detail just to understand how to use it.

Please everyone, first put your thoughts into a document and write them in the comments of this PR. Then I will schedule a Tencent meeting to finalize a time. Once we have confirmed, I will share it in the SRT group for others to review and see if there are any additions.

I would like to propose a few objectives:

1. Both streaming and playback require support for multiple parameters. There is no need to specifically consider the case of a single parameter, as the URL format for both single and multiple parameters remains the same.
2. Streaming and playback should not use the same secret. In other words, the authentication for playback must be different from that of streaming. Otherwise, if someone knows how to play the stream, they will also have streaming permissions, which is completely unacceptable.
3. Adapt to open-source industry standards as much as possible, and prioritize compatibility with established commercial standards. Our previous definitions should only be considered if they are appropriate. Otherwise, they should be modified accordingly.

Please everyone, first share your thoughts so that we can reach a consensus on this.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
我想提几个目标：

1. 推流拉流，都需要支持多个参数。不需要特别考虑一个参数的情况，一个参数和多个参数的URL格式是一样的。
2. 推流拉流不能使用同样的secret，或者说播放的鉴权一定要和推流不一样，不然知道播放的人就有了推流权限，这完全不行。
3. 适配开源的事实标准，尽量适配线上的商业标准，最后才是兼容我们之前的定义。或者说，如果我们的定义不合适，那就改吧。

请大家先把自己的想法给出来吧，这个需要先达成一致。

**Comment by xiaozhihong** [comment]
rtmp url示例

https://cloud.tencent.com/document/product/267/53955
https://github.com/ossrs/srs/wiki/v4_CN_SRTURL
https://github.com/Haivision/srt/blob/master/docs/features/access-control.md

**Comment by xiaozhihong** [comment]
> 看了下目前腾讯和B站的URL格式，好像和我们定义不太一样。
> 
> 腾讯：
> 
> ```
> srt://${rtmp-push-domain}:9000?streamid=#!::h=${rtmp-push-domain},r=${app}/${stream},txSecret=${txSecret},txTime=${txTime}
> ```
> 
> B站：
> 
> ```
> 服务器地址：
> srt://live-push.bilivideo.com:1937?streamid=#!::h=live-push.bilivideo.com,r=live-bvc/?streamname=live_430256302_28738971,key=ad890c602709895446f8fb994a01393b,schedule=srtts,pflag=1
> 
> 流密钥：
> ?streamname=live_430256302_28738971&key=ad890c602709895446f8fb994a01393b
> ```
> 
> 请大家先确定了，到底用哪个URL的格式，要把最终结论确定下来，落到文档。不然看的人一脸懵逼，用户也不知道怎么使用，代码又需要改来改去的。
> 
> 要重视文档，文档先定了，再搞代码。代码最终是要给用户用的，如果我们自己都没弄明白，怎么可能用户知道怎么用呢。
> 
> 另外，之前的相关文档都需要更新，文档比代码更重要，如果文档没有更新，代码更新了也没有用，没有人会详细看一遍代码后，才能知道怎么用。
> 
> 请大家先把自己的想法形成文档，写到这个PR的评论中，然后我发起个腾讯会议，约个时间敲定下来把。等我们确定后，我发SRT群里，让其他人看看，看有没有补充的。

B站的url不具备参考性, B站的url本身stream是空的
?streamname=live_430256302_28738971, 也就是说, 这串东西对应rtmp的stream

**Comment by winlinvip** [comment]
Thanks @xiaozhihong @zhouxiaojun2008
