### ISSUE TITLE
SRT：推到RTMP出现错误时，不会停止SRT推流

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#2897]
SRT推流时，会转成RTMP推给后端，如果后端有鉴权可能会导致RTMP失败，此时SRT并不会断开而是一直重试。

这时候就完全不知道发生什么，只知道推SRT没有失败，但是无法播放RTMP流，可以播放SRT流。

同时这也是一个漏洞，相当于鉴权无效，因为可以播SRT，只是播放不了RTMP而已。

因此，当RTMP失败时，SRT也必须失败；或者单独实现鉴权和回调。

**Comment by zhouxiaojun2008** [comment]
The 'srt' data is received and pushed into a queue by the 'srt_server' thread. The 'srt2rtmp' coroutine retrieves data from the queue. The entire process involves one-way data flow.

When there is an error in the 'rtmp' interaction, only the 'rtmp' session can be closed. The error information cannot be passed to the 'srt_server' thread, and it is not possible to directly call the 'srt_server' interface to close the 'srt' session, which is not easy to handle.

There is a solution to consider implementing separate authentication using 'srt'. Of course, it is not possible to use 'st' to implement an HTTP client. Instead, the [cpp-httplib](https://github.com/yhirose/cpp-httplib/) library can be used. This library consists of only one '.h' file, and it may be feasible in terms of copyright.


`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Discussed and decided to use global variables with locks to store the error. After replacing the IO with ST driver, we can use it without locking.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS 4.0
