### ISSUE TITLE
About webrtc player

### ISSUE THREAD

**Issue by alnux** [ossrs/srs#2898]
Hi, I'm new with SRS, i have a question 

1.- does SRS suport webrtc 1 to n stream?? Like ovenmediaengine.

Obs->rtmp->SRS->webrtc->player->n users seen

2.- if yes to 1, witch player can i use with SRS webrtc? Ovenmediaengine has their own player ovenplayer.

Note: i read that there Is a H5 player but the link Is corrupted.

Really thanks

**Comment by winlinvip** [comment]
For discussion or idea, please ask in [discord](https://discord.gg/yZ4BnPmHAd).

This issue will be eliminated, see #2716
