### ISSUE TITLE
srs显示连接客户端数量不对

### ISSUE THREAD

**Issue by xsmyqf** [ossrs/srs#2903]
**描述(Description)**

> 向srs推流，使用一个客户端拉流，此时短时间内断开并重新推流，会显示客户端数量不一致。

**重现(Replay)**

1. 向srs推流，使用vlc拉流播放，此时srs显示有两个客户端
2. 短时间内，断开推流，再重新推流
3. 拉流的客户端接着播放，但是此时srs显示只有一个客户端

**期望行为(Expect)**

> 拉流的客户端接着播放，那我认为它依旧在拉流，那它应该保持跟前面一致，此时srs应该显示连接的客户端是两个。

**Comment by winlinvip** [comment]
Fixed.
