### ISSUE TITLE
nvdia硬编码 webrtc推流异常

### ISSUE THREAD

**Issue by yjjgithub** [ossrs/srs#2904]
描述(Description)

英伟达平台通过webrtc 向srs推流，srs配置是rtc2rtmp.conf  发现nvdia硬编码的情况下，通过自带的rtc播放器无法拉取webrtc码流，nvdia软编码的情况下， 自带的rtc播放器可以拉取webrtc的流， 不管是硬编还是软编   都可以转出rtmp的码流进行拉取播放。

重现(Replay)
nvdia硬编码情况下推流情况：

![前端播放拉流失败](https://user-images.githubusercontent.com/20619686/152895021-e1458b9c-7b00-4b45-a462-284c4e6fb14a.jpg)
srs响应的sdp描述：
![9df55430bbbac90003691bbee7dc71c](https://user-images.githubusercontent.com/20619686/152895491-89e31fa7-f925-4a1f-9bda-3d1ef493f4f7.jpg)

软编码推流情况：
![image](https://user-images.githubusercontent.com/20619686/152895117-b7261349-2008-43a5-a6ff-a90ca6d8a5c8.png)

期望行为(Expect)
期望nvdia webrtc客户端不管是软编还是硬编码流推到srs上 都可以正常被srs的rtc客户端拉取并播放

我知道肯定是nvdia硬编码和软编码情况下的sdp描述符的问题  但是不清楚原因  以及解决方案，因为srs都可以正常把webrtc的流转为rtmp的流 只是srs自带的播放器无法拉取硬编码情况下的webrtc流，希望可以请教

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
