### ISSUE TITLE
http/2无法跨域

### ISSUE THREAD

**Issue by bruce1110** [ossrs/srs#2905]
使用http/2时，请求头未处理大小写，导致cors err，这个头在http/2中为origin
<img width="519" alt="image" src="https://user-images.githubusercontent.com/12758090/153115290-04336489-087d-4601-a0d1-5b3af977ef77.png">

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
