### ISSUE TITLE
SrsEdgeStateIngestStopping状态保持过久问题，导致新播放端播放失败

### ISSUE THREAD

**Issue by mingyang0921** [ossrs/srs#2911]
**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
当客户端播放流断开时，如果edge只有这一个consumer,会进行销毁SrsEdgeIngester::stop，
但是trd->stop();会跳出协程，耗时平均2~3秒，这时候如果有新的客户端进行播放，判断状态是SrsEdgeStateIngestStopping
会直接退出。导致播放失败，当超过3秒后，ingster销毁完成，重新赋值state = SrsEdgeStateInit;播放即可

1. SRS版本(Version): `4.0.240`

1. SRS的日志如下(Log):

-----------------------------新播放端日志
[2022-02-11 15:49:29.319][Error][156310][pljn64or][11] serve error code=2020 : service cycle : rtmp: stream service : rtmp: create consumer : play edge : state is stopping
thread [156310][pljn64or]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:217][errno=11]
thread [156310][pljn64or]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:414][errno=11]
thread [156310][pljn64or]: playing() [src/app/srs_app_rtmp_conn.cpp:659][errno=11]
thread [156310][pljn64or]: create_consumer() [src/app/srs_app_source.cpp:2583][errno=11]
thread [156310][pljn64or]: on_client_play() [src/app/srs_app_edge.cpp:676][errno=11](Resource temporarily unavailable)

-------------------------------------------测试耗时代码

void SrsEdgeIngester::stop()
{   
        srs_warn("EdgeIngester: stop start. ");
    trd->stop();
        srs_warn("EdgeIngester: stop end. ");
    upstream->close();
    
    // notice to unpublish.
    if (source) {
        source->on_unpublish();
    }
}
---------------------------------耗时代码日志

[2022-02-11 15:49:28.519][Warn][156310][37109828][32] EdgeIngester: stop start. 
[2022-02-11 15:49:31.519][Warn][156310][37109828][11] EdgeIngester: stop end. 

1. SRS的配置如下(Config):

```
listen              2937;
max_connections     1000;
pid                 objs/edge.pid;
daemon              off;#on;#off;
srs_log_tank        console;#file;#console;
vhost __defaultVhost__ {
    cluster {
        mode            remote;
        origin          10.31.31.37:2937;
    }
}
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1、srs edge,srs code, srs origin,
2、obs推流推流到orgin
3、播放器连接edge,edge ingester from core,出图像后，关闭播放器。
4、在三秒内，迅速重新播放流，这时候播放器显示 rtmp://*:2937/live/12345: I/O errorB sq=    0B f=0/0
5、edge显示: play edge : state is stopping

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
1、期望解决3秒内重新播放，失败问题。

自己考虑解决办法：
1、state  由 SrsEdgeStateIngestStopping 改为两个状态 SrsEdgeStateIngestStopping_th , SrsEdgeStateIngestStopping_source，
准确来确认是在关闭协程还是资源销毁。
2、按照不同的状态，判断是否还继续销毁资源
3、如果新播放端发现状态是SrsEdgeStateIngestStopping_th ，可以创建一个新的协程。同时修改状态。
这样上个协程可以跳过SrsEdgeStateIngestStopping_source状态

**Comment by winlinvip** [comment]
Dup to #2901

重复问题，该Issue会被删除
