### ISSUE TITLE
推流后以.m3u8打开链接无法播放

### ISSUE THREAD

**Issue by moeik** [ossrs/srs#2930]
以docker运行

docker pull ossrs/srs:latest

应该是4.0.x的版本

推流后打开.m3u8链接无法观看到，要加上?hls_ctx=xxx（xxx任意字段均可）才能播放，
之前部署的另一台在3.0版本中不存在这个问题

启动命令:
`docker run --name srs --restart=unless-stopped -d -it --net web -p 1935:1935 -p 1985:1985 ossrs/srs ./objs/srs -c conf/https.docker.conf`
srs配置文件未更改，前端使用nginx进行反向代理

请问如何解决？能否在配置文件参数中关闭这个hls_ctx校验？

**Comment by winlinvip** [comment]
这根本就不是个问题。

你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by peipeiguo** [comment]
see pr #3067
