### ISSUE TITLE
output rtmp & flv & hls ? h265

### ISSUE THREAD

**Issue by goliveok** [ossrs/srs#2933]
我需要幫助將 h265 輸出 hls 和 flv 運行到 vlc 或 ffpaly 

s1:
./objs/srs -c conf/srs.conf

s2:
./ffmpeg -i http://host:port/streamH265 -c copy -f flv rtmp://localhost/live/livestream

ffmpeg-h265 不錯 

`    Stream #0:0[0x100]: Video: hevc (Main) ([36][0][0][0] / 0x0024), yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 96 kb/s
`

rtmp h265 和 flv 沒有響應並且流式傳輸沒有圖片的音頻 

我的配置 

`listen              1935;
max_connections     1000;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    candidate $CANDIDATE;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtmp-to-rtc
        rtmp_to_rtc off;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtc-to-rtmp
        rtc_to_rtmp off;
    }
}`

**Comment by goliveok** [comment]
Is my problem difficult?

**Comment by winlinvip** [comment]
Please ask question in English, never translate it by tools. Please update your question.

Thanks.
