### ISSUE TITLE
那么，这个问题最后解决了吗？路由器整了一天，哈哈哈

### ISSUE THREAD

**Issue by XJISHANDSOME** [ossrs/srs#2934]
我猜可能的原因是端口问题,尽量所有的端口都跟暴露的一样,
也可能出在了防火墙那里
还有可能是udp与tcp的问题
我没有解决这个问题

At 2021-12-18 10:04:43, "iauhsil" ***@***.***> wrote:

@cfeigithub

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you were mentioned.Message ID: ***@***.***>

_Originally posted by @cfeigithub in https://github.com/ossrs/srs/issues/2773#issuecomment-997617327_

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
