### ISSUE TITLE
SRT: error in libsrt build options

### ISSUE THREAD

**Issue by everything411** [ossrs/srs#2936]
https://github.com/ossrs/srs/blob/4b838659e962780595cd62992a96c1fcd0d51b0a/trunk/auto/depends.sh#L815
禁用apps的正确选项是--enable-apps=0，而--disable-app选项无效。
此前表现正常是因为--enable-c++11=0在libsrt内部设置了ENABLE_APPS=0，禁用了apps

**Comment by winlinvip** [comment]
👍

**Comment by zhouxiaojun2008** [comment]
--disable-app' option is equivalent to '--enable-app=0'.
https://github.com/ossrs/srs/blob/95bbb5a0c3493df1a6cf897b55dc77232b910a24/trunk/3rdparty/srt-1-fit/configure#L35
app is written in C++11, so removing app also disables the compilation of libsrt with C++11. No problem at all.

`TRANS_BY_GPT3`

**Comment by everything411** [comment]
> The --disable-app option is equivalent to --enable-app=0
> 
> https://github.com/ossrs/srs/blob/95bbb5a0c3493df1a6cf897b55dc77232b910a24/trunk/3rdparty/srt-1-fit/configure#L35
> 
> 
> The app is written in C++11, so removing the app also disables the compilation of libsrt with C++11. No problem at all.

The correct option is --enable-apps=0 or --disable-apps. The original option was misspelled, missing an 's', which made the option invalid. The original option was able to successfully disable apps due to the side effect of disabling C++11 compilation, so it should still be modified for the better.

https://github.com/ossrs/srs/blob/95bbb5a0c3493df1a6cf897b55dc77232b910a24/trunk/3rdparty/srt-1-fit/CMakeLists.txt#L864

`TRANS_BY_GPT3`

**Comment by zhouxiaojun2008** [comment]
> > The option --disable-app is equivalent to --enable-app=0.
> > https://github.com/ossrs/srs/blob/95bbb5a0c3493df1a6cf897b55dc77232b910a24/trunk/3rdparty/srt-1-fit/configure#L35
> > 
> > The app is written in C++11, so removing the app also disables the compilation of libsrt with C++11. There is no problem with that.
> 
> The correct options are --enable-apps=0 or --disable-apps. The original option was misspelled, which made it ineffective. The original option was able to successfully disable apps due to the side effect of disabling compilation with C++11. Therefore, it should still be modified for the better.
> 
> https://github.com/ossrs/srs/blob/95bbb5a0c3493df1a6cf897b55dc77232b910a24/trunk/3rdparty/srt-1-fit/CMakeLists.txt#L864

Sorry, my mistake. Can I submit a pull request?

`TRANS_BY_GPT3`
