### ISSUE TITLE
WebRTC: 回调踢流，cpu一直处于98%的状态

### ISSUE THREAD

**Issue by LUOQING1994** [ossrs/srs#2937]
**描述(Description)**

> 描述你遇到了什么问题

用户点播视频，PC端使用WebRtc播放，当用户关闭视频后，云服务器利用回调函数，主动踢掉用户播放的视频流，该过程进行十几次后，云服务器的CPU一直处于98%的状态，即使没有任何推流操作，cpu也无法得到释放。

1. SRS版本(Version): `v 4.0.198`

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `本地推流到SRS云服务器`
2. `PC端成功播放视频后，主动关闭视频，云服务器使用回调函数，进行主动踢流`
3. `重复十几次后，CPU处于98%的状态`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)

频繁推流、拉流、踢流后，cpu处于正常状态

**Comment by winlinvip** [comment]
感谢反馈，麻烦试试最新的 4.0 版本是否能重现这个问题。

**Comment by winlinvip** [comment]
Can't replay.
