### ISSUE TITLE
整理rtcp的nack包的代码是否出现了遗漏

### ISSUE THREAD

**Issue by Lei-Xiangyu** [ossrs/srs#2959]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**在一个nack包pid后第一个超出blp范围的包是否遗漏？**

> 描述你遇到了什么问题(Please description your issue here)

![image](https://user-images.githubusercontent.com/77920719/157210430-317c2e98-e016-421d-b420-ebeee9ec9358.png)
此处在首次(sn - pid) > 16之后，是否忘记对这个seq进行处理

**Comment by chen-guanghua** [comment]
Confirmed, after determining (sn - pid) > 16, no processing was done on seq.

`TRANS_BY_GPT3`

**Comment by chen-guanghua** [comment]
The problem has been fixed and the PR has been submitted for this issue: https://github.com/ossrs/srs/pull/2966.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Merged. Thanks 👍
