### ISSUE TITLE
为何wireshark中抓取的rtcp-fb-nack的seq大于发包以及srstrace中的seq

### ISSUE THREAD

**Issue by Lei-Xiangyu** [ossrs/srs#2961]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**wireshark中显示返回的seq远大于已经发送的seq和trace中显示的update的nack的seq区间**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0-release`

1. SRS的日志如下(Log):

![image](https://user-images.githubusercontent.com/77920719/157415099-cf40f7f6-4348-4451-8fa7-5ebc169a8fa7.png)

1. SRS的配置如下(Config):

```
https.rtc默认
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `打开wireshark抓取rtcp；`
1. `对比其与trace中seq的大小；`
1. `对比其与抓取的rto包中seq的大小；`

**期望行为(Expect)**

> 描述你期望发生的事情(Please describe your expectation)
wireshark抓取的seq（rtcp中的pid）应该和trace与rtp的seq一致

**Comment by winlinvip** [comment]
有问题？

**Comment by Lei-Xiangyu** [comment]
为什么wireshark中显示的rtcp-nack的seq的数目与我在代码中观察到的seq数目明显不同，而且在wireshark中仍然比rtp的seq大很多，这应该是不可能的

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room)交流，每周六晚上20点。也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
