### ISSUE TITLE
Como restringir acceso con user y password

### ISSUE THREAD

**Issue by jhonyesg** [ossrs/srs#2963]
Cordial greetings.

I have the SRS Docker version, everything flows perfectly, but I have a problem of massive connection to unauthorized persons, I want to share a stream route with user and password that allows me a limited number of simultaneous connections to my stream, so I avoid being blocked the vps.

I hope you can help me or tell me how to do it.
thanks
![Captura de pantalla 2022-03-09 123530](https://user-images.githubusercontent.com/29180546/157498574-5a9ecb85-a182-4135-9bb3-797c1df8e5fa.png)
.

**Comment by winlinvip** [comment]
For discussion or idea, please ask in [discord](https://discord.gg/yZ4BnPmHAd).

This issue will be eliminated, see #2716
