### ISSUE TITLE
SRS云服务器带鉴权能力，开源版srs会加入鉴权功能吗？要用HTTP Callback自己搞啊？好难

### ISSUE THREAD

**Issue by sapceman** [ossrs/srs#2973]
SRS云服务器带鉴权能力，开源版srs会加入鉴权功能吗？要用HTTP Callback自己搞啊？好难

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room)交流，每周六晚上20点。也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
