### ISSUE TITLE
docker 部署 srs 并映射 80 端口后推流失败！

### ISSUE THREAD

**Issue by chuck1in** [ossrs/srs#2977]
使用 docker 启动并部署 SRS 后，由于服务器的 80 端口被别的应用占用，于是采用端口映射将 80 映射为其他端口如下：

docker run --rm -it -p 1935:1935 -p 1985:1985 -p 3000:8080 -p 4000:80 registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4 ./objs/srs -c conf/docker.conf

启动成功后，使用推流地址  rtmp://localhost:4000/live/livestream 推流失败。更换一台服务器，不映射 80 端口，使用 rtmp://localhost/live/livestream 推流成功。

请问这是什么原因，为什么端口映射行不通？谢谢@

**Comment by l0g1n** [comment]
The default port number for the RTMP protocol is 1935.
rtmp://localhost/live/livestream is equivalent to rtmp://localhost:1935/live/livestream
So you don't need to map port 80, as it is not being used at all.

`TRANS_BY_GPT3`
