### ISSUE TITLE
domain restriction

### ISSUE THREAD

**Issue by sirfpsycho** [ossrs/srs#2980]
I am referring from https://stackoverflow.com/questions/71112928/nginx-rtmp-video-is-out-of-sync/71273264

I have installed srs successfully and yes there is no sync issue. But Now I want to restrict access of live stream with only my domain. In nginx-rtmp it was very easy to add CORS setup valid_referers blocked mydomain.com; Is there any method so that stream can only be played on my domain only?

Additionally, how can I set atc on ? Can you please tell me the path of exact file in which I can edit and set atc on?

**Comment by winlinvip** [comment]
If you have fixed the issue, you don't have to set the `atc` on, it's an optional config, not required.

If you want to set CORS, you could use NGINX to proxy to SRS, and set the CORS in NGINX as you wish.

For detail about nginx proxy, please read https://github.com/ossrs/srs/issues/2881
