### ISSUE TITLE
ios 15+以上safari浏览器无法播放hls

### ISSUE THREAD

**Issue by gaecom** [ossrs/srs#2984]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)

1. SRS版本(Version): `4.0.34`

1. SRS的日志如下(Log):

```
日志一切正常，hls在ios 15以下播放正常
```

1. SRS的配置如下(Config):

```
hls默认配置
```

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. `启动srs默认配置`
2. `推送华为/海康等rtsp的视频流`

**期望行为(Expect)**

ios 15+ 的safari可以正常播放

> 描述你期望发生的事情(Please describe your expectation)

ios 15+ 的safari无法播放hls，而其他版本和其他端，桌面端播放都正常

**Comment by gaecom** [comment]
临时方案，禁止hls配置，配置 transcode {
        enabled     on;
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine ff {
            enabled         on;
            vfilter {
            }
            vcodec           copy;
            acodec           an;
            #vbitrate        500;
            #vfps            25;
            #vwidth          768;
            #vheight         320;
           # vthreads        12;
            vprofile        main;
            vpreset         fast;
            vparams {

            }
            #acodec          libfdk_aac;
            #abitrate        70;
            #asample_rate    44100;
            #achannels       2;
            aparams {
            }
            oformat hls;
            output      ./objs/nginx/html/live/[stream].m3u8;
        }
    }

**Comment by gaecom** [comment]
作者知道如何将EXTINF 配置成整数吗 或者期望的浮点数，试了hls官方参数，都不行

**Comment by winlinvip** [comment]
SRS版本太老
