### ISSUE TITLE
无法多人(大于1人)通过观看分发出来的流媒体视频

### ISSUE THREAD

**Issue by chuck1in** [ossrs/srs#2985]
服务端正常拉流，推流到固定的端点。接着浏览器通过 localhost:3000 进入页面能够正常观看视频。但是如果尝试再打开一个浏览器访问同样的页面，却无法观看同一个端点的视频，但是此时另外一个浏览器是可以正常观看的。

请问是什么原因，是本身 srs 就不支持还是需要做配置？

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
