### ISSUE TITLE
How to add mydomain.com in the rtmp://mydomain.com/live?

### ISSUE THREAD

**Issue by thanhntvt** [ossrs/srs#2986]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 描述你遇到了什么问题(Please description your issue here)
I use Nginx as proxy and SRS for server live streaming. I can publish the stream via OBS software, but only work the stream setting look like: `rtmp://my_public_ip/live`
but didn't work if `rtmp://mydomain.com/live`

When OBS working, I can play the livestreaming via url look like: `https://mydomain.com/live/livestream.m3u8`

=> How can I publish the stream via `rtmp://mydomain.com/...` from OBS?

**Comment by winlinvip** [comment]
For discussion or idea, please ask in [discord](https://discord.gg/yZ4BnPmHAd).

This issue will be eliminated, see #2716
