### ISSUE TITLE
Chrome浏览器 100版本无法播放webrtc视频

### ISSUE THREAD

**Issue by cherrysakurali** [ossrs/srs#2997]
> 注意：提问前，请先看FAQ(Please read FAQ before file an issue) https://github.com/ossrs/srs/issues/2716

**描述(Description)**

> 使用chrome100版本无法播放webrtc视频，使用99版本正常

1. SRS版本(Version): `4.0.43`

1. SRS的日志如下(Log):
日志显示流接入成功，但是8080播放器页面无法打开视频
1. SRS的配置如下(Config):
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./logs/srs.log;
daemon              on;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    candidate       8.129.44.194;
}
vhost __defaultVhost__ {
    rtc {
        enabled     on;
        bframe      discard;
    }
}

**重现(Replay)**

> 重现Bug的步骤(How to replay bug?)

1. rtmp流接入srs后，使用100版本谷歌浏览器，打开8080网页播放器，播放对应的webrtc流，黑屏，无法播放
2. rtmp流接入srs后，使用99版本谷歌浏览器，打开8080网页播放器，播放对应的webrtc流，成功播放

**期望行为(Expect)**

> 100版本数字问题在谷歌浏览器更新中提到过，希望srs可以添加100及之后版本的支持

**Comment by winlinvip** [comment]
试试最新4.0 该Issue会被删除。#2716
