### ISSUE TITLE
问一下怎么开启HTTPS的M3U8链接推流，试了一下没成功，貌似只支持http

### ISSUE THREAD

**Issue by MrTlyer** [ossrs/srs#3011]
`http://127.0.0.1:8080 `能进控制台，但是`https://127.0.0.1:8088`不能打开
1.尝试修改了srs.conf配置文件，添加了https配置信息
`http_server {`
    `enabled         on;`
   `listen          8080;`
    `dir             ./objs/nginx/html;`
     `crossdomain     on;`
    `https {`
        `enabled on;`
       ` listen 8088;`
        `key ./conf/server.key;`
        `cert ./conf/server.crt;`
   ` }`
`}`

2.更新了SSL证书(server.key、server.crt)

还是没有解决，问一下这种问题出在哪，是不是这个SRS版本就不支持https？@winlinvip

**Comment by MrTlyer** [comment]
ngnix 重新安装后问题解决了，已经可以走https,但是又有新问题，`blocked by CORS`，跨域问题怎么解决呢？

**Comment by MrTlyer** [comment]
跨域问题已经解决了，分享方法：
修改nginx.conf
在
` server {‘
       ’listen       443 ssl http2;‘
    ’ listen       [::]:443 ssl http2;`
后面新增一行配置
`add_header 'Access-Control-Allow-Origin' '*';`
reboot后解决

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
