### ISSUE TITLE
API: 推流和转码时，Streams接口的数据不对

### ISSUE THREAD

**Issue by zengWJJJ** [ossrs/srs#3014]
场景：VLC用rtmp拉流，使用obs推流
配置：配置了一个转码引擎和http flv接口
bug重现：当VLC正在拉流播放时，使用bos推流。接着在obs停止推流，然后又开始推流
bug：
http api接口http://127.0.0.1:1985/api/v1/streams返回的json结果中，stream->clients数据不对

比如在停止推流之前clients为3（因为配置了转码引擎，所以clients多了一个，另外两个则是正常的推流和拉流的client），停止推流再重新推流后，clients变为了2，此时VLC还在播放重新推流后的视频，很明显clients数据不对。

另外，通过http://127.0.0.1:1985/api/v1/clients接口查询时，VLC的client再重新推流后依然是存在的，只不过streams接口的数据没有加进去

**Comment by zengWJJJ** [comment]
The docker image is being used, and as of the latest version, this phenomenon still exists.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in 5.0
