### ISSUE TITLE
webrtc推流hls切片格式问题

### ISSUE THREAD

**Issue by hyw100200** [ossrs/srs#3019]
用了srs4.0的rtc功能进行推流，前端使用hls观看，但是发现生成的m3u8中包含很多#EXT-X-DISCONTINUITY，用网页端观看会经常卡顿，ios上是完全无法播放

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
