### ISSUE TITLE
开发版（Cygwin）反复报Warn

### ISSUE THREAD

**Issue by HNGHTNLP** [ossrs/srs#3020]
开发版（Cygwin）反复提示
`[Warn][643][490b1141][2] open vmstat failed, ignore`
`[Warn][643][490b1141][2] open proc network devices failed, ignore`
`[Warn][643][490b1141][2] open proc network sockstat failed, ignore`
`[Warn][643][490b1141][2] open proc network snmp failed, ignore`
`[Warn][643][490b1141][2] open proc network sockstat failed, ignore`
之后报Trace
[Trace][643][b9561d0d] Hybrid cpu=12.34%,22MB, cid=1,11, timer=58,0,91, clock=0,21,20,2,1,1,0,1,0, objs=(pkt:945,raw:152,fua:793,msg:1099,oth:1,buf:50)
[Trace][643][b9561d0d] RTC: Server conns=2, rpkts=(10,rtp:0,stun:1,rtcp:10), spkts=(631,rtp:630,stun:1,rtcp:0), fid=(id:0,fid:10,ffid:0,addr:1,faddr:10)
[Trace][643][b9561d0d] Hybrid cpu=3.09%,106MB, cid=1,0, timer=58,0,0, clock=1,20,20,2,1,1,1,0,0, objs=(pkt:314,raw:50,fua:263,msg:467,oth:1,buf:50)
隔几秒又报这几个Warn
这样交叉且循环的报Warn
没有问题吗?

**Comment by winlinvip** [comment]
有问题吗？
