### ISSUE TITLE
如何实现dvr动态录制视频？

### ISSUE THREAD

**Issue by yangmingli08** [ossrs/srs#3024]
1. SRS版本(Version): `4.0`

vhost xxx {
    dvr {
        dvr_apply record/lecture1 record/lecture2 record/lecture3 [...] ;
    }
}

2. 期望

我想录制 app = record 下的所有视频 stream = lecture1, lecture2, lecture3, .... ， 不限制stream的名字
其他像是 app = live 则不予录制

我试过 
vhost xxx {
    dvr {
        dvr_apply record/[stream];
    }
}
并没有识别为变量
而是存到了 record/[stream].flv 文件

版本是4.0 有用到的RAW API被删除了，无法通过API调用这个功能

需求如何能实现？

**Comment by winlinvip** [comment]
你的问题已经在FAQ中存在，该Issue会被删除，请在FAQ中搜索。#2716
