### ISSUE TITLE
Build from source error

### ISSUE THREAD

**Issue by Alijaaan** [ossrs/srs#3026]
**Description(描述)**

> I'm trying to build srs on Centos 7 as described in document by : 
> git clone -b develop https://gitee.com/ossrs/srs.git && cd srs/trunk && ./configure && make && ./objs/srs -c conf/srs.conf
> But I have this error on ./configure :
> -bash: ./configure: /bin/bash^M: bad interpreter: No such file or directory

Could you please help me.
I already build srs before without any problem.

1. SRS Version(版本): `latest`

**Comment by Alijaaan** [comment]
In this case I rebuild my centos and upgraded, I installed fresh git . my problem solved.
My problem was not related to the srs.

**Comment by esagulto** [comment]
Hello, thanks for that. I also managed to build it.

**Comment by winlinvip** [comment]
For discussion or idea, please ask in [discord](https://discord.gg/yZ4BnPmHAd).

This issue will be eliminated, see #2716
