### ISSUE TITLE
OBS 推流SRT，通过FLV、WebRTC接收，延迟非常大，超过10秒

### ISSUE THREAD

**Issue by wanstonq** [ossrs/srs#3031]
OBS 27 推流SRT，配置如下：

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

srt_server {
    enabled on;
    listen 10080;
    maxbw 1000000000;
    connect_timeout 4000;
    peerlatency 300;
    recvlatency 300;
}

rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#config-candidate
    candidate $CANDIDATE;
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtc-to-rtmp
        rtc_to_rtmp on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

**Comment by wanstonq** [comment]
![image](https://user-images.githubusercontent.com/26664484/167276465-073757f0-f07c-4393-9a2e-1857cd14d20b.png)

**Comment by wanstonq** [comment]
采用rtmp推流，延迟基本1秒作用

![image](https://user-images.githubusercontent.com/26664484/167324154-95bc828a-8034-48e7-b177-35224a5773e5.png)

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room)交流，每周六晚上20点。也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by wanstonq** [comment]
哦，延迟很大不是BUG吗？
