### ISSUE TITLE
webrtc拉流黑屏

### ISSUE THREAD

**Issue by okxzapp** [ossrs/srs#3032]
use private address as ip: 172.x.x.x

总是显示这个，配置了公网ip，webrtc拉流黑屏，flv能显示，不知道怎么解决
![image](https://user-images.githubusercontent.com/73098636/167366092-045122d4-9771-4e27-8332-f441a16c334e.png)

**Comment by LIUSHUAI2018** [comment]
我也是控制台也没报错

**Comment by dengzhengxiong** [comment]
请问你解决这个问题了吗
