### ISSUE TITLE
gb28181 某康相机 主码流 srs 无法播放，子码流可以

### ISSUE THREAD

**Issue by tiancw829** [ossrs/srs#3035]
**接入gb28181的平台，推某康的rtp主码流到9000，无法播放，什么原因造成？**

> 
某康相机主码流接入GB2818，srs 播放器无法播放，子码流可以

1. SRS Version(版本): `4.0`

1. SRS Log(日志):

```
RTP: jitbuffer NACK list has grown too large: 273 > 250
requesting key frame due to too large NACK list.
...
...
```

1. SRS Config(配置):

```
sip off
外部sip
```

**Comment by winlinvip** [comment]
GB已经放到独立的仓库 [srs-gb28181](https://github.com/ossrs/srs-gb28181)， 请参考 #2845
问题请提交到GB的仓库[bug](https://github.com/ossrs/srs-gb28181/issues)，或者[pr](https://github.com/ossrs/srs-gb28181/pulls)

由于265主要在GB中使用，所以265分支也迁移到了 [srs-gb28181](https://github.com/ossrs/srs-gb28181/tree/feature/h265)

该Issue会被删除，请先阅读FAQ：#2716
