### ISSUE TITLE
WebRTC播放器资源释放问题

### ISSUE THREAD

**Issue by cindli** [ossrs/srs#3037]
**Description(描述)**

> Please description your issue here(描述你遇到了什么问题)

服务器版本：SRS/5.0.26(Leo)

WebRTC播放器在进行关闭或刷新页面后（调用RTCPeerConnection.close()方法，如下图：）
![image](https://user-images.githubusercontent.com/19762594/168476047-23d83c4f-64e6-4af0-9efb-e4748864053a.png)

发现相关整体的网络带宽占用并没有下降，要等很久（30s以上才会慢慢降下来）, 单独看chrome的网络占用是正常的

初步判断是否是因为webrtc是基于udp的，客户端断开后，服务端的仍然在发送数据

这个问题会导致在播放很多路视频的时候带宽增加过多且释放过程较慢，刷新页面也不会立即释放之前播放器占用的网络带宽

![整体网络占用](https://user-images.githubusercontent.com/19762594/168475649-c09bfe2b-943b-419d-80af-26e34ef08531.png)

![浏览器网络占用](https://user-images.githubusercontent.com/19762594/168475694-902cd1b0-f878-4b32-98b0-db4caa897bef.png)

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

1. 刷新正在播放的视频 或 重复执行播放/关闭操作

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)

执行关闭后 相关网络占用立即降低

**Comment by logicin** [comment]
SRS/4.0.251 seems to be fine.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
When the client closes, it sends a message to the server, but sometimes it may be lost. This problem is unsolvable, haha.

`TRANS_BY_GPT3`
