### ISSUE TITLE
边缘服务器拉流时启用opus转码，非常容易导致异常内存分配退出

### ISSUE THREAD

**Issue by wanstonq** [ossrs/srs#3043]
srs_app_edge.cpp 相关修改如下：

srs_error_t SrsEdgeIngester::start()
{
    srs_error_t err = srs_success;
    
#ifdef SRS_RTC
    bool edge = _srs_config->get_vhost_is_edge(req->vhost);
    SrsRtcSource *rtc = NULL;
    bool rtc_server_enabled = _srs_config->get_rtc_server_enabled();
    bool rtc_enabled = _srs_config->get_rtc_enabled(req->vhost);
    if (edge && rtc_server_enabled && rtc_enabled) { 
        if ((err = _srs_rtc_sources->fetch_or_create(req, &rtc)) != srs_success) {
            return srs_error_wrap(err, "create source");
        }

        if (!rtc->can_publish()) {
            return srs_error_new(ERROR_SYSTEM_STREAM_BUSY, "rtc stream %s busy", req->get_stream_url().c_str());
        }
    }
#endif

    // Bridge to RTC streaming.
#if defined(SRS_RTC) && defined(SRS_FFMPEG_FIT)
    if (!source->get_bridger() && rtc) {
        SrsRtcFromRtmpBridger *bridger = new SrsRtcFromRtmpBridger(rtc);
        if ((err = bridger->initialize(req)) != srs_success) {
            srs_freep(bridger);
            return srs_error_wrap(err, "bridger init");
        }

        source->set_bridger(bridger);
    }
#endif

    if ((err = source->on_publish()) != srs_success) {
        return srs_error_wrap(err, "notify source");
    }
    
    srs_freep(trd);
    trd = new SrsSTCoroutine("edge-igs", this);
    
    if ((err = trd->start()) != srs_success) {
        return srs_error_wrap(err, "coroutine");
    }
    
    return err;
}

CoreDump 信息（每次位置不太一样，但大多是内存分配问题）：
(gdb) bt
#0  0x000000398b87a1e8 in _int_malloc () from /lib64/libc.so.6
#1  0x000000398b87aaac in malloc () from /lib64/libc.so.6
#2  0x0000003996cbd0cd in operator new(unsigned long) ()
   from /usr/lib64/libstdc++.so.6
#3  0x0000003996cbd1e9 in operator new[](unsigned long) ()
   from /usr/lib64/libstdc++.so.6
#4  0x00000000004c5962 in SrsRtpPacket::wrap (this=0x41deb70, size=188)
    at src/kernel/srs_kernel_rtc_rtp.cpp:793
#5  0x00000000004c59ec in SrsRtpPacket::wrap (this=0x41deb70,
    data=0x42b0cc0 "\374.B\004eص\"2B;\374D\217\305v\201@\242\204{Q\027\022 <?\277#m\217\031\020\214\202l%\267\237-\265>\257\354%\325", <incomplete sequence \321>, size=188) at src/kernel/srs_kernel_rtc_rtp.cpp:803
#6  0x00000000006a7f04 in SrsRtcFromRtmpBridger::package_opus (
    this=0x41e8810, audio=0x42c1b60, pkt=0x41deb70)
    at src/app/srs_app_rtc_source.cpp:983
#7  0x00000000006a7c4b in SrsRtcFromRtmpBridger::transcode (this=0x41e8810,
    audio=0x44d1a80) at src/app/srs_app_rtc_source.cpp:952
#8  0x00000000006a7a87 in SrsRtcFromRtmpBridger::on_audio (this=0x41e8810,
    msg=0x44d3380) at src/app/srs_app_rtc_source.cpp:924
#9  0x00000000005720d1 in SrsLiveSource::on_audio_imp (this=0x4159170,
    msg=0x44d3380) at src/app/srs_app_source.cpp:2409
#10 0x0000000000571cca in SrsLiveSource::on_audio (this=0x4159170,
    shared_audio=0x42b0680) at src/app/srs_app_source.cpp:2364
#11 0x000000000061bbb1 in SrsEdgeIngester::process_publish_message (
---Type <return> to continue, or q <return> to quit---
    this=0x41592a0, msg=0x42b0680, redirect=...)
    at src/app/srs_app_edge.cpp:370
#12 0x000000000061ba8a in SrsEdgeIngester::ingest (this=0x41592a0,
    redirect=...) at src/app/srs_app_edge.cpp:356
#13 0x000000000061b544 in SrsEdgeIngester::do_cycle (this=0x41592a0)
    at src/app/srs_app_edge.cpp:299
#14 0x000000000061b0aa in SrsEdgeIngester::cycle (this=0x41592a0)
    at src/app/srs_app_edge.cpp:260
#15 0x00000000005950cc in SrsFastCoroutine::cycle (this=0x41e9060)
    at src/app/srs_app_st.cpp:272
#16 0x0000000000595134 in SrsFastCoroutine::pfn (arg=0x41e9060)
    at src/app/srs_app_st.cpp:287
#17 0x0000000000736fda in _st_thread_main () at sched.c:363
#18 0x0000000000737879 in st_thread_create (
    start=0x595114 <SrsFastCoroutine::pfn(void*)>, arg=0x41e9060, joinable=1,
    stk_size=65536) at sched.c:694
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by wanstonq** [comment]
禁用AAC编码后，一切正常
可能是边缘拉流onunpublish后，释放SrsAudioTranscoder后引起的内存分配问题


但推流端启用转码，目前没发现问题

**Comment by xiaozhihong** [comment]
修改了源代码就得尝试自己找问题了, 我们没有完整代码, 缺乏背景上下文, 无法判断问题.

**Comment by winlinvip** [comment]
SRS边缘不支持Opus转码。
