### ISSUE TITLE
srs在X86设备中编译安装过程中，出现下面这个错误，如何解决呢？

### ISSUE THREAD

**Issue by VPN-V2Ray** [ossrs/srs#3047]
srs在X86设备中编译安装过程中，出现下面这个错误，如何解决呢？

LINUX_5.4.0-113-generic_DBG/sched-pic.o：在函数‘st_poll’中：
/home/tony/srs/trunk/objs/Platform-Linux-5.4.0-GCC7.5.0-SRS4-i686/st-srs/sched.c:131：对‘__stack_chk_fail_local’未定义的引用
LINUX_5.4.0-113-generic_DBG/sync-pic.o：在函数‘st_utime’中：
/home/tony/srs/trunk/objs/Platform-Linux-5.4.0-GCC7.5.0-SRS4-i686/st-srs/sync.c:70：对‘__stack_chk_fail_local’未定义的引用
LINUX_5.4.0-113-generic_DBG/io-pic.o：在函数‘_st_io_init’中：
/home/tony/srs/trunk/objs/Platform-Linux-5.4.0-GCC7.5.0-SRS4-i686/st-srs/io.c:126：对‘__stack_chk_fail_local’未定义的引用
LINUX_5.4.0-113-generic_DBG/io-pic.o：在函数‘_st_netfd_new’中：
/home/tony/srs/trunk/objs/Platform-Linux-5.4.0-GCC7.5.0-SRS4-i686/st-srs/io.c:186：对‘__stack_chk_fail_local’未定义的引用
LINUX_5.4.0-113-generic_DBG/io-pic.o：在函数‘st_netfd_poll’中：
/home/tony/srs/trunk/objs/Platform-Linux-5.4.0-GCC7.5.0-SRS4-i686/st-srs/io.c:260：对‘__stack_chk_fail_local’未定义的引用
LINUX_5.4.0-113-generic_DBG/io-pic.o:/home/tony/srs/trunk/objs/Platform-Linux-5.4.0-GCC7.5.0-SRS4-i686/st-srs/io.c:451: 跟着更多未定义的参考到 __stack_chk_fail_local
Makefile:363: recipe for target 'LINUX_5.4.0-113-generic_DBG/libst.so.1.9' failed
make[1]: *** [LINUX_5.4.0-113-generic_DBG/libst.so.1.9] Error 1
make[1]: 离开目录“/home/tony/srs/trunk/objs/Platform-Linux-5.4.0-GCC7.5.0-SRS4-i686/st-srs”
Makefile:451: recipe for target 'linux-debug' failed
make: *** [linux-debug] Error 2
Build state-threads failed, ret=2

**Comment by VPN-V2Ray** [comment]
make 之后出现下面这样的错误，请作者和各位大神指点一下，如何解决这个问题？

src/protocol/srs_service_st.cpp
src/protocol/srs_service_st.cpp:9:10: fatal error: st.h: 没有那个文件或目录
 #include <st.h>
          ^~~~~~
compilation terminated.
objs/Makefile:278: recipe for target 'objs/src/protocol/srs_service_st.o' failed
make[1]: *** [objs/src/protocol/srs_service_st.o] Error 1
make[1]: 离开目录“/home/t/srs/trunk”
Makefile:105: recipe for target 'server' failed
make: *** [server] Error 2

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
