### ISSUE TITLE
我在虚拟机上部署的srs但是webrtc就是预览不了

### ISSUE THREAD

**Issue by LIUSHUAI2018** [ossrs/srs#3048]
![image](https://user-images.githubusercontent.com/37928107/170459147-22cac0aa-9385-4529-af47-1556ff2dde22.png)

1. SRS Version(版本): v-4.0-b10

1. SRS Log(日志):

![image](https://user-images.githubusercontent.com/37928107/170459314-f9360610-e570-4897-9b84-d9dfc20763cc.png)
![image](https://user-images.githubusercontent.com/37928107/170459469-4a8f640f-bcf9-4e72-94f9-c406082ea51f.png)

1. SRS Config(配置):
` # main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
#srs_log_tank        file;
#srs_log_file        ./objs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled on;
    listen 8000;
    candidate 192.168.161.128;
}
vhost 192.168.161.128 {
    min_latency     on;
    mr {
        enabled     off;
    }
    mw_latency      100;
    gop_cache       off;
    queue_length    10;
    http_remux {
        enabled     on;
        mount [vhost]/[app]/[stream].flv;
        hstrs   on;
    }
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        rtmp_to_rtc on;
        rtc_to_rtmp on
    }
}
`

**Comment by xiaozhihong** [comment]
不能带.flv
改为live/1

**Comment by winlinvip** [comment]
明显不是跟着Wiki操作。

请看[Wiki](https://github.com/ossrs/srs/wiki/v4_CN_Home)。该Issue会被删除，请先阅读FAQ：#2716
