### ISSUE TITLE
rtmp推流url后接参数会导致拉流失败

### ISSUE THREAD

**Issue by ghostsf** [ossrs/srs#3057]
1. SRS Version(版本): `latest`

**Replay(重现)**
 ffmpeg -re -i doc/source.200kbps.768x320.flv -c copy -f flv -y "rtmp://r.ossrs.net/live/test?debug=1"

可以正常推流

但是拉流失败
rtmp://r.ossrs.net/live/test?debug=1

**Comment by ghostsf** [comment]
进一步测试发现
第一次推流，可以成功拉流；
关掉第一次推流，进行第二次推流，就会拉流失败

每次都需要新的stream key 才可以

**Comment by ghostsf** [comment]
似乎是stream session缓存之类的问题

**Comment by xiaozhihong** [comment]
有log吗, 这个问题测试了下并不会出现, 从代码来看, 也是不太可能的.

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
