### ISSUE TITLE
CentOS7 下编译安装一路报错的有没有

### ISSUE THREAD

**Issue by 1164461842** [ossrs/srs#3065]
CentOS7 下编译安装一路报错的有没有

已经解决了， 6~7个报错了,`./config`都没执行成功呢

![image](https://user-images.githubusercontent.com/54823693/173193154-d83acbfd-6d36-4963-ae40-655765605f4a.png)

这报错咋搞..

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room)交流。也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
