### ISSUE TITLE
SRS可以做多路推流嘛

### ISSUE THREAD

**Issue by zfs1993** [ossrs/srs#3066]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**
现在有两种场景，一种是拉rtsp数据流，再推出几路rtmp数据流（1路原始画面，其他几路是原始画面的切块）
一种是接收多路rtsp数据流，再都推出来，推多路流，不知道有没有这种功能？

> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本): `xxxxxx`

1. SRS Log(日志):

```
xxxxxxxxxxxx
```

1. SRS Config(配置):

```
xxxxxxxxxxxx
```

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room)交流。也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
