### ISSUE TITLE
rtmp设置推流口令（密钥）

### ISSUE THREAD

**Issue by ivangohub** [ossrs/srs#3068]
请问怎么给rtmp服务器设置推流的口令（密钥）？
很多推流的客户端需要填写推流地址和口令密钥且不能为空

1. SRS Config(配置):
这个配置文件里应该怎么填入我指定的密钥？

谢谢

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
