### ISSUE TITLE
forward 在失败的情况下会一直重试

### ISSUE THREAD

**Issue by victoriahammer** [ossrs/srs#3069]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

有一种场景，rtmp推流到srs 后，需要srs forward 到另外多个服务器处理，这些服务做了入流鉴权，最终只有一个服务会处理forward。其他都会forward失败，但是发现srs在失败的情况下，会不断的重试推流。

> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本): `4.0.236`

1. SRS Log(日志):

```
xxxxxxxxxxxx
```

1. SRS Config(配置):

```
vhost vhost.live {
    forward {
       enabled on;
       destination x.x.x.x:1935 y.y.y.y:1935;
    }
}
```

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

forward 配置 失败的推流地址即可

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)

不重试，或者进行少量重试。

**Comment by winlinvip** [comment]
After OBS starts streaming, it will keep retrying if the server disconnects.

If there are several retries or no retries, it will result in the stream playing normally but the server for transcoding being abnormal, making troubleshooting more difficult.

If your forward doesn't require a stream to run normally, then you should disable the forward. This is equivalent to not retrying even if it fails every time.

If you insist that the forward should have a special retry strategy, you can implement it yourself using FFmpeg to pull the stream and then forward it. This way, you can achieve a very flexible retry strategy, and you can implement it however you want in your own code.

`TRANS_BY_GPT3`
