### ISSUE TITLE
新手问下默认8000的udp，可以用其他端口不。

### ISSUE THREAD

**Issue by bbhxwl** [ossrs/srs#3075]
新手问下默认8000的udp，可以用其他端口不。

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://github.com/ossrs/srs/wiki/Contact#wechat-live-room)交流。也可以[加微信群](https://github.com/ossrs/srs/wiki/Contact#wechat)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
