### ISSUE TITLE
有关于srs.sdk.js 的详细说明么。

### ISSUE THREAD

**Issue by bbhxwl** [ossrs/srs#3080]
https://github.com/ossrs/srs/blob/310514ea94fc180d170a20c2bd4b42d05a001ddc/trunk/research/players/rtc_publisher.html
我看这个，里面需要的js文件挺多，想vue用。很多不知道是不是必须的，有这个js的详细说明么。
目前差推流，是必须用这个才能推么。

**Comment by bbhxwl** [comment]
不能推自定义流

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
