### ISSUE TITLE
提几个意见和小bug

### ISSUE THREAD

**Issue by bbhxwl** [ossrs/srs#3082]
webrtc用srs.sdk.js推流，不能自定义流，里面默认写好了只是摄像头，这个我自己改了。不止摄像头
webrtc推完了以后，网页后台console，显示入网流量一直是0，应该是bug吧。obs的推能统计到流量。还有流明如果是.flv的话，好像不推也一直存在，不知道为什么。不会消失

**Comment by bbhxwl** [comment]
另外sdk，好像也不能自定义端口和协议吧？

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716

**Comment by bbhxwl** [comment]
> 这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716

这个不是一般的推拉流库用不了，只能用这个sdk么。好像推流之前会有一个api请求。 sdk很多地方写死不能自定义不太方便。
