### ISSUE TITLE
支持配置多个http端口吗

### ISSUE THREAD

**Issue by mdzz0073** [ossrs/srs#3090]
**Description(描述)**

> 我部署了一个docker容器化的srs，http端口号是11985，这个端口我已经用来推送一个视频流地址了，现在我想要再推送一个音频流的rtmp地址，需要另外再配置一个端口吗

1. SRS Version(版本): `v4.0.56`

**Expect(期望行为)**

> 希望能够部署一个srs推送多个不同的流

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
