### ISSUE TITLE
webrtc推，拉取不下来

### ISSUE THREAD

**Issue by bbhxwl** [ossrs/srs#3091]
我用webrtc推，拉，都可以。
但是webrtc推，非rtc拉就不行呢？
我推的网址是 

webrtc://localhost:8080/live/aaa/123
 
拉取是http://localhost:8080/live/aaa/123.flv 
 http://localhost:8080/live/aaa/123.m3u8

都没成功，用vlc拉的，h5也测试过。

**Comment by bbhxwl** [comment]
配置方面我也开了的
```
rtc {
        enabled     on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://github.com/ossrs/srs/wiki/v4_CN_WebRTC#rtc-to-rtmp
        rtc_to_rtmp on;
    }

```

**Comment by bbhxwl** [comment]
测试了在线播放m3u8的话，时灵时不灵，配置都没问题，而且延迟超级大。总卡。

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
