### ISSUE TITLE
使用SRS 调用FFmpeg讲RTSP转推RTMP生成HLS，SRS正常运行RTMP，HLS出现异常均无法播放

### ISSUE THREAD

**Issue by wjtNo2** [ossrs/srs#3092]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**
使用SRS 调用FFmpeg讲RTSP转推RTMP生成HLS，运行一段时间SRS正常运行RTMP，HLS出现异常均无法播放，重启SRS后正常
> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本):
4.0.150
1. SRS Log(日志):

```
xxxxxxxxxxxx
```

1. SRS Config(配置):
listen              1937;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         off;
    listen          80;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    hls {
        enabled         off;
        hls_path        /hls/;
        hls_fragment    5;
        hls_window      15;
        hls_on_error    continue;
        hls_cleanup     on;
        hls_dispose      20;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    

    ingest 1-502{
        enabled      on;
        input {
            type    stream;
            url rtsp://admin:PASSword@11.152.115.80:554/h264/ch1/main/av_stream;
        }
        ffmpeg       ./objs/zhuanma;
        engine {
            enabled          on;
            vcodec          copy;
            r           25;
            acodec           copy;
            rtsp_transport   tcp;
            ar              44100;
            strict             2;
            ac                 1;
            output rtmp://127.0.0.1:1936/live/1-502;
        }
    }

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

偶然未发现重新步骤

**Expect(期望行为)**

> Please describe your e
[srs.zip](https://github.com/ossrs/srs/files/8998199/srs.zip)
xpectation(描述你期望发生的事情)

文件较大无法上传

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
