### ISSUE TITLE
SRT to WebRTC

### ISSUE THREAD

**Issue by arjan-kuiper** [ossrs/srs#3094]
Does anyone have any clue on how to feed in an SRT stream and playback it using WebRTC? I've got the SRT part working, but I don't know how to play it back on WebRTC

**Comment by winlinvip** [comment]
`SRT to RTMP to WebRTC`

Please read wiki about how to covert RTMP to WeRTC: https://ossrs.io/lts/en-us/docs/v4/doc/getting-started#webrtc-for-live-streaming
