### ISSUE TITLE
使用ffmpeg推流一个纯音频文件到srs生成的ts文件带空视频信息，导致iphone12下播放有问题

### ISSUE THREAD

**Issue by zk1173168848** [ossrs/srs#3097]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**
使用ffmpeg推流一个纯音频文件到srs生成的ts文件带空视频信息，导致iphone12下播放有问题

1. SRS Version(版本): SRS/4.0.253

1. SRS Log(日志):

```
xxxxxxxxxxxx
```

1. SRS Config(配置):

```
xxxxxxxxxxxx
```

**Replay(重现)**

ffmpeg -re -i http://rscdn.ajmide.com/r_1390/live_1390.m3u8?"from="singlemessage"&isappinstalled="0 -vn  -acodec aac  -f flv rtmp://192.168.10.140/live/123456
![image](https://user-images.githubusercontent.com/49718621/176845151-cfda1766-32d8-40fa-90ee-583e211a9b27.png)
发现生成的ts文件中包含空的视频轨道信息导致无法播放
![image](https://user-images.githubusercontent.com/49718621/176845410-5deaf44f-63c5-4d8d-bcea-7d14a81724a8.png)
类似只包含音频轨道信息的是可以正常播放的

**Expect(期望行为)**

>期望推送纯音频的时候，在新版本的ios中可以正常播放

**Comment by zk1173168848** [comment]
https://github.com/winshining/nginx-http-flv-module/issues/217

**Comment by zk1173168848** [comment]
https://github.com/winshining/nginx-http-flv-module/issues/217 Found the same issue in nginx-flv


`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If it is pure audio, disabling video is sufficient.

```
        # the default video codec of hls.
        # when codec changed, write the PAT/PMT table, but maybe ok util next ts.
        # so user can set the default codec for pure audio(without video) to vn.
        # the available video codec:
        #       h264, vn
        # Overwrite by env SRS_VHOST_HLS_HLS_VCODEC for all vhosts.
        # default: h264
        hls_vcodec vn;
```

`TRANS_BY_GPT3`

**Comment by winshining** [comment]
> [winshining/nginx-http-flv-module#217](https://github.com/winshining/nginx-http-flv-module/issues/217) Found the same issue in nginx-flv

I saw a reference to an issue in my project, and the problem has already been fixed.

`TRANS_BY_GPT3`
