### ISSUE TITLE
srs编译使用--use-sys-ssl和--srt=on问题

### ISSUE THREAD

**Issue by victoriahammer** [ossrs/srs#3098]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

编译srs带 --srt=on  --use-sys-ssl 会编译失败
打印"OpenSSL pkgconfig no found, build srt-1-fit failed."
看编译脚本，
因为不会编译openssl，所以找不到objs/${SRS_PLATFORM}/openssl/lib/pkgconfig

auto/depends.sh
```
if [[ ! -d ${SRS_OBJS}/${SRS_PLATFORM}/openssl/lib/pkgconfig ]]; then
                echo "OpenSSL pkgconfig no found, build srt-1-fit failed.";
                exit -1;
            fi
```

> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本): `4.0.236`

1. SRS Log(日志):

```
OpenSSL pkgconfig no found, build srt-1-fit failed.
```

1. SRS Config(配置):

不涉及

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

./configure  --srt=on  --use-sys-ssl  && make

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)
srt 编译正确。

**Comment by xiaozhihong** [comment]
./configure --srt=on
Is it necessary for you to use the system's SSL library?

`TRANS_BY_GPT3`

**Comment by victoriahammer** [comment]
> ./configure --srt=on 即可, 你是一定要用系统的ssl库吗?
我主要反馈的是这个场景下，编译脚本有问题。

**Comment by victoriahammer** [comment]
> ./configure --srt=on. Do you really need to use the system's SSL library?

I mainly provide feedback on the issue with the compilation script in this scenario. Using the system's SSL is because SSL vulnerabilities have been constantly reported.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The SSL system may also have vulnerabilities, but compiling and upgrading the SSL source code of SRS will be faster.

`TRANS_BY_GPT3`

**Comment by victoriahammer** [comment]
> The SSL system may also have vulnerabilities, but compiling and upgrading the SSL source code of SRS will be faster.

> Does it mean to directly replace /3rdparty/openssl-1.1-fit and compile directly?

`TRANS_BY_GPT3`
