### ISSUE TITLE
master分支在osx编译openssl 失败的问题

### ISSUE THREAD

**Issue by yushimeng** [ossrs/srs#3103]
1. SRS Version(版本): `master`

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

1. `操作系统 macOS Catalina 10.15.7 intel芯片`
2、下载master分支代码, 编译提示: Build openssl-1.1.0e failed. 定位在openssl config失败.
**按照以下解决方法, 可以正常编译通过.**
https://github.com/guanzhi/GmSSL/issues/811#issuecomment-600976821
是否考虑把该改动增加到openssl tar包中.

**Comment by winlinvip** [comment]
The master branch has already been synchronized with the stable 4.0 branch. Thank you for the feedback.

`TRANS_BY_GPT3`
