### ISSUE TITLE
rtc转rtmp流通过ffmpeg转码改变高度播放失败

### ISSUE THREAD

**Issue by zk1173168848** [ossrs/srs#3110]
Note: Please read FAQ before file an issue, see 2716

Note: 提问前，请先看FAQ, 即 2716

Description(描述)
1、srs通过rtc捕捉电脑桌面，在srs配置文件中配置ffmpeg转流至其他服务器，简单copy流播放成功，改变宽高播放失败。
Please description your issue here(描述你遇到了什么问题)
SRS Version(版本): SRS/4.0.253

ffmpeg命令及srs配置：
![image](https://user-images.githubusercontent.com/49718621/178972731-cc796cc2-17e1-4f08-b0dc-3809025a6b1f.png)
播放失败画面：
![image](https://user-images.githubusercontent.com/49718621/178972884-6d5aeb2c-e3ba-4c71-9453-567570ed2d45.png)
播放成功画面：
![image](https://user-images.githubusercontent.com/49718621/178972917-ce7d759d-676e-4f3e-8ffc-832ae6fd0f7f.png)

Replay(重现)

Please describe how to replay the bug? (重现Bug的步骤)

Please describe your expectation(描述你期望发生的事情)
期望可以播放

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
