### ISSUE TITLE
手机端播放rtmp http-flv第二次就开始卡

### ISSUE THREAD

**Issue by JoneJay** [ossrs/srs#3121]
srs4，android ios 
试了各种播放器都一样，vlc playxtreme都一样，看进度条一直延迟是0秒，也没开倍速。
PC播放没问题，网络没问题，用nginx-rtmp那一套完全没问题。

**Comment by JoneJay** [comment]
这个项目问题太多了，测试做的肯定一塌糊涂

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
