### ISSUE TITLE
web实现IPC视频流实时播放，延时长怎么解决？有没有大佬？

### ISSUE THREAD

**Issue by 524215212** [ossrs/srs#3124]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**

> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本): `xxxxxx`

1. SRS Log(日志):

```
xxxxxxxxxxxx
```

1. SRS Config(配置):

```
xxxxxxxxxxxx
```

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
