### ISSUE TITLE
生成一个ts 文件  fps 是90000

### ISSUE THREAD

**Issue by fastfading** [ossrs/srs#3136]
**Description(描述)**

生成一个ts 文件  fps 是90000
ts pts dts  正常
不确定什么原因导致这个ts 异常，  ts 文件在附件中

1. SRS Version(版本): `2.0`

1. SRS Log(日志):

log 正常

1. SRS Config(配置):

2s 一个切片

**Replay(重现)**
[1659428041760_911_1280x720.ts.zip](https://github.com/ossrs/srs/files/9257950/1659428041760_911_1280x720.ts.zip)

偶现，不明原因

**Expect(期望行为)**

fps 是 是标准 30

**Comment by fastfading** [comment]
[adts.txt](https://github.com/ossrs/srs/files/9257972/adts.txt)
[apts.txt](https://github.com/ossrs/srs/files/9257973/apts.txt)
[dts.txt](https://github.com/ossrs/srs/files/9257974/dts.txt)
[pts.txt](https://github.com/ossrs/srs/files/9257975/pts.txt)
pts dts  for video
apts adts for audio

pts looks normal,  


ffprobe -v quiet -print_format json -show_format -show_streams -show_error -show_chapters  1659428041760_911_1280x720.ts >1659428041760_911_1280x720.dump

"r_frame_rate": "90000/1",

`TRANS_BY_GPT3`

**Comment by fastfading** [comment]
[1659428039701_910_1280x720.dump.txt](https://github.com/ossrs/srs/files/9265615/1659428039701_910_1280x720.dump.txt)
[1659428039701_910_1280x720.txt](https://github.com/ossrs/srs/files/9265616/1659428039701_910_1280x720.txt)
[1659428041760_911_1280x720.txt](https://github.com/ossrs/srs/files/9265617/1659428041760_911_1280x720.txt)
[1659428041760_911_1280x720.dump.txt](https://github.com/ossrs/srs/files/9265618/1659428041760_911_1280x720.dump.txt)
Compared, the header information is also completely the same.

`TRANS_BY_GPT3`

**Comment by fastfading** [comment]
The following are three consecutive ts files. Only the fps of the middle one is 90000, while the fps of the others before and after are normal.
[Archive.zip](https://github.com/ossrs/srs/files/9265884/Archive.zip)

This problem is too bizarre.



`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Usually, it is related to the timestamp or content of your flow. This situation occurs when the timestamp or content is abnormal.

You need to seek help from the R&D team to investigate and troubleshoot. It is not possible to directly determine the problem based on the phenomenon.

If there is no R&D team, you can try using FFmpeg to transcode the stream and then feed it to SRS. This usually corrects some abnormal content.

> Note: You can also try transcoding the original stream with FFmpeg, which usually prompts for errors or warnings.

`TRANS_BY_GPT3`

**Comment by fastfading** [comment]
FFmpeg displays 90k fps, while other tools like mediainfo show 30.62fps. I have attached the pts. The pts are not very regular, with some video frames having an interval of only 22ms, but they are still strictly ordered. Of course, this issue is not related to SRS.

However, some third-party sources are not very stable, which can cause slight disturbances in the pts, making them slightly shorter or longer. Some streaming conversion tools like nginx-rtmp (some non-open source versions) perform pts correction on the server to make them more regular. Will SRS consider adding these features?



`TRANS_BY_GPT3`
