### ISSUE TITLE
cmaf hls min latency 3s.

### ISSUE THREAD

**Issue by mjnk9xw** [ossrs/srs#3139]
I'm learning about livestream and found this to be an extremely cool project. But the problem I have just optimized the latency hls about 4-10s. I am learning about cmaf technology for hls , do you guys support this in the project. thank.

**Comment by winlinvip** [comment]
The latency of HLS/DASH/CMAF and other file based streaming protocol, is about 5s+.

Please use HTTP-FLV(1~3s) or WebRTC(<1s) instead.
