### ISSUE TITLE
Fixed by [feature/h265](https://github.com/ossrs/srs/tree/feature/h265)

### ISSUE THREAD

**Issue by superemewill** [ossrs/srs#3142]
Fixed by [feature/h265](https://github.com/ossrs/srs/tree/feature/h265)

_Originally posted by @winlinvip in https://github.com/ossrs/srs/issues/465#issuecomment-903200743_

 为啥我们的H265视频用srs的H265分支 播放不了，H264的视频可以播放
 是因为SRS支持H265，但是各个浏览器不支持
 是否可以开发浏览器相关插件

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
