### ISSUE TITLE
dvr录播了四个摄像头的rtmp流，录制时长为一个小时，但是经常会有mp4.tmp文件不能正常转换为MP4格式，并且会一直保留着，需要怎么处理呢

### ISSUE THREAD

**Issue by 2298yang** [ossrs/srs#3161]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**
![image](https://user-images.githubusercontent.com/92721886/187823671-8baac83a-d80e-4bb3-a41d-20229e15cf33.png)

> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本): `xxxxxx`

1. SRS Log(日志):

```
xxxxxxxxxxxx
```

1. SRS Config(配置):

```
xxxxxxxxxxxx
```

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by fengyang1** [comment]
停止录制的时候，别直接杀死srs服务器，先把需要保存的视频流踢出去，
例如
 curl -v -X GET http://192.168.126.128:1985/api/v1/streams/          （192.168.126.128:1985）
curl -v -X GET http://192.168.126.128:1985/api/v1/streams/vid-673oxk6  （"id":"vid-673oxk6"） 
curl -v -X DELETE http://192.168.126.128:1985/api/v1/clients/v5763spt&& echo ""   （"cid":"v5763spt"）

踢出去再关闭SRS ,这样.tmp文件会转变为.mp4
