### ISSUE TITLE
SRT: Stutter/Choppy/Glitch covert to RTMP. After converting to RTMP, there is jitter.

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#3164]
SRS 5.0, after coverting SRT to RTMP, the streaming is stuttering/choppy/glitch.

Replay:

1. Start SRS 5.0 by docker. v5.0.59
2. Publish to SRS by FFmpeg, source is `doc/source.flv`.
3. Play by RTMP or FLV, the stream is stuttering/choppy/glitch.

`TRANS_BY_GPT3`

**Comment by xiaozhihong** [comment]
Occasionally, certain videos will appear, such as the built-in [Avatar flv](https://github.com/ossrs/srs/blob/develop/trunk/doc/source.200kbps.768x320.flv) in SRS.

From the observation, it appears that the timestamp of the pulled stream elapses faster than the timestamp of the pushed stream. In other words, if the stream is pushed for 10 seconds, the playback has already advanced to around 18 seconds.
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/8449258/188152955-dddd0bc7-44d7-4954-9f68-9dc7afb6fd10.png">

Upon analyzing the code, it was found that the lack of proper interleaving of audio and video timestamps resulted in jitter correction.

After analysis, it was found that SRT streaming uses MPEG-TS payload, where audio is combined and sent in multiple packets. From this problematic video, it can be observed that 16 audio frames are combined to form a single PES packet.
<img width="409" alt="image" src="https://user-images.githubusercontent.com/8449258/188151830-b4f683dc-1cb1-4f49-9c6d-069da132e2f3.png">

`TRANS_BY_GPT3`

**Comment by xiaozhihong** [comment]
There are several solutions:
1. Open ATC, which is the absolute timestamp, so that jitter will not be enabled. However, this may cause other issues.
2. Add a fixed offset to the timestamp of SRT, which may result in audio and video being out of sync.
3. Use mix_correct.
4. Avoid caching audio when streaming.

The final choice is 4. Add the parameter `-pes_payload_size 0` to FFmpeg. The command is as follows:

```bash
ffmpeg -re -i ./doc/source.flv -c copy -pes_payload_size 0 \
  -f mpegts 'srt://127.0.0.1:10080?streamid=#!::r=live/livestream,m=publish'
```

`TRANS_BY_GPT3`
