### ISSUE TITLE
EDGE服务器，配置了 rtmp_to_rtc , WEBRTC 收看黑屏 ， hls m3u8 没问题

### ISSUE THREAD

**Issue by walletiger** [ossrs/srs#3168]
srs 版本: 4.0.251
edge配置: 跟  rtc相关
rtc_server {
    enabled on;
    listen 1938;
    candidate *;
    merge_nalus off;
}

vhost __defaultVhost__ {
    enabled         on;
    gop_cache       off;
    queue_length    10;
    cluster {
        mode        remote;
        origin 172.16.7.12:1935;
    }
    hls {
        enabled         on;
        hls_fragment    2;
        hls_window      5;
        #hls_dts_directly on;
        hls_on_error    continue;
        hls_path        /data/records/live;
        hls_m3u8_file   [stream].m3u8;
        hls_ts_file     [stream]-[seq].ts;
    }

rtc {
        enabled on;
        nack on;
        bframe discard;
        rtmp_to_rtc on;
    }
}

抓包看 webrtc ice 握手成功，dtls handshake 成功，没有向客户端发送媒体 数据 
日志中的状态 
RTC: Server conns=1, rpkts=(1,rtp:0,stun:1,rtcp:1), spkts=(1,rtp:0,stun:1,rtcp:0), fid=(id:0,fid:1,ffid:0,addr:1,faddr:1)

[srs.2022-09-05_1.log](https://github.com/ossrs/srs/files/9488038/srs.2022-09-05_1.log)

**Comment by walletiger** [comment]
抓包文件 
[rtc_udp_port_1938.zip](https://github.com/ossrs/srs/files/9488105/rtc_udp_port_1938.zip)

**Comment by winlinvip** [comment]
这个问题在[Wiki](https://ossrs.net/lts/zh-cn/docs/v4/doc/introduction)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716
