### ISSUE TITLE
希望增加类似zlmedia的自动添加静音音频功能

### ISSUE THREAD

**Issue by ladycwd** [ossrs/srs#3175]
希望增加类似zlmedia的自动添加静音音频功能
用了很长一段时间的srs4.0发现首屏打开慢，如果快速切换视频大概两到三次会出现播放器报错，然后视频需要很久才加载出来，后来换成zlmedia后首屏秒开，而且无论怎样快速切换视频多少次也不会出现srs的情况，后来发现如果推流视频源里面如果有音频SRS也能做到首屏秒开，但有些场景的视频源里面不合适有音频的存在，这个时候就需要服务端能自动为每一路无音频的视频源添加上一条静音的音频

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
