### ISSUE TITLE
GB28181: SRS 5.0 has already supported GB-2016, with built-in SIP signaling and TCP single-port transmission media.

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#3176]
Supporting GB28181 is the right thing to do, and it may also be a challenging thing to do, because challenges make things interesting.

See [English](https://ossrs.io/lts/en-us/docs/v6/doc/gb28181) or [Chinese](https://ossrs.net/lts/zh-cn/docs/v6/doc/gb28181)

## Latency

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2777660/205198483-09e927a4-3e78-46c3-9c0b-1c187b798071.png">

Under intranet conditions, GB/TCP does not increase latency.

**Comment by pedoc** [comment]
> There is no particularly good SIP library in C++, which is also one of the reasons for the unstable SIP handling.

The SIP protocol has support for [The eXtended osip library](https://savannah.nongnu.org/projects/exosip).

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
我测试了下最多跑了13小时，由于我家里设备不方便长期测试，欢迎大家跑一跑，看最长能跑多久。

<img width="784" alt="image" src="https://user-images.githubusercontent.com/2777660/194291468-6241ec58-d454-4f28-a60f-2d0cc62518ad.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/2777660/194291491-a88fea1c-239c-4bde-9fe2-f265611cb821.png">

<img width="820" alt="image" src="https://user-images.githubusercontent.com/2777660/194291503-c58a67af-0e80-49d4-986a-1a9dadae048c.png">

**Comment by 402939556** [comment]
国标SIP configuration, does it not support password authentication?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
We need to refine the lazy object to shared_ptr, see https://github.com/ossrs/srs/discussions/3667#discussioncomment-8969107

**Comment by LeiYangGH** [comment]
is it enabled by default in docker version?
