### ISSUE TITLE
视频流能播放但是控制台视频流列表里状态显示无流且名字变成了数字

### ISSUE THREAD

**Issue by agsea** [ossrs/srs#3182]
SRS Version(版本): 5.0.28
![图片](https://user-images.githubusercontent.com/20497891/191283425-12d8f099-6a45-4ce9-a2a6-de6f68354764.png)

**Replay(重现)**
多个视频流长时间推流（一天以上）

**Expect(期望行为)**
能播放的视频流状态正常显示，且流名称也正常显示

**Comment by winlinvip** [comment]
版本太老。

该Issue会被删除，请在Issues中搜索。#2716
