### ISSUE TITLE
ffmpeg streaming error: Packet is missing PTS

### ISSUE THREAD

**Issue by Aniu-hub** [ossrs/srs#3185]
The account and password for the camera are correct, and the RTSP stream can be played in VLC. However, when using ffmpeg to pull the stream, an error occurs: "Packet is missing PTS.
![image](https://user-images.githubusercontent.com/69847948/191675616-c286ddc0-7544-4ee2-ab60-50a5f5d79180.png)

The configuration being used is:
![image](https://user-images.githubusercontent.com/69847948/191675903-b9e06dd5-91f8-4933-a183-63a08aa3c840.png)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is not an SRS issue, but rather an issue with FFmpeg, WebRTC, client, OBS, reverse proxy Nginx, stream content, and compilation tools. #2716

`TRANS_BY_GPT3`
