### ISSUE TITLE
Configure the slice to be 2 seconds, the streaming GOP also 2 seconds, but the HLS slice is 3.960 seconds.

### ISSUE THREAD

**Issue by dearplain** [ossrs/srs#3191]
**Description**

**SRS Version: 4.0.258**

**Push streaming command:**
```bash
ffmpeg -re -f lavfi -i testsrc2=s=600x400 -c:v libx264 -x264opts keyint=50:no-scenecut \
 -r 25 -f flv -y rtmp://localhost/live/teststream
```

**SRS configuration**
```
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_td_ratio    1.0;
        hls_fragment    2;
        hls_window      30;
    }
}
```

**m3u8 output:**
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:844
#EXT-X-TARGETDURATION:4
#EXTINF:3.960, no desc
teststream-844.ts
#EXTINF:3.960, no desc
teststream-845.ts
#EXTINF:3.960, no desc
....
```

**Expect (Expected Behavior)**

**Should be sliced for 2 seconds**
```
#EXT-X-TARGETDURATION:2
EXTINF:2.0
```

`TRANS_BY_GPT3`

**Comment by dearplain** [comment]
gop is 2s, that's correct, but srs missed one frame time, so if you want to cut it into 2s, you can only change hls_fragment to a value smaller than 2s.
After the modification, the output should be as follows, with the duration on EXTINF being 2?

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:2
#EXT-X-DISCONTINUITY
#EXTINF:1.960, no desc
teststream-0.ts
#EXTINF:1.960, no desc
teststream-1.ts
#EXTINF:1.960, no desc
teststream-2.ts
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This time cannot be precisely equal to your slice time. The distance between frames is not in whole numbers, and there is no requirement for it to be so. The client also does not demand this.

`TRANS_BY_GPT3`
