### ISSUE TITLE
这个问题，  我这边也出现过。  断网重连我这边使用同一个 StreamUrl时， 会报 rtc流busy。

### ISSUE THREAD

**Issue by haiyiya** [ossrs/srs#3192]
这个问题，  我这边也出现过。  断网重连我这边使用同一个 StreamUrl时， 会报 rtc流busy。

_Originally posted by @Timnf in https://github.com/ossrs/srs/issues/3180#issuecomment-1258841527_
      我也是断网遇到这个问题

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
