### ISSUE TITLE
API: Failed to parse the hostname which is single word.

### ISSUE THREAD

**Issue by BrickCarvingArtist** [ossrs/srs#3196]
> Note: Please read FAQ before filing an issue, see 2716

> Note: Before asking a question, please read the FAQ, i.e., 2716

**Description (描述)**'

请确保保持Markdown结构。

> Please describe your issue here (describe the problem you encountered)

1. SRS Version (version): `4.0.265`

2. SRS Log (log):

```
[Error][1][1cu7603n][11] serve error code=3007 : parse message : set url=/api/v1/versions, jsonp=1 : init uri http://srs_server:1985/api/v1/versions : parse url http://srs_server:1985/api/v1/versions failed, code=1
```

3. SRS Config (configuration):

```
Original configuration with http_api, http_callback
```

**Replay (reproduce)**

> Please describe how to replay the bug? (Steps to reproduce the bug)

1. `Setting the hostname with an underscore will cause an error, removing it will not. I guess it's because the underscore is not included in the hostname parsing.`

**Expect (expected behavior)**

> Please describe your expectation (describe what you expect to happen)

The hostname can be parsed when set with an underscore.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is because the http parser considers this hostname to be in an illegal format.

Why do you need to support such a hostname? If it's a K8s service, it can also support the standard domain name method.

**Comment by BrickCarvingArtist** [comment]
I just checked the original standard, and indeed it only supports non-hyphen-starting \w, so it's not considered a bug. It's just that using the service directly as a hostname is more convenient, that's all 😄

**Comment by winlinvip** [comment]
It should be able to support such a name, you can check in more detail. Welcome to submit a patch.
