### ISSUE TITLE
srs 4.0 webrtc api breadcrumb mode causes security issues in production environment

### ISSUE THREAD

**Issue by nihaoma001** [ossrs/srs#3209]
> Note: Please read FAQ before file an issue, see 2716
In version srs4.0-b10, the API interface in the production environment is vulnerable to information leakage due to the breadcrumb return method, posing a high-risk vulnerability.
> Note: Before asking a question, please refer to the FAQ, specifically 2716.

**Description**

> Please describe your issue here
The API interface is undergoing security scanning in the production environment. The breadcrumb return method is causing information leakage and there is a high-risk vulnerability.
1. SRS Version: `xxxxxx`
srs4.0-b10
1. SRS Log:
None

1. SRS Config (Configuration)

Default WebRTC configuration file

**Replay (重现)**

**Accessing the http://ip:1985 port will return the prompt data. Regardless of the characters entered after the path, the backend access prompt content will be returned.**

**Expect (Expected Behavior)**

In a production environment, disable the content returned by breadcrumbs and block the prompt content.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Even if the breadcrumbs are hidden, attackers can still guess the path of your API. The secure practice is to authenticate the API. Please refer to the relevant WIKI for more information.

`TRANS_BY_GPT3`
