### ISSUE TITLE
[Technical Consultation] Can rtmp2rtc calculate the real-time delay of rtmp push and webrtc pull?

### ISSUE THREAD

**Issue by SuperChrisliu** [ossrs/srs#3211]
**Description**

Can I ask, my requirement is for a web page (WebRTC) and a mini program (RTMP) to have a 1v1 intercom. SRS implements the conversion between RTMP and RTC. On the web side, one Connection is responsible for sending, and another Connection is responsible for receiving. In this case, if I want to calculate the delay of the receiving Connection, which is the delay from the RTMP side to the WebRTC side, using the [WebRTC getStats API](https://www.webrtc-experiment.com/getStats/) on the web side, is it possible?

Can we calculate the delay in SFU mode using the [WebRTC getStats API](https://www.webrtc-experiment.com/getStats/)? This demo is for P2P mode.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/7054257/195780112-41486435-ea42-4135-b0d6-961925440434.png">

Does the "round trip time" in the charts of `chrome://webrtc-internals/` represent the delay?

1. SRS Version: v4.0-r3

1. SRS Log:

```
xxxxxxxxxxxx
```

1. SRS Config:

```
xxxxxxxxxxxx
```

**Replay:**

**Expect:**

**能够计算从rtmp推流到webrtc拉流音频的实时延迟**

**Translation:**

Able to calculate real-time audio latency from rtmp streaming to webrtc playback.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is not an SRS issue, but rather a problem with FFmpeg, WebRTC, client, OBS, reverse proxy Nginx, stream content, and compilation tools. This issue will be deleted. #2716

`TRANS_BY_GPT3`
