### ISSUE TITLE
webrtc2rtmp 用ffmpeg 转发 rtmp推流时，报av_interleaved_write_frame(): End of fileB Error writing trailer of rtmps:

### ISSUE THREAD

**Issue by zhangyong7887** [ossrs/srs#3214]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**
 我们想实现一个这样的小功能，在web端利用webrtc技术向SRS的webrtc 服务推流，然后再通过 ffmpeg 把 SRS的 rtmp 流 向 facebook的go live 上推送直播。但我们遇到一个问题，在用ffmpeg 转发推流时，报av_interleaved_write_frame(): End of fileB Error writing trailer of rtmps://live-api-s.facebook.com:443/rtmp/* 的错误， 想请各位大侠帮忙指导下，看是问题可能出现在那些地方，
      
我们执行的命令为：./ffmpeg -threads 2  -thread_queue_size 9512 -re -i "rtmp://xxx.xxx.xxx:1935/live/******" -max_muxing_queue_size 1024  -force_key_frames  "expr:gte(t,n_forced*2)" -vf crop=in_w:in_w*9/16,scale=1280:720 -reorder_queue_size 4000 -max_delay 10000000 -c:v libx264 -preset veryfast -b:v 3000k -maxrate 1500k -bufsize 4000k  -g 50 -c:a aac -ac 2 -ar 48000 -f flv -r 30  -flvflags no_duration_filesize  "rtmps://live-api-s.facebook.com:443/rtmp/*****"

ffmpeg版本为：4.13 及更高版本均一样错误。
SRS版本：5.56
配置如下：
rtc_server {
        enabled on;
        listen  8030;
        candidate       x.x.x.x; #$CANDIDATE;
        merge_nalus on;
}

vhost __defaultVhost__ {
    #srt {
    #    enabled     on;
    #    srt_to_rtmp on;
    #}
    tcp_nodelay     on;
    min_latency     on;

    play {
        time_jitter     full;
        #gop_cache       off;
        queue_length    10;
        mw_latency      350;
        mw_msgs         8;
        send_min_interval 6.0;
        mix_correct     on;
   }

    publish {
        mr off;
        mr_latency  350;
    }
    rtc {
        enabled on;
        #nack on;
        #twcc on;
        bframe  discard;
        stun_timeout 60
        keep_bframe off;
        pli_for_rtmp 3
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
