### ISSUE TITLE
SRS集群是否支持webrtc拉流

### ISSUE THREAD

**Issue by starise-wg** [ossrs/srs#3226]
**SRS集群是否支持webrtc拉流**

> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本): `4.0`

1. SRS Log(日志):

```
无
```

1. SRS Config(配置):

```
无
```

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**Expect()**

> 现有SRS支持webrtc，请问在集群模式下是否可以部署支持webrtc呢，基于现有官网webrtc demo实现集群部署

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
