### ISSUE TITLE
httpserver /api/v1/stream 只能获取10路正在推流的信息

### ISSUE THREAD

**Issue by aiaa5505** [ossrs/srs#3228]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**
本地开了 15路流推到srs http server ,但是通过/api/v1/stream 接口 始终只能获取10路流的信息

1. SRS Version(版本): `ossrs/srs:5.0.63` 镜像

1. SRS Log(日志):

```

```

1. SRS Config(配置):
```
listen              1935;
max_connections     1000;
#srs_log_tank        file;
#srs_log_file        ./objs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
     cluster {
        # local: It's an origin server, serve streams itself.
        # remote: It's an edge server, fetch or push stream to origin server.
        mode            local;
        origin_cluster      on;
        coworkers           srs2:8081;
    }
}
```

**Replay(重现)** 
必现

> Please describe how to replay the bug? (重现Bug的步骤)
docker 的启动命令
sudo docker run --rm -itd --log-opt max-size=10m --log-opt max-file=3 --name=srs1 -p 1935:1935 -p 1985:1985 -p 8080:8080 \
-v ~/srs1.conf:/srs1.conf \
ossrs/srs:v5.0.63 ./objs/srs -c ./objs/srs -c /srs1.conf

**Expect(期望行为)**
希望通过api 接口能查询到所有流的信息和状态，

> Please describe your expectation(描述你期望发生的事情)

**Comment by Aniu-hub** [comment]
同样的问题，请问一下您现在解决了吗
