### ISSUE TITLE
webrtc 中的缓存问题

### ISSUE THREAD

**Issue by qiantaossx** [ossrs/srs#3280]
想讨论下，rtmp 推流，webrtc 播放的场景中，在 SRS 中通过加上 gop 的缓存，来提高 播放器的起播速度（我们的场景可以接受一定程度的快进或者跳秒，代替黑屏）
想请教一下对 webrtc 的播放器来说，是否会有兼容问题，是否合适

**Comment by winlinvip** [comment]
WebRTC有个播放缓冲区设置，详细可以参考WebRTC文档哈。

这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
