### ISSUE TITLE
webrtc playback issues on web pages

### ISSUE THREAD

**Issue by nonobject14514** [ossrs/srs#3285]
> Note: Please read FAQ before file an issue, see 2716

> Note: Before asking a question, please refer to the FAQ, specifically 2716.

**Description (描述)**

> Please describe your issue here (描述你遇到了什么问题)  
Make sure to maintain the markdown structure.

1. SRS Version (版本): `xxxxxx`  
Make sure to maintain the markdown structure.
SRS/5.0.89
1. SRS Log (日志):  
Make sure to maintain the markdown structure.

```
xxxxxxxxxxxx
```

1. SRS Config (配置):  
Make sure to maintain the markdown structure.

```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
#srs_log_tank        file;
#srs_log_file        ./objs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8001;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate 0.0.0.0;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }

    play{
        gop_cache_max_frames 2500;
    }
}

```

**Replay (重现)**  
Make sure to maintain the markdown structure.

> Please describe how to replay the bug? (重现Bug的步骤)  
Make sure to maintain the markdown structure.

I can stream through the internal IP and watch it normally using a browser with WebRTC. However, when using an external domain name, I cannot watch it properly. It keeps loading. I have already allowed UDP on port 1935. Regardless of whether I write the public IP, domain name, or 0.0.0.0 as the candidate, the issue cannot be resolved.

**Expect (Expected Behavior)**

> Please describe your expectation
I expect that the website can be accessed online through a domain name.

`TRANS_BY_GPT3`

**Comment by abigailcg** [comment]
0.0.0.0 配置成公网IP

**Comment by abigailcg** [comment]
Translate to English:
'candidate is configured as a public IP
1. If the rtc video is embedded in another webpage, and that webpage is using https, your webrtc service also needs to have a certificate.
2. If it is a video playback test page using IP+port, then rtc cannot use the domain name method, and instead use the webrtc://public IP/xxx method for playback.

`TRANS_BY_GPT3`

**Comment by nonobject14514** [comment]
The issue has been resolved by adding HTTPS to the API server, thank you.

`TRANS_BY_GPT3`
