### ISSUE TITLE
SRS v6.0.4中SRT对于TS的兼容性有问题；

### ISSUE THREAD

**Issue by superszhu** [ossrs/srs#3290]
**Description(描述)**

> Please description your issue here(描述你遇到了什么问题)

SRS Version(版本): `V6.04`

1. SRS Log(日志):
[WARN][62257][86r1n530][22] parse ts packet err=code=4021(CasterTsCodec)(Invalid ts codec for stream caster) : ts: handle ts message : ts: unsupported stream codec=36
thread [62257][86r1n530]: decode() [./src/kernel/srs_kernel_ts.cpp:273][errno=22]
thread [62257][86r1n530]: on_ts_message() [./src/app/srs_app_srt_source.cpp:342][errno=22]
[WARN][62257][86r1n530][22] parse ts packet err=code=4019(CasterTsPse)(Invalid ts PSE payload for stream caster) : ts: ts packet decode : ts: demux payload : ts: PES fresh packet length=0, us=0, cc=10
thread [62257][86r1n530]: decode() [./src/kernel/srs_kernel_ts.cpp:264][errno=22]
thread [62257][86r1n530]: decode() [./src/kernel/srs_kernel_ts.cpp:629][errno=22]
thread [62257][86r1n530]: decode() [./src/kernel/srs_kernel_ts.cpp:1955][errno=22]

1. SRS Config(配置):
1）采用标准的 ./objs/srs -c ./conf/srt.conf 启动；
2）h265=on; srt=on

2、centOS 7.3上 使用 ./ffmpeg -re -stream_loop -1 -i ../videos/8K60P_30M.mp4 -c copy -f mpegts 'srt://192.168.2.22:10080?streamid=#!::h=live/v6,m=publish'  推SRT流；
     
win10 上使用 ffplay -vcodec hevc_cuvid -x 1280 srt://192.168.2.22:10080?streamid=#!::h=live/v6,m=request  拉流

3、SRS v6.0.4 －－〉ffplay 无法收流；
     SRS v5.019 (srs-gb28181-feature-h265) －－〉ffplay 正常收流；

4、SRS v5.019：码流越大，终端马赛克越多，推到60M时，ffplay卡顿严重；
    使用libsrt1.5 一对一的推拉流，ffplay/VLC在终端体验比 SRS v5.019 要好很多；

**Expect(期望行为)**
1、SRS v6.0.4 能更好兼容 TS，播放能流畅；

**Comment by winlinvip** [comment]
目前SRT还没支持HEVC。
