### ISSUE TITLE
webrtc点击播放黑屏没画面

### ISSUE THREAD

**Issue by 2021-cm** [ossrs/srs#3294]
按照官网demo  
https://ossrs.net/lts/zh-cn/docs/v4/doc/getting-started-build#webrtc
部署  
ffmpeg -re -i ./doc/source.flv -c copy -f flv rtmp://localhost/live/livestream 推流
结果
![微信截图_20221205135245](https://user-images.githubusercontent.com/34293473/205559671-cf2e1d4b-a558-4590-a692-c856ac239b3d.png)
SRS Version(版本):   
4.0release
SRS Log(日志):
![微信截图_20221205135542](https://user-images.githubusercontent.com/34293473/205559928-47f2bba8-d222-46a6-9cd3-e8de339e8ef4.png)

xxxxxxxxxxxx
![微信截图_20221205135610](https://user-images.githubusercontent.com/34293473/205559939-1034864d-fad4-466a-afcf-7d1e0ca112e8.png)
SRS Config(配置):
默认配置
```
xxxxxxxxxxxx
```

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)
按照官网文档步骤

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)

 obs  rtmp 推流 webrtc 可以看

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
