### ISSUE TITLE
请教一个webrtc拉流的问题，能不能在不用转码的情况下，拉流sdk通过修改sdp内容达到降低拉流码率或带宽的目的,使用Simulcast可以吗

### ISSUE THREAD

**Issue by timfengzi** [ossrs/srs#3299]
> Note: Please read FAQ before file an issue, see 2716

> Note: 提问前，请先看FAQ, 即 2716

**Description(描述)**

> Please description your issue here(描述你遇到了什么问题)

1. SRS Version(版本): `xxxxxx`

1. SRS Log(日志):

```
xxxxxxxxxxxx
```

1. SRS Config(配置):

```
xxxxxxxxxxxx
```

**Replay(重现)**

> Please describe how to replay the bug? (重现Bug的步骤)

1. `xxxxxx`
1. `xxxxxx`
1. `xxxxxx`

**Expect(期望行为)**

> Please describe your expectation(描述你期望发生的事情)
能不能在不用转码的情况下，拉流sdk通过修改sdp内容达到降低拉流码率或带宽的目的

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
