### ISSUE TITLE
FEAT: How to do load balancing and service discovery for WEBRTC deployment in K8S

### ISSUE THREAD

**Issue by jinleileiking** [ossrs/srs#3329]
When deploying WebRTC streaming using k8s, you may encounter an issue:

```mermaid
graph TD;
    pod1-->lb-->player;
    pod2-->lb;
    pod3-->lb;
    pod4-->lb;
```

Assuming the streaming is happening in pod1, due to load balancing, UDP packets may be routed to pod3. In this case, there are two possible solutions:

1. Introduce a proxy to handle WebRTC signaling messages, which is a complex solution. Refer to the solution provided in https://github.com/ossrs/srs/issues/3138.
```mermaid
graph TD;
    pod1-->proxy-->lb-->player;
    pod2-->proxy;
    pod3-->proxy;
    pod4-->proxy;
```
2. pod3, find pod1 and start pulling the stream.
```mermaid
graph TD;
    pod1-->lb-->player;
    pod2-->lb;
    pod3-->lb;
    pod4-->lb;
    pod3-->pod1;
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
WebRTC Cascading: https://github.com/ossrs/srs/issues/2091

WebRTC Proxy: https://github.com/ossrs/srs/issues/3138

For tens of millions or hundreds of millions of concurrent connections, cascading is a necessary solution, which is quite complex but also highly scalable.

For general situations, Proxy is simple and reliable, with decent scalability support. We will prioritize supporting the Proxy solution.

`TRANS_BY_GPT3`
