### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ossrs/srs#3331]
:thought_balloon: An extra null pointer check is not needed in macros like "srs_freep" and "srs_freepa".

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Sounds good! Would you please file a PR?

**Comment by yashwardhan-jyani** [comment]
Hey @winlinvip , i fixed the issue and submitted a PR on this!

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/pull/3477
