### ISSUE TITLE
 SRT: rtmp conversion in cluster mode

### ISSUE THREAD

**Issue by attiliodrei** [ossrs/srs#3332]
1. SRS Version(版本): `ossrs/srs:5.0-a2`

SRS Config(配置):  mode cluster-> does not work
 
vhost srt.vhost.srs.com {
    cluster {
        mode            remote;
        origin          winlinvip-vhost.srs.com:1935;
        token_traverse on;
    }    
}

SRS Config(配置):  mode transcode-> works
vhost srt.vhost.srs.com {
    transcode live {
      enabled on;
      ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
      engine   {
           enabled on;
            vcodec          copy;
            acodec          copy;
            oformat         flv;
            output  rtmp://winlinvip-vhost.srs.com:1935?token=password;
      }
}

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
