### ISSUE TITLE
srs 可以使用多个cpu的核心吗

### ISSUE THREAD

**Issue by zk1173168848** [ossrs/srs#3343]
![image](https://user-images.githubusercontent.com/49718621/209797209-cbd92553-aedc-431c-b8e4-213d957cb5f6.png)

这边在对srs做压力测试的时候，发现总是用的单核的cpu，想问下srs可以用多核的cpu吗？

**Comment by SPDionysius** [comment]
可以参考以下文章关于SRS现有架构部分https://mp.weixin.qq.com/s/r2jn1GAcHe08IeTW32OyuQ

**Comment by winlinvip** [comment]
这个问题在[Wiki](https://ossrs.net/lts/zh-cn/docs/v4/doc/introduction)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716
