### ISSUE TITLE
推流报错

### ISSUE THREAD

**Issue by zzj917** [ossrs/srs#3344]
> Note: Please read FAQ before file an issue, see #2716

> Note: 提问前，请先看FAQ, 即 #2716

**Description(描述)**

Please description your issue here(描述你遇到了什么问题)
推流(海康全景的摄像头) 报错
1. SRS Version(版本): 4

2. SRS Log(日志):

 serve error code=3001(HlsDecode)(HLS decode av stream failed) : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: consume video : meta update video : demux SPS/PPS : avc decode sequence header
thread [1][h2x7639z]: do_cycle() [./src/app/srs_app_rtmp_conn.cpp:262][errno=0]
thread [1][h2x7639z]: service_cycle() [./src/app/srs_app_rtmp_conn.cpp:456][errno=0]
thread [1][h2x7639z]: do_publishing() [./src/app/srs_app_rtmp_conn.cpp:1024][errno=11]
thread [1][h2x7639z]: consume() [./src/app/srs_app_recv_thread.cpp:380][errno=11]
thread [1][h2x7639z]: handle_publish_message() [./src/app/srs_app_rtmp_conn.cpp:1161][errno=11]
thread [1][h2x7639z]: process_publish_message() [./src/app/srs_app_rtmp_conn.cpp:1189][errno=11]
thread [1][h2x7639z]: on_video_imp() [./src/app/srs_app_source.cpp:2434][errno=11]
thread [1][h2x7639z]: video_avc_demux() [./src/kernel/srs_kernel_codec.cpp:806][errno=11]
thread [1][h2x7639z]: avc_demux_sps_pps() [./src/kernel/srs_kernel_codec.cpp:833][errno=11]

**Expect(期望行为)**

正常推流

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
