### ISSUE TITLE
stream is lost 流会莫名其妙丢失，报错日志在下面，好像是内存溢出或者信道阻塞导致的

### ISSUE THREAD

**Issue by yipeng2001** [ossrs/srs#3351]
> Note: Please read FAQ before file an issue, see #2716

## Description
stream is lost 流会莫名其妙丢失

1. SRS Version: srs_gbs8181

2. SRS Log:
 出现的非常不规则，没有找到有效的日志

3. SRS Config:
 # push gb28181 stream to SRS. 
#  
listen                  1935;
max_connections         1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
}

stats {
    network         0;
}

stream_caster {
    enabled             on;
    caster              gb28181;

    # 转发流到rtmp服务器地址与端口
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400875104
    # [stream] is VideoChannelCodecID(视频通道编码ID) for sip
    # 自动创建的道通[stream] 是‘chid[ssrc]’ [ssrc]是rtp的ssrc
    # [ssrc] rtp中的ssrc
    output              rtmp://127.0.0.1:1935/live/[stream];
    
    # 接收设备端rtp流的多路复用端口
    listen              9000;
    # 多路复用端口类型，on为tcp，off为udp
    # 默认：on
    tcp_enable            on;

    # rtp接收监听端口范围，最小值
    rtp_port_min        58200;
    # rtp接收监听端口范围，最大值
    rtp_port_max        58300;

    # 是否等待关键帧之后，再转发，
    # off:不需等待，直接转发
    # on:等第一个关键帧后，再转发
    wait_keyframe       on;
    
    # rtp包空闲等待时间，如果指定时间没有收到任何包
    # rtp监听连接自动停止，发送BYE命令
    rtp_idle_timeout    30;

    # 是否转发音频流
    # 目前只支持aac格式，所以需要设备支持aac格式
    # on:转发音频
    # off:不转发音频，只有视频
    # *注意*!!!:flv 只支持11025  22050  44100 三种
    # 如果设备端没有三种中任何一个，转发时为自动选择一种格式
    # 同时也会将adts的头封装在flv aac raw数据中
    # 这样的话播放器为自动通过adts头自动选择采样频率
    # 像ffplay, vlc都可以，但是flash是没有声音，
    # 因为flash,只支持11025 22050 44100
    audio_enable        off;

    # 服务器主机号，可以域名或ip地址
    # 也就是设备端将媒体发送的地址，如果是服务器是内外网
    # 需要写外网地址，
    # 调用api创建stream session时返回ip地址也是host
    # $CANDIDATE 是系统环境变量，从环境变量获取地址，如果没有配置，用*
    # *代表指定stats network 的网卡号地址，如果没有配置network，默认则是第0号网卡地址
    # TODO: https://github.com/ossrs/srs/pull/1679/files#r400917594
    # host       $CANDIDATE;
    host 8.210.198.174;

    #根据收到ps rtp包自带创建rtmp媒体通道，不需要api接口创建
    #rtmp地址参数[stream] 就是通道id  格式chid[ssrc]

    auto_create_channel   off;

    sip {
        # 是否启用srs内部sip信令
        # 为on信令走srs, off 只转发ps流
        enabled on;
        
        # sip监听udp端口
        listen              5060;
        
        # SIP server ID(SIP服务器ID).
        # 设备端配置编号需要与该值一致，否则无法注册
        serial              34020000002000000002;

        # SIP server domain(SIP服务器域)
        realm               3402000000;

        # 服务端发送ack后，接收回应的超时时间，单位为秒
        # 如果指定时间没有回应，认为失败
        ack_timeout         30;

        # 设备心跳维持时间，如果指定时间内(秒）没有接收一个心跳
        # 认为设备离线
        keepalive_timeout   120;

        # 注册之后是否自动给设备端发送invite
        # on: 是  off 不是，需要通过api控制
        auto_play           on;
        # 设备将流发送的端口，是否固定
        # on 发送流到多路复用端口 如9000
        # off 自动从rtp_mix_port - rtp_max_port 之间的值中
        # 选一个可以用的端口
        invite_port_fixed     on;

        # 向设备或下级域查询设备列表的间隔，单位(秒)
        # 默认60秒
        query_catalog_interval  60;
    }
}

rtc_server {
    enabled         on;
    # Listen at udp://8000
    listen          8000;
    #
    # The $CANDIDATE means fetch from env, if not configed, use * as default.
    #
    # The * means retrieving server IP automatically, from all network interfaces,
    # @see https://github.com/ossrs/srs/issues/307#issuecomment-599028124
    # candidate       $CANDIDATE;
    candidate 8.210.198.174;
}
#  这里是webrtc的配置，也是降低直播延迟的重要配置！！！
vhost __defaultVhost__ {
    rtc {
        enabled     on;
        bframe      discard;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
    }
    #可以将HLS延迟降低到3-5秒：
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    0.2;
        hls_window      2;
        hls_wait_keyframe  off;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

## Replay

Please describe how to replay the bug?

Step 1:
1. 启动srs 
2. 这时流会自动加载上
3. 打开客户端拉流，过一会后，有流就变成无流
 

## Expect

请给出大概的解决问题的思路，大概什么原因导致的

**Comment by yipeng2001** [comment]
找到报错日志了 ： [2023-01-02 11:51:49.605][Trace][39858][n4i287k9] TCP: before dispose resource(HttpStream)(0x555555f589f0), conns=5, zombies=0, ign=0, inz=0, ind=0
[2023-01-02 11:51:49.605][Error][39858][n4i287k9][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [39858][n4i287k9]: process_requests() [src/app/srs_app_http_conn.cpp:185][errno=62]
thread [39858][n4i287k9]: parse_message() [src/protocol/srs_service_http_conn.cpp:98][errno=62]
thread [39858][n4i287k9]: parse_message_imp() [src/protocol/srs_service_http_conn.cpp:161][errno=62]
thread [39858][n4i287k9]: grow() [src/protocol/srs_protocol_stream.cpp:162][errno=62]
thread [39858][n4i287k9]: read() [src/protocol/srs_service_st.cpp:522][errno=62](Timer expired)
[2023-01-02 11:51:49.605][Trace][39858][1625393o] TCP: clear zombies=1 resources, conns=5, removing=0, unsubs=0
[2023-01-02 11:51:49.605][Trace][39858][n4i287k9] TCP: disposing #0 resource(HttpStream)(0x555555f589f0), conns=5, disposing=1, zombies=0
[2023-01-02 11:51:49.611][Trace][39858][h074fp69] TCP: before dispose resource(HttpStream)(0x555555f57400), conns=4, zombies=0, ign=0, inz=0, ind=0
[2023-01-02 11:51:49.612][Error][39858][h074fp69][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [39858][h074fp69]: process_requests() [src/app/srs_app_http_conn.cpp:185][errno=62]
thread [39858][h074fp69]: parse_message() [src/protocol/srs_service_http_conn.cpp:98][errno=62]
thread [39858][h074fp69]: parse_message_imp() [src/protocol/srs_service_http_conn.cpp:161][errno=62]
thread [39858][h074fp69]: grow() [src/protocol/srs_protocol_stream.cpp:162][errno=62]
thread [39858][h074fp69]: read() [src/protocol/srs_service_st.cpp:522][errno=62](Timer expired)
[2023-01-02 11:51:49.612][Trace][39858][1625393o] TCP: clear zombies=1 resources, conns=4, removing=0, unsubs=0
[2023-01-02 11:51:49.612][Trace][39858][h074fp69] TCP: disposing #0 resource(HttpStream)(0x555555f57400), conns=4, disposing=1, zombies=0
[2023-01-02 11:51:49.613][Trace][39858][04f98485] TCP: before dispose resource(HttpStream)(0x555555f59170), conns=3, zombies=0, ign=0, inz=0, ind=0
[2023-01-02 11:51:49.613][Error][39858][04f98485][62] serve error code=1011 : parse message : parse message : grow buffer : read bytes : timeout 15000 ms
thread [39858][04f98485]: process_requests() [src/app/srs_app_http_conn.cpp:185][errno=62]
thread [39858][04f98485]: parse_message() [src/protocol/srs_service_http_conn.cpp:98][errno=62]
thread [39858][04f98485]: parse_message_imp() [src/protocol/srs_service_http_conn.cpp:161][errno=62]
thread [39858][04f98485]: grow() [src/protocol/srs_protocol_stream.cpp:162][errno=62]
thread [39858][04f98485]: read() [src/protocol/srs_service_st.cpp:522][errno=62](Timer expired)

**Comment by winlinvip** [comment]
GB已经合并到5.0，请使用5.0.100+的版本。该Issue会被删除，请先阅读FAQ：#2716
