### ISSUE TITLE
SRT:Process packet : invalid ts packet first=0x57

### ISSUE THREAD

**Issue by bigmisspanda** [ossrs/srs#3368]
## Description

When using ffmpeg to push multiple SRT streams to SRS, an error occurs while parsing TS packets.

1. SRS Version: /srs-server-5.0-a2
2. SRS Log:

```
[2023-01-08 13:54:15.882][ERROR][12265][334u0b26][4] srt serve error code=6006(SrtConnection)(SRT connectin level error) : srt: process packet : invalid ts packet first=0x57
```
ffmpeg log:
```
13:54:16.220994/ffmpeg*E:SRT.ea: remove_usock: @280805110 not found as either socket or group. Removing only from epoll system.
[srt @ 0xaaaae5d6f730] Operation not supported: Invalid socket ID: Operation now in progress
av_interleaved_write_frame(): Operation now in progress
Error writing trailer of srt://192.168.2.125:10080?passphrase=fcymfcymfcym&pbkeylen=16&streamid=#!::h=live/livestream,m=publish: Operation now in progress
```

3. SRS Config:

```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
#srs_log_tank        file;
#srs_log_file        ./objs/srs.log;
daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

srt_server {
    enabled on;
    listen 10080;
    maxbw 1000000000;
    connect_timeout 4000;
    peerlatency 0;
    recvlatency 0;
    latency 0;
    tsbpdmode off;
    tlpktdrop off;
    sendbuf 2000000;
    recvbuf 2000000;
    passphrase fcymfcymfcym;
    pbkeylen 16;
}

rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}
vhost __defaultVhost__ {
    publish_normal_timeout  120000;
    hls {
        enabled         on;
    }
    dvr {
        enabled      off;
        dvr_path     ./objs/nginx/html/[app]/[stream]/[2006]/[01]/[02]-[15].[04].[05].[999].flv;
        dvr_plan     segment;
        dvr_duration    30;
        dvr_wait_keyframe       on;
    }
    srt {
        enabled     on;
        srt_to_rtmp on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }

    http_hooks {
# whether the http hooks enalbe.
        # default off.
        enabled off;

        on_play https://192.168.0.162:7790/register/onPlay;
        on_publish https://192.168.0.162:7790/register/on_publish;
        on_dvr     http://127.0.0.1:8085/api/v1/dvrs;
}
    play{
        gop_cache_max_frames 2500;
    }
}
```

## Replay

Step 1: Start streaming task A.
#3361 
```
ffmpeg  -rtsp_transport udp -i  rtsp://admin:xxx@192.168.2.216:554/h264/ch1/sub/av_stream -rw_timeout 6000000  -an -r 25 -codec copy -f mpegts 'srt://192.168.2.125:10080?passphrase=fcymfcymfcym&pbkeylen=16&streamid=#!::h=live/livestream002,m=publish'

```

Step 2: Start streaming task B.

```
ffmpeg  -rtsp_transport udp -i  rtsp://admin:xxx@192.168.2.216:554/h264/ch1/sub/av_stream -rw_timeout 6000000  -an -r 25 -codec copy -f mpegts 'srt://192.168.2.125:10080?passphrase=fcymfcymfcym&pbkeylen=16&streamid=#!::h=live/livestream,m=publish'

```

Task A is streaming steadily, but task B stops streaming quickly (about every 10 minutes). The SRS log prints "srt: process packet: invalid ts packet first=0x57". The streams being pulled are from the same camera.

## Expect

All the pulling tasks are streaming SRT to SRS steadily.

`TRANS_BY_GPT3`

**Comment by xiaozhihong** [comment]
Can you grab a packet and take a look? This means that the first byte of the ts packet must be 0x47, as specified by the ts standard. It could be a problem with the stream or some other issue with the push. We need to capture a packet and examine it.

`TRANS_BY_GPT3`

**Comment by bigmisspanda** [comment]
Happy New Year, it may be caused by UDP network packet loss resulting in the loss of TS packets. Today, I retested it and encountered a new problem.
SRS LOG:
[2023-02-02 09:52:44.851][ERROR][12265][4d6s5476][4] srt serve error code=6002(**_SrtTimeout_**)(SRT connection is timeout) : srt: recvmsg : wait readable : srt socket 157739261 timeout
thread [12265][4d6s5476]: do_publishing() [./src/app/srs_app_srt_conn.cpp:467][errno=62]
thread [12265][4d6s5476]: recvmsg() [./src/protocol/srs_protocol_srt.cpp:801][errno=62]
thread [12265][4d6s5476]: wait_readable() [./src/protocol/srs_protocol_srt.cpp:861][errno=62](Interrupted system call)
[2023-02-02 09:52:44.851][INFO][12265][qyx850y2] SRT: clear zombies=1 resources, conns=2, removing=0, unsubs=0
[2023-02-02 09:52:44.851][INFO][12265][4d6s5476] SRT: disposing #0 resource(srt-ts-conn)(0x60d0000158c0), conns=2, disposing=1, zombies=0
[2023-02-02 09:52:44.851][INFO][12265][4d6s5476] close srt_fd=157739261
[2023-02-02 09:52:44.863][INFO][12265][29x0734l] cleanup when unpublish
[2023-02-02 09:52:44.863][INFO][12265][29x0734l] cleanup when unpublish, created=1, deliver=1
[2023-02-02 09:52:44.863][INFO][12265][29x0734l] SRT: before dispose resource(srt-ts-conn)(0x60d00002e6e0), conns=1, zombies=0, ign=0, inz=0, ind=0


[2023-02-02 09:52:44.863][ERROR][12265][29x0734l][4] srt serve error code=6002(**_SrtTimeout_**)(SRT connection is timeout) : srt: recvmsg : wait readable : srt socket 157739262 timeout
thread [12265][29x0734l]: do_publishing() [./src/app/srs_app_srt_conn.cpp:467][errno=62]
thread [12265][29x0734l]: recvmsg() [./src/protocol/srs_protocol_srt.cpp:801][errno=62]
thread [12265][29x0734l]: wait_readable() [./src/protocol/srs_protocol_srt.cpp:861][errno=62](Interrupted system call)

Still the same testing scenario, the connection was disconnected after streaming for about 30 minutes. Below is the packet capture file of SRT port 10080 around the time of the abnormal log.
[srtpcap.zip](https://github.com/ossrs/srs/files/10567184/srtpcap.zip)


In packet number 1370, the SRT server closed the external connection.

Before this, the streaming end corresponding to this connection did not send any data for more than 5 seconds. I checked this link.
https://github.com/Haivision/srt/pull/719
It is explained that if the streaming end does not send any data, it will send a heartbeat every second, and if there is still no data after 5 seconds, the connection will be closed. I am wondering if this disconnection is caused by this limitation. At the same time, SRT has parameters to set this 5-second timeout.
https://github.com/Haivision/srt/issues/842
Can the current version of SRS support adding this setting? Sometimes, when the camera's network is unstable and the streaming fails, it is necessary to quickly recover.

`TRANS_BY_GPT3`

**Comment by xiaozhihong** [comment]
> Happy New Year. It may be caused by UDP packet loss resulting in the loss of TS packets. Today, I retested it and encountered a new problem. SRS LOG: [2023-02-02 09:52:44.851][ERROR][12265][4d6s5476][4] srt serve error code=6002(SrtTimeout)(SRT connection is timeout): srt: recvmsg: wait readable: srt socket 157739261 timeout thread [12265][4d6s5476]: do_publishing() [./src/app/srs_app_srt_conn.cpp:467][errno=62] thread [12265][4d6s5476]: recvmsg() [./src/protocol/srs_protocol_srt.cpp:801][errno=62] thread [12265][4d6s5476]: wait_readable() [./src/protocol/srs_protocol_srt.cpp:861][errno=62](Interrupted system call) [2023-02-02 09:52:44.851][INFO][12265][qyx850y2] SRT: clear zombies=1 resources, conns=2, removing=0, unsubs=0 [2023-02-02 09:52:44.851][INFO][12265][4d6s5476] SRT: disposing #0 resource(srt-ts-conn)(0x60d0000158c0), conns=2, disposing=1, zombies=0 [2023-02-02 09:52:44.851][INFO][12265][4d6s5476] close srt_fd=157739261 [2023-02-02 09:52:44.863][INFO][12265][29x0734l] cleanup when unpublish [2023-02-02 09:52:44.863][INFO][12265][29x0734l] cleanup when unpublish, created=1, deliver=1 [2023-02-02 09:52:44.863][INFO][12265][29x0734l] SRT: before dispose resource(srt-ts-conn)(0x60d00002e6e0), conns=1, zombies=0, ign=0, inz=0, ind=0.
> 
> [2023-02-02 09:52:44.863][ERROR][12265][29x0734l][4] srt serve error code=6002(**_SrtTimeout_**)(SRT connection is timeout) : srt: recvmsg : wait readable : srt socket 157739262 timeout thread [12265][29x0734l]: do_publishing() [./src/app/srs_app_srt_conn.cpp:467][errno=62] thread [12265][29x0734l]: recvmsg() [./src/protocol/srs_protocol_srt.cpp:801][errno=62] thread [12265][29x0734l]: wait_readable() [./src/protocol/srs_protocol_srt.cpp:861][errno=62](Interrupted system call)
> 
> It is still the same test scenario. After streaming for about 30 minutes, the connection was disconnected. Here is the packet capture file of SRT port 10080 around the time of the exception: [srtpcap.zip](https://github.com/ossrs/srs/files/10567184/srtpcap.zip).
> 
> In packet number 1370, the SRT server closed the outbound connection.
> 
> Before this, the streaming end corresponding to this connection did not send any data for more than 5 seconds. I found this link [Haivision/srt#719](https://github.com/Haivision/srt/pull/719) which explains that if the streaming end does not send data, it will send a heartbeat every second, and if there is still no data after 5 seconds, the connection will be closed. I'm wondering if this disconnection is caused by this limitation. At the same time, SRT has a parameter to set this 5-second timeout [Haivision/srt#842](https://github.com/Haivision/srt/issues/842). Can the current version of SRS support adding this setting? Sometimes, when the camera network is unstable and the streaming fails, it can only be quickly recovered.

> SRT has a parameter called `peer_idle_timeout` that can be configured.

```
# The timeout time of SRT connection on the receiver side in ms. When the SRT connection is idle
# more than this config, it will be close.
# Overwrite by env SRS_SRT_SERVER_PEER_IDLE_TIMEOUT
# default: 10000
peer_idle_timeout 8000;
```

`TRANS_BY_GPT3`

**Comment by bigmisspanda** [comment]
Okay, I will test it out. Thank you for your help.

`TRANS_BY_GPT3`
