### ISSUE TITLE
性能：  rtmp推rtc拉的压测下，cpu利用率有些高

### ISSUE THREAD

**Issue by jinleileiking** [ossrs/srs#3373]
`./objs/srs_bench -sr 'webrtc://47.92.7.160/live/a?schema=http'  -nn 100`

单核cpu 在0.6左右，也就是100路拉流就差不多了，有些低

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
