### ISSUE TITLE
hls_ctx function cannot be disabled on version 4.0

### ISSUE THREAD

**Issue by NangenX** [ossrs/srs#3376]
> Note: Please read FAQ before file an issue, see #2716

## Description
SRS/4.0.268, even with hls_ctx off, still enables hls_ctx. Resolve hls_ctx issue by loading SRS/5.0.128 with the same configuration.

SRS Config:

listen               1935;
max_connections      5000;
#srs_log_tank         file;
#srs_log_level        verbose;
http_server {
                     enabled       on;
                     listen        8080;
                     dir           ./objs/nginx/html;
            }
vhost __defaultVhost__ {
hls {
                     enabled       on;
                     hls_path      ./objs/nginx/html;
                     hls_ctx      off;
                     hls_ts_file     [app]/[stream]-[timestamp]-[seq].ts;
                     hls_fragment  5;
                     hls_cleanup     on;
                     hls_dispose     10;
    }
http_hooks {
                    enabled         on;
                    on_hls          http://192.168.2.143:5000/api/srs/on_hls;
}
}

## Expect
Hope to resolve this issue on version 4.0.

`TRANS_BY_GPT3`

**Comment by duiniuluantanqin** [comment]
Version 4.0 did not include the merge of this feature. If you want, you can merge it yourself following the commit below.
https://github.com/ossrs/srs/commit/d39995cc31524d844e896ba687f91c451034243d

`TRANS_BY_GPT3`

**Comment by NangenX** [comment]
Thank you, I will handle it.

`TRANS_BY_GPT3`
