### ISSUE TITLE
请问srs怎样通过url获取和播放已经存储到/trunk/objs/nginx/html/ 路径下的录像 ？如何在SRS网页控制台里面看到录制的视频列表？

### ISSUE THREAD

**Issue by yipeng2001** [ossrs/srs#3381]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here
请问srs怎样通过url获取和播放已经存储到/trunk/objs/nginx/html/ 路径下的录像 ？
 

1. SRS Version: srs 5.0

2. SRS Log:

 

3. SRS Config:
  dvr {
        enabled             off;
        dvr_apply       all;
        dvr_path        ./objs/nginx/html/[stream].[timestamp].flv;
        # dvr_path        ./objs/nginx/html/[app]/[stream].[2023]/[01]/[02]/[15].[04].[05].[999].flv;
        # dvr_path            ./objs/nginx/html/[app]/[stream]/[2006]/[01]/[02]/[15].[04].[05].[999].flv;
        dvr_plan            segment;
        dvr_duration        30;
        dvr_wait_keyframe   on;
        time_jitter             full;
    }
    # 仍需要配置 HTTP回调
    http_hooks {
        enabled         on;
        # on_connect      http://127.0.0.1:8085/api/v1/clients http://localhost:8085/api/v1/clients;
        # on_close        http://127.0.0.1:8085/api/v1/clients http://localhost:8085/api/v1/clients;
        # on_connect    http://http://8.210.198.174:8080/srs_http_call_back;
        # on_dvr         http://172.29.122.88:8089/api/v1/dvrs;
        on_dvr          http://8.210.198.174:8085/api/v1/dvrs  ;
        # on_publish      http://127.0.0.1:8085/api/v1/streams http://localhost:8085/api/v1/streams;
        # on_unpublish    http://127.0.0.1:8085/api/v1/streams http://localhost:8085/api/v1/streams;
        # on_play         http://127.0.0.1:8085/api/v1/sessions http://localhost:8085/api/v1/sessions;
        # on_stop         http://127.0.0.1:8085/api/v1/sessions http://localhost:8085/api/v1/sessions;
        # on_hls          http://127.0.0.1:8085/api/v1/hls http://localhost:8085/api/v1/hls;
        # on_hls_notify   http://127.0.0.1:8085/api/v1/hls/[server_id]/[app]/[stream]/[ts_url][param];
    }
 
```<img width="1390" alt="image" src="https://user-images.githubusercontent.com/66982645/212470810-680c0708-17e1-43fd-91dc-367a563b853a.pn
![811673697913_ pic_hd](https://user-images.githubusercontent.com/66982645/212470859-87bdace9-c3e1-4467-aac1-919a12fb1584.jpg)
g">
## Replay

Please describe how to replay the bug?

Step 1: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 2: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 3: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Expect

Please describe your expectation.

**Comment by winlinvip** [comment]
咨询和讨论请来[视频号直播间](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
