### ISSUE TITLE
SRT转rtmp较慢问题

### ISSUE THREAD

**Issue by whyf0730** [ossrs/srs#3395]
> Note: Please read FAQ before file an issue, see #2716

## Description

使用srt推流至srs，拉流端观看rtmp流，首先发现拉流速度较慢，推拉流都是用rtmp拉流延迟的900ms左右，推拉流都使用srt延迟在500ms左右，但推流使用srt，拉流使用rtmp，延迟在1500ms左右，通过打日志发现，启动rtmp客户端时就耗时近700ms，不知道是否可以优化。

1. SRS Version: 4.0

2. SRS Log:

无

**Comment by xiaozhihong** [comment]
> > Note: Please read FAQ before file an issue, see #2716
> 
> ## Description
> 使用srt推流至srs，拉流端观看rtmp流，首先发现拉流速度较慢，推拉流都是用rtmp拉流延迟的900ms左右，推拉流都使用srt延迟在500ms左右，但推流使用srt，拉流使用rtmp，延迟在1500ms左右，通过打日志发现，启动rtmp客户端时就耗时近700ms，不知道是否可以优化。
> 
> 1. SRS Version: 4.0
> 2. SRS Log:
> 
> 无

启动RTMP客户端耗时近700ms, 是指的哪里?
另外, 播放耗时大部分来自于播放器.

**Comment by whyf0730** [comment]
> > > Note: Please read FAQ before file an issue, see #2716
> > 
> > 
> > ## Description
> > 使用srt推流至srs，拉流端观看rtmp流，首先发现拉流速度较慢，推拉流都是用rtmp拉流延迟的900ms左右，推拉流都使用srt延迟在500ms左右，但推流使用srt，拉流使用rtmp，延迟在1500ms左右，通过打日志发现，启动rtmp客户端时就耗时近700ms，不知道是否可以优化。
> > 
> > 1. SRS Version: 4.0
> > 2. SRS Log:
> > 
> > 无
> 
> 启动RTMP客户端耗时近700ms, 是指的哪里? 另外, 播放耗时大部分来自于播放器.

感谢回复！在SRS4.0上推拉流都使用rtmp的时候，用同样的播放器测试，延迟在900ms以内，但是推流用srt，拉流用rtmp的时候，延迟就达到了1.5秒左右，我描述的可能不太妥当，这700ms是srt连接建立成功后到接收到srt转rtmp的publish之间的时间差值，不知道还能否有优化的空间。谢谢

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
