### ISSUE TITLE
Your OS Linux is not supported.

### ISSUE THREAD

**Issue by phijazz** [ossrs/srs#3403]
Hello, here is my issue:

> uname -rpvsmio
Linux 6.1.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 01 Feb 2023 17:07:37 +0000 x86_64 unknown unknown GNU/Linux

> ./configure 
Enable asan by auto options.
User config: 
Detail config: --prefix=/usr/local/srs --config=conf/srs.conf --osx=off --hls=on --hds=off --dvr=on --ssl=on --https=on --ssl-1-0=off --ssl-local=off --sys-ssl=off --transcode=on --ingest=on --stat=on --http-callback=on --http-server=on --stream-converter=on --http-api=on --utest=off --cherrypy=off --srt=on --rtc=on --h265=off --gb28181=off --simulator=off --cxx11=on --cxx14=off --backtrace=on --ffmpeg-fit=on --ffmpeg-opus=off --nasm=on --srtp-nasm=on --clean=on --gperf=off --gmc=off --gmd=off --gmp=off --gcp=off --gprof=off --static=off --shared-st=off --shared-srt=off --shared-ffmpeg=off --log-verbose=off --log-info=off --log-trace=on --log-level_v2=on --gcov=off --apm=off --debug=off --debug-stats=off --cross-build=off --sanitizer=on --sanitizer-static=off --sanitizer-log=off --cygwin64=off --single-thread=off --cc=gcc --cxx=g++ --ar=ar --ld=ld --randlib=randlib
Discover SRS version=6.0.21, major=6
SRS_WORKDIR: ., SRS_OBJS: ./objs, SRS_PLATFORM: Platform-SRS6-Linux-6.1.9-GCC12.2.1-x86_64
All outputs to: ./objs/Platform-SRS6-Linux-6.1.9-GCC12.2.1-x86_64
Alias python2 as python
Your OS Linux is not supported.

What is the reason?

**Comment by winlinvip** [comment]
The error message is quiet straight forward: Your OS is not supported.

Could you please write more information about your OS? What's the OS, CPU? 

How to replay it? Do you have a cloud environment to relay this issue?

**Comment by winlinvip** [comment]
Can't replay it.
