### ISSUE TITLE
SRS4配置减小延迟的配置，服务器启动后好用（延迟1s），热加载（killall -1 srs）之后延迟变为和没延迟配置的一样(延迟10s),只后再启动，延迟配置也都不好用

### ISSUE THREAD

**Issue by fengyang1** [ossrs/srs#3414]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here

1. SRS Version: x.x.x

2. SRS Log:

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

3. SRS Config:

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Replay

Please describe how to replay the bug?

Step 1: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 2: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 3: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Expect

Please describe your expectation.

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
