### ISSUE TITLE
SrsFormat::hevc_demux_hvcc has a bug, dec_conf_rec_p->nalu_vec needs to be cleared first.

### ISSUE THREAD

**Issue by JalySN** [ossrs/srs#3417]
## Description

Supported versions of HEVC
Multiple calls to SrsFormat::hevc_demux_hvcc will cause the continuous increase of the stored vps sps pps in dec_conf_rec_p->nalu_vec.

`TRANS_BY_GPT3`

**Comment by chundonglinlin** [comment]
see  PR #3411

**Comment by winlinvip** [comment]
Fixed in v6.0.26
