### ISSUE TITLE
docker 构建时发生错误

### ISSUE THREAD

**Issue by na-hui** [ossrs/srs#3422]
docker 构建时发生错误，版本 5.0release：

Step 14/29 : COPY . /srs
 ---> 99969be37e1a
Step 15/29 : WORKDIR /srs/trunk
 ---> Running in 0dd4ecbfc045
Removing intermediate container 0dd4ecbfc045
 ---> 56610f9e6eba
Step 16/29 : RUN ./configure --gb28181=on $ {CONFARGS} && make $ {MAKEARGS} && make install
 ---> Running in fc5f38e3b5f4
/bin/bash: ./configure: No such file or directory
The command '/bin/bash -c ./configure --gb28181=on $ {CONFARGS} && make $ {MAKEARGS} && make install' returned a non-zero code: 127
##[error]The command '/bin/bash -c ./configure --gb28181=on $ {CONFARGS} && make $ {MAKEARGS} && make install' returned a non-zero code: 127
##[error]The process '/usr/bin/docker' failed with exit code 127
Finishing: Build an image

/bin/bash: ./configure: No such file or directory
尝试了不同base，一致报错，使用的docker文件是 trunk/DockerFile ，使用Azure 进行构建 或者 在 centos7 环境下 使用docker build 构建，都是报相同错误。

请问，问题出现哪里？如何解决

**Comment by winlinvip** [comment]
请根据文档操作。该Issue会被删除

**Comment by zhenhao-huang** [comment]
解决了吗

**Comment by shoyu666** [comment]
change WORKDIR /srs/trunk   >>>   WORKDIR /srs
