### ISSUE TITLE
【技术咨询】关于http-flv直播流的读取，解封装

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ossrs/srs#3433]
大家好，请教下啊：我从srs拉取http-flv直播流，想提取里面的关键帧，现在的问题是怎么样收到流呢(前提是不用ffmepg的av_read_frame，不想用到ffmepg)，srs有不基于ffmepg的读取http-flv直播流的操作么(读取，解封装)

**Comment by winlinvip** [comment]
咨询和讨论请加[付费星球](https://mp.weixin.qq.com/s/HdSf7qAR94v2Mxdzf2qLAQ)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。

该Issue会被删除，请先阅读FAQ：#2716
