### ISSUE TITLE
how to limit IP publish rtmp

### ISSUE THREAD

**Issue by kawaguchimaeda8** [ossrs/srs#3434]
I installed using docker

docker run --rm -it -p 1935:1935 -p 1985:1985 -p 8080:8080 \
     ossrs/srs:4 ./objs/srs -c conf/docker.conf

after I try

ffmpeg -re -i ./doc/source.flv -c copy -f flv rtmp://localhost/live/livestream

there are no problems, the problem is how to limit the IP that publishes? i tried another IP by trying to make ffmpeg

ffmpeg -re -i ./doc/source.flv -c copy -f flv rtmp://localhost/live/ihackerstream

then it runs, even though it wasn't me who published it.

how do you make the IP settings so that only certain IPs can publish

**Comment by winlinvip** [comment]
这个问题在[Wiki](https://ossrs.net/lts/zh-cn/docs/v4/doc/introduction)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716
