### ISSUE TITLE
iOS原生使用GoogleWebRTC推流

### ISSUE THREAD

**Issue by gloryFlow** [ossrs/srs#3442]
iOS原生使用GoogleWebRTC推流，我在GoogleWebRTC没有找到推流的srs的地址设置呢

您们的iOS上如何使用WebRTC推流的呢？

期待您的回复。

谢谢！！

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
