### ISSUE TITLE
Your OS Linux is not supported (ARM). SRS compilation failed on ARM system.

### ISSUE THREAD

**Issue by wddnzjwd** [ossrs/srs#3443]
Hello everyone, I want to compile SRS for the ARM version. So, I prepared an ARM Linux OS for it.
But I received the error message "Your OS Linux is not supported" when I attempted to compile it. Does anyone know the solution?

1.OS: openEuler 22.03 LTS SP1

2. SRS Version: 4.0

3. Log:
[root@localhost trunk]# uname -a
Linux localhost.localdomain 5.10.0-60.18.0.50.oe2203.aarch64 #1 SMP Wed Mar 30 02:43:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
[root@localhost trunk]# arch
aarch64
[root@localhost trunk]# ./configure 
User config: 
Detail config: --prefix=/usr/local/srs --hls=on --hds=off --dvr=on --ssl=on --https=on --ssl-1-0=off --ssl-local=off --sys-ssl=off --transcode=on --ingest=on --stat=on --http-callback=on --http-server=on --stream-caster=on --http-api=on --utest=off --cherrypy=on --srt=off --rtc=on --h265=on --transmit-rtp=on --simulator=off --gb28181=on --cxx11=on --cxx14=off --ffmpeg-fit=on --nasm=on --srtp-nasm=on --clean=on --gperf=off --gmc=off --gmd=off --gmp=off --gcp=off --gprof=off --static=off --use-shared-st=off --use-shared-srt=off --log-verbose=off --log-info=off --log-trace=on --gcov=off --debug=off --debug-stats=off --cc=gcc --cxx=g++ --ar=ar --ld=ld --randlib=randlib
SRS_WORKDIR: ., SRS_OBJS_DIR: objs, SRS_OBJS: ./objs, SRS_PLATFORM: Platform-Linux-5.10.0-GCC9.5.0-SRS4
Checking gcc/g++/gdb/make.
Required tools are ok.
SED is sed_utility
Your OS Linux is not supported.
[root@localhost trunk]# 

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is because your OS is not Ubuntu/Ubuntu/Debian/macOS/cygwin64, we should support an option for other linux systems:

```
./configure --generic-linux=on
```
