### ISSUE TITLE
WebRTC: The bitrate of transcoding AAC to Opus is too low. The audio quality is severely compromised. We hope the minimum bitrate can be 192Kbps, or provide an option to configure it.

### ISSUE THREAD

**Issue by zlyhsjd** [ossrs/srs#3448]
## Description

Please description your issue here
In the process of rtmp/srt-WebRTC with AAC-opus, the opus bitrate is too low, it seems to be only 64Kbps, causing severe audio quality loss. I hope the minimum can be 192Kbps. The bandwidth occupied by audio is negligible compared to video, so it's fine to increase it a bit. Alternatively, it would be great to have a configurable option to adjust it ourselves. If this suggestion can be adopted, I would be extremely grateful.

1. SRS Version: 5.0

3. SRS Config:

```
listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
srt_server {
    enabled on;
    listen 10080;
    maxbw 1000000000;
    connect_timeout 4000;
    peerlatency 0;
    recvlatency 0;
}
rtc_server {
    enabled on;
    # Listen at udp://8000
    listen 8000;
    #candidate $CANDIDATE;
```
candidate *; # Support any IP, which means letting the server choose by itself, first selecting public IP, then selecting private IP
use_auto_detect_network_ip on; # If this feature is disabled, it will not automatically select IP
ip_family ipv4; # When automatically selecting IP, choose IPv4 or IPv6 address
api_as_candidates on; # Whether to enable this feature. If the API is a separate server, this feature can be disabled
resolve_api_domain on; # If the API is a domain name, whether to resolve the domain name to an IP address. Note that Firefox does not support domain names, so it is generally recommended to enable this
keep_api_domain on; # Whether to keep the domain name of the API. Clients that support domain name resolution can resolve the IP address themselves to avoid server-side resolution
```
}
vhost __defaultVhost__ {
    srt {
        enabled     on;
    }
    rtc {
        enabled     on;
        rtmp_to_rtc on;
        rtc_to_rtmp on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}
```

## Expect

Please describe your expectation.

`TRANS_BY_GPT3`

**Comment by xiaozhihong** [comment]
agree!
