### ISSUE TITLE
SRS 作为边缘节点时remote模式下是否可以启用transcode转码？

### ISSUE THREAD

**Issue by cocozhaocs** [ossrs/srs#3457]
> Note: Please read FAQ before file an issue, see #2716

## Description

      目前在使用SRS构建直播服务器的边缘节点。有个功能是需求在边缘节点减少带宽占用，进行转码。发现边缘节点转码时总是失败，同样的转码规则和配置如果是master 节点则可以成功转码。所以有个疑问是我的配置和操作有问题，还是SRS目前尚不支持边缘节点使用remote模式后转码。
     另外转码后的流地址必须和转码前的不一样吗（看到给出的样例里，都是加上engine区分），是否可以这样设为一样rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]; 设置为一致的话是否存在流名称冲突等问题

1. SRS Version: 3.0.168.

2. SRS Log:ffmpeg的转码日志

Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
    Stream #0:1: Audio: aac (libfdk_aac) ([10][0][0][0] / 0x000A), 44100 Hz, stereo, s16, 128 kb/s
    Metadata:
      encoder         : Lavc57.107.100 libfdk_aac
av_interleaved_write_frame(): Broken pipe
[flv @ 0x231fd20] Failed to update header with correct duration.
[flv @ 0x231fd20] Failed to update header with correct filesize.
Error writing trailer of rtmp://127.0.0.1:1935/livehouse?vhost=__defaultVhost__/livetest: Broken pipe
frame=   49 fps=0.0 q=28.0 Lsize=       1kB time=00:00:02.26 bitrate=   2.1kbits/s speed=3.28x
video:10kB audio:36kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

3. SRS Config:

vhost __defaultVhost__ {
    transcode {
        enabled     on;
        ffmpeg      /home/cdn/livehouse/ffmpeg/bin/ffmpeg;
        engine ff {
            enabled         on;
            vfilter {
            }
            vcodec          libx264;
            vthreads        4;
            vprofile        main;
            vpreset         medium;
            vwidth          768;
            vheight         320;
            vparams {
            }
            acodec          libfdk_aac;
            aparams {
               flvflags no_duration_filesize;
            }
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }

    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    cluster{
        mode remote;
        origin  x.x.x.x:1935;
    }
    
}

## Replay

Please describe how to replay the bug?

Step 1: xxxxxx

启动直播源站，并推流

Step 2: xxxxxx

启动边缘节点拉流，并配置相关转码配置项

Step 3: xxxxxx
客户端从边缘节点拉流，查看日志

## Expect

确定SRS的remote模式是否支持转码，以及转码流名称问题。支持的话，应该如何配置呢

**Comment by winlinvip** [comment]
咨询和讨论请加[付费星球](https://mp.weixin.qq.com/s/HdSf7qAR94v2Mxdzf2qLAQ)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
