### ISSUE TITLE
iOS WebRTC在设置低分辨率如1280x720, SRS可以看到画面，高分辨率3840x2160无法看到画面

### ISSUE THREAD

**Issue by gloryFlow** [ossrs/srs#3466]
CMVideoDimensions videoVideoDimensions = CMVideoFormatDescriptionGetDimensions(formatNilable.formatDescription);
        float width = videoVideoDimensions.width;
        float height = videoVideoDimensions.height;
        [cameraVideoCapturer startCaptureWithDevice:camera format:formatNilable fps:fps completionHandler:^(NSError *error) {
            DebugLog(@"startCaptureWithDevice error:%@", error);
        }];
        [self changeResolution:width height:height fps:(int)fps];

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
