### ISSUE TITLE
请问下怎么判断是否在直播？

### ISSUE THREAD

**Issue by JakeWoki** [ossrs/srs#3478]
/api/v1/streams接口可以查直播列表，但是要轮询比较麻烦，有没有类似websocket之类的做法？

**Comment by winlinvip** [comment]
咨询和讨论请加[付费星球](https://mp.weixin.qq.com/s/HdSf7qAR94v2Mxdzf2qLAQ)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
