### ISSUE TITLE
Using DJI's cloud API, we are streaming through RTMP and converting it to WebRTC for playback. However, there is stuttering and dropped frames when playing locally, while other clients can access it normally.

### ISSUE THREAD

**Issue by hqzqaq** [ossrs/srs#3481]
## Description

Using DJI's cloud API, we are streaming through RTMP and converting it to WebRTC for playback. However, there is stuttering and frame dropping when playing locally, while other clients can access it normally.

1. SRS Version: 4
We have tried deploying using Docker with both v5 and v6 versions, but the problem persists. Previously, we were using DJI's MSDK for streaming, and it was working fine. However, after switching to the cloud API for streaming, we are experiencing abnormalities.

2. SRS Log:

3. SRS Config:

Docker deployment configuration:
```sh
version: '3'

services:
  srs:
    # image: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:4
    image: ossrs/srs:v5
    # image: ossrs/srs:v6
    container_name: srs
    ports:
      - "1935:1935"
      - "1985:1985"
      - "8080:8080"
      - "8000:8000/udp"
    volumes:
      - ./conf:/usr/local/srs/conf
      - ./html:/usr/local/srs/objs/nginx/html
    environment:
      CANDIDATE: $CANDIDATE
    command: ./objs/srs -c conf/rtmp2rtc.conf
    privileged: true
    restart: always
    network_mode: "host"
```

SRS configuration:
```

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}

vhost __defaultVhost__ {
    
    
# Low latency configuration
    tcp_nodelay     on;
    min_latency     on;
    play {
        
        atc auto;
        gop_cache       off;
        queue_length    10;
        mw_latency      100;
    }

    publish {
        mr off;
    }    

    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp off;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    # dvr {
    #     enabled             on;
    #     dvr_path            ./objs/nginx/html/[app]/[stream]/[2006]/[01]/[02]/[15].[04].[05].[999].flv;
    #     dvr_plan            session;
    # }
    http_hooks {
        # enabled         on;
    }
}


```

## Replay

Please describe how to replay the bug?

Step 1: Configure the DJI Cloud API and initiate a live streaming request
On the computer where the SRS server is deployed, if the video stream is stuttering or dropping frames, it plays normally on other clients in the local network and on the public network address accessed through internal network penetration.

## Expect
On the computer where the SRS server is deployed, the video playback is normal. However, we need to deploy some AI algorithms on this computer to process the video stream. Currently, the AI algorithms are failing due to the video stream.

`TRANS_BY_GPT3`

**Comment by hss233** [comment]
Hello, we are also a DJI project, and we encountered a little problem with the live streaming push-pull flow. We mapped the server's IP port to the public network through internal network penetration. In the DJI-demo, we replaced 'rtmp' in 'rtmpurl' with 'webrtc' for return. When the vue end plays, it converts 'webrecurl' to 'http', which prevents the correct pulling of the stream. Could you possibly help me solve this problem?

`TRANS_BY_GPT4`
