### ISSUE TITLE
5.0以上版本，采用gb28181方式如何调用云台？

### ISSUE THREAD

**Issue by lonrown** [ossrs/srs#3493]
gb28181协议海康摄像机，如何通过接口方式控制摄像机？ptz应该如何调用？谢谢

**Comment by winlinvip** [comment]
咨询和讨论请加[付费星球](https://mp.weixin.qq.com/s/HdSf7qAR94v2Mxdzf2qLAQ)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
