### ISSUE TITLE
使用msys2 编译失败

### ISSUE THREAD

**Issue by sg0771** [ossrs/srs#3496]
执行configure提示

$ ./configure
Warning: Your OS is not Ubuntu(no apt-get), CentOS(no yum), maxOS(not Darwin), Windows(not CYGWIN)
Enable asan by auto options.
User config:
Detail config: --prefix=/usr/local/srs --config=conf/srs.conf --osx=off --hls=on --hds=off --dvr=on --ssl=on --https=on --ssl-1-0=off --ssl-local=off --sys-ssl=off --transcode=on --ingest=on --stat=on --http-callback=on --http-server=on --stream-converter=on --http-api=on --utest=off --cherrypy=off --srt=on --rtc=on --h265=off --gb28181=off --simulator=off --cxx11=on --cxx14=off --backtrace=on --ffmpeg-fit=on --ffmpeg-opus=off --nasm=on --srtp-nasm=on --clean=on --gperf=off --gmc=off --gmd=off --gmp=off --gcp=off --gprof=off --static=off --shared-st=off --shared-srt=off --shared-ffmpeg=off --log-verbose=off --log-info=off --log-trace=on --log-level_v2=on --gcov=off --apm=off --debug=off --debug-stats=off --cross-build=off --sanitizer=on --sanitizer-static=off --sanitizer-log=off --cygwin64=off --single-thread=off --generic-linux=off --cc=gcc --cxx=g++ --ar=ar --ld=ld --randlib=randlib
Discover SRS version=6.0.41, major=6
SRS_WORKDIR: ., SRS_OBJS: ./objs, SRS_PLATFORM: Platform-SRS6-MINGW32_NT-10.0-2.9.0(0.318/5/3)-GCCBuilt-x86_64
All outputs to: ./objs/Platform-SRS6-MINGW32_NT-10.0-2.9.0(0.318/5/3)-GCCBuilt-x86_64
Alias python2 as python
Your OS MINGW32_NT-10.0 is not supported.

**Comment by winlinvip** [comment]
暂不支持。

该Issue会被删除，请先阅读FAQ：#2716
