### ISSUE TITLE
关于srt2rtc.conf的使用

### ISSUE THREAD

**Issue by SeanOntheWay** [ossrs/srs#3499]
version：SRS 5
URL：`webrtc://mylocalhost:10080/live/livestream`
想试一试用srt推流rtc拉流，但上面这个好像一直不太对。所以推流srt在用rtc拉流时的URL应该是怎样的？

**Comment by winlinvip** [comment]
这个问题在[Wiki](https://ossrs.net/lts/zh-cn/docs/v4/doc/introduction)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716
