### ISSUE TITLE
自定义平台推流密钥不能设置为空？

### ISSUE THREAD

**Issue by 2331892928** [ossrs/srs#3514]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here

1. SRS Version: 4.6.13

2. SRS Log:

默认

3. SRS Config:

默认

## Replay

Please describe how to replay the bug?

Step 1: 
我需要将直播推流到虎牙，但虎牙的远程推流，只有地址，没有密钥。我将他填到srs后台，当密钥为空时虽然弹窗保存成功，实际保存失败。

## Expect

允许密钥为空，请迅速修复，这么久的开源项目了，居然没人发现这个问题？

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716

**Comment by 2331892928** [comment]
这不是 FFmpeg、WebRTC、客户端、OBS、反代理Nginx、流的内容、编译工具的问题，是你们SRS的问题，是不可为空，设置为空显示保存成功，但实际保存失败。我敲个空格就真正保存成功了，也开始推流了，你应该从自己身上找原因，而不是你的客户和客户使用的工具

**Comment by 2331892928** [comment]
我不懂都没解决为何将我的issus设定为垃圾？如果重复，你丢我issus让我查看，如果提出错误，你应该截图哪句话有错。直接设定为垃圾？请问开源的目的究竟是什么？将你的客户设定为仆人，只提供bug和漏洞，不理想直接垃圾，开源的精神是共同维护，共同探讨，你别开源了，闭源吧

**Comment by 2331892928** [comment]
不能像楼上那个酷酷的一样进行探讨？我真无语了
