### ISSUE TITLE
WebRTC: Failed to handshake with OBS WHIP

### ISSUE THREAD

**Issue by SetoKaiba** [ossrs/srs#3521]
> Note: Please read FAQ before file an issue, see #2716

## Description

WebRTC is not compatible with the WHIP branch of OBS.
The testing server provided by the OBS project team, https://b.siobud.com/, can stream and receive normally.
ZLM can also stream and receive normally.

1. SRS Version: 6.0.41, the latest version compiled from the develop branch.
2. SRS Log:
Question 1) In the related log, it can be seen that the part after the colon in the username is missing. This is because the OBS parsing does not support ice-ufrag in the global section. This can be temporarily resolved through the Johzzy branch.
https://github.com/johzzy/srs/tree/feature/obs
```
[2023-03-31 09:56:02.364][INFO][23][go5397c1] RTC username=5759z3ye:, offer=1170B, answer=1348B
```
Question 2) In the related log, it appears to be an encoding issue, but after confirming with the OBS project team, it is confirmed that there is SPSPPS information available.
```
[2023-04-02 23:31:02.151][WARN][11085][002lp93r][11] avc ignore type=1 for no sequence header
```
**UPDATE:** When pulling the latest Johzzy's OBS branch, an error occurred at the SDP step, making it impossible to confirm problem 2.

3. SRS Config:

```
rtc2rtmp.conf
```

## Replay

Please describe how to replay the bug?

Step 1: Run SRS.

Step 2: Use OBS for WHIP streaming.

## Expect

It should run normally.

## Other Known Issues

* #3583
* #3582

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
OBS WHIP has not been formally submitted as a PR yet, there may still be changes, so you can wait and take another look.

`TRANS_BY_GPT3`

**Comment by SetoKaiba** [comment]
https://github.com/obsproject/obs-studio/pull/7926
Now the PR for WHIP support in OBS has been merged.
Can srs be compatible?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Yes, now that the pull request for OBS WHIP has been merged, SRS should be able to support it.

**Comment by winlinvip** [comment]
PR at https://github.com/ossrs/srs/pull/3581

Known issue: 

- [ ] Playback fails if attempted before publishing. Successful playback occurs after publishing.
- [ ] Conversion from RTC to RTMP failed because SPS, PPS, and IDR were sent in separate UDP packets, which SRS should be able to handle.
