### ISSUE TITLE
RAM端推webrtc流到RSR播放花屏

### ISSUE THREAD

**Issue by cwy1996** [ossrs/srs#3524]
> Note: Please read FAQ before file an issue, see #2716

## Description

srs最新版develop

推流摄像头海康

arm端推流（花屏）
./ffmpeg -rtsp_transport udp -i "rtsp://admin:Admin123@192.168.10.203/h264/ch1/sub/av_stream" -f webrtc
![image](https://user-images.githubusercontent.com/76695859/233897578-45b244ce-790f-4976-98a4-7d58c6136dee.png)

同样配置推流x86端正常
./ffmpeg -rtsp_transport udp -i "rtsp://admin:Admin123@192.168.10.203/h264/ch1/sub/av_stream" -f webrtc
![image](https://user-images.githubusercontent.com/76695859/233924821-2cf2e826-6a29-4462-89de-42de002d7155.png)

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
