### ISSUE TITLE
rtmp to webrtc

### ISSUE THREAD

**Issue by ngoc-duong** [ossrs/srs#3525]
> Note: Please read FAQ before file an issue, see #2716

## Description

I am having problem converting from rtmp stream to webrtc, it seems that when converting from rtmp to rtc the track received by the client side has no trackID and streamID, how can i fix it?,  Can someone help me? Please!

1. SRS Version: v4.0-r4

2. SRS Log:

```
Not get trackID and streamID
```

3. SRS Config:

```
rtmp2rtc.conf
```

## Replay

Please describe how to replay the bug?

Step 1: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 2: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 3: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Expect

Please describe your expectation.

**Comment by duantuidp** [comment]
我倒是没有这个报错，但是我的问题client disconnect peer. ret=1007，rtmp播放正常，rtc就是不行

**Comment by ngoc-duong** [comment]
If using srs player i still see track id and streamid but i'm trying srs-benrch in 3rdparty to pull rtc stream when ontrack doesn't see trackid and streamid srs benrch is using pion's webrtc to connect

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
