### ISSUE TITLE
Pull WebRTC streams from Edge

### ISSUE THREAD

**Issue by amiadz-highlander** [ossrs/srs#3529]
Hi guys,

I would like to have the option to pull WebRTC streams from Edge.
I know it is possible to pull RTMP from the Edge server, but can't pull WebRTC from Edge only from the origin.
Can WebRTC packets be pulled from Edge, if not, do you intend to add support, and when?

**Comment by winlinvip** [comment]
SRS edge is RTMP edge, which only supports RTMP and HTTP-FLV. So you can't pull HLS, WebRTC, or SRT from RTMP edge.

For HLS cluster, please see [HLS Edge Cluster](http://ossrs.io/lts/en-us/docs/v5/doc/sample-hls-cluster).

We are working on developing a Proxy cluster for WebRTC and SRT, see #3138

See FAQ:

* Chinese: https://ossrs.net/lts/zh-cn/faq#edge-hlsdvrrtc
* English: https://ossrs.io/lts/en-us/faq#edge-hlsdvrrtc
