### ISSUE TITLE
实在搞不定了，云面板总是显示An error occurred.

### ISSUE THREAD

**Issue by garyzhao1** [ossrs/srs#3536]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here
已经重装了很多次了，用的DD一键重装系统的,ubuntu 20.04版本
宝塔，aapanel 都装过了，安装系统，直接安装的宝塔，然后在宝塔安装的必要环境，如图

然后，在宝塔安装的srs，4.6.13版本。但是就是在都安装完了点云面板时，打开总是提示
Sorry, the page you are looking for is currently unavailable.
Please try again later.
If you are the system administrator of this resource then you should check the error log for details.
Faithfully yours, nginx.
日志如图
2023/05/09 02:56:02 [error] 38097#0: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 64.62.197.72, server: srs.cloud.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:2022/favicon.ico", host: " 144.X.X.X"
2023/05/09 02:59:05 [error] 38097#0: *28 "/www/wwwroot/srs.cloud.local/geoserver/web/index.php" is not found (2: No such file or directory), client: 64.62.197.75, server: srs.cloud.local, request: "GET /geoserver/web/ HTTP/1.1", host: " 144.X.X.X"
2023/05/09 02:59:45 [error] 38097#0: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 123.233.56.101, server: srs.cloud.local, request: "GET /mgmt/ HTTP/2.0", upstream: "http://127.0.0.1:2022/mgmt/", host: " 144.X.X.X"
2023/05/09 02:59:46 [error] 38097#0: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 123.233.56.101, server: srs.cloud.local, request: "GET /favicon.ico HTTP/2.0", upstream: "http://127.0.0.1:2022/favicon.ico", host: " 144.X.X.X", referrer: "https:// 144.X.X.X/mgmt/"
2023/05/09 03:00:48 [error] 38097#0: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 123.233.56.101, server: srs.cloud.local, request: "GET /mgmt/ HTTP/1.1", upstream: "http://127.0.0.1:2022/mgmt/", host: " 144.X.X.X"
2023/05/09 03:00:49 [error] 38097#0: *37 connect() failed (111: Connection refused) while connecting to upstream, client: 123.233.56.101, server: srs.cloud.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:2022/favicon.ico", host: " 144.X.X.X", referrer: "http:// 144.X.X.X/mgmt/"

版本也切换了很多个了，怎么就是不行呢？很着急啊

**Comment by winlinvip** [comment]
云SRS的问题，请提交到[srs-cloud](https://github.com/ossrs/srs-cloud)，该Issue会被删除，请先阅读FAQ：#2716
