### ISSUE TITLE
在使用webrtc play publish webrtc流的时候，为什么调用play publish接口时候的参数中，sdp没有candidate信息

### ISSUE THREAD

**Issue by vince2000** [ossrs/srs#3537]
只是一个疑问，为什么没有candidate信息，依然可以建立p2p连接。感谢知道答案的大哥回复下我的疑问，谢谢！！！！

**Comment by winlinvip** [comment]
咨询和讨论请加[付费星球](https://mp.weixin.qq.com/s/HdSf7qAR94v2Mxdzf2qLAQ)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
