### ISSUE TITLE
摄像头推流报错

### ISSUE THREAD

**Issue by yuxuanxinchen** [ossrs/srs#3540]
> Note: Please read FAQ before file an issue, see #2716

## Description
docker运行的

1. SRS Version: 5.0

2. SRS Log:

[2023-05-12 09:09:52.010][Error][1][72o41998][4] serve error code=2003 : service cycle : rtmp: stream service : rtmp: receive thread : handle publish message : rtmp: consume message : rtmp: decode message : decode message : decode command name : String invalid marker=0
thread [1][72o41998]: do_cycle() [src/app/srs_app_rtmp_conn.cpp:217][errno=4]
thread [1][72o41998]: service_cycle() [src/app/srs_app_rtmp_conn.cpp:414][errno=4]
thread [1][72o41998]: do_publishing() [src/app/srs_app_rtmp_conn.cpp:910][errno=11]
thread [1][72o41998]: consume() [src/app/srs_app_recv_thread.cpp:380][errno=11]
thread [1][72o41998]: handle_publish_message() [src/app/srs_app_rtmp_conn.cpp:1037][errno=11]
thread [1][72o41998]: process_publish_message() [src/app/srs_app_rtmp_conn.cpp:1082][errno=11]
thread [1][72o41998]: decode_message() [src/protocol/srs_rtmp_stack.cpp:415][errno=11]
thread [1][72o41998]: do_decode_message() [src/protocol/srs_rtmp_stack.cpp:638][errno=11]
thread [1][72o41998]: srs_amf0_read_string() [src/protocol/srs_protocol_amf0.cpp:1513][errno=11](Interrupted system call)

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
