### ISSUE TITLE
Cygwin64 compilation failed-ffmpeg-4-fit

### ISSUE THREAD

**Issue by fengyang1** [ossrs/srs#3543]
Building ffmpeg-4-fit.
./configure: line 598: $'aac_adtstoasc_bsf\r=yes': command not found
./configure: line 598: $'av1_metadata_bsf\r=yes': command not found
./configure: line 598: $'chomp_bsf\r=yes': command not found
./configure: line 598: $'dump_extradata_bsf\r=yes': command not found
./configure: line 598: $'dca_core_bsf\r=yes': command not found
./configure: line 598: $'eac3_core_bsf\r=yes': command not found
./configure: line 598: $'extract_extradata_bsf\r=yes': command not found
./configure: line 598: $'filter_units_bsf\r=yes': command not found
./configure: line 598: $'h264_metadata_bsf\r=yes': command not found
./configure: line 598: $'h264_mp4toannexb_bsf\r=yes': command not found
./configure: line 598: $'h264_redundant_pps_bsf\r=yes': command not found
./configure: line 598: $'hapqa_extract_bsf\r=yes': command not found
./configure: line 598: $'hevc_metadata_bsf\r=yes': command not found
./configure: line 598: $'hevc_mp4toannexb_bsf\r=yes': command not found
./configure: line 598: $'imx_dump_header_bsf\r=yes': command not found
./configure: line 598: $'mjpeg2jpeg_bsf\r=yes': command not found
./configure: line 598: $'mjpega_dump_header_bsf\r=yes': command not found
./configure: line 598: $'mp3_header_decompress_bsf\r=yes': command not found
./configure: line 598: $'mpeg2_metadata_bsf\r=yes': command not found
./configure: line 598: $'mpeg4_unpack_bframes_bsf\r=yes': command not found
./configure: line 598: $'mov2textsub_bsf\r=yes': command not found
./configure: line 598: $'noise_bsf\r=yes': command not found
./configure: line 598: $'null_bsf\r=yes': command not found
./configure: line 598: $'remove_extradata_bsf\r=yes': command not found
./configure: line 598: $'text2movsub_bsf\r=yes': command not found
./configure: line 598: $'trace_headers_bsf\r=yes': command not found
./configure: line 598: $'vp9_metadata_bsf\r=yes': command not found
./configure: line 598: $'vp9_raw_reorder_bsf\r=yes': command not found
./configure: line 598: $'vp9_superframe_bsf\r=yes': command not found
./configure: line 598: $'vp9_superframe_split_bsf\r=yes': command not found
./configure: line 598: $'aasc_decoder\r=yes': command not found
./configure: line 598: $'aic_decoder\r=yes': command not found
./configure: line 598: $'alias_pix_decoder\r=yes': command not found
./configure: line 598: $'amv_decoder\r=yes': command not found
./configure: line 598: $'anm_decoder\r=yes': command not found
./configure: line 598: $'ansi_decoder\r=yes': command not found
./configure: line 598: $'apng_decoder\r=yes': command not found
./configure: line 598: $'asv1_decoder\r=yes': command not found
./configure: line 598: $'asv2_decoder\r=yes': command not found
./configure: line 598: $'aura_decoder\r=yes': command not found
./configure: line 598: $'aura2_decoder\r=yes': command not found
./configure: line 598: $'avrp_decoder\r=yes': command not found
./configure: line 598: $'avrn_decoder\r=yes': command not found
./configure: line 598: $'avs_decoder\r=yes': command not found

**Comment by winlinvip** [comment]
这个问题不是SRS问题，是FFmpeg、WebRTC、客户端、OBS、反向代理Nginx、流的内容、编译工具问题，该Issue会被删除。#2716
