### ISSUE TITLE
srs循环抓取1935的流 

### ISSUE THREAD

**Issue by jdjn12345** [ossrs/srs#3544]
> Note: Please read FAQ before file an issue, see #2716

## Description
srs不停的循环读取
Please description your issue here
![图片](https://github.com/ossrs/srs/assets/99314567/465120c0-2750-48be-acfa-2607123cdb65)

1. SRS Version: x.x.x
5.0.148
2. SRS Log:
srs不停的循环读取本机的1935端口然后再把1935端口的流重新推流到本机的1935端口
![图片](https://github.com/ossrs/srs/assets/99314567/7cfa932a-9b15-40c9-bf0a-9c86413cdd7e)
这是92的配置文件，用ori抓取了一个流，然后推送到了92的1935端口，在抓取 到92的1935的ori流之后推送到了93的1935端口
![图片](https://github.com/ossrs/srs/assets/99314567/584d026e-f391-4a0e-a774-fd3aa9790653)
这是93的配置文件
![图片](https://github.com/ossrs/srs/assets/99314567/54e2a386-e88b-43a6-b4de-f47430c3a199)
这是93的进程

**Comment by winlinvip** [comment]
没看明白。

**Comment by xiangzi1** [comment]
这个一看就是配置文件的问题，这个自己去看看配置吧，还有93的进程循环，你给了个92的配置文件，这个怎么看呢？

**Comment by winlinvip** [comment]
信息不够，会删除这个issue。
