### ISSUE TITLE
RTC playback always starts with an RTP timestamp of 0

### ISSUE THREAD

**Issue by xuehw357** [ossrs/srs#3561]
## Description
RTMP push stream, WebRTC playback, already configured:
```
play {
     time_jitter off;
}
```
But it's not working, the playback RTP timestamp still starts from 0.

Note: It works normally in version 4.0.

1. SRS Version: branch 5.0release v6.0.45

2. SRS Log:
 None

3. SRS Config:

```
play {
     time_jitter off;
}

rtc {
     enabled  on;
     rtmp_to_rtc on;
     rtc_to_rtmp on;
}
```

## Replay

Please describe how to replay the bug?

RTMP push stream, RTC playback

## Expect
When configuring time_jitter off, the playback RTP timestamp should not be forced to start from 0, and should maintain the original timestamp of the push stream side.

**Comment by winlinvip** [comment]
Not sure what starting from 0 would do?

**Comment by xuehw357** [comment]
In some scenarios, it is necessary to restore the push stream timestamp on the playback side. If it is forced to start from 0, it does not match the meaning of configuring time_jitter off.
