### ISSUE TITLE
HLS 响应时能否返回keep-alive？

### ISSUE THREAD

**Issue by syzh** [ossrs/srs#3563]
hls 协议返回m3u8,ts文件时http响应头connection始终是close。这样会导致使用nginx作为缓存时无法复用upstream连接。

https://github.com/ossrs/srs/blob/27f9db97621341cefd93593e176d633b60e4ae8e/trunk/src/app/srs_app_http_conn.cpp#L411

https://github.com/ossrs/srs/blob/27f9db97621341cefd93593e176d633b60e4ae8e/trunk/src/protocol/srs_protocol_http_stack.cpp#L390

当响应http请求时在这俩地方直接设置connection:close。
能否返回默认返回keep-alive?

**Comment by winlinvip** [comment]
咨询和讨论请加[付费星球](https://mp.weixin.qq.com/s/HdSf7qAR94v2Mxdzf2qLAQ)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by winlinvip** [comment]
咨询和讨论请加[付费星球](https://mp.weixin.qq.com/s/HdSf7qAR94v2Mxdzf2qLAQ)交流。也可以[加微信群](https://ossrs.net/lts/zh-cn/docs/v4/doc/contact)，在群里交流。
该Issue会被删除，请先阅读FAQ：#2716
