### ISSUE TITLE
DemoCallbackServer: Critical security vulnerability

### ISSUE THREAD

**Issue by pwntester** [ossrs/srs#3564]
Hi,

We reported a security vulnerability a while ago through the private disclosure feature. Can any maintainer please take a look?

https://github.com/ossrs/srs/security/advisories/GHSA-vpr5-779c-cx62

**Comment by winlinvip** [comment]
Great job! We will investigate this security vulnerability.

**Comment by pwntester** [comment]
Thanks, now that the issue is being handled in the GHSA, I think we can close this issue. Thanks!
