### ISSUE TITLE
Q: If there is built-in HTTP2-FLV support?

### ISSUE THREAD

**Issue by KamenRiderKuuga** [ossrs/srs#3566]
## Description

Because worrying about being limited by the browser when playing multiple videos, I would like to ask if there is built-in HTTP2-FLV support, or do I have to use other gateway proxies to achieve?

1. SRS Version: `v5.0-b0`

**Comment by winlinvip** [comment]
Since HTTP is a very mature protocol, existing tools and reverse proxy capabilities are well developed, and there is no need for SRS to implement a complete protocol.

See FAQ:

* Chinese: https://ossrs.net/lts/zh-cn/faq#https-h2-3
* English: https://ossrs.io/lts/en-us/faq#https-h2-3
