### ISSUE TITLE
srs6 gb28181必须开启内置sip吗？

### ISSUE THREAD

**Issue by akingbrDu** [ossrs/srs#3576]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here

1. SRS Version: x.x.x

2. SRS Log:

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

3. SRS Config:

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Replay

Please describe how to replay the bug?

Step 1: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 2: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 3: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Expect

Please describe your expectation.

**Comment by akingbrDu** [comment]
看文档不是说可以外置sip，传ps进来，现在sip enabled配置关了，提示gb sip需要错误？

**Comment by akingbrDu** [comment]
测试了下把srs的sip端口改成别的，用独立的sip服务（用udp）来完成注册，然后invite时候指定srs的（tcp 9000）端口，结果一直在报：PS: Ignore packet length=1400 for no session ，这个nosession错误，看了下源码，发现即使invite的时候告诉视频设备ssrc值，仍然_srs_gb_manager里找不到这个，因为_srs_gb_manager添加ssrc集合是 （SrsLazyGbSession::drive_state()）里通过内置的sip功能去添加了关联的ssrc session，这样的话那么srs6的 外置sip机会是不是完全没有了？还有别的机会绕过去吗？

**Comment by winlinvip** [comment]
你的问题已经在Issues中存在，属于重复的问题，该Issue会被删除，请在Issues中搜索。#2716
