### ISSUE TITLE
Windows Clion compilation error: libsrt.a not found

### ISSUE THREAD

**Issue by xiangshenb** [ossrs/srs#3585]
> Note: Please read FAQ before filing an issue, see #2716

## Description

When right-clicking on 'Reload CMake project' in the `CMakelists.txt` file in `srs_clion` directory of Clion on Windows 10, the error below is reported:
You can build SRS:
" make " to build the SRS server
" make help " to get some help
`/cygdrive/d/git/srs_gf/trunk/objs/st/libst.a` is ok
`/cygdrive/d/git/srs_gf/trunk/objs/openssl/lib/libssl.a` is ok
`/cygdrive/d/git/srs_gf/trunk/objs/openssl/lib/libcrypto.a` is ok
`/cygdrive/d/git/srs_gf/trunk/objs/srtp2/lib/libsrtp2.a` is ok
`/cygdrive/d/git/srs_gf/trunk/objs/ffmpeg/lib/libavcodec.a` is ok
`/cygdrive/d/git/srs_gf/trunk/objs/ffmpeg/lib/libavutil.a` is ok
`/cygdrive/d/git/srs_gf/trunk/objs/opus/lib/libopus.a` is ok
`/cygdrive/d/git/srs_gf/trunk/objs/ffmpeg/lib/libswresample.a` is ok
CMake Error at CMakeLists.txt:52 (MESSAGE):
  `/cygdrive/d/git/srs_gf/trunk/objs/srt/lib/libsrt.a` not found

1. SRS Version:
   This issue occurs in both the develop branch and the 5.0 release branch.
2. Operating Environment:
   Windows 10
![Image](https://github.com/ossrs/srs/assets/17942071/badbe970-a8ca-4778-bf26-490f9d4cd6ea)

Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
你的问题已经在Issues中存在，属于重复的问题，该Issue会被删除，请在Issues中搜索。#2716
