### ISSUE TITLE
Build: Support build on SW-64 CPU architecture

### ISSUE THREAD

**Issue by xiangleiren** [ossrs/srs#3588]
![image](https://github.com/ossrs/srs/assets/112311627/7fe94004-b25c-4f3f-a1b8-3e2fac2bfdb1)

**Comment by xiaozhihong** [comment]
What platform is this? If you are not familiar with the platform, you need to add them one by one. You can try to support it yourself with the instruction set manual. Refer to [How to port ST Coroutines to other systems or CPUs?](https://mp.weixin.qq.com/s/dARz99INVlGuoFW6K7SXaw)

`TRANS_BY_GPT3`
