### ISSUE TITLE
GB28181: Support NVR with multiple channels.

### ISSUE THREAD

**Issue by timfengzi** [ossrs/srs#3589]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here
Can I only see one channel in the NVR using the GB28181 protocol? The NVR is configured with two channels and two video channel encoding IDs, but there is only one stream.

## Replay
![image](https://github.com/ossrs/srs/assets/8926448/c5a08dd3-3390-407d-9e2d-ff8e38ced6e1)

## Expect

Please describe your expectation.

`TRANS_BY_GPT3`

**Comment by timfengzi** [comment]
![image](https://github.com/ossrs/srs/assets/8926448/843c8fe1-1c4a-4228-9927-64ecb7553da0)

**Comment by duiniuluantanqin** [comment]
Unfortunately, SRS does not support NVR devices currently. Welcome PR.

**Comment by r0achnnan9p** [comment]
> Unfortunately, SRS does not support NVR devices currently. Welcome PR.

No wonder, I spent half a day adjusting the NVR, but couldn't receive any stream. In the end, I directly used the camera.

`TRANS_BY_GPT3`
