### ISSUE TITLE
When will SRS plan to support low-latency HLS?

### ISSUE THREAD

**Issue by webberzheng** [ossrs/srs#3593]
When will SRS plan to support LLHLS that has been defined in [HLS specification](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis) for years?

**Comment by xiaozhihong** [comment]
Have no plan yet, LL-HLS is no stable, and only servel player support it. It also require HTTP2 to transport it, and will case high qps because frequence request of partial segments.

Keep trace on it.
