### ISSUE TITLE
How to modify the default stream and client number in the console console

### ISSUE THREAD

**Issue by lck1115** [ossrs/srs#3603]
I have checked the documentation here: 'https://ossrs.io/lts/zh-cn/docs/v5/doc/http-api#streams'

According to the information provided, it is possible to modify the settings. However, I couldn't find where to modify the configuration in the console.

`TRANS_BY_GPT3`

**Comment by linkewei0580** [comment]
Translate to English:

Change the JS code in the webpage ./trunk/objs/nginx/html/console/js/srs.console.js, find the following code `url+='&count=200';` is what I added.

```
streams_get: function(success) {
    var url = $sc_server.jsonp("/api/v1/streams/");
    url +='&count=200';
    $http.jsonp(url).success(success);
},
streams_get2: function(id, success) {
    var url = $sc_server.jsonp("/api/v1/streams/" + id);
    $http.jsonp(url).success(success);
},
clients_get: function(success) {
    var url = $sc_server.jsonp("/api/v1/clients/");
    url +='&count=200';
    $http.jsonp(url).success(success);
},
```

`TRANS_BY_GPT3`

**Comment by lck1115** [comment]
Thank you, master. Done.

`TRANS_BY_GPT3`
