### ISSUE TITLE
Flutter: Another flutter webrtc demo based on SRS.

### ISSUE THREAD

**Issue by as946640** [ossrs/srs#3613]
Recently, my project used the technology of WebRTC, with SRS as the backend. However, after seeing the blogger's Flutter demo, it seems that they are all from 2 years ago. So, I wrote a basic demo for streaming and pulling, which can be directly used to implement one person streaming and multiple people simultaneously pulling in a conference scenario. Project link: https://github.com/as946640/flutter_webrtc_deom. I also hope that everyone can give me a star.

Preview
![Image Description](https://img-blog.csdnimg.cn/ed962091018f4b96ae0515cdd85a3488.jpeg#pic_center)

`TRANS_BY_GPT3`

**Comment by xiaozhihong** [comment]
Thank you for sharing. Friends who need it can help themselves and test it out, providing feedback on any issues. I hope we can continue this for the long term.

`TRANS_BY_GPT3`
