### ISSUE TITLE
Even though the password has been set, accessing still does not require a password.

### ISSUE THREAD

**Issue by liuliran123** [ossrs/srs#3692]
![image](https://github.com/ossrs/srs/assets/73535336/4f4d818f-31d1-4952-820c-feea3d4588ac)

In addition, the documentation does not mention any enabled password authentication feature. How can we guarantee security?

`TRANS_BY_GPT3`

**Comment by liuliran123** [comment]
There is also no password authentication feature enabled in the document. How can security be ensured?

`TRANS_BY_GPT3`

**Comment by Kentsonshum** [comment]
Have you read the http.api.auth.conf document carefully? The format is incorrect. You also need to enable auth under the api section.

```
http_api {
    enabled         on;
    listen          1985;
    auth {
        enabled         on;
        username        admin;
        password        admin;
    }
}
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Doc is here https://ossrs.io/lts/en-us/docs/v5/doc/http-api#authentication

Thanks @Kentsonshum
