### ISSUE TITLE
srs 5.0.166 gb28181.conf allow_update on cannot be enabled. Is it no longer supported?  可以支持用户调用http raw api控制是否以及何时DVR吗

### ISSUE THREAD

**Issue by wangguibin489** [ossrs/srs#3755]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here

1. SRS Version: x.x.x

2. SRS Log:

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

3. SRS Config:

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Replay

Please describe how to replay the bug?

Step 1: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 2: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

Step 3: xxxxxx

```
xxxxxxxxxxxx
xxxxxxxxxxxx
xxxxxxxxxxxx
```

## Expect

Please describe your expectation.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
你的问题已经在FAQ中存在，该Issue会被删除，请在FAQ中搜索。#2716
