### ISSUE TITLE
can not delete client 

### ISSUE THREAD

**Issue by finch-yihe** [ossrs/srs#3756]
using /api/v1/streams to get info about streams like fellow:
<img width="461" alt="CleanShot 2023-08-04 at 15 30 51@2x" src="https://github.com/ossrs/srs/assets/23740883/84abb049-1442-4296-8f44-db5e773de42e">
but 2049 code returned when using delete api (/api/v1/clients/dj629c58) to delete the client dj629c58, there is no error log in server log and the client dj629c58 is never deleted

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
