### ISSUE TITLE
Have any window-srs support hevc-codec stream push?

### ISSUE THREAD

**Issue by akingbrDu** [ossrs/srs#3760]
1. SRS Version: -Windows-x86_64-5.0-b3
2. SRS Version:  6.0.42

I compile one custom ffmpeg version which can push rtmp-stream with flv format and hevc vcodec, I try push stream for two srs version(linux & windows like above).

linux-version-srs support very well , stream info can be watched from srs-web-console. window-version-srs always drop video frame with header info errors like below

 drop unknown header video, size=14712, bytes[0]....

I guess win-x86_64.5.0 still not support hevc (using codecid=12))? any release-window-version can slove this, or some compile-doc about compiling srs6.0 on window? thanks for help

**Comment by winlinvip** [comment]
HEVC is supported in SRS 6.0, please use the corresponding SRS Windows installation package for 6.0, which can be found in the Releases section.

`TRANS_BY_GPT4`
