### ISSUE TITLE
The stream encountered a problem after a while, serve error code=1011(SocketTimeout)

### ISSUE THREAD

**Issue by beyond21299** [ossrs/srs#3765]
> Note: Please read FAQ before file an issue, see #2716

## Description

Please description your issue here

1. SRS Version: SRS/5.0.170(Bee), MIT

2. SRS Log:

[2023-08-14 09:44:12.611][ERROR][1331][4q096686][4] serve error code=1011(SocketTimeout)(Socket io timeout) : service cycle : rtmp: stream service : rtmp: send 106 messages : send messages : send iovs : writev : writev timeout 30000 ms
thread [1331][4q096686]: do_cycle() [./src/app/srs_app_rtmp_conn.cpp:262][errno=4]
thread [1331][4q096686]: service_cycle() [./src/app/srs_app_rtmp_conn.cpp:456][errno=4]
thread [1331][4q096686]: do_playing() [./src/app/srs_app_rtmp_conn.cpp:901][errno=62]
thread [1331][4q096686]: send_and_free_messages() [./src/protocol/srs_protocol_rtmp_stack.cpp:755][errno=62]
thread [1331][4q096686]: do_send_messages() [./src/protocol/srs_protocol_rtmp_stack.cpp:497][errno=62]
thread [1331][4q096686]: srs_write_large_iovs() [./src/protocol/srs_protocol_utility.cpp:376][errno=62]
thread [1331][4q096686]: writev() [./src/protocol/srs_protocol_st.cpp:664][errno=62](Interrupted system call)

3. SRS Config: windows default config

# no-daemon and write log to console config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }
}

## Replay

The stream encountered a problem after a while, can anyone help analyze the reason? I'm not very familiar with ffmpeg streaming. Where could the problem have occurred?

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
