### ISSUE TITLE
SRS as RTSP Server

### ISSUE THREAD

**Issue by SwanseaLeo** [ossrs/srs#3766]
> Note: Please read FAQ before file an issue, see #2716

## Description

How can I modify the configuration to support RTSP output?
Also, I notice the issue : https://github.com/ossrs/srs/issues/2304. I want to ask how can I recover the RTSP out by recompiling SRS.

1. SRS Version: 6.0

2. SRS Log:

Could not write header for output file #0 (incorrect codec parameters ?): Connection refused
Error initializing output stream 0:0 --

## Replay

Please describe how to replay the bug?

Step 1: 

```
ffmpeg -i rtsp://admin:hik@192.168.1.2 -c copy -f rtsp rtsp://192.168.1.2/live/stream
```

## Expect

I can push RTSP to SRS and run SRS as RTSP server.

`TRANS_BY_GPT4`

**Comment by xiaozhihong** [comment]
SRS removed RTSP's code, no support now.

See [this issue](https://github.com/ossrs/srs/issues/2304).
