### ISSUE TITLE
My own ICE/TURN/STUN server

### ISSUE THREAD

**Issue by alex-drinkwater** [ossrs/srs#3821]
Is there an environment variable for ICE servers? I'd like to know which ICE server this project uses. If there isn't an environment variable for this then I'd like to know where it's hardcoded so I can change it myself, as I am hosting my own eturnal server.

Thank you.

**Comment by winlinvip** [comment]
SRS implements SFU, based on the ice-lite mode. This means it has an IP address that provides services to the outside world. Therefore, it no longer needs an ICE or TURN server to communicate with the client.

In simple terms, you can think of SRS SFU as a regular server. The client can directly access this server's IP to push and pull streams, so there's no need for additional ICE and TURN servers.

The reason we need ICE and TURN servers is when two clients don't go through SFU, but directly P2P. They need to go through the ICE server for hole punching, or relay through TURN.

`TRANS_BY_GPT4`
