### ISSUE TITLE
server not handle long jwt token

### ISSUE THREAD

**Issue by jmowlaei** [ossrs/srs#3831]
For example server not responce when set token :

eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..YSso8gghT84p_7Ic.oywMpi1stu5Yqd5ZT4NMMCvvEogQiD72YuEvQQxFSj0ErIAjYl4rvuDprVJXOizqnr6ZX3Pfa66lk4XaMUgVpzbDfyWFCYiISjy6RANzCzO1LNcIPmvRwW7NoKe0ic8iK8x7bMK13SLdnFxdvx4Kw7zHWT7DaHV3bvdObrCZlGo831J8nriFEoEzzjK6qBgRblaz8m6PaKAGG4yHaycpXfRRPfGimZ6Oe1hzv2-KNk99d_o.sKk1EEjYZ7sJRIFYZCZgcw

http://x.x.x.:8080/live/x5/x.flv?token1=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..3kEfOOGNlQXodfbG.e9WJrVyvdCBASz0mmmuQhv-l-xo8xag2OnI3LCHzhSqhvwNPOeADfXskX2h7BMZzZIrqEoH2T9HJ2M_b7JVVYje4ZQwpzMqqptSyN8q0q5XYsIeeEJIRQLLWb06tNDhuhPLZ7kh0Sle7leRwDB7nTnsEBm4onLGXRcFziyRre3hiONvVziE5Ozbfkw23oRrO4UWSdTGESfQb5bGictd0vRibMcoAUW-aA50OHGWL3FXE64c.kWqizGx3lYqVOh2V-vl2tA

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
