### ISSUE TITLE
Mirage F1EE TRAP 136 issues

### ISSUE THREAD

**Issue by Xeno426** [ossrs/srs#3848]
**Describe the bug**
In multiplayer, the TRAP 136 (Green, U/V) radio stops functioning properly if the radio presets in ME are changed.
Turning the radio off sets the frequency to 0MHz in the overlay (as normal for an off radio), but never turns on again. Further, the selected manual frequency is never reflected on the overlay. Finally, the changed presets do not adjust the frequency shown on the overlay. However, once the presets get to the default ones, the overlay frequency changes as appropriate.

If the radio presets of the TRAP 136 are not changed in the ME, everything functions normally.

These might apply to the CE and BE, but I have not tested those.

**Version**
2.0.8.7

**To Reproduce**
1. Open a mission in ME.
2. Create a Mirage F1EE with "client" as the pilot.
3. Change some of the radio preset frequencies of TRAP 136.
4. Fly the mission in multiplayer, hop into the Mirage F1EE.
5. Attempt to adjust the frequencies on the TRAP 136 (Green) radio.

**Expected behavior**
If the radio is set to Manual or Manual+G, changing the frequency in the cockpit will not adjust the frequency of SRS or the overlay. If the radio is set to Preset, changing preset channel will not change the frequency of the radio or the overlay, which will stay on the default 127.5 MHz. As soon as the preset selector reaches channels that were not modified in the ME, the SRS overlay should change frequency.

**Comment by winlinvip** [comment]
是不是提交错了地方，SRS是流媒体服务器，不是软基站。

**Comment by Xeno426** [comment]
Yes, sorry. Wrong Github. :(
