### ISSUE TITLE
Does SRS 6 support RTMP push streaming with H265?

### ISSUE THREAD

**Issue by jiangbo** [ossrs/srs#3859]
**Describe the bug**
We are using the container version of SRS, with the container address: registry.cn-hangzhou.aliyuncs.com/ossrs/srs:6. 
When using OBS to stream, the streaming address is RTMP protocol, and the video encoder selected is HEVC, but the video cannot be played. 
Without changing any other settings, just changing the video encoder to X264, the video can be played normally. 
Does the container version of SRS 6 support H265 by default?

**Version**
[2023-11-02 10:59:30.043][INFO][1][583k9246] XCORE-SRS/6.0.59(Bee)

**To Reproduce**
1. Deploy the container version of SRS.
2. Use OBS to stream, using the RTMP protocol, and change the video encoder to HEVC.
3. Use the RTC player to play the video, but the video cannot be played.

**Expected behavior**
The video can be played normally.

**Screenshots**
None

**Additional context**
None

`TRANS_BY_GPT4`

**Comment by laurfb** [comment]
Yes! :)

![srs_rtmp_h265](https://github.com/ossrs/srs/assets/5213650/9933b250-d8b3-4eab-b853-e536a4ce2d64)

regards,
Laur
