### ISSUE TITLE
Does srs support single rtmp connection create multi stream?

### ISSUE THREAD

**Issue by KittenBall** [ossrs/srs#3860]
I see the rtmp protocol support multi call create stream and return different stream id to use send message.

I'm new to streaming media and I am writing a rtmp client and publish the stream to the srs server, but I found that multi send createStream command just the first one return a _result.

Version SRS/6.0.85(Hang)

Can anyone help me?

Thank you very much.

**Comment by xiaozhihong** [comment]
What is the context in which you require multiple RTMP streams, and why is this necessary? The support for multiple RTMP streams in players is generally very poor.

`TRANS_BY_GPT4`

**Comment by KittenBall** [comment]
Just for learning interest, because I see that the rtmp protocol is supported
