### ISSUE TITLE
In gb28181, there is no corresponding API interface to control `auto_play`.

### ISSUE THREAD

**Issue by LUOQING1994** [ossrs/srs#3863]
**Describe the bug**
In the gb28181.conf file, after setting auto_play to off, I couldn't find the corresponding API interface to control auto_play to on. I tried the V1 version of the interface, but it was not available.

**Version**
v 5.0.7+

**Expected behavior**
After setting auto_play to off, you can control auto_play through a new API interface, which allows you to manually send an invite to the device end.

**Screenshots**
![image](https://github.com/ossrs/srs/assets/20340633/16d4bcec-c964-4faf-9490-2aefeebd74e8)

`TRANS_BY_GPT4`

**Comment by LUOQING1994** [comment]
那我如何实现以下功能？
功能需求:
摄像头通过gb28181在srs上注册成功后，不主动推流。当用户在监控平台点击某一摄像头后，对应摄像头才进行推流操作

**Comment by winlinvip** [comment]
你的问题已经在Issues中存在，属于重复的问题，该Issue会被删除，请在Issues中搜索。#2716
