### ISSUE TITLE
Video file cannot be uploaded

### ISSUE THREAD

**Issue by lishuai8895** [ossrs/srs#3865]
You got an error!
Request: http://43.132.218.178:2022/terraform/v1/ffmpeg/vlive/upload/bfx.mp4
Status: 503 Service Unavailable
Data:

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
