### ISSUE TITLE
./configur compilation error

### ISSUE THREAD

**Issue by haozhaosun** [ossrs/srs#3876]
Environment Error: 'Permission denied' when trying to run './configure'.
Build libsrtp failed, ret=126

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by ibaoger** [comment]
> Environment Error: 'Permission denied' when trying to run './configure'. Build libsrtp failed, ret=126
> 
> `TRANS_BY_GPT4`

You can try this command:
chmod u+x srs/trunk -R
./configure
