### ISSUE TITLE
I would like to ask, after the GB28181 camera registration is completed, does the camera continuously stream to SRS? Or does it only pull the stream when a client requests it?

### ISSUE THREAD

**Issue by song0320** [ossrs/srs#3880]
I would like to ask, after the camera has completed registration with gb28181, does the camera continuously stream to srs? Or does it only pull the stream when a client requests it?

If I have 100 cameras, this difference is significant. If they are continuously streaming, it would constantly occupy the bandwidth, which might require a high-performance network.

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题已经在Issues中存在，属于重复的问题，该Issue会被删除，请在Issues中搜索。#2716
