### ISSUE TITLE
[bug][GB28181] does not reinvite after the client unexpectedly stops streaming

### ISSUE THREAD

**Issue by underthere** [ossrs/srs#3881]
**Describe the bug**
When the client stops streaming without sending a BYE message (for example, when the camera is directly rebooted by power cycling), SRS (Streaming Relay Server) retains the old media connection and does not reinvite.

**Version**
5.0

**To Reproduce**
Described above

**Expected behavior**
Described above

**Comment by winlinvip** [comment]
Dup to #3944
