### ISSUE TITLE
Need a way to determine whether the stream has stopped coming on a SRS RTMP server due to network disconnection on publisher's end.

### ISSUE THREAD

**Issue by mrdixitjain** [ossrs/srs#3892]
We have a specific need to utilize the SRS for streaming in conjunction with OBS or similar software. Presently, in the event of a publisher's connection drop during a stream, the default behavior of SRS involves buffering for end clients until the publish timeout occurs, ultimately terminating the stream.

Our objective is to implement a feature that displays a screen message such as "Publisher will rejoin shortly" upon a connection dropout. This aims to prevent end users from becoming frustrated and leaving the stream prematurely. Despite my investigation, I have not identified a straightforward method to achieve this.

Could someone kindly suggest a solution or provide guidance on how to implement this feature within the SRS framework?

**Comment by gfloras** [comment]
Good point, we also need that
