### ISSUE TITLE
srt-to-rtmp-forward

### ISSUE THREAD

**Issue by attiliodrei** [ossrs/srs#3893]
**Describe the bug**
when srt-to-rtmp on  , sending to ossrs with srt protocol  and forwarding  to other rtmp server , metatadata informations are not sent
**Version**
5.0.195
**Config**
vhost test.com {
    srt {
        enabled     on;
        srt_to_rtmp on;
    }
forward 192.168.1.18;
}

**Bug**
should send metadata packet containing the track list
**reported by 3rd party rtmp server error**
RTMP ERR: first packet must be metadata
https://github.com/bluenviron/mediamtx/issues/386

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
