### ISSUE TITLE
forward stream to 2 servers

### ISSUE THREAD

**Issue by maxwelllin-kingkey** [ossrs/srs#3894]
I use the forward feature to push many streams to a master server first. This master server then forwards all the streams to server1 and server2 via forward (this is done for bandwidth considerations). However, I've noticed that occasionally one or two streams are missing on server1, but they exist on server2, while the frontend continues to send stream packets.

**Comment by xiaozhihong** [comment]
Please provide  your config and log.

**Comment by winlinvip** [comment]
如果转发过程中出现异常，会有重试，不过不一定能保证恢复，所以需要看看详细的日志。

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
