### ISSUE TITLE
SRS is still running after compressing logfile, but no log output to srs.log until executing "srs restart";

### ISSUE THREAD

**Issue by liaoshuguang** [ossrs/srs#3897]
**Describe the bug**
SRS is still running after compressing logfile, but no log output to srs.log until executing "srs restart";

**Version**
SRS/4.0.269(Leo)

**Screenshots**
![Snipaste_2023-11-30_17-42-07](https://github.com/ossrs/srs/assets/33723662/03a6152b-000e-4620-ab3d-7306dde81e12)

**Comment by liaoshuguang** [comment]
<img width="861" alt="image" src="https://github.com/ossrs/srs/assets/33723662/ebea3e78-23c0-47ac-af96-9a7c66fb4e32">
the last appended log

**Comment by winlinvip** [comment]
If you need to set up log rotation, please follow the instructions in the documentation. Do not directly move the SRS log files.

See https://ossrs.io/lts/en-us/docs/v6/doc/log-rotate or https://ossrs.net/lts/zh-cn/docs/v6/doc/log-rotate

`TRANS_BY_GPT4`
