### ISSUE TITLE
When pushing against the official webrtc-demo, the rtc/v1/publish/ interface always returns the following error

### ISSUE THREAD

**Issue by BiuBIu-Ka** [ossrs/srs#3903]
**Describe**
When pushing against the official **webrtc-demo**, the **rtc/v1/publish/** interface always returns the following error

    "code": 0,
    "server": "vid-4fs8k34",
    "service": "8c6t324d",
    "pid": "20559",
    "urls": {
        "api": "the api root",
        "rtc": {
            "v1": {
                "play": "Play stream",
                "publish": "Publish stream",
                "nack": "Simulate the NACK"
             }
         }
     }

This result directly leads to the failure of pushing stream and playing, and the relevant documents are not queried. Is the configuration incorrect?

**Comment by winlinvip** [comment]
Please click the `ASK AI` button on either https://ossrs.io or https://ossrs.net for the Chinese language.
I think the AI can address this query since relevant articles or discussions may already be available.

This issue will be eliminated, see #2716
