### ISSUE TITLE
on_publish rtmp authentication

### ISSUE THREAD

**Issue by bugsyb** [ossrs/srs#3906]
Currently using nginx-rtmp-mod which supports i.e. 
`on_publish http://localhost:44444/auth;`

This effectively implement authentication fulfilled elsewhere and returning 200 or 401 depending on good/bad credentials.

Any chances to add the like of `on_publish` to SRS?

Did the RTFM and only reference to auth is in regards to HTTP API, can't find also anything relate to on_publish in regards to rtmp.

Thanks!

**Comment by bugsyb** [comment]
Feeling is that it should be somehow reachable using token/http_callback. Just unsure how to connect it all into one:
https://ossrs.net/lts/en-us/docs/v4/doc/drm#token-authentication

For my use case, need a simple user/pass auth, which have currently done through on_publish in nginx and validated by third party flask app validating credentials.

Can this be somehow plugged into SRS? 
If not, what would be recommended solution (best would be an example, as feeling is that token can partially support it). It needs to be static token.

**Comment by winlinvip** [comment]
这个问题在[Wiki](https://ossrs.net/lts/en-us/docs/v5/doc/getting-started)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716
