### ISSUE TITLE
add a new option of file permission to config

### ISSUE THREAD

**Issue by zubin999** [ossrs/srs#3913]
**What is the business background? Please provide a description.**
in `on_dvr` hook, I need to move the file to a new place. I write the script in PHP. 

**Is your feature request related to a problem? Please describe.**

when copy file got error:
```
{"type":2,"message":"copy(\\/data\\/srs\\/record\\/live\\/987cc704-2332-402a-963e-99177218c6a2\\/1702624496464.mp4): Failed to open stream: No such file or directory...
```
in fact, file exists.because file permission is `-rw-r--r--`, so when call function `copy`,`file_exists`,all got above error.

**Describe the solution you'd like**
set the default permission to 0755 or let user config it in config file

**Describe alternatives you've considered**

**Additional context**

**Comment by zubin999** [comment]
sorry, it's my fault. I run my script in a docker container,but I forgot to mount the path into container.

**Comment by winlinvip** [comment]
Thank you for your feedback. Thank you for choosing SRS.

`TRANS_BY_GPT4`
