### ISSUE TITLE
Android /system/bin srs  No such file or directory

### ISSUE THREAD

**Issue by SunnyCaptain** [ossrs/srs#3915]
**Describe the bug**
After cross-compiling, an error message "No such file or directory" occurs when running in the /system/bin directory on the Android system, but this issue does not exist with version 3.0.

**Version**
srs 4.0

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
Please click the `ASK AI` button on either https://ossrs.io or https://ossrs.net for the Chinese language.
I think the AI can address this query since relevant articles or discussions may already be available.

This issue will be eliminated, see #2716
