### ISSUE TITLE
OBS can't publish stream to SRS Stack service

### ISSUE THREAD

**Issue by johnnguyen1816** [ossrs/srs#3919]
I have deployed the srs-stack on my ec2 using docker and follow [Scenarios] but OBS cannot connect via rtmp or whip, please help me

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
