### ISSUE TITLE
SIP displays that the port is unreachable" means what?

### ISSUE THREAD

**Issue by UChiHa-Obitoto** [ossrs/srs#3922]
![1704246215940(1)](https://github.com/ossrs/srs/assets/108263720/1609a337-d9d0-4d97-a6fc-36de25f7382d)

Version
![image](https://github.com/ossrs/srs/assets/108263720/e684d3ad-382c-422b-9ff2-3f928857fd35)

Console log
![image](https://github.com/ossrs/srs/assets/108263720/1a059800-91bd-4850-907a-3398661b4c9c)

GB28181 protocol configuration file for push service
![image](https://github.com/ossrs/srs/assets/108263720/9dabcf3e-a596-4d17-9b6f-2155139a2314)
![image](https://github.com/ossrs/srs/assets/108263720/4674a75d-e2d6-443b-89b8-098571c1c29f)
![image](https://github.com/ossrs/srs/assets/108263720/cc0043ff-af05-4b58-b608-3b5e1c473937)

The firewall has been disabled, and the host machine can successfully telnet to the virtual machine using ports such as 8080, 5060, etc.

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
请在官网问AI Assistant。

**Comment by winlinvip** [comment]
!!! Before submitting a new bug report, please ensure you have searched for any existing bugs and utilized 
the `Ask AI` feature at https://ossrs.io or https://ossrs.net (for users in China). Duplicate issues or 
questions that are overly simple or already addressed in the documentation will be removed without any 
response.
