### ISSUE TITLE
OBS WHIP: No video on FLV

### ISSUE THREAD

**Issue by rscataran** [ossrs/srs#3929]
**Describe the bug**
Using OBS WHIP ang enabling DVR, the FLV file saved does not have a video stream. audio only.

**Version**
SRS/5.0.205

**To Reproduce**
1. Using conf\rtmp2rtc.conf as base.
2. enable DVR by including on vhost
```
 	dvr {
		enabled 	on;
		dvr_path    D:/SRS/data/[app]/[stream].[timestamp].flv;
	}

```
3. Start OBS, set stream to WHIP, with server `http://localhost:1985/rtc/v1/whip/?app=live&stream=livestream`
4. Start Streaming, then stop after a few seconds.
5. Open recorded FLV file in VLC, audio only will be played.
- SRS LivePlayer also does not show the video

**Expected behavior**
Video and audio should be recorded

**Screenshots**
![image](https://github.com/ossrs/srs/assets/13414746/10134968-e505-4812-b3c9-7e45f1444886)
![image](https://github.com/ossrs/srs/assets/13414746/65733eb0-439e-44aa-b8aa-9be620de0d02)

**Additional context**
Using SRS WHIP Player Publish, produces FLV file that has both video and audio.

**Comment by rscataran** [comment]
I tried to add

`
has_audio on;
has_video on;
guess_has_av off;
`

Under `http_remux` to try and force the FLV headers to have video and audio,

then the FLV file does not play using SRS LivePlayer.

**Comment by winlinvip** [comment]
Dup to https://github.com/ossrs/srs/pull/3920
