### ISSUE TITLE
port unresponsive

### ISSUE THREAD

**Issue by ahonggea** [ossrs/srs#3941]
**Describe the bug**
May I ask if you have encountered deployment under Windows and have listened to all ports. But all ports did not respond when sending requests. Telnet can be accessed, but requests sent using wget have been waiting for a response. And there is no abnormality in the log at all

**Version**
 v6,v5

**Comment by winlinvip** [comment]
!!! Before submitting a new feature request, please ensure you have searched for any existing features and utilized
the `Ask AI` feature at https://ossrs.io or https://ossrs.net (for users in China). Duplicate issues or
questions that are overly simple or already addressed in the documentation will be removed without any
response.

**Comment by ahonggea** [comment]
but i think this is a bug
