### ISSUE TITLE
How to replace the audio track within a live stream with random noise audio.

### ISSUE THREAD

**Issue by djkcyl** [ossrs/srs#3965]
For instance, the usage of the following commands:

```
ffmpeg -i input_video_file_or_stream -f lavfi -i anoisesrc -c:v copy -c:a aac -map 0:v:0 -map 1:a:0 -shortest output_file_or_stream
```

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
SRS is a media server that doesn't transcode or drop audio streams. However, you can use FFmpeg for this purpose. When you publish a stream to SRS, it can notify your system via an HTTP callback. Then, you can start FFmpeg to replace the audio stream with a silent one in your service.
