### ISSUE TITLE
DVR Creating MP4 file where audio is off sync with the video. 

### ISSUE THREAD

**Issue by loyal2dagame** [ossrs/srs#3966]
What would cause the dvr to convert to mp4 and the audio be out of sync by over a second?

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716

**Comment by loyal2dagame** [comment]
@winlinvip I don't know how to explain a way you could reproduce this. When I test with OBS DVR conversion to mp4 works fine. However when I use a mobile library with settings that match that of obs I get a 2 second audio offset from the video. Can you suggest anything?
