### ISSUE TITLE
Is it possible to configure a range for WebRTC ports in SRS5?

### ISSUE THREAD

**Issue by slps970093** [ossrs/srs#3991]
Is it possible to configure a range for WebRTC ports in SRS5, for example, from 4000 to 5000?

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
