### ISSUE TITLE
Support stereo audio for WebRTC audio mixing.

### ISSUE THREAD

**Issue by chinajuak** [ossrs/srs#3994]
Our software, when pushing an RTMP stream, has two distinct audio tracks for the left and right channels. However, after processing through SRS, when played back via WebRTC, the audio from the left and right channels is mixed together.

Our requirement is that the audio tracks for the left and right channels should not be mixed together.

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
Interesting. I think it should be caused by the audio transcoder model of WebRTC, which need to be refined for stereo audio. Patch welcome.

**Comment by chinajuak** [comment]
Yes, two distinct audio tracks to facilitate the separate extraction of each voice in post-production.

`TRANS_BY_GPT4`
