### ISSUE TITLE
gettid impl in macOS and cygwin64

### ISSUE THREAD

**Issue by suzp1984** [ossrs/srs#3996]
https://github.com/ossrs/srs/blob/954b1b7ef218f17a010f47d7032ae1af63bdc9bf/trunk/src/app/srs_app_threads.cpp#L39-L48

I already met same issue in another project: 
https://github.com/signalwire/libks/pull/205/files

So why not add this patch here?

**Comment by winlinvip** [comment]
Please do not open an issue, unless you really need to open a bug report.

1. Open a discussion if want to discuss.
2. Open a pull request if want to improve, where we can discuss at.

I will delete this issue.
