### ISSUE TITLE
Mac Os build failed

### ISSUE THREAD

**Issue by mdsohelmia** [ossrs/srs#4021]
ld: multiple errors: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libssl.a'; archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'
ld: multiple errors: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'; archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libssl.a'
ld: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'
ld: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'
ld: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ld: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'
make[1]: *** [fuzz/conf-test] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [fuzz/client-test] Error 1
make[1]: *** [fuzz/bignum-test] Error 1
clangmake[1]: *** [fuzz/asn1parse-test] Error 1
: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fuzz/asn1-test] Error 1
make[1]: *** [fuzz/cms-test] Error 1
ld: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fuzz/bndiv-test] Error 1
ld: archive member '/' not a mach-o file in '/Users/sohelmia/code/streaming-platform/media-server/srs/trunk/objs/Platform-SRS6-Darwin-23.4.0-Clang15.0.0-arm64/openssl-1.1-fit/libcrypto.a'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [fuzz/crl-test] Error 1
make: *** [all] Error 2
Build openssl-1.1-fit failed, ret=2

**Comment by suzp1984** [comment]
Are you just transfer data from a Mac Intel Chip machine  to a new Mac M1/2 chip machine? I met a similar error before, just `make clean` or `rm -rf ./objs`, be careful the `rm` cmd. Then do `configure` and `make` again.

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
