### ISSUE TITLE
Cannot boot a SRS docker container when using docker -v

### ISSUE THREAD

**Issue by Vzhangs** [ossrs/srs#4022]
**Describe the bug**
Cannot boot a SRS docker container when using docker -v

**Version**
Using docker image registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5

**To Reproduce**
shell
```shell
docker run -it -p 1935:1935 -p 8080:8080 -p 10080:10080/udp -v ./srs_conf:/usr/local/srs/conf --privileged registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5 ./objs/srs -c conf/srt.conf
```

**Expected behavior**
Successful boot

**Screenshots**
The text appears to be a description of an image file, possibly a screenshot, with specific dimensions and a reference to its location on a GitHub repository within the 'ossrs/srs' project. The image seems to be related to a commit or an issue in the repository. The text is formatted as HTML code for embedding an image with a width of 882 pixels.

**Additional context**
If remove `-v ./srs_conf:/usr/local/srs/conf` it will boot successful

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
Google about how to use `docker -v`
