### ISSUE TITLE
(Near) real time reporting bandwidth and/or time

### ISSUE THREAD

**Issue by misiek08** [ossrs/srs#403]
Is it possible to add to 2.0 http hook like nginx's-rtmp-module on_update to periodically report sent/received bytes and time of play and publish? It will be great to account usage and make statistics and now it's possible only by polling stats or counting time between on_play-on_stop.

Simple adding all bytes between server and client to some variable and reporting it will be enough for me. About the time I know the duration is sometimes crazy in RTMP, so it's not so important for me.

**Comment by winlinvip** [comment]
SRS provides HTTP api to query the detail info, see:
http://ossrs.net:19851/api/v1/vhosts
http://ossrs.net:19851/api/v1/streams
Maybe better than http callback.

**Comment by misiek08** [comment]
Can you tell me one more thing only: how stable is 2.0 code? Is 2.0release branch stable? I know there are develop and 2.0release branch, but they get all commits at the same time, so can I treat it as stable, production-ready code?

I'm going to try hosting 20k people and I have choice to take nginx's module (becuase of lack on_update in srs and need to write polling code for stats) or srs, so that's why I asked the question.

**Comment by winlinvip** [comment]
SRS2 is not stable right now, we will release it at 2015.12.
Recomment to wait and use the STABLE release of SRS2.

About the on_update http callback, can you describe it? I can add this feature to SRS.

**Comment by misiek08** [comment]
It's the thing I described in first post, but there is workaround, so no problem.

SRS1.0 is performing good, but not enough for me and the 2015.12.... way too late for me, too :)

Do you have any commercial version of this server? I'm working on SRS code locally to add debug messages that will help in case of any problems. The code is stable, but SRS1.0 and it's 2.7k clients it's too small amount - yes, I know about cluster capabilities, but even with that it's not enough. I continue to work on 2.0 locally.

**Comment by winlinvip** [comment]
Yep, we provides commercial version of SRS for:
1. More fast release roadmap.
2. Support FlashP2P over HLS.
3. Realtime server support for bug fix.
4. User required feature.

**Comment by winlinvip** [comment]
You can contact us by skype winterserver, or http://www.chnvideo.com

**Comment by winlinvip** [comment]
Email is ok: winlin@vip.126.com or winlin@chnvideo.com

**Comment by winlinvip** [comment]
No need to fix.
