### ISSUE TITLE
How to set authentication for rtmp

### ISSUE THREAD

**Issue by Jithklm** [ossrs/srs#4032]
!!! Before submitting a new bug report, please ensure you have searched for any existing bugs and utilized 
the `Ask AI` feature at https://ossrs.io or https://ossrs.net (for users in China). Duplicate issues or 
questions that are overly simple or already addressed in the documentation will be removed without any 
response.

**Describe the bug**

**Version**
Desribe your SRS Server version here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Jithklm** [comment]
How to set authentication for rtmp

**Comment by winlinvip** [comment]
这个问题在[Wiki](https://ossrs.net/lts/en-us/docs/v5/doc/getting-started)中有，请看文档。该Issue会被删除，请先阅读FAQ：#2716
