### ISSUE TITLE
WebRTC WHEP URL playback is stuttering in Google Chrome browser.

### ISSUE THREAD

**Issue by suhaojava** [ossrs/srs#4035]
WebRTC WHEP URL experiences playback stuttering in Google Chrome browser.

Initiating the upload of the file named "2024-04-22 13-40-33.mp4"...

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
