### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by Innu38** [ossrs/srs#4045]
!!! Before submitting a new bug report, please ensure you have searched for any existing bugs and utilized 
the `Ask AI` feature at https://ossrs.io or https://ossrs.net (for users in China). Duplicate issues or 
questions that are overly simple or already addressed in the documentation will be removed without any 
response.

**Describe the bug**

**Version**
Desribe your SRS Server version here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
