### ISSUE TITLE
When the DVR generates a segment, it sends a request to /ws/v1/update.

### ISSUE THREAD

**Issue by hskent** [ossrs/srs#4047]
When the DVR creates a segment, 
it always attempts to connect to /ws/v1/update, but it is unclear what the purpose is. 
Attempts to receive only result in the connection closing immediately after being established, with no messages sent. 
No relevant documentation could be found.

Version
4.0.253
5.0.210

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
SRS won't do this. Please check your code.
