### ISSUE TITLE
FFmepg: Transcode will result in endless ffmpeg process

### ISSUE THREAD

**Issue by suzp1984** [ossrs/srs#4055]
**Describe the bug**

Do transcode according to guide: [https://ossrs.net/lts/zh-cn/docs/v4/doc/sample-ffmpeg](https://ossrs.net/lts/zh-cn/docs/v4/doc/sample-ffmpeg).

If I start a ffmpeg transcode srs process and set the output to same srs process. It will result in endless ffmpeg process being triggered until the system's memory or cpu power exhausted.

**Version**
SRS 6 or maybe any SRS version support `transcode`

**To Reproduce**
1. start srs process: `./objs/srs -c conf/ffmpeg.transcode.conf`
2. publish a rtmp stream: `ffmpeg -re -stream_loop -1 -i test.mp4 -vcodec h264 -profile:v baseline -acodec copy  -f flv rtmp://localhost/live/livestream`
3. wait and monitor the `ffmpeg` processes, or check the srs log.
4. the `ffmpeg` processes will be started to do transcode and republish the transcoded stream to same srs process, which will trigger another `ffmpeg` process to do another transcode, dead endless loops.
   e.g. `live/livestream_ff` will trigger `live/livestream_ff_ff`;
          `live/livestream_ff_ff` will trigger `live/livestream_ff_ff_ff`;
          ... endless;

**Expected behavior**
the tutorial [https://ossrs.net/lts/zh-cn/docs/v4/doc/sample-ffmpeg](https://ossrs.net/lts/zh-cn/docs/v4/doc/sample-ffmpeg) update, maybe remind the user don't sent the output to same srs process.

Or

refactor the `transcode` feature, let it only accept certain streams `[app]/[stream]`.

**Comment by winlinvip** [comment]
Duplicated to #3516

**Comment by duiniuluantanqin** [comment]
see https://github.com/ossrs/srs/pull/4325
