### ISSUE TITLE
High latency on raspberry pi 5

### ISSUE THREAD

**Issue by Y-k-Y** [ossrs/srs#4056]
**Describe the bug**
The latency is way to high on raspberry pi 5 using SRS 5 via docker and realtime.flv.conf. The latency is 6s or sometimes it takes much longer. The command i'm using to publish rtmp output is this:
```
rpicam-vid -v 0 --nopreview --timeout 0 --framerate 16 --bitrate 2048k --width 1920 --height 1080 --libav-format flv -o rtmp://localhost/live/livestream
```

**Version**
5

**Expected behavior**
2 ~ 3s is expected

**Comment by lifeibin** [comment]
I am utilizing SRS (Simple Real-time Server) version 5 to stream content using WebRTC. However, I am experiencing a delay of approximately 3-4 seconds, whereas the anticipated latency for WebRTC is around 1 second. I am uncertain about the cause of this issue.

`TRANS_BY_GPT4`
