### ISSUE TITLE
FFmpeg concurrent streaming.

### ISSUE THREAD

**Issue by xiao5555** [ossrs/srs#4070]
!!! Before submitting a new bug report, please ensure you have searched for any existing bugs and utilized 
the `Ask AI` feature at https://ossrs.io or https://ossrs.net (for users in China). Duplicate issues or 
questions that are overly simple or already addressed in the documentation will be removed without any 
response.

**Describe the bug**
Issue: When using a script to invoke ffmpeg for streaming, running 50 streams results in SRS log indicating a CPU usage of 65% with normal video output. After streaming for a few minutes, multiple streaming processes fail, and it is observed that when streaming failures occur, they happen consecutively across several processes. The SRS log at this time shows CPU usage at 95%. Once these few abnormal streams exit, CPU usage returns to normal. The ffmpeg streaming command is as follows:
ffmpeg -loglevel quiet -re -stream_loop -1 -i /home/firefly/Videos/1280x720.mp4 -c copy -f flv rtmp://192.168.164.59:1935/live/tt45
The aforementioned issue is relatively stable when streaming with 10 channels.
**Version**
v5.0.205

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
你的问题不符合Issue的要求，请按Issue模版提Bug，不提供**完整**信息的Issue会被直接删除。
该Issue会被删除，请先阅读FAQ：#2716
