### ISSUE TITLE
SRS服务器无法转发AMF数据

### ISSUE THREAD

**Issue by zhao-xiang** [ossrs/srs#412]
SRS服务器无法转发AMF数据

**Comment by winlinvip** [comment]
This may only be fixed in SRS3, and the changes are not insignificant.

`TRANS_BY_GPT3`

**Comment by baiys** [comment]
May I ask if there is a version of SRS that supports AMF data forwarding?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Nop, no plan for this.

**Comment by baiys** [comment]
For example ,I want to pull stream for AMF ,this is my config
vhost www.trycry.com {
    mode            remote;
    origin           110.125.15.5:1935;
    } 
if origin stream is AMF 0 or AMF 3 , the SRS can pull this stream ?

**Comment by winlinvip** [comment]
Won't fix.
