### ISSUE TITLE
Windows编译出来的安装文件，SRT功能没有打开

### ISSUE THREAD

**Issue by yanght1001** [ossrs/srs#4125]
1、在github的发布程序里面下载最新的6.0 或者5.0版本的程序，安装完成服务。
2、按照文档进行SRT推流，推流失败。

然后在我 debian 11 下面编译了6.0的源码，运行代码 按照文档推流成功。

由此推断 Windows编译的程序没有加入，设置编译的时候打开srt功能。类似： ./configure --srt=on && make 这样。

**Comment by winlinvip** [comment]
已知问题，提问前请先搜下之前的issue。这个问题会删除。
