### ISSUE TITLE
WebRTC streaming was successful, but WebRTC play failed

### ISSUE THREAD

**Issue by fangzi0813** [ossrs/srs#4133]
**Describe the bug**
When using WebRTC for streaming, if the SDP only has m=video and not m=audio, the streaming is successful. But when playing webrtc, the sdp request will include m=audio and m=video, while the sdp response is only video, resulting in playback failure. The console will print "Failed to set remote answer sdp: The order of m-lines in answer does not match order in offer. Rejecting answer". Is there any way to solve this?

**Version**
srs5.0

**Expected behavior**
webrtc play success

**Screenshots**
play request:
![image](https://github.com/user-attachments/assets/2b45b8c6-27f1-4b8a-8882-ba39dab7b9e3)
play respones:
![image](https://github.com/user-attachments/assets/60a5b788-287f-4c57-b04f-5b6e398e6c29)
console:
![image](https://github.com/user-attachments/assets/8eaa9d0b-3a1b-4ea6-8d74-95616d3c32b5)

**Additional context**
There is a phenomenon that all protocols except WebRTC can play normally

**Comment by Diras226** [comment]
You can set what you expect to get when sending a whep offer to play a stream.
    
    const pc = new RTCPeerConnection();

    const options: RTCOfferOptions = {
      offerToReceiveAudio: false,
      offerToReceiveVideo: true
    }

    const rtcSessionDescriptionInit = await pc.createOffer(options)

**Comment by fangzi0813** [comment]
> You can set what you expect to get when sending a whep offer to play a stream.
> 
> ```
> const pc = new RTCPeerConnection();
> 
> const options: RTCOfferOptions = {
>   offerToReceiveAudio: false,
>   offerToReceiveVideo: true
> }
> 
> const rtcSessionDescriptionInit = await pc.createOffer(options)
> ```

Thanks, this is a solution！
