### ISSUE TITLE
Simultaneous SRT callers

### ISSUE THREAD

**Issue by JonnyTech** [ossrs/srs#4168]
**Describe the bug**
Unable to connect more than one SRT caller / client to SRS

**Version**
Release v5.0-r3 self compiled Debian Linux x64

**To Reproduce**
Push SRT from ffmpeg to ingest on SRS as per https://ossrs.io/lts/en-us/docs/v6/doc/srt
Connect several client to the SRS output stream (ffplay, VLC, OBS)
Only the first client will successfully establish connection

**Expected behaviour**
Multiple SRT clients (callers) should connect to the SRT server (listener)

Is there a limitation on number of simultaneous viewers?
I am on a closed LAN with no other network traffic.

**Comment by suzp1984** [comment]
No, there are no media viewers number limitation.
If `ffplay` works, then you can open more `ffplay` cmd to verify.

I guess your issue is config the `VLC` and `OBS` incorrectly.

For `VLC`, is below issue fix your problem?
https://github.com/ossrs/oryx/issues/186

**Comment by JonnyTech** [comment]
Thanks for your reply. It ended up being a typo on my side.
