### ISSUE TITLE
The srs-cloud service is no longer operational, and it is also not functioning within the Baota panel. Could you provide an updated release of resources and a new method for setting up within the Baota environment?

### ISSUE THREAD

**Issue by Alvin1986** [ossrs/srs#4175]
The srs-cloud service is no longer functional, and it is also not working within the Baota panel. Could you please provide an updated release of resources and a new method for setting it up specifically for Baota?

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
See https://ossrs.net/lts/zh-cn/docs/v7/doc/getting-started-oryx
