### ISSUE TITLE
DASH: no dash output for audio/video only stream

### ISSUE THREAD

**Issue by flnewsoft** [ossrs/srs#4189]
env:  branch: develop
       git  : commit 6bbd461ec960652c65deaaa9356d79fac691dd6d
how to reproduce:
 1.  objs/srs -c conf/dash.conf
 2. send rtmp stream to 1935 using ffmpeg
 3.  cd objs/nginx/html, no mpd file exist. 
 4.  cd objs/nginx/html/live/stream, only audio-init.mp4  video-init.mp4 found.

**Comment by suzp1984** [comment]
Because you are publish a only video or only audio media resource. 
Try another stream with both audio and video track, then after 3 fragment period, around 30 seconds, the `mpd` file will appear.

But it's a bug, let dash support single audio or single video stream.

**Comment by winlinvip** [comment]
No plan to support audio or video only stream in DASH.
