### ISSUE TITLE
The RTMP stream disconnects every night.

### ISSUE THREAD

**Issue by timfengzi** [ossrs/srs#4191]
!!! Before submitting a new bug report, please ensure you have searched for any existing bugs and utilized 
the `Ask AI` feature at https://ossrs.io or https://ossrs.net (for users in China). Duplicate issues or 
questions that are overly simple or already addressed in the documentation will be removed without any 
response.

**Describe the bug**
Is the disconnection of the RTMP stream every night due to the SRS mechanism?
![image](https://github.com/user-attachments/assets/48fcdc6e-b0ef-4239-9bbd-0d5435b7e44c)

**Version**
linux 6.0.155

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
The error log clearly provides the error details.
