### ISSUE TITLE
The "--static=on" option is unable to achieve static compilation.

### ISSUE THREAD

**Issue by jevian-ma** [ossrs/srs#4193]
After testing, it has been found that in the latest release of SRS 5.0, using the command './configure --static=on' does not result in a static compilation. Upon examining the configure script, it was discovered that adding './configure --static=on' only includes the '-static-libstdc++' flag during the linking process, rather than '-static'. Additionally, it was noted that the compilation of SRS 5.0 involves the use of other libraries. A feasible method to achieve true static compilation has been identified as
`./configure --srt=off --extra-ldflags=-static --sanitizer=off`
The options '--srt=off' and '--sanitizer=off' are necessary for successful compilation. Without '--srt=off', the compilation will not complete, and omitting '--sanitizer=off' will result in a conflict with the static compilation option.

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
Duplicated
