### ISSUE TITLE
When using SRS (Simple Real-time Server) to play RTC (Real-Time Communication), the API endpoint /rtc/v1/play/ is utilized. What is the API endpoint to stop the client's playback?

### ISSUE THREAD

**Issue by scortLi** [ossrs/srs#4206]
!!! Before submitting a new feature request, please ensure you have searched for any existing features and utilized
the `Ask AI` feature at https://ossrs.io or https://ossrs.net (for users in China). Duplicate issues or
questions that are overly simple or already addressed in the documentation will be removed without any
response.

**What is the business background? Please provide a description.**
Who are the users? How do they utilize this feature? What problem does this feature address?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
Should follow issue template.
