### ISSUE TITLE
obs publish rtmp stream,rtc play very lagging

### ISSUE THREAD

**Issue by xengine-qyt** [ossrs/srs#4207]
**Describe the bug**
When streaming RTMP using OBS, RTC playback is choppy, but RTMP playback is normal.

**Version**
OBS Version: 30.2.3
player is :
![image](https://github.com/user-attachments/assets/f93a2ab7-8f7e-42df-a2f5-18076e2cf748)

[Desribe your SRS Server version here.](https://github.com/ossrs/srs/commit/364bec264e3ecda3483aaff6c47afaa2d82fc754)

**To Reproduce**
open obs ,create configure .set framerate is 30.set publish stream : rtmp://10.0.3.154/live/livestream.other are default
parameters is : 1920x1080 30fps  2500kbps cbr
                         aac 48000 2channels

http://10.0.3.154:8080/players/whep.html?schema=http.
whep .play http://10.0.3.154:1985/rtc/v1/whep/?app=live&stream=livestream. is ver lag.obs is not lost frame
However, http://10.0.3.154:8080/live/livestream.flv the play is very smooth.just rtc lag.

i test ffmpeg.exe publish steram:./ffmpeg -re -stream_loop -1 -i .\1.mp4  -vcodec copy  -acodec copy -f flv "rtmp://10.0.3.154/live/livestream"
ffmpeg publish rtmp and play rtc is correct

**Expected behavior**
rtc play not lag

**Screenshots**
![image](https://github.com/user-attachments/assets/74f4c790-5916-482a-9306-2168a24e9e52)
![image](https://github.com/user-attachments/assets/ef537fdd-8d0d-4683-b529-9605a7b0dcc9)

**Additional context**

```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        console;
srs_log_file        ./objs/srs.log;
daemon              off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled on;
    listen 8000; # UDP port
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate 10.0.3.154;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
    rtc {
        enabled     on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc on;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp on;
    }

    play{
        gop_cache_max_frames 2500;
    }
}
```

**Comment by winlinvip** [comment]
Should follow issue template.

**Comment by julydate** [comment]
Check your B-frames setting. close it, in obs it should set to 0.

> The issue here is b-frames. As a WebRTC client, according to the standard, you must only support VP8 and H.264 Constrained Baseline (https://datatracker.ietf.org/doc/html/rfc7742#section-5). H.264 Constrained Baseline does not have support for b-frames and therefore it goes wrong when StableFPS sends such. An easy fix, however, is simply to change the video streams in use to StableFPS so that they do not contain b-frames.

See: https://milestonesys.my.site.com/developer/s/question/0D53X0000DFHbQXSQ1/low-frame-rate-issue-with-webrtc-video-streams-from-xprotect-in-chromium-browsers
