### ISSUE TITLE
Docker SRS/5.0.210(Bee) crash

### ISSUE THREAD

**Issue by yrJim** [ossrs/srs#4208]
system log shows:

**Comment by yrJim** [comment]
Oct 22 11:34:32 iZbp1addccvbhjzpbp63bjZ kernel: [11480932.899994] srs-hybrid-2[2506130]: segfault at 10 ip 000055fa0414f820 sp 00007ff408c094f0 error 4 in srs[55fa03ec6000+643000]
Oct 22 11:34:32 iZbp1addccvbhjzpbp63bjZ kernel: [11480932.900003] Code: f8 66 89 50 22 b8 01 00 00 00 eb 05 b8 01 00 00 00 c9 c3 90 f3 0f 1e fa 55 48 89 e5 48 89 7d f8 89 f0 66 89 45 f4 48 8b 45 f8 <48> 8b 48 10 48 8b 45 f8 0f b7 70 08 0f b7 45 f4 ba 00 00 00 00 66

**Comment by yrJim** [comment]
This typically indicates a specific type of memory access error.

**Comment by yrJim** [comment]
error 4 indicates that this segment error was caused by a read operation access crossing the boundary of the user-mode program

**Comment by yrJim** [comment]
but there's no error log in srs.log,how should i do

**Comment by winlinvip** [comment]
Should follow issue template.
