### ISSUE TITLE
SRT stream not available via HTTP-FLV

### ISSUE THREAD

**Issue by pannal** [ossrs/srs#4242]
**Describe the bug**
I'm pushing a h264 stream using OBS to SRS's SRT endpoint. From how I understand the documentation, this should then be exposed via /app/live/key.flv, but it's unplayable (timeout via mpegts.js and VLC). Am I missing something? 

SRS is behind an NGINX reverse proxy if that helps, config:
```
    location / {
        include snippets/authelia/authrequest.conf;
        include snippets/proxy.conf;
        proxy_pass http://127.0.0.1:18080/$request_uri;
    }


    # For SRS homepage, console and players
    #   http://r.ossrs.net/console/
    #   http://r.ossrs.net/players/
    location ~ ^/(console|players)/ {
        include snippets/authelia/authrequest.conf;
        include snippets/proxy.conf;
        proxy_pass http://127.0.0.1:18080/$request_uri;
    }
    # For SRS streaming, for example:
    #   http://r.ossrs.net/live/livestream.flv
    #   http://r.ossrs.net/live/livestream.m3u8
    location ~ ^/.+/.*\.(flv|m3u8|ts|aac|mp3)$ {
        #include snippets/authelia/authrequest.conf;
        #include snippets/proxy.conf;
        proxy_pass http://127.0.0.1:18080$request_uri;
    }
    # For SRS backend API for console.
    # For SRS WebRTC publish/play API.
    location ~ ^/(api|rtc)/ {
        proxy_pass http://127.0.0.1:1985$request_uri;
    }

```

SRS config:
```
# docker config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
# For docker, please use docker logs to manage the logs of SRS.
# See https://docs.docker.com/config/containers/logging/
srs_log_tank        console;
daemon              off;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
rtc_server {
    enabled off;
    listen 8000;
    # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#config-candidate
    candidate $CANDIDATE;
}
#srt_server {
#    enabled on;
#    listen 10080;
#    connect_timeout 4000;
#    peerlatency 300; # RTT * 3
#    recvlatency 300; # RTT * 3
#    latency 300; # RTT * 3
#    tlpktdrop on;
#    tsbpdmode on;
#}
srt_server {
    enabled on;
    listen 10080;
    connect_timeout 4000;
    peerlatency 0;
    recvlatency 0;
    latency 0;
    tlpktdrop off;
    tsbpdmode off;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
    }
    srt {
        enabled     on;
        srt_to_rtmp on;
    }
    http_remux {
        enabled     on;
        mount       /[app]/[stream].flv;
    }
    rtc {
        enabled     off;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtmp-to-rtc
        rtmp_to_rtc off;
        # @see https://ossrs.net/lts/zh-cn/docs/v4/doc/webrtc#rtc-to-rtmp
        rtc_to_rtmp off;
    }
}
```

Docker-Compose:
```
srs:
    container_name: srs
    image: ossrs/srs:v6
    volumes:
      - /etc/srs/docker.conf:/usr/local/srs/conf/docker.conf
    ports:
      - 1339:1935/tcp
      - 127.0.0.1:1985:1985
      - 127.0.0.1:18080:8080
      - 8000:8000/udp
      - 10080:10080/udp
```

**Version**
SRS V6 docker (via dockerhub), SRS/6.0.155

**Comment by suzp1984** [comment]
The nginx config its proxy:

```
location ~ ^/.+/.*\.(flv|m3u8|ts|aac|mp3)$ {
        #include snippets/authelia/authrequest.conf;
        #include snippets/proxy.conf;
        proxy_pass http://127.0.0.1:18080$request_uri;
    }
```

proxy to `127.0.0.0:18080`, but srs config its http server listen on `8080`:

```
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
```

**Comment by pannal** [comment]
Yes, the port is remapped in docker to expose on 18080 because the port is already in use on the host machine from another service. 

To be clear: this Config works when directly streaming to RTMP and using the .flv URL in VLC or mpegts.js.

Only when publishing using SRT the flv is not available/doesn't load (times out).

**Comment by pannal** [comment]
Can I get you some logs? Any debug settings I need? 

Edit: Updated the first post with the docker config and specific version of SRS 6.

**Comment by suzp1984** [comment]
>  - 127.0.0.1:18080:8080

Is the `http://127.0.0.1:18080/live/livestream.flv` plays well in your localhost?

**Comment by pannal** [comment]
It plays well using RTMP and playing via the external https://domain/live/livestream.flv, yes (via the NGINX location, which uses `http://127.0.0.1:18080/live/livestream.flv`).

But not for SRT.

**Comment by suzp1984** [comment]
I tried your srs conf, SRT publish and http-flv plays well in my machine.

`ffmpeg -re -i source.flv  -c copy -f mpegts 'srt://localhost:10080?streamid=#!::r=live/livestream,m=publish'`
`ffplay http://localhost:8080/live/livestream.flv`

Try above two cmds, check in your env.

**Comment by pannal** [comment]
Does `ffplay http://localhost:18080/live/livestream.flv` work as well? Because that's the port used for exposing the streams.

**Comment by pannal** [comment]
@suzp1984 You're right, I must've been doing something wrong.

When trying to play back an SRT HEVC stream, it still works with mpegts.js, but ffplay shows:
```
[flv @ 000001c756560600] Video codec (c) is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[flv @ 000001c756560600] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[flv @ 000001c756560600] Video codec (c) is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[flv @ 000001c756560600] If you want to help, upload a sample of this file to https://streams.videolan.org/upload/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
```

How would I push an AV1 stream via SRT, to get it inside stream.flv to be played back with mpegts.js? That wouldn't work via srt_to_rtmp I guess, but would need a remux? (AV1 is possible inside mpegts.js in the development version AFAIK)

The doc states:
```
Does SRS support forwarding SRT streams to Nginx?
Yes, it is supported. You can use OBS/FFmpeg to push SRT streams to SRS, and SRS will convert the SRT stream into the RTMP protocol. Then, you can convert RTMP to HLS, FLV, WebRTC, and also forward the RTMP stream to Nginx.
```
Why the intermediate step to RTMP? That severely limits the video codecs one can use.

**Comment by suzp1984** [comment]
That's What the `SRS` name initially short for? `SRS == Simple RTMP Server`.

**Comment by pannal** [comment]
If that's the answer to any feature requests, that'd be sad.

No, honestly: Would it be possible to not have that intermediate step to RTMP? Or, ideally, support the latest ERTMP spec out of the box? Thank you!

**Comment by suzp1984** [comment]
SRS support Enhanced RTMP, but only HEVC(H.265) code.

**Comment by pannal** [comment]
Yes, that's why I was referring to _the latest ERTMP spec_, which is Enhanced RTMP V2: https://veovera.org/docs/enhanced/enhanced-rtmp-v2.html

**Comment by zapf2000** [comment]
As far as i know, AV1 is not yet supported with SRT (only WebRTC and eRTMP), because SRT uses MPEG-TS and AV1 is not yet implemented for transport stream usage.

**Comment by pannal** [comment]
SRT is codec agnostic by nature, but relies on MPEGTS, correct; Nimble for example accepts [AV1 via SRT already](https://softvelum.com/nimble/av1/); the other current MPEGTS implementations don't (FFmpeg at least [doesn't](https://github.com/Vincit/ffmpeg/blob/master/libavformat/mpegtsenc.c#L291)); Not sure if [the spec](https://aomediacodec.github.io/av1-mpeg2-ts/) is even finalized yet: https://github.com/AOMediaCodec/av1-mpeg2-ts/issues/

So the only option at the moment would be to implement the Enhanced RTMP V2 spec

**Comment by pannal** [comment]
But the original issue has been resolved, so let's continue here: https://github.com/ossrs/srs/issues/4239
