### ISSUE TITLE
字符串方式Ingester：如何添加 ffmpeg 选项？ 例如rtsp 传输模式 (tcp/udp/http)? 

### ISSUE THREAD

**Issue by sealand210** [ossrs/srs#447]
请问 如何在ingest 配置文件中 添加rtsp 的传输模式设定？ 

例如现在程序生成的指令是：
ffmpeg -i rtsp://xxx.xxx.xxx.xxx:554  -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=**defaultVhost**/livestream

但是需要的指令是：
 ffmpeg -rtsp_transport tcp -i rtsp://xxx.xxx.xxx.xxx:554  -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=**defaultVhost**/livestream

谢谢

**Comment by winlinvip** [comment]
https://github.com/simple-rtmp-server/srs/wiki/v2_CN_FFMPEG#transcode-rulers

**Comment by winlinvip** [comment]
Refer to vfilter.

`TRANS_BY_GPT3`

**Comment by sealand210** [comment]
Vfilter tried, but it didn't work.
> On 28 Jul 2015, at 7:54 am, winlin notifications@github.com wrote:
> 
> Closed #447 https://github.com/simple-rtmp-server/srs/issues/447.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/simple-rtmp-server/srs/issues/447#event-366671930.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Need to add an option before vfilter.

`TRANS_BY_GPT3`

**Comment by miracletao** [comment]
Code has been added
![image](https://cloud.githubusercontent.com/assets/21237296/17961645/88a165f2-6adf-11e6-8447-8dc35439cbae.png) 
The execution still has errors.
![image](https://cloud.githubusercontent.com/assets/21237296/17961656/99f8d970-6adf-11e6-9972-c23ba53ddb1b.png)
However, it runs normally directly in the command line.
![image](https://cloud.githubusercontent.com/assets/21237296/17961672/ac5e5950-6adf-11e6-9e38-1987af1d3891.png)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It should be two parameters, "rtsp_transport" and "tcp", instead of one parameter separated by a space.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Ingest is better to support a string, along with some variables, such as the stream name, see: #1329

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Postpone to SRS4.

**Comment by winlinvip** [comment]
Fixed in SRS4
