### ISSUE TITLE
Mix audio streams to one audio, 服务器混音

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#481]
服务器上可以对多路音频解码后合并，然后再编码成一个音频流。
服务器可以收到包后直接处理，而不用再拉流出去合并再送回来，延迟会很低。

**Comment by winlinvip** [comment]
Can be used in video conferences, online hosting with one-way video and multiple-way audio, and external audio input.

`TRANS_BY_GPT3`

**Comment by wenjiegit** [comment]
The synthesis and encoding of audio consume less, so it can be considered for integration.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Audio mixing may not be necessary to support, audio ranking can be used.
For gb18181 monitoring scenarios, audio transcoding may be required. #1500

`TRANS_BY_GPT3`
