### ISSUE TITLE
Support for Multibitrate rtmp(smil generation)

### ISSUE THREAD

**Issue by genxstylez** [ossrs/srs#488]
As titled.

**Comment by winlinvip** [comment]
RTMP multiple bitrates not supported yet.
HLS multiple bitrates: #463

Seems the multiple bitrates, both RTMP and HLS are useless in China.
What about your use scenarios?

**Comment by genxstylez** [comment]
I am starting out the project in Taiwan,

"Seems the multiple bitrates, both RTMP and HLS are useless in China.
What about your use scenarios?" - Why is that?

**Comment by winlinvip** [comment]
Sorry, I means I don't know the use scenario of multiple RTMP streams.

**Comment by genxstylez** [comment]
It would be just a live stream with different bitrate? to accomodate various bandwidth such as LTE, 3g , Wifi etc.

**Comment by genxstylez** [comment]
any updates on this?

**Comment by winlinvip** [comment]
Nop, no plan for this issue.

**Comment by genxstylez** [comment]
ok, no worries
