### ISSUE TITLE
推送流媒体bug

### ISSUE THREAD

**Issue by MSG-maniac** [ossrs/srs#491]
例如推送地址rtmp://172.17.30.150:1935/wlhd/lost
hls切片目录为/usr/share/nginx/html
那么切片地址就会变为/usr/share/nginx/html/wlhd/lost/目录下切片，并且没有m3u8文件
正常应该是/usr/share/nginx/html/wlhd/lost.m3u8
[root@localhost lost]# ls
-0.ts  -1.ts  -2.ts  -3.ts.tmp

**Comment by MSG-maniac** [comment]
[root@localhost lost]# cat  /usr/local/srs/conf/srs.conf   
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
        hls {
                enabled         on;
                hls_path        /usr/share/nginx/html;
                hls_fragment    10;
                hls_window      60;
        }
}

**Comment by winlinvip** [comment]
Please provide the SRS log, the streaming command, and the source file for streaming (if possible, you can put it on Baidu Netdisk).

`TRANS_BY_GPT3`

**Comment by lostmaniac** [comment]
Link: http://pan.baidu.com/s/1gd2gdkJ Password: vgqy
This is a log,
Pushing my local camera and audio, the pushing software is OBS version 0.11.4.

I will save the virtual machine, if needed, you can contact me for remote testing.

`TRANS_BY_GPT3`

**Comment by lostmaniac** [comment]
If it is done using ff for pushing, there is no problem. I haven't tested other software.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
What does the configuration of OBS look like?

`TRANS_BY_GPT3`

**Comment by lostmaniac** [comment]
One installation package, CentOS system, the configuration file is the one above. SRS is not very stable when used in a production environment, there may be issues, the pull part is very good, but occasionally it will exit abnormally. I will open another question later, and also send the logs.

`TRANS_BY_GPT3`

**Comment by lostmaniac** [comment]
The default configuration of OBS, only modified the rtmp address.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
You can configure the paths for HLS output m3u8 and ts files.

`TRANS_BY_GPT3`

**Comment by xinst** [comment]
How was it finally resolved? I have the same problem.

`TRANS_BY_GPT3`

**Comment by ChandZhang** [comment]
OBS by default appends a slash to the URL, which means there is no stream name when parsing. If not using OBS, you can enter the stream name followed by parameters in the Stream key.
streamname?querystring  @xinst 

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Will OBS have this problem? It seems like I haven't encountered it, maybe it's related to the OBS version...

`TRANS_BY_GPT3`
