### ISSUE TITLE
vhost支持通配子域名

### ISSUE THREAD

**Issue by walkermi** [ossrs/srs#492]
1、能否支持conf文件类似nginx的include指令？这样有较多vhost方便管理？

2、能否支持泛域名的vhost，比如_.srs.com，_.demo.srs.com？

**Comment by walkermi** [comment]
The mobile submission cannot display asterisks, there are asterisks in front of the domain name!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
1. The RAW API will support API management configuration, and the configuration file will become internal. Reference: #319
2. Why is it necessary to support wildcard domains, such as `*.srs.com`?

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
For example, both sets of wildcard domains, _.srs.net and _.srs.com, are resolved to the same IP address of SRS. Each set has its own separate conf information.
We want 123.srs.net, 456.srs.net, demo.srs.net... to have the same configuration. And xoxo.srs.com, xxxx.srs.com, yyyy.srs.com... to have another configuration. If wildcard domains are not supported, how many VHosts do we need to write?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Why are there so many subdomains? What is your business?
## 








I will do my best!
winlin.








On 2015-09-23 14:19:53, "walkermi" notifications@github.com wrote:




For example, both .srs.net and .srs.com wildcard domains are resolved to the same SRS IP, but each group has its own separate conf information. I hope that 123.srs.net, 456.srs.net, demo.srs.net... have the same configuration, and xoxo.srs.com, xxxx.srs.com, yyyy.srs.com... have another configuration. If wildcard domains are not supported, how many VHosts would need to be written?




—' translates to '—' in English.
Reply to this email directly or view it on GitHub.




`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
A small platform for individuals (wedding photography, company meeting recording). Each registrant can have their own second-level or third-level domain name, and the APP and Stream can be independently customized under the domain name.

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
For example, when user A registers, they automatically obtain the domain name usera.srs.com and can create multiple apps under that VHost.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Oh, I see. Why not use multiple apps and streams instead of multiple subdomains?

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
What if both user A and user B want to create an app called "live"? What if there are even dozens of users on the platform who want to have an app called "live"?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Registrants can have multiple users, and each user can choose their own app and stream.

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
Yes, that's the requirement.

`TRANS_BY_GPT3`

**Comment by limjoe** [comment]
There is also such a scenario to solve the limitation of the number of concurrent streams pulled by the web player under the same domain name.

In the large screen monitoring business, a large screen will simultaneously play 8 or more than 16 video streams. However, the browser has limitations on the number of streams pulled under the same domain name.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS 4.0 supports include.
