### ISSUE TITLE
source 对 forward/hls/hds/dvr/trancode  reload的处理有问题

### ISSUE THREAD

**Issue by zhengfl** [ossrs/srs#503]
在对forward/hls/hds/dvr/trancode做reload操作时，需要判断源流是否在推（origin），或者拉（edge）。若源流已断开，不需要做reload操作

**Comment by winlinvip** [comment]
Assignee to Li Qiang, Feilong will make the changes whenever he is free. If it is not changed before the release, I will make the changes.

`TRANS_BY_GPT3`

**Comment by zhengfl** [comment]
Reproduction steps:
Streaming (forward/hls/dvr... start) --> Stop streaming (forward/hls/dvr... stop) --> Modify configuration (forward/hls/dvr...) --> Reload (forward/hls/dvr started again)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Replay is succeed.
