### ISSUE TITLE
Using HLS and http callback

### ISSUE THREAD

**Issue by paulashford1975** [ossrs/srs#504]
Hi, so I've configured the SRS for HLS --with-nginx however If I add --with-http-callback the build fails, so looks like its dependant on --with-http-server. Therefore how can I produce HLS and use the http callbacks? Thanks

**Comment by winlinvip** [comment]
It's should be ok for the `--with-hls`, `--with-nginx`, `--with-http-callback`, and it must be bug if not.
What is your OS, SRS version, configure command?

**Comment by paulashford1975** [comment]
Using the latest SRS 2 source. Running ./configure --disable-all --with-ssl --with-hls --with-nginx --with-http-callback --with-ingest --with-dvr --with-transcode. Running a MAKE I receive the following;

          -o objs/src/app/srs_app_http_conn.o src/app/srs_app_http_conn.cpp
src/app/srs_app_http_conn.cpp: In constructor ‘SrsHttpServer::SrsHttpServer(SrsServer*)’:
src/app/srs_app_http_conn.cpp:1294:46: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     http_stream = new SrsHttpStreamServer(svr);
                                              ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1295:46: error: invalid use of incomplete type ‘class SrsHttpStaticServer’
     http_static = new SrsHttpStaticServer(svr);
                                              ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: error: forward declaration of ‘class SrsHttpStaticServer’
 class SrsHttpStaticServer;
       ^
In file included from src/app/srs_app_http_conn.hpp:31:0,
                 from src/app/srs_app_http_conn.cpp:24:
src/app/srs_app_http_conn.cpp: In destructor ‘virtual SrsHttpServer::~SrsHttpServer()’:
src/app/srs_app_http_conn.cpp:1300:15: warning: possible problem detected in invocation of delete operator: [enabled by default]
     srs_freep(http_stream);
               ^
src/core/srs_core.hpp:102:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp:1300:15: warning: invalid use of incomplete type ‘class SrsHttpStreamServer’ [enabled by default]
     srs_freep(http_stream);
               ^
src/core/srs_core.hpp:102:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: warning: forward declaration of ‘class SrsHttpStreamServer’ [enabled by default]
 class SrsHttpStreamServer;
       ^
In file included from src/app/srs_app_http_conn.hpp:31:0,
                 from src/app/srs_app_http_conn.cpp:24:
src/app/srs_app_http_conn.cpp:1300:15: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     srs_freep(http_stream);
               ^
src/core/srs_core.hpp:102:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp:1301:15: warning: possible problem detected in invocation of delete operator: [enabled by default]
     srs_freep(http_static);
               ^
src/core/srs_core.hpp:102:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp:1301:15: warning: invalid use of incomplete type ‘class SrsHttpStaticServer’ [enabled by default]
     srs_freep(http_static);
               ^
src/core/srs_core.hpp:102:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: warning: forward declaration of ‘class SrsHttpStaticServer’ [enabled by default]
 class SrsHttpStaticServer;
       ^
In file included from src/app/srs_app_http_conn.hpp:31:0,
                 from src/app/srs_app_http_conn.cpp:24:
src/app/srs_app_http_conn.cpp:1301:15: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined
     srs_freep(http_static);
               ^
src/core/srs_core.hpp:102:16: note: in definition of macro ‘srs_freep’
         delete p; \
                ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::initialize()’:
src/app/srs_app_http_conn.cpp:1315:27: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     if ((ret = http_stream->initialize()) != ERROR_SUCCESS) {
                           ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1319:27: error: invalid use of incomplete type ‘class SrsHttpStaticServer’
     if ((ret = http_static->initialize()) != ERROR_SUCCESS) {
                           ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: error: forward declaration of ‘class SrsHttpStaticServer’
 class SrsHttpStaticServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::serve_http(ISrsHttpResponseWriter*, ISrsHttpMessage*)’:
src/app/srs_app_http_conn.cpp:1329:20: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     if (http_stream->mux.can_serve(r)) {
                    ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1330:27: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
         return http_stream->mux.serve_http(w, r);
                           ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp:1333:23: error: invalid use of incomplete type ‘class SrsHttpStaticServer’
     return http_static->mux.serve_http(w, r);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:71:7: error: forward declaration of ‘class SrsHttpStaticServer’
 class SrsHttpStaticServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::http_mount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1338:23: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     return http_stream->http_mount(s, r);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual void SrsHttpServer::http_unmount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1343:16: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     http_stream->http_unmount(s, r);
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::mount_hls(SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1348:23: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     return http_stream->mount_hls(r);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_update_m3u8(SrsRequest*, std::string)’:
src/app/srs_app_http_conn.cpp:1353:23: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     return http_stream->hls_update_m3u8(r, m3u8);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_update_ts(SrsRequest*, std::string, std::string)’:
src/app/srs_app_http_conn.cpp:1358:23: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     return http_stream->hls_update_ts(r, uri, ts);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_remove_ts(SrsRequest*, std::string)’:
src/app/srs_app_http_conn.cpp:1363:23: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     return http_stream->hls_remove_ts(r, uri);
                       ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual void SrsHttpServer::unmount_hls(SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1368:16: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     http_stream->unmount_hls(r);
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: error: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::serve_http(ISrsHttpResponseWriter*, ISrsHttpMessage*)’:
src/app/srs_app_http_conn.cpp:1334:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::http_mount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1339:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::mount_hls(SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1349:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_update_m3u8(SrsRequest*, std::string)’:
src/app/srs_app_http_conn.cpp:1354:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_update_ts(SrsRequest*, std::string, std::string)’:
src/app/srs_app_http_conn.cpp:1359:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_remove_ts(SrsRequest*, std::string)’:
src/app/srs_app_http_conn.cpp:1364:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [objs/src/app/srs_app_http_conn.o] Error 1
make[2]: Leaving directory `/usr/local/srs'
make[1]: *** [server] Error 2
make[1]: Leaving directory `/usr/local/srs'
make: *** [default] Error 2

**Comment by winlinvip** [comment]
I's a bug of SRS2, I will fix it.

**Comment by paulashford1975** [comment]
ok super, I did realise that I was pulling down the master and not the srs2release but will wait for the fix, may thanks for your assistance

**Comment by winlinvip** [comment]
Not need to use SRS1, there is a workaround:

```
./configure --with-ssl --with-hls --with-nginx --with-http-callback --with-ingest --with-dvr --with-transcode
```

It's ok, for it's just a bug for macro check. Please try it~

**Comment by paulashford1975** [comment]
on another note. I'm streaming a video using OBS to our SRS server, setup with HLS. However when playing the stream using HLS it keeps stopping and pausing and is not constant or smooth. Is there anything else I can check?

**Comment by winlinvip** [comment]
What's your SRS config and log?

**Comment by paulashford1975** [comment]
srs.conf >

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
        hls {
                enabled         on;
                hls_path        ./objs/nginx/html;
                hls_fragment    10;
                hls_window      60;
                hls_on_error    continue;
        }


}

**Comment by paulashford1975** [comment]
log file when streaming to the server;

[2015-10-20 08:18:21.537][trace][43060][0] grandpa process exit.
[2015-10-20 08:18:21.537][trace][43062][100] write pid=43062 to ./objs/srs.pid success!
[2015-10-20 08:18:21.548][trace][43062][100] RTMP listen at tcp://0.0.0.0:1935, fd=8
[2015-10-20 08:18:21.548][trace][43062][100] signal installed
[2015-10-20 08:18:21.568][trace][43062][100] ingest thread cid=103, current_cid=100
[2015-10-20 08:19:16.513][trace][43062][105] RTMP client ip=193.34.187.198
[2015-10-20 08:19:16.513][trace][43062][105] srand initialized the random.
[2015-10-20 08:19:16.605][trace][43062][105] simple handshake success.
[2015-10-20 08:19:16.694][trace][43062][105] input chunk size to 4096
[2015-10-20 08:19:16.695][trace][43062][105] connect app, tcUrl=http://live.yellowroc.net/live, pageUrl=, swfUrl=http://live.yellowroc.net/live, schema=http, vhost=__defaultVhost__, port=1935, app=live, args=null
[2015-10-20 08:19:16.695][trace][43062][105] out chunk size to 60000
[2015-10-20 08:19:16.873][trace][43062][105] client identified, type=fmle-publish, stream_name=livestream, duration=-1.00
[2015-10-20 08:19:16.893][trace][43062][105] source url=/live/livestream, ip=193.34.187.198, cache=1, is_edge=0, source_id=-1[-1]
[2015-10-20 08:19:17.137][trace][43062][105] hls: win=60.00, frag=10.00, prefix=, path=./objs/nginx/html, m3u8=[app]/[stream].m3u8, ts=[app]/[stream]-[seq].ts, aof=2.00, floor=0, clean=1, waitk=1, dispose=0
[2015-10-20 08:19:17.147][trace][43062][105] start publish mr=0/350, p1stpt=20000, pnt=20000, tcp_nodelay=0, rtcid=108
[2015-10-20 08:19:17.314][trace][43062][105] got metadata, width=1024, height=640
[2015-10-20 08:19:18.235][trace][43062][105] 4B audio sh, codec(10, profile=LC, 2channels, 0kbps, 44100HZ), flv(16bits, 2channels, 44100HZ)
[2015-10-20 08:19:18.236][trace][43062][105] 47B video sh,  codec(7, profile=High, level=3.1, 1024x768, 0kbps, 0fps, 0s)
[2015-10-20 08:19:26.613][trace][43062][105] -> HLS time=10001, stream dts=752940(8366ms), sno=1, ts=livestream-0.ts, dur=8.37, dva=0p
[2015-10-20 08:19:36.616][trace][43062][105] -> HLS time=20001, stream dts=1652940(18366ms), sno=2, ts=livestream-1.ts, dur=4.83, dva=0p
[2015-10-20 08:19:46.615][trace][43062][105] -> HLS time=30002, stream dts=2552940(28366ms), sno=3, ts=livestream-2.ts, dur=4.23, dva=0p
[2015-10-20 08:19:56.616][trace][43062][105] -> HLS time=40002, stream dts=3452940(38366ms), sno=4, ts=livestream-3.ts, dur=1.50, dva=0p
[2015-10-20 08:19:57.148][trace][43062][105] <- CPB time=20001, okbps=0,0,0, ikbps=2546,2546,0, mr=0/350, p1stpt=20000, pnt=20000
[2015-10-20 08:20:06.623][trace][43062][105] -> HLS time=50003, stream dts=4356000(48400ms), sno=4, ts=livestream-3.ts, dur=11.53, dva=0p
[2015-10-20 08:20:16.641][trace][43062][105] -> HLS time=60003, stream dts=5252940(58366ms), sno=5, ts=livestream-4.ts, dur=9.83, dva=0p
[2015-10-20 08:20:17.148][trace][43062][105] <- CPB time=40002, okbps=0,0,0, ikbps=2590,2546,0, mr=0/350, p1stpt=20000, pnt=20000
[2015-10-20 08:20:26.665][trace][43062][105] -> HLS time=70004, stream dts=6156000(68400ms), sno=6, ts=livestream-5.ts, dur=5.80, dva=0p
[2015-10-20 08:20:36.637][trace][43062][105] -> HLS time=80004, stream dts=7056000(78400ms), sno=7, ts=livestream-6.ts, dur=2.47, dva=0p
[2015-10-20 08:20:37.148][trace][43062][105] <- CPB time=60003, okbps=0,0,0, ikbps=2600,2655,0, mr=0/350, p1stpt=20000, pnt=20000
[2015-10-20 08:20:46.661][trace][43062][105] -> HLS time=90005, stream dts=7956000(88400ms), sno=8, ts=livestream-7.ts, dur=1.87, dva=0p
[2015-10-20 08:20:56.637][trace][43062][105] -> HLS time=100006, stream dts=8856000(98400ms), sno=8, ts=livestream-7.ts, dur=11.87, dva=0p
[2015-10-20 08:20:57.148][trace][43062][105] <- CPB time=80004, okbps=0,0,0, ikbps=2615,2655,0, mr=0/350, p1stpt=20000, pnt=20000
[2015-10-20 08:21:06.634][trace][43062][105] -> HLS time=110007, stream dts=9756000(108400ms), sno=9, ts=livestream-8.ts, dur=8.73, dva=0p
[2015-10-20 08:21:16.629][trace][43062][105] -> HLS time=120008, stream dts=10656000(118400ms), sno=10, ts=livestream-9.ts, dur=7.47, dva=0p
[2015-10-20 08:21:17.148][trace][43062][105] <- CPB time=100006, okbps=0,0,0, ikbps=2628,2685,0, mr=0/350, p1stpt=20000, pnt=20000
[2015-10-20 08:21:26.674][trace][43062][105] -> HLS time=130009, stream dts=11558970(128433ms), sno=11, ts=livestream-10.ts, dur=3.40, dva=0p
[2015-10-20 08:21:36.662][trace][43062][105] -> HLS time=140009, stream dts=12440970(138233ms), sno=11, ts=livestream-10.ts, dur=13.20, dva=0p
[2015-10-20 08:21:37.148][trace][43062][105] <- CPB time=120008, okbps=0,0,0, ikbps=2619,2685,0, mr=0/350, p1stpt=20000, pnt=20000
[2015-10-20 08:21:46.654][trace][43062][105] -> HLS time=150010, stream dts=13356000(148400ms), sno=12, ts=livestream-11.ts, dur=10.03, dva=0p
[2015-10-20 08:21:56.675][trace][43062][105] -> HLS time=160011, stream dts=14258970(158433ms), sno=13, ts=livestream-12.ts, dur=9.47, dva=0p
[2015-10-20 08:21:57.148][trace][43062][105] <- CPB time=140009, okbps=0,0,0, ikbps=2631,2639,0, mr=0/350, p1stpt=20000, pnt=20000
[2015-10-20 08:21:59.110][trace][43062][105] cleanup when unpublish
[2015-10-20 08:21:59.111][trace][43062][105] control message(unpublish) accept, retry stream service.
[2015-10-20 08:21:59.111][warn][43062][105][104] client disconnect peer. ret=1004

**Comment by winlinvip** [comment]
Seems no problem, can u email me the HLS files(m3u8 and ts)?
email: winlin at vip.126.com

**Comment by paulashford1975** [comment]
Also noticed that when publishing stops it does not clear down the files also recorded the following in the srs.log;

[2015-10-08 09:33:40.291][trace][3547][111] cleanup when unpublish
[2015-10-08 09:33:40.291][trace][3547][111] control message(unpublish) accept, retry stream service.
[2015-10-08 09:33:40.291][error][3547][111][32] send with writev failed. ret=1009(Broken pipe)
[2015-10-08 09:33:40.291][warn][3547][111][32] response call failed. ret=1009
[2015-10-08 09:33:40.292][warn][3547][111][32] client disconnect peer. ret=1004
[2015-10-08 09:33:40.292][warn][3547][111][22] join thread failed. code=-1

**Comment by winlinvip** [comment]
When encoder unpublish, SRS won't cleanup the files which is still active in m3u8, unless user required to do this by config the `hls_dispose`.

**Comment by diguasange** [comment]
系统为Cent OS 6.8,64bit
编译命令如下：
`./configure --rtmp-hls --with-http-api --with-ffmpeg && make`
编译时出现如下错误：
`-o objs/src/app/srs_app_http_conn.o src/app/srs_app_http_conn.cpp
src/app/srs_app_http_conn.cpp: In constructor ‘SrsHttpServer::SrsHttpServer(SrsServer*)’:
src/app/srs_app_http_conn.cpp:1346: error: invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: error: forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1347: error: invalid use of incomplete type ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.hpp:71: error: forward declaration of ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.cpp: In destructor ‘virtual SrsHttpServer::~SrsHttpServer()’:
src/app/srs_app_http_conn.cpp:1352: warning: possible problem detected in invocation of delete operator:
src/app/srs_app_http_conn.cpp:1352: warning: invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: warning: forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1352: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined.
src/app/srs_app_http_conn.cpp:1353: warning: possible problem detected in invocation of delete operator:
src/app/srs_app_http_conn.cpp:1353: warning: invalid use of incomplete type ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.hpp:71: warning: forward declaration of ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.cpp:1353: note: neither the destructor nor the class-specific operator delete will be called, even if they are declared when the class is defined.
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::initialize()’:
src/app/srs_app_http_conn.cpp:1367: error: invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: error: forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1371: error: invalid use of incomplete type ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.hpp:71: error: forward declaration of ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::serve_http(ISrsHttpResponseWriter*, ISrsHttpMessage*)’:
src/app/srs_app_http_conn.cpp:1381: error: invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: error: forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1382: error: invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: error: forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1385: error: invalid use of incomplete type ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.hpp:71: error: forward declaration of ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::http_mount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1390: error: invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: error: forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual void SrsHttpServer::http_unmount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1395: error: invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: error: forward declaration of ‘struct SrsHttpStreamServer’
make[2]: *** [objs/src/app/srs_app_http_conn.o] Error 1
make[2]: Leaving directory `/usr/src/git-2.0.5/srs/trunk'
make[1]: *** [server] Error 2
make[1]: Leaving directory `/usr/src/git-2.0.5/srs/trunk'
make: *** [default] Error 2`
请问该怎么解决？
