### ISSUE TITLE
HLS自动检测纯音频

### ISSUE THREAD

**Issue by niuxsh** [ossrs/srs#506]
SRS对纯音频切片时，需要添加如下类似配置：

```
 hls_vcodec      vn;
 hls_acodec      aac;
```

我想了个办法，收到音频时就写只包含音频的PMT，收到视频时，根据文件偏移，重写PMT（加上视频信息），这样就不用增加任何配置了，我在nginx_rtmp的代码上实现后测试没问题。不知道SRS这样是否可行？

**Comment by winlinvip** [comment]
This plan is feasible and the solution is relatively comprehensive. It can be considered for future versions of SRS.
1. Writing the offset will be more complicated, especially when SRS supports stream writing, such as directly writing to the network stream in http-ts, which cannot be rewritten. Therefore, implementing a buffer is the only option, which makes it even more complex.
2. For applications that are purely audio, they are generally fixed, such as radio stations, which are definitely pure audio, so they can be configured.

Based on these two reasons, we will temporarily not consider this and keep the configuration as it is.

`TRANS_BY_GPT3`
