### ISSUE TITLE
HLS ram-storage overflow

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#513]
I use ram storage for HLS (SRS 3.0) and find some trouble.
It seem to ram not free when old HLS part has been cleaned.
Thanks for you work. SRS 3.0 is great!

@see https://github.com/winlinvip/simple-rtmp-server/issues/411
https://github.com/icevl @icevl

**Comment by winlinvip** [comment]
HLS RAM功能将会从SRS中去掉，在SRS3中考虑是否支持。
主要因为linux支持挂载RAM到磁盘，和HLS RAM功能重合。另外HLS的瓶颈也不在这个地方。
所以这个功能很鸡肋，白白增加了许多的复杂性。

配置依然保留，为了兼容。但是会给出警告，并且这个功能会禁用。
也就是如果你用了HLS RAM，那么还是能运行，但是不起作用了。

**Comment by winlinvip** [comment]
已经去掉了hls ram。

**Comment by winlinvip** [comment]
HLS RAM is removed from SRS2 and SRS3, user can mount RAM to disk and use ordinary HLS.

**Comment by hy05190134** [comment]
@winlinvip  这个是不是就是 hls+ 的功能？
