### ISSUE TITLE
"&" in ffmpeg stream path

### ISSUE THREAD

**Issue by icevl** [ossrs/srs#517]
Hi! I found that if i have "&" in my stream path, ffmpeg not runing correctly and in result srs crash!
I have camera with "&" in rtsp stream path.
Thanks.

**Comment by winlinvip** [comment]
What's your SRS version?

**Comment by winlinvip** [comment]
And the config and log please.

**Comment by icevl** [comment]
SRS 3.0 develop
rtsp://admin:pass@10.101.3.4:554/cam/realmonitor?channel=1&subtype=1

**Comment by icevl** [comment]
[NULL @ 0x387d9c0] Unable to find a suitable output format for '1>'
1>: Invalid argument
rtmp://0.0.0.0:1935/live?vhost=s1.cam.utl.ru/cam50: Input/output error
rtmp://0.0.0.0:1935/live?vhost=s2.cam.utl.ru/cam50: Input/output error
rtmp://0.0.0.0:1935/live?vhost=s1.cam.utl.ru/cam48: Input/output error
rtmp://0.0.0.0:1935/live?vhost=s1.cam.utl.ru/cam51: Input/output error
rtmp://0.0.0.0:1935/live?vhost=s2.cam.utl.ru/cam48: Input/output error
Segmentation fault (core dumped)
root@cam0:/home/srs/srs/trunk# Input #0, rtsp, from 'rtsp://utl:1597531234@10.101.3.4:554/cam/realmonitor?channel=1&subtype=0':
  Metadata:
    title           : RTSP Session/2.0
  Duration: N/A, start: 0.760000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc), 1920x1080, 25 fps, 25 tbr, 90k tbn, 50 tbc
[tcp @ 0x1d88ae0] Connection to tcp://0.0.0.0:1935 failed: Connection refused
[rtmp @ 0x1d999a0] Cannot open connection tcp://0.0.0.0:1935
rtmp://0.0.0.0:1935/live?vhost=s1.cam.utl.ru/cam53: Connection refused

**Comment by winlinvip** [comment]
Got it, I will fix it ASAP~

**Comment by icevl** [comment]
I pull latest development source (SRS 3) and compile. 
When I run stream from my camera to ingest in console it work fine without connection reset ...
But in SRS ingest i see error "connection reset by peer". 

[ffmpeg-ingest-s1.cam.utl.ru-cam53.txt](https://github.com/ossrs/srs/files/32416/ffmpeg-ingest-s1.cam.utl.ru-cam53.txt)
[running from console.txt](https://github.com/ossrs/srs/files/32412/running.from.console.txt)

**Comment by winlinvip** [comment]
SEEMS the ingester has lots of problems~~~

**Comment by icevl** [comment]
another stream from this camera:

```

process parent pid=20145
process parent cid=105
process binary=./objs/ffmpeg/bin/ffmpeg
process cli: ./objs/ffmpeg/bin/ffmpeg -i rtsp://utl:1597531234@10.101.3.4:554/cam/realmonitor?channel=1&subtype=1 -vcodec copy -an -f flv -y rtmp://0.0.0.0:1935/live?vhost=s2.cam.utl.ru/cam53 1 > ./objs/ffmpeg-ingest-s2.cam.utl.ru-cam53.log 2 > ./objs/ffmpeg-ingest-s2.cam.utl.ru-cam53.log
ffmpeg version 2.1.1 Copyright (c) 2000-2013 the FFmpeg developers
  built on Oct  2 2015 10:23:34 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --enable-gpl --enable-nonfree --yasmexe=/home/ice/srs3.0/trunk/objs/ffmpeg.src/_release/bin/yasm --prefix=/home/ice/srs3.0/trunk/objs/ffmpeg.src/_release --cc= --enable-static --disable-shared --disable-debug --extra-cflags='-I${ffmpeg_exported_release_dir}/include' --extra-ldflags='-L${ffmpeg_exported_release_dir}/lib -lm -ldl' --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --enable-postproc --enable-bzlib --enable-zlib --enable-parsers --enable-libx264 --enable-libmp3lame --enable-libfdk-aac --enable-libspeex --enable-pthreads --extra-libs=-lpthread --enable-encoders --enable-decoders --enable-avfilter --enable-muxers --enable-demuxers
  libavutil      52. 48.101 / 52. 48.101
  libavcodec     55. 39.101 / 55. 39.101
  libavformat    55. 19.104 / 55. 19.104
  libavdevice    55.  5.100 / 55.  5.100
  libavfilter     3. 90.100 /  3. 90.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100
Input #0, rtsp, from 'rtsp://utl:1597531234@10.101.3.4:554/cam/realmonitor?channel=1&subtype=1':
  Metadata:
    title           : RTSP Session/2.0
  Duration: N/A, start: 2.080000, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuvj420p(pc), 704x576, 25 fps, 25 tbr, 90k tbn, 50 tbc
Output #0, flv, to 'rtmp://0.0.0.0:1935/live?vhost=s2.cam.utl.ru/cam53':
  Metadata:
    title           : RTSP Session/2.0
    encoder         : Lavf55.19.104
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuvj420p, 704x576, q=2-31, 25 fps, 1k tbn, 90k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
av_interleaved_write_frame(): Connection reset by peer
```

**Comment by icevl** [comment]
it seem trouble in my camera video stream.
solved. thank you!

**Comment by winlinvip** [comment]
dup to #1329
