### ISSUE TITLE
accept上来的fd忘了设置FD_CLOEXEC

### ISSUE THREAD

**Issue by YueHonghui** [ossrs/srs#518]
accept上来的fd忘了设置FD_CLOEXEC, 会导致FORK FFMPEG时, fd泄露.

**Comment by winlinvip** [comment]
Can I submit a patch? `git format-patch origin/develop` will do, I haven't looked at this ioctl for a long time.

`TRANS_BY_GPT3`

**Comment by YueHonghui** [comment]
Submitting a patch won't... Does submitting a PR work?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
PR is better than patch, haha.
:smile: 

`TRANS_BY_GPT3`
