### ISSUE TITLE
Add support for input stream mapping

### ISSUE THREAD

**Issue by synologic** [ossrs/srs#519]
Hi,
it would be very useful to have input stream mapping for the ffmpeg ingest, in order to be able to ingest from MPTS or to ingest from SPTS multicast streams that contain more than one audio track, which is not supported in FLV.

**Comment by synologic** [comment]
Along with that, would be also nice to have filtering options such as -ignore_unknown -sn -dn etc

**Comment by winlinvip** [comment]
I will fix in SRS3.

**Comment by winlinvip** [comment]
I will support one string ingester, #447
