### ISSUE TITLE
Http callback on_play support RTMP/HLS/HTTP-FLV

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#52]
https://github.com/winlinvip/simple-rtmp-server/issues/52

**Comment by reduxionist** [comment]
:+1: very much need this feature, don't need CDN support for it though

**Comment by winlinvip** [comment]
It's impossible for u to hook each request of player, when play stream from cdn.

**Comment by reduxionist** [comment]
Thank you for your reply! We don't want to hook on_play from CDN. We only want to use the on_play hook when serving HLS directly ourselves; no CDN involved.


Thanks for sharing your excellent code! :)


> On 17 Jun 2015, at 10:15, winlin notifications@github.com wrote:'
Make sure to maintain the markdown structure.
> 
> It's impossible for u to hook each request of player, when play stream from cdn.
> 
> —
Make sure to maintain the markdown structure.
> Reply to this email directly or view it on GitHub.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Got it. It's ok for your use scenario. When use SRS as RTMP/HTTP/HLS server, the on_play can be hooked when user play the stream, especially the stream, for example the HTTP FLV stream.

**Comment by reduxionist** [comment]
Wow! I must have misunderstood the Google translation of this issue, as I thought that HTTP hooks such as on_play only worked with RTMP  and that they did not work with HLS.


But if I understand correctly now, with SRS you can use HTTP callbacks registered against the on_play hook even with HLS (and thus m3u8 delivered MP4s)!


This is functionality that many people want from nginx-mod-rtmp but which is not possible there.


I will update your English language docs to highlight this feature once I have got the functionality working myself and know what I'm talking about.


Congratulations on being the most advanced open-source, industrial-strength, media streaming server in the world, and thanks for the fast replies to support issues!


> On 17 Jun 2015, at 13:18, winlin notifications@github.com wrote:'
Make sure to maintain the markdown structure.
> 
> Got it. It's ok for your use scenario. When use SRS as RTMP/HTTP/HLS server, the on_play can be hooked when user play the stream, especially the stream, for example the HTTP FLV stream.
> 
> —
Make sure to maintain the markdown structure.
> Reply to this email directly or view it on GitHub.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The on_play hook is only support RTMP now. But it's possible for HLS/HTTP-FLV, which is not support yet.
When this bug is closed, the on_play hook will support RTMP/HLS/HTTP-FLV.

**Comment by winlinvip** [comment]
Sorry, I will fix this issue on SRS3.

**Comment by superxrb** [comment]
How about on_stop for HTTP-FLV and HLS?

**Comment by winlinvip** [comment]
For HLS, you should handle it on NGINX.
For FLV, the http callback is planed in SRS3.

**Comment by winlinvip** [comment]
RTMP and FLV are already supported, and HLS is expected to be supported in SRS4.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to #1657
