### ISSUE TITLE
关于推http-flv流疑惑　&&  详细的api文档？

### ISSUE THREAD

**Issue by Speknight** [ossrs/srs#529]
你好，根据相应的wiki和本人的实验结果：
　　在推http-flv的时候，如果用户需要观看http-flv流，需要配置stream-caster和http-remux,才能观看http-flv流，想问下，这其中的过程是不是http-flv流　＝>    rtmp流　=>   http->flv流的过程？
　　可不可以类似推rtmp流，直接看rtmp流的过程; 当在推http-flv流的时候，可以直接观看http-flv流？

另外有个小小的请求：
　　因为本人想在srs的基础上写一个http-flv流的相关应用，需要处理对http-flv流进行切片处理，苦于没有详细的api文档，还是有点吃力，希望作者能有所提点；

**Comment by winlinvip** [comment]
请参考wiki，其他的就只有代码了，没有额外的文档。
