### ISSUE TITLE
RTMP流转发（Forward）可否通过url来指定。

### ISSUE THREAD

**Issue by daozhao** [ossrs/srs#53]
目前流转发Forward模式需通过配置文件来完成。请可否增加url来配置forward的推送地址。

例如：
推送地址 rtmp://192.168.1.2/myapp/mystream?forward=rtmp://cdn.com/myapp/mystream?XXXXXX

这样比较方便随时改变是否需要转发流。
目前我们有一个应用场景。客户大部分的流只需要在局域网观看就可以了。不需要互联网观看。但是有时候有部分播放源需要在互联网上播放。如果通过config文件配置这个forward的话，不太灵活。

请问可否添加此功能，或者有什么方式可以达到比较相似的效果。

又或者可否指导一下，我如何可以快速修改代码可以达到这个功能。

**Comment by winlinvip** [comment]
在3.0考虑支持，SRS2已经进入bug fix阶段了。
如果很着急用，考虑用商业版，http://www.chnvideo.com

**Comment by daozhao** [comment]
Thank you, for now I can only rely on myself to provide for my clothing and food.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS3 is considering support.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Postpone to SRS4.

**Comment by winlinvip** [comment]
Dup to #1342
