### ISSUE TITLE
在Issues中的链接失效

### ISSUE THREAD

**Issue by zdco** [ossrs/srs#532]
在Issues中的链接失效了，例如，打开Issues的
https://github.com/ossrs/srs/issues/136
里面的链接
https://github.com/winlinvip/simple-rtmp-server/issues/133
报404错误，类似的情况有很多啊。

**Comment by winlinvip** [comment]
我把那个项目的issues关闭了，总是有人提交issue到我个人的项目。

**Comment by zdco** [comment]
请问，能否将你个人项目里的问题回答移过来呢？
很多问题的答案都找不到了.....

**Comment by winlinvip** [comment]
貌似这个项目已经删除了。 :smiley:

**Comment by winlinvip** [comment]
也就是说那些链接都没有用了。。。。

**Comment by haofz** [comment]
天啦咯，损失好大！
好多答案都没得找了。。

**Comment by winlinvip** [comment]
@haofz 是啊，确实失误了，手欠，哈哈。
好在代码在，一切都在；只是解决bug的过程没有了而已。
