### ISSUE TITLE
关于dvr录制成flv的播放问题

### ISSUE THREAD

**Issue by zdco** [ossrs/srs#534]
hi, winlin

直播可以使用HLS方式跨各移动端，PC端使用RTMP推流。

如果是点播情况下，我是开启了dvr录像功能，将rtmp推的流存储成flv格式，这个格式在PC端很好用，一堆的插件都支持，但在移动端的话，无法实现跨各移动端，请问有什么解决方式可以实现点播跨移动端呢？或者能配置成dvr存储为MP4，使用H5来实现跨移动端？或者能配置成dvr存储为HLS，使用H5来实现跨移动端？

**Comment by winlinvip** [comment]
You can use the `on_hls` callback to move the HLS segment.

`TRANS_BY_GPT3`

**Comment by zdco** [comment]
Thanks!

**Comment by zdco** [comment]
Hi, winlin


Using the on_hls callback to move the segments can indeed achieve the storage of recorded files for mobile use. However, during implementation, it was found that it is not convenient to move the segments while HLS live streaming is ongoing. If the TS segments are moved, the live streaming cannot be played. If only the previous 5 segments are moved, it can be achieved, but it is difficult to determine the number of segments to move. It is also difficult to specify which streams to move and which ones not to move.

Is there a more reasonable way to implement the recording function while also enabling playback on mobile devices?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Just copy the slice...

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
@winlinvip I have saved all the ts fragments, but is there a way to rebuild the index file m3u8 for HLS? Or is there a configuration option to choose to save all fragment information?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
`on_hls` will provide you with information about the segments. You can record it yourself and reconstruct the m3u8 file.

`TRANS_BY_GPT3`

**Comment by jhaoheng** [comment]
Hi @winlinvip, I would like to ask a question. I am using on_hls to put files into s3 and I need to manually create the m3u8 file. However, I am a bit confused about when you update the m3u8 file, what triggers the automatic deletion of old information and the addition of new information? I'm not sure if there is any reference information available. Thank you.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
In the configuration, the window will be set to determine the duration of the active segment. Once this duration is exceeded, the old segment should be removed from the M3U8 playlist. If you are implementing time shifting, you can configure your own window, for example, consisting of 3-5 segments.

`TRANS_BY_GPT3`
