### ISSUE TITLE
hls 播放没有声音，rtmp 播放是有声音的

### ISSUE THREAD

**Issue by ieworks** [ossrs/srs#538]
使用 ffmpeg 把一段 ts 流使用 rtmp 方式推到 srs 后播放， 测试播放 hls 没有声音。

1）推流命令：
ffmpeg -re -i e.ts -vcodec copy -acodec copy -bsf:a aac_adtstoasc -f flv -y rtmp://127.0.0.1/live/livestream

2）SRS 报的 warn 信息如下：
[2015-11-30 14:39:30.695][warn][12644][104][11] aac ignore type=1 for no sequence header. ret=0

查了一下这个信息是从 SrsAvcAacCodec::is_aac_codec_ok 函数里面打印出来的

ts 文件路径：
链接: http://pan.baidu.com/s/1qWw3q48 密码: f7d1

**Comment by winlinvip** [comment]
This is a failure in parsing the sequence header, resulting in issues with HLS.

`TRANS_BY_GPT3`

**Comment by ieworks** [comment]
如果推 mp4 的试就不会出现这个问题，是 ffmpeg 从 ts 到 flv 的转封装的过程中没有处理好 AudioSpecificConfig 信息。网上有一个参考链接说明的 如下：https://kexiao8.com/blog/index.php/2013/12/18/64.html

**Comment by winlinvip** [comment]
OK, it should be done by ffmpeg, and the server is compatible.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If FFMPEG loses ASC information, the server cannot recover it and it must be resolved within FFMPEG.

`TRANS_BY_GPT3`
