### ISSUE TITLE
关于SRS语音对讲功能

### ISSUE THREAD

**Issue by zdco** [ossrs/srs#539]
Hi, 请问SRS支持客户端将语音发送给设备吗？

**Comment by wenjiegit** [comment]
不支持，这个属于推流，srs提供了librtmp 库

**Comment by zdco** [comment]
也就是说，需要设备使用librtmp从服务端取到客户端发布的音频流，然后输出到音频硬件输出端口上

**Comment by winlinvip** [comment]
SRS是服务器，负责分发。
