### ISSUE TITLE
forward收包的线程阻塞时间太大

### ISSUE THREAD

**Issue by yanclark** [ossrs/srs#540]
使用forward命令推流， 端口都是1935。
10.1.100.69  -->(forward)  10.1.100.71\10.1.100.72
先启动10.1.100.71 和 10.1.100.72  再启动 10.1.100.69  情况是正常的， 在三台服务器上都能看到流。。
在运行过程中。。 重启10.1.100.71 和 10.1.100.72  发现71、72没有流了。。只有69有。。
然后在69的错误日志里找到如下日志：
[2015-12-02 15:41:17.590][error][9948][117][2] connect to server error. ip=10.1.100.71, port=1935, ret=1018(No such file or directory)
[2015-12-02 15:41:17.602][error][9948][118][2] connect to server error. ip=10.1.100.72, port=1935, ret=1018(No such file or directory)

此时如果重启69，侧一切又恢复正常。
重复测试过很多次都是这个情况。

**Comment by yanclark** [comment]
I made a mistake, it was due to my own code.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
What's going on?

`TRANS_BY_GPT3`

**Comment by yanclark** [comment]
It's like this, there is a packet receiving process in the logic of SrsForwarder::forward(), which is to receive the response from the server. This logic was originally fine, but there is a problem that the streaming push is not smooth because the packet receiving process is blocking, and the blocking time is uncertain depending on the server's response. I observed that in the internal network, under normal circumstances, the blocking time is definitely greater than mw_latency 100, that is, greater than 100ms. So the process of sending packets may be as follows:
send 10 package  --> wait  50ms --> send 5 package -->wait 300ms -->send 15 package --> wait 400ms --> send 20 package ;
This is what I mentioned earlier about the streaming push not being smooth. Of course, this is not a problem for general players because they will wait until enough packets are received before playing. So when using the VLC player, although there may be some delay, the playback is smooth. However, the player developed by our Flash team does not handle this. It works like this: if the cached data is less than 1 second, it basically starts playing as soon as data arrives. This inconsistency mentioned above can cause problems. But obviously, this small amount of data can only be played once, and then due to the inconsistent streaming push, there will be a short pause, making the overall video playback appear choppy and not very smooth.

So, to address this issue, I came up with a solution to create a separate thread to read the server's response, while the streaming thread is only responsible for smooth streaming. Initially, this worked well and solved my problem, making the video playback smooth. But later, I discovered the issue mentioned above.

Then, I did some research and found that there was a problem with the implementation. Specifically, I didn't close the thread dedicated to receiving the server's response in the on_unpublish function. Now, this has been fixed, and the desired behavior described above has been achieved.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Um, is the wait time of 50ms/300ms/400ms you mentioned because of the time waited during packet reception? Why does it keep increasing?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
However, your approach is correct. The thread for receiving should be separate, while the main thread is responsible for sending. But using a timeout for one thread would be simpler :smile: 

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I changed this to forward receiving packets, but the blocking is too significant. This is also a problem. Let's see when it can be resolved.

`TRANS_BY_GPT3`

**Comment by yanclark** [comment]
That time I was just giving an example. I have also tried the method of exceeding the time limit, but I didn't feel it was very effective.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
That time will not increase, excluding the time for code execution, st's timeout is very accurate, I have tested this accurately.

`TRANS_BY_GPT3`
