### ISSUE TITLE
2.0.200版本， 运行九天后，服务挂掉。

### ISSUE THREAD

**Issue by yanclark** [ossrs/srs#541]
![image](https://cloud.githubusercontent.com/assets/16114049/11558055/4bd2997c-99eb-11e5-8130-ec06c28622c5.png)

**Comment by winlinvip** [comment]
这个是assert错误，比较好改，可能你的流有点特殊。
麻烦把srs和对应的core文件上传到网盘，我看看内存。

**Comment by yanclark** [comment]
可能是内存问题，反正后面来的请求所有的handshake都失败了。
你网盘地址是多少，  core文件有1.7G， 比较大的。

**Comment by winlinvip** [comment]
我一般都是直接去看别人网盘，自己没有；你放百度网盘，密码可以发我邮箱的。

**Comment by winlinvip** [comment]
这个得分析下上下文，你是否能把core和对应的srs放网盘上？我需要看崩溃时几个变量的值是多少。

**Comment by winlinvip** [comment]
有一种可能是chunk size被设置为了负数，导致崩溃。我已经修正了这个问题；具体是什么情况还需要你的core。
