### ISSUE TITLE
SrsJsonAny* loads(char* str) function modifes str content

### ISSUE THREAD

**Issue by AlexisSellier** [ossrs/srs#542]
Hi,

I've found that the **loads** function from SrsJsonAny modify the paramter **str**

For example, when I am calling  do_post(url, data, status_code, res)) in an http_hook,
the res variable contains **{"code** instead of **{"code" : 0}**
It seems that the problem come from the unescape_string  where you set the `'\0'`
```
 while ((c=*p++)) {
    if (c=='"') {
      *d='\0';
```

I am a little bit afraid of sending a patch since it is deep in the code.
Btw what was the reason a rewriting a Json parser instead of using an existing one ?

**Comment by winlinvip** [comment]
1. There is no json parser in stl.
1. The json parser is not provided by srs, but use exists json parser.

**Comment by winlinvip** [comment]
SRS use nxjson: https://bitbucket.org/yarosla/nxjson
```


// whether use nxjson
// @see: https://bitbucket.org/yarosla/nxjson
#undef SRS_JSON_USE_NXJSON
#define SRS_JSON_USE_NXJSON
```
