### ISSUE TITLE
SRS Paused

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#543]
SRS 2.0 is postponed to release, please wait~

**Comment by winlinvip** [comment]
I have mentioned before that after turning 30, I need to focus on making money and don't have time to spend on open-source projects. I will contribute to open-source when I have money. Thank you for your attention to SRS~

`TRANS_BY_GPT3`

**Comment by FlowerWrong** [comment]
@winlinvip Thank you + Keep it up + Best wishes

`TRANS_BY_GPT3`

**Comment by ziyan** [comment]
Thank you, great god 🙏
On Tue, Dec 8, 2015 at 12:56, 浮生 notifications@github.com wrote:

> @winlinvip https://github.com/winlinvip Thank you + Keep it up + Best wishes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ossrs/srs/issues/543#issuecomment-162751796.

`TRANS_BY_GPT3`

**Comment by phantomgz** [comment]
It's a great project, support.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS resumed, with new roadmap, SRS2 plan to release at 2016.12, to do more test.

**Comment by winlinvip** [comment]
Recently considering donating SRS to the open-source foundation, it can have a more stable development for about thirty more years.

`TRANS_BY_GPT3`
