### ISSUE TITLE
Flash Media Live Encoder 3.2 upload multi-rate to SRS 2.0 (2.0.195) problem.

### ISSUE THREAD

**Issue by steve1108** [ossrs/srs#545]
I am using FMLE 3.2 upload multi-rate 3 streams to SRS server, but middle stream always can't working, 1th and 3th will normal, i don't know what's happened some, and please look at this issue, thanks a lot.
This is SRS logs:
Wed Dec 16 2015 11:58:39 : Primary - Connected to FMS/3,5,3,888
Wed Dec 16 2015 11:58:41 : Resample Required.
Wed Dec 16 2015 11:58:41 : Primary - Stream[test23451] Status: Success
Wed Dec 16 2015 11:58:42 : Primary - Stream[test23451] Status: NetStream.Publish.Start
Wed Dec 16 2015 11:58:42 : Primary - Stream[test23451] Status: NetStream.Unpublish.Success
Wed Dec 16 2015 11:59:07 : Primary - Stream[test23453] Status: Success
Wed Dec 16 2015 11:59:07 : Primary - Stream[test23453] Status: NetStream.Publish.Start
Wed Dec 16 2015 11:59:07 : Problem publishing at Primary Server. Unable to publish test23452 stream either due to Network Problem at server, the stream name being used is busy, or you are not authorized to publish to this server. Please check the network connection with server, try publishing with other stream name, or contact your FMS administrator for help.
Wed Dec 16 2015 11:59:07 : Session Started
Wed Dec 16 2015 11:59:07 : Audio Encoding Started 
Wed Dec 16 2015 11:59:07 : Video Encoding Started

**Comment by wenjiegit** [comment]
Hi, Steve, SRS only supports one stream over one connection.

`TRANS_BY_GPT3`

**Comment by steve1108** [comment]
If possible the SRS 2.0 release version have been possible net-connection multi net-streams, it will better.

**Comment by wenjiegit** [comment]
this is more complex than one stream over one connection, so srs2.0 will not support it.

**Comment by winlinvip** [comment]
Won't support.
