### ISSUE TITLE
No http api token authentication support for http-api

### ISSUE THREAD

**Issue by FlowerWrong** [ossrs/srs#548]
There is no token authentication support for http-api module.
I have found the `srs/trunk/src/app/srs_app_http_api.cpp`, but no code for this.

**Comment by winlinvip** [comment]
Not support yet.

**Comment by FlowerWrong** [comment]
I also found that there is only [security](https://github.com/ossrs/srs/wiki/v2_EN_Security) config for user who can push rtmp flow to srs server, but the ip of push flow client may change often. Can you support it on `http-callback`. For example, you can support it with `on_publish` event. The `on_connect` event can not do that.

**Comment by winlinvip** [comment]
SRS does support `on_publish` and `on_connect` callback. The `security` is another solution, for example, some edge only allow play.

**Comment by FlowerWrong** [comment]
Hi, I found that `http callback api` has a `"tcUrl": "rtmp://x/x?key=xxx"` in `on_connect`. But there is no one in `on_publish`, I want to deny someone to publish rtmp stream to srs server without username and password or named token.

**Comment by winlinvip** [comment]
OK, Accept.

`TRANS_BY_GPT3`
