### ISSUE TITLE
首先感谢SRS!  希望http_server能支持mp4的mime！

### ISSUE THREAD

**Issue by wuxianlijiang** [ossrs/srs#551]
在跨平台播放的时代，把h264/aac录制为mp4是很好的选择，希望SRS自带的server能支持mp4格式。感谢！！

另希望案例中能够加上  丽江热线 http://www.lijiangtv.com

**Comment by wuxianlijiang** [comment]
目前我们使用nginx的模拟来实现mp4播放（指定xxx.mp4?start=xxx&end=xxx）。如SRS能独立实现，那就太帅啦！

**Comment by winlinvip** [comment]
点播不是SRS的目标哈。不过mp4这种seek，貌似已经支持了吧。
