### ISSUE TITLE
SRS 实现 vlc 点播指定文件的功能？

### ISSUE THREAD

**Issue by 69567272** [ossrs/srs#557]
如题。 

使用srs实现了直播功能、录像功能。

但是没有配置正确点播录像文件的功能。 望大神指教。

**Comment by winlinvip** [comment]
点播直接用nginx分发文件，不用脱了裤子放屁。

**Comment by 69567272** [comment]
大神能给个参考吗？ 小弟刚入门数月。 nginx不熟啊。
