### ISSUE TITLE
用户动态自定义transcode

### ISSUE THREAD

**Issue by FlowerWrong** [ossrs/srs#560]
目前transcode是写死在配置文件里面的，但对于客户端来说，并不一定会指定码率push rtmp流。多数时候会根据网络状况而定。有什么办法可以给用户自定义transcode呢？

我想到了一种是利用`http hooks`，添加一个回调`on_transcode`， 把视频的metadata（最重要的就是编码，码率，长宽等数据）信息传递给自定义服务器。由此来实现自定义。

例如用户上传的是720P 2500kbps的视频，那么可以自定义服务器利用`on_transcode`回调自己设定将其转为480p(500kbps), 250p(300bps)等等。如果是1080P 4500kbps的视频，那么服务器就可以转为720p, 480p and 240p等等。

**Comment by winlinvip** [comment]
There are three scenarios for transcoding:

1. Simple transcoding: Configure the transcode settings and use ffmpeg for transcoding. This is applicable for one or two streams.
2. Use `on_publish` and `on_unpublish` callbacks to transcode when publishing a stream and stop transcoding when unpublishing. You can retrieve the desired parameters by querying the server's API after receiving the `on_publish` event or by parsing the stream's data, without needing to pass this data through `on_publish`.
3. Integrate with a dedicated transcoding cluster, which is more complex than solution 2.

`TRANS_BY_GPT3`

**Comment by FlowerWrong** [comment]
@winlinvip, you misunderstood my meaning. What I meant is that the parameter configuration of `transcode` (such as engines and all other parameters) should be returned by the callback function each time, rather than being configured by the config. The result returned by the callback function is as follows:


``` json
transcode {
        enabled     on;
        # ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        ffmpeg      /home/yy/bin/ffmpeg;
        engine 240P {
            enabled         on;
            vfilter {
                max_interleave_delta 0;
            }
            vcodec          libx264;
            vbitrate        700;
            vfps            30;
            vwidth          426;
            vheight         240;
            vthreads        12;
            vprofile        main;
            vpreset         medium;
            vparams {
            }
            acodec          libfdk_aac;
            abitrate        70;
            asample_rate    44100;
            achannels       2;
            aparams {
            }
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }


        engine 360P {
            enabled         on;
            vfilter {
                max_interleave_delta 0;
            }
            vcodec          libx264;
            vbitrate        750;
            vfps            30;
            vwidth          640;
            vheight         360;
            vthreads        12;
            vprofile        main;
            vpreset         medium;
            vparams {
            }
            acodec          libfdk_aac;
            abitrate        70;
            asample_rate    44100;
            achannels       2;
            aparams {
            }
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }
}
```


Then the SRS server transcodes based on the returned result.

Regarding the solution you mentioned in 2, I think it is also feasible, but it should be built on the basis of [forward](https://github.com/ossrs/srs/wiki/v1_CN_SampleForward).

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
For solution 2, there is no need to forward. After the callback to the external system, the stream can be pulled from the server, transcoded, and then sent back to the server.

`TRANS_BY_GPT3`

**Comment by FlowerWrong** [comment]
@winlinvip Thank you.

`TRANS_BY_GPT3`

**Comment by FlowerWrong** [comment]
Hi, I want to make a pr with more streams info of http stream api.
Now, the stream api `http://192.168.10.160:1985/api/v1/streams/9112` return this:
```json
{
    "code": 0,
    "server": 9110,
    "stream": {
        "id": 9112,
        "name": "demo",
        "vhost": 9111,
        "app": "live",
        "live_ms": 1452493910452,
        "clients": 1,
        "send_bytes": 110824,
        "recv_bytes": 1539671,
        "kbps": {
            "recv_30s": 0,
            "send_30s": 0
        },
        "publish": {
            "active": true,
            "cid": 110
        },
        "video": {
            "codec": "H264",
            "profile": "Baseline",
            "level": "3"
        },
        "audio": {
            "codec": "AAC",
            "sample_rate": 22050,
            "channel": 2,
            "profile": "LC"
        }
    }
}
```

But there is no width, height, video and audio bitrate etc info which I can say.
After read the source code, I may add it to `class SrsStatisticStream` in [line](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_statistic.hpp#L62)

Is it a suitable way?

**Comment by winlinvip** [comment]
Please file a new issue, this #560 is not for this api.

**Comment by wjtNo2** [comment]
Is this method more resource-intensive in terms of server configuration and memory usage?

`TRANS_BY_GPT3`

**Comment by zsinba** [comment]
This way [https://longrm.com/2019/10/29/2019-10-29-srs_ffmpeg_transcode_as_needed/](https://longrm.com/2019/10/29/2019-10-29-srs_ffmpeg_transcode_as_needed/)

`TRANS_BY_GPT3`
