### ISSUE TITLE
add more stream info to http stream api

### ISSUE THREAD

**Issue by FlowerWrong** [ossrs/srs#561]
Hi, I want to make a pr with more streams info of http stream api.
Now, the stream api `http://192.168.10.160:1985/api/v1/streams/9112` return this:

``` json
{
    "code": 0,
    "server": 9110,
    "stream": {
        "id": 9112,
        "name": "demo",
        "vhost": 9111,
        "app": "live",
        "live_ms": 1452493910452,
        "clients": 1,
        "send_bytes": 110824,
        "recv_bytes": 1539671,
        "kbps": {
            "recv_30s": 0,
            "send_30s": 0
        },
        "publish": {
            "active": true,
            "cid": 110
        },
        "video": {
            "codec": "H264",
            "profile": "Baseline",
            "level": "3"
        },
        "audio": {
            "codec": "AAC",
            "sample_rate": 22050,
            "channel": 2,
            "profile": "LC"
        }
    }
}
```

But there is no width, height, video and audio bitrate etc info which I can say.
After read the source code, I may add it to `struct SrsStatisticStream` in [line](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_statistic.hpp#L62) according to the [SrsStatisticStream::dumps method](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_statistic.cpp#L121).

Is it a suitable way?

**Comment by winlinvip** [comment]
Please file a PR.

**Comment by winlinvip** [comment]
Sometimes, we cannot got the width and height, please ignore this error.

**Comment by FlowerWrong** [comment]
There is another problem, in the `on_publish` hook, I can not visit the http stream api at all. Because the `on_publish` hook not back `0` to srs server. So I have to sleep some seconds in a background job.
You can see [scale_transcode_job](https://github.com/FlowerWrong/srs_callback/blob/master/app/jobs/scale_transcode_job.rb#L8). So, should we add a `on_publish_success` hook?

**Comment by winlinvip** [comment]
Why should you access the stream api when process the on_publish API?

**Comment by FlowerWrong** [comment]
@winlinvip see this https://github.com/ossrs/srs/issues/560#issuecomment-170320519

**Comment by FlowerWrong** [comment]
It is a small problem. But with `on_publish_success` will better.

**Comment by winlinvip** [comment]
Why do you need to simultaneously retrieve stream information when publishing a stream? Your backend system can query after a successful on_publish event. This should inherently be asynchronous, where if the asynchronous task finds that the stream does not require transcoding, it won't send a request to the transcoding system. If the stream requires transcoding, then it can send a request to the transcoding system.

`TRANS_BY_GPT3`

**Comment by FlowerWrong** [comment]
@winlinvip It would be better to have this, as it would facilitate user operations. Indeed, both can achieve the goal.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Less is more when it comes to APIs.

`TRANS_BY_GPT3`
