### ISSUE TITLE
Why the audio_data_rate and video_data_rate is always not set in SrsAvcAacCodec class

### ISSUE THREAD

**Issue by FlowerWrong** [ossrs/srs#562]
Hi @winlinvip , I found a bug. The `audio_data_rate` and `video_data_rate` is always 0 in [srs_app_source.cpp](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_source.cpp#L1829) and [srs_app_source.cpp](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_source.cpp#L1611)

The result log:
```
44B video sh,  codec(7, profile=Baseline, level=3, 640x768, 0kbps, 0fps, 0s)
7B audio sh, codec(10, profile=LC, 1channels, 0kbps, 22050HZ), flv(16bits, 2channels, 22050HZ)
```
It is always  0kbps. And after I search all source code with `video_data_rate` or `audio_data_rate`, I am not found where to set it.

Why not set it?

**Comment by winlinvip** [comment]
It should be parsed from sps/pps. But the actual kbps can be calc by server. That is, the kbps in sps/pps is encoding settings, not the real data.

**Comment by FlowerWrong** [comment]
So you use [class Kbps](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_statistic.cpp#L76) to calc it? The http api is [SrsKbps::get_send_kbps_30s()](https://github.com/ossrs/srs/blob/2.0release/trunk/src/protocol/srs_protocol_kbps.cpp#L173).
But it will delay at least 30s.

**Comment by winlinvip** [comment]
Yep, it's ok.

**Comment by FlowerWrong** [comment]
How about use the stream info of [SrsSource::on_meta_data(SrsCommonMessage* msg, SrsOnMetaDataPacket* metadata)](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_source.cpp#L1411)

**Comment by winlinvip** [comment]
The priority of data accuracy is as follows:
1. Metadata: This is the least accurate.
2. SPS and PPS: Set by the encoder, better than metadata.
3. Calculate: The most accurate calculated by the server.

`TRANS_BY_GPT3`
