### ISSUE TITLE
Can't use seek function from as3 API

### ISSUE THREAD

**Issue by yellowfish1220** [ossrs/srs#568]
Hi, I find that if the server is WOWZA or FMS, I can use the seek function. But when using SRS, if I call NetStream.seek(), nothing happens. It seems like the seek function cannot work at all. I want to know if the seek function is not supported or if my SRS configuration is wrong.

Thanks for your apply.

**Comment by winlinvip** [comment]
SRS is live streaming cluster, not support "seek" for all live streaming.

**Comment by yellowfish1220** [comment]
Sorry, I still can't understand. Can you describe the difference in more details or give me some websites for more information?
