### ISSUE TITLE
Bad news!!! 

### ISSUE THREAD

**Issue by DyncEric** [ossrs/srs#576]
This project is closed, it's not good news for all developers!
So bad, so bad!

**Comment by gouravd** [comment]
Why is it closed? Will there be a paid version soon?

**Comment by DyncEric** [comment]
Maybe, i don't know. There has no official statement.

**Comment by wenjiegit** [comment]
the new address of srs is https://github.com/wenjiegit/srs, which is cloned from this project.

**Comment by winlinvip** [comment]
Considering donating SRS to an open-source foundation, which can ensure its stable and sustainable development for another thirty years.

`TRANS_BY_GPT3`
