### ISSUE TITLE
VLC无法播放FMLE推的aac纯音频流

### ISSUE THREAD

**Issue by loxeyer** [ossrs/srs#577]
srs版本用的是release2.0，下面是vlc报错信息：

httplive debug: playing segment 863 from stream 0
httplive debug: downloaded segment 863 from stream 0
**ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 0**
core debug: creating access 'http' location='live.yikelive.com/live/livestream-864.ts', path='(null)'
**ts error: libdvbpsi error (PSI decoder): TS duplicate (received 0, expected 1) for PID 4097**
core debug: looking for access module matching "http": 19 candidates
http debug: querying proxy for http://live.yikelive.com/live/livestream-864.ts
http debug: no proxy
http debug: http: server='live.yikelive.com' port=80 file='/live/livestream-864.ts'
core debug: net: connecting to live.yikelive.com port 80
httplive warning: playback in danger of stalling
core debug: connection succeeded (socket = 26)
http debug: protocol 'HTTP' answer code 206
http debug: Server: nginx
http debug: Content-Type: video/mp2t
http debug: this frame size=164500
http debug: Connection: close
http debug: stream size=164500,pos=0,remaining=164500
core debug: using access module "http"
core debug: Using stream method for AStream*
core debug: starting pre-buffering
core debug: received first data after 0 ms
core debug: pre-buffering done 1024 bytes in 0s - 45454 KiB/s

**上面是报错信息，下面是m3u8内容：**

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:1058
#EXT-X-TARGETDURATION:11
#EXTINF:10.007, no desc
livestream-1058.ts
#EXTINF:10.009, no desc
livestream-1059.ts
#EXTINF:10.008, no desc
livestream-1060.ts
#EXTINF:10.008, no desc
livestream-1061.ts

音频地址能用safari打开播放，FMLE是在mac下推送的，支持AAC。
另外RTMP流能用VLC播放

**Comment by winlinvip** [comment]
需要配置成纯音频，参考wiki
