### ISSUE TITLE
增加receiveVideo命令的处理

### ISSUE THREAD

**Issue by Hello2015** [ossrs/srs#578]
您好，服务器端能否增加对as3客户端NetStream发送的receiveVideo命令的处理，这样播放端可以控制是否接收视频流，达到类似YY的音视频的无缝切换？

**Comment by winlinvip** [comment]
@wenjiegit

**Comment by wenjiegit** [comment]
I will not be able to do this for now. I may be able to do it in the second half of the year.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
No longer support RTMP new features.

`TRANS_BY_GPT3`
