### ISSUE TITLE
级别日志INFO---服务器崩溃

### ISSUE THREAD

**Issue by wzw200** [ossrs/srs#579]
srs_app_thread.cpp  void SrsThread::thread_cycle()

        while (loop) {
            if ((ret = handler->on_before_cycle()) != ERROR_SUCCESS) {
                srs_warn("thread %s on before cycle failed, ignored and retry, ret=%d", _name, ret);
                goto failed;
            }
          **  srs_info("thread %s on before cycle success");**

多了一个%s把服务器搞崩溃
vfprintf.c 1161
program terminated with signal SIGSEGV , Segmentation fault.

**Comment by winlinvip** [comment]
@wenjiegit This bug doesn't need to be fixed in SRS2 because the online version definitely won't have info enabled. It's up to you.

`TRANS_BY_GPT3`

**Comment by intliang** [comment]
Fixed, https://github.com/intliang/srs

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@intliang  merged, thanks~

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/commit/3fbe9d2442df696e6cb55ad24b1c454a24ce4ae1
