### ISSUE TITLE
MAC OS | ulimit -HSn 1008 | 我已经调整了 但是还是不行

### ISSUE THREAD

**Issue by enjory520** [ossrs/srs#581]
nvalid max_connections=1000, required=1008, system limit to 256, total=1007(max_connections=1000, nb_consumed_fds=7), ret=1023. you can change max_connections from 1000 to 248, or you can login as root and set the limit: ulimit -HSn 1008

**Comment by winlinvip** [comment]
You need to set the size of OSX larger.

`TRANS_BY_GPT3`

**Comment by ghost** [comment]
Okay.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS should calculate more accurately.
@wenjiegit 

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Currently it is `nb_total + 1`, you can add a little more `nb_total + 100`, so that users can set a surplus amount, it is estimated that some other fds have been consumed, but not calculated.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Setting it a bit larger can solve the problem.

`TRANS_BY_GPT3`
