### ISSUE TITLE
srs  http json解析时unescape_string修改源字符串问题

### ISSUE THREAD

**Issue by willkk** [ossrs/srs#582]
在调用http hooks模块时，由于每次发送http请求后等待response，然后json在调用
### SrsJsonAny\* info = SrsJsonAny::loads((char*)res.c_str());

解析res字符串过程中，递归调用到
### unescape_string

函数会修改res源字符串，将右侧双引号设置成０。

这样导致的问题是，我在后续的处理中无法再使用http response字符串res。

另外，下面这个body_read_all函数中，因为是对body.append，是不是函数进来的时候，body.clear一次比较安全。不过这个好像牵涉到谁用谁负责的问题，从程序编写规范来说也没太大问题。

int SrsHttpMessage::body_read_all(string& body)
{
    int ret = ERROR_SUCCESS;

```
// cache to read.
char* buf = new char[SRS_HTTP_READ_CACHE_BYTES];
SrsAutoFreeA(char, buf);

// whatever, read util EOF.
while (!_body->eof()) {
    int nb_read = 0;
    if ((ret = _body->read(buf, SRS_HTTP_READ_CACHE_BYTES, &nb_read)) != ERROR_SUCCESS) {
        return ret;
    }

    if (nb_read > 0) {
        body.append(buf, nb_read);
    }
}

return ret;
```

}

**Comment by winlinvip** [comment]
This library is comparing 2, so the content of the parameter should not be modified...
However, since its parameter is char*, there shouldn't be any problem. SRS should copy the content before each call.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
A bug only mentions one issue, I simply ignored the one that follows.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS3
