### ISSUE TITLE
如何关闭 --with-nginx 模式下的 Demo 功能？

### ISSUE THREAD

**Issue by Feiox** [ossrs/srs#589]
版本 2.0.209

我尝试从文档中寻找，未果。
我又试着讲附带的 HTML 等文件删除，发现竟然还可以访问
那么，如果我要用于对外环境，怎么关闭 Demo 功能呢？
非常感谢 ~

另外，

1. 启动 Nginx 只需要一个命令 `./objs/nginx/sbin/nginx` 似乎未指定配置文件，如果我想要使用自己的配置文件，应该怎样做呢
2. 自带的 Nginx 版本似乎是 1.5.7 那么，我可以使用自己编译的其他版本吗？
3. 在使用 `--with-http-callback` 参数编译时依然报错，我看到有一个 issue 提到了这个问题，您说在 SRS 2.0 中已解决这个 bug，但，我这边依旧不成功。#504

**Comment by winlinvip** [comment]
nginx是可选的，不一定非得带着。
