### ISSUE TITLE
视频快照功能

### ISSUE THREAD

**Issue by wavestudio** [ossrs/srs#592]
请问srs支持将rtmp流中的视频按关键帧或者隔一段时间生成图片并保存成图片文件吗？

**Comment by winlinvip** [comment]
At present, the server does not directly support it, but there is support for external commands to execute exe files or http hooks.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS3 supports Snapshot, referring to exec.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
read [v3_CN_Snapshot](https://github.com/ossrs/srs/wiki/v3_CN_Snapshot) and [v3_EN_Snapshot](https://github.com/ossrs/srs/wiki/v3_EN_Snapshot)
