### ISSUE TITLE
APPLICATION: connect_app2()时，由于tcUrl内容差异，forward给CDN节点时连接返回失败，可能是安全验证问题

### ISSUE THREAD

**Issue by haofz** [ossrs/srs#595]
SRS2.0，SrsRtmpClient::connect_app2()中，有一段代码如下：

```
    if (req && req->tcUrl != "") {
        pkt->command_object->set("tcUrl", SrsAmf0Any::str(req->tcUrl.c_str()));
    } else {
        pkt->command_object->set("tcUrl", SrsAmf0Any::str(tc_url.c_str()));
    }
```

比如我源流为“”rtmp://192.168.1.10/live/livestream“”，把流forward给CDN节点如“rtmp://cnrtmp.com/live”,此时data中的tcUrl内容为“rtmp://192.168.1.10/live/livestream”，CDN节点均拒绝该连接。

1、我不太清楚，但应该是大部分CDN节点对tcUrl有验证，网宿和蓝汛皆是如此，此处修改tcUrl代码就行。
2、二是请问winlin哥，此处修改的初衷是什么能否说明一下？（1.0的tcUrl并不经过判断赋值）

**Comment by winlinvip** [comment]
If the original req contains a tcUrl, use the original one. CDN uses domain names, so you need to modify the forward. Alternatively, use edge+vhost to match the CDN.

`TRANS_BY_GPT3`

**Comment by chundonglinlin** [comment]
I have also encountered this problem and feel that changing this parameter by Winlin does not make much sense.

`TRANS_BY_GPT3`

**Comment by hping16** [comment]
What does this tcUrl specifically mean? Should it include the stream name or not?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@hping16 Please refer to the relevant wiki.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
4.0 should be fine. If there are any issues, please provide feedback again.

`TRANS_BY_GPT3`
