### ISSUE TITLE
How to play HTTP FLV on iOS and Android

### ISSUE THREAD

**Issue by winking324** [ossrs/srs#596]
I have setup a cluster by [v2_EN_SampleHttpFlvCluster](https://github.com/ossrs/srs/wiki/v2_EN_SampleHttpFlvCluster).

But I cannot watch the HTTP FLV stream on iOS and Android.

I also try to modify the JWPlayer's config on my local Nginx, such as in my index.html:

``` js
player = jwplayer("container").setup({
            type: "mp4",
            primary: "html5",
            width: 640,
            height: 480,
            image: "bg.jpg",
            autostart: false,
            file: "http://192.168.1.12:8080/live/livestream.flv",
        });
```

but the browser try to download the flv file, then play it.

So can HTTP FLV run on iOS or Android?

**Comment by misiek08** [comment]
Android and iOS won't play .flv because it requires Flash. You need HLS for
them.

**Comment by winlinvip** [comment]
Android use exoplayer. iOS seems should write a player by yourself

**Comment by liutao6982** [comment]
you need do some work by yourself

**Comment by winlinvip** [comment]
Please read wiki:

* https://github.com/ossrs/srs/wiki/v4_CN_ClientSDK
* https://github.com/ossrs/srs/wiki/v4_EN_ClientSDK
