### ISSUE TITLE
国外编码器推流超时

### ISSUE THREAD

**Issue by zhengfl** [ossrs/srs#598]

**Comment by zhengfl** [comment]
After a certain period of time, the encoder from abroad did not disconnect the connection, nor did it send any command packets, but it stopped sending any audio or video data.

`TRANS_BY_GPT3`

**Comment by zhengfl** [comment]
The encoder did not report any errors, and the network is also functioning properly. There is no such issue when pushing to other servers (nginx, fms).

`TRANS_BY_GPT3`

**Comment by zhengfl** [comment]
By comparing the packet capture with nginx, it was found that the WindowAcknowledgementSize is different when receiving around 4GB of data. In the protocol, WindowAcknowledgementSize is only 4 bytes, and the maximum it can represent is also 4GB. SRS did not handle the overflow.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Is it only 31 bits? I didn't understand the root of the problem you mentioned. Are you saying that nginx is 32 bits, which means 4GB?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
ack size is 31 bits.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This problem could be an ack overflow or it may require setting a default in ack size. The overflow issue has been resolved in SRS2. The support for setting in ack size has been added in SRS3.

`TRANS_BY_GPT3`
