### ISSUE TITLE
ingester 拉流无法释放

### ISSUE THREAD

**Issue by wanghuan578** [ossrs/srs#599]
ingester 拉流无法释放，在SrsEdgeIngester::cycle()调用stop（）方法无效。

**Comment by wanghuan578** [comment]
无法释放还是个漏洞，容易被利用攻击。

**Comment by winlinvip** [comment]
ffmpeg的问题，不建议使用ffmpeg拉流，自己实现。

**Comment by wanghuan578** [comment]
您好，我的意思是ingester中的“线程”假设拉了一个不存在的频道，它会不停滴轮训回源列表，如果存在大量的无效频道的回源，势必会产生大量的“僵尸线程”，占用ingester资源，导致服务质量下降。所以，想请请教下，回源线程是否有退出机制，比如轮训了回源ip列表三遍后，仍无法回源，就释放这路线程，停止无效频道的回源行为。谢谢。

**Comment by winlinvip** [comment]
我的意思是你要自己实现ingester。
