### ISSUE TITLE
PROTOCOL: 关于rtsp的几个问题

### ISSUE THREAD

**Issue by aesirteam** [ossrs/srs#601]
1. 对应ffmpeg命令, 定义了rtsp_transport    tcp无效果，在log中也没看到ffmpeg 的-re参数， -vpreset参数貌似也没有；
2. 对于rtsp的拉流，是否只有通过ffmpeg来实现到rtmp的过程？

**Comment by winlinvip** [comment]
ffmpeg有坑不建议用。自己实现。

**Comment by aesirteam** [comment]
Are you referring to writing the RTSP Pull part in SRS? Is it compatible with the integration of live555?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
```
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     ./doc/source.200kbps.768x320.flv;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled         off;
            perfile {
                re;
                rtsp_transport tcp;
            }
```

SRS3 is already supported, add it to the perfile configuration.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Does not support pushing RTSP streams from the camera to SRS, only supports ingesting/FFmpeg pulling RTSP streams from the camera and then forwarding them to SRS. Refer to: https://github.com/ossrs/srs/issues/2304#issuecomment-826009290

`TRANS_BY_GPT3`
