### ISSUE TITLE
srs 随着播放时间越来越长，延迟也越来越长---求救

### ISSUE THREAD

**Issue by guoying1030** [ossrs/srs#606]
hi，环境是这样的：
orign一台服务器，一台edge服务器。主播推送到orign服务器，edge服务器从orign上拉取主播流。
用sb_rtmp_load_fast压测500个客户端到edge服务器，同时开了一个页面窗口，从edge服务器上播放流。
edge的带宽只占到了50M/s，，，edge的带宽是千兆的网卡
刚开始延迟在1.2秒左右，，，但是30分钟后达到了5秒，，，1个小时候，达到了39秒的延迟。

我想问下，这是什么问题，，，播放器用的是http://ossrs.net/srs.release/trunk/research/players/srs_player.html?server=192.168.116.139&vhost=192.168.116.139#  的播放器。。

**Comment by ghmack** [comment]
RTMP does not have a time synchronization verification mechanism, so any program, system, or network-related lag will result in increasing delays. To achieve minimal lag, optimization should be done from both the pusher and receiver ends.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
What is the bandwidth speed to the edge of the player? Also, you have to keep watching the streamer continuously, you can't switch to other pages.

`TRANS_BY_GPT3`

**Comment by guoying1030** [comment]
hi，播放器到边缘的带宽测速是百兆宽带。。主播就是我自己，，主播和播放器在同一台机器上。。。。我用手机的秒表测试出来的。求答案

**Comment by winlinvip** [comment]
Try changing the server and network, I have never heard of this issue before, I used to play for a long time without encountering it.

`TRANS_BY_GPT3`

**Comment by liutao6982** [comment]
If there is network jitter, it can indeed lead to buffering and thus cause an increase in latency. However, it is usually the client that experiences the buffering.

`TRANS_BY_GPT3`

**Comment by wanghuan578** [comment]
Enabling gof_cache will solve the issue of delayed accumulation.

`TRANS_BY_GPT3`

**Comment by LF-DevJourney** [comment]
I use ffplay with the nobuffer setting `ffplay -fflags nobuffer rtmp://192.168.1.66/myapp/live`, but there is still an issue of accumulating delay. Initially, there is less than a second of delay, but after half an hour, it increases to over 2 seconds. If I stop ffplay and execute the above command again, the accumulated delay disappears, but it reappears after a while.

`TRANS_BY_GPT3`

**Comment by watchpoints** [comment]
How to solve it?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Client problem.

`TRANS_BY_GPT3`
