### ISSUE TITLE
PROTOCOL: 识别RTMP客户端，栈溢出崩溃，产生core文件

### ISSUE THREAD

**Issue by HCLAC** [ossrs/srs#607]
赵文杰：
         杰哥，在多用户观看直播时，出现服务器崩溃问题，查看生成的core文件，好像是栈溢出了，通过阅读源码发现：SrsRtmpServer类的identify_create_stream_client函数中，在有死循环的情况下，还在递归调用自己(identify_create_stream_client)，个人感觉这个函数的原意是：在接到客户端的createstream命令后，给客户端反馈，等待客户端是拉流还是推流，如果是拉流推流就完成这个函数的使命，但如果没有判断出是什么性质的客户端，就一直递归调用自己，等待客户端的消息命令。
         个人感觉这样有漏洞，如果某个自己完成的RTMP客户端，按照RTMP协议正常处理流程没有问题，如果恶意持续发送createstream命令，会导致服务器崩溃。
         我想添加一个参数，通过计算递归次数，提供一个保护机制，来保证服务器正常运行。不知道这样的想法是否正确，希望杰哥有时间指导一下

**Comment by idxa** [comment]
Can we implement it without using recursion?

`TRANS_BY_GPT3`

**Comment by HCLAC** [comment]
Well, I looked at the code again and removed the recursion. It is now implemented with a while loop.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
I have never encountered such a malicious client.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in SRS3, set recursive depth to 3.
