### ISSUE TITLE
关于on_connect的hook时能否区分publisher和Player

### ISSUE THREAD

**Issue by aesirteam** [ossrs/srs#608]
已按wiki文档使用http hook做了on_connect验证，现在的场景是，同一个VHost下，只对publisher做验证，Player不做验证，但是如果hook在on_connect时，两者都会进入这个验证，我改成on_publish的hook来完成上述场景是可以，验证失败就kickoff，但是connect实际是接入的，想能不能在connect环节判断出是那种类型的流？如果有的话方法名是什么？ 谢谢！

**Comment by winlinvip** [comment]
In the RTMP protocol, when connecting, it is not known whether it is for publishing or playing. You must hook the publish or play action.

`TRANS_BY_GPT3`
