### ISSUE TITLE
直播有延时，如何分析延时的位置，如何获取推流客户端到srs server的延时情况，以及srs server到播放器的延时？

### ISSUE THREAD

**Issue by nustee** [ossrs/srs#610]

**Comment by wanghuan578** [comment]
问问题要问到点子上，作者也是要养家糊口的。时间宝贵，望理解。

**Comment by winlinvip** [comment]
首先，@wanghuan578说的是对的，@mustee建议你描述更清楚一些。
按照一般的做法：推流到播放的延时可测量，内部无法测量，只能按照srs的wiki先搭建一个低延迟的结果出来，然后一个一个的换成你的，哪个换掉延迟大了，就是它的问题。

**Comment by FreshLuoBoGan** [comment]
你好，你目前的延时效果如何？
