### ISSUE TITLE
请问 当将一个rtmp流转换成另一个rtmp流的时候，能同时输出hls流嘛？？

### ISSUE THREAD

**Issue by lihb** [ossrs/srs#615]
ffmpeg -re -stream_loop -1 -i rtmp://srs服务器地址/live/livestream  -codec:v h264 -codec:a aac -f flv -y rtmp://srs服务器地址/test9/rtmptest

请问当我用ffmpeg这样推流到srs服务器时，srs服务器能同时又hls流输出吗？能的话，是需要怎么配置？？

**Comment by winlinvip** [comment]
看wiki: https://github.com/ossrs/srs/wiki
