### ISSUE TITLE
srs bug:  srs切片hls发生无法播放的错误

### ISSUE THREAD

**Issue by guoying1030** [ossrs/srs#616]
在hls_windows设置为12，hls_fragement设置为2的时候，推流端使用windows adobe live encoder,关键帧距离设置为2秒的时候，此时使用iphone在有的时候，出现了iphone段卡住，然后就一直卡住。。

而同样的配置，使用nginx rtmp没有这个问题。
都是同样的机器，同样的配置

**Comment by chundonglinlin** [comment]
你可以把这个设置的长点，保证每个ts能够有个I帧

**Comment by winlinvip** [comment]
描述不清
