### ISSUE TITLE
调用http_api时streams有时返回的json结构是错误的

### ISSUE THREAD

**Issue by chundonglinlin** [ossrs/srs#618]
比如：
{
	"code": 0,
	"server": 32646,
	"streams": [{
		"id": 32667,
		"name": "456_33",
		"vhost": 32647,
		"app": "live",
		"live_ms": 1467249878478,
		"clients": 1,
		"send_bytes": 0,
		"recv_bytes": 0,
		"kbps": {
			"recv_30s": 0,
			"send_30s": 0
		},
		"publish": {
			"active": true,
			"cid": 5198
		},
		"video": {
			"codec": "H264",
			"profile": "Main",
			"level": other
		},
		"audio": {
			"codec": "AAC",
			"sample_rate": 44100,
			"channel": 2,
			"profile": "LC"
		}
	}]
}

**Comment by chundonglinlin** [comment]
发现是video里面level参数的问题

**Comment by winlinvip** [comment]
更新到最新的版本看看，代码貌似没有这个问题。
