### ISSUE TITLE
播放 http_remux 里面的 流 http callback 没有回调

### ISSUE THREAD

**Issue by pleasurelong** [ossrs/srs#623]
播放 http_remux 里面的 流 http callback 没有回调，比如播放http://127.0.0.1:1935/app/test.aac  httphooks 收不到callback

**Comment by winlinvip** [comment]
这块没有做。

**Comment by chfeizy** [comment]
https://github.com/ossrs/srs/issues/624
http callback 如何配置的呀 我这里怎么配置都没推数据到接口

**Comment by winlinvip** [comment]
Fixed.
