### ISSUE TITLE
full.conf备注有笔误

### ISSUE THREAD

**Issue by MaxLoveThree** [ossrs/srs#626]
最近刚下了srs源码开始学习
在full.conf中发现备注有误
```
# whether start as deamon      //应该是单词daemon
# @remark: donot support reload.
# default: on
daemon              on;
```

由于是新手，不知道提到这里合适不合适，也不知道是不是已经改了
我不知道去哪下最新的版本，只是在https://github.com/ossrs/srs/tree/2.0release 下载了srs的2.0release版本
```
[root@localhost trunk]# ./objs/srs -v
2.0.209
```

**Comment by winlinvip** [comment]
fixed at f87646d489e5862e5a6173181ed2463723e46372

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/commit/f87646d489e5862e5a6173181ed2463723e46372
