### ISSUE TITLE
HTTP TS Remuxer

### ISSUE THREAD

**Issue by beginho** [ossrs/srs#629]
Hello,

http TS remuxer produce http stream which is only playable in VLC, but not on STBs like enigma2 boxes... 
When i analyze http TS stream from srs, ts analyzer dont show pmt tables, sdt and other stuff which i usualy have when i make stream with ffmpeg (-f mpegts) for example.

So, config like this:

```
listen              1935;
max_connections     1000;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].ts;
        hstrs       on;
    }
}
```

makes http ts stream that is not recognized as TS in analyzers....
TS Analyzers i used:

> TSReader Lite
> one of well known in video broadcast world
> 
> http://www.coolstf.com/tsreader/
> http://www.coolstf.com/tsreader/TSReaderLite2.8.47c.exe
> 
> This is trial version, but functional enough to make simple testing . . .

and

> Astra - Stream / Analyzer
> Also very popular software for TV operators and broadcasters
> 
> https://cesbo.com/en/astra/
> http://cesbo.com/download/astra/4.4.182/free/x86/

Astra output for same stream over ffmpeg and srs:

from ffmpeg

> astra --analyze udp://232.10.26.1:5002
> Jul 17 19:29:32: INFO: Starting Astra 4.4.187
> Jul 17 19:29:32: INFO: PAT: tsid: 1
> Jul 17 19:29:32: INFO: PAT: pid: 4096 PMT pnr: 1
> Jul 17 19:29:32: INFO: PAT: crc32: 0x2AB104B2
> Jul 17 19:29:32: INFO: PMT: pnr: 1
> Jul 17 19:29:32: INFO: PMT: pid: 256 PCR
> Jul 17 19:29:32: INFO: VIDEO: pid: 256 type: 0x1B
> Jul 17 19:29:32: INFO: AUDIO: pid: 257 type: 0x0F
> Jul 17 19:29:32: INFO: AUDIO: Language: ita
> Jul 17 19:29:32: INFO: PMT: crc32: 0xFDB504E8
> Jul 17 19:29:32: INFO: SDT: tsid: 1
> Jul 17 19:29:32: INFO: SDT: sid: 1
> Jul 17 19:29:32: INFO: SDT:     Service: Del Arno
> Jul 17 19:29:32: INFO: SDT:     Provider: neo
> Jul 17 19:29:32: INFO: SDT: crc32: 0x5B51DC0D
> Jul 17 19:29:33: INFO: Bitrate: 914 Kbit/s

from srs:

> astra --analyze http://localhost:18080/live/livestream.ts
> Jul 17 19:45:38: INFO: Starting Astra 4.4.187
> Jul 17 19:45:39: INFO: Bitrate: 4354 Kbit/s
> Jul 17 19:45:40: INFO: Bitrate: 1681 Kbit/s
> Jul 17 19:45:41: INFO: Bitrate: 2001 Kbit/s

there is data streaming, but not recognized as in ffmpeg case . . .

**Comment by winlinvip** [comment]
SRS already insert the PMT and PAT in ts stream, why this tool not got it?

**Comment by winlinvip** [comment]
About PCR, read #311

**Comment by winlinvip** [comment]
Can't replay.
