### ISSUE TITLE
trunk\src\protocol\srs_rtmp_stack.cpp 笔误

### ISSUE THREAD

**Issue by MaxLoveThree** [ossrs/srs#640]
函数
string srs_client_type_string(SrsRtmpConnType type)
{
    switch (type) {
        case SrsRtmpConnPlay: return "Play";
        case SrsRtmpConnFlashPublish: return "flash-publish)";
        case SrsRtmpConnFMLEPublish: return "fmle-publish";
        default: return "Unknown";
    }
}

case SrsRtmpConnFlashPublish: return "flash-publish)"; 这里应该是多了个‘)’

**Comment by winlinvip** [comment]
Fixed, thanks~
