### ISSUE TITLE
SRS dvr录制flv文件中H264 参数ReFrames错误，视频无法解码播放

### ISSUE THREAD

**Issue by willkk** [ossrs/srs#648]
版本：SRS/2.0.209

用ffmpeg推送两个具有不同的ReFrames的文件推到同一个流名称，SRS录制的flv文件会出现h264参数混淆错误，导致录制的flv文件不能正常解码播放。

重现测试1：
1.先推送ReFrames=4的文件到SRS。
2.推送ReFrames=2的另一个文件到SRS（流名称相同）。
结果：后一个推流录制的文件会有参数错误，用ffplay播放log：

[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 202 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 138 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 556 is out of range
[h264 @ 0x7f04d8007380] illegal memory management control operation 13
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 32
[h264 @ 0x7f04d8007380] luma_log2_weight_denom 17 is out of range
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 19
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 7
[h264 @ 0x7f04d8007380] reference count 4 overflow
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 32
    Last message repeated 1 times
[h264 @ 0x7f04d8007380] reference count 4 overflow
[h264 @ 0x7f04d8007380] reference overflow 1717 > 15 or 0 > 15
[h264 @ 0x7f04d8007380] luma_log2_weight_denom 25 is out of range
    Last message repeated 1 times
[h264 @ 0x7f04d8007380] illegal memory management control operation 7
[h264 @ 0x7f04d8007380] luma_log2_weight_denom 106 is out of range
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 32
[h264 @ 0x7f04d8007380] luma_log2_weight_denom 106 is out of range
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 32
[h264 @ 0x7f04d8007380] luma_log2_weight_denom 428 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 52 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 213 is out of range
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 32
[h264 @ 0x7f04d8007380] reference count 1 overflow
    Last message repeated 1 times
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 32
[h264 @ 0x7f04d8007380] luma_log2_weight_denom 1114 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 67 is out of range
[h264 @ 0x7f04d8007380] illegal memory management control operation 32
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 41 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 170 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 202 is out of range
[h264 @ 0x7f04d8007380] chroma_log2_weight_denom 812 is out of range
[h264 @ 0x7f04d8007380] illegal reordering_of_pic_nums_idc 32

重现测试2：
1.先推送ReFrames=2的文件到SRS。
2.推送ReFrames=4的另一个文件到SRS（流名称相同）。
结果：后一个推流录制的文件会有参数错误，用ffplay播放log：
[h264 @ 0x7ff0e4007380] illegal memory management control operation 31
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 31
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 31
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 31
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 7
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 7
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 7
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 31
[h264 @ 0x7ff0e4007380] reference count 2 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal memory management control operation 31
[h264 @ 0x7ff0e4007380] illegal reordering_of_pic_nums_idc 17=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] illegal reordering_of_pic_nums_idc 6f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0  
[h264 @ 0x7ff0e4007380] reference count 1 overflowsq=    0B f=0/0   

可能原因：
SRS混淆了SPS和PPS。

**Comment by meibaogit** [comment]
Which version?

`TRANS_BY_GPT3`

**Comment by willkk** [comment]
2.0.209

**Comment by winlinvip** [comment]
What is your configuration file? What is the command for FFMPEG push?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
If you are recording a segment, which means there are two encoding headers in one flv file, the player may ignore the second encoding header, resulting in the inability to play. There are two solutions:
1. If there is a header switch, transcode it with ffmpeg, make sure to transcode instead of just repackaging (copy).
2. Use session recording, so that each push only has one file. Of course, if the encoder changes the encoding header during publishing, it will still have the same problem, but this situation is rare.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Won't fix.
