### ISSUE TITLE
KERNEL: SRS無預期crash

### ISSUE THREAD

**Issue by mulder0103** [ossrs/srs#652]
kernel: [ 8169.484739] srs[1405]: segfault at 200080004 ip 0000000200080004 sp 00007f002910d908 error 14 in libc-2.19.so[7f0028250000+1ba000]

**Comment by winlinvip** [comment]
什么版本号？什么平台？core文件是在哪里？或者core里面的bt显示什么（可以查查资料用gdb获取bt）。

**Comment by mulder0103** [comment]
不確定這是否是您要的
https://s3-ap-northeast-1.amazonaws.com/cosmetic-test-01/core

SRS Version: 2.0.210~2.0.218 (2.0.205我用打包好的zip 感覺是沒問題)
OS Version:  Ubuntu Server 14.04 LTS

**Comment by winlinvip** [comment]
请给出core的bt。
如果给core文件。需要给出你用到的binary才行。

**Comment by winlinvip** [comment]
Can replay.

**Comment by winlinvip** [comment]
Can't replay this issue.
