### ISSUE TITLE
hls 没有视频 只有声音，但是rtmp很正常

### ISSUE THREAD

**Issue by xiayongtao** [ossrs/srs#655]
![image](https://cloud.githubusercontent.com/assets/11712819/18857582/adaf4edc-8497-11e6-9a04-8b7acffee8d4.png)
是视频格式的问题吗，打开转码引擎后就好了

**Comment by xiayongtao** [comment]
http://pan.baidu.com/s/1o8LF3Pw 这是视频地址，麻烦帮忙好心人帮忙看看是哪出了问题，谢谢

**Comment by winlinvip** [comment]
srs2有问题吗？

**Comment by xiayongtao** [comment]
我用那个的是2的版本，刚刚使用develop版本代码编译，还是同样的错误

**Comment by xiayongtao** [comment]
hls 使用ffmpeg 解码播放会提示找不到sps pps
![image](https://cloud.githubusercontent.com/assets/11712819/18901294/5b841332-857c-11e6-84d9-87f3446e4066.png)

**Comment by winlinvip** [comment]
可能是文件的问题。

**Comment by xiayongtao** [comment]
这是使用ffmpeg播放这个文件错误信息，是文件编码格式的问题吗，因为这个是第三方的rtmp流推过来的，主要是想看hls 从srs这边还能救活不？
![image](https://cloud.githubusercontent.com/assets/11712819/19219465/78b354b8-8e46-11e6-8a65-99febcea1fce.png)

**Comment by winlinvip** [comment]
Dup to #635
