### ISSUE TITLE
Push RTMP Output HLS

### ISSUE THREAD

**Issue by developeralp** [ossrs/srs#656]
Hello all,

Thanks for this amazing server.

I'm publishing rtmp (from yasea) ,  to srs and its success.(I can play it with vlc or another player)
But I want to play live stream with hls..

(shortly : publish rtmp from android and watch it in another device with hls)

How can i set output to hls ? 
How can i do that ?

**Comment by developeralp** [comment]
OK ! 

I can successfully play hls stream.

But i can't hear audio , how to solve that ? :(

i tried that : https://github.com/ossrs/srs/wiki/v2_EN_SampleTranscode2HLS

i'm using 'conf/transcode2hls.audio.only.conf' configuration but i can see video but i can't hear audio..

**Comment by winlinvip** [comment]
This config is `audio only` which disable video. You can refer to other hls config.

**Comment by developeralp** [comment]
Thanks for reply,

I will try.

But , how can i change hls output delay ? (Its about 10 or 15 second)
