### ISSUE TITLE
停止的时候是会崩溃

### ISSUE THREAD

**Issue by xiayongtao** [ossrs/srs#661]
![image](https://cloud.githubusercontent.com/assets/11712819/18978840/b5e0809a-86f8-11e6-97c6-baba62ba1812.png)

版本编译信息
![image](https://cloud.githubusercontent.com/assets/11712819/18978863/ed8497fc-86f8-11e6-937e-1ba68e8d2f03.png)

**Comment by xiayongtao** [comment]
hls has stopped streaming, is there an automatic aging version on it? Why is it not working when I test it multiple times? When rtmp streaming generates an m3u8 file, and then stops streaming, the file is not being deleted consistently.

`TRANS_BY_GPT3`

**Comment by xiayongtao** [comment]
hls 清除的时候是不是因为 push 已经退出了
![image](https://cloud.githubusercontent.com/assets/11712819/18981386/6268798c-8710-11e6-9211-42a1054d6814.png)
但是检测超时时间还没到导致的，反正我现在了几个版本的代码都不能实现 hls 超时老化，麻烦作者抽空看看是否是这样导致的，谢谢

**Comment by winlinvip** [comment]
Please do not describe multiple issues in one bug. This bug refers to the crashing problem. Please create a separate bug report for HLS cleanup.

`TRANS_BY_GPT3`
