### ISSUE TITLE
推流网络不好丢包时，ts切片会停止

### ISSUE THREAD

**Issue by bluehunters** [ossrs/srs#662]
推流网络不好丢包时，rtmp不会中断，但ts切片会停止。不知道是不是个案。

**Comment by winlinvip** [comment]
重现步骤描述不清。

**Comment by bluehunters** [comment]
比如用3g网络推流，丢包后，rtmp能继续推送，但是hls切片会停止。得重启服务，才能继续切片。生成新的文件。

**Comment by bluehunters** [comment]
我大致找到原因了，我把
hls_dispose     0;
这样设置了。

估计原因如下：
网络不稳定导致丢包，流中断，清理程序会立即执行删除任务，而此时流已经恢复，有任务正在切片，从而产生冲突。
目前设置成 120；

网络不好时不会立即执行清理，恢复后继续切片，从而未出现过切片卡死。

**Comment by winlinvip** [comment]
版本是2.0？

**Comment by winlinvip** [comment]
网络不好，这个问题貌似没有好的办法，只能先这样。
