### ISSUE TITLE
hls 没正常老化

### ISSUE THREAD

**Issue by xiayongtao** [ossrs/srs#664]
hls 没流了自动老化上面的版本有吗？为什么我测试多次都无效呢。rtmp 推流产生m3u8 文件，然后停止推流量，文件一直没被删除

**Comment by ansi88** [comment]
这个建议做成一个开关，在某些场景下，还希望推流结束后，能够保存最后的一段m3u8文件。

**Comment by winlinvip** [comment]
参考配置，有间隔一定时间不推流就清理的参数配置。

**Comment by bluehunters** [comment]
hls_dispose     1; 是否保留所有历史切片。
hls_cleanup     on;  断流后清理；

**Comment by ansi88** [comment]
# whether cleanup the old ts files.
        # default: on
        hls_cleanup     on;
        # the timeout in seconds to dispose the hls,
        # dispose is to remove all hls files, m3u8 and ts files.
        # when timeout or server terminate, dispose hls.
        # @remark 0 to disable dispose.
        # default: 0
        hls_dispose     0;

**Comment by ansi88** [comment]
4楼@bluehunters 的说法 我觉着不正确。

**Comment by winlinvip** [comment]
就是这两个配置，具体用法参考说明。
