### ISSUE TITLE
FLV: 将http_remux从on设置为off，reload之后，只会disable最后一条stream

### ISSUE THREAD

**Issue by madope** [ossrs/srs#665]
将http_remux从on设置为off，reload之后，只会disable最后一条stream，前面的若干stream仍能正常播放。
SrsHttpStreamServer -> tflvs[] 的SrsLiveEntry template 为何只记录最近的一个stream而不是所有的stream呢

**Comment by winlinvip** [comment]
HTTP remux在2.0需要优化。

**Comment by winlinvip** [comment]
Postpone to SRS3.
