### ISSUE TITLE
启用http-flv后，srs经常自动退出

### ISSUE THREAD

**Issue by jiangzhibin** [ossrs/srs#666]
现在用的是SRS 2.0 的http-flv ，通过指令./objs/srs -c conf/http.flv.live.conf运行一段时候后，会莫名的退出（这种情况很频繁）。 srs.log中没有srs退出的相关日志

编译./configure --with-ssl --with-hls --with-ssl --with-nginx --with-http-server --with-http-api --with-http-callback  && make
配置文件：
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }

}

srs.log中可用看到 几分钟前还在正常推流  当推流推不上去时 发现srs已经退出  查看srs.log  并无srs退出的相关日志.
运行了ulimit -c unlimited  然后运行srs.
等srs退出后  切到根目录  执行 find / -name core.* 
发现没有srs的core文件

请问有什么办法 可以查明造成自动退出的原因？
（测试过 未启用http-flv`配置：./configure --with-ssl --with-hls --with-nginx --with-http-callback  && make`，用hls.conf的配置启动srs，srs运行很稳定，未出现过上述问题。）

**Comment by winlinvip** [comment]
Where are the versions and logs?

`TRANS_BY_GPT3`

**Comment by flhcd** [comment]
```
I also encountered this phenomenon, and version 2.0.219 also had this problem. The specific testing process is as follows:
The client sends an RTMP stream (rtmp://channellive.ds.com/live/test2) to the SRS server and stops for 30 seconds.
```


SRS destructed srssource. When the client sends another RTMP stream (rtmp://channellive.ds.com/live/test2) to the SRS server, if there is an HTTP-FLV request (http://channellive.ds.com:8080/live/test2.flv), the program throws an error, and the error is located at line 486 of the srs_app_http_stream.cpp file (using a released source pointer).
 if ((ret = source->create_consumer(NULL, consumer, true, true, !enc->has_cache())) != ERROR_SUCCESS) 
)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Let's take a look.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed in https://github.com/ossrs/srs/commit/4f09bcce9f1b10a95dd2e57aaad03038956d7a4a 2.0.220
