### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by developeralp** [ossrs/srs#669]
Hello,

How to develop publish authentication ? 

I know srs does not supports publish authentication but i think i can develop a tiny authentication , 
i.e : publisher passes some token in page_url or tc_url 
srs checks page_url or tc_url and publishes if it acceptable.

**Comment by winlinvip** [comment]
Use http callback.

**Comment by developeralp** [comment]
Thanks , i looked the https://github.com/ossrs/srs/wiki/v3_EN_HTTPCallback 

But on_publish srs http callback only sends that : 

```
#       {
#           "action": "on_publish",
#           "client_id": 1985,
#           "ip": "192.168.1.10", "vhost": "video.test.com", "app": "live",
#           "stream": "livestream"
#       }
```

How can i detect tc_url or page_url on http side ? 

tc_url and page_url only sending on_connect event.
But is not on_connect covers playing and publishing live stream ..

How can i seperate them ? 

I want to detect only on_publish event..

**Comment by developeralp** [comment]
also , Is that works with srs 2 ?
