### ISSUE TITLE
Snapshot Image ?

### ISSUE THREAD

**Issue by developeralp** [ossrs/srs#672]
Hello , 

i just read https://github.com/ossrs/srs/issues/502 , 

Also , i looked https://github.com/ossrs/srs/wiki/v3_EN_Snapshot.

But how to create snapshot automatically (i.e : 4-5 images) when a new rtmp stream published ?

**Comment by winlinvip** [comment]
Use http callback.

**Comment by developeralp** [comment]
Is this works with srs 2 ?

**Comment by winlinvip** [comment]
read [v3_CN_Snapshot](https://github.com/ossrs/srs/wiki/v3_CN_Snapshot) and [v3_EN_Snapshot](https://github.com/ossrs/srs/wiki/v3_EN_Snapshot)
