### ISSUE TITLE
srs的http-flv模式目前是不是没有办法支持安全验证

### ISSUE THREAD

**Issue by scatzr** [ossrs/srs#677]
rtmp推流和rtmp客户端访问直播流可以通过回调http callback完成鉴权。
但是如果客户端使用http-flv来访问直播流是不是目前没有办法鉴权？

**Comment by winlinvip** [comment]
You can use a http proxy as the frontend for HTTP-FLV of SRS, and the proxy provides security or https service. We must just keep the SRS simple.

**Comment by scatzr** [comment]
ok ,thank you

**Comment by winlinvip** [comment]
SRS2 and SRS3 have both supported FLV authentication, please refer to http hooks.

* SRS2: HTTP Callback: the parameter of on_play at [CN](https://github.com/ossrs/srs/wiki/v2_CN_HTTPCallback#http-callback-events) or [EN](https://github.com/ossrs/srs/wiki/v2_EN_HTTPCallback#http-callback-events).
* SRS3: HTTP Callback: the parameter of on_play at [CN](https://github.com/ossrs/srs/wiki/v3_CN_HTTPCallback#http-callback-events) or [EN](https://github.com/ossrs/srs/wiki/v3_EN_HTTPCallback#http-callback-events).

`TRANS_BY_GPT3`
