### ISSUE TITLE
在srs_kernel_ts.cpp中计算ts流的PCR有错误，

### ISSUE THREAD

**Issue by daozhao** [ossrs/srs#678]
在srs_kernel_ts.cpp中函数int SrsTsAdaptationField::encode(SrsStream* stream)计算ts流的PCR有错误，
函数计算PCR部分代码如下：
```
        int64_t pcrv = program_clock_reference_extension & 0x1ff;
        pcrv |= (const1_value0 << 9) & 0x7E00;
        pcrv |= (program_clock_reference_base << 15) & 0x1FFFFFFFF000000LL;

        pp = (char*)&pcrv;
        *p++ = pp[5];
        *p++ = pp[4];
        *p++ = pp[3];
        *p++ = pp[2];
        *p++ = pp[1];
        *p++ = pp[0];
```
  其中一个：
```
pcrv |= (program_clock_reference_base << 15) & 0x1FFFFFFFF000000LL;
```
应该改为：
```
pcrv |= (program_clock_reference_base << 15) & 0xFFFFFFFF8000LL;
```
因为PCR的组成是33(PCR_Base)+6(PCR_const)+9(PCR_Ext) 。

另外[stackoverflow](http://stackoverflow.com/questions/6199940/generate-pcr-from-pts?answertab=active#tab-top)有另外一种计算方法。不过他的方法不是那么好理解。

虽然这个PCR计算错误比较微少。

**Comment by winlinvip** [comment]
We will check it.

**Comment by winlinvip** [comment]
Fixed in https://github.com/ossrs/srs/commit/85a7cb884f0cc825c47110bc136e0d785700b1bc

**Comment by winlinvip** [comment]
About pcr, read #311
