### ISSUE TITLE
PC端使用srs.publisher.js推流，Android上使用Vitamio播放rtmp，只能看到画面但是没有声音是什么原因？

### ISSUE THREAD

**Issue by SunnyBoolean** [ossrs/srs#679]
PC端使用srs.publisher.js推流，Android上使用Vitamio播放rtmp，只能看到画面但是没有声音是什么原因呢？音频编码问题吗？

**Comment by winlinvip** [comment]
Android only support h.264+aac, which srs.publisher.js use flash as encoder, which just supports h.264+speex. You must transcode the audio stream.
