### ISSUE TITLE
STREAM: 想通过改源码让SRS支持264转码到265

### ISSUE THREAD

**Issue by victor9382** [ossrs/srs#683]
看作者的开发日志说到，支持265的hls不难，我想推流用264，然后服务器转码成265，并且切成ts文件。
我想通过改源码实现这个功能，请（求）作者指点一下思路0.0_(:зゝ∠)_

**Comment by winlinvip** [comment]
要让RTMP支持265，加一种codec就可以。具体可以问高升的悟空，在微信群里问，他们实现了。

**Comment by victor9382** [comment]
但是我应该怎样进微信群。。

**Comment by winlinvip** [comment]
加我微信：winterserver

**Comment by winlinvip** [comment]
Dup to #465
