### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Hassaram** [ossrs/srs#684]
Hi. Was anyone able to get this along with the related project https://github.com/begeekmyfriend/yasea to work?

I always get one of the following errors in the android project:
libyuv failure
Network weak
Connection to server-ip port 1935 timed out after 1935 s

Sometimes I get the error that the application has stopped working so basically an unexpected error occurred.

The server project does not get any error so far.

Thanks in advance.

**Comment by winlinvip** [comment]
Maybe you should disable your seliux and iptables, please google it.
