### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by zqfoffice** [ossrs/srs#686]
int SrsEdgeIngester::ingest()
{
    int ret = ERROR_SUCCESS;
    
    client->set_recv_timeout(SRS_EDGE_INGESTER_TIMEOUT_US);
    
    SrsPithyPrint* pprint = SrsPithyPrint::create_edge();
    SrsAutoFree(SrsPithyPrint, pprint);

    while (!pthread->interrupted()) {
        pprint->elapse();
        
        // pithy print
        if (pprint->can_print()) {
            kbps->sample();
            srs_trace("<- "SRS_CONSTS_LOG_EDGE_PLAY
                " time=%"PRId64", okbps=%d,%d,%d, ikbps=%d,%d,%d", 
                pprint->age(),
                kbps->get_send_kbps(), kbps->get_send_kbps_30s(), kbps->get_send_kbps_5m(),
                kbps->get_recv_kbps(), kbps->get_recv_kbps_30s(), kbps->get_recv_kbps_5m());
        }

        // read from client.
        SrsCommonMessage* msg = NULL;
        if ((ret = client->recv_message(&msg)) != ERROR_SUCCESS) {
            if (!srs_is_client_gracefully_close(ret)) {
                srs_error("pull origin server message failed. ret=%d", ret);
            }
            return ret;
        }
        srs_verbose("edge loop recv message. ret=%d", ret);
        
        srs_assert(msg);

/////////////////////////////////////////////////////////////////////////////////////////////
//内存泄露
        SrsAutoFree(SrsCommonMessage, msg);
        
        if ((ret = process_publish_message(msg)) != ERROR_SUCCESS) {

            return ret;
        }
////////////////////////////////////////////////////////////////////////////////////////////
    }
    
    return ret;
}

多层级联，顶层断开，边缘产生内存泄露，泄露点在以上函数。初步判断是msg产生泄露。

**Comment by winlinvip** [comment]
Why does SrsAutoFree leak? Did you check with valgrind? Or just look at the code?

`TRANS_BY_GPT3`

**Comment by zqfoffice** [comment]
I tested it with a stress testing tool. After this test, the memory consistently increases, but it will be reclaimed after stopping.

On 2016-11-12 19:02:02, winlin notifications@github.com wrote:

Why does SrsAutoFree leak? Did you check with valgrind? Or did you just look at the code?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Memory growth is not necessarily a memory leak.

`TRANS_BY_GPT3`
