### ISSUE TITLE
objs/src/app/srs_app_server.o

### ISSUE THREAD

**Issue by zhuashaoweiwu** [ossrs/srs#694]
SRS2.0编译： 
./configure   --with-ssl --rtmp-hls   --with-ingest  --pure-rtmp --with-ffmpeg --with-transcode  --with-http-callback  && make
如果加上--with-http-callback  就会出现

src/app/srs_app_server.cpp:1341: 错误：‘kafka’在此作用域中尚未声明
src/app/srs_app_server.cpp:1348: 错误：从类型‘int’到类型‘SrsConnection*’的转换无效
make[2]: *** [objs/src/app/srs_app_server.o] 错误 1
make[2]: Leaving directory `/etc/srs/srs-develop/trunk'
make[1]: *** [server] 错误 2
make[1]: Leaving directory `/etc/srs/srs-develop/trunk'
make: *** [default] 错误 2
此问题，编译不通过。
![4 2](https://cloud.githubusercontent.com/assets/23515321/20422967/825ab2fa-ada8-11e6-82b5-c21e8d12d9c8.png)

**Comment by zhuashaoweiwu** [comment]
![5](https://cloud.githubusercontent.com/assets/23515321/20423375/d4987bb8-adaa-11e6-89d1-acf61880706f.png)

**Comment by winlinvip** [comment]
SRS3强制打开HTTP.
