### ISSUE TITLE
objs/src/app/srs_app_http_conn.o

### ISSUE THREAD

**Issue by zhuashaoweiwu** [ossrs/srs#695]
使用SRS服务2.0编译centos6
./configure --with-ssl --rtmp-hls --with-nginx   --with-ingest  --pure-rtmp --with-ffmpeg --with-transcode --with-http-callback  && make

src/app/srs_app_http_conn.cpp:1354: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1358: 错误：invalid use of incomplete type ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.hpp:71: 错误：forward declaration of ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::serve_http(ISrsHttpResponseWriter*, ISrsHttpMessage*)’:
src/app/srs_app_http_conn.cpp:1368: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1369: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp:1372: 错误：invalid use of incomplete type ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.hpp:71: 错误：forward declaration of ‘struct SrsHttpStaticServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::http_mount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1377: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual void SrsHttpServer::http_unmount(SrsSource*, SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1382: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::mount_hls(SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1387: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_update_m3u8(SrsRequest*, std::string)’:
src/app/srs_app_http_conn.cpp:1392: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_update_ts(SrsRequest*, std::string, std::string)’:
src/app/srs_app_http_conn.cpp:1397: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual int SrsHttpServer::hls_remove_ts(SrsRequest*, std::string)’:
src/app/srs_app_http_conn.cpp:1402: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.cpp: In member function ‘virtual void SrsHttpServer::unmount_hls(SrsRequest*)’:
src/app/srs_app_http_conn.cpp:1407: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
src/app/srs_app_http_conn.hpp:70: 错误：forward declaration of ‘struct SrsHttpStreamServer’
make[2]: *** [objs/src/app/srs_app_http_conn.o] 错误 1
make[2]: Leaving directory `/etc/mysrs/srs-2.0release/trunk'
make[1]: *** [server] 错误 2
make[1]: Leaving directory `/etc/mysrs/srs-2.0release/trunk'
make: *** [default] 错误 2
![6](https://cloud.githubusercontent.com/assets/23515321/20423562/fd93daca-adab-11e6-8f12-ac0e698a6642.png)

**Comment by zhuashaoweiwu** [comment]
请问下谢谢！！

**Comment by winlinvip** [comment]
应该fix了，请尽量不要用SRS3，开发版改动天翻地覆。
