### ISSUE TITLE
编译时冲突--with-http-callback

### ISSUE THREAD

**Issue by zhuashaoweiwu** [ossrs/srs#696]
您好SRS2.0版本，为什么编译的时候
./configure --with-ssl --with-nginx  --with-ffmpeg --with-transcode --with-http-callback --with-ingest --pure-rtmp && make 这个样子会报错
make[2]: *** [objs/src/app/srs_app_http_conn.o] 错误 1
src/app/srs_app_http_conn.cpp:1402: 错误：invalid use of incomplete type ‘struct SrsHttpStreamServer’
去掉 --pure-rtmp   --with-http-callback其中一个就可以了，请问为什么？

**Comment by winlinvip** [comment]
SRS3强制开启HTTP。

**Comment by winlinvip** [comment]
SRS3强制开启HTTP。
