### ISSUE TITLE
release 2.0 REST API is not working

### ISSUE THREAD

**Issue by myhu** [ossrs/srs#701]
hi,

I have played a lot of using flv stream over http, wich is working really fine, but I cannot manage the stream.
Seeing the http api, I can see all the time 0 client, no matter how many stream are started.
Perhaps, this can be the reason, when I send DELETE stream or client, the stream in question is running forward, unstoppable way....
Sending DELETE query I get all the time different code in JSON ( i.e 2049 )

My configuration is :+1: ./configure --disable-all --with-hls --with-ssl --with-http-server --with-http-api --with-stat

What can I do wrong?

**Comment by winlinvip** [comment]
Not understand.
