### ISSUE TITLE
直播服务的时候，默认推送地址是rtmp://192.168.xxx.xxx:1935/live/stream一个推流地址吗？

### ISSUE THREAD

**Issue by ysfox** [ossrs/srs#705]
直播服务的时候，一个srs服务器默认推送地址是rtmp://192.168.xxx.xxx:1935/live/stream一个推流地址吗？我可以设置多个直播间吗，也就是对应不同的推流地址？如果可以设置，我要如何设置多个推流地址？

**Comment by shtzr840329** [comment]
live是你的项目  stream就是房间

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion
