### ISSUE TITLE
APPLICATION: forward to external servers

### ISSUE THREAD

**Issue by Steinies** [ossrs/srs#706]
This goes as feature request.

I downloaded and compiled srs then I tried to forward with this config:
v2:
```
vhost __defaultVhost__ {
	forward live-cdg.twitch.tv:1935/app/live_KryGoHere
}
```

v3:
```
vhost __defaultVhost__ {
    forward {
        enabled on;
        destination live-cdg.twitch.tv:1935/app/live_KryGoHere
    }
}
```

And i noticed that as tcUrl the server adds vHost and other information and other not nice things.

Is there a way to accomplish that? If not can an option for external forward to "not srs server" be added?
I would like to stream to my server and this one should stream to multiple targets.
e.g.:
`destination live-cdg.twitch.tv:1935/app/live_KryGoHere a.rtmp.youtube.com:1935/live2/key1234`

**Comment by Steinies** [comment]
I even tried to edit srs_app_forward.cpp, but it did not worked.

**Comment by bzdk** [comment]
@Steinies 

I have same requirement.Found 1 related issue:
https://github.com/ossrs/srs/pull/231

**Comment by bzdk** [comment]
@Steinies 

Here is my approach by using srs v1.FYI

I also prefer to use FORWARD for this purpose.

`
listen              1935;
max_connections     1000;
vhost __defaultVhost__ {
    transcode {
        enabled     on;
        ffmpeg      /root/ffmpeg/ffmpeg-3.0.2-64bit-static/ffmpeg;

        engine youtube_live {
            enabled         on;
            vcodec          copy;
            acodec          copy;
            output          rtmp://a.rtmp.youtube.com/live2/qwqm-f1sf-9g1m-****;
        }
    }
}
`

**Comment by winlinvip** [comment]
@bzdk You use the ingester to forward which need to forward one by one. The forward can apply rulers to all stream which publish to origin. I think it's ok when there is only few streams to forward, but we must use forward for amount of streams under the same ruler.

**Comment by bzdk** [comment]
@winlinvip agreed.

**Comment by Bit0git** [comment]
What is the state for this feature in 3.0?
It is too much of a limit inability to forward to external server.
For example what I need to accomplish is

OSB -----> SRS -----> (streaming platform A: xxx.com/key123)
                             |--> (streaming platform B: yyy.com/key456)
                             |--> (streaming platform C: zzz.com/key789)

In 2.0 I think the only solution is the copy transcode.
In Nginx is easy to push to multiple external server, without the demux/remux overhead and the spawn of ffmpeg, like in:

application live{

live on;
record off;
meta copy;
push “rtmp://xxx.com/key123”;
push “rtmp://yyy.com/key456”;
push “rtmp://xxx.com/key789”;
#Add all your rtmp endpoints here
}

**Comment by winlinvip** [comment]
Dup to #1342
