### ISSUE TITLE
PROTOCOL: 推送RTSP流时，录制flv观看、rtmp拉流观看失败。

### ISSUE THREAD

**Issue by Shuo-Jia** [ossrs/srs#707]
###  1、推送本地文件：
ffmpeg -re -i ../2.mp4 -vcodec libx264 -f rtsp rtsp://[ip]:554/live/1.sdp

录制和观看失败->vlc拉流观看绿屏，vlc观看录制的flv，画面大小总是跳动，总之解码失败，无法观看
### 2、推送摄像头：
ffmpeg -f dshow -i video="HD WebCam" -vcodec libx264 -preset:v ultrafast -tune:v zerolatency -f rtsp rtsp://[ip]:554/live/streamrtsp1.sdp

录制和观看失败->vlc拉流观看绿屏，vlc观看录制的flv，画面大小总是跳动，总之解码失败，无法观看
### 3、停止推送时，服务器崩溃:
推送本地文件时错误日志->
srs: src/app/srs_app_st.cpp:239: void srs_close_stfd(_st_netfd*&): Assertion `err != -1' failed.

推送摄像头文件时错误日志->
srs: src/app/srs_app_st.cpp:239: void srs_close_stfd(_st_netfd*&): Assertion `err != -1' failed.

**Comment by winlinvip** [comment]
RTSP会在SRS3增强。

**Comment by joke-lee** [comment]
也遇到这个问题，现在这个问题解决了么？

**Comment by winlinvip** [comment]
SRS3增强的方向还是在集群，RTSP摄像头越来越少了哇。

**Comment by KingMTan** [comment]
这个问题应该是下面代码的逻辑判断有误，在on_udp_packet函数中
`if (!cache->completed && pprint->can_print()) {
                srs_trace("<- "SRS_CONSTS_LOG_STREAM_CASTER" rtsp: rtp chunked %dB, age=%d, vt=%d/%u, sts=%u/%#x/%#x, paylod=%dB", 
                    nb_buf, pprint->age(), cache->version, cache->payload_type, cache->sequence_number, cache->timestamp, cache->ssrc, 
                    cache->payload->length()
                );
                return ret;
            }`
不应该将 cache->completed 与 pprint->can_print()放在一起判断

**Comment by winlinvip** [comment]
不支持RTSP推流，仅支持拉流，参考：https://github.com/ossrs/srs/issues/2304#issuecomment-826009290
