### ISSUE TITLE
支持RTMP推流认证，RTMP authentication

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#71]
https://github.com/winlinvip/simple-rtmp-server/issues/71

**Comment by winlinvip** [comment]
http://help.adobe.com/en_US/FlashMediaLiveEncoder/3.0/Using/WS5b3ccc516d4fbf351e63e3d11c104ba878-7fe2.html


```
When authenticating, users must provide a username, password, and RTMP string.


Flash Media Live Encoder can publish to multiple servers. If the servers have different authentication credentials, Flash Media Live Encoder may need to prompt for passwords more than once. To ensure that users enter the correct user ID and password, make sure that the password prompt indicates which server is being connected to.
```


It means that the FMS server can send a packet to request client authentication, and FMLE will display a username and password input box for authentication.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
![image](https://user-images.githubusercontent.com/2777660/71411979-78a87300-2686-11ea-892b-0de64e3f3a3c.png)

There is a place on OBS to enter a username and password, but currently, it is more common to directly place the authentication information in the URL. This is because it is more convenient for integration and also facilitates HTTP Callback verification.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Not necessarily need support, consider it in the future.

`TRANS_BY_GPT3`

**Comment by jyy1082** [comment]
Is there any implementation idea for stream certification?

`TRANS_BY_GPT3`

**Comment by winson08Li** [comment]
Has the push stream certification been implemented?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Without considering implementation, it is recommended to use HTTP Callback.

`TRANS_BY_GPT3`
