### ISSUE TITLE
SOURCE: SrsMessageQueue丢包shrink机制讨论（极端或故意情况）

### ISSUE THREAD

**Issue by haofz** [ossrs/srs#712]
```
int SrsMessageQueue::enqueue(SrsSharedPtrMessage* msg, bool* is_overflow)
{
    int ret = ERROR_SUCCESS;
    
    if (msg->is_av()) {
        if (av_start_time == -1) {
            av_start_time = msg->timestamp;
        }
        
        av_end_time = msg->timestamp;
    }
    
    msgs.push_back(msg);

    while (av_end_time - av_start_time > queue_size_ms) {
        // notice the caller queue already overflow and shrinked.
        if (is_overflow) {
            *is_overflow = true;
        }
        
        shrink();
    }
    
    return ret;
}

```
过程：发起一个流，对该流数据制造异常异常时间戳，然后，使用一个播放器观看且对该播放器限速（且不会因为超时而连接中断的情况下），查看srs进程占用内存会一直增长。
异常情况：
1、不开启time_jitter时，如果后来的视频包，时间戳比之前的值小很多很多，可能导致while(av_end_time - av_start_time > queue_size_ms)为负值，不会执行shrink
2、开启time_jitter=FULL时，极端情况下矫正也不会完全生效，导致av_end_time - av_start_time = 0，不会执行shrink
   比如：在SrsConsumer::enqueue()时，强行写死一个时间戳，矫正后的时间戳不是单增的
   ```
 SrsSharedPtrMessage* msg = shared_msg->copy();
    msg->timestamp = 90000000;  （新增测试）
    if (!atc) {
        if ((ret = jitter->correct(msg, ag)) != ERROR_SUCCESS) {

```
3、想法
while (av_end_time - av_start_time > queue_size_ms) { 
为是否可以增加一个“**小于等于0时**”和一个“**多于最大队列长度**”的条件 ？如：
`while (av_end_time - av_start_time > queue_size_ms || av_end_time - av_start_time <= 0 || msgs.size() > 2048) { `

**Comment by haofz** [comment]
Supplement:
1. When this situation occurs, the following similar message appears in the log, indicating a backlog in the queue:
srs.00.log-20161201:2016-12-01 20:29:29.092|warn|6048|4073382|11|fast vector incrase 1024=>2048
srs.00.log-20161201:2016-12-01 20:29:41.233|warn|6048|4073382|11|fast vector incrase 2048=>4096
srs.00.log-20161201:2016-12-01 21:36:49.772|warn|6048|4073382|11|fast vector incrase 1024=>2048
srs.00.log-20161201:2016-12-01 21:41:31.232|warn|6048|4073382|11|fast vector incrase 2048=>4096
srs.00.log-20161201:2016-12-01 21:42:08.660|warn|6048|4073382|11|fast vector incrase 4096=>8192
srs.00.log-20161201:2016-12-01 21:43:13.097|warn|6048|4073382|11|fast vector incrase 8192=>16384
srs.00.log-20161201:2016-12-01 21:45:38.953|warn|6048|4073382|11|fast vector incrase 16384=>32768
srs.00.log-20161201:2016-12-01 21:50:23.749|warn|6048|4073382|11|fast vector incrase 32768=>65536
srs.00.log-20161201:2016-12-01 21:59:55.806|warn|6048|4073382|11|fast vector incrase 65536=>131072

2. When the player link is disconnected, that is, when the srsconsumer is destructed, the queue can be cleared() and the memory can be released.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
There is a risk in that the conditions for judgment are relatively loose.
I think it can be simplified by setting a maximum queue length, for example, if the interval between audio and video packets is generally 10 milliseconds, then 10,000 packets would be 100 seconds. If it exceeds 10,000 packets, the queue should be cleared, which would be a suitable safeguard. After all, this situation is not very common.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Rare scenes, do not solve.

`TRANS_BY_GPT3`
