### ISSUE TITLE
请求强化httpServer，支持m3u8和mp4的高级播放

### ISSUE THREAD

**Issue by wuxianlijiang** [ossrs/srs#715]
当接到如下请求时：
` http://www.testvod.com/rec/hls/rec_xxx.m3u8?stat=60&end=120`
SERVER只返回m3u8文件中60秒到120秒之间的内容。

实现类似功能的ngx模块：
`http://nginx.org/en/docs/http/ngx_http_hls_module.html
For each media file, two URIs are supported:
A playlist URI with the “.m3u8” filename extension. The URI can accept optional arguments:
“start” and “end” define playlist boundaries in seconds (1.9.0).
“offset” shifts an initial playback position to the time offset in seconds (1.9.0). A positive value sets a time offset from the beginning of the playlist. A negative value sets a time offset from the end of the last fragment in the playlist.
“len” defines the fragment length in seconds.
A fragment URI with the “.ts” filename extension. The URI can accept optional arguments:
“start” and “end” define fragment boundaries in seconds.`

作为一名纯粹的没有开发能力的用户，想到的可能的思路是：当收到带有Start和end参数的请求时，server根据完整的m3u8生成一个临时m3u8，并把请求重定向到这个m3u8。

可否？热切期待！感谢成立兄和开发团队！

**Comment by winlinvip** [comment]
你这个是点播吧？直播从60到120秒没有意义啊。

**Comment by wuxianlijiang** [comment]
是的，成立兄

**Comment by wuxianlijiang** [comment]
悟空兄说到ffmpeg的一个东西，好像是只录成一个ts文件，用这个方法录制下来，应该能给m3u8的带参播放节省许多事情:) 我说的就是vod，成立兄。当然一并支持类似于 nginx_mod_h264_streaming  这样，支持mp4带start和end参数播放，就更棒了！

**Comment by winlinvip** [comment]
SRS不打算支持点播。
