### ISSUE TITLE
http_hooks模块 SrsHttpResponseReader::read_all_body() 解析content_length json body时，可能失败

### ISSUE THREAD

**Issue by afly3** [ossrs/srs#716]
在函数 buffer->grow(skt, owner->content_length());的结尾处，在读取完所指定长度的content_length后，结尾应该置0.
    *end = '\0';

**Comment by winlinvip** [comment]
这个读取是带长度的，也就是它实际上是类似std::string的，自己就带有长度信息，是不需要\0结尾的。
你是否是说，有时候json解析需要\0结尾，也就是要求是c_str？

**Comment by winlinvip** [comment]
我看了下代码：
```
int SrsHttpHooks::do_post(std::string url, std::string req, int& code, string& res)
。。。。。。
    SrsJsonAny* info = SrsJsonAny::loads((char*)res.c_str());
```
是将response:string转成了c_str的，所以会在后面自动加\0的，不会有这个问题。除非标准库的这个函数不对。

**Comment by afly3** [comment]
您说的是对的， 我忽略了您现有的json解析库。是由于需求，vhost改成动态可配置的，需要传送json串给srs接收，感觉SrsJsonAny库的效率太低，换成了rapidjson。调用完read_all_body()后，直接将srsfastbuffer的data传给rapidjson解析，出问题了。

**Comment by afly3** [comment]
不好意思，是我改动的问题，您原本的没有问题。给您添麻烦了

**Comment by winlinvip** [comment]
SrsJsonAny底下是用的另外的库解析的。你做过性能测试，瓶颈是在SrsJsonAny还是底下的库？如果是底下的库，你换库就可以。
