### ISSUE TITLE
Redirect videos without live them

### ISSUE THREAD

**Issue by massoudAfrashteh** [ossrs/srs#719]
I have two rtmp servers. In first one given user request with **rtmp://.../appName/token** and then I'll push my video to an another server. Then problem is that both servers serve my video is it a standard thing than we have to serve video in first RTMP too?

**Comment by winlinvip** [comment]
Not understand what's your problem.

**Comment by massoudAfrashteh** [comment]
When I push a video to another RTMP server I can play it on my first RTMP server but I just want to play it on second server.

**Comment by winlinvip** [comment]
You can use security to deny play on the first server(allow publish to both). Please read wiki.

**Comment by massoudAfrashteh** [comment]
I know I can do this but I need to send many videos with same name to first RTMP server and then push them with that names I want to secend RTMP server.
