### ISSUE TITLE
Push videos to anther server with dynamic callback

### ISSUE THREAD

**Issue by massoudAfrashteh** [ossrs/srs#720]
I want to return the url of RTMP edge server from a http url and then push my video to that URL like on_publish on Nginx-rtmp. origin just push videos to a static address!

Thanks

**Comment by winlinvip** [comment]
Read wiki about http callback, a better solution.

**Comment by massoudAfrashteh** [comment]
Thanks.

**Comment by olegmelnik** [comment]
@winlinvip Сould you explain how to return multiple urls from callback? I can not find an example in the documentation
