### ISSUE TITLE
能否支持html5播放？能否支持websocket

### ISSUE THREAD

**Issue by chfeizy** [ossrs/srs#722]
http_server 支持Access-Control-Allow-Origin:*
使flv或者hls可以用mse播放
然后能否支持websocket推直播流使用mse播放（使用flv.js播放）

**Comment by winlinvip** [comment]
需要用一个websocket的代理，将http-flv转成websocket，我在video-flow中给了一个demo，用golang写的，你可以直接用：
https://github.com/winlinvip/videojs-flow/blob/master/demo/mse.go

**Comment by winlinvip** [comment]
写了个例子：https://github.com/ossrs/srs/issues/1576#issuecomment-574963151
