### ISSUE TITLE
退出时st_net_close的内存泄漏

### ISSUE THREAD

**Issue by enochi** [ossrs/srs#724]
develop3.0版本.只要是st_read,st_accept等传入的超时时间无限大时,st_netfd_close便不会调用st_netfd_free.
查得st源码 
int st_netfd_close(_st_netfd_t *fd)
{
  if ((*_st_eventsys->fd_close)(fd->osfd) < 0)
    return -1;

  st_netfd_free(fd);
  return close(fd->osfd);
}
 int _st_select_fd_close(int osfd){ if (_ST_SELECT_READ_CNT(osfd) || _ST_SELECT_WRITE_CNT(osfd) ||
        _ST_SELECT_EXCEP_CNT(osfd)) {
        errno = EBUSY;
        return -1;
    }
似乎我们需要先手动将fd从epoll队列中移除才行?
gperftools检测得如下:
Leak of 40 bytes in 1 objects allocated from:
	@ 6d2e88 _st_netfd_new
	@ 6d2f7b st_netfd_open
	@ 6a260f SrsSignalManager::initialize
	@ 6a3acf SrsServer::initialize_signal
	@ 5492ed run_master
	@ 548fdd run
	@ 548f94 main
	@ 7efe5ce81830 __libc_start_main
Leak of 40 bytes in 1 objects allocated from:
	@ 6d2e88 _st_netfd_new
	@ 6d2f9c st_netfd_open_socket
	@ 66dce0 SrsTcpListener::listen
	@ 6a06e8 SrsBufferListener::listen
	@ 6a62f5 SrsServer::listen_rtmp
	@ 6a4162 SrsServer::listen
	@ 549357 run_master
	@ 548fdd run
	@ 548f94 main

**Comment by enochi** [comment]
另外,为什么我们的srs gperf为啥要指定PPROF_PATH才行啊,而且指定2.5版本的pprof还不行,虽然我链接的也是gperf 2.5 tcmalloc?这个问题折腾了2天了,最后还是老老实实指定到我们的2.1版本才出来对应的函数结果.

**Comment by winlinvip** [comment]
不会有这个问题吧？fd如果是wait(fd,-1)的方式，那应该先interrupt，然后再close(fd)，这样释放fd就没事。
