### ISSUE TITLE
CLUSTER: edge集群可否做成支持多个源站？

### ISSUE THREAD

**Issue by superxrb** [ossrs/srs#725]
Hi winlin.是这样的，edge集群的时候只能设置单个有效的源站，这个无法远远满足我们直播源比较多的需求。可否做成推流多个不同码流到多个不同源站，然后在边缘向源站请求的时候，轮询每个源站去找码流，谢谢！

**Comment by winlinvip** [comment]
The efficiency of polling is extremely low, as it requires 10 round trips if there are 10 origin servers. If a request is made for a non-existent stream, it takes 10 attempts to determine that the stream does not exist. It should be considered to use RTMP302, which directly redirects to the origin server with the stream. This is a feature of the origin server cluster.

`TRANS_BY_GPT3`

**Comment by superxrb** [comment]
Hi winlin. We need many features that are only available in version 3.0. When do you plan to open the testing for SRS 3.0? Do you have a version plan?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Around 2-3 years.

`TRANS_BY_GPT3`

**Comment by QGB** [comment]
cluster edge

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed, Origin Cluster.
