### ISSUE TITLE
twitch streaming guide

### ISSUE THREAD

**Issue by rembomy** [ossrs/srs#726]
Sorry for a dumb question, but is there a guide for setting this up to use for transcoding and streaming to twitch for not so gifted guys with basic understanding of how stuff works? Thanks!

**Comment by winlinvip** [comment]
What's the guide or API of twitch? For example, how can you publish stream to twitch by ffmpeg?

**Comment by rembomy** [comment]
It should basically be 'push rtmp://live-lhr.twitch.tv/app/twitch_key;' and it should be flv

for ffmpeg i've been using:
ffmpeg -re -i rtmp://localhost:1935/trans/$name -vcodec libx264 -preset medium -x264opts nal-hrd=cbr:force-cfr=1:keyint=60 -r 30 -b:v 2500k -maxrate 2500k -bufsize 2500k -threads 12 -s hd1080 -sws_flags spline -acodec copy -f flv rtmp://localhost:1935/live/${name};                  

This was done with arut/nginx-rtmp-module, but since it is no longer being updated I would like to move to something that is an maybe get better results in the long run :)

**Comment by mbeacom** [comment]
You can stream to twitch the same way that you stream to any other RTMP FLV consumer via some push.  
@rembomy You should be able to use the functionality outlined in: https://github.com/ossrs/srs/issues/367 or https://github.com/ossrs/srs/wiki/v1_EN_SampleRTMP

**Comment by winlinvip** [comment]
Maybe you can try SRS edge, which proxy all stream to upstream server, without any transcoding. BTW, why transcode by ffmpeg in your previous scenario? Must you transcode it? Or just ok to proxy the stream to twitch server? The transcoding takes lots of CPU, so we should never use it unless it's necessary.

**Comment by winlinvip** [comment]
SRS EDGE to proxy stream to one upstream: https://github.com/ossrs/srs/wiki/v1_EN_Edge
Or use forward to proxy to many upstreams. Recommend to use EDGE, which is more convinent.

**Comment by rembomy** [comment]
I want to transcode on server side because this way I can keep my gaming PC CPU free, I can send 50000k video with NVENC to server (almost 0 impact on gaming pc) and then server makes it ready for twitch with good quality at 2500k. If I would use same 2500k on PC then NVENC would screw with quality and x264 would just eat up CPU.

I'll start experimenting on this and see what I can come up with, thanks!

**Comment by winlinvip** [comment]
You must use transcoding of SRS by FFMPEG, you can write the output url to use variables, please read the transcode wiki.
