### ISSUE TITLE
编译缺少文件valgrind/valgrind.h

### ISSUE THREAD

**Issue by Laizhongsheng** [ossrs/srs#727]
git clone https://github.com/ossrs/srs
cd srs/trunk;
./configure --disable-all --with-ssl   报错
		if [ ! -d LINUX_2.6.32-358.el6.x86_64_DBG ]; then mkdir LINUX_2.6.32-358.el6.x86_64_DBG; fi
			cc  -DLINUX -DMD_HAVE_EPOLL -DDEBUG -Wall -g -DMD_HAVE_EPOLL -DMD_VALGRIND -c sched.c -o LINUX_2.6.32-358.el6.x86_64_DBG/sched.o
			sched.c:52:31: ??:valgrind/valgrind.h:?????????
			sched.c: ???'st_thread_exit'?:
			sched.c:272: ??:??????'VALGRIND_STACK_DEREGISTER'
			sched.c: ???'st_thread_create'?:
			sched.c:642: ??:??????'VALGRIND_STACK_REGISTER'
			make[1]: *** [LINUX_2.6.32-358.el6.x86_64_DBG/sched.o] Error 1
			make[1]: Leaving directory `/opt/srs/trunk/objs/state-threads-1.9.1'
			make: *** [linux-debug] Error 2
			Build state-threads failed, ret=2

**Comment by winlinvip** [comment]
Valgrind is not supported in SRS2.0. The current release is SRS2.
SRS3 supports valgrind. Is your system CentOS or Ubuntu? I have installed valgrind-devel for both, but still cannot find the header files?

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
The system is Centos 6.0.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
After installing valgrind-devel, you can configure it.
yum -y install valgrind-devel

Compiling now, thank you.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Oh, I understand. You have valgrind, but not devel. The script needs to be modified.

`TRANS_BY_GPT3`
