### ISSUE TITLE
推流数据断开后，ffmpeg拉流超时

### ISSUE THREAD

**Issue by kria113** [ossrs/srs#731]
推流 /live/xxx地址，ffmpeg本地拉这个流，然后做一些其他操作，推流结束后，我向ffmpeg发送了'q'结束，但是没有很快结束，等了30s超时才结束，RTMP_ReadPacket, failed to read RTMP packet header；
推流/live/xxx结束后，所有拉取这个流地址的 RTMP tcp连接都应该断开吧，但是这样测试，没有断开，超时了。帮忙看看srs是这样的逻辑吗？ 谢谢~

**Comment by winlinvip** [comment]
FFMPEG的逻辑。
