### ISSUE TITLE
APPLICATION: Redirect, Nginx rtmp 里带的通过 Http API进行切换客户端播放流功能也很实用

### ISSUE THREAD

**Issue by dreamsxin** [ossrs/srs#732]
多个摄像头流进来，可以控制客户端看哪个流，随时切换。

**Comment by winlinvip** [comment]
Can you provide a detailed description? Are you referring to the Redirect function?

`TRANS_BY_GPT3`

**Comment by dreamsxin** [comment]
Just redirect to  https://github.com/arut/nginx-rtmp-module/wiki/Control-module#redirect

I am describing his API.
`http://server.com/control/redirect/subscriber?srv=SRV&app=APP&name=NAME&newname=NEWNAME`

There is a bug in switching his push target address, and switching back and forth will cause the stream to be lost.
`http://server.com/control/redirect/publisher?srv=SRV&app=APP&name=NAME&newname=NEWNAME`

It would be even more perfect if we could add a "newapp".

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Got it.

**Comment by winlinvip** [comment]
This Redirect uses the Duplicate Stream scheme to achieve a more appropriate approach, duplicating the specified stream into other streams with different names. In this way, the original stream is not affected, and it can simultaneously output as RTMP, FLV, and HLS.

`TRANS_BY_GPT3`

**Comment by dreamsxin** [comment]
Making a copy is of course better, as long as it is possible to control which copy to duplicate at any time, so that the client will not experience any issues with the connection being disconnected. This enables seamless switching, but will there be any anomalies in the data during this process?

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
Redirect https://github.com/arut/nginx-rtmp-module/wiki/Control-module#redirect
This is a function to switch streams. I'm not sure if there will be any issues during the switching process. Will RTMP lag for a moment? Will HLS die?


`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
HLS estimation will not die, but there will be a DISCONTINUITY, and generally, player support should not be a problem.
However, I do have a question, does NIGNX's Redirect only support RTMP? Have they not considered HLS?

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
Is it possible to implement this switch stream function in srs?

`TRANS_BY_GPT3`

**Comment by dreamsxin** [comment]
If it is only about switching publishers, then HLS doesn't need to be considered. If it is about switching the client-side playback source, Nginx shouldn't be used because its HLS segmentation is not performed by client-side pulling and partitioning.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS can certainly be implemented, but it needs to be put in SRS3.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
Okay, I still prefer applications developed by ourselves Chinese. Let's try using nginx-rtmp first. Once it can run on srs, please inform us. Thank you.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Soon, SRS3 will be released in 2 to 3 years. By the way, why do you need this feature? What is it used for? In what situations would there be multiple streams and a need to call the API to select one route as the output?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
#739 mentioned a method to use ffmpeg to duplicate the stream and push it to SRS. This method is also very good (low cost because it is a copy). If SRS does the duplication on its own, it needs to consider the problem of information loss after restart.

`TRANS_BY_GPT3`

**Comment by dreamsxin** [comment]
Switching streams in Ffmpeg will cause disconnection, but if using hls it will be possible.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Will re-stream, but the client will not disconnect.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
For example, there are two venues, which means two streams. The audience can only see one stream address in the end. This stream is controlled by the broadcasting control party, who selects one of the two routes. The player (rtmp or m3u8) cannot switch the playback address.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is most suitable to implement using ingest, or you can create your own program to pull the stream from the server, rename it, and then push it back to the server. This way, both RTMP and HLS are available.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
Redirect https://github.com/arut/nginx-rtmp-module/wiki/Control-module#redirect
I have set up the environment and tested a few rounds, and the conclusion is as follows:
1. During the switching process, nginx-rtmp will first unpublish the previous stream before publishing the new stream.
2. For the player (playing rtmp stream), it will first receive notification messages: NetStream.Play.UnpublishNotify (closing the previous stream) and NetStream.Play.PublishNotify (switching to the new stream). For normal players, it is likely to freeze and not respond (tested with several players, they all froze).
3. After reviewing the nginx-rtmp code, it indeed closes the previous stream before switching to the new stream.
4. This is for reference for winlinvip. I hope it can be implemented to directly switch to the new stream without closing the previous stream, so that no event is pushed to the client's player.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS will not transfer this UnpublishNotify and PublishNotify to the player, only SequenceHeader + A/V data will be provided. Additionally, why not use the above solution? Start an FFmpeg to capture and push different streams.
A=>ffmpeg=>C
If it is changed to B:
B=>ffmpeg=C
The player plays C without interruption and won't receive any strange events.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
I have tried the method you mentioned before:
Use ffmpeg to capture different streams and then push them:
Currently it is A: A=>ffmpeg=>C
If it is changed to B: B=>ffmpeg=C (Before pushing B, A still needs to be stopped first)

In the player end, the observed effect is a brief pause, and then it continues to play the content of B. I don't know if there is any solution to prevent the pause.
Furthermore, HLS will recalculate the index of the segments.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Firstly, the player has a buffer, for example, a 3-second buffer. In reality, it might be up to 10 seconds due to network fluctuations.
Secondly, when you switch, if you switch using a program, it will be very fast, for example, the switch will be completed in 300 milliseconds.
So, when you restart the streaming, you won't see any pause.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
I create an environment to test.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
Using ffmpeg for switching push effects indeed performs better than using nginx-rtmp's redirect. However, when switching, it is necessary to kill the process ID of the previous push, which feels a bit violent.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
As long as it's not `KILL -9`, it cannot be considered as violence. When it comes to servers, the main focus is on managing the state, and after restarting, this rule information might not be available anymore (whether it's A to C or B to C). Conceptually speaking, it is incomplete.

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
To switch using ffmpeg, you need to kill the previous process and then push again.

1. From A to D: ffmpeg -i rtmp://ip/streamA -f flv rtmp://ip/streamD

2 kill -9 `pidof ffmpeg`

3. From B to D: ffmpeg -i rtmp://ip/streamB -f flv rtmp://ip/streamD


Is there any way to do it without killing? When I use the method of killing, the player (rtmp) does not stop when switching, but the screen jumps.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Why not KILL? You want to achieve functionality, the purpose is not to avoid killing...

`TRANS_BY_GPT3`

**Comment by zhenchengdezhichi** [comment]
It can be implemented on the streaming end to switch and discard raw stream.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍
