### ISSUE TITLE
srs_app_rtmp_conn.cpp日志打印崩溃bug

### ISSUE THREAD

**Issue by hujixiang** [ossrs/srs#734]
版本:1b175b11070e70c824664f42e99344c93160b40a
时间：2017-01-06
文件：srs_app_rtmp_conn.cpp
现象：
运行edge模式下会崩溃，原因是打印存在 格式化输出错误问头

代码：
void SrsSimpleRtmpClient::kbps_sample(const char* label, int64_t age)
{
    kbps->sample();
    
    int sr = kbps->get_send_kbps();
    int sr30s = kbps->get_send_kbps_30s();
    int sr5m = kbps->get_send_kbps_5m();
    int rr = kbps->get_recv_kbps();
    int rr30s = kbps->get_recv_kbps_30s();
    int rr5m = kbps->get_recv_kbps_5m();
    
    srs_trace("<- %s time=%"PRId64", okbps=%d,%d,%d, ikbps=%d,%d,%d", age, sr, sr30s, sr5m, rr, rr30s, rr5m);
}

void SrsSimpleRtmpClient::kbps_sample(const char* label, int64_t age, int msgs)
{
    kbps->sample();
    
    int sr = kbps->get_send_kbps();
    int sr30s = kbps->get_send_kbps_30s();
    int sr5m = kbps->get_send_kbps_5m();
    int rr = kbps->get_recv_kbps();
    int rr30s = kbps->get_recv_kbps_30s();
    int rr5m = kbps->get_recv_kbps_5m();
    
    srs_trace("<- %s time=%"PRId64", msgs=%d, okbps=%d,%d,%d, ikbps=%d,%d,%d", age, msgs, sr, sr30s, sr5m, rr, rr30s, rr5m);
}

**Comment by winlinvip** [comment]
版本号应该是3.0.13，`./objs/srs -v`可以看到的。
