### ISSUE TITLE
多路如何使用其中一路

### ISSUE THREAD

**Issue by Laizhongsheng** [ossrs/srs#739]
有人做过多路推流，切换成1路：

1 手机A 推 /live/live1     (H264+AAC)
2 手机B 推 /live/live2   (H264+AAC)
3 手机C 推 /live/live3  (H264+AAC)

某一时刻选择 /live/live2，推到 /live/livenew ; 
某一时刻选择  /live/live1，推到 /live/livenew ; 
某一时刻选择  /live/live3，推到 /live/livenew ; 
.....
3路中的任何选择与操作

最终使用 rtmp://ip/live/livenew 和 http://ip/live/livenew.m3u8

**Comment by winlinvip** [comment]
Dup to #732

**Comment by winlinvip** [comment]
Can NGINX's Redirect support RTMP and HLS?

`TRANS_BY_GPT3`

**Comment by Laizhongsheng** [comment]
The configuration file is below. Use 2 FMLE to push it up, both can access the RTMP and HLS within it. Use FFmpeg to switch the final stream "livenew" which also has RTMP and HLS.
```
ffmpeg -re -i rtmp://10.10.10.26:1935/live/live2  \
-vcodec copy -acodec copy -f flv -y rtmp://10.10.10.26:1935/live/livenew

---srs.conf----
listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8081;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
	security {
		 enabled         on;
		 allow           play        all;
		 allow           publish     10.10.10.100;
	}
	hls {
	    enabled         on;
	    hls_fragment    10;
	    hls_window      60;
	    hls_path        ./objs/nginx/html;
	    hls_m3u8_file   [app]/[stream].m3u8;
	    hls_ts_file     [app]/[stream]-[seq].ts;
	}
}
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Well, using ffmpeg to re-encode and then send it to SRS is also a very good approach. Server-side duplication is a similar implementation, but it is done at the memory level by oneself.
The method you are using is actually very good too, but SRS's own duplication needs to consider how to handle it after restarting.

`TRANS_BY_GPT3`
