### ISSUE TITLE
一个vhost 支持多个转码

### ISSUE THREAD

**Issue by crazyhailong** [ossrs/srs#759]
一个vhost能否支持多个transcode

**Comment by winlinvip** [comment]
Read wiki https://github.com/ossrs/srs/wiki/v2_CN_FFMPEG

**Comment by winlinvip** [comment]
Please follow [HOW TO ASK QUESTION](https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion) to file issue.
