### ISSUE TITLE
OpenSSL version upgrade consideration

### ISSUE THREAD

**Issue by HarukaMa** [ossrs/srs#767]
From [OpenSSL website](https://www.openssl.org/source/):

> The 0.9.8, 1.0.0 and 1.0.1 versions are now out of support and should not be used.

Please consider upgrading OpenSSL.

**Comment by winlinvip** [comment]
Consider it in SRS3.
For SRS2, there is a workaround, to use `./configure --use-sys-ssl` to use system ssl library:
```
--use-sys-ssl                     donot compile ssl, use system ssl(-lssl) if required.
```

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/01d5e4da17f4dcb1180094c58abc6ff54679b30b
