### ISSUE TITLE
同一推流地址推流，第二次推流日志提示DVR出错

### ISSUE THREAD

**Issue by eagle-zhang** [ossrs/srs#768]
SRS开了rtmp、hls、http-flv、DVR。
使用FFmpeg推流，同一个推流地址，推的是同一个文件。
第一次推是正常的，第二次推，提示出错，删除DVR视频文件后推流正常。
DVR到flv和mp4都是如此。

日志如下：
[Error][142][11] DVR can't append to exists path=./objs/nginx/html/dvr/mylive/test_film.flv. ret=3082(Resource temporarily unavailable)
[Error][142][11] start dvr failed. ret=3082(Resource temporarily unavailable)
[Error][142][11] start dvr failed. ret=3082(Resource temporarily unavailable)
[Error][142][11] notify publish failed. ret=3082(Resource temporarily unavailable)
[Trace][142] unpublish drop ts segment, sequence_no=241, uri=test_film-241.ts, duration=0.00, start=181285290
[Trace][142] cleanup when unpublish
[Error][142][2] stream service cycle failed. ret=3082(No such file or directory)

**Comment by eagle-zhang** [comment]
看了源码，功能是这么实现的。虽然说得过去，但易用性不太好。断线重连后就没法推流了。

**Comment by winlinvip** [comment]
不可以录制到一个文件，路径不要写死了。

**Comment by winlinvip** [comment]
segment或者session的plan，路径都有变量可用的。
