### ISSUE TITLE
(Unofficially) Support more OS?

### ISSUE THREAD

**Issue by HarukaMa** [ossrs/srs#769]
You could just list the dependencies and let end users install them themselves. You of course don't need to give support on those configurations.

Such strict requirements doesn't really make sense, and using profanity words with it is **PLAIN STUPID**. Respect your users.

Why don't you use Chinese in those scripts if you can't really use English correctly?

> what a fuck.

**Comment by winlinvip** [comment]
Only CentOS, Ubuntu, ARM linux are supported.

**Comment by winlinvip** [comment]
MAC/OSX is supported in SRS3+

Windows is on the way in SRS5.
