### ISSUE TITLE
I got something worry when to publish raw h264 steam on ubuntu 16.04 by srs_h264_raw_publish.c .

### ISSUE THREAD

**Issue by ssgnat** [ossrs/srs#772]
I got something worry when to publish h264 steam on ubuntu 16.04 by srs_h264_raw_publish.c .

the error log as following:
publish raw h.264 as rtmp stream to server like FMLE/FFMPEG/Encoder
SRS(ossrs) client librtmp library.
version: 3.0.18
[2017-02-17 14:59:00.56][9738] raw_file=./720p.h264.raw (from http://winlinvip.github.io/srs.release/3rdparty/720p.h264.raw), rtmp_url=rtmp://baoqianli.8686c.com/live/d5f742ff87bb4aaab0fa37e21d26ec1f, fps=25.00
[2017-02-17 14:59:00.56][9738] read entirely h264 raw file, size=5169KB
[2017-02-17 14:59:00.62][9738] simple handshake success
[2017-02-17 14:59:00.66][9738] connect vhost/app success
[2017-02-17 14:59:00.68][9738] publish stream failed.

**Comment by winlinvip** [comment]
May I have your server log, please?

**Comment by winlinvip** [comment]
Please give me other data, follow:
https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion
Or https://github.com/ossrs/srs/wiki/v1_EN_HowToAskQuestion

**Comment by ssgnat** [comment]
服务端看不到日志，我只是使用这些服务器，而且没有直接渠道可以对上那边；
后面我努力想想办法让他们给下

**Comment by winlinvip** [comment]
你可以自己搭建一个SRS服务器，推SRS上面，如果没有问题，可以用SRS转发RTMP给你的供应商。
有可能你的供应商没有办法接收直接推的流。

**Comment by ssgnat** [comment]
[log-1728.zip](https://github.com/ossrs/srs/files/847342/log-1728.zip)

关键日志：createStream 36.251.248.183 2017-03-16 15:02:10 - baoqianli.8686c.com live - 5411 200 rtmp - rtmp://baoqianli.8686c.com/live /live - - - - - - - - 395 3431 rtmp-8f815478a85f3d91099b91a4-52391
publish 36.251.248.183 2017-03-16 15:02:10 - baoqianli.8686c.com live ad221df0e4e1423991c4e6e5c224abff123?videoKeyframeFrequency=2&totalDatarate=248 0 200 rtmp - rtmp://baoqianli.8686c.com/live /live - - - - - - - - 515 3677 rtmp-8f815478a85f3d91099b91a4-52391
FCUnpublish 36.251.248.183 2017-03-16 15:03:35 - baoqianli.8686c.com live - 90655 200 rtmp - rtmp://baoqianli.8686c.com/live /live - - - - - - - - 2696255 4014 rtmp-8f815478a85f3d91099b91a4-52391
closeStream 36.251.248.183 2017-03-16 15:03:35 - baoqianli.8686c.com live - 90656 200 rtmp - rtmp://baoqianli.8686c.com/live /live - - - - - - - - 2696291 4205 rtmp-8f815478a85f3d91099b91a4-52391
deleteStream 36.251.248.183 2017-03-16 15:03:35 - baoqianli.8686c.com live - 90662 200 rtmp - rtmp://baoqianli.8686c.com/live /live - - - - - - - - 2696341 4542 rtmp-8f815478a85f3d91099b91a4-52391
stop 36.251.248.183 2017-03-16 15:03:35 - baoqianli.8686c.com live ad221df0e4e1423991c4e6e5c224abff123?videoKeyframeFrequency=2&totalDatarate=248 85243 200 rtmp - rtmp://baoqianli.8686c.com/live /live - - - - - - - - 2696341 4542 rtmp-8f815478a85f3d91099b91a4-52391
disconnect 36.251.248.183 2017-03-16 15:03:43 - baoqianli.8686c.com live - 98264 200 rtmp - rtmp://baoqianli.8686c.com/live /live - - - - - - - - 2696341 4542 rtmp-8f815478a85f3d91099b91a4-52391

看起来服务器做了处理。主动关闭了。

**Comment by ssgnat** [comment]
push://baoqianli.8686c.com/live/ad221df0e4e1423991c4e6e5c224abff?wsRecord=off
play:rtmp://live-baoqianli.8686c.com/live/ad221df0e4e1423991c4e6e5c224abff

**Comment by winlinvip** [comment]
这个日志没有用的。你应该自己搭一个SRS，看有没有错误。可以让SRS Edge转推给你的供应商。
