### ISSUE TITLE
KERNEL: Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ossrs/srs#789]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in a macro like [`srs_freep`](https://github.com/ossrs/srs/blob/3903d2a8e36dd9d36bd0c863aa582efc523a9938/trunk/src/core/srs_core.hpp#L101 "Update candidate: srs_freep(p)").

**Comment by winlinvip** [comment]
Seems reasonable, thanks~
