### ISSUE TITLE
HLS服务经常出问题

### ISSUE THREAD

**Issue by dadait** [ossrs/srs#791]
RTMP的流使用情况很好，一直没出过什么问题，推送的流断开后，再次连接推流都没什么问题。

HLS的切片经常会会出现一种情况，每天都会遇到，流全都切到xxx.ts.tmp中。导致文件一直不停变大，后面也不会再有新的切片产生。需要重启SRS服务才能解决。     

请问大家有没有遇到过此类问题的。是怎么解决的？

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion#file-issue
信息不全。

**Comment by guoyawei** [comment]
同样问题
