### ISSUE TITLE
C++11 and Beyond Support

### ISSUE THREAD

**Issue by HungMingWu** [ossrs/srs#793]
C++11已經是個成熟的標準了。相對於自己寫SRS_Auto_free和srs_free/srs_frepa
我想C++11的Smart_pointer是個更好的選擇，同時C++11的一些特性也能簡化程式碼邏輯

**Comment by winlinvip** [comment]
I really wish I could use ANSI C, using ANSI C++ has already been despised by many people. 😭

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Open source should consider not only new technologies, but also the habits of developers. For most audio and video developers who use C/C++, it is important to make sure that C programmers can see and modify the code.

Many C++ programmers may not necessarily write in true C++. Their skill level is in C, but they use the syntax of C++.

`TRANS_BY_GPT3`
