### ISSUE TITLE
能在2.0稳定版中加入  in_ack_size 支持吗？现在wirecast推流10来秒后就断了

### ISSUE THREAD

**Issue by wavecut** [ossrs/srs#795]
能把3.0中的以下这些参数加入到2.0稳定版中吗？谢谢。

    # The input ack size, 0 to not set.
    # Generally, it's set by the message from peer,
    # but for some peer(encoder), it never send message but use a different ack size.
    # We can chnage the default ack size in server-side, to send acknowledge message,
    # or the encoder maybe blocked after publishing for some time.
    # Default: 0
    in_ack_size     0;
    
    # The output ack size, 0 to not set.
    # This is used to notify the peer(player) to send acknowledge to server.
    # Default: 2500000
    out_ack_size    2500000;

**Comment by winlinvip** [comment]
This feature is for SRS3, you can merge it yourself. Or find someone to merge it for you, I can recommend someone in the WeChat group.
There are more people familiar with SRS now compared to the past two years, so you can customize it.

`TRANS_BY_GPT3`

**Comment by andrew867** [comment]
In case someone finds this when searching for a solution for Wirecast 7 constant disconnects, use the 3.0 develop branch and set these options in your vhost configuration:
```
    in_ack_size     2500000;
    out_ack_size    2500000;
    mix_correct     on;
```

Full hls.conf file:

```
# the config for srs to delivery hls
# @see https://github.com/ossrs/srs/wiki/v1_CN_SampleHLS
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
vhost __defaultVhost__ {
    in_ack_size     2500000;
    out_ack_size    2500000;
    mix_correct     on;
    hls {
        enabled         on;
        hls_fragment    10;
        hls_window      60;
        hls_path        ./objs/nginx/html;
        hls_m3u8_file   [app]/[stream].m3u8;
        hls_ts_file     [app]/[stream]-[seq].ts;
    }
}

```

**Comment by winlinvip** [comment]
👍
