### ISSUE TITLE
APPLICATION: OBS publish stream failed, SRS error for no stream name

### ISSUE THREAD

**Issue by winlinvip** [ossrs/srs#796]
When using OBS to publish live stream to SRS, it maybe upset you if you don't be careful. Remember to split your RTMP url to tcURL and stream, for example, when you want to publish to URL `rtmp://192.168.1.170:1935/live/livestream`:

It's wrong if `Stream key` is empty:
```
URL: rtmp://192.168.1.170:1935/live/livestream
Stream key:
```

The right way:
```
URL: rtmp://192.168.1.170:1935/live
Stream key: livestream
```

![obs](https://cloud.githubusercontent.com/assets/2777660/23576635/b54c307c-00e5-11e7-899d-29f88ef6e1d0.jpeg)

**Comment by ChandZhang** [comment]
It seems that when streaming with OBS, a slash is added to the end of the streaming URL, and then the key is directly appended to the URL.
The input URL is rtmp://192.168.1.170:1935/live/livestream
The key is aabbccdd
The actual output is rtmp://192.168.1.170:1935/live/livestream/aabbccdd
This is an issue with OBS, or perhaps it is their intention to place the stream name below.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Yes, translation issue, "密钥" should be translated as "stream name".

`TRANS_BY_GPT3`
