### ISSUE TITLE
STREAM: 2.0最新版本，使用ffmpeg转码后hls 花屏

### ISSUE THREAD

**Issue by xiayongtao** [ossrs/srs#802]
![image](https://cloud.githubusercontent.com/assets/11712819/23798038/b3bf39e6-05dd-11e7-9d61-9005f463102f.png)

转码参数
![image](https://cloud.githubusercontent.com/assets/11712819/23798062/c35ae99a-05dd-11e7-8d50-7e6dd5fd2a31.png)

之前版本也是zhe这个的转码参数正常

**Comment by winlinvip** [comment]
The description of the steps to reproduce is unclear.

`TRANS_BY_GPT3`

**Comment by xiayongtao** [comment]
1. Normal streaming, using ffmpeg transcoding mechanism, transcoding parameters: libx264, bitrate 1024, fps 25, resolution 960x540, profile main. The rtmp stream can be viewed normally.
2. When the hls switch is turned on, the m3u8 stream shows screen distortion.
3. When ffmpeg transcoding is turned off, the m3u8 stream is normal.
4. In the previous version, when ffmpeg transcoding is turned on and hls switch is turned on, the m3u8 stream is normal.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Please provide a usable config and the source (if the flv under the SRS doc is available, there is no need to provide it). 
Make sure to maintain the markdown structure.

`TRANS_BY_GPT3`

**Comment by xiayongtao** [comment]
[srs.zip](https://github.com/ossrs/srs/files/835631/srs.zip)

The video used in the doc will also have screen flickering issues.
![image](https://cloud.githubusercontent.com/assets/11712819/23821962/65b3270e-067c-11e7-984d-58e1724e5a7b.png)




`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
https://github.com/ossrs/srs/wiki/v1_CN_HowToAskQuestion#file-issue
Please provide the reproduction steps and detailed configuration, do not simply mention the parameters used.

`TRANS_BY_GPT3`

**Comment by xiayongtao** [comment]
The configuration file is in the attachment above.
1. Start the SRS service using the configuration file in the attached SRS.zip.
2. Use ffmpeg -re -i ./doc/source.200kbps.768x320.flv -vcodec copy -acodec copy -f flv rtmp://127.0.0.1/live/test to stream.
3. Use VLC player to view http://127.0.0.1/live/test_ff.m3u8, occasionally there may be screen glitches.

srs.conf
```
# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          80;
    dir             /video;
}

stats {
    network         0;
    disk            sda sdb xvda xvdb;
}

vhost __defaultVhost__ {


     hls {
		  enabled         on;
		  hls_fragment    5;
		  hls_window      20;
		  hls_dispose     300;
		  hls_cleanup     on;
		  hls_path        /video;
		  hls_m3u8_file   [app]/[stream].m3u8;
		  hls_ts_file     [app]/[stream]-[seq].ts;
        }

    transcode live  {
        enabled     on;
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine ff {
            enabled         on;
            vfilter {
                v           quiet;
            #    vsync       1;
            }
            vcodec          libx264;
            vbitrate        1024;
            vfps            25;
            vwidth          960;
            vheight         540;
            vthreads        12;
            vprofile        main;
            vpreset         ultrafast;
            vparams {
             tune zerolatency;
            }
            acodec          copy;
            aparams {
            }
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream]_[engine];
        }
    }
}
```

`TRANS_BY_GPT3`

**Comment by jinguanzhu** [comment]
[`我这边也出现这种花屏现象。使用srs-librtmp进行推流，使用这里的h264推流demo进行推流，帧率30`](url) ，https://github.com/ossrs/srs/tree/2.0release/trunk/research/librtmp      @##[推doc中的h264文件没有播放顺畅，使用我自己的h264视频流进行播放，出现这种花屏现象，请博主帮我看看这个h264文件是不是有什么问题？

**Comment by jinguanzhu** [comment]
I am also experiencing this screen flickering phenomenon. I am using srs-librtmp for streaming and pushing the h264 stream from [demo] here at a frame rate of 30 (https://github.com/ossrs/srs/tree/2.0release/trunk/research/librtmp). The h264 file mentioned in the documentation does not play smoothly, and when I try to play my own h264 video stream, I encounter this screen flickering issue. I suspect that the h264 video is lacking I-frames. Could you please help me check if there is any problem with this h264 file? (I have uploaded the file with a .txt extension).
[h264data.txt](https://github.com/ossrs/srs/files/892263/h264data.txt)


`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
You need to open a new Issue, which only solves the problem of screen flickering in HLS after FFMPEG transcoding. @jinguanzhu

`TRANS_BY_GPT3`

**Comment by nanguantong** [comment]
On my side, there is also screen flickering. The screen flickers when switching different sources to the same output during the ingest process.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
花屏是FFMPEG的问题，目前已经更新到了FFMPEG4.1，可以在srs-docker中用二进制。'

Translation:
'Flashing screen is an issue with FFMPEG. It has now been updated to FFMPEG 4.1 and can be used in srs-docker with binary.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Dup to https://github.com/ossrs/srs/issues/1641

After switching the codec header, it should cause HLS to be unrecoverable, even refreshing the player won't work.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed
