### ISSUE TITLE
观看一段时间后刷新浏览器会黑屏

### ISSUE THREAD

**Issue by sawachika-kenji** [ossrs/srs#804]
centos6.8 
2.0r0 release(2.0.234)
全部默认配置没改过任何东西，使用 ./objs/srs -c conf/realtime.conf 启动的服务器，OBS推流，可以正常观看，但是观看一段时间后刷新浏览器，播放就会黑屏，但是有声音，使用srs播放器和163的rtmp播放器（http://vcloud.163.com/demo/player.html）都试过，请问是什么原因如何解决？

**Comment by winlinvip** [comment]
请给出详细的重现步骤。是否每次必现？

**Comment by sawachika-kenji** [comment]
详细的重现步骤就是装好系统，没有修改任何设置，然后下载http://www.ossrs.net/srs.release/releases/files/SRS-CentOS6-x86_64-2.0.234.zip 解压，通过 ./objs/srs -c conf/realtime.conf 启动srs，OBS相关设置：http://imgur.com/a/F7HSx
服务器是阿里云的，观看几分钟后刷新浏览器，只有音频没有画面，使用srs播放器和163的rtmp播放器都是一样的问题，OBS停止推流然后再开启推流后会恢复正常，需要的话我可以提供一台阿里云服务器以供测试

**Comment by winlinvip** [comment]
我先试试，看能不能重现。

**Comment by gaoxianrui52** [comment]
我用ffmpeg中继了一个源，在用videos.js播放时也会遇到相同问题，几乎每10次刷新就会有一次以上的黑屏，通过带宽跟抓包看，播放器还是有不断拉流的，能听到声音。用vlc等播放器就没问题。

**Comment by winlinvip** [comment]
Can't replay.
