### ISSUE TITLE
DVR: SRS3 录制mp4文件的一些问题

### ISSUE THREAD

**Issue by sky173795520** [ossrs/srs#806]
1）使用srs录制来下的mp4文件使用迅雷不可以播放，后来我把SrsMp4FileTypeBox::set_compatible_brands方法的nb_compatible_brands改成3后，迅雷播放器就可以播放了
2）使用srs录制来下的mp4文件在win 10上无法生成预览图出来

**Comment by sky173795520** [comment]
3）修改nb_compatible_brands为3后，使用kmplayer还是播不了，kmplayer直接崩溃

**Comment by zachry-zhang** [comment]
mp4这块应该还不太完善。
我推流录制的mp4文件VLC、QQ影音、迅雷影音可以播，windows media player、QuickTime、KMPlayer放不了。
不过html5的Video标签可以放，暂时够用。^_^

**Comment by sky173795520** [comment]
第一点是经过测试，确认是我这边搞错了，是因为没有填写宽高导致的

**Comment by winlinvip** [comment]
有些MP4的BOX没有加进去，可以对比下FFMPEG的box。
你们有空多帮忙试试，看需要怎么弄。我现在每周的一点点时间，只够回复issues。
DASH估计都还要几周。。。

**Comment by winlinvip** [comment]
Dup to #1105
