### ISSUE TITLE
少了 --with-http-server 觸發編譯錯誤

### ISSUE THREAD

**Issue by s25g5d4** [ossrs/srs#810]
抱歉我知道這個問題有點蠢... 完全是我自己的問題
不過鑒於我折騰了一個晚上才搞定它
希望您能在文件中註明一下我碰到的問題

事情是這樣的，我嘗試在 Ubuntu 16.04.1 LTS 編譯 srs v2.0 r0
我照著 Wiki 文件執行，並以以下選項設定編譯參數
```
./configure --rtmp-hls --with-ffmpeg --with-transcode --with-stream-caster \
--with-http-callback --with-http-api --with-stat --jobs=4
```
而後使用 `make -j4` 編譯 srs, 接著便是一連串的
```
src/app/srs_app_http_conn.cpp:1382:16: error: invalid use of incomplete type ‘class SrsHttpStreamServer’
     http_stream->http_unmount(s, r);
                ^
In file included from src/app/srs_app_http_conn.cpp:24:0:
src/app/srs_app_http_conn.hpp:70:7: note: forward declaration of ‘class SrsHttpStreamServer’
 class SrsHttpStreamServer;
       ^
```

於是我就看起了 srs_app_http_conn.cpp,
確定有 include <srs_app_http_stream.hpp> 後，
打開 srs_app_http_stream.hpp, 發現有這一行
```
#ifdef SRS_AUTO_HTTP_SERVER
```

我才知道是我的 configure 參數缺少了 --with-http-server
最後以
```
./configure --rtmp-hls --with-ffmpeg --with-transcode --with-stream-caster \
--with-http-server --with-http-callback --with-http-api --with-stat --jobs=4
```
編譯成功了

希望您能在文件中註明開啟 --with-http-* 參數時，
必須同時開啟 --with-http-server 參數

謝謝收看

**Comment by winlinvip** [comment]
在SRS3中，HTTP Server和API都是不可配置的选项，是系统的核心功能。
所以这个功能在SRS3中会彻底解决。
