### ISSUE TITLE
develop加上编译选项--log-info --log-verbose后报错

### ISSUE THREAD

**Issue by zachry-zhang** [ossrs/srs#812]
develop分支.
编译指令: ./configure --log-info --log-verbose && make
configure正常, make时抛错.

错误日志如下:
g++ -c -ansi -Wall -g -O0  -Isrc/kernel -Isrc/core  -Iobjs \
          -o objs/src/kernel/srs_kernel_codec.o src/kernel/srs_kernel_codec.cpp
In file included from src/kernel/srs_kernel_codec.cpp:31:0:
src/kernel/srs_kernel_codec.cpp: 在成员函数‘virtual int SrsFormat::video_avc_demux(SrsBuffer*, int64_t)’中:
src/kernel/srs_kernel_codec.cpp:717:26: 错误：‘video_codec_id’在此作用域中尚未声明
              frame_type, video_codec_id, avc_packet_type, composition_time, size);
                          ^
src/kernel/srs_kernel_log.hpp:140:87: 附注：in definition of macro ‘srs_info’
     #define srs_info(msg, ...)    _srs_log->info(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
                                                                                       ^
src/kernel/srs_kernel_codec.cpp:717:77: 错误：‘size’在此作用域中尚未声明
              frame_type, video_codec_id, avc_packet_type, composition_time, size);
                                                                             ^
src/kernel/srs_kernel_log.hpp:140:87: 附注：in definition of macro ‘srs_info’
     #define srs_info(msg, ...)    _srs_log->info(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
                                                                                       ^
src/kernel/srs_kernel_codec.cpp: 在成员函数‘virtual int SrsFormat::audio_aac_demux(SrsBuffer*, int64_t)’中:
src/kernel/srs_kernel_codec.cpp:1353:74: 错误：‘size’在此作用域中尚未声明
              sound_type, codec_id, sound_size, sound_rate, sound_format, size);
                                                                          ^
src/kernel/srs_kernel_log.hpp:140:87: 附注：in definition of macro ‘srs_info’
     #define srs_info(msg, ...)    _srs_log->info(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
                                                                                       ^
src/kernel/srs_kernel_codec.cpp: 在成员函数‘virtual int SrsFormat::audio_mp3_demux(SrsBuffer*, int64_t)’中:
src/kernel/srs_kernel_codec.cpp:1398:94: 错误：‘class SrsAudioCodecConfig’没有名为‘acodec’的成员
              acodec->sound_type, acodec->id, acodec->sound_size, acodec->sound_rate, acodec->acodec, size);
                                                                                              ^
src/kernel/srs_kernel_log.hpp:140:87: 附注：in definition of macro ‘srs_info’
     #define srs_info(msg, ...)    _srs_log->info(NULL, _srs_context->get_id(), msg, ##__VA_ARGS__)
                                                                                       ^
make[2]: *** [objs/src/kernel/srs_kernel_codec.o] 错误 1

**Comment by winlinvip** [comment]
Fixed.
