### ISSUE TITLE
是否支持多网卡

### ISSUE THREAD

**Issue by DyncEric** [ossrs/srs#814]
今天遇到了这个问题，就是Linux服务器有多个网卡，一个网卡100M带宽想充分利用，这样可以省掉不少服务器。
SRS是否能够绑定多个网卡使用呢？

**Comment by winlinvip** [comment]
可以用[go-oryx](https://github.com/ossrs/go-oryx)启动多个SRS Edge，然后回源。绑定网卡linux应该可以通过绑定中断到进程的方式实现。
