### ISSUE TITLE
arm平台运行出错Illegal instruction

### ISSUE THREAD

**Issue by sxp-ilinkin** [ossrs/srs#824]
Program received signal SIGILL, Illegal instruction.
[Switching to Thread 0x4648d490 (LWP 1597)]
0x000870c8 in srs_is_little_endian () at src/kernel/srs_kernel_utility.cpp:238
238     src/kernel/srs_kernel_utility.cpp: No such file or directory.

gdb调试结果，arm TI DM365，交叉编译工具arm-none-linux-gnueabi-gcc

**Comment by winlinvip** [comment]
Please use SRS3.
