### ISSUE TITLE
通过as3写的代码无法播放srs的rtmp，可是用vlc确实正常的

### ISSUE THREAD

**Issue by jonahzheng** [ossrs/srs#825]
以下是as3写的播放rtmp的代码，已连接成功，但就是无法出现画面。用工具vlc可以正常播放，说明srs服务应该正常的
`package {  
    import flash.display.Sprite;  
    import flash.net.NetConnection;  
    import flash.events.NetStatusEvent;  
    import flash.events.AsyncErrorEvent;  
    import flash.net.NetStream;  
    import flash.media.Video;  
  
  
    public class simplest_as3_rtmp_player extends Sprite  
    {  
        var nc:NetConnection;  
        var ns:NetStream;  
        var video:Video;  
  
  
        public function simplest_as3_rtmp_player()  
        {  
            nc = new NetConnection();  
            nc.addEventListener(NetStatusEvent.NET_STATUS, netStatusHandler);  
            nc.connect("rtmp://192.168.1.80/live/livestream");  
        }   
  
        private function netStatusHandler(event:NetStatusEvent):void  
        {  
            trace("event.info.level: " + event.info.level + "\n", "event.info.code: " + event.info.code);  
            switch (event.info.code)  
            {  
                case "NetConnection.Connect.Success":  
                    doVideo(nc);  
                    break;  
                case "NetConnection.Connect.Failed":  
                    break;  
                case "NetConnection.Connect.Rejected":  
                    break;  
                case "NetStream.Play.Stop":  
                    break;  
                case "NetStream.Play.StreamNotFound":  
                    break;  
            }  
        }  
  
  
  
  
        // play a recorded stream on the server  
        private function doVideo(nc:NetConnection):void {  
            ns = new NetStream(nc);  
            ns.addEventListener(NetStatusEvent.NET_STATUS, netStatusHandler);  
  
  
            video = new Video(640,480);  
            video.attachNetStream(ns);  
  
  
            ns.play("myCamera");  
            addChild(video);  
        }  
  
  
        // create a playlist on the server  
        /*  
        private function doPlaylist(nc:NetConnection):void {  
            ns = new NetStream(nc);  
            ns.addEventListener(NetStatusEvent.NET_STATUS, netStatusHandler);  
  
  
            video = new Video();  
            video.attachNetStream(ns);  
  
  
            // Play the first 3 seconds of the video  
            ns.play( "bikes", 0, 3, true );  
            // Play from 20 seconds on  
            ns.play( "bikes", 20, -1, false);  
            // End on frame 5  
            ns.play( "bikes", 5, 0, false );  
            addChild(video);  
        }  
        */  
    }  
}  `

**Comment by winlinvip** [comment]
What happend?
