### ISSUE TITLE
KERNEL: 在stream_caster功能模块，未释放SrsConnection连接对象

### ISSUE THREAD

**Issue by haofz** [ossrs/srs#826]
条件： 编译启用--with-stream-caster模块，且配置中打开stream_caster监听8936端口

复现：在阿里云主机的SLB后搭建srs，SLB每秒扫描8936端口，导致内存泄漏。后来自己写脚本扫描测试，
```for循环执行： curl -m 1 127.0.0.1:8936/; ```，内存泄漏约一分钟1Mb。

原因：stream_caster功能模块的连接对象在结束后未被释放，见
```
void SrsAppCasterFlv::remove(SrsConnection* c)  
{  
    std::vector<SrsHttpConn*>::iterator it;
    if ((it = std::find(conns.begin(), conns.end(), c)) != conns.end()) {
        conns.erase(it);
    }
}
```
应在此处释放SrsConnection对象： `srs_freep(c);`

如有理解纰漏，还望指正。

**Comment by winlinvip** [comment]
👍 Please file a PR to fix it.

**Comment by haofz** [comment]
Okay, the PR has been submitted.

`TRANS_BY_GPT3`
