### ISSUE TITLE
SrsConsumer 的SrsMessageQueue在溢出时，会清除所有msg，这样造成客户端接收出现马赛克

### ISSUE THREAD

**Issue by wanstonq** [ossrs/srs#827]
建议在清除队列后，视频再次插入时，要判断第一帧是否为KeyFrame

如果第一帧非关键帧，则解码造成马赛克

**Comment by winlinvip** [comment]
When the queue overflows, it is a very rare event. At this time, the network has already encountered major issues, and the server can handle it easily. Because no matter how it is handled, there will be problems, and the client may refresh the page because the network is too poor.

`TRANS_BY_GPT3`
