### ISSUE TITLE
STREAM: Clear the gop cache when publish stopped.

### ISSUE THREAD

**Issue by henmaodun** [ossrs/srs#829]
边缘服务器http-flv停止推流以后，画面静止在最后一秒。当再次访问这个推流地址时，会重复播放最后一秒的画面。如何在停止推流以后清除最后一秒的播放画面？源服务器不会出现这个问题，但是源服务器会有大量的close_wait。 边缘服务器不会生成close_wait会一直保持ESTABLISHED 状态

**Comment by winlinvip** [comment]
Turn off GOP cache.

`TRANS_BY_GPT3`

**Comment by henmaodun** [comment]
If the gop cache is disabled, instant loading cannot be achieved. If the keyframe is set to 1 on OBS, although the initial screen can be opened faster, there will be stuttering during the live streaming process. If OBS is set to 0, there will be a black screen for a while, resulting in a poor user experience. Is it possible to delete the cache after stopping the live streaming when gop cache is enabled?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This feature seems reasonable and can be considered in SRS3.

`TRANS_BY_GPT3`

**Comment by henmaodun** [comment]
I am using the latest version 239. The edge server cannot generate m3u8 slices during live streaming, but the source server can play m3u8. It seems that this version has already cleared the cache. Is it possible to make the screen go black after clearing the cache and interrupting the stream? Currently, it stays on the last frame.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Edge does not support HLS, please carefully read the WIKI.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/5d365bade862d121cad780aa57657bef5ed1d3e0
