### ISSUE TITLE
PROTOCOL: 未来能否支持WebSocket协议

### ISSUE THREAD

**Issue by langhuihui** [ossrs/srs#831]
本人开发了一个在网页上播放流媒体的客户端（利用js来解析音视频）是用websocket来连接服务器的，服务器是在MonaServer基础上修改而成，但有内存泄露问题一直解决不了，srs貌似很强大，但没有websocket协议，我看源码，也不知道如何添加进去，或者能给个说明，该如何扩展，谢谢

**Comment by winlinvip** [comment]
FLV over websocket: https://github.com/winlinvip/videojs-flow/blob/master/demo/mse.go
I write a proxy to convert HTTP-FLV to websocket, and the bilibili player https://github.com/Bilibili/flv.js#features can play it.

**Comment by winlinvip** [comment]
Reference example of converting HTTP-FLV to WS-FLV: https://github.com/ossrs/srs/issues/1576#issuecomment-574963151

`TRANS_BY_GPT3`
