### ISSUE TITLE
srs player这个播放器有开源吗

### ISSUE THREAD

**Issue by jonahzheng** [ossrs/srs#835]

**Comment by haofz** [comment]
I would like to help the author answer the following:

'srs/trunk/research/players/srs_player/src/srs_player.as' - AS3 source code
In conjunction with the JavaScript code in 'srs/trunk/research/players/srs_player.html'.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
👍 @haofz, it would be perfect if you provide the link.

`TRANS_BY_GPT3`

**Comment by haofz** [comment]
Haha, added:
as source code:
https://github.com/ossrs/srs/blob/2.0release/trunk/research/players/srs_player/src/srs_player.as
The HTML and JS code is in the folder below:
https://github.com/ossrs/srs/tree/2.0release/trunk/research/players

`TRANS_BY_GPT3`
