### ISSUE TITLE
边缘服务器在播放http-flv 或者rtmp时黑屏

### ISSUE THREAD

**Issue by henmaodun** [ossrs/srs#837]
手机APP是使用金山播放器。当客户端提前进入直播课程以后，然后通过obs进行推流。APP接收到流播放时，有时会黑屏。只有声音，没有画面

**Comment by winlinvip** [comment]
试试用SRS player是否有这个问题。
另外，最好找到能一定重现的方法，不然只能猜测，解决不了问题。

**Comment by Chand-zhang** [comment]
金山播放器本身有这个现象，需要runBack  runFore切换一下 ^_^

**Comment by winlinvip** [comment]
什么导致的？

**Comment by winlinvip** [comment]
Closed for no reply.
