### ISSUE TITLE
~SrsConnection()的时候coredump，原因是srs_close_stfd时fd上的事件没有清空。请问如何修改？

### ISSUE THREAD

**Issue by businiaowyf** [ossrs/srs#850]
我的程序经常在~SrsConnection()的时候coredump， 原因是srs_close_stfd()时fd上的事件没有清空。
查看了代码， 是因为在~SrsConnection()时没有在dispose前调用pthread->stop()。 

SrsConnection::SrsConnection(IConnectionManager* cm, st_netfd_t c)
{
    id = 0;
    manager = cm;
    stfd = c;
    disposed = false;
    expired = false;
    
    **// the client thread should reap itself, 
    // so we never use joinable.
    // TODO: FIXME: maybe other thread need to stop it.
    // @see: https://github.com/ossrs/srs/issues/78**
    pthread = new SrsOneCycleThread("conn", this);
}

SrsConnection::~SrsConnection()
{
    dispose();
    
    srs_freep(pthread);
}

修改方案：
1. 在~SrsConnection()中手动调用pthread->stop()
2.去掉srs_close_stfd()里面的assert判断。 

想请问下哪种方案比较好， 为什么srs_close_stfd里要用assert来保证监听事件被清空， 这里有什么坑吗？

**Comment by winlinvip** [comment]
你的call stack是什么？不能粗暴的直接关闭fd，而是要等线程退出后，才能close(fd)

**Comment by winlinvip** [comment]
Closed for no reply.
