### ISSUE TITLE
int SrsAmf0EcmaArray::write(SrsStream* stream)可能有问题

### ISSUE THREAD

**Issue by wanstonq** [ossrs/srs#852]
第930行 stream->write_4bytes(this->_count);

this->_count一直为0，没有变化，是否应该是this->count()？

**Comment by winlinvip** [comment]
In fact, AMF0 ECMA ARRAY does not rely on count, but uses EOF to determine, so in fact, this count is not used. You can see that the packages sent by FLASH or FMLE are all 0.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is WAF Adobe protocols. 😭
