### ISSUE TITLE
这个能配合flv.js吗？

### ISSUE THREAD

**Issue by xxfaxy** [ossrs/srs#855]
在哪里设置flv.js所要求的跨域配置啊？

**Comment by Chand-zhang** [comment]
3.0支持。

http_server {
    # whether enable crossdomain request.
    # for both http static and stream server and apply on all vhosts.
    # default: on
    crossdomain     on;
}

**Comment by KrisRoofe** [comment]
使用flv.js 播放flv时，出现跨域问题。 在[srs_app_http_stream.cpp#485](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_http_stream.cpp#L485)后添加`w->header()->set("Access-Control-Allow-Origin", "*");`来设置`Access-Control-Allow-Origin`即可。为安全起见，`*`可以具体设置。

**Comment by KrisRoofe** [comment]
参考这里   https://github.com/ossrs/srs/issues/798
