### ISSUE TITLE
播放器反复请求不存在的http-flv流，会造成fd leak

### ISSUE THREAD

**Issue by walkermi** [ossrs/srs#858]
1、2.0release分支，此时最新代码。
2、编译
     ./configure --full --without-ffmpeg --without-nginx  
3、conf文件
     `listen              1935;
max_connections     8000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
#daemon              on;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          80;
    dir             /usr/local/srs/objs/hls;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       /[app]/[stream].flv;
        hstrs       on;
    }
}`
5、不推送任何流，用测试播放器ffplay反复打开关闭http://xxx.xxx.xxx.xxx/app/1.flv
6、close_wait数量每打开关闭一次播放，均会增长。
7、https://github.com/ossrs/srs/blob/a37a14377a9a38e245aed16d7a651217249c0baf/trunk/src/app/srs_app_http_stream.cpp#L557
8、在这里循环无法跳出
![image](https://cloud.githubusercontent.com/assets/1332874/25337128/1fa52ed2-292d-11e7-80ce-27ea5721be21.png)

**Comment by walkermi** [comment]
It seems to be the same issue as #636, although it has a backtrace. Similarly, serve_http cannot break out of the loop.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
dup to #636

**Comment by walkermi** [comment]
#633 The same issue also occurs when the player requests a non-existent http-flv, resulting in a large number of close_wait.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Duplicated to #636 
#636 has been duplicated, it will be addressed in that issue, so this one can be closed.

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
hstrs off;

Setting this configuration item seems to prevent close_wait from continuously increasing. @winlinvip

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This feature has been removed and will be removed during configuration parsing by default. If you find it still useful, you can raise another bug separately.

`TRANS_BY_GPT3`

**Comment by rageJune** [comment]
The phenomenon still exists, repeatedly pulling disconnected non-existent flv streams will increase the close_wait, and it will be included in the statistics of clients.

srs version: 3.0.45
Configuration file: conf/http.flv.live.conf

![51233031-b0ea0080-19a3-11e9-923d-55d3d8059be6](https://user-images.githubusercontent.com/30453799/51233268-661cb880-19a4-11e9-85bf-fab56d74ff65.png)
![image](https://user-images.githubusercontent.com/30453799/51233049-c3fcd080-19a3-11e9-83f9-ec0fd9fdbe53.png)
![image](https://user-images.githubusercontent.com/30453799/51233153-1d64ff80-19a4-11e9-99e2-54e346ab29a9.png)

`TRANS_BY_GPT3`

**Comment by rageJune** [comment]
Also tested the situation in cluster mode:
`
## edge.conf
listen              1935;
max_connections     1000;
pid                 objs/edge.pid;
daemon              off;
srs_log_tank        console;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    cluster {
        mode            remote;
        origin          127.0.0.1:19350;
    }
    http_remux {
        enabled     on;
        mount       [app]/[stream].flv;
        hstrs       on;
    }
}
`
After pulling a non-existent FLV stream and disconnecting, the connection between origin and edge is still being repeatedly established.
![image](https://user-images.githubusercontent.com/30453799/51233847-fd364000-19a5-11e9-94b1-200b2002c4b9.png)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs/commit/f2b4bc7110a6f4d6390211001a395fdd2de07b25
