### ISSUE TITLE
APPLICATION: 当使用http-flv播放时，调用srs http api查看流量统计不对，客户端连接数是对的

### ISSUE THREAD

**Issue by xialixin** [ossrs/srs#863]
当使用http-flv播放时，查看流量统计不对，send_bytes, kbps.send_30s两个参数一定数后一直不会增加，客户端连接是对的
查看了srs代码，发现在http-flv相关代码中统计代码
```
int SrsLiveStream::serve_http(ISrsHttpResponseWriter* w, ISrsHttpMessage* r)
{   ...
    // update the statistic when source disconveried.
    SrsStatistic* stat = SrsStatistic::instance();
    if ((ret = stat->on_client(_srs_context->get_id(), req, NULL, SrsRtmpConnPlay)) != ERROR_SUCCESS) {
        srs_error("stat client failed. ret=%d", ret);
        return ret;
    }
   ...
}
```
继续跟踪代码在SrsHttpConn中相关流量统计代码如下
```
void SrsHttpConn::resample()
{
    // TODO: FIXME: implements it
}

int64_t SrsHttpConn::get_send_bytes_delta()
{
    // TODO: FIXME: implements it
    return 0;
}

int64_t SrsHttpConn::get_recv_bytes_delta()
{
    // TODO: FIXME: implements it
    return 0;
}

void SrsHttpConn::cleanup()
{
    // TODO: FIXME: implements it
}
```
SrsHttpConn,SrsRtmpConn的基类都是SrsConnection。 在SrsConnection类中调用了SrsKbps。为了验让是否跟上面代码有关, 直接将上面代码修改如下，调用基类SrsConnection中的相关方法
```
void SrsHttpConn::resample()
{
    SrsConnection::resample()
}

int64_t SrsHttpConn::get_send_bytes_delta()
{
    return SrsConnection::get_send_bytes_delta()
}

int64_t SrsHttpConn::get_recv_bytes_delta()
{
    return SrsConnection::get_recv_bytes_delta();
}
void SrsHttpConn::cleanup()
{
     SrsConnection::cleanup()
}
```
重新编译后，启动srs,然后能过api查看相关参数，send_bytes,kbps.send_30s两个参数都一直在增加。
以上是测试过程中发现问题，提出来供大家参考。

**Comment by winlinvip** [comment]
I will find time to take a look at why it was necessary to rewrite the base class for bandwidth statistics at that time.

`TRANS_BY_GPT3`

**Comment by superxrb** [comment]
The number of client connections has shown an incorrect situation. The steps are as follows:

1. Play a non-existent stream using VLC, for example, http://192.168.177.181:8080/live/952700000A5S348E_0_ext.flv. At this time, the statistics at http://192.168.177.181:1985/api/v1/streams/ are correct, with "clients" being 1.

2. Forcefully close VLC and check the statistics again. The statistics remain unchanged, with "clients" still being 1.

3. Repeat the above two steps using the RTMP streaming method. It is found that in the second step, the statistics are correct, with "clients" being 0.

`TRANS_BY_GPT3`

**Comment by RocFang** [comment]
@xialixin 
Hello, how did you handle this issue later on? If your solution works, please create a pull request for winlin. :)

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
See https://github.com/ossrs/srs/issues/1657

**Comment by winlinvip** [comment]
Fixed.
