### ISSUE TITLE
API - get connected listeners and other stats

### ISSUE THREAD

**Issue by moster67** [ossrs/srs#864]
I am using the SRS in it is most simple mode i.e. set up using the RTMP deploy example. It is working incredibly nice!
Now, I wonder if it is possible to rebuild SRS using the RTMP deploy example and adding HTTP API so I can query connected listeners/clients? If yes, what is the correct command for building and starting server with HTTP API enabled?
Many thanks in advance for your help.

**Comment by moster67** [comment]
Sorry for bumping. Any help on my earlier question?

**Comment by notmark** [comment]
I would like the same feature, much like the nginx_rtmp_live stat module.

**Comment by Chand-zhang** [comment]
All of HTTP API is here [HTTP API](https://github.com/ossrs/srs/wiki/v2_EN_HTTPApi)

**Comment by winlinvip** [comment]
Strongly recommend to read all WIKIs of SRS, because we can find answers for almost all questions.
