### ISSUE TITLE
srs边缘服务器服务停止，错误详见内容

### ISSUE THREAD

**Issue by henmaodun** [ossrs/srs#866]
May  1 10:15:35 localhost kernel: srs invoked oom-killer: gfp_mask=0x200da, order=0, oom_adj=0, oom_score_adj=0
May  1 10:15:35 localhost kernel: srs cpuset=/ mems_allowed=0
May  1 10:15:35 localhost kernel: Pid: 10711, comm: srs Not tainted 2.6.32-431.el6.x86_64 #1
May  1 10:15:35 localhost kernel: Call Trace:
May  1 10:15:35 localhost kernel: [<ffffffff810d05b1>] ? cpuset_print_task_mems_allowed+0x91/0xb0
May  1 10:15:35 localhost kernel: [<ffffffff81122960>] ? dump_header+0x90/0x1b0
May  1 10:15:35 localhost kernel: [<ffffffff8122798c>] ? security_real_capable_noaudit+0x3c/0x70
May  1 10:15:35 localhost kernel: [<ffffffff81122de2>] ? oom_kill_process+0x82/0x2a0
May  1 10:15:35 localhost kernel: [<ffffffff81122d21>] ? select_bad_process+0xe1/0x120
May  1 10:15:35 localhost kernel: [<ffffffff81123220>] ? out_of_memory+0x220/0x3c0
May  1 10:15:35 localhost kernel: [<ffffffff8112fb3c>] ? __alloc_pages_nodemask+0x8ac/0x8d0
May  1 10:15:35 localhost kernel: [<ffffffff81167b9a>] ? alloc_pages_vma+0x9a/0x150
May  1 10:15:35 localhost kernel: [<ffffffff8115b872>] ? read_swap_cache_async+0xf2/0x160
May  1 10:15:35 localhost kernel: [<ffffffff8115c399>] ? valid_swaphandles+0x69/0x150
May  1 10:15:35 localhost kernel: [<ffffffff8115b967>] ? swapin_readahead+0x87/0xc0
May  1 10:15:35 localhost kernel: [<ffffffff8114ac3d>] ? handle_pte_fault+0x6dd/0xb00
May  1 10:15:35 localhost kernel: [<ffffffff8122f864>] ? inode_has_perm+0x54/0xa0
May  1 10:15:35 localhost kernel: [<ffffffff8114b28a>] ? handle_mm_fault+0x22a/0x300
May  1 10:15:35 localhost kernel: [<ffffffff8104a8d8>] ? __do_page_fault+0x138/0x480
May  1 10:15:35 localhost kernel: [<ffffffff8118e7b4>] ? cp_new_stat+0xe4/0x100
May  1 10:15:35 localhost kernel: [<ffffffff812334eb>] ? selinux_file_permission+0xfb/0x150
May  1 10:15:35 localhost kernel: [<ffffffff8152d45e>] ? do_page_fault+0x3e/0xa0
May  1 10:15:35 localhost kernel: [<ffffffff8152a815>] ? page_fault+0x25/0x30
May  1 10:15:35 localhost kernel: Mem-Info:
May  1 10:15:35 localhost kernel: Node 0 DMA per-cpu:
May  1 10:15:35 localhost kernel: CPU    0: hi:    0, btch:   1 usd:   0
May  1 10:15:35 localhost kernel: CPU    1: hi:    0, btch:   1 usd:   0
May  1 10:15:35 localhost kernel: CPU    2: hi:    0, btch:   1 usd:   0
May  1 10:15:35 localhost kernel: CPU    3: hi:    0, btch:   1 usd:   0
May  1 10:15:35 localhost kernel: Node 0 DMA32 per-cpu:
May  1 10:15:35 localhost kernel: CPU    0: hi:  186, btch:  31 usd:   7
May  1 10:15:35 localhost kernel: CPU    1: hi:  186, btch:  31 usd:  48
May  1 10:15:35 localhost kernel: CPU    2: hi:  186, btch:  31 usd:   9
May  1 10:15:35 localhost kernel: CPU    3: hi:  186, btch:  31 usd:  52
May  1 10:15:35 localhost kernel: Node 0 Normal per-cpu:
May  1 10:15:35 localhost kernel: CPU    0: hi:   42, btch:   7 usd:   7
May  1 10:15:35 localhost kernel: CPU    1: hi:   42, btch:   7 usd:   5
May  1 10:15:35 localhost kernel: CPU    2: hi:   42, btch:   7 usd:   2
May  1 10:15:35 localhost kernel: CPU    3: hi:   42, btch:   7 usd:   6
May  1 10:15:35 localhost kernel: active_anon:760196 inactive_anon:151824 isolated_anon:32
May  1 10:15:35 localhost kernel: active_file:20 inactive_file:720 isolated_file:0
May  1 10:15:35 localhost kernel: unevictable:0 dirty:1 writeback:0 unstable:0
May  1 10:15:35 localhost kernel: free:21411 slab_reclaimable:3976 slab_unreclaimable:16365
May  1 10:15:35 localhost kernel: mapped:77 shmem:0 pagetables:10692 bounce:0
May  1 10:15:35 localhost kernel: Node 0 DMA free:15688kB min:248kB low:308kB high:372kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15292kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
May  1 10:15:35 localhost kernel: lowmem_reserve[]: 0 3896 4022 4022
May  1 10:15:35 localhost kernel: Node 0 DMA32 free:67448kB min:65220kB low:81524kB high:97828kB active_anon:3014820kB inactive_anon:581196kB active_file:0kB inactive_file:2316kB unevictable:0kB isolated(anon):128kB isolated(file):0kB present:3989664kB mlocked:0kB dirty:4kB writeback:0kB mapped:284kB shmem:0kB slab_reclaimable:10076kB slab_unreclaimable:41980kB kernel_stack:1296kB pagetables:40588kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:1975 all_unreclaimable? yes
May  1 10:15:35 localhost kernel: lowmem_reserve[]: 0 0 126 126
May  1 10:15:35 localhost kernel: Node 0 Normal free:2508kB min:2112kB low:2640kB high:3168kB active_anon:25964kB inactive_anon:26100kB active_file:80kB inactive_file:564kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:129280kB mlocked:0kB dirty:0kB writeback:0kB mapped:24kB shmem:0kB slab_reclaimable:5828kB slab_unreclaimable:23480kB kernel_stack:1392kB pagetables:2180kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:122 all_unreclaimable? yes
May  1 10:15:35 localhost kernel: lowmem_reserve[]: 0 0 0 0
May  1 10:15:35 localhost kernel: Node 0 DMA: 2*4kB 4*8kB 2*16kB 2*32kB 3*64kB 0*128kB 0*256kB 0*512kB 1*1024kB 1*2048kB 3*4096kB = 15688kB
May  1 10:15:35 localhost kernel: Node 0 DMA32: 584*4kB 1313*8kB 825*16kB 504*32kB 209*64kB 53*128kB 18*256kB 1*512kB 0*1024kB 0*2048kB 0*4096kB = 67448kB
May  1 10:15:35 localhost kernel: Node 0 Normal: 623*4kB 2*8kB 0*16kB 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 2508kB
May  1 10:15:35 localhost kernel: 47298 total pagecache pages
May  1 10:15:35 localhost kernel: 46538 pages in swap cache
May  1 10:15:35 localhost kernel: Swap cache stats: add 125087496, delete 125040958, find 28204685/40519621
May  1 10:15:35 localhost kernel: Free swap  = 4kB
May  1 10:15:35 localhost kernel: Total swap = 4063224kB
May  1 10:15:35 localhost kernel: 1048560 pages RAM
May  1 10:15:35 localhost kernel: 69571 pages reserved
May  1 10:15:35 localhost kernel: 336 pages shared
May  1 10:15:35 localhost kernel: 952261 pages non-shared
May  1 10:15:35 localhost kernel: [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
May  1 10:15:35 localhost kernel: [  492]     0   492     2812        0   0     -17         -1000 udevd
May  1 10:15:35 localhost kernel: [ 1286]     0  1286    23294       29   2     -17         -1000 auditd
May  1 10:15:35 localhost kernel: [ 1311]     0  1311    62659      132   0       0             0 rsyslogd
May  1 10:15:35 localhost kernel: [ 1340]     0  1340     2705       48   1       0             0 irqbalance
May  1 10:15:35 localhost kernel: [ 1354]    32  1354     4759       15   2       0             0 rpcbind
May  1 10:15:35 localhost kernel: [ 1465]    81  1465     8127      209   2       0             0 dbus-daemon
May  1 10:15:35 localhost kernel: [ 1476]     0  1476    41318      122   2       0             0 NetworkManager
May  1 10:15:35 localhost kernel: [ 1480]     0  1480    14516       49   2       0             0 modem-manager
May  1 10:15:35 localhost kernel: [ 1497]    29  1497     5837        1   3       0             0 rpc.statd
May  1 10:15:35 localhost kernel: [ 1523]     0  1523    11250        1   2       0             0 wpa_supplicant
May  1 10:15:35 localhost kernel: [ 1557]     0  1557    47368        1   3       0             0 cupsd
May  1 10:15:35 localhost kernel: [ 1568]     0  1568     1020        0   3       0             0 acpid
May  1 10:15:35 localhost kernel: [ 1577]    68  1577     9688      105   3       0             0 hald
May  1 10:15:35 localhost kernel: [ 1578]     0  1578     5082        1   0       0             0 hald-runner
May  1 10:15:35 localhost kernel: [ 1620]     0  1620     5612        1   0       0             0 hald-addon-inpu
May  1 10:15:35 localhost kernel: [ 1623]    68  1623     4484        1   3       0             0 hald-addon-acpi
May  1 10:15:35 localhost kernel: [ 1643]     0  1643   113073       35   0       0             0 automount
May  1 10:15:35 localhost kernel: [ 1668]     0  1668    16657       25   3     -17         -1000 sshd
May  1 10:15:35 localhost kernel: [ 1676]    38  1676     7685       45   3       0             0 ntpd
May  1 10:15:35 localhost kernel: [ 1756]     0  1756    20327       23   1       0             0 master
May  1 10:15:35 localhost kernel: [ 1770]    89  1770    20389       21   3       0             0 qmgr
May  1 10:15:35 localhost kernel: [ 1780]     0  1780    27579        1   0       0             0 abrtd
May  1 10:15:35 localhost kernel: [ 1799]     0  1799     5385        0   0       0             0 atd
May  1 10:15:35 localhost kernel: [ 1811]     0  1811    15589       13   3       0             0 certmonger
May  1 10:15:35 localhost kernel: [ 1820]     0  1820    33509       47   3       0             0 gdm-binary
May  1 10:15:35 localhost kernel: [ 1825]     0  1825     1016        1   0       0             0 mingetty
May  1 10:15:35 localhost kernel: [ 1827]     0  1827     1016        1   0       0             0 mingetty
May  1 10:15:35 localhost kernel: [ 1829]     0  1829     1016        1   1       0             0 mingetty
May  1 10:15:35 localhost kernel: [ 1831]     0  1831     1016        1   0       0             0 mingetty
May  1 10:15:35 localhost kernel: [ 1834]     0  1834     3125        0   0     -17         -1000 udevd
May  1 10:15:35 localhost kernel: [ 1836]     0  1836     1016        1   1       0             0 mingetty
May  1 10:15:35 localhost kernel: [ 1851]     0  1851    41205        1   2       0             0 gdm-simple-slav
May  1 10:15:35 localhost kernel: [ 1854]     0  1854    53662     1643   0       0             0 Xorg
May  1 10:15:35 localhost kernel: [ 1868]     0  1868   521231       57   1       0             0 console-kit-dae
May  1 10:15:35 localhost kernel: [ 1938]    42  1938     5010        0   0       0             0 dbus-launch
May  1 10:15:35 localhost kernel: [ 1944]     0  1944    12470       56   0       0             0 devkit-power-da
May  1 10:15:35 localhost kernel: [ 1984]     0  1984    13168       79   3       0             0 polkitd
May  1 10:15:35 localhost kernel: [ 1995]   499  1995    42114        8   1       0             0 rtkit-daemon
May  1 10:15:35 localhost kernel: [ 2000]     0  2000    48048        1   1       0             0 gdm-session-wor
May  1 10:15:35 localhost kernel: [63495]     0 63495    57254        1   0       0             0 gnome-keyring-d
May  1 10:15:35 localhost kernel: [63505]     0 63505    63427       88   2       0             0 gnome-session
May  1 10:15:35 localhost kernel: [63513]     0 63513     5010        0   1       0             0 dbus-launch
May  1 10:15:35 localhost kernel: [63514]     0 63514     8077        1   2       0             0 dbus-daemon
May  1 10:15:35 localhost kernel: [63574]     0 63574    33494      676   3       0             0 gconfd-2
May  1 10:15:35 localhost kernel: [63581]     0 63581   128919      626   0       0             0 gnome-settings-
May  1 10:15:35 localhost kernel: [63584]     0 63584    73491        1   2       0             0 seahorse-daemon
May  1 10:15:35 localhost kernel: [63588]     0 63588    34352        1   2       0             0 gvfsd
May  1 10:15:35 localhost kernel: [63599]     0 63599     2811        0   3     -17         -1000 udevd
May  1 10:15:35 localhost kernel: [63602]     0 63602    68674        1   1       0             0 gvfs-fuse-daemo
May  1 10:15:35 localhost kernel: [63606]     0 63606    67394       69   3       0             0 metacity
May  1 10:15:35 localhost kernel: [63614]     0 63614    89556      125   0       0             0 gnome-panel
May  1 10:15:35 localhost kernel: [63615]     0 63615   160916        1   1       0             0 nautilus
May  1 10:15:35 localhost kernel: [63617]     0 63617   157769        1   1       0             0 bonobo-activati
May  1 10:15:35 localhost kernel: [63620]     0 63620   128804     1017   2       0             0 gpk-update-icon
May  1 10:15:35 localhost kernel: [63636]     0 63636    88957      133   2       0             0 nm-applet
May  1 10:15:35 localhost kernel: [63637]     0 63637    81912        1   2       0             0 wnck-applet
May  1 10:15:35 localhost kernel: [63639]     0 63639    36640        1   1       0             0 gvfs-gdu-volume
May  1 10:15:35 localhost kernel: [63640]     0 63640    64552       66   0       0             0 gnome-power-man
May  1 10:15:35 localhost kernel: [63645]     0 63645    81170        1   2       0             0 python
May  1 10:15:35 localhost kernel: [63647]     0 63647    80836        1   0       0             0 trashapplet
May  1 10:15:35 localhost kernel: [63649]     0 63649    99360        1   0       0             0 gnome-volume-co
May  1 10:15:35 localhost kernel: [63651]     0 63651    31348        1   2       0             0 im-settings-dae
May  1 10:15:35 localhost kernel: [63653]     0 63653    57521        1   0       0             0 polkit-gnome-au
May  1 10:15:35 localhost kernel: [63654]     0 63654    63939        1   3       0             0 gdu-notificatio
May  1 10:15:35 localhost kernel: [63655]     0 63655    92296        1   3       0             0 pulseaudio
May  1 10:15:35 localhost kernel: [63657]     0 63657    11343       42   1       0             0 udisks-daemon
May  1 10:15:35 localhost kernel: [63658]     0 63658    67156       97   0       0             0 bluetooth-apple
May  1 10:15:35 localhost kernel: [63659]     0 63659    91192       69   3       0             0 evolution-alarm
May  1 10:15:35 localhost kernel: [63663]     0 63663    67601       61   0       0             0 abrt-applet
May  1 10:15:35 localhost kernel: [63667]     0 63667    36055        1   1       0             0 gvfsd-trash
May  1 10:15:35 localhost kernel: [63668]     0 63668    66245      156   0       0             0 gnome-screensav
May  1 10:15:35 localhost kernel: [63671]     0 63671    23807        1   1       0             0 gconf-helper
May  1 10:15:35 localhost kernel: [63673]     0 63673    11277       48   0       0             0 udisks-daemon
May  1 10:15:35 localhost kernel: [63722]     0 63722    58124       13   0       0             0 gvfs-afc-volume
May  1 10:15:35 localhost kernel: [63731]     0 63731    37719        1   2       0             0 gvfs-gphoto2-vo
May  1 10:15:35 localhost kernel: [63735]     0 63735    12028        0   0       0             0 restorecond
May  1 10:15:35 localhost kernel: [63838]     0 63838   105429        1   1       0             0 gdm-user-switch
May  1 10:15:35 localhost kernel: [63840]     0 63840   104460        1   0       0             0 gnote
May  1 10:15:35 localhost kernel: [63843]     0 63843    72862        1   2       0             0 notification-ar
May  1 10:15:35 localhost kernel: [63844]     0 63844   121456      278   2       0             0 clock-applet
May  1 10:15:35 localhost kernel: [63864]     0 63864    37826        1   2       0             0 ibus-daemon
May  1 10:15:35 localhost kernel: [63867]     0 63867    10241        1   2       0             0 gconf-im-settin
May  1 10:15:35 localhost kernel: [63868]     0 63868    39115        1   3       0             0 ibus-gconf
May  1 10:15:35 localhost kernel: [63870]     0 63870    88743        1   2       0             0 python
May  1 10:15:35 localhost kernel: [63872]     0 63872    59163        1   0       0             0 ibus-x11
May  1 10:15:35 localhost kernel: [63875]     0 63875    41334        1   1       0             0 ibus-engine-pin
May  1 10:15:35 localhost kernel: [63885]     0 63885    34372        1   1       0             0 gvfsd-burn
May  1 10:15:35 localhost kernel: [20516]     0 20516    29331       22   1       0             0 crond
May  1 10:15:35 localhost kernel: [10711]     0 10711  1960099   859263   3       0             0 srs
May  1 10:15:35 localhost kernel: [  709]    89   709    20347       16   3       0             0 pickup
May  1 10:15:35 localhost kernel: Out of memory: Kill process 10711 (srs) score 887 or sacrifice child
May  1 10:15:35 localhost kernel: Killed process 10711, UID 0, (srs) total-vm:7840396kB, anon-rss:3437036kB, file-rss:16kB

**Comment by winlinvip** [comment]
内存耗光？这么多文字只能看出内存没有了。
方便的话给完整的信息吧。

**Comment by winlinvip** [comment]
Closed for no reply.
