### ISSUE TITLE
transcode to file and not to rtmp 

### ISSUE THREAD

**Issue by arpu** [ossrs/srs#868]
hello

how can i automatic transcode to file with ffmpeg ? 
the idea is to use srs to automatic  encode to DASH codec (using ffmpeg chunking)
like 
ffmpeg -progress /dev/null -y -vsync passthrough -analyzeduration 2140 -probesize 2140 -i rtmp://localhost:8001/live/teststream -map 0:0 -c:v copy -f webm_chunk -live 1 -audio_chunk_duration 4000 -header /var/www/teststream_sd.webm_tZRYU3GZWoy2QIkr._v.hdr /var/www/teststream_sd.webm_tZRYU3GZWoy2QIkr._v_%d.chk -map 0:1? -c:a copy -f webm_chunk -audio_chunk_duration 4000 -live 1 -vsync 1 -header /var/www/teststream_sd.webm_tZRYU3GZWoy2QIkr._a.hdr /var/www/teststream_sd.webm_tZRYU3GZWoy2QIkr._a_%d.chk

 does this work ?

**Comment by winlinvip** [comment]
Please use DVR: 
https://github.com/ossrs/srs/wiki/v2_EN_DVR
https://github.com/ossrs/srs/wiki/v2_CN_DVR

**Comment by winlinvip** [comment]
If you want to do something when close the DVR segment, use `on_dvr` HTTP callback.
