### ISSUE TITLE
边缘节点大量TIME_WAIT

### ISSUE THREAD

**Issue by zhuashaoweiwu** [ossrs/srs#869]
请问一下,两个源站,两个边缘,边缘在向源站拉流和保持心跳连接时,有大量(边缘节点)TIME_WITE,
srs   版本 v2.0
       linux CentOS6x
srs边缘配置:
    gop_cache       off;
    queue_length    10;
    min_latency     on;
    mr {
        enabled     off;
    }
    enabled         on;
    mw_latency      50;
    mode            remote;
    origin          172.18.21.32:1935 172.18.21.11:1935;
谢谢!

**Comment by zhuashaoweiwu** [comment]
如果快速回收tcp连接,觉得治标不治本,问一下有没有什么高见?谢谢!

**Comment by winlinvip** [comment]
EDGE拉流为何会有这么多的断开的连接？
如果是心跳，为何不用长连接？

**Comment by winlinvip** [comment]
建议用长连接，TIMEWAIT对于短连接是无解的。
