### ISSUE TITLE
有无便利卸载功能, 误删文件后,无法再次编译,

### ISSUE THREAD

**Issue by czboosj** [ossrs/srs#870]
./configure --with-ssl --with-http-api --with-hls --with-http-server  --with-nginx --with-ffmpeg --with-transcode && make
regenerate config: --prefix=/usr/local/srs --with-hls --with-hds --with-dvr --with-nginx --with-ssl --with-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --without-stream-caster --with-http-api --with-librtmp --without-research --with-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --without-arm-ubuntu12 --without-mips-ubuntu12 --log-trace
check gcc/g++/gdb/make
depends tools are ok
OSX detected, install tools if needed
OSX detected, must specifies the --osx

**Comment by wuxianlijiang** [comment]
老人家，你可以重新下载zip报，解压到其他目录重新编译。

**Comment by winlinvip** [comment]
这个错误的说明是`OSX detected, must specifies the --osx`，是用法错误。
