### ISSUE TITLE
关于强制断开连接的问题

### ISSUE THREAD

**Issue by enochi** [ossrs/srs#871]
SrsConnection并没有提供主动断开的接口，继承SrsConnection有SrsRtmpConn和SrsHttpApi 等
SrsRtmpConn单独开了个线程做socket读写，通过停止这个单独的线程达到强制断开的目的。但是像SrsHttpApi等，要是想主动断开，即使是free(SrsHttpApi*)也没法办到吧。
此外像RTSP的连接却没有从SrsConnection里继承，也还是无法安全地通过free(SrsConnection*)达到强制断开的目的。
是不是SrsConnection线程是不是一开始就是不打算在里面读写数据的，或者像HttpConn一样，不能被强制断开？
这些算是不一致吗？

**Comment by winlinvip** [comment]
可以做到断开的，只是目前没有做完善，算一个一致性问题的。

**Comment by winlinvip** [comment]
偏实现细节，合适时会改掉，不放在issue中跟踪。
