### ISSUE TITLE
srsplayer 问题

### ISSUE THREAD

**Issue by zhangfh** [ossrs/srs#872]
在本地打开srs_player.html， 点击播放按钮，弹出模式对话框，然后点击关闭，无法关闭，查看console，发现错误如下：
Uncaught TypeError: this.callbackObj.ref.__stop is not a function
请问这是什么问题

**Comment by zhangfh** [comment]
难道必须部署在服务器上才行，本地运行不行？明天部署到服务器上试试

**Comment by winlinvip** [comment]
放在web服务器下面就可以。

**Comment by zhangfh** [comment]
确实如此，谢谢
