### ISSUE TITLE
webm vp9 support with icecast2 (http) 

### ISSUE THREAD

**Issue by arpu** [ossrs/srs#875]
hello

any plans to support vp9 video codec maybe with icecast2 protocoll?

**Comment by winlinvip** [comment]
What's the use scenario? What's the encoder and player for VP9?

**Comment by arpu** [comment]
playing videos vod and live (50% traffic with same quality (h264) 

encoder ffmpeg with libvp9 or google vp9 encoder 
player any dash player like dashjs https://github.com/Dash-Industry-Forum/dash.js/wiki

**Comment by arpu** [comment]
ok maybe srs is not for this use case (rtmp server) 

i can/will use icecast2 server with dash packager this should work fine
