### ISSUE TITLE
Raspberry Pi 3 Model B Segmentation Fault

### ISSUE THREAD

**Issue by bennnjamin** [ossrs/srs#880]
Still cannot run SRS. I can compile successfully but running gives a segfault. I have tried SRS1, SRS2, and SRS3. None of them run. 

I am using:
Raspbian Jessie
gcc 4.9.2
glibc 2.25

\# ./configure --pi --jobs=4
\# make -j4
\# ./objs/srs -c conf/realtime.conf
Segmentation Fault

I cannot find a way to downgrade glibc to older version.

**Comment by bennnjamin** [comment]
I found the solution, it is just not documented in ARM compilation.

# git checkout 3.0release
# ./configure && make

No need to use --pi flag. That is the problem.

**Comment by winlinvip** [comment]
The `--pi` is used for user to build SRS on raspberry-pi, so I think it's ok to use it.
The problem is the ST, SRS3 patched it for ARMv7. 

Please use SRS3 for ARMv7+, for instance PI3.
