### ISSUE TITLE
APPLICATION: SRS在Centos7.0上不能自启动

### ISSUE THREAD

**Issue by SunnyBoolean** [ossrs/srs#883]
按照官网说明，添加了init.id/srs链接，也sudo sbin/chkconfig srs,但是我重启Centos后srs并没有启动，请问是啥原因。

**Comment by winlinvip** [comment]
CENTOS7的启动脚本不再是init.d，需要针对CENTOS7重新写重启脚本。

**Comment by winlinvip** [comment]
你可看看如何支持。

**Comment by winlinvip** [comment]
Fixed.
