### ISSUE TITLE
Question: Can SRS live redirect streams without interruption?

### ISSUE THREAD

**Issue by hach-que** [ossrs/srs#886]
We are writing a client app that streams the contents of the user's desktop to a server on-demand.  We want the server to be serving an RTMP stream that rotates between connected streams throughout the day.

For example, in this setup:

- client1
- client2 (publishing an RTMP stream with ffmpeg to server)
- client3 (publishing an RTMP stream with ffmpeg to server)
- server (receiving RTMP streams and serving a single RTMP "view" stream)

We want to be able to interact with the server in the following ways:

- Ask the server for a list of connected clients (in this scenario, it should give client2 and client3)
- Ask the server to switch the view stream to a specific client

Importantly, there should be no interruption or delay when switching the view stream; for people watching the view stream is should appear to be continuous.  When we were trying out nginx RTMP server a while back, we found that requesting a live stream change would cause problems for viewers, which we don't want.

Can SRS do this sort of thing?

**Comment by winlinvip** [comment]
You can switch the stream on client-side(client2 or client3). I think it's fine and won't cause problem for client/viewers/players.

**Comment by hach-que** [comment]
What do you mean switch the stream on the client-side?  You mean have the client feed a different video into the same endpoint?

That won't work for our case.  Imagine a service like Twitch where you have a hundreds of people all streaming to their own channels, and you want to have a channel which rotates between each one every couple of minutes, while still being a single video stream.

**Comment by winlinvip** [comment]
Maybe you can try this:

```
Users => SRSA ====IngestController==> SRSB
```

For example:

1. UserA publish streamA to SRSA
1. UserB publish streamB to SRSA

Then config some ingesters at SRSB:

1. IngestA ingest streamA to SRSB as streamC

In this situation, streamA=>streamC and all players play streamC.

When you want to switch:

1. Change IngestA to ingest streamB to streamC
1. Reload SRSB.

Now, all players are watching streamB actually, without any interruption.

**Comment by winlinvip** [comment]
As all ingesters are using FFMPEG to pull stream from SRSA to SRSB, if there a huge number of streams, it's maybe need to be replaced, but I think it's fine for hundreds of streams, please do some benchmark.

Maybe you can implements your own ingester, to ingest huge streams and with detail business requirements, in this situation, you can add a SRS module to use the classes and objects of SRS to create a complex ingester, such as use the kernel and protocol module, to use RTMP protocol to read and write stream.

In a word, it's fine to use FFMEPG as ingester and you maybe need more complex ingester built from SRS module.
