### ISSUE TITLE
Forward能否实现转推到指定RTMP服务器

### ISSUE THREAD

**Issue by nightcoffee** [ossrs/srs#888]
Hi,
看了一下文档，目前Forward只是支持转到其他SRS上，是否能够支持 Client推流到SRS，SRS将该流Forward到N个RTMP服务器上？
比如nginx-rtmp的push功能，但是nginx无法平滑修改，如果push N个RTMP，在直播进行过程中修改其中任意RTMP服务器地址都需要全部停止。

**Comment by winlinvip** [comment]
可以试一试。

**Comment by z2690108** [comment]
So does it works?
