### ISSUE TITLE
[HLS][on_hls_notify] 是否可支援 vhost 標籤

### ISSUE THREAD

**Issue by jhaoheng** [ossrs/srs#890]
目前似乎只能支援

- [app]
- [stream]
- [ts_url]

不知是否可以支援 [vhost] 標籤的設定
在多個不同的 vhost 下，可以更方便的管理 感謝

**Comment by jhaoheng** [comment]
Hi 

目前我是寫死 uri
/__hostName__/[app]/[stream]/[ts_url]
也可得到類似功能

**Comment by winlinvip** [comment]
Please use English or Simplified Chinese.

You can use the `http_static` to support HTTP vhost, and use `[vhost]` as home dir for each vhost.
