### ISSUE TITLE
TS解析不正确

### ISSUE THREAD

**Issue by pbesedm** [ossrs/srs#893]
![image](https://cloud.githubusercontent.com/assets/1814190/26139786/9cf1ea30-3b05-11e7-9112-6bd9acb7c22c.png)

srs\_kernel\_ts.cpp

    1658: // (1+x)B
	1659: if (PES_extension_flag_2) {
	1660:    PES_extension_field_length = stream->read_1bytes();
	1661:    PES_extension_field_length &= 0x07;

1661 行的 PES\_extension\_field\_length &= 0x07; 不应该是 PES\_extension\_field\_length &= 0x7F; 吗？

**Comment by winlinvip** [comment]
👍 Yep, can you file a PR please?

**Comment by winlinvip** [comment]
Merged
