### ISSUE TITLE
srs_app_recv_thread.cpp 编译报错

### ISSUE THREAD

**Issue by chenliang2017** [ossrs/srs#895]
in file included from src/app/srs_app_rtmp_conn.cpp:51:0:
src/app/srs_app_recv_thread.hpp:233:5: error: ‘SrsResponseOnlyHttpConn’ does not name a type

使用方式：./configure --disable-all --with-ssl
系统环境：Linux vip 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:35 UTC 2017 i686 i686 i686 GNU/Linux

在srs_app_http_conn.hpp文件class SrsResponseOnlyHttpConn 在宏定义SRS_AUTO_HTTP_CORE中，
但是srs_app_recv_thread.hpp使用的时候没有加宏定义，编译出错

使用#ifdef SRS_AUTO_HTTP_SERVER包含SrsHttpRecvThread相关项后编译通过。

**Comment by winlinvip** [comment]
Fixed in SRS3. SRS2 won't fix it.
