### ISSUE TITLE
multiple inputs

### ISSUE THREAD

**Issue by jb-alvarado** [ossrs/srs#898]
Hello,
sorry when this is a stupid question, but I'm very new to srs.
Is it possible to have multiple inputs in srs. Do I need for this different ports, or works this with vhosts to?

**Comment by winlinvip** [comment]
You can config multiple ports to listen at, please read https://github.com/ossrs/srs/blob/2.0release/trunk/conf/full.conf#L9

**Comment by jb-alvarado** [comment]
Thanks!
