### ISSUE TITLE
passphrase to srs server and prioritize input streams 

### ISSUE THREAD

**Issue by jb-alvarado** [ossrs/srs#900]
Hello winlinvip,
is it possible to secure the srs server with an password or key? Other servers support something like:
`rtmp://user:password@example.com/live/livestream`

wowza has also a feature, that you can load a dummy clip and when your input stream fails it play this clip. And you also can stream a second clip with a higher priority, that replace the standard stream. 
For example: we have a 24/7 stream and sometime we have live events. This live event stream have a higher priority and when this starts, it replace the other streams. People who watch our stream have not to reload the page when the streams are changing, because they don't break the connecting.
Is this also possible with srs?

**Comment by jb-alvarado** [comment]
Ok, I found out that I can work with HTTPCallback.

`http_hooks {
		enabled         on;
		on_publish      http://127.0.0.1:8085/api/v1/streams http://localhost:8085/api/v1/streams;
	}
` 

I guess I have to use for this the python server, that is ok. I Also can grab with curl the client info and see there, if my publishing connection use the correct token:

`
"clients": [
        {
            "alive": 58.725,
            "id": 108,
            "ip": "188.192.47.86",
            "pageUrl": "",
            "publish": true,
            "stream": 53432,
            "swfUrl": "",
            "tcUrl": "rtmp://example.com:1934/live?key=123456789",
            "type": "fmle-publish",
            "url": "/live/tv",
            "vhost": 53431
        },
`
But how can I use this for automatic authentication? I could write a cronjob, but that sounds a bit strange to me.

**Comment by winlinvip** [comment]
You should write your API server like the python server, which is just a example.

**Comment by winlinvip** [comment]
BTW, it's the right solution to authenticate your user.

**Comment by jb-alvarado** [comment]
Ok thank you. When someone have the same problem, here is a little hack of the demo sever:
https://github.com/jb-alvarado/srs/blob/3.0release/trunk/research/api-server/server.py
I never write in python before, so I don't give grantee.
