### ISSUE TITLE
Sometimes  ‘Operation not permitted‘

### ISSUE THREAD

**Issue by jonahzheng** [ossrs/srs#905]
ffmpeg -re -ss 541.68 -i /opt/test.mp4 -r 15 -vcodec libx264 -preset veryfast -crf 35 -maxrate 1500k -bufsize 1500k -acodec libfaac -compression_level 3 -t 39.02 -f flv rtmp://21.21.222.221/live/test

Sometimes  ‘Operation not permitted‘

05-25-954e2b3 Copyright (c) 2000-2017 the FFmpeg developers
   built with gcc 4.9.2 (Debian 4.9.2-10)
   configuration: --enable-gpl --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvorbis --enable-libx264 --enable-nonfree --enable-postproc --enable-version3 --enable-librtmp --enable-libxvid --enable-libass --enable-libfreetype --enable-libfontconfig --enable-libfribidi --disable-yasm
   libavutil      55. 63.100 / 55. 63.100
   libavcodec     57. 96.101 / 57. 96.101
   libavformat    57. 72.101 / 57. 72.101
   libavdevice    57.  7.100 / 57.  7.100
   libavfilter     6. 90.100 /  6. 90.100
   libswscale      4.  7.101 /  4.  7.101
   libswresample   2.  8.100 /  2.  8.100
   libpostproc    54.  6.100 / 54.  6.100
 Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/opt/test.mp4':
   Metadata:
     major_brand     : isom
     minor_version   : 512
     compatible_brands: isomiso2avc1mp41
     encoder         : Lavf55.19.104
   Duration: 01:00:36.67, start: 0.000000, bitrate: 249 kb/s
     Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], 249 kb/s, 15 fps, 15 tbr, 15360 tbn, 30 tbc (default)
     Metadata:
       handler_name    : VideoHandler
 Stream mapping:
   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
 Press [q] to stop, [?] for help
 [libx264 @ 0x2906640] using SAR=1/1
 [libx264 @ 0x2906640] using cpu capabilities: none!
 [libx264 @ 0x2906640] profile High, level 3.1
 [libx264 @ 0x2906640] 264 - core 150 r2833 df79067 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=35.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=1500 vbv_bufsize=1500 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
 Output #0, flv, to 'rtmp://21.21.222.221/live/test':
   Metadata:
     major_brand     : isom
     minor_version   : 512
     compatible_brands: isomiso2avc1mp41
     encoder         : Lavf57.72.101
     Stream #0:0(und): Video: h264 (libx264) ([7][0][0][0] / 0x0007), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=-1--1, 15 fps, 1k tbn, 15 tbc (default)
     Metadata:
       handler_name    : VideoHandler
       encoder         : Lavc57.96.101 libx264
     Side data:
       cpb: bitrate max/min/avg: 1500000/0/0 buffer size: 1500000 vbv_delay: -1
 frame=    5 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
 frame=   13 fps= 13 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
 WriteN, RTMP send error 32 (140 bytes)
 WriteN, RTMP send error 32 (41 bytes)
 WriteN, RTMP send error 9 (42 bytes)
 **av_interleaved_write_frame(): Operation not permitted**
 **[flv @ 0x2905060] Failed to update header with correct duration.
 [flv @ 0x2905060] Failed to update header with correct filesize.**
 **Error writing trailer of rtmp://21.21.222.221/live/test: Operation not permitted**
 frame=   18 fps= 12 q=39.0 Lsize=      32kB time=-00:00:00.06 bitrate=N/A speed=N/A    
 video:37kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
 [libx264 @ 0x2906640] frame I:1     Avg QP:28.39  size: 37562
 [libx264 @ 0x2906640] frame P:5     Avg QP:34.36  size:  1280
 [libx264 @ 0x2906640] frame B:12    Avg QP:40.70  size:   262
 [libx264 @ 0x2906640] consecutive B-frames:  5.6% 11.1% 16.7% 66.7%
 [libx264 @ 0x2906640] mb I  I16..4: 40.8% 26.5% 32.7%
 [libx264 @ 0x2906640] mb P  I16..4:  0.6%  0.7%  0.1%  P16..4:  4.0%  1.3%  0.5%  0.0%  0.0%    skip:92.8%
 [libx264 @ 0x2906640] mb B  I16..4:  0.1%  0.1%  0.0%  B16..8:  1.3%  0.4%  0.0%  direct: 0.2%  skip:98.0%  L0:46.2% L1:46.0% BI: 7.8%
 [libx264 @ 0x2906640] 8x8 transform intra:28.4% inter:14.8%
 [libx264 @ 0x2906640] coded y,uvDC,uvAC intra: 47.9% 53.5% 24.8% inter: 0.4% 0.7% 0.0%
 [libx264 @ 0x2906640] i16 v,h,dc,p: 57% 24%  9% 10%
 [libx264 @ 0x2906640] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 26% 29%  3%  5%  3%  5%  3%  8%
 [libx264 @ 0x2906640] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 16% 34% 15%  3%  8%  4% 10%  2%  8%
 [libx264 @ 0x2906640] i8c dc,h,v,p: 53% 23% 19%  5%
 [libx264 @ 0x2906640] Weighted P-Frames: Y:0.0% UV:0.0%
 [libx264 @ 0x2906640] kb/s:314.08
 Conversion failed!

**Comment by winlinvip** [comment]
File issue to FFMPEG.
