### ISSUE TITLE
关于录制的功能

### ISSUE THREAD

**Issue by cl1069573062** [ossrs/srs#912]
1 关于录制，是否可以支持，通过发起一个开始录制的api，开始录制， 发起一个结束录制的api，结束录制。

**Comment by Chand-zhang** [comment]
按需录制。
这不是正常的直播里的功能，所以作者应该不会添加。
可以自己扩展。

**Comment by winlinvip** [comment]
用http callback，回调你的系统，你的系统知道什么时候要录制，就把流拉过去录制。
特殊业务逻辑不能在服务器做。
