### ISSUE TITLE
srs_string_ends_with有个小bug

### ISSUE THREAD

**Issue by hanlei0901** [ossrs/srs#915]
最近改造srs的时移播放器功能时，用到srs_string_ends_with
rfind没有检测返回值是不是-1
比如判断".."是否包含".ts"时就会返回真

改成下面了
bool srs_string_ends_with(string str, string flag)
{
	size_t find_ret = str.rfind(flag);
    return ((find_ret!=string::npos) && (find_ret == str.length() - flag.length()));
}

**Comment by winlinvip** [comment]
👍
