### ISSUE TITLE
ingest 拉流并转码的时候，源站断流，会有一定几率ffmpeg进程卡死

### ISSUE THREAD

**Issue by yanest** [ossrs/srs#922]
使用ingest进行拉流，如果这个时候源站突然断流，或者网络中断，会造成ffmpeg进程卡死，这个时候需要kill ffmpeg进程

**Comment by yanest** [comment]
上网查了一下，fmpeg用avformat_open_input()解析网络流时，默认是阻塞的。
当遇到解析错误的网络流时，会导致该函数长时间不返回。
为此可以设置ffmpeg的-stimeout 的参数。
srs能否加上此参数

**Comment by yanest** [comment]
很奇怪，尝试在ffmpeg中加这个参数却提示说不存在，不知道有没有判断超时的办法

**Comment by winlinvip** [comment]
如果拉FLV或HLS，可以用srs的库。
