### ISSUE TITLE
流密钥的简单保护

### ISSUE THREAD

**Issue by huanghe2015** [ossrs/srs#932]
用OBS推流时，流密钥和stream名称对应，如果在网页上播放HLS流，用IDM可以直接看到地址，进而看见流密钥，有点恐怖，不知今后会不会添加对stream进行简单保护的功能？例如在输出HLS和RTMP流时将stream名称进行MD5处理。本人拙见，望见谅。

**Comment by winlinvip** [comment]
Won't fix.
