### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by roneyrogerio** [ossrs/srs#933]
I currently use nginx with rtmp module, I have a python program that creates the ffmpe command, start and publish to rtmp, this python program is automatic started by nginx-rtmp and only start when my user connects to rtmp, but this functionality in nginx-rtmp does not work with hls/m3u8 .

Can I do the same with SRS? Is it possible to use my python program to connect ffmpeg? It is possible to connect the python program only when a user connects to streaming (even in hls/m3u8)?

**Comment by winlinvip** [comment]
Read http callbacks and exec of wiki.
