### ISSUE TITLE
http://ossrs.net:1985/console 这个console是否可以在自己的环境部署？

### ISSUE THREAD

**Issue by wuchuanbin** [ossrs/srs#935]
有没有开源这个控制台 内网想要在自己的环境中看下该如何使用？自己加工下http-api?

**Comment by wuchuanbin** [comment]
Looking forward to receiving a reply.

`TRANS_BY_GPT3`

**Comment by chundonglinlin** [comment]
no problem

**Comment by winlinvip** [comment]
Fork https://github.com/ossrs/srs-ngb
