### ISSUE TITLE
edge是否能在没有rtmp访问的情况下自动做HLS切片？

### ISSUE THREAD

**Issue by chenshaoze** [ossrs/srs#936]
您好，如题，edge貌似只有在通过rtmp拉流访问的时候才能进行hls切片，是否能通过配置开启edge默认hls切片？（作者为了节省服务器和带宽资源，仅当edge被访问时，才会去主服务器拉流，从而触发hls切片。）
目前我放弃了edge的配置，转而通过forward配置主从，从而实现所有服务器都能默认进行hls切片。但这种配置的缺点就是只能由配置了forward的服务器作为接收推流的服务器。
我看到作者在wiki中写道主从也可以是edge，但不推荐这么做。
求大神指导！

**Comment by notmark** [comment]
+1 this. We should be able to access HLS stream without having to request RTMP stream first.

**Comment by xushibo** [comment]
May I ask if Edge can be configured to allow customization of whether to automatically perform HLS slicing? In a cluster, if only mobile devices access it, they should only access HLS. However, currently, HLS streams are only generated when accessing Edge's RTMP or FLV streams, which is not conducive to cluster deployment.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
HLS slicing is a source station function.

`TRANS_BY_GPT3`
