### ISSUE TITLE
ffmpeg 2.1.1不支持h265视频

### ISSUE THREAD

**Issue by jinqilin721** [ossrs/srs#937]
您好。
srs最新版中使用的ffmpeg 版本号是 2.1.1 ，该版本不支持 h265，现很多摄像头都已经默认是 h265编码，能否升级一下版本？另：解压后更换3rdparty包下的ffmpeg包至最新版本能否正常安装？

**Comment by wnpllrzodiac** [comment]
应该可以，我自己改了升级到3.3.3，还加了外部库。搞不定联系我

**Comment by winlinvip** [comment]
可以用自己的FFMPEG代替SRS的2.1.1
