### ISSUE TITLE
关于Cluster：forward、edge、slave、master等的若干问题

### ISSUE THREAD

**Issue by juntaoliu** [ossrs/srs#938]
Hi， 
我用三个机器组成源站集群（1个master，2个slave），其它若干机器作为edge从源站拉流，可以wrok。使用的srs版本是2.0的最新版。有几个问题想请教一下大家：

1. 源站的集群虽然有三台机器，但push接收流只有master接收，这样，整个集群的push接收能力就受限于mster的单点了，单个srs服务器推流有上限（比如2k），那该源站集群只能同时服务2000路直播。实践中如何解决这个问题？

1.1 即使推流接入用的是Edge，分散终端压力，但最终还是会汇集到Master，一样有2k的推流上限限制，这个理解对吗？

2. Master和Slave组成简单的热备，当Master挂了的时候，Slave也无法收到推流了（因为Slave的流是Master通过forward转发过来的），这个时候，Edge即使连上Slave，也收不到rtmp的流，那么，其热备作用体现在哪儿？

3. 还是上一个问题，Edge的origin同时配置了上述三个源站IP，其中一个IP挂了的时候，会自动切换到下一个？切换的顺序是什么？轮询？还是可以配置？

4. Edge的origin配置了三个源站IP，分别是master， slave1， slave2. 然后如果推流的时候推给了Edge，Edge如何知道这三个origin哪个是Master？如果它挑选的那个不是Master，而是推给了比如slave2，这个时候流如何forward给master和slave1?

**Comment by winlinvip** [comment]
Origin cluster is not supported yet, please read #464

**Comment by winlinvip** [comment]
Origin Cluster is supported in SRS 3.0.

`TRANS_BY_GPT3`
