### ISSUE TITLE
http-flv下flv header出现问题

### ISSUE THREAD

**Issue by wxzcyy** [ossrs/srs#941]
当直播源没有视频或者音频时，拉下来的`http-flv`直播流`has audio`和`has vedio`都是1，即使在推流时使用`-an`禁掉视频或者音频还是这样

**Comment by winshining** [comment]
感觉是发送HTTP-FLV的时候，没有根据推流的音视频编码信息设置FLV头中对应的值

**Comment by winlinvip** [comment]
Dup to #939
