### ISSUE TITLE
2.0release在编译的时候出现异常

### ISSUE THREAD

**Issue by calmriver** [ossrs/srs#943]
2.0release版本，执行./configure --osx --without-ssl --without-hls --without-hds --without-dvr --without-nginx --without-http-callback --without-http-server --without-stream-caster --without-http-api --without-ffmpeg --without-transcode --without-ingest --without-stat --without-librtmp，然后make，出现如下错误：
<img width="883" alt="2017-07-20 19 11 37" src="https://user-images.githubusercontent.com/3891199/28415802-e64cd310-6d83-11e7-86b5-d4dffc45e66e.png">

**Comment by bruceshu** [comment]
我也出现了同样的问题，没人出来解答吗？

**Comment by M20170924** [comment]
（2.0稳定版本）以下步骤在我的macbook中编译并运行成功
1、cd srs/trunk （你的srs/trunk目录）
2、# 指定Mac编译，注意一下with是否开启（不确定是否所有的with都必须
<img width="631" alt="123" src="https://user-images.githubusercontent.com/32235793/31054804-171f2414-a6ed-11e7-9499-64f478b79340.png">
） 
./configure --osx --with-librtmp --with-ssl --with-hls --without-hds --without-dvr --with-nginx --with-http-callback --with-http-server --without-stream-caster --with-http-api --without-ffmpeg --without-transcode --without-ingest --without-stat
3、make

如未报错则成功
4、（此步骤未验证是否必须）；
Make成功后会提示：
You can:
      ./objs/srs -c conf/srs.conf
                  to start the srs server, with config conf/srs.conf.
我执行了一次 ./objs/srs -c conf/srs.conf

修改 srs/conf/srs.conf
由于Mac系统的限制，运行SRS的话需要把./conf/srs.conf中的并发数修改下，我修改成250: srs.conf中的这一行需要修改下：max_connections 240; 
注：系统最大允许256，根据max_connections值，srs启动后会增加8，即实际为max_connections+8，因此max_connections不能大于257


命令启动停止重启
1、cd srs/trunk
2、 1开始）    ./etc/init.d/srs start
       2停止）   ./etc/init.d/srs stop
       3重启）   ./etc/init.d/srs restart

**Comment by vainly** [comment]
@M20170924 我在mac的CLion中进行debug启动，没有报错，启动之后立马就停止了，不知为何
`
[2017-10-23 15:56:55.799][trace][13311][0] XCORE-SRS/2.0.243(ZhouGuowen)
[2017-10-23 15:56:55.802][trace][13311][0] config parse complete
[2017-10-23 15:56:55.804][trace][13311][0] write log to file ./objs/srs.log
[2017-10-23 15:56:55.804][trace][13311][0] you can: tailf ./objs/srs.log
[2017-10-23 15:56:55.804][trace][13311][0] @see: https://github.com/ossrs/srs/wiki/v1_CN_SrsLog
`

**Comment by M20170924** [comment]
debug只能通过命令行进行，不能直接使用xcode
https://casatwy.com/shi-yong-lldbdiao-shi-cheng-xu.html （页面中搜索：lldb调试之旅-调试某个正在运行中的进程）

**Comment by vainly** [comment]
@M20170924 可以在CLion中进行debug，刚才没有成功是因为在srs.conf中没有配置daemon。谢谢帮忙了。

**Comment by winlinvip** [comment]
推荐直接用`./configure && make`方式，有些开关选项可能有问题，来不及改了。。。
