### ISSUE TITLE
ffmpeg推流中断录制的flv文件metadata中duration字段异常

### ISSUE THREAD

**Issue by zzugyl** [ossrs/srs#945]
srs版本SRSv2.0.243
ffmpeg推流命令：
`ffmpeg -re -i "H:\baseline.mp4" -c copy -f flv rtmp://172.23.236.3:1935/live/1234567`
录制过程中加日志在[SrsFlvSegment::on_update_duration](https://github.com/ossrs/srs/blob/2.0release/trunk/src/app/srs_app_dvr.cpp#L479)
推流端按q退出推流。srs日志最后一段显示：
`
video  last_packet_time=11243
stream_previous_pkt_time=11243,duration=11243,stream_duration=11243
audio  last_packet_time=11261
end, stream_previous_pkt_time=11261,duration=11261,stream_duration=11261
video  last_packet_time=2147483630
stream_previous_pkt_time=2147483630,duration=2147483630,stream_duration=2147483630`

最后的2147483630是2^31-上一个pts值。录制的flv文件，其中duration字段值就是2147483630
然而真正的值应该是上一次的值11261。
多次试验，基本上都是这样。

**Comment by zhangketing** [comment]
I have also encountered similar situations. After stopping the recording, the values of append and duration remain the same as the previous segment, without updating. Additionally, there is repeated writing of metadata.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Fixed.

```
./objs/research/librtmp/srs_flv_parser html/live/livestream.09.28.40.flv
String onMetaData
Object (19 items)
    Property 'width' Number 768.0
    Property 'height' Number 320.0
    Property 'filesize' Number 430164.0
    Property 'duration' Number 10.9
```
