### ISSUE TITLE
求一个抓hls流的配置，我这么配置抓流异常

### ISSUE THREAD

**Issue by lizhi2013** [ossrs/srs#957]
ingest aaa {
        enabled      on;
        input {
             type stream;
             url  http://172.22.180.101:9000/hls/aaa.m3u8;

        }
       ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          off;
            output   rtmp://127.0.0.1:[port]/live?vhost=[vhost]/aaa;
        }
    }
出如下错误
Input #0, hls,applehttp, from 'http://172.22.180.101:9000/hls/aaa.m3u8':
  Duration: N/A, start: 265.418667, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 86 kb/s
[flv @ 0x263b860] Codec for stream 0 does not use global headers but container format requires global headers
[flv @ 0x263b860] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, flv, to 'rtmp://127.0.0.1:1935/live?vhost=xxxx/aaa':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p, 720x576 [SAR 64:45 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 90k tbc
    Stream #0:1: Audio: aac ([10][0][0][0] / 0x000A), 48000 Hz, stereo, 86 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[flv @ 0x263b860] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Invalid data found when processing input
[flv @ 0x263b860] Failed to update header with correct duration.
[flv @ 0x263b860] Failed to update header with correct filesize.
frame=    6 fps=0.0 q=-1.0 Lsize=      56kB time=00:00:00.18 bitrate=2530.1kbits/s    
video:55kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.657640%
Conversion failed!

**Comment by lizhi2013** [comment]
我自己搞定了 ，配置如下,主要是要启用ffmpeg的一些参数
 ingest aaa{
        enabled      on;
        input {
             type stream;
              url  http://172.22.180.101:9000/hls/aaa.m3u8;
        }
       ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          on;
            vcodec copy ;
            acodec  libfdk_aac;
            aparams {
                bsf:a   aac_adtstoasc;
                profile:a   aac_he_v2;
            }
        output   rtmp://127.0.0.1:[port]/live?vhost=[vhost]/ZJTV;
}
}

**Comment by WJZMC** [comment]
这个方法虽然可以，但是/api/v1/streams/获取到的状态是"publish":{"active":false,"cid":131}，有官方的解法吗？
