### ISSUE TITLE
服务器已经没有客户端播放和推流了，但是还有不少TCP连接存在。（版本2.0）

### ISSUE THREAD

**Issue by lmxuwork** [ossrs/srs#960]
什么情况下，连接不会断开呢

**Comment by juntaoliu** [comment]
TCP's TIME_WAIT? The side that initiates the active closure of a TCP connection needs to enter the TIME_WAIT state, as required by the TCP protocol itself.

You can set the TIME_WAIT time in the system kernel, make it shorter.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@juntaoliu Good job, thanks!
