### ISSUE TITLE
http server not displaying

### ISSUE THREAD

**Issue by zameelpichen** [ossrs/srs#963]
what can i do, please help

**Comment by juntaoliu** [comment]
flv? m3u8?
First, you should describe the context and what you want.

**Comment by zhuleiandy888** [comment]
maybe the flash plug-in is blocked by the  browser （Chrome ...）

**Comment by zameelpichen** [comment]
sorry, i want the html page to display at :8888
but this is not happening.

the browser say, it refuses to connect.

can you tell me how to start and stop the server? i started it using the guidelines, but i cant see anywhere how to stop it.
Thanks a lot for the quick response.

**Comment by juntaoliu** [comment]
if you install it as what wiki described, you can : 

start it: service srs start
restart it: service srs restart
stop it: service srs stop

For the flv play, you should use a conf file like the following:

# the config for srs to remux rtmp to flv live stream.
# @see https://github.com/ossrs/srs/wiki/v2_CN_DeliveryHttpStream
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}
vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
        hstrs       on;
    }
}

Then you can play it with a url like: http://youripaddress:8080/app/stream.flv

**Comment by winlinvip** [comment]
Fixed
