### ISSUE TITLE
How to customize m3u8?

### ISSUE THREAD

**Issue by thisroot** [ossrs/srs#971]
I many thought about how to time suncronize two video stream on a one client. 
Perhaps to customize write data and add chunc timestumps into m3u8. Onwards add to video player function which will sunchronize two HLS streams on a one client.

I want to experiments with this idea. Please tell me where find in srs code sections which responsible for write into m3u8

**Comment by winlinvip** [comment]
Read `hls_m3u8_file `, `hls_ts_file ` and `hls_path ` at https://github.com/ossrs/srs/wiki/v2_EN_DeliveryHLS#hls-configuration
