### ISSUE TITLE
forward功能是否只支持ip地址，不支持域名？

### ISSUE THREAD

**Issue by pudd** [ossrs/srs#972]
2.0版本，官方实例中的forward本地转发可以成功跑通，但是尝试使用forward功能推去国外的直播平台
时报错，转发配置如下：

vhost __defaultVhost__ {
    forward      live-hkg.twitch.tv/app/live_172181393_wo5eRCtzWSrv8gPbfTnK5FMXyXyaHA;
}

日志提示失败，报错中有dns的无法解析的提示
[2017-09-04 18:06:15.750][error][1767][108][0] dns resolve server error, ip empty. ret=1029

有劳各位解答，谢谢！

**Comment by xialixin** [comment]
Forward cannot include app and stream. Just write the IP or domain name.
vhost defaultVhost {
forward live-hkg.twitch.tv;
This should work, you can give it a try.

`TRANS_BY_GPT3`

**Comment by pudd** [comment]
@xialixin Thank you!
So does this mean that it is not possible to bring the app and stream together? Or are there other syntaxes that can be used?

`TRANS_BY_GPT3`

**Comment by xialixin** [comment]
Unable to bring app and stream together, SRS will forward all apps and streams to the specified address. If you only want to forward specific streams, you need to modify the code yourself.

`TRANS_BY_GPT3`

**Comment by pudd** [comment]
Thank you very much, but I'm not sure if I misunderstood.

The meaning of my previous question is **not** whether SRS can specify a certain app and stream to forward, but whether it can forward to a specified app and stream on the target server.

However, for now, I have used ffmpeg to forward the local stream, temporarily solving the business problem: )

`TRANS_BY_GPT3`

**Comment by xialixin** [comment]
In this case, you can only push the stream to SRS, also according to your app and stream name, or use your current method, using ffmpeg to convert it.

`TRANS_BY_GPT3`
