### ISSUE TITLE
使用ingest.conf 配置海康的摄像头rtsp地址。ffmpeg拉流报错。

### ISSUE THREAD

**Issue by stavid** [ossrs/srs#975]
UDP timeout, retrying with TCP
[rtsp @ 0x2599900] method PAUSE failed: 551 Option not supported
[rtsp @ 0x2599900] Could not find codec parameters for stream 0 (Video: h264): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
rtsp://192.168.1.100:4822/MPEG-4/ch1/main/av_stream: could not find codec parameters

ffmpeg cid=103
log=./objs/ffmpeg-ingest-__defaultVhost__-live-livestream.log
params: ./objs/ffmpeg/bin/ffmpeg -i rtsp://192.168.1.100:4822/MPEG-4/ch1/main/av_stream -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1:1935/live?vhost=__defaultVhost__/livestream
ffmpeg version 2.1.1 Copyright (c) 2000-2013 the FFmpeg developers
  built on Sep  7 2017 10:13:34 with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --enable-gpl --enable-nonfree --yasmexe=/root/srs/trunk/objs/ffmpeg.src/_release/bin/yasm --prefix=/root/srs/trunk/objs/ffmpeg.src/_release --cc= --enable-static --disable-shared --disable-debug --extra-cflags='-I${ffmpeg_exported_release_dir}/include' --extra-ldflags='-L${ffmpeg_exported_release_dir}/lib -lm -ldl' --disable-ffplay --disable-ffprobe --disable-ffserver --disable-doc --enable-postproc --enable-bzlib --enable-zlib --enable-parsers --enable-libx264 --enable-libmp3lame --enable-libfdk-aac --enable-libspeex --enable-pthreads --extra-libs=-lpthread --enable-encoders --enable-decoders --enable-avfilter --enable-muxers --enable-demuxers
  libavutil      52. 48.101 / 52. 48.101
  libavcodec     55. 39.101 / 55. 39.101
  libavformat    55. 19.104 / 55. 19.104
  libavdevice    55.  5.100 / 55.  5.100
  libavfilter     3. 90.100 /  3. 90.100
  libswscale      2.  5.101 /  2.  5.101
  libswresample   0. 17.104 /  0. 17.104
  libpostproc    52.  3.100 / 52.  3.100

**Comment by deqoder** [comment]
It is because Hikvision cameras do not support UDP. By default, ffmpeg uses UDP. To resolve this, you need to add the option "-rtsp_transport tcp" (ffmpeg's command line option).

`TRANS_BY_GPT3`

**Comment by scai2013** [comment]
How can I add -rtsp_transport tcp in ingest.conf? Is there a solution for this?

`TRANS_BY_GPT3`

**Comment by scai2013** [comment]
<pre>
vhost __defaultVhost__ {
    ingest livestream {
        enabled      on;
        input {
            type    stream;
            url     rtsp://admin:12345@111.113.3.154:10004/h264/ch1/main/av_stre
am;
        }
        ffmpeg     '/usr/local/srs/srsr2/trunk/objs/ffmpeg/bin/ffmpeg -f rtsp -r
tsp_transport tcp'; //**String declaration
        engine {
                        enabled          on;
			vcodec          copy;
			acodec          aac;
             		aparams{
				ab          96000;
				strict          experimental;
				ac          2;		
			}
              output          rtmp://127.0.0.1:1935/live/zb3;
        }
    }
}
</pre>
I found that this declaration can include the parameter 'tcp', but it also reports other issues:
<pre>
params: /usr/local/srs/srsr2/trunk/objs/ffmpeg/bin/ffmpeg -f rtsp -rtsp_transport tcp -i rtsp://admin:12345@111.113.3.154:10004/h264/ch1/main/av_stream -vcodec copy -acodec aac -ab 96000 -strict experimental -ac 2 -f flv -y rtmp://127.0.0.1:1935/live/zb3
fork ffmpeg failed, errno=2(No such file or directory)
ffmpeg cid=105
log=./objs/ffmpeg-ingest-__defaultVhost__-live-zb3.log
params: /usr/local/srs/srsr2/trunk/objs/ffmpeg/bin/ffmpeg -f rtsp -rtsp_transport tcp -i rtsp://admin:12345@111.113.3.154:10004/h264/ch1/main/av_stream -vcodec copy -acodec aac -ab 96000 -strict experimental -ac 2 -f flv -y rtmp://127.0.0.1:1935/live/zb3
fork ffmpeg failed, errno=2(No such file or directory)


</pre>

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This means ffmpeg does not exist. Are you sure the path is correct? Can you execute this command directly?

`TRANS_BY_GPT3`

**Comment by lincoln24** [comment]
题主问题解决了吗？我现在也是打算接入海康摄像头，ingest.conf中直接写了rtsp流地址，推到SRS上也是看不了，一直提示client disconnect peer. ret=1004，文件如下
`listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;
vhost __defaultVhost__ {
    ingest livestream {
        enabled      on;
        input {
            type    stream;
            url     rtsp://admin:admin123456@10.112.17.145:554;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg -f rtsp -rtsp_transport tcp;
        engine {
            enabled          off;
            output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
}
`

**Comment by OpenBodhi** [comment]
Hello, I also encountered this problem. Have you solved it? Can you guide me?

`TRANS_BY_GPT3`

**Comment by yangxiaoxie** [comment]
I have encountered the same problem, please guide me.

`TRANS_BY_GPT3`

**Comment by kongling** [comment]
You need to first confirm whether the address of this stream is available or not. Try opening it with VLC to see if it can play. Generally, for Hikvision cameras, you need to add the username and password in the address bar (similar to: rtsp://admin:xxxx@192.168.0.25/ch1/.......). Alternatively, you can receive the RTSP stream from an NVR.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
@kongling 👍 Thanks.
