### ISSUE TITLE
RTMP DVR configuration not working for me

### ISSUE THREAD

**Issue by swgmstr** [ossrs/srs#976]
Hi, 

I have been trying to turn ON the DVR feature to record a live RTMP stream from an android device. I am using VLC as my player and the live stream works but I am having trouble with the DVR feature.

I build the program with command: ./configure --with-dvr --with-ffmpeg --with-ingest && make
The feature says it is ON once I build it.  

 But no video file is saving to the default dvr_path:  ./objs/nginx/html 

What should I do so that the DVR feature works and saves the video file to the default path? 

Do i need to edit any of these files? full.conf file, dvr.path.conf, dvr.session.conf, dvr.segment.conf

**Comment by Charlyhash** [comment]
Do you solve this problem? 
can't enable vhost.dvr of __defaultVhost__

**Comment by winlinvip** [comment]
Follow DVR wiki.
