### ISSUE TITLE
使用Release的srs-2.0-r2版本演示页面脚本错误

### ISSUE THREAD

**Issue by canglongxiang** [ossrs/srs#979]
CentOS6.9，使用的srs-2.0-r2版本，按照wiki里说的运行demo后，出现了以下两个截图所示的问题。
![srs_player_error_1](https://user-images.githubusercontent.com/5906745/30306901-6a5f986a-97ad-11e7-89b0-a2afba8a64b4.png)
![srs_player_error_2](https://user-images.githubusercontent.com/5906745/30306904-71c2d806-97ad-11e7-840f-9a06f3f0c5c9.png)

**Comment by XiaoWind** [comment]
chrome要先允许flash权限

**Comment by ntnyq** [comment]
我昨天也遇到了这个问题。。。

Chrome禁用了flash。

**Comment by winlinvip** [comment]
Fixed。
