### ISSUE TITLE
测速的时候一直无法正常握手

### ISSUE THREAD

**Issue by MAYDAYHAO** [ossrs/srs#985]
不知道是不是我的地址格式问题。 rtmp://ip/live:1935/app?key:xxx,vhost:xxx这样的格式我试过了不行，不带live，直接ip:端口/app也不行。key跟vhost是默认的。

**Comment by MAYDAYHAO** [comment]
Reason: The firewall has not been closed yet.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
The RTMP speed test feature is no longer supported in SRS 4.0.

`TRANS_BY_GPT3`
