### ISSUE TITLE
SrsSource析构coredump

### ISSUE THREAD

**Issue by fantasyARM** [ossrs/srs#986]
srs_kernel_codec.cpp  LINE:567 把acodec 传递到audio对象内部，造成的double free。
， srs_kernel_codec.cpp LINE:420行的free去掉，这个对象是外部传进来的，生命周期由外部管理，不应该在SrsFrame析构的时候free 它。【bug】

**Comment by ynchsung** [comment]
Previously, when cleaning up SrsSource, it is possible that a premature free occurred, but other coroutines continued to use that memory, causing the process to crash.
(https://github.com/ossrs/srs/issues/713)
Would using std::shared_ptr for these pointers solve the problem? When using this type of pointer, there is no need to free the memory manually. When there are no pointers pointing to that memory, the library will automatically free it. This can solve the issue of double free or premature free.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
SRS2 or SRS3?

**Comment by winlinvip** [comment]
Dup to #1579
