### ISSUE TITLE
xcode编译源码错误：Unknown OS

### ISSUE THREAD

**Issue by M20170924** [ossrs/srs#992]
编译后srs服务已经能够正常运行
但是打开ide中srs_xcode中编译错误
In file included from /Users/tt/Documents/GitHub/srs-2.0-r2/trunk/objs/st-1.9/stk.c:47:
In file included from /Users/tt/Documents/GitHub/srs-2.0-r2/trunk/objs/st-1.9/common.h:68:
/Users/tt/Documents/GitHub/srs-2.0-r2/trunk/objs/st-1.9/md.h:607:2: error: Unknown OS
#error Unknown OS
 ^
In file included from /Users/tt/Documents/GitHub/srs-2.0-r2/trunk/objs/st-1.9/stk.c:47:
/Users/tt/Documents/GitHub/srs-2.0-r2/trunk/objs/st-1.9/common.h:429:2: error: Unknown OS
#error Unknown OS
 ^
/Users/tt/Documents/GitHub/srs-2.0-r2/trunk/objs/st-1.9/stk.c:139:2: error: Unknown OS
#error Unknown OS
 ^
3 errors generated.

**Comment by winlinvip** [comment]
不支持xcode编译，xcode可以用来编辑代码，用configure和make编译，用lldb和gdb调试。
