### ISSUE TITLE
How configure __defaultVhost__ to domain_name

### ISSUE THREAD

**Issue by thisroot** [ossrs/srs#993]
Hi, I can't understand how to bind `__defaultVhost__` variable to domain name?
- now I have binded `__defaultVhost__` to server `IP address`  - and it works for me.

**Comment by juntaoliu** [comment]
You should modify the code to support it. SRS does not support it now.

**Comment by winlinvip** [comment]
You can add some vhosts such as:

```
vhost a.domain.com {
}

vhost b.domain.com {
}

vhost xxx.net {
}
```

Please read wiki https://github.com/ossrs/srs/wiki/v1_EN_RtmpUrlVhost
