### ISSUE TITLE
HTTP callbacks fail for HTTP 30X

### ISSUE THREAD

**Issue by mastashake08** [ossrs/srs#995]
I'm trying to call an external api on the on_connect method but it fails everytime no matter the URL. If I cURL the same URL it works perfect. Any suggestions?

**Comment by juntaoliu** [comment]
The url called by on_connect should return one of the following results: 1) return a body, only with the number "0"; 2) return json encode body, which has a key named after "code" and its value is  number "0".

Any other return will be treated as failure.

**Comment by mastashake08** [comment]
Even when I return "0" I get this
[2017-10-17 15:26:37.064][error][8356][107][11] invalid response
status=301. ret=4005(Resource temporarily unavailable)
[2017-10-17 15:26:37.064][error][8356][107][11] http post on_connect uri
failed. client_id=107, url=https://blaqswan.com/api/connect,
request={"action":"on_connect","client_id":107,"ip":"174.97.201.249","vhost":"__defaultVhost__","app":"live","tcUrl":"rtmp://
198.199.100.59:1935/live","pageUrl":""}, response=<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
, code=301, ret=4005(Resource temporarily unavailable)
[2017-10-17 15:26:37.064][error][8356][107][11] hook client on_connect
failed. url=https://blaqswan.com/api/connect, ret=4005(Resource temporarily
unavailable)
[2017-10-17 15:26:37.065][error][8356][107][11] check vhost failed.
ret=4005(Resource temporarily unavailable)

The API URL is https://blaqswan.com/api/connect

*Jyrone Parker*
*Technical Consultant, *Technopreneur

*Never Let Limited Minds Limit Your Success*
*https://www.jyroneparker.com <http://www.jyroneparker.com> |
https://youtube.com/c/jyroneparker <https://youtube.com/c/jyroneparker>*
Twitter: @mastashake08

**Comment by misiek08** [comment]
You have redirection in your endpoint and srs won't follow redirects. You
have to double check if your website answers directly to srs.

17.10.2017 6:15 PM "Jyrone Parker" <notifications@github.com> napisał(a):

**Comment by mastashake08** [comment]
That makes no sense like I said if I do a cURL request or use postman or
the like it's returning perfectly. No redirects it's literally return 0 I'm
just trying to test.

*Jyrone Parker*
*Technical Consultant, *Technopreneur

*Never Let Limited Minds Limit Your Success*
*https://www.jyroneparker.com <http://www.jyroneparker.com> |
https://youtube.com/c/jyroneparker <https://youtube.com/c/jyroneparker>*
Twitter: @mastashake08

**Comment by misiek08** [comment]
In log you posted there is 301 redirect...

Run cURL with -vv flag to see all operations and if it's possible share
cURL log.

23.10.2017 21:58 "Jyrone Parker" <notifications@github.com> napisał(a):

> That makes no sense like I said if I do a cURL request or use postman or
> the like it's returning perfectly. No redirects it's literally return 0 I'm
> just trying to test.
>
> *Jyrone Parker*
> *Technical Consultant, *Technopreneur
>
> *Never Let Limited Minds Limit Your Success*
> *https://www.jyroneparker.com <http://www.jyroneparker.com> |
> https://youtube.com/c/jyroneparker <https://youtube.com/c/jyroneparker>*
> Twitter: @mastashake08
>
>

**Comment by mastashake08** [comment]
This is from OSSRS Logs and then below it is the cURL logs
[2017-10-30 17:16:19.003][error][18185][109][11] invalid response
status=301. ret=4005(Resource temporarily unavailable)
[2017-10-30 17:16:19.003][error][18185][109][11] http post on_connect uri
failed. client_id=109, url=https://blaqswan.com/api/connect,
request={"action":"on_connect","client_id":109,"ip":"174.97.201.249","vhost":"__defaultVhost__","app":"live","tcUrl":"rtmp://
198.199.100.59/live","pageUrl":""}, response=<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
, code=301, ret=4005(Resource temporarily unavailable)
[2017-10-30 17:16:19.003][error][18185][109][11] hook client on_connect
failed. url=https://blaqswan.com/api/connect, ret=4005(Resource temporarily
unavailable)
[2017-10-30 17:16:19.003][error][18185][109][11] check vhost failed.
ret=4005(Resource temporarily unavailable)


CURL
mastashake08@mastashake08-laptop:~/Desktop/android-studio/bin$ curl -vv -X
POST  https://blaqswan.com/api/connect/
*   Trying 104.131.14.89...
* TCP_NODELAY set
* Connected to blaqswan.com (104.131.14.89) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection:
ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=blaqswan.com
*  start date: Oct 29 18:09:33 2017 GMT
*  expire date: Jan 27 18:09:33 2018 GMT
*  subjectAltName: host "blaqswan.com" matched cert's "blaqswan.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> POST /api/connect/ HTTP/1.1
> Host: blaqswan.com
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-cache, private
< Date: Mon, 30 Oct 2017 17:14:29 GMT
< X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 59
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
<
* Curl_http_done: called premature == 0
* Connection #0 to host blaqswan.com left intact


*Jyrone Parker*
*Technical Consultant, *Technopreneur

*Never Let Limited Minds Limit Your Success*
*https://www.jyroneparker.com <http://www.jyroneparker.com> |
https://youtube.com/c/jyroneparker <https://youtube.com/c/jyroneparker>*
Twitter: @mastashake08

**Comment by winlinvip** [comment]
SRS doesn't follow HTTP30X. Maybe fixed in SRS3.

**Comment by mastashake08** [comment]
I will try thanks

**Comment by mastashake08** [comment]
I was trying to call https that was the issue. When will this be addressed?
