### ISSUE TITLE
编译fdk-aac时报错

### ISSUE THREAD

**Issue by li2251421** [ossrs/srs#999]
libAACenc/src/aacEnc_rom.cpp:674:1: 错误：在 {} 内将‘2229462401u’从‘unsigned int’转换为较窄的类型‘FIXP_DBL {aka int}’ [-Wnarrowing]

具体代码在  fdk-aac-0.1.3/libAACenc/src/aacEnc_rom.cpp：
const  FIXP_DBL FDKaacEnc_tnsEncCoeff3[8]=
{
  0x81f1d201, 0x91261481, 0xadb92301, 0xd438af00, 0x00000000, 0x37898080, 0x64130dff, 0x7cca6fff
};
大概知道原因，但是不知该怎么修改

**Comment by li2251421** [comment]
FIXP_DBL == int ?
这个不是很明白，没搞过c++

**Comment by li2251421** [comment]
看了fdk-0.1.5的源码，发现修复了这个问题：
const FIXP_DBL FDKaacEnc_tnsEncCoeff3[8]=
{
  (FIXP_DBL)0x81f1d201, (FIXP_DBL)0x91261481, (FIXP_DBL)0xadb92301, (FIXP_DBL)0xd438af00, (FIXP_DBL)0x00000000, (FIXP_DBL)0x37898080, (FIXP_DBL)0x64130dff, (FIXP_DBL)0x7cca6fff
};

**Comment by li2251421** [comment]
这个错误应该是跟本机的编译环境有关的 gcc/gcc-c++

**Comment by winlinvip** [comment]
FFMPEG的问题。
